WalletWasabi/WalletWasabi

src/HiddenWallet/UI/WindowConfig.cs
=> Fix(#13): Fixes the configuration not being applied after a modification by the UI

README.md
=> Readme fix  - mentioning tor expert bundle

HiddenWallet.ChaumianTumbler/Controllers/TumblerController.cs, HiddenWallet.ChaumianTumbler/HiddenWallet.ChaumianTumbler.csproj, HiddenWallet.ChaumianTumbler/Models/PhaseChangeBroadcast.cs, HiddenWallet.ChaumianTumbler/Properties/launchSettings.json, HiddenWallet.ChaumianTumbler/Startup.cs, HiddenWallet.ChaumianTumbler/TumblerHub.cs, HiddenWallet.ChaumianTumbler/TumblerPhaseBroadcaster.cs, HiddenWallet.ChaumianTumbler/TumblerStateMachine.cs, HiddenWallet.ChaumianTumbler/Views/Tumbler/ClientTest.cshtml, HiddenWallet.ChaumianTumbler/Views/Tumbler/ClientTest.cshtml.cs
Have also added a call to the Broadcaster within TumblerstateMachine.UpdatePhase.
You can test by running - it will fire up a test html page with javascript to connect to client and a way to fire a broadcast back to the clients.
=> Added SignalR Hub and TumblerPhaseBroadcaster. 

HiddenWallet.Gui/app/js/broadcast-window.ts, HiddenWallet.Gui/app/js/cleanup.ts, HiddenWallet.Gui/app/js/decryption-phase.ts, HiddenWallet.Gui/app/js/default.ts, HiddenWallet.Gui/app/js/hw-client.ts, HiddenWallet.Gui/app/js/settings.ts, HiddenWallet.Gui/app/js/status.ts, HiddenWallet.Gui/app/js/wallet-phase.ts, HiddenWallet.Gui/main.ts
To compile after a get of this code: within the HiddenWallet.GUI folder run:
tsc
...which will compile the ts to js. Then run as normal using npm start. I have also made a change so you can also run with the debug window open (to debug the outputted javascript etc if you want). To do this just use:
npm start dev
This has been fully tested, new wallet, regen, load existing, send tx, shutdown etc - the only thing I haven't tested is the code in one function of default.ts as it references the dropbtn class which I can't see used in the Master branch.
This one: 
window.onclick = function (mouseEvent: MouseEvent) { 
let eventTarget: HTMLElement = mouseEvent.target as HTMLElement;
if (eventTarget.className !== 'dropbtn') {
..etc
}
=> TypeScript typing added.

HiddenWallet.Daemon/Controllers/WalletController.cs, HiddenWallet.Gui/app/html/wallet-content.html, HiddenWallet.Gui/app/html/wallet-phase-tabs.html, HiddenWallet.Gui/app/js/default.ts, HiddenWallet.Gui/app/js/wallet-phase.ts, HiddenWallet/ChaumianCoinJoin/Models/StatusResponse.cs
Second stage (which I'm now working on) will include integration to Server through client and any changes to the gui following review.
I have made a best guess as to the fileds we need to show in the mixing UI. Happy to change and remove/add more.
NEXT STEPS:
**Integrate with client/server:**
A new method I will add in WalletWrapper.cs called by the controller that calls...
CoinJoinService.GetStatusAsync which I will add that calls...
ChaumianTumblerClient.GetStatusAsync which already exists that calls...
(server) ChaumianTumbler.TumblerController.Status which already exists
**When they click 'Begin Mixing' button it will:**
Call a new MVC action I will add in the Daemon called 'tumble' which calls...
A new method I will add in WalletWrapper.cs that calls...
CoinJoinService.TumbleAsync …
=> Initial Commit - html and ts added to support mixer tab. 

HiddenWallet.Documentation/TestingTheZeroLinkMixer.md
=> fix small typo

WalletWasabi/Logging/Logger.cs
This PR improves a bit the logs by using one line by entry approach and adding colors when they go through the standard output.
=> Log improvements

WalletWasabi.Tests/RegTests.cs
This superseeds the PR: https://github.com/zkSNACKs/WalletWasabi/pull/159
=> Add more coin tests

.gitignore, WalletWasabi.Backend/Controllers/ChaumianCoinJoinController.cs, WalletWasabi.Backend/Global.cs, WalletWasabi.Backend/Startup.cs, WalletWasabi.Tests/KeyManagementTests.cs, WalletWasabi.Tests/P2pTests.cs, WalletWasabi.Tests/RegTestFixture.cs, WalletWasabi.Tests/RegTests.cs, WalletWasabi.Tests/TorTests.cs, WalletWasabi/ChaumianCoinJoin/CcjRound.cs, WalletWasabi/ChaumianCoinJoin/CcjRoundConfig.cs, WalletWasabi/Crypto/BlindingRsaKey.cs, WalletWasabi/Crypto/BlindingRsaPubKey.cs, WalletWasabi/Models/Height.cs, WalletWasabi/Services/CcjCoordinator.cs, WalletWasabi/Services/ConfigWatcher.cs, WalletWasabi/Services/IndexBuilderService.cs, WalletWasabi/Services/UtxoReferee.cs
So far this DoS protection only implements severity 1.
=> [WIP] Implement DoS protection

WalletWasabi.Backend/Controllers/BlockchainController.cs, WalletWasabi.Tests/P2pTests.cs, WalletWasabi.Tests/RegTests.cs, WalletWasabi/Services/IndexBuilderService.cs, WalletWasabi/Services/IndexDownloader.cs
=> Prevent unbound filter requests (fix tests)

.travis.yml, appveyor.yml
Reverts zkSNACKs/WalletWasabi#193
=> Revert "Re-enable CI cache"

.travis.yml, appveyor.yml
Reverts zkSNACKs/WalletWasabi#194
=> Revert "Revert "Re-enable CI cache""

WalletWasabi.Tests/RegTests.cs, WalletWasabi/Services/CcjCoordinator.cs
@nopara73 please **REVIEW** i am trying to understand all the interactive involved in the CoinJoin with the blind signatures an the components so, i don't know if what I did is okay.
I am trying to cover the code that is not covered by the unit tests.
=> Some test lines for CcjCoordinator class

WalletWasabi.UI/Desktop/App.xaml, WalletWasabi.UI/Desktop/App.xaml.cs, WalletWasabi.UI/Desktop/Program.cs, WalletWasabi.UI/Desktop/Themes/Theme.xaml, WalletWasabi.UI/Desktop/ViewLocator.cs, WalletWasabi.UI/Desktop/ViewModels/MainWindowViewModel.cs, WalletWasabi.UI/Desktop/ViewModels/ViewModelBase.cs, WalletWasabi.UI/Desktop/Views/MainWindow.xaml, WalletWasabi.UI/Desktop/Views/MainWindow.xaml.cs, WalletWasabi.UI/Desktop/WalletWasabi.UI.Desktop.csproj
This PR contains an AvaloniaUI projects with a layout to discuss. This is almost the standard MVVM application template as it comes with the VS extension. However, given I use vscode on Linux I did it without template. (Basically, it helped me to do a quick tutorial about Avalonia)
=> First UI skeleton

WalletWasabi.Tests/RegTests.cs, WalletWasabi/Services/CcjClient.cs
This PR signs a transaction using the NBitcoin's `TransactionBuilder.BuildTransaction` method.
=> Sign transaction

WalletWasabi/Models/ChaumianCoinJoin/Alice.cs, WalletWasabi/Models/ChaumianCoinJoin/Bob.cs
This PR removes the outputs size verification as requested in this another PR comment https://github.com/zkSNACKs/WalletWasabi/pull/217#issuecomment-390460075
=> Removes scriptPubkey length checks

WalletWasabi.Tests/ExternalApiTests.cs, WalletWasabi.Tests/RegTests.cs, WalletWasabi.Tests/XunitConfiguration/RegTestFixture.cs, WalletWasabi/Models/ChaumianCoinJoin/CcjRound.cs, WalletWasabi/Models/ChaumianCoinJoin/CcjRoundConfig.cs, WalletWasabi/Services/CcjClient.cs
Simplified all instances of Money being created from a decimal type
See also: #161
=> Simplified the creation of Money instances from decimal types

WalletWasabi/Services/CcjCoordinator.cs
There was a code error because we try to remove elements while iterate a collection. Previously, this didn't happen because the `string.IsNullOrWhiteSpace(getRawTransactionResponse?.ResultString)` is always `false`.
=> Fixes issue 223

WalletWasabi/Logging/Logger.cs
=> Uses 24hrs time format

WalletWasabi.Backend/Controllers/OffchainController.cs, WalletWasabi/Helpers/EnvironmentHelpers.cs, WalletWasabi/Helpers/HttpMessageHelper.cs, WalletWasabi/KeyManagement/HdPubKey.cs, WalletWasabi/KeyManagement/KeyManager.cs, WalletWasabi/Logging/Logger.cs, WalletWasabi/Services/IndexDownloader.cs
This PR reduces the level of indentations for readability.
=> Add some small simplifications

WalletWasabi.Backend/Global.cs, WalletWasabi/Helpers/HttpMessageHelper.cs, WalletWasabi/Services/CcjClient.cs, WalletWasabi/Services/WalletService.cs
This PR removes the string interpolation when they are no needed.
=> Remove redundant string interpolation

WalletWasabi/Helpers/HttpMessageHelper.cs, WalletWasabi/WebClients/ChaumianCoinJoin/AliceClient.cs
This PR contains two very simple improvements.
=> Simplify for loops

WalletWasabi.Backend/Global.cs, WalletWasabi/Extensions/HttpRequestMessageExtensions.cs, WalletWasabi/Extensions/HttpResponseMessageExtensions.cs, WalletWasabi/Helpers/HttpMessageHelper.cs
This PR removes unused variables, just that.
=> Remove unused local variables

WalletWasabi.Tests/ExternalApiTests.cs, WalletWasabi/Backend/Models/FilterModel.cs, WalletWasabi/Exceptions/TorSocks5FailureResponseException.cs, WalletWasabi/Http/Models/HttpProtocol.cs, WalletWasabi/Http/Models/RequestLine.cs, WalletWasabi/Http/Models/StatusLine.cs
This PR contains 2 trivial changes for readability.
=> Remove redundant tostring

WalletWasabi/Bases/ByteArraySerializableBase.cs, WalletWasabi/Bases/OctetSerializableBase.cs, WalletWasabi/Interfaces/IByteArraySerializable.cs, WalletWasabi/Interfaces/IByteSerializable.cs
In this PR I did what @nopara73 requested: remove those methods that were hiding other overloaded methods. Removing them had no side effects.
=> Removes methods that hide others

WalletWasabi/Helpers/ByteHelpers.cs, WalletWasabi/JsonConverters/BlockCypherDateTimeOffsetJsonConverter.cs, WalletWasabi/Models/SmartCoin.cs, WalletWasabi/Services/MemPoolBehavior.cs, WalletWasabi/Services/WalletService.cs
Removes redundant casting for readability.
=> Remove redundant casts

WalletWasabi/Helpers/HttpMessageHelper.cs
Trivial change for preventing possible NRE.
=> Prevent possible NRE

WalletWasabi/Crypto/BlindingRsaKey.cs, WalletWasabi/Crypto/BlindingRsaPubKey.cs
This PR implements null comparisons for the `== operators` preventing they throw `NullReferenceExceptions`
=> Adds null comparison for operator ==

WalletWasabi/Http/Models/StartLine.cs, WalletWasabi/KeyManagement/KeyManager.cs, WalletWasabi/Services/WalletService.cs, WalletWasabi/TorSocks5/TorSocks5Client.cs
This PR fixes a few cases where the code contained `if` statements that always `true`.
=> Fix always TRUE expressions

WalletWasabi/Bases/TorDisposableBase.cs, WalletWasabi/WebClients/ChaumianCoinJoin/AliceClient.cs, WalletWasabi/WebClients/ChaumianCoinJoin/BobClient.cs, WalletWasabi/WebClients/ChaumianCoinJoin/SatoshiClient.cs
Created TorDisposableBase class for the common TorHttpClient disposable logic
=> Moved common tor disposable logic to base class

WalletWasabi.Backend/Controllers/ChaumianCoinJoinController.cs, WalletWasabi/Models/ChaumianCoinJoin/CcjRound.cs
Use UTC in dates stored in the server-side and in calculation for banning/unbanning coins
=> Use UtcNow instead of Utc

WalletWasabi.Backend/README.md, WalletWasabi.Tests/RegTests.cs, WalletWasabi/Services/IndexDownloader.cs, WalletWasabi/Services/WalletService.cs, WalletWasabi/WebClients/ChaumianCoinJoin/WasabiClient.cs
Implemented the remaining queries from the BlockchainController and OffchainController as part of point 3 from the feedback left on #252.
=> WasabiClient completeness update

README.md, WalletWasabi.Documentation/BackendDeployment.md
Code blocks of command line instructions have had the sh tag added for #270
=> Added sh tag to command line instructions

WalletWasabi/Extensions/HttpResponseMessageExtensions.cs, WalletWasabi/WebClients/ChaumianCoinJoin/AliceClient.cs, WalletWasabi/WebClients/ChaumianCoinJoin/BobClient.cs, WalletWasabi/WebClients/ChaumianCoinJoin/SatoshiClient.cs, WalletWasabi/WebClients/ChaumianCoinJoin/WasabiClient.cs
Moved repeated logic to extension method.
Changed PostConfirmationAsync control flow to be in line with other
methods.
=> Created method for throwing request exceptions

WalletWasabi.Gui/Controls/StatusBar.xaml, WalletWasabi.Gui/ViewModels/StatusBarViewModel.cs, WalletWasabi/Services/IndexDownloader.cs
Left filters number is displayed as '--' when it is unknown and
with the real number when it is synchronizing.
=> Display left filters in a friendly way

WalletWasabi/Backend/Models/FilterModel.cs, WalletWasabi/Services/IndexBuilderService.cs, WalletWasabi/WalletWasabi.csproj
This PR updates NBitcoin to the latest version and updates the filters' parameters. Fixes https://github.com/zkSNACKs/WalletWasabi/issues/285
=> Updates the NBitcoin version to the lastest one

Directory.Build.targets
This PR fixes the StatusBar and MainMenu misalignment produced by the wrong font in linux.
=> Upgrade avalonia version

WalletWasabi.Gui/Tabs/CustomerSupportView.xaml, WalletWasabi.Gui/Tabs/PrivacyPolicyViewModel.cs, WalletWasabi.Gui/Tabs/TermsAndConditionsViewModel.cs
This PR contains the harcoded texts for **Terms and Conditions** and **Privacy Policy** taken from the google doc documents. Also, it adds the Tor recommendation in the **Customer Support** tab.
=> Missing tabs Texts

WalletWasabi.Gui/Tabs/LegalIssuesView.xaml, WalletWasabi.Gui/Tabs/LegalIssuesViewModel.cs, WalletWasabi.Gui/Tabs/PrivacyPolicyView.xaml, WalletWasabi.Gui/Tabs/TermsAndConditionsView.xaml
Wraps the text for Legal Issues, Terms and Conditions and Privacy Policy. Add Content to legal issues tab.
=> Missing tabs continue

WalletWasabi.Gui/Tabs/WalletManager/LoadWalletView.xaml, WalletWasabi.Gui/Tabs/WalletManager/LoadWalletViewModel.cs
This PR just is for adding the "Load Button" to the Load Wallet
=> Add Load Button to the Load Wallet

WalletWasabi.Gui/Tabs/WalletManager/LoadWalletViewModel.cs
Minor improvement for usability.
=> Order existing wallets by LastAccess date first

WalletWasabi.Gui/MainWindow.xaml.cs, WalletWasabi.Gui/Shell/Commands/ToolCommands.cs, WalletWasabi.Gui/Shell/Commands/WalletCommands.cs, WalletWasabi.Gui/Tabs/WalletManager/GenerateWalletSuccessViewModel.cs, WalletWasabi.Gui/Tabs/WalletManager/LoadWalletViewModel.cs, WalletWasabi.Gui/Tabs/WalletManager/RecoverWalletViewModel.cs, WalletWasabi.Gui/Tabs/WalletManager/WalletManagerViewModel.cs, WalletWasabi.Gui/Utils.cs
In this PR we improve the UI code and prevent the loading wallets when there is one already loaded wallet.
=> Allows only one wallet

WalletWasabi.Gui/Styles/Styles.xaml, WalletWasabi.Gui/Tabs/WalletManager/GenerateWalletSuccessViewModel.cs, WalletWasabi.Gui/Tabs/WalletManager/LoadWalletView.xaml, WalletWasabi.Gui/Tabs/WalletManager/LoadWalletViewModel.cs, WalletWasabi.Gui/Tabs/WalletManager/RecoverWalletViewModel.cs, WalletWasabi.Gui/Tabs/WalletManager/WalletManagerViewModel.cs
Doesn't allow users to open a second wallet.
=> Display message indicating there is an open wallet

WalletWasabi/Models/ChaumianCoinJoin/CcjRound.cs, WalletWasabi/Services/CcjClient.cs, WalletWasabi/Services/WalletService.cs
Using lists to avoid multiple enumeration.
Removed unnecessary ToArray call.
=> Small performance improvements

WalletWasabi.Gui/Styles/Styles.xaml
Improves the vorder lines and header color.
This change has a dependency with the AvaloniaStudio project.
=> Improves the border and headers lines

WalletWasabi.Gui/Controls/WalletExplorer/WalletExplorerView.xaml
=> Fix issue #334

WalletWasabi.Gui/Tabs/WalletManager/LoadWalletViewModel.cs
=> Fixes the displayed wallet list order

WalletWasabi.Gui/Controls/WalletExplorer/WalletExplorerView.xaml
=> Better icons for Send/Receive

WalletWasabi.Gui/Tabs/WalletManager/LoadWalletView.xaml, WalletWasabi.Gui/Tabs/WalletManager/LoadWalletViewModel.cs
=> Adds Open Folder Button

WalletWasabi.Gui/Tabs/LegalIssuesViewModel.cs, WalletWasabi.Gui/Tabs/PrivacyPolicyViewModel.cs, WalletWasabi.Gui/Tabs/TermsAndConditionsViewModel.cs
Fix applied to:
* Privacy policy,
* Terms and conditions and
* Legal issues
Closes #356
=> Fixes texboex with huge content

WalletWasabi.Gui/Controls/StatusBar.xaml, WalletWasabi.Gui/Converters/StatusColorConvertor.cs
Created converter to toggle the text color of the Tor and Backend status.
Ref: #325
=> Created convertor to toggle status colors

WalletWasabi.Gui/Behaviors/ClearPropertyOnLostFocusBehavior.cs, WalletWasabi.Gui/Controls/WalletExplorer/HistoryTabView.xaml, WalletWasabi.Gui/Controls/WalletExplorer/HistoryTabView.xaml.cs, WalletWasabi.Gui/Controls/WalletExplorer/ReceiveTabView.xaml, WalletWasabi.Gui/Controls/WalletExplorer/ReceiveTabView.xaml.cs
and helps keep the application maintainable.
=> Clear selections on LostFocus by using a behavior which is reusable

WalletWasabi.Gui/Behaviors/CommandBaseBehavior.cs, WalletWasabi.Gui/Behaviors/CommandOnEnterBehavior.cs, WalletWasabi.Gui/Controls/WalletExplorer/ReceiveTabView.xaml
This PR is for allowing TextBoxes to raise commands when they receive Enter.
=> Make press Enter raise a Command in TextBox

WalletWasabi.Gui/Behaviors/CommandBaseBehavior.cs, WalletWasabi.Gui/Behaviors/CommandOnEnterBehavior.cs, WalletWasabi.Gui/Controls/QrCode.cs, WalletWasabi.Gui/Controls/WalletExplorer/ReceiveTabView.xaml, WalletWasabi.Gui/ViewModels/AddressViewModel.cs, WalletWasabi.Gui/WalletWasabi.Gui.csproj
This PR add and expandable row for each available bitcoin address in the wallet that when expanded, display the bitcoin address encoded as a QR code.
=> QR Code in receive tab

WalletWasabi.Gui/Controls/WalletExplorer/HistoryTabView.xaml, WalletWasabi.Gui/Converters/MoneyBrushConverter.cs
This PR adds Green and Red color for amounts depending if they are incoming or outgoing transactions.
=> Green and Red color for amounts

WalletWasabi.Gui/Controls/QrEncoder/BitMatrixBase.cs, WalletWasabi.Gui/Controls/QrEncoder/DataEncodation/ECISet.cs, WalletWasabi.Gui/Controls/QrEncoder/Masking/Pattern5.cs, WalletWasabi.Gui/Controls/QrEncoder/Masking/Pattern6.cs, WalletWasabi.Gui/Controls/QrEncoder/Masking/Pattern7.cs, WalletWasabi.Gui/Controls/QrEncoder/Masking/Scoring/Penalty4.cs, WalletWasabi.Gui/Controls/QrEncoder/SquareBitMatrix.cs, WalletWasabi.Gui/Controls/QrEncoder/TriStateMatrix.cs, WalletWasabi.Gui/Controls/QrEncoder/VersionDetail.cs, WalletWasabi.Gui/Controls/QrEncoder/Versions/QRCodeVersion.cs
Added parens for clarity.
Created base class for shared logic.
Ref: #379
=> Code factor fixes

WalletWasabi.Gui/Controls/QrEncoder/BitMatrixBase.cs
=> Code factor: Removed whitespace

WalletWasabi.Gui/Controls/WalletExplorer/CoinListView.xaml, WalletWasabi.Gui/Controls/WalletExplorer/CoinViewModel.cs
This PR add the following data items to the coin list tooltip:
* Height
* Confirmations
* Output index (Outpoint.N)
* AnonymitySet
Also, it improves the info layout.
=> Add info to the CoinList tooltip

WalletWasabi.Gui/Controls/WalletExplorer/CoinJoinTabView.xaml
CoinJoin tab didn't display okay on small resolutions. This PR improves this situation.
=> Make CoinJoin page view better in small resolutions

WalletWasabi.Gui/Controls/WalletExplorer/CoinListView.xaml, WalletWasabi.Gui/Controls/WalletExplorer/CoinViewModel.cs, WalletWasabi.Gui/Controls/WalletExplorer/SendTabView.xaml
Improves the Send Tab controls layout.
=> Moves the Send panel into the main panel

WalletWasabi.Gui/Controls/WalletExplorer/SendTabView.xaml
This PR is for fixing the broken send panel and adding the missing fee label.
=> Fix broken send panel

WalletWasabi.Gui/Controls/WalletExplorer/CoinListView.xaml, WalletWasabi.Gui/Controls/WalletExplorer/CoinViewModel.cs
=> Revert changes in History

Directory.Build.targets
fixes #312 
bug was in avalonia and fixed here:
https://github.com/AvaloniaUI/Avalonia/pull/1739
=> update avalonia with fix for menuitems getting stuck on.

Directory.Build.targets
=> update avalonia with fix for mac osx focus bug.

WalletWasabi.Gui/Controls/WalletExplorer/ReceiveTabView.xaml
=> Add gap between label/button and address list

Directory.Build.targets
=> update avalonia to fix watermarks.

WalletWasabi.Gui/Styles/Styles.xaml
=> Hides the chrome buttons

WalletWasabi.Gui/Controls/WalletExplorer/WalletViewModel.cs
Balance is included next to the wallet name.
Ref: #446
=> Added the balance to the wallet name

WalletWasabi.Gui/MainWindow.xaml, WalletWasabi.Gui/Program.cs, WalletWasabi.Gui/ViewModels/MainWindowViewModel.cs, WalletWasabi.Gui/ViewModels/StatusBarViewModel.cs
Moved network to header.
Removed network from statusbar.
For: #422
=> Moved network to header

.gitignore, .vscode/settings.json
Add project-specific settings for indentation.
=> Add .vscode/settings.json file to force use of latest omnisharp.

WalletWasabi.Gui/Controls/WalletExplorer/CoinListView.xaml, WalletWasabi.Gui/Controls/WalletExplorer/ReceiveTabView.xaml
This may eventually become a performance issue for very large lists.
However for now this fixes the issue. We need to do work on avalonia to fix this.
=> allow expander to work in listbox

WalletWasabi.Gui/Controls/WalletExplorer/SendTabViewModel.cs, WalletWasabi.Gui/ViewModels/Validation/ReflectionHelper.cs, WalletWasabi.Gui/ViewModels/Validation/ValidateMethodAttribute.cs, WalletWasabi.Gui/ViewModels/Validation/Validator.cs, WalletWasabi.Gui/ViewModels/ViewModelBase.cs
=> implement validation for any property - adds validation for Address

WalletWasabi.Gui/Controls/WalletExplorer/CoinJoinTabView.xaml, WalletWasabi.Gui/Controls/WalletExplorer/SendTabView.xaml
=> fix button alignments.

WalletWasabi.Gui/Controls/WalletExplorer/CoinListView.xaml
=> Fix Copy/Paste in CoinList control

WalletWasabi.Gui/Controls/ExtendedTextBox.cs
=> disable paste command is extended tb is made readonly.

WalletWasabi.Gui/Controls/ExtendedTextBox.cs
=> Added copy and paste icons

WalletWasabi.Gui/Controls/WalletExplorer/CoinJoinTabView.xaml
=> Add scroll to the coinjoin status panel

WalletWasabi.Gui/Controls/WalletExplorer/ReceiveTabView.xaml, WalletWasabi.Gui/Controls/WalletExplorer/ReceiveTabViewModel.cs, WalletWasabi.Gui/ViewModels/AddressViewModel.cs
Reverts zkSNACKs/WalletWasabi#536
=> Revert "Add Copy context menu to addresses"

WalletWasabi.Gui/Controls/WalletExplorer/CoinJoinTabViewModel.cs
Made validation of selected coins to enqueue inline with selected coins for send transaction
=> Add selected coins to enqueue validation

WalletWasabi.Gui/Controls/GroupBox.xaml
Fixes #438 This is not planned for Beta but it was so easy to fix that i couldn't resist the tentation.
=> Adds padding to the groupbox panel

WalletWasabi.Gui/Controls/WalletExplorer/ReceiveTabView.xaml, WalletWasabi.Gui/Controls/WalletExplorer/ReceiveTabViewModel.cs, WalletWasabi.Gui/ViewModels/AddressViewModel.cs
This is for redoing https://github.com/zkSNACKs/WalletWasabi/pull/536 adding the icon. I need clarification about this:
> it'd be better to show the context menu when right clicking on the row, not on the grid.
=> Copy context menu

WalletWasabi.Gui/Shell/Commands/ExitCommands.cs
=> Prevent freeze on File/Exit

WalletWasabi.Gui/MainWindow.xaml.cs, WalletWasabi.Gui/Shell/Commands/HelpCommands.cs, WalletWasabi.Gui/Shell/MainMenu/HelpMainMenuItems.cs
=> Hide DevTools in Release mode

WalletWasabi.Gui/Tabs/WalletManager/LoadWalletView.xaml
Reverts zkSNACKs/WalletWasabi#559
=> Revert "Make Load page look like the rest"

WalletWasabi.Gui/Controls/WalletExplorer/CoinJoinTabViewModel.cs
=> Enqueue Coin: Clear password when successful/unsuccessful

WalletWasabi.Backend/Controllers/BlockchainController.cs, WalletWasabi.Gui/Config.cs, WalletWasabi.Tests/RegTests.cs
Lowered fee rate sanity check to 2.
Part 1 for: #566
=> Backend: Lower fee rate sanity check

README.md
PR for adding a simple note about .NET telemetry.
=> Add note about telemetry in README file

WalletWasabi.Gui/Styles/Styles.xaml
This PR fixes #449. Please let me know if you like it or I have to change something.
=> Hightlight tab's close buttom

WalletWasabi.Gui/Controls/WalletExplorer/CoinJoinTabView.xaml, WalletWasabi.Gui/Converters/PhaseColorConverter.cs
This PR is for adding a new visual indicator of progress. Implements https://github.com/zkSNACKs/WalletWasabi/issues/531
=> Phases progress

WalletWasabi.Gui/Controls/StatusBar.xaml
Use StringFormat to reduce repetition.
=> Use string format for TODOs

WalletWasabi/Models/ChaumianCoinJoin/CcjRound.cs
Resolves https://github.com/zkSNACKs/WalletWasabi/issues/617
=> Lower final CJ fees if possible

WalletWasabi.Gui/Program.cs
This is for closing #645. We need to wait for the PR
https://github.com/VitalElement/AvalonStudio.Shell/pull/9 to be merged
first.
=> Base directory for Avalonia

WalletWasabi.Gui/Program.cs
Reverts zkSNACKs/WalletWasabi#646
=> Revert "Base directory for Avalonia"

WalletWasabi.Gui/Program.cs
Reverts zkSNACKs/WalletWasabi#647
This is the same as this: https://github.com/zkSNACKs/WalletWasabi/pull/646
Just has to wait for https://github.com/VitalElement/AvalonStudio.Shell/pull/9
=> [WIP] Revert "Revert "Base directory for Avalonia""

WalletWasabi/KeyManagement/KeyManager.cs, WalletWasabi/Models/TxoRef.cs, WalletWasabi/Services/WalletService.cs
PR replacement: https://github.com/zkSNACKs/WalletWasabi/pull/701/
@lontivero I was clicking on the wrong buttons, I'm not sure why it wasn't pushing directly to your PR, so this is going to be a few fixes.
=> [WIP] Pr/701 load wallet performance

WalletWasabi/Services/WalletService.cs
This should be closer to what I was going for.  
In the existing version, is it bad or unexpected when this exception gets triggered? When I started loading my wallet, this was thrown repeatedly so I thought maybe something may be wrong elsewhere.
If the exception is expected, then I normally would change the code to avoid the exception, because you have to remember to turn off that exception in IDE when debugging, which is annoying, and also they are slow.
=> Check if fileName is a valid hex string to avoid unneeded exceptions

Directory.Build.targets
Reverts zkSNACKs/WalletWasabi#818
=> Revert "[osx] update avalonia to fix cmd key gestures."

WalletWasabi.Gui/Controls/WalletExplorer/CoinListView.xaml, WalletWasabi.Gui/Controls/WalletExplorer/CoinViewModel.cs
=> Add Bitcoin address to the coins' details

WalletWasabi.Gui/Controls/WalletExplorer/CoinListView.xaml, WalletWasabi.Gui/Controls/WalletExplorer/HistoryTabView.xaml, WalletWasabi.Gui/Converters/MoneyBrushConverter.cs, WalletWasabi.Gui/Icons/Icons.xaml
#798 
Changed the green BTC value to Medium Sea Green (ff3cb371), as requested I also changed the privacy badge green and the checkmarks to all be the same color.
=> Fix green highlight visibility issue (Issue #798)

Directory.Build.targets
Maybe it's still good. Wrong branch was tested by @molnard
=> [WIP] Revert "Revert "[osx] update avalonia to fix cmd key gestures.""

Directory.Build.targets
- Fixes the IBeam cursor issue on textboxes.
- Fixes the tooltips and popups overlapping screen edges.
fixes:
https://github.com/zkSNACKs/WalletWasabi/issues/432
=> update avalonia with multiple fixes

WalletWasabi.Gui/Controls/StatusBar.xaml, WalletWasabi.Gui/Controls/WalletExplorer/HistoryTabView.xaml, WalletWasabi.Gui/MainWindow.xaml
- History Tab - Column headers aligned
- Status bar height should be increased
- Increase distance of Wasabi Icon on the left upper and File menuitem
=> Small ui fixes mainly aligns and pixel fixes

WalletWasabi.Gui/Controls/WalletExplorer/CoinListView.xaml, WalletWasabi.Gui/Controls/WalletExplorer/CoinListViewModel.cs, WalletWasabi.Gui/Controls/WalletExplorer/CoinViewModel.cs, WalletWasabi.Gui/Controls/WalletExplorer/SendTabView.xaml
- Added Dequeue per coin functionality with right click in coinlist
- Hightlighted rows in coinlist
- Fixed circular propertyChange problem on ToolTip.
=> Added right click Dequeue per coin functionality

WalletWasabi.Backend/Controllers/ChaumianCoinJoinController.cs, WalletWasabi.Tests/RegTests.cs, WalletWasabi.Tests/XunitConfiguration/RegTestFixture.cs, WalletWasabi/Models/ChaumianCoinJoin/CcjRound.cs, WalletWasabi/Models/ChaumianCoinJoin/CcjRoundConfig.cs, WalletWasabi/Services/CcjCoordinator.cs, WalletWasabi/Services/UtxoReferee.cs, WalletWasabi/WebClients/Wasabi/ChaumianCoinJoin/AliceClient.cs
Resolves: https://github.com/zkSNACKs/WalletWasabi/issues/847
=> Add "noted" status for first round disrupting

WalletWasabi.Gui/Behaviors/PasteAddressOnClickBehavior.cs
=> Increase Address sanity check from 50 to 100

WalletWasabi.Gui/Controls/StatusBar.xaml, WalletWasabi.Gui/Converters/PascalToPhraseConverter.cs
It changes  "**Tor: NotConnected**" by "**Tor is not connected**" and the same for Backend.
=> Status bar messages

Directory.Build.targets
https://youtu.be/WVq7MkG4G3k
https://github.com/AvaloniaUI/Avalonia/pull/2128
=> Updated Avalonia so that Windows Snap is supported.

WalletWasabi/Services/WalletService.cs
=> Ignore corrupted Transactions.json file

WalletWasabi.Gui/Global.cs
=> Wrap osasacript parameter around quote marks

WalletWasabi.Gui/Config.cs, WalletWasabi.Gui/Global.cs, WalletWasabi/TorSocks5/TorHttpClient.cs, WalletWasabi/TorSocks5/TorProcessManager.cs, WalletWasabi/WebClients/Wasabi/WasabiClient.cs
Closes https://github.com/zkSNACKs/WalletWasabi/issues/912
Closes https://github.com/zkSNACKs/WalletWasabi/issues/943
Closes https://github.com/zkSNACKs/WalletWasabi/pull/930
Closes https://github.com/zkSNACKs/WalletWasabi/pull/931
Closes https://github.com/zkSNACKs/WalletWasabi/pull/947
=> Backupbranch

WalletWasabi.Gui/Controls/WalletExplorer/HistoryTabViewModel.cs, WalletWasabi.Gui/Controls/WalletExplorer/TransactionViewModel.cs
=> Fixing the Amount ordering at history tab

WalletWasabi.Gui/Controls/WalletExplorer/CoinJoinTabViewModel.cs
=> - coinjoin tab shows warning if no coins are selected on dequeue button

WalletWasabi.Gui/Controls/WalletExplorer/SendTabViewModel.cs, WalletWasabi.Gui/Global.cs, WalletWasabi.Gui/MainWindow.xaml.cs, WalletWasabi.Gui/UiConfig.cs
- saving the FeeTarget (on sendTab) to the UiConfig file making it nonvolatile.
=> saving the FeeTarget (on sendTab) to the UiConfig

WalletWasabi.Gui/Controls/WalletExplorer/CoinListView.xaml
resolve https://github.com/zkSNACKs/WalletWasabi/issues/988
=> remove tooltip from Select All checkbox

WalletWasabi.Community/Dojo.md
resolve https://github.com/zkSNACKs/WalletWasabi/issues/956
=> Wax on, wax off. Wax on, wax off.

WalletWasabi/Extensions/RPCClientExtensions.cs, WalletWasabi/WalletWasabi.csproj
=> Update NBitcoin version

WalletWasabi.Backend/Controllers/ChaumianCoinJoinController.cs, WalletWasabi.Gui/Controls/WalletExplorer/ReceiveTabViewModel.cs, WalletWasabi.Tests/ModelTests.cs, WalletWasabi.Tests/RegTests.cs, WalletWasabi/Backend/Models/Requests/InputsRequest.cs, WalletWasabi/Backend/Models/Requests/OutputRequest.cs, WalletWasabi/Backend/Models/Responses/CcjRunningRoundState.cs, WalletWasabi/Backend/Models/Responses/InputsResponse.cs, WalletWasabi/Extensions/NBitcoinExtensions.cs, WalletWasabi/Helpers/Constants.cs, WalletWasabi/JsonConverters/KeyJsonConverter.cs, WalletWasabi/KeyManagement/KeyManager.cs, WalletWasabi/Models/ChaumianCoinJoin/Alice.cs, WalletWasabi/Models/ChaumianCoinJoin/Bob.cs, WalletWasabi/Models/ChaumianCoinJoin/CcjClientRound.cs, WalletWasabi/Models/ChaumianCoinJoin/CcjRound.cs, WalletWasabi/Models/ChaumianCoinJoin/MixingLevel.cs, WalletWasabi/Models/ChaumianCoinJoin/MixingLevels.cs, WalletWasabi/Models/ChaumianCoinJoin/SchnorrKey.cs, WalletWasabi/Models/ChaumianCoinJoin/SchnorrPubKey.cs, WalletWasabi/Services/CcjClient.cs, WalletWasabi/Services/WalletService.cs, WalletWasabi/WebClients/Wasabi/ChaumianCoinJoin/AliceClient.cs, WalletWasabi/WebClients/Wasabi/ChaumianCoinJoin/BobClient.cs
=> Unequal Amount Mixing Basic

WalletWasabi.Gui/Controls/StatusBar.xaml, WalletWasabi.Gui/Program.cs, WalletWasabi.Gui/ViewModels/StatusBarViewModel.cs
This is the continuation of molnard PR #1004. I wasn't able to edit his PR. Closes #1003
=> Mempool removed from statusbar II

WalletWasabi.Gui/Controls/StatusBar.xaml
resolves https://github.com/zkSNACKs/WalletWasabi/issues/1003
=> Mempool removed from statusbar

WalletWasabi.Tests/RegTests.cs
This PR is for testing the hardfork's unequal outputs coinjoin. The integration test runs a coinjoin session with 4 participants, with four 0.1 btc coins each (0.4 btc each). Each participant blinds 10 outputs and send them to the coordinator but it only signs 2 (0.1btc and 0.2btc what I think is the expected behavior). However the coinjoin transaction doesn't have the expected outputs (I can be wrong here):
* four 0.1 outputs,
* four 0.2 outputs and,
* four change outputs
* four 0.399xxx outputs,
* no change outputs
**NOTE:** please take a look at the `#if REVIEW ... #endif`
=> Test multilevel coinjoins

WalletWasabi.Gui/Controls/WalletExplorer/CoinJoinTabView.xaml, WalletWasabi.Gui/Controls/WalletExplorer/CoinJoinTabViewModel.cs
Add new feature like CoinJoin auto dequeue
Add setable the desired anonymity level
=> [WIP] coinjoin redisign

WalletWasabi.Backend/Controllers/ChaumianCoinJoinController.cs, WalletWasabi/Extensions/RPCClientExtensions.cs, WalletWasabi/Models/ChaumianCoinJoin/CcjRound.cs
This PR contains the same commit that #1051 but with the idea of merging on hardfork branch.
=> Improve Alice removal (hardfork)

WalletWasabi.Gui/Global.cs
=> Increase required number of addresses to prevent discovery

WalletWasabi.Gui/Controls/ExtendedTextBox.cs, WalletWasabi.Gui/Controls/NoparaPasswordBox.cs, WalletWasabi.Gui/Controls/WalletExplorer/CoinJoinTabView.xaml, WalletWasabi.Gui/Controls/WalletExplorer/SendTabView.xaml, WalletWasabi.Gui/Tabs/WalletManager/GenerateWalletView.xaml, WalletWasabi.Gui/Tabs/WalletManager/GenerateWalletViewModel.cs, WalletWasabi.Gui/Tabs/WalletManager/RecoverWalletView.xaml, WalletWasabi/Helpers/Constants.cs
resolves: https://github.com/zkSNACKs/WalletWasabi/issues/439
=> [WIP] Funnypwbox

WalletWasabi.Gui/Controls/WalletExplorer/CoinJoinTabView.xaml
=> Let anonimity set text wrap under the shield icon.

WalletWasabi.Backend/Controllers/ChaumianCoinJoinController.cs
Just another check for registered outputs.
=> Check posted addresses are no Wasabi coordinator address

WalletWasabi/Models/ChaumianCoinJoin/CcjRound.cs
When Alice has no enough money to pay the coordinator fee take from her what she can to afford.
=> Allow Alice to pay what she can instead of pay nothing

WalletWasabi.Gui/Behaviors/BindSelectedTextBehavior.cs, WalletWasabi.Gui/Controls/WalletExplorer/CoinJoinTabViewModel.cs, WalletWasabi.Gui/Controls/WalletExplorer/CoinListView.xaml, WalletWasabi.Gui/Controls/WalletExplorer/CoinListViewModel.cs, WalletWasabi.Gui/Controls/WalletExplorer/CoinViewModel.cs, WalletWasabi.Gui/Controls/WalletExplorer/HistoryTabView.xaml, WalletWasabi.Gui/Controls/WalletExplorer/HistoryTabViewModel.cs, WalletWasabi.Gui/Controls/WalletExplorer/ReceiveTabViewModel.cs, WalletWasabi.Gui/Controls/WalletExplorer/SendTabViewModel.cs, WalletWasabi.Gui/Controls/WalletExplorer/TransactionViewModel.cs, WalletWasabi.Gui/Program.cs, WalletWasabi.Gui/ViewModels/MainWindowViewModel.cs, WalletWasabi.Gui/ViewModels/StatusBarViewModel.cs
=> Disposing viewmodels

WalletWasabi.Documentation/Guides/HowToDebug.md
=> Create HowToDebug.md file

WalletWasabi.Gui/Controls/WalletExplorer/ReceiveTabViewModel.cs, WalletWasabi.Gui/Controls/WalletExplorer/SendTabViewModel.cs
=> Add null check for entered label in receive tab input field

WalletWasabi.Gui/Tabs/SettingsView.xaml, WalletWasabi.Gui/Tabs/SettingsViewModel.cs, WalletWasabi/Helpers/IoHelpers.cs
Need test on different flatforms
=> Open config file

Directory.Build.targets
Warning! This PR depends on #1148 being merged first.
Closes https://github.com/zkSNACKs/WalletWasabi/issues/1160
=> [Linux] update avalonia with X11 scaling fix.

WalletWasabi.Gui/Icons/Icons.xaml, WalletWasabi.Gui/Shell/Commands/DiskCommands.cs, WalletWasabi.Gui/Shell/Commands/HelpCommands.cs, WalletWasabi.Gui/Shell/MainMenu/FileMainMenuItems.cs, WalletWasabi.Gui/Shell/MainMenu/HelpMainMenuItems.cs, WalletWasabi.Gui/Tabs/WalletManager/WalletManagerViewModel.cs
Closes https://github.com/zkSNACKs/WalletWasabi/pull/1165
- Removed Open Data Folder from Help Menu
- Added Open Menu to File Menu
@lontivero @molnard Could one of take a quick look? I'm pretty sure it's good, but I want to start minimizing my commits to the master and start doing pull requests.
=> Implement Open Menu

Directory.Build.targets
Reverts zkSNACKs/WalletWasabi#1166
See: https://github.com/zkSNACKs/WalletWasabi/issues/1170
=> Revert "[Linux] update avalonia with X11 scaling fix."

Directory.Build.targets
Reverts zkSNACKs/WalletWasabi#1166
See: https://github.com/zkSNACKs/WalletWasabi/issues/1170
=> Revert "fix for deferred renderer nre"

Directory.Build.targets, WalletWasabi.Gui/Controls/WalletExplorer/CoinListView.xaml
Fixes: https://github.com/zkSNACKs/WalletWasabi/issues/1170
=> Fix Xaml Parse Error in CoinListView and update Avalonia with fixes

WalletWasabi/TorSocks5/TorSocks5Client.cs
This PR fixes https://github.com/zkSNACKs/WalletWasabi/issues/1169
Closes https://github.com/zkSNACKs/WalletWasabi/pull/1173
@lontivero Can you review it? It fixes all the possible stackoverflows, because it explicitly recognizes if a call is recursive.
=> Fix stackoverflow

WalletWasabi.Gui/Controls/WalletExplorer/CoinJoinTabViewModel.cs, WalletWasabi.Gui/Controls/WalletExplorer/CoinListViewModel.cs, WalletWasabi.Gui/Controls/WalletExplorer/HistoryTabViewModel.cs, WalletWasabi.Gui/Controls/WalletExplorer/ReceiveTabViewModel.cs, WalletWasabi.Gui/Controls/WalletExplorer/SendTabViewModel.cs, WalletWasabi.Gui/Dialogs/CannotCloseDialogViewModel.cs, WalletWasabi.Gui/Global.cs, WalletWasabi.Gui/Tabs/SettingsViewModel.cs, WalletWasabi.Gui/Utils.cs, WalletWasabi.Gui/ViewModels/StatusBarViewModel.cs
Closes https://github.com/zkSNACKs/WalletWasabi/issues/1147
=> UI Dispatcher Post task exception handling

Directory.Build.targets, WalletWasabi.Gui/Models/ShieldLevelHelper.cs
=> Fix OSX NRE on exit

WalletWasabi.Gui/CommandLine/Daemon.cs, WalletWasabi.Gui/CommandLine/Native.cs, WalletWasabi.Gui/Global.cs, WalletWasabi.Gui/Program.cs, WalletWasabi.Gui/Tabs/WalletManager/LoadWalletViewModel.cs, WalletWasabi/Helpers/IoHelpers.cs, WalletWasabi/Helpers/PasswordConsole.cs, WalletWasabi/KeyManagement/KeyManager.cs, WalletWasabi/Models/ChaumianCoinJoin/CcjClientState.cs
Now with the new options the daemon must be reimplemented. 
Closes https://github.com/zkSNACKs/WalletWasabi/pull/1130
The new workflow is: `dotnet run "--mix --wallet {WalletName}"`.
=> Start implementing daemon again

Directory.Build.targets
Closes https://github.com/zkSNACKs/WalletWasabi/issues/1202
=> Fix Restore Issue

WalletWasabi.Gui/Controls/NoparaPasswordBox.cs
=> Prevent using non-initialized displayText

WalletWasabi.Backend/Config.cs, WalletWasabi.Backend/Program.cs, WalletWasabi.Documentation/BackendDeployment.md, WalletWasabi.Tests/XunitConfiguration/RegTestFixture.cs
Reverts zkSNACKs/WalletWasabi#1210
=> Revert "Uses RPC cookie file instead of rpcuser:rpcpassword"

WalletWasabi.Backend/Config.cs, WalletWasabi.Backend/Program.cs, WalletWasabi.Tests/XunitConfiguration/RegTestFixture.cs
Un-revert https://github.com/zkSNACKs/WalletWasabi/pull/1210
Closes #1214
=> Uses RPC cookie file instead of rpcuser:rpcpassword (2)

WalletWasabi.Packager/Program.cs
=> Pass parameter from the launcher

WalletWasabi.Tests/RegTests.cs, WalletWasabi/Models/SmartCoin.cs, WalletWasabi/Models/SmartTransaction.cs, WalletWasabi/Services/WalletService.cs
I will push code to this PR because it would be good to get some feedback while I am moving forward.
Closes https://github.com/zkSNACKs/WalletWasabi/pull/1237
Closes https://github.com/zkSNACKs/WalletWasabi/issues/474
=> Fix Replacement tx detection

WalletWasabi.Gui/Controls/WalletExplorer/ReceiveTabView.xaml, WalletWasabi.Gui/Controls/WalletExplorer/ReceiveTabViewModel.cs
fixes: https://github.com/zkSNACKs/WalletWasabi/issues/1009
=> QR code popup menu on receive tab

WalletWasabi.Gui/Tabs/SettingsView.xaml
Closes https://github.com/zkSNACKs/WalletWasabi/issues/1271
=> Add Scroll to settings tab content

.github/ISSUE_TEMPLATE/bug-report.md, .github/ISSUE_TEMPLATE/feature-request.md
Bugs: version, where it was downloaded from (maybe add signature hash?
Features: version
=> Add wasabi version in issue template

WalletWasabi.Documentation/Guides/InstallInstructions.md
closes https://github.com/zkSNACKs/WalletWasabi/issues/1268
closes https://github.com/zkSNACKs/WalletWasabi/issues/1158
=> Add GPG verification guide with GUI

WalletWasabi.Gui/Controls/WalletExplorer/HistoryTabViewModel.cs
Fixes: https://github.com/zkSNACKs/WalletWasabi/issues/1286
Just a side note. Throwing an exception in `RewriteTableAsync()` and the application breaks. have to investigate this. Normally is should cause `TaskScheduler_UnobservedTaskException` with a warning in the log. Maybe it is because `.ObserveOn(RxApp.MainThreadScheduler)`?
```c#
Observable.FromEventPattern(Global.WalletService.Coins, nameof(Global.WalletService.Coins.CollectionChanged))
.Merge(Observable.FromEventPattern(Global.WalletService, nameof(Global.WalletService.NewBlockProcessed)))
.Merge(Observable.FromEventPattern(Global.WalletService, nameof(Global.WalletService.CoinSpentOrSpenderConfirmed)))
.Throttle(TimeSpan.FromSeconds(5))
.ObserveOn(RxApp.MainThreadScheduler)
.Subscribe(async _ => await RewriteTableAsync()) …
```
=> Fix and catch exception.

WalletWasabi/Helpers/RuntimeParams.cs, WalletWasabi/Services/WalletService.cs
fixes: https://github.com/zkSNACKs/WalletWasabi/issues/1279
=> Adjust node Timeout

WalletWasabi.Gui/Tabs/WalletManager/GenerateWalletViewModel.cs
=> Prevent invalid wallet names

WalletWasabi.Gui/Controls/WalletExplorer/ReceiveTabView.xaml, WalletWasabi.Gui/ViewModels/AddressViewModel.cs
=> Lurking wife cannot lurk anymore.

WalletWasabi/Services/WalletService.cs
=> Re-download corrupted block files

WalletWasabi.Gui/Tabs/WalletManager/LoadWalletViewModel.cs
With a fresh install the WalletBackups dir not exists. This PR fix the crash in this case.
=> Fix loading HW wallet.

WalletWasabi.Community/Dojo.md
I've created and linked several playlists with more precise categories.
- Hands on tutorials
- Interviews
- Zero Link Framework reading
=> Added playlists

WalletWasabi/KeyManagement/KeyManager.cs
De-serialize whole wallet file: __98 ms__
Read only ExtPubKey: __1 ms__
=> Performance ExtPubKey reader from Wallet file

WalletWasabi.Gui/Controls/WalletExplorer/WalletInfoView.xaml, WalletWasabi.Gui/Controls/WalletExplorer/WalletInfoViewModel.cs
=> Remove encrypted secret info from wallet info

WalletWasabi.Gui/Controls/WalletExplorer/CoinJoinTabView.xaml, WalletWasabi.Gui/Controls/WalletExplorer/CoinJoinTabViewModel.cs, WalletWasabi.Gui/Converters/InverseBooleanConverter.cs, WalletWasabi.Gui/Converters/LurkingWifeModeStringConverter.cs, WalletWasabi.Gui/Tabs/SettingsViewModel.cs
Closes https://github.com/zkSNACKs/WalletWasabi/issues/1386
=> Lurk amount queued on CoinJoin Tab 

WalletWasabi.Gui/CommandLine/CommandInterpreter.cs, WalletWasabi.Gui/Global.cs, WalletWasabi.Gui/Program.cs, WalletWasabi/Mono/CommandSet.cs, WalletWasabi/Services/WalletService.cs
@lontivero This ruined the run. When you do `dotnet run` nothing happens.
=> Revert "Allow to specify --datadir"

WalletWasabi/Services/WalletService.cs
Taken from this commit: https://github.com/zkSNACKs/WalletWasabi/pull/1368/commits/753c4f85f68b89bb9031e88b4cb87eeece9b1502
=> Improve nullcheck

WalletWasabi.Gui/Program.cs
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/1411
will wait for feedback from the guy who reported the issue.
=> use glx instead of egl on linux.

WalletWasabi.Gui/Tabs/WalletManager/RecoverWalletViewModel.cs, WalletWasabi/WalletWasabi.csproj
Update NBitcoin and use KeyPath.TryParse instead.
=> Minor changes

WalletWasabi.Gui/Controls/WalletExplorer/WalletInfoView.xaml, WalletWasabi.Gui/Controls/WalletExplorer/WalletInfoViewModel.cs
=> Display MasterKey fingerprint

WalletWasabi/Services/WalletService.cs, WalletWasabi/WalletWasabi.csproj
Upgrade NBitcoin version because @nicolasdorier says there are bug fixes in PSBT code. 
There has been an important refactoring in many of the PSBT classes and a breaking change. The code to make Wasabi build and pass the tests is only one but I don't know if it is 100% correct. Can we assume the tests cover this change or is the Wasabi PSBT code only for HW support?
=> Upgrade NBitcoin

WalletWasabi.Gui/Controls/WalletExplorer/PinPadViewModel.cs, WalletWasabi.Gui/Controls/WalletExplorer/SendTabViewModel.cs, WalletWasabi.Gui/Models/LoadWalletEntry.cs, WalletWasabi.Gui/Tabs/WalletManager/LoadWalletView.xaml, WalletWasabi.Gui/Tabs/WalletManager/LoadWalletViewModel.cs, WalletWasabi.Tests/RegTests.cs, WalletWasabi/Hwi/HwiProcessManager.cs, WalletWasabi/Hwi/Models/HardwareWalletInfo.cs, WalletWasabi/Services/WalletService.cs, WalletWasabi/Stores/IndexStore.cs, WalletWasabi/Stores/IoManager.cs
Closes https://github.com/zkSNACKs/WalletWasabi/issues/1455
=> Add Trezor One Support

WalletWasabi/Models/ChaumianCoinJoin/CcjRound.cs
=> Fix the log message

WalletWasabi.Backend/Program.cs, WalletWasabi.Backend/UnversionedWebBuilder.cs, WalletWasabi.Backend/wwwroot/index.html
I implemented a few minor suggestions those were around on Slack. Since I removed the total amount calculation it also speeds up server startup time significantly.
=> Improve On Website

WalletWasabi.Gui/Tabs/WalletManager/LoadWalletViewModel.cs, WalletWasabi/KeyManagement/KeyManager.cs
Closes https://github.com/zkSNACKs/WalletWasabi/issues/1471
=> Don't show if there isn't encrypted secret.

WalletWasabi/Services/WasabiSynchronizer.cs
=> Throw IOE instead of NRE when no fees

WalletWasabi.Gui/Behaviors/CommandOnDoubleClickBehavior.cs, WalletWasabi.Gui/Tabs/WalletManager/LoadWalletView.xaml
=> Open wallet file with double click

WalletWasabi.Gui/Controls/WalletExplorer/PinPadView.xaml
Closes https://github.com/zkSNACKs/WalletWasabi/issues/1479
=> Add dots to PinPad buttons.

WalletWasabi.Gui/Models/StatusBarStatus.cs, WalletWasabi.Gui/Models/StatusBarStatusSet.cs, WalletWasabi.Gui/ViewModels/StatusBarViewModel.cs, WalletWasabi/Helpers/Constants.cs, WalletWasabi/Stores/HashChain.cs
Should be straightforward, but not sure it's the best pattern. I modify the `StatusBacking` on different threads and subscribe to its changes and set the `Status` on the UI thread.
=> Fix status get stucked (only modify on UI thread.)

WalletWasabi/WebClients/BitcoinAverage/BitcoinAverageExchangeRateProvider.cs, WalletWasabi/WebClients/ExchangeRateProviders.cs
Closes https://github.com/zkSNACKs/WalletWasabi/issues/1554
=> Use BitcoinAverage as default ExchangeRate provider

WalletWasabi.Gui/Controls/WalletExplorer/HistoryTabViewModel.cs
=> Check for null Global.WalletService

WalletWasabi.Gui/Controls/WalletExplorer/WalletExplorerView.xaml
=> Set transaparent background

WalletWasabi.Gui/ViewModels/StatusBarViewModel.cs
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/1571
=> Throttle filters to update less often.

WalletWasabi/Extensions/NBitcoinExtensions.cs, WalletWasabi/Services/WalletService.cs
Reverts zkSNACKs/WalletWasabi#1574
=> Revert "Fix hanging block download"

WalletWasabi.Gui/Controls/StatusBar.xaml, WalletWasabi.Gui/Converters/FilterLeftStatusConverter.cs, WalletWasabi.Gui/Converters/StatusColorConverter.cs, WalletWasabi.Gui/ViewModels/StatusBarViewModel.cs, WalletWasabi/Services/WalletService.cs
Closes https://github.com/zkSNACKs/WalletWasabi/issues/1576
=> Implove filters and blocks status messages.

WalletWasabi.Gui/Global.cs, WalletWasabi/Services/WalletService.cs
=> Change user-agents

WalletWasabi.Gui/Controls/QrCode.cs
=> Center QR code

WalletWasabi.Gui/Program.cs
=> Initialize AvaloniaInstance before using it

WalletWasabi.Gui/Converters/BooleanOnOffConverter.cs, WalletWasabi.Gui/Tabs/SettingsView.xaml, WalletWasabi.Gui/Tabs/SettingsViewModel.cs
This PR clean a bit the Settings View Model by moving the On/Off convertions to a new converter. This will be more important when I add new settings in the Settings page in coming PRs.
=> Simplify settings viewmodel

WalletWasabi.Gui/Controls/WalletExplorer/SendTabViewModel.cs
There wasa missing semicolon in one of my previous merged PRs. This fix it.
=> Missing semicolon

WalletWasabi.Documentation/FAQ.md
=> small typos in faq

WalletWasabi/JsonConverters/Uint256JsonConverter.cs
This pull request is a part of breaking down the MempoolStore PR (https://github.com/zkSNACKs/WalletWasabi/pull/1609) into smaller, more reviewable parts.
=> Add nullcheck

WalletWasabi/Extensions/ExceptionExtensions.cs, WalletWasabi/Services/WalletService.cs
Was caused by https://github.com/zkSNACKs/WalletWasabi/pull/1619
=> Fix UI thread exception crash

WalletWasabi/Helpers/EnvironmentHelpers.cs
This pull request is a part of breaking down the MempoolStore PR (https://github.com/zkSNACKs/WalletWasabi/pull/1609) into smaller, more reviewable parts.
=> Only initialize DataDir once

WalletWasabi.Gui/Controls/ExtendedTextBox.cs
Issue opened on Avalonia and fix coming in next avalonia release. 
https://github.com/AvaloniaUI/Avalonia/issues/2692
=> #1391 - allow textbox context menu to open without deleting selection.

WalletWasabi/Models/ChaumianCoinJoin/CcjClientState.cs
It's been reviewed already, but tests have to be adjusted (thus draft.) Code is well commented.
=> Consolidate in CoinJoin when it doesn't ruin privacy

WalletWasabi.Gui/Controls/WalletExplorer/CoinJoinTabViewModel.cs, WalletWasabi.Gui/Controls/WalletExplorer/CoinListView.xaml, WalletWasabi.Gui/Controls/WalletExplorer/CoinListViewModel.cs, WalletWasabi.Gui/Controls/WalletExplorer/SendTabViewModel.cs, WalletWasabi.Gui/Models/CoinListContainerType.cs, WalletWasabi/Services/WalletService.cs
Added only the send tab as mentioned in the issue.
Closes: #1653
=> Created warning for red coin and non-redcoin merging

WalletWasabi.Gui/Controls/WalletExplorer/ReceiveTabView.xaml
=> Fix Keyboard navigation in Address label field.

WalletWasabi.Gui/Controls/WalletExplorer/SendTabViewModel.cs
fixes: https://github.com/zkSNACKs/WalletWasabi/issues/1662
=> Fix the binding on Send Tab with suggestions

WalletWasabi.Tests/ExternalApiTests.cs
Broke the test: https://github.com/zkSNACKs/WalletWasabi/pull/1671
=> Fix blockcypher tests

WalletWasabi.Documentation/CodeCoverage.md, WalletWasabi.Documentation/FAQ.md, WalletWasabi.Documentation/Guides/HowToDebug.md, WalletWasabi.Documentation/Guides/InstallInstructions.md, WalletWasabi.Documentation/Guides/WasabiCodingGuidelines.md, WalletWasabi.Documentation/ManualTesting.md, WalletWasabi.Documentation/PasswordFinder.md, WalletWasabi.Documentation/Ports.md
Fix some spelling, grammar, incorrect path names, and added link to Coverage Gutters github page.
=> Fixes documentation grammar and spelling

WalletWasabi/Logging/Logger.cs
Closes https://github.com/zkSNACKs/WalletWasabi/pull/1684
=> Remove logger encryption

WalletWasabi.Backend/Controllers/ChaumianCoinJoinController.cs, WalletWasabi.Gui/Controls/WalletExplorer/CoinJoinTabView.xaml, WalletWasabi.Gui/Controls/WalletExplorer/CoinJoinTabViewModel.cs, WalletWasabi.Gui/Converters/AmountForegroundConverter.cs, WalletWasabi.Gui/Converters/BooleanOnOffConverter.cs, WalletWasabi.Gui/Converters/CoinItemExpanderColorConverter.cs, WalletWasabi.Gui/Converters/CoinJoinedVisibilityConverter.cs, WalletWasabi.Gui/Converters/CoinStatusBorderBrushConverter.cs, WalletWasabi.Gui/Converters/CoinStatusColorConverter.cs, WalletWasabi.Gui/Converters/CoinStatusForegroundConverter.cs, WalletWasabi.Gui/Converters/CoinStatusStringConverter.cs, WalletWasabi.Gui/Converters/FilterLeftStatusConverter.cs, WalletWasabi.Gui/Converters/InverseBooleanConverter.cs, WalletWasabi.Gui/Converters/MaxClearBoolStringConverter.cs, WalletWasabi.Gui/Converters/MoneyBrushConverter.cs, WalletWasabi.Gui/Converters/MoneyStringConverter.cs, WalletWasabi.Gui/Converters/PhaseStringConverter.cs, WalletWasabi.Gui/Converters/PrivacyLevelValueConverter.cs, WalletWasabi.Gui/Converters/StatusBarStatusStringConverter.cs, WalletWasabi.Gui/Converters/TimeSpanStringConverter.cs, WalletWasabi.Gui/Converters/TimeSpanVisibilityConverter.cs, WalletWasabi/Backend/Models/Responses/CcjRunningRoundState.cs, WalletWasabi/Exceptions/TypeArgumentException.cs, WalletWasabi/Models/ChaumianCoinJoin/CcjRound.cs, WalletWasabi/Services/CcjClient.cs
resolves https://github.com/zkSNACKs/WalletWasabi/issues/1427
resolves https://github.com/zkSNACKs/WalletWasabi/issues/1387
=> Implement countdown

WalletWasabi/Backend/Models/Responses/VersionsResponse.cs, WalletWasabi/Helpers/Constants.cs, WalletWasabi/WebClients/Wasabi/WasabiClient.cs
BackenMajordVersion  -> BackendMajorVersion
=> Spelling fix for variable name

WalletWasabi.Gui/Tabs/AboutView.xaml, WalletWasabi.Gui/Tabs/AboutViewModel.cs
I do not have an OSX computer, I'd appreciate if someone was able to test the functionality for it.
=> Add functionality to about page links

WalletWasabi.Gui/ViewModels/AddressViewModel.cs
Should be a small performance improvement
=> Only generate QR code when needed

WalletWasabi/Crypto/StringCipher.cs
This PR is for authenticating the encryption IV. Close #1631
@nopara73 could you request the guy who found this to take a look, please?
=> Authenticate initialization vector

WalletWasabi.Gui/Controls/WalletExplorer/CoinListView.xaml, WalletWasabi.Gui/Converters/PrivacyLevelValueConverter.cs, WalletWasabi.Gui/Icons/Icons.xaml
Closes #1129 
I couldn't find a super shield svg, if someone can I can change it.
Currently looks like:
=> Anonymity set over 9,000 easter egg

WalletWasabi.Gui/ViewModels/AddressViewModel.cs
On Receive Tab if you expand on or more coins the UI will freeze.
=> Fix hang on QR code generation

WalletWasabi.Gui/Controls/WalletExplorer/CoinListView.xaml, WalletWasabi.Gui/Controls/WalletExplorer/CoinListViewModel.cs
Closes: #1706
Some small refactoring changes to improve redability and reduce lines of code. Also made the total amount of selected btc yellow green for readability. It is currently not very noticeable when you toggle coins.
=> Fix incorrect selected coins checkbox state

WalletWasabi/TorSocks5/TorSocks5Client.cs
As suggested by @benthecarman in #1736.
=> Edit HandshakeAsync method

WalletWasabi.Gui/Controls/WalletExplorer/PinPadViewModel.cs, WalletWasabi.Gui/Controls/WalletExplorer/SendTabViewModel.cs, WalletWasabi.Gui/Controls/WalletExplorer/WalletActionViewModel.cs, WalletWasabi.Gui/Controls/WalletExplorer/WalletViewModel.cs, WalletWasabi.Gui/Tabs/WalletManager/LoadWalletViewModel.cs, WalletWasabi.Gui/ViewModels/WasabiDocumentTabViewModel.cs
@NicolasDorier When you messed with the global, the PinPadView was ruined, this makes people not be able to use Trezor. This PR attempts to fix it.
=> Fix PinPadView Initialization

WalletWasabi/Helpers/Constants.cs
The 1.1.6 prerelease failed testing.
=> Downgrade ClientVersion

WalletWasabi.Gui/Controls/ExtendedTextBox.cs, WalletWasabi.Gui/Controls/WalletExplorer/CoinListViewModel.cs, WalletWasabi.Gui/Controls/WalletExplorer/HistoryTabViewModel.cs, WalletWasabi.Gui/Controls/WalletExplorer/ReceiveTabViewModel.cs, WalletWasabi.Gui/Controls/WalletExplorer/SendTabViewModel.cs, WalletWasabi.Gui/Dialogs/CannotCloseDialogViewModel.cs, WalletWasabi.Gui/Program.cs, WalletWasabi.Gui/Shell/Commands/ExitCommands.cs, WalletWasabi.Gui/Tabs/WalletManager/GenerateWalletSuccessViewModel.cs, WalletWasabi.Gui/Tabs/WalletManager/GenerateWalletViewModel.cs, WalletWasabi.Gui/Tabs/WalletManager/LoadWalletViewModel.cs, WalletWasabi.Gui/Tabs/WalletManager/RecoverWalletViewModel.cs, WalletWasabi/Gma/QrCodeNet/Encoding/Masking/PatternFactory.cs, WalletWasabi/Models/BannedUtxoRecord.cs, WalletWasabi/Services/WalletService.cs, WalletWasabi/TorSocks5/Models/Fields/ByteArrayFields/AddrField.cs
Syntax is more succint and less compile-time overheard by not using lambdas
=> Performance: Using method groups instead of lamdas

WalletWasabi.Gui/Converters/LurkingWifeModeStringConverter.cs, WalletWasabi.Gui/ViewModels/AddressViewModel.cs
=> fix crashing when starting with Lurking Wife Mode enabled.

WalletWasabi.Documentation/PasswordFinder.md
helper text consistency and ease of reading
=> helper text consistency and copywriting

WalletWasabi.Gui/WalletWasabi.Gui.csproj, WalletWasabi.Gui/nuget.config
Release notes:
https://github.com/AvaloniaUI/avaloniaui.net/blob/master/wwwroot/blog/2019-07-06-avalonia-0.8.1-release.md
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/1201
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/1758
=> Avalonia 0.8.1

WalletWasabi.Gui/Controls/WalletExplorer/TransactionViewerView.xaml, WalletWasabi.Gui/Controls/WalletExplorer/TransactionViewerViewModel.cs
=> LurkingWifeMode on transaction view page

WalletWasabi.Backend/Config.cs, WalletWasabi.Gui/Config.cs, WalletWasabi.Gui/UiConfig.cs, WalletWasabi/Models/ChaumianCoinJoin/CcjRoundConfig.cs
I am planning to create a series of pull requests that is breaking down the following PRs and issues into small, reviewable parts.
https://github.com/zkSNACKs/WalletWasabi/pull/1739
https://github.com/zkSNACKs/WalletWasabi/pull/1740/
https://github.com/zkSNACKs/WalletWasabi/issues/1738
=> Use DeepEquals for config file change detection

WalletWasabi.Community/Dojo.md
He made a very good video explaining how to use Wasabi wallet.
=> BTC Sessions - White Belt

WalletWasabi.Gui/WalletWasabi.Gui.csproj
Updated to match the current github description and tags
=> Update project description and tags to match GitHub

WalletWasabi.Gui/Controls/WalletExplorer/TransactionViewerView.xaml
=> Fix lurking wife mode bug on transaction tab

WalletWasabi.Gui/Controls/WalletExplorer/CoinListViewModel.cs
Was throwing a bunch of exceptions without this
=> bugfix: add missing null check

WalletWasabi.Packager/NSubsys/NSubsysUtil.cs, WalletWasabi.Packager/NSubsys/PeUtility.cs
=> NSubsys update.

.editorconfig
All interfaces should be  IPascalCase.
=> Add interface naming rule

.editorconfig
To get rid of the suggestion to add `readonly` modifier.
=> Do not prefer readonly fields

WalletWasabi.Gui/Controls/WalletExplorer/HistoryTabView.xaml, WalletWasabi.Gui/Controls/WalletExplorer/HistoryTabViewModel.cs, WalletWasabi.Gui/Controls/WalletExplorer/TransactionInfo.cs, WalletWasabi.Gui/Controls/WalletExplorer/TransactionViewModel.cs
=> Confirmations on history's confirmed checkmark tooltip

WalletWasabi.Gui/Controls/WalletExplorer/CoinJoinTabViewModel.cs, WalletWasabi.Gui/Controls/WalletExplorer/SendTabViewModel.cs
Also use magic string instead of nameof.
=> Remove unnecessary lines

WalletWasabi.Gui/ManagedDialogs/ManagedFileChooserViewModel.cs
Fixes minor issue where file dialog crashes when there is some strange file name encoding in Linux.
=> fix crash with strange filename encoding,

WalletWasabi.Gui/Controls/WalletExplorer/TransactionViewerView.xaml, WalletWasabi.Gui/Controls/WalletExplorer/TransactionViewerViewModel.cs
=> Tx Id on transaction view page

WalletWasabi.Gui/Tabs/SettingsView.xaml, WalletWasabi.Gui/Tabs/WalletManager/GenerateWalletSuccessView.xaml, WalletWasabi.Gui/Tabs/WalletManager/LoadWalletView.xaml, WalletWasabi.Gui/Tabs/WalletManager/RecoverWalletView.xaml
Format xaml files (Remove extra spaces and lines).
=> Xaml formatting 2

WalletWasabi.Gui/ViewModels/StatusBarViewModel.cs
If a comment is necessary there then it should be edited.
=> Remove wrong comment

WalletWasabi/Gma/QrCodeNet/Encoding/DataEncodation/ECISet.cs
To get rid of the suggestion to remove redundant assignment.
=> Add pragma warning

WalletWasabi.Gui/Controls/WalletExplorer/SendTabViewModel.cs
Reverts zkSNACKs/WalletWasabi#1925
=> Revert "Remove redundant check"

WalletWasabi/Services/WalletService.cs
This PR reduces the amount of operations needed to process relevant transactions.
=> Refactoring - perf improvement

WalletWasabi/Services/WalletService.cs
Here we are checking tx index not id
=> Rename variable to fitting name

WalletWasabi/Services/WalletService.cs
Whenever we remove a coin from the coin list it has to be removed recursively.
=> Refactor coin removal

WalletWasabi/Services/WalletService.cs
=> Abort processing dust coins early

WalletWasabi.Gui/Shell/Commands/HelpCommands.cs, WalletWasabi.Gui/Tabs/AboutViewModel.cs
=> Move in-wallet FAQ links to the new site

WalletWasabi/KeyManagement/KeyManager.cs
This function doesn't return anything yet has documentation on what it returns
=> Remove useless comment

WalletWasabi.Gui/Controls/WalletExplorer/CoinListViewModel.cs
Looks like I missed this in #1948
=> Fix select all X checkbox functionality

WalletWasabi/Services/CcjCoordinator.cs
Was the variable supposed to be used for something?
=> Remove unused variable

WalletWasabi/Hwi/HwiProcessManager.cs
Fixes: https://github.com/zkSNACKs/WalletWasabi/issues/2080
=> Increase timeout of GetXpubAsync

WalletWasabi/Services/WalletService.cs
We were removing only one coin when the event can be raised when multiple coins were removed. Anyway, it was working fine.
=> Removes all coins

WalletWasabi/Helpers/Constants.cs
We refactored how we store bitcoins. @lontivero @molnard.
=> Change Coordinator address.

WalletWasabi.Gui/Controls/WalletExplorer/CoinViewModel.cs
HdPubKey of a coin can be null.
=> Check for null.

README.md
This adds a quick introduction paragraph to the main README, with the advantages for network and blockchain privacy, as well as a link to the docs.
=> [DOC] Add introduction to ReadMe

WalletWasabi.Backend/wwwroot/css/style.css, WalletWasabi.Backend/wwwroot/index.html
Cache busting query strings for static assets.
=> Cache busting CSS and Images

WalletWasabi.Packager/Program.cs
@benthecarman @lontivero You were involved with the PR that ruined it. This PR should be a nobrainer.
=> Fix version string in Packager

WalletWasabi.Gui/Controls/LockScreen/PinLockScreen.xaml.cs, WalletWasabi.Gui/Controls/LockScreen/PinLockScreenViewModel.cs
=> Delete PIN contents on refocus.

WalletWasabi/Helpers/Constants.cs
Closes https://github.com/zkSNACKs/WalletWasabi/issues/2227
=> Dump release version

WalletWasabi.Gui/Controls/WalletExplorer/CoinJoinTabViewModel.cs
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/2183
=> Prevent NRE

WalletWasabi/Hwi/HwiProcessManager.cs
Fixes #2312 
Very basic fix here, resolved it on my end, but I do not know any other implications of the modification.
=> Increase timeout of HWI Enumeration

WalletWasabi.Tests/UnitTests/PasswordTests.cs, WalletWasabi/Nito/AsyncEx/AsyncMutex.cs
- Remove the pw compatibility ERROR message from test console
- Asyncmutex fix.
=> Fix CI tests and remove error message from test console.

.github/workflows/ci.yml
Add the new GitHub-Actions feature to manage continuous integration.
Recreated PR: https://github.com/zkSNACKs/WalletWasabi/pull/2320
To fix the tests, this should be merged first: https://github.com/zkSNACKs/WalletWasabi/pull/2315
=> Introduce github actions - Continuous integration

WalletWasabi.Gui/ViewModels/AddressViewModel.cs
@jmacato in https://github.com/zkSNACKs/WalletWasabi/pull/2332 forgot to dispose and we didn't catch it in the review.
=> Dispose oaph

WalletWasabi/Logging/BenchmarkLogger.cs, WalletWasabi/Logging/Logger.cs, WalletWasabi/Stores/BitcoinStore.cs, WalletWasabi/Stores/IndexStore.cs
I decided to break down PR #2188 to reviewable parts. In this PR I simplify and improve logging a lot.
This adds a class that logs elapsed time.
=> Implement and use BenchmarkLogger (MempoolStore Breakdown Part 10) 

WalletWasabi.Gui/Behaviors/ClearPropertyOnLostFocusBehavior.cs, WalletWasabi.Gui/Behaviors/CommandOnEnterBehavior.cs, WalletWasabi.Gui/Behaviors/CommandOnFirstVisible.cs, WalletWasabi.Gui/Behaviors/CommandOnKeyDownBehavior.cs, WalletWasabi.Gui/Behaviors/CommandOnKeyUpBehavior.cs, WalletWasabi.Gui/Behaviors/CommandOnPointerEnterLeaveBehavior.cs, WalletWasabi.Gui/Behaviors/GreyOutOnDisabledBehavior.cs, WalletWasabi.Gui/Behaviors/PasteAddressOnClickBehavior.cs, WalletWasabi.Gui/Behaviors/SuggestionBehavior.cs, WalletWasabi.Gui/Controls/EditableTextBlock.cs, WalletWasabi.Gui/Controls/ExtendedListBox.cs, WalletWasabi.Gui/Controls/ExtendedTextBox.cs, WalletWasabi.Gui/Controls/MultiTextBox.cs, WalletWasabi.Gui/Controls/WalletExplorer/CoinJoinTabViewModel.cs, WalletWasabi.Gui/Controls/WalletExplorer/HistoryTabViewModel.cs, WalletWasabi.Gui/Controls/WalletExplorer/ReceiveTabViewModel.cs, WalletWasabi.Gui/Controls/WalletExplorer/SendTabViewModel.cs, WalletWasabi.Gui/Controls/WalletExplorer/WalletInfoViewModel.cs, WalletWasabi.Gui/Controls/WalletExplorer/WalletViewModel.cs, WalletWasabi.Gui/Tabs/WalletManager/WalletManagerViewModel.cs, WalletWasabi.Gui/ViewModels/AddressViewModel.cs
This is only indentation changes.
=> Correct indentation

.editorconfig, WalletWasabi.Tests/UnitTests/IoTests.cs
https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-8#static-local-functions
=> Add rule to make local functions static

WalletWasabi.Gui/Global.cs, WalletWasabi.Tests/IntegrationTests/P2pTests.cs, WalletWasabi.Tests/IntegrationTests/RegTests.cs, WalletWasabi/Services/TransactionProcessor.cs, WalletWasabi/Services/WalletService.cs, WalletWasabi/Stores/BitcoinStore.cs
TxStore Breakdown: https://github.com/zkSNACKs/WalletWasabi/pull/2374/
=> Put MempoolService and MempoolBehavior to BitcoinStore

WalletWasabi.Gui/Controls/WalletExplorer/HistoryTabViewModel.cs, WalletWasabi/Models/ConcurrentHashSet.cs, WalletWasabi/Models/TransactionSummaryData.cs, WalletWasabi/Services/TransactionHistoryBuilder.cs, WalletWasabi/Services/WalletService.cs
This PR started as an attempt to clean a bit the `History` building algorithm but I realized the performance could be improved in many ways so I did it. Finally, I moved the code from the `ViewModel` because it is clear it shouldn't be there.
The best way to review this PR is going commit by commit because blocks were moved.
=> Improve history code

WalletWasabi.Backend/wwwroot/index.html
Dump version to v1.1.9.2.
Related: https://github.com/zkSNACKs/WasabiDoc/pull/250
=> Dump version to v1.1.9.2

WalletWasabi.Gui/Controls/WalletExplorer/SendTabViewModel.cs
=> Fix manual fee box not allowing changes

WalletWasabi.Gui/Controls/LockScreen/LockScreenViewModel.cs, WalletWasabi.Gui/Controls/WalletExplorer/ReceiveTabView.xaml, WalletWasabi.Gui/Controls/WalletExplorer/SendTabViewModel.cs
Closes https://github.com/zkSNACKs/WalletWasabi/pull/2205
=> Improve label explanation

WalletWasabi.Gui/Controls/WalletExplorer/SendTabViewModel.cs
This resets the UserFeeText to 1 when resetting the UI (After sending or building a transaction).
PS: I am not sure if this is the best way to do it.
=> Don't touch UserFeeText

WalletWasabi.Backend/wwwroot/index.html
Suggested by @RiccardoMasutti here: https://github.com/zkSNACKs/WalletWasabi/pull/2326#issuecomment-535509127
=> Add canonical to website

WalletWasabi/CoinJoin/Client/Clients/AliceClient.cs, WalletWasabi/CoinJoin/Client/Clients/CoinJoinClient.cs, WalletWasabi/CoinJoin/Common/Crypto/SchnorrKey.cs, WalletWasabi/CoinJoin/Common/Crypto/SchnorrPubKey.cs, WalletWasabi/CoinJoin/Common/Models/RoundStateResponse.cs, WalletWasabi/CoinJoin/Coordinator/MixingLevels/MixingLevel.cs, WalletWasabi/CoinJoin/Coordinator/MixingLevels/MixingLevelCollection.cs, WalletWasabi/Extensions/NBitcoinExtensions.cs
Rename folder `Crytpo` to `Crypto` (added in #2442)
=> Correct folder name

WalletWasabi/CoinJoin/Coordinator/Coordinator.cs, WalletWasabi/TorSocks5/TorHttpClient.cs, WalletWasabi/TorSocks5/TorSocks5Client.cs, WalletWasabi/WebClients/BlockCypher/BlockCypherClient.cs, WalletWasabi/WebClients/SmartBit/SmartBitClient.cs
As suggested [here](https://github.com/zkSNACKs/WalletWasabi/pull/2447#discussion_r336805474).
=> Clean deconstructor's commented code

WalletWasabi.Tests/UnitTests/Transactions/TransactionFactoryTests.cs, WalletWasabi/Transactions/TransactionBuilding/SmartCoinSelector.cs
When cluster's labes is empty a DivideByZeroException is thrown. This PR fixes that.
=> Fix divide by zero

WalletWasabi.Tests/UnitTests/Transactions/TransactionProcessorTests.cs
This PR contains only an Unit Test that verifies the case where a replaceable transaction (rbf) is replaced by a new transaction that spend one additional coin.
=> Test for bump fee processing

WalletWasabi.Gui/Controls/WalletExplorer/TransactionBroadcasterViewModel.cs, WalletWasabi.Gui/Controls/WalletExplorer/TransactionViewerViewModel.cs, WalletWasabi.Gui/ManagedDialogs/ManagedFileChooserViewModel.cs, WalletWasabi.Gui/Tabs/WalletManager/LoadWalletViewModel.cs
There is a bug in master branch that makes the file chooser to nullify the file name. This PR fixes that and also make it open in a better location in linux (where the coldcard SD card probably is mounted)
=> Fix managed file chooser

WalletWasabi.Tests/UnitTests/Transactions/TransactionProcessorTests.cs, WalletWasabi/Coins/CoinsRegistry.cs, WalletWasabi/Transactions/TransactionProcessor.cs
Currently, when a replacement transaction is processed (a transaction that spends at least one coin already spent by a previous transaction signaling rbf) we remove the coins created by the replaced transaction but we don't re-add the coins that it destroyed. This assumes the replacement transaction always spends at least the same set of coins that the replaced transaction did, but that's not correct.
This PR undo the replaced transaction before processing its replacement. There is a test for making the problem evident. 
Closes #2493
=> Fix RBF undoing process

WalletWasabi.Gui/Controls/StatusBar.xaml, WalletWasabi.Gui/Icons/Icons.xaml
Move remaining DrawingGroup on StatusBar to Icons.xaml. Also change the flag colors depending whether it's a normal update or a forking update. 
cc: @molnard
=> StatusBar fixes (Part III)

WalletWasabi/Microservices/Binaries/README.md
now that bitcoind is in the binaries too, it should be reflected in the README header, it is already in the content.
=> change header, update both hwi and bitcoind

WalletWasabi.Gui/Controls/WalletExplorer/CoinViewModel.cs, WalletWasabi/Blockchain/TransactionOutputs/SmartCoin.cs
Fixes: https://github.com/zkSNACKs/WalletWasabi/issues/2535
Closes: https://github.com/zkSNACKs/WalletWasabi/pull/2539
=> Proper triggering of Confirmations in CoinList

WalletWasabi.Tests/IntegrationTests/RegTests.cs
In debug mode, this was failing.
=> Fix RegTest - CcjTestAsync

.editorconfig, WalletWasabi.Gui/Controls/WalletExplorer/SendTabViewModel.cs, WalletWasabi.Gui/Tabs/WalletManager/RecoverWalletViewModel.cs, WalletWasabi/Blockchain/Analysis/FeesEstimation/FeeProviders.cs, WalletWasabi/Gma/QrCodeNet/Encoding/ReedSolomon/Polynomial.cs, WalletWasabi/Mono/OptionSet.cs
https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-8#indices-and-ranges
=> Add rule to use index operator

WalletWasabi.Backend/wwwroot/css/_variables.scss
@mayankchhabra Is this correct?
=> Remove extra semicolon

WalletWasabi/BitcoinCore/P2pNode.cs
@nopara73 is this what you mean in #2554?
=> Catch and log uncaught node exceptions

WalletWasabi.Tests/UnitTests/Transactions/TransactionProcessorTests.cs
A few more test for `TransactionStore`
=> More test for TransactionStore

WalletWasabi.Gui/Controls/WalletExplorer/ReceiveTabViewModel.cs, WalletWasabi.Gui/Controls/WalletExplorer/WalletViewModel.cs, WalletWasabi/Services/WalletService.cs
=> try-catch event subscribers

WalletWasabi.Gui/Controls/WalletExplorer/CoinListViewModel.cs, WalletWasabi.Gui/Controls/WalletExplorer/CoinViewModel.cs
Refactoring CoinListViewModel and CoinViewModel. This is one of the slowest element what we have now in Wasabi. Also, we got a strange issue here.
Closes: https://github.com/zkSNACKs/WalletWasabi/issues/2536
=> Refactor CoinListViewModel

WalletWasabi.Backend/wwwroot/index.html
=> Update .onion link with SameAs attribute

WalletWasabi.Backend/Controllers/BlockchainController.cs, WalletWasabi.Backend/Controllers/ChaumianCoinJoinController.cs, WalletWasabi/CoinJoin/Coordinator/Coordinator.cs
```bash
curl -X GET "http://127.0.0.1:37127/api/v3/btc/ChaumianCoinJoin/unconfirmedcoinjoins" -H  "accept: */*"
```
```
[
"fd174c3849724754150408c2fbdd66e44f78e21e9853c647c9d91323634a5384",
"9eee94b3b3a683cf2fe3d8a2579179ed06c889d03258a036bde751460e60b8b9",
"187f30eac75cb16f087b8f30b1537262ab93d15a54c40893ca638e2ccf7f575a",
"2bebcbfe271add2baea9a8aff010b0768d886b3b2b023d0898b830bb54134360",
"a21081b0a68344dbe3e85cf25b68a3894515f2e178e845fab66aaa46157ddb6a",
"83491c863cdf271a4b9b0945fed65f4777bc6b3550d1ffab04b9671db9b48c3e",
"b5d946beb7252faf502bdfba7dc664b659c32bf3ce107eb8c1a1b415bf8d4f28"
]
```
=> New GetUnconfirmedCoinJoins API request

WalletWasabi.Gui/ViewModels/AddressViewModel.cs
It is to remove the `Dispatcher.UIThread.PostLogException` and use Rx to solve the issue.
=> Code clean ReceiveAddress QR code generation

WalletWasabi.Gui/Controls/WalletExplorer/SendTabView.xaml, WalletWasabi.Gui/Controls/WalletExplorer/SendTabViewModel.cs, WalletWasabi/Blockchain/Analysis/FeesEstimation/AllFeeEstimate.cs, WalletWasabi/Blockchain/TransactionBuilding/FeeStrategy.cs, WalletWasabi/Blockchain/Transactions/TransactionFactory.cs, WalletWasabi/CoinJoin/Coordinator/Rounds/CoordinatorRound.cs
=> Replace sat/byte by sat/vByte

WalletWasabi.Gui/Controls/WalletExplorer/CoinListViewModel.cs, WalletWasabi.Tests/IntegrationTests/RegTests.cs, WalletWasabi.Tests/UnitTests/Transactions/TransactionProcessorTests.cs, WalletWasabi/Blockchain/TransactionBroadcasting/TransactionBroadcaster.cs, WalletWasabi/Blockchain/TransactionProcessing/DoubleSpendReceivedEventArgs.cs, WalletWasabi/Blockchain/TransactionProcessing/ReplaceTransactionReceivedEventArgs.cs, WalletWasabi/Blockchain/TransactionProcessing/TransactionProcessor.cs, WalletWasabi/Blockchain/Transactions/ReplaceTransactionReceivedEventArgs.cs, WalletWasabi/Blockchain/Transactions/TransactionProcessor.cs, WalletWasabi/CoinJoin/Client/CoinJoinProcessor.cs, WalletWasabi/Services/WalletService.cs
Safe changes from https://github.com/zkSNACKs/WalletWasabi/pull/2664
=> TransactionProcessor Safe Refactoring

WalletWasabi.Tests/IntegrationTests/RegTests.cs, WalletWasabi/Blockchain/TransactionBroadcasting/TransactionBroadcaster.cs, WalletWasabi/Blockchain/TransactionProcessing/TransactionProcessor.cs, WalletWasabi/Blockchain/Transactions/SmartTransaction.cs, WalletWasabi/CoinJoin/Client/CoinJoinProcessor.cs, WalletWasabi/Services/WalletService.cs
For https://github.com/zkSNACKs/WalletWasabi/pull/2664, https://github.com/zkSNACKs/WalletWasabi/pull/2661 and https://github.com/zkSNACKs/WalletWasabi/issues/2641
=> Make transaction processor lock private

WalletWasabi.Backend/wwwroot/index.html
Following https://github.com/zkSNACKs/WalletWasabi/issues/2662
=> Update MacOS version on website

WalletWasabi/BitcoinCore/Configuration/CoreConfig.cs
https://github.com/zkSNACKs/WalletWasabi/pull/2495#discussion_r342361046
=> Refactor code

WalletWasabi.Gui/Tabs/SettingsView.xaml
=> Add experimental explanation to bitcoin core feature

WalletWasabi.Gui/Controls/ExtendedTextBox.cs
=> fix multiple cursors in extended textbox.

WalletWasabi.Gui/WalletWasabi.Gui.csproj
=> update to avalonia rc.1

WalletWasabi.Gui/Tabs/SettingsViewModel.cs
=> Improve PIN verifications

WalletWasabi.Gui/Controls/WalletExplorer/SendTabViewModel.cs, WalletWasabi/Helpers/Constants.cs
Closes #2739
There were two exception: OutOfRangeException and OverflowException.
=> Validate user fee

WalletWasabi.Gui/Controls/WalletExplorer/WalletInfoViewModel.cs, WalletWasabi/Extensions/ExceptionExtensions.cs
=> Use friendly error

WalletWasabi.Gui/Controls/WalletExplorer/CoinJoinTabViewModel.cs
=> Empty password textbox after dequeuing

CONTRIBUTING.md
@danwalmsley Is this what you asked for?
=> Add code-behind rule into coding conventions

WalletWasabi.Gui/Controls/WalletExplorer/SendTabViewModel.cs, WalletWasabi.Gui/Converters/AmountForegroundConverter.cs
Closes #2736
This PR notifies the user when the fee percentage is equal or higher than 100%.
=> Notify when fee% is higher than 100

WalletWasabi.Backend/wwwroot/index.html
=> Update CoinJoin link to reflect docs changes

WalletWasabi.Backend/InitConfigStartupTask.cs, WalletWasabi.Backend/WebsiteTorifier.cs
=> Replace Blockstream.info clearnet links to .onion

WalletWasabi.Gui/Controls/LockScreen/PinLockScreenViewModel.cs
=> Throttle PIN check notification from 1 second to 2.5 seconds.

WalletWasabi.Gui/Tabs/SettingsViewModel.cs
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/2773
=> set initial value for LockScreenPinHash

WalletWasabi.Backend/WebsiteTorifier.cs
=> Fix API .onion redirect

WalletWasabi.Gui/Controls/WalletExplorer/HistoryTabView.xaml, WalletWasabi.Gui/Controls/WalletExplorer/HistoryTabViewModel.cs, WalletWasabi.Gui/Controls/WalletExplorer/ReceiveTabView.xaml, WalletWasabi.Gui/Controls/WalletExplorer/ReceiveTabViewModel.cs
Fixes: https://github.com/zkSNACKs/WalletWasabi/issues/2800
=> Hide context menu is no item selected on Receive Tab

WalletWasabi.Gui/Controls/WalletExplorer/SendTabViewModel.cs
Closes https://github.com/zkSNACKs/WalletWasabi/issues/2841
Closes https://github.com/zkSNACKs/WalletWasabi/issues/2768
=> fix amount issue

WalletWasabi.Gui/Global.cs
Resolves https://github.com/zkSNACKs/WalletWasabi/issues/2843
Resolves https://github.com/zkSNACKs/WalletWasabi/issues/2825
Resolves https://github.com/zkSNACKs/WalletWasabi/issues/2835
Note: ugly
=> Exit when global fails to initialize.

WalletWasabi.Gui/Controls/WalletExplorer/SendTabViewModel.cs, WalletWasabi/Blockchain/TransactionBroadcasting/TransactionBroadcaster.cs
Add missing exception handler and improve logging.
=> [WIP] Better logging on SendTab

WalletWasabi.Gui/WalletWasabi.Gui.csproj
Fixes #2833,  
Fixes #2838
Fixes #2837
Fixes #2761 
and allows:
#2724 to be merged.
=> Update to Avalonia 0.9 RC2

WalletWasabi.Backend/wwwroot/index.html, WalletWasabi/Helpers/Constants.cs
First, merge this! https://github.com/zkSNACKs/WalletWasabi/pull/2853
Also https://github.com/zkSNACKs/WasabiDoc/pull/397
=> Dump client version for v1.1.10

WalletWasabi.Gui/Tabs/WalletManager/LoadWalletViewModel.cs, WalletWasabi/Helpers/NBitcoinHelpers.cs
To have a clean git history, original PR: https://github.com/zkSNACKs/WalletWasabi/pull/2873
=> Fix ColdCard fingerprint mystery

WalletWasabi.Gui/Global.cs
This PR means if an exception is thrown before Global.Initialise is called, we wont hang forever.
=> Dont hang if we throw exception in AppMainAsync

WalletWasabi/Bases/ConfigBase.cs
Cherry picked https://github.com/zkSNACKs/WalletWasabi/pull/2879 and applied https://github.com/zkSNACKs/WalletWasabi/pull/2879#discussion_r359642528.
Nobrainer. Merging.
Closes https://github.com/zkSNACKs/WalletWasabi/issues/2863
Closes https://github.com/zkSNACKs/WalletWasabi/pull/2879
=> Recover from config corruption

WalletWasabi.Gui/Tabs/WalletManager/LoadWalletViewModel.cs, WalletWasabi/Helpers/NBitcoinHelpers.cs
=> Merge backport to master

WalletWasabi/Blockchain/BlockFilters/IndexBuilderService.cs
integration tests pass
Closes https://github.com/zkSNACKs/WalletWasabi/issues/2887
=> Fix off by one (resulting filter getting stuck)

WalletWasabi.Gui/WalletWasabi.Gui.csproj
Cherry picked for backport: https://github.com/zkSNACKs/WalletWasabi/pull/2891
=> update avalonia to 0.9.1 with egl fixes.

WalletWasabi.Gui/Global.cs, WalletWasabi.Gui/WalletWasabi.Gui.csproj
Fixes #2856
Fixes #2836 
Same, closes https://github.com/zkSNACKs/WalletWasabi/pull/2891
=> Merge backport into master

WalletWasabi.Gui/Controls/SuggestLabelView.xaml, WalletWasabi.Gui/Controls/WalletExplorer/CoinListView.xaml, WalletWasabi.Gui/Controls/WalletExplorer/CoinViewModel.cs, WalletWasabi.Gui/Controls/WalletExplorer/HistoryTabView.xaml, WalletWasabi.Gui/Controls/WalletExplorer/ReceiveTabView.xaml, WalletWasabi.Gui/Controls/WalletExplorer/ReceiveTabViewModel.cs, WalletWasabi.Gui/Controls/WalletExplorer/SendTabViewModel.cs, WalletWasabi/Blockchain/Keys/KeyManager.cs
Closes #2872
Should I also rename the classes and variables where `Label` was used?
=> Replace 'Label' by 'Observers'

WalletWasabi.Backend/Controllers/ChaumianCoinJoinController.cs, WalletWasabi.Gui/Global.cs, WalletWasabi.Tests/IntegrationTests/RegTests.cs, WalletWasabi.Tests/UnitTests/BitcoinCore/ConfigTests.cs, WalletWasabi.Tests/UnitTests/BitcoinCore/ConfigTranslatorTests.cs, WalletWasabi/BitcoinCore/Configuration/CoreConfig.cs, WalletWasabi/BitcoinCore/Configuration/CoreConfigTranslator.cs, WalletWasabi/BitcoinCore/Configuration/NetworkTranslator.cs, WalletWasabi/BitcoinCore/Configuration/Whitening/WhiteBind.cs, WalletWasabi/BitcoinCore/Configuration/Whitening/WhiteEntry.cs, WalletWasabi/BitcoinCore/Configuration/Whitening/WhiteList.cs, WalletWasabi/BitcoinCore/CoreNode.cs, WalletWasabi/BitcoinCore/IRPCClient.cs, WalletWasabi/BitcoinCore/Monitoring/RpcFeeProvider.cs, WalletWasabi/BitcoinCore/Processes/BitcoindRpcProcessBridge.cs, WalletWasabi/CoinJoin/Coordinator/Coordinator.cs, WalletWasabi/CoinJoin/Coordinator/Rounds/CoordinatorRound.cs, WalletWasabi/Extensions/RPCClientExtensions.cs, WalletWasabi/Helpers/Constants.cs, WalletWasabi/Microservices/Binaries/README.md, WalletWasabi/WalletWasabi.csproj
Reverts zkSNACKs/WalletWasabi#2918
This should be cherry-pickable to backport?
=> Revert "Revert "Upgrade to Bitcoin Core 19 + Small Improvements""

WalletWasabi.Gui/Controls/Spinner.xaml, WalletWasabi.Gui/Tabs/SettingsView.xaml
See  https://github.com/AvaloniaUI/Avalonia/pull/2393 and https://github.com/AvaloniaUI/Avalonia/pull/2163.
=> Replace obsolete Avalonia UI controls/properties

WalletWasabi.Gui/Models/StatusBarStatuses/Status.cs, WalletWasabi/Bases/ByteArraySerializableBase.cs, WalletWasabi/Bases/OctetSerializableBase.cs, WalletWasabi/BitcoinCore/Monitoring/RpcStatus.cs, WalletWasabi/Blockchain/Analysis/Clustering/Cluster.cs, WalletWasabi/Blockchain/Analysis/Clustering/SmartLabel.cs, WalletWasabi/Blockchain/Analysis/FeesEstimation/AllFeeEstimate.cs, WalletWasabi/Blockchain/Keys/HdPubKey.cs, WalletWasabi/Blockchain/TransactionOutputs/SmartCoin.cs, WalletWasabi/Blockchain/TransactionOutputs/TxoRef.cs, WalletWasabi/Blockchain/Transactions/SmartTransaction.cs, WalletWasabi/CoinJoin/Common/Crypto/SchnorrKey.cs, WalletWasabi/CoinJoin/Common/Crypto/SchnorrPubKey.cs, WalletWasabi/CoinJoin/Coordinator/MixingLevels/MixingLevel.cs, WalletWasabi/Http/Models/HttpProtocol.cs, WalletWasabi/Hwi/Models/HwiOption.cs, WalletWasabi/Models/UpdateStatus.cs
https://github.com/MetacoSA/NBitcoin/pull/799/files#r362458401
=> Improve IEquitable implementation

WalletWasabi.Gui/Models/ShieldState.cs, WalletWasabi/Blockchain/Keys/KeyManager.cs
These methods are used only in the `KeyManager` class.
=> Change access modifier to private

WalletWasabi.Backend/wwwroot/css/style.css, WalletWasabi.Backend/wwwroot/index.html
- add new menu element "get wasabi" cta as anchor link
- change navbar to fixed to top
- add padding to "available" and "faq" section, couse the navbar covered this
- fix menu elements on smaller than 991 px couse the new cta is bigger
=> Add new menu element and fix navbar

CONTRIBUTING.md
Some advice on async Main, Binding expressions in Xaml and MVVM pattern.
=> Add some advice for UI development

WalletWasabi.Gui/Controls/WalletExplorer/BuildTabView.xaml, WalletWasabi.Gui/Controls/WalletExplorer/BuildTabView.xaml.cs, WalletWasabi.Gui/Controls/WalletExplorer/BuildTabViewModel.cs, WalletWasabi.Gui/Controls/WalletExplorer/SendControlView.xaml, WalletWasabi.Gui/Controls/WalletExplorer/SendControlView.xaml.cs, WalletWasabi.Gui/Controls/WalletExplorer/SendControlViewModel.cs, WalletWasabi.Gui/Controls/WalletExplorer/SendTabView.xaml, WalletWasabi.Gui/Controls/WalletExplorer/SendTabView.xaml.cs, WalletWasabi.Gui/Controls/WalletExplorer/SendTabViewModel.cs, WalletWasabi.Gui/Controls/WalletExplorer/WalletExplorerView.xaml, WalletWasabi.Gui/Controls/WalletExplorer/WalletViewModel.cs
There was a lot of file renaming in this PR: https://github.com/zkSNACKs/WalletWasabi/pull/2967
Unfortunately, Visual Studio does not use the proper rename operation for git so I used Tortoise git separately for this. However, as you can see GitHub still displays the diff wrongly because it is bugous. If you rename a file then create a new one with the same name, git diff will not handle it.
REVIEW TIP:
1. Select only the first commit, review. https://github.com/zkSNACKs/WalletWasabi/pull/2990/commits/87b5e3506209a4e28c7c59e5ff98b1cbd554a668
2. Select the remaining commits, review. https://github.com/zkSNACKs/WalletWasabi/pull/2990/files/87b5e3506209a4e28c7c59e5ff98b1cbd554a668..5d8cf0189768eb8b8e36492a2ddbb3c55b5d0c2f
=> Separate Send and Build tab ViewModels 2

WalletWasabi.Backend/wwwroot/index.html
To merge before redirect the entire website from www to non-www (#2730)
=> Update Facebook and Twitter Opengraph images

WalletWasabi.Gui/Controls/WalletExplorer/CoinViewModel.cs, WalletWasabi.Gui/Controls/WalletExplorer/HistoryTabViewModel.cs, WalletWasabi.Gui/Controls/WalletExplorer/PinPadViewModel.cs, WalletWasabi.Gui/Controls/WalletExplorer/ReceiveTabViewModel.cs, WalletWasabi.Gui/Controls/WalletExplorer/SendControlViewModel.cs, WalletWasabi.Gui/Controls/WalletExplorer/SendTabViewModel.cs, WalletWasabi.Gui/Controls/WalletExplorer/TransactionBroadcasterViewModel.cs, WalletWasabi.Gui/Controls/WalletExplorer/TransactionViewModel.cs, WalletWasabi.Gui/Controls/WalletExplorer/TransactionViewerViewModel.cs, WalletWasabi.Gui/Tabs/WalletManager/GenerateWalletViewModel.cs, WalletWasabi.Gui/Tabs/WalletManager/LoadWalletViewModel.cs, WalletWasabi.Gui/Tabs/WalletManager/RecoverWalletViewModel.cs, WalletWasabi.Gui/ViewModels/AddressViewModel.cs
This PR is for logging the errors first and then display the UI notification using the user-friendly message (that by default is the same message than before).
=> Use user-friendly messages for errors

WalletWasabi.Tests/UnitTests/Hwi/HwiProcessBridgeMock.cs
Insert parenthesis to make the code more readable.
=> Declare precedence

WalletWasabi.Documentation/BackendDeployment.md
=> Increase open files limit

WalletWasabi.Documentation/WasabikaCodex.md
I would like to refactor our project management system.
Problems : https://miro.com/app/board/o9J_kw6ixFo=/
Refactoring internals:
https://github.com/zkSNACKs/WalletWasabi/issues/2359
Roadmap:
https://github.com/zkSNACKs/Meta/issues/68
Sources: 
https://github.com/nopara73/ForeverAloneProgramming
https://gist.github.com/molnard/a2fa16c5a3d5931b78b79ef336cef73a
=> Refactor Project Management

WalletWasabi.QualityGate/Program.cs, WalletWasabi.QualityGate/WalletWasabi.QualityGate.csproj, WalletWasabi.sln, azure-pipelines-quality.yml
Just experimenting how to make CI fail. Not for review.
Design decisions
- I decided to go with Linux because if we would want to script it, then we will find examples for bash scripts more often than for other platforms.
=> Add Quality Gate

WalletWasabi/Bases/ConfigBase.cs
=> Catch all JsonException when reading json config files

WalletWasabi.Backend/Config.cs, WalletWasabi.Backend/Controllers/ChaumianCoinJoinController.cs, WalletWasabi.Documentation/BackendDeployment.md, WalletWasabi/CoinJoin/Coordinator/Rounds/CoordinatorRound.cs, WalletWasabi/CoinJoin/Coordinator/Rounds/CoordinatorRoundConfig.cs, WalletWasabi/Helpers/Constants.cs
Reasoning: https://twitter.com/6102bitcoin/status/1223226608070414336
=> Fetch Coordinator Address from ExtPubKey

WalletWasabi.Backend/Controllers/ChaumianCoinJoinController.cs, WalletWasabi/Backend/Models/FilterModel.cs, WalletWasabi/Helpers/PasswordHelper.cs, WalletWasabi/TorSocks5/Models/Messages/TorSocks5Request.cs, WalletWasabi/TorSocks5/Models/Messages/TorSocks5Response.cs, WalletWasabi/TorSocks5/Models/Messages/UsernamePasswordRequest.cs, WalletWasabi/TorSocks5/TorSocks5Client.cs
This PR replaces a few `IEnumerable.Skip` and `IEnumerable.Take` by ranges.
=> Use c# 8 ranges

WalletWasabi.Gui/WalletWasabi.Gui.csproj
Avalonia Update Includes:
- OSX rendering updates, so that we cant get deadlocks.
- OSX exception swallowing is now a thing of the past.
- OSX wont crash if your in full screen mode and you close application
Further info on 0.9.3 Avalonia release here:
https://github.com/AvaloniaUI/Avalonia/releases
=> update avalonia to 0.9.3

WalletWasabi.Tests/UnitTests/NBitcoinTests.cs
https://www.codefactor.io/repository/github/zksnacks/walletwasabi/issues?category=Style&groupId=93
=> Fix 'Single line comments must begin with single space issue'

WalletWasabi/Blockchain/TransactionOutputs/CoinsRegistry.cs, WalletWasabi/Blockchain/TransactionProcessing/TransactionProcessor.cs
This replaces https://github.com/zkSNACKs/WalletWasabi/pull/3074
It improves the transaction processing time a lot. You can see some numbers here: https://github.com/zkSNACKs/WalletWasabi/pull/2532#issuecomment-585920700
=> Improve double spending detection performance

WalletWasabi.Gui/Models/StatusBarStatuses/Status.cs, WalletWasabi/Blockchain/TransactionOutputs/SmartCoin.cs, WalletWasabi/Blockchain/TransactionOutputs/TxoRef.cs, WalletWasabi/CoinJoin/Common/Crypto/SchnorrKey.cs, WalletWasabi/CoinJoin/Common/Crypto/SchnorrPubKey.cs, WalletWasabi/CoinJoin/Coordinator/MixingLevels/MixingLevel.cs, WalletWasabi/Hwi/Models/HwiOption.cs, WalletWasabi/Models/UpdateStatus.cs
Fixes: https://github.com/zkSNACKs/WalletWasabi/issues/2973
Tests are fine. 
I didn't change the code here: https://github.com/zkSNACKs/WalletWasabi/blob/master/WalletWasabi/Blockchain/Analysis/FeesEstimation/AllFeeEstimate.cs#L79
=> Refactor GetHashCode to ( tuple )GetHashCode

WalletWasabi.Tests/UnitTests/Transactions/TransactionFactoryTests.cs, WalletWasabi/Services/WalletService.cs
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/3086 by doing the test deterministic.
=> Make SelectLockTimeForTransaction test deterministic

WalletWasabi.Gui/Controls/LockScreen/PinLockScreenViewModel.cs, WalletWasabi.Gui/Helpers/NotificationHelpers.cs, WalletWasabi.Gui/Tabs/SettingsViewModel.cs
This is the follow up to #3097 and unifies the notification messages.
=> unify notification messages

WalletWasabi/Blockchain/TransactionProcessing/TransactionProcessor.cs
This is a break down of PR #3105
- master: 1:04
- this branch: 0:38
This is also necessary because when we later want to send from one wallet to another in a coinjoin, the old algorithm would've failed to mark those txs own coinjoins.
=> Improve Load Speed: CJ Heuristic (1.7x faster)

WalletWasabi.Tests/IntegrationTests/RegTests.cs
Some steps were removed in #3109
=> Trivial: Edit comments number

WalletWasabi.Gui/CommandLine/CommandInterpreter.cs, WalletWasabi.Gui/Controls/SuggestLabelViewModel.cs, WalletWasabi.Gui/Controls/WalletExplorer/CoinJoinTabViewModel.cs, WalletWasabi.Gui/Controls/WalletExplorer/CoinListViewModel.cs, WalletWasabi.Gui/Controls/WalletExplorer/CoinViewModel.cs, WalletWasabi.Gui/Controls/WalletExplorer/HistoryTabViewModel.cs, WalletWasabi.Gui/Controls/WalletExplorer/ReceiveTabViewModel.cs, WalletWasabi.Gui/Controls/WalletExplorer/SendControlViewModel.cs, WalletWasabi.Gui/Controls/WalletExplorer/WalletExplorerViewModel.cs, WalletWasabi.Gui/Controls/WalletExplorer/WalletViewModel.cs
Quoting @danwalmsley from https://github.com/zkSNACKs/WalletWasabi/pull/3116:
> This is no way this PR can be broken down any further.
Challenge accepted!
=> Give WalletService to wallet dependent ViewModels

WalletWasabi.Tests/UnitTests/Transactions/TransactionProcessorTests.cs, WalletWasabi/Blockchain/Analysis/Clustering/Cluster.cs, WalletWasabi/Blockchain/TransactionOutputs/CoinsRegistry.cs, WalletWasabi/Blockchain/TransactionOutputs/CoinsView.cs, WalletWasabi/Blockchain/TransactionOutputs/SmartCoin.cs, WalletWasabi/Blockchain/TransactionProcessing/TransactionProcessor.cs, WalletWasabi/Blockchain/Transactions/TransactionFactory.cs, WalletWasabi/CoinJoin/Client/Clients/CoinJoinClient.cs
As these two PRs modify the exact same code, this PR merges them together.
Closes https://github.com/zkSNACKs/WalletWasabi/pull/3080
Closes https://github.com/zkSNACKs/WalletWasabi/pull/3129
Measuring my own wallet load 3-3 times in release:
```
master: 21.59s, 21.71s, 22.17s
this pr: 18.06s, 17.97s, 18.26s
```
=> Optimize Wallet Load (3.6x faster)

WalletWasabi/Blockchain/Keys/KeyManager.cs
Fixes CodeFactor's issue in #3103
=> Order elements (KeyManager.cs)

WalletWasabi.Backend/Controllers/SoftwareController.cs, WalletWasabi.Gui/Shell/Commands/HelpCommands.cs, WalletWasabi.Gui/Tabs/WalletManager/GenerateWalletViewModel.cs, WalletWasabi/Models/UpdateStatus.cs, WalletWasabi/Services/UpdateChecker.cs
Breaking down this: https://github.com/zkSNACKs/WalletWasabi/pull/3136
=> legalversion Preparation PR

WalletWasabi/Backend/Models/FilterModel.cs, WalletWasabi/Bases/ByteArraySerializableBase.cs, WalletWasabi/Bases/ConfigBase.cs, WalletWasabi/Bases/OctetSerializableBase.cs
Trying to fix CodeFactor's style issue (Elements must appear in the correct order) by ordering the elements.
Should I continue doing this?
Is this easy to review? I thought to do it file by file but then we will have a lot of PRs.
=> Order elements in some classes

WalletWasabi.Documentation/WasabiSetupRegtest.md
Create technical tutorial for RegTest setup
=> Create technical tutorial for RegTest setup

WalletWasabi.Documentation/Ports.md
https://github.com/zkSNACKs/WasabiDoc/issues/537#issuecomment-591535516
=> Move back Ports.md document

WalletWasabi/Services/WalletService.cs
Not sure why we haven't done this before.
=> Measure wallet load performance

WalletWasabi.Gui/Controls/WalletExplorer/CoinJoinTabViewModel.cs, WalletWasabi.Gui/Controls/WalletExplorer/HistoryTabViewModel.cs, WalletWasabi.Gui/Controls/WalletExplorer/ReceiveTabViewModel.cs, WalletWasabi.Gui/Controls/WalletExplorer/TransactionBroadcasterViewModel.cs, WalletWasabi.Gui/Controls/WalletExplorer/WalletInfoViewModel.cs, WalletWasabi.Gui/Tabs/SettingsViewModel.cs
Depends on #3168 
purely ordering code in files!
=> Fix lots of code factor issues

azure-pipelines-linux.yml, azure-pipelines-osx.yml, azure-pipelines-windows.yml
Pick reasonable changes from here: https://github.com/zkSNACKs/WalletWasabi/pull/3122
- Batching: https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?view=azure-devops&tabs=yaml#batching-ci-runs
- MacOS image update: https://aka.ms/removing-older-images-hosted-pools
=> Refactoring CI yamls 2

WalletWasabi.Gui/Global.cs, WalletWasabi.Tests/IntegrationTests/RegTests.cs, WalletWasabi/Blockchain/TransactionBroadcasting/TransactionBroadcaster.cs, WalletWasabi/CoinJoin/Client/CoinJoinProcessor.cs, WalletWasabi/Wallets/WalletManager.cs
Same as https://github.com/zkSNACKs/WalletWasabi/pull/3176.
Closes https://github.com/zkSNACKs/WalletWasabi/pull/3176
=> Implement WalletManager

WalletWasabi.Backend/wwwroot/index.html, WalletWasabi/Helpers/Constants.cs
=> Dump version to v1.1.10.3

WalletWasabi.Gui/Tabs/WalletManager/LoadWalletViewModel.cs
Brought over a part of PR https://github.com/zkSNACKs/WalletWasabi/pull/3170
=> Bring out walletservice to a variable.

WalletWasabi/BitcoinCore/Processes/BitcoindException.cs, WalletWasabi/BitcoinCore/Processes/BitcoindRpcProcessBridge.cs
https://github.com/zkSNACKs/WalletWasabi/pull/3207#discussion_r388885813
=> Beautify throw exception

WalletWasabi.Gui/CommandLine/Daemon.cs, WalletWasabi.Gui/Global.cs, WalletWasabi.Gui/Rpc/WasabiJsonRpcService.cs, WalletWasabi.Gui/Shell/Commands/DiskCommands.cs, WalletWasabi.Gui/Shell/Commands/ToolCommands.cs, WalletWasabi.Gui/Tabs/WalletManager/GenerateWallets/GenerateWalletViewModel.cs, WalletWasabi.Gui/Tabs/WalletManager/LoadWallets/LoadWalletViewModel.cs, WalletWasabi.Gui/Tabs/WalletManager/RecoverWallets/RecoverWalletViewModel.cs, WalletWasabi.Gui/ViewModels/MainWindowViewModel.cs, WalletWasabi.Tests/UnitTests/WalletDirTests.cs, WalletWasabi.Tests/WalletWasabi.Tests.csproj, WalletWasabi/Wallets/WalletDirectories.cs, WalletWasabi/Wallets/WalletManager.cs
As part of the MultiWallet preparation, the directory handlings of the wallet moved into this new class.
=> Creating walletDirectories class

WalletWasabi.Gui/CommandLine/Daemon.cs, WalletWasabi.Gui/Global.cs, WalletWasabi.Gui/Rpc/WasabiJsonRpcService.cs, WalletWasabi.Gui/Shell/Commands/DiskCommands.cs, WalletWasabi.Gui/Shell/Commands/ToolCommands.cs, WalletWasabi.Gui/Tabs/WalletManager/GenerateWallets/GenerateWalletViewModel.cs, WalletWasabi.Gui/Tabs/WalletManager/LoadWallets/LoadWalletViewModel.cs, WalletWasabi.Gui/Tabs/WalletManager/RecoverWallets/RecoverWalletViewModel.cs, WalletWasabi.Gui/ViewModels/MainWindowViewModel.cs, WalletWasabi.Tests/UnitTests/WalletDirTests.cs, WalletWasabi.Tests/WalletWasabi.Tests.csproj, WalletWasabi/Wallets/WalletDirectories.cs, WalletWasabi/Wallets/WalletManager.cs
Analyzing https://github.com/zkSNACKs/WalletWasabi/pull/3253
=> [Codescene] Wallets dir

WalletWasabi/Blockchain/Keys/KeyManager.cs
=> Order KeyManager

WalletWasabi.Gui/CommandLine/CommandInterpreter.cs, WalletWasabi.Gui/Global.cs
Breaking down PR https://github.com/zkSNACKs/WalletWasabi/pull/3258
=> Bring logger initialization forward

WalletWasabi.Tests/RegressionTests/CoinJoinTests.cs, WalletWasabi.Tests/RegressionTests/SendTests.cs, WalletWasabi.Tests/UnitTests/SmartCoinTests.cs, WalletWasabi.Tests/UnitTests/Transactions/TransactionFactoryTests.cs, WalletWasabi/Blockchain/TransactionOutputs/CoinsRegistry.cs, WalletWasabi/Blockchain/TransactionOutputs/CoinsView.cs, WalletWasabi/Blockchain/TransactionOutputs/ICoinsView.cs, WalletWasabi/Blockchain/TransactionOutputs/SmartCoin.cs, WalletWasabi/Blockchain/TransactionProcessing/TransactionProcessor.cs, WalletWasabi/Blockchain/Transactions/TransactionFactory.cs, WalletWasabi/Extensions/NBitcoinExtensions.cs
This is a subset of the changes in the PR https://github.com/zkSNACKs/WalletWasabi/pull/2909
In this PR we replace `TxoRef` by `OutPoint` in a few places and only on the client-side code.
=> Remove TxoRef (part 1)

WalletWasabi.Gui/Controls/WalletExplorer/SendControlViewModel.cs, WalletWasabi/CoinJoin/Client/Clients/CoinJoinClient.cs, WalletWasabi/CoinJoin/Client/Rounds/ClientState.cs, WalletWasabi/Services/WalletService.cs
Remove TxoRef from CoinJoinClient and ClientState (client-side code only)
Related PR #2909
=> Remove TxoRef (part 2)

WalletWasabi.Gui/CommandLine/Daemon.cs, WalletWasabi.Gui/Controls/WalletExplorer/BuildTabViewModel.cs, WalletWasabi.Gui/Controls/WalletExplorer/CoinJoinTabViewModel.cs, WalletWasabi.Gui/Controls/WalletExplorer/CoinListViewModel.cs, WalletWasabi.Gui/Controls/WalletExplorer/CoinViewModel.cs, WalletWasabi.Gui/Controls/WalletExplorer/HistoryTabViewModel.cs, WalletWasabi.Gui/Controls/WalletExplorer/ReceiveTabViewModel.cs, WalletWasabi.Gui/Controls/WalletExplorer/SendControlViewModel.cs, WalletWasabi.Gui/Controls/WalletExplorer/SendTabViewModel.cs, WalletWasabi.Gui/Controls/WalletExplorer/WalletAdvancedViewModel.cs, WalletWasabi.Gui/Controls/WalletExplorer/WalletExplorerViewModel.cs, WalletWasabi.Gui/Controls/WalletExplorer/WalletInfoViewModel.cs, WalletWasabi.Gui/Controls/WalletExplorer/WalletViewModel.cs, WalletWasabi.Gui/Global.cs, WalletWasabi.Gui/Rpc/WasabiJsonRpcService.cs, WalletWasabi.Gui/Suggestions/SuggestLabelViewModel.cs, WalletWasabi.Gui/Tabs/WalletManager/LoadWallets/LoadWalletViewModel.cs, WalletWasabi.Gui/ViewModels/StatusBarViewModel.cs, WalletWasabi.Tests/IntegrationTests/P2pTests.cs, WalletWasabi.Tests/RegressionTests/BuildTests.cs, WalletWasabi.Tests/RegressionTests/CoinJoinTests.cs, WalletWasabi.Tests/RegressionTests/Common.cs, WalletWasabi.Tests/RegressionTests/SendTests.cs, WalletWasabi.Tests/RegressionTests/WalletTests.cs, WalletWasabi.Tests/UnitTests/Transactions/TransactionFactoryTests.cs, WalletWasabi/Blockchain/Transactions/TransactionHistoryBuilder.cs, WalletWasabi/CoinJoin/Client/CoinJoinProcessor.cs, WalletWasabi/Wallets/Wallet.cs, WalletWasabi/Wallets/WalletManager.cs
=> Rename WalletService to Wallet

WalletWasabi/Helpers/PasswordConsole.cs
Closes https://github.com/zkSNACKs/WalletWasabi/issues/3257
Don't be afraid of the diff, look at it without whitespace, I just added a trycatch.
=> Make sure daemon password console works on Windows 7

WalletWasabi.Tests/IntegrationTests/P2pTests.cs, WalletWasabi.Tests/RegressionTests/BuildTests.cs, WalletWasabi.Tests/RegressionTests/CoinJoinTests.cs, WalletWasabi.Tests/RegressionTests/SendTests.cs, WalletWasabi.Tests/RegressionTests/WalletTests.cs, WalletWasabi/Wallets/Wallet.cs, WalletWasabi/Wallets/WalletManager.cs, WalletWasabi/Wallets/WalletState.cs
Breaking down https://github.com/zkSNACKs/WalletWasabi/pull/3275
=> Add WalletState

WalletWasabi/Wallets/Wallet.cs, WalletWasabi/Wallets/WalletManager.cs
Breakdown of https://github.com/zkSNACKs/WalletWasabi/pull/3275
=> Pipe events

WalletWasabi.Documentation/BackendDeployment.md
Simply documents how to query the tor's logs
=> Review the logs

WalletWasabi.Backend/Global.cs, WalletWasabi.Backend/InitConfigStartupTask.cs, WalletWasabi.Gui/Config.cs, WalletWasabi.Gui/Controls/MultiTextBox.cs, WalletWasabi.Gui/Controls/WalletExplorer/CoinJoinTabViewModel.cs, WalletWasabi.Gui/Controls/WalletExplorer/ReceiveTabViewModel.cs, WalletWasabi.Gui/Controls/WalletExplorer/SendControlViewModel.cs, WalletWasabi.Gui/Controls/WalletExplorer/WalletViewModel.cs, WalletWasabi.Gui/Global.cs, WalletWasabi.Gui/MainWindow.xaml.cs, WalletWasabi.Gui/Program.cs, WalletWasabi.Gui/Tabs/SettingsViewModel.cs, WalletWasabi.Gui/UiConfig.cs, WalletWasabi.Tests/RegressionTests/CoinJoinTests.cs, WalletWasabi.Tests/RegressionTests/DosTests.cs, WalletWasabi.Tests/XunitConfiguration/RegTestFixture.cs, WalletWasabi/Bases/ConfigBase.cs, WalletWasabi/CoinJoin/Coordinator/Coordinator.cs, WalletWasabi/CoinJoin/Coordinator/Rounds/CoordinatorRound.cs, WalletWasabi/CoinJoin/Coordinator/Rounds/CoordinatorRoundConfig.cs, WalletWasabi/Interfaces/IConfig.cs, WalletWasabi/Services/ConfigWatcher.cs
Just want to see how the code would look like with this.
=> [Draft] Make config stuff sync

WalletWasabi.Gui/WalletWasabi.Gui.csproj
https://github.com/AvaloniaUI/Avalonia/releases/tag/0.9.4
Fixes specifically for wasabi:
-  Slowing performance after running many many hours (several days)
- OSX deadlocks no need for reactive ui workarounds anymore...
- Closing window fullscreen on OSX no longer crashes
=> update to new avalonia release

WalletWasabi.Backend/Controllers/ChaumianCoinJoinController.cs, WalletWasabi.Tests/XunitConfiguration/LiveServerTestsFixture.cs
Remove TxoRef from server-side code.
=> Remove TxoRef (part 4)

WalletWasabi.Gui/Controls/WalletExplorer/WalletAdvancedViewModel.cs, WalletWasabi.Gui/Controls/WalletExplorer/WalletExplorerViewModel.cs, WalletWasabi.Gui/Controls/WalletExplorer/WalletInfoViewModel.cs, WalletWasabi.Gui/Controls/WalletExplorer/WalletViewModel.cs, WalletWasabi.Gui/Global.cs, WalletWasabi.Tests/IntegrationTests/P2pTests.cs, WalletWasabi.Tests/RegressionTests/BuildTests.cs, WalletWasabi.Tests/RegressionTests/CoinJoinTests.cs, WalletWasabi.Tests/RegressionTests/SendTests.cs, WalletWasabi.Tests/RegressionTests/WalletTests.cs, WalletWasabi/Blockchain/Keys/KeyManager.cs, WalletWasabi/Blockchain/TransactionBroadcasting/TransactionBroadcaster.cs, WalletWasabi/Wallets/Wallet.cs, WalletWasabi/Wallets/WalletManager.cs
Breakdown of https://github.com/zkSNACKs/WalletWasabi/pull/3282
Probably closes https://github.com/zkSNACKs/WalletWasabi/issues/2554
=> Continue towards multiwallet

WalletWasabi.Gui/Controls/WalletExplorer/SendControlViewModel.cs, WalletWasabi.Gui/Rpc/WasabiJsonRpcService.cs, WalletWasabi.Tests/RegressionTests/BuildTests.cs, WalletWasabi.Tests/RegressionTests/SendTests.cs, WalletWasabi.Tests/UnitTests/Transactions/TransactionFactoryTests.cs, WalletWasabi/Blockchain/Transactions/TransactionFactory.cs, WalletWasabi/CoinJoin/Client/Rounds/ClientState.cs, WalletWasabi/Wallets/Wallet.cs
Remove TxoRef rerefences from client-side code (except in protocol message)
Related PR #2909
=> Remove TxoRef (part 3)

WalletWasabi/Blockchain/Keys/KeyManager.cs, WalletWasabi/Wallets/Wallet.cs
Reverts zkSNACKs/WalletWasabi#3294
=> Revert "Move SetLastAccessTimeForNow"

WalletWasabi/Wallets/WalletManager.cs
This is required for WalletExplorer.
=> Make StartWalletAsync public

WalletWasabi/Blockchain/Keys/KeyManager.cs
It's acting up for @danwalmsley and this fixes it.
Closes https://github.com/zkSNACKs/WalletWasabi/pull/3317
=> Use UTC for LastAccessTime

WalletWasabi.Tests/UnitTests/MockRpcClient.cs, WalletWasabi/BitcoinCore/IRPCClient.cs, WalletWasabi/BitcoinCore/RpcClientBase.cs
Backend fails with stackoverflow due to missing TryEstimateSmartFeeAsync in IRPCClient
=> Implement TryEstimateSmartFeeAsync to fix backend

WalletWasabi.Documentation/BackendDeployment.md, WalletWasabi.Gui/CommandLine/CommandInterpreter.cs, WalletWasabi.Gui/Tabs/AboutView.xaml, WalletWasabi.Gui/Tabs/SettingsView.xaml, WalletWasabi/BitcoinCore/Configuration/CoreConfigTranslator.cs, WalletWasabi/BitcoinCore/CoreNode.cs, WalletWasabi/BitcoinCore/Monitoring/RpcStatus.cs
Reopening this PR as part of an attempt break down the coordinator refactor to smaller parts
=> Use Bitcoin Knots binaries as default fullnode 

.editorconfig, WalletWasabi.Backend/Global.cs, WalletWasabi.Gui/Controls/WalletExplorer/SendControlViewModel.cs, WalletWasabi.Gui/Global.cs, WalletWasabi.Gui/Rpc/WasabiJsonRpcService.cs, WalletWasabi.Packager/MacSignTools.cs, WalletWasabi.Tests/Helpers/TestNodeBuilder.cs, WalletWasabi.Tests/UnitTests/AsyncMutexTests.cs, WalletWasabi/Blockchain/BlockFilters/StartingFilters.cs, WalletWasabi/CoinJoin/Coordinator/Banning/BannedUtxo.cs, WalletWasabi/CoinJoin/Coordinator/Rounds/CoordinatorRound.cs, WalletWasabi/Helpers/EndPointParser.cs, WalletWasabi/Nito/AsyncEx/AsyncMutex.cs, WalletWasabi/Wallets/Wallet.cs
The last version of VS add some [refactorings](https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes#net-productivity), and one of them is to simplify string interpolation:
https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes#simplify-string-interpolation
=> Interpolation

WalletWasabi.Gui/MainWindow.xaml, WalletWasabi.Gui/MainWindow.xaml.cs
Fixes are coming in Avalonia right now for Linux and OSX.
=> Fix on Windows, remembering maximized / normal window size.

WalletWasabi.Gui/Tabs/WalletManager/HardwareWallets/ConnectHardwareWalletViewModel.cs
This is my final approach to this, cannot be broken down more. 
I made the review easier by creating clever commits so please review this by reviewing them one by one.
I removed the inheritance from `LoadWalletViewModel` and copy/pasted everything to `ConnectHardwareWalletViewModel`.
I intentionally not removed the unnecessary logic in `ConnectHardwareWalletViewModel` to stay in size/L and for the sake of reviewability. That will be in the upcoming PR.
=> [3.2] Remove Hardware Wallet Stuff from LoadWalletView

WalletWasabi.Gui/Controls/WalletExplorer/ClosedWalletViewModel.cs
Related https://github.com/zkSNACKs/WalletWasabi/issues/3367
=> Clear IsBusy on Wallet load error

WalletWasabi.Gui/Models/LoadWalletEntry.cs, WalletWasabi.Gui/Tabs/WalletManager/HardwareWallets/ConnectHardwareWalletViewModel.cs, WalletWasabi.Gui/Tabs/WalletManager/HardwareWallets/HardwareWalletViewModel.cs, WalletWasabi.Gui/Tabs/WalletManager/LoadWallets/LoadWalletType.cs, WalletWasabi.Gui/Tabs/WalletManager/LoadWallets/LoadWalletViewModel.cs
Built on top of https://github.com/zkSNACKs/WalletWasabi/pull/3338
This PR removed the Hardware wallet related stuff from LoadWalletViewModel. Probably the final PR.
1. Separated HardwareWalletViewModel.
2. Removed HardwareWallet related stuff from LoadWalletViewModel. 
LoadWalletViewModel.cs improves its Code Health from 6.85 -> 9.66
=> [4] Remove Hardware Wallet Stuff from LoadWalletView

WalletWasabi.Gui/ViewModels/StatusBarViewModel.cs
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/3349
=> Fix DivideByZero exception

WalletWasabi.Gui/Controls/WalletExplorer/WalletExplorerViewModel.cs, WalletWasabi.Gui/Tabs/WalletManager/GenerateWallets/GenerateWalletSuccessViewModel.cs, WalletWasabi/Wallets/WalletManager.cs
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/3367
=> Multiwalleting generate wallet 

WalletWasabi.Gui/Controls/WalletExplorer/WalletExplorerViewModel.cs, WalletWasabi/Wallets/WalletManager.cs
Easy addon, required for ViewModels to create the list of wallets.
=> Add GetWallets method to WalletManager

WalletWasabi.Gui/WalletWasabi.Gui.csproj
- Fixes issue with treeview (allowing correct seleciton in WalletExplorer)
- Fixes restoring window state on load, for OSX and Linux.
=> update avalonia with bug fixes for release.

WalletWasabi.Gui/MainWindow.xaml.cs, WalletWasabi.Gui/ViewModels/MainWindowViewModel.cs, WalletWasabi.Gui/WalletWasabi.Gui.csproj
required #3375 to be merged first.
This means OSX and Linux will now remember the window state.
=> Persist window state size all platforms

WalletWasabi.Gui/Controls/WalletExplorer/WalletExplorerView.xaml
=> Make Wallet explorer context menu consistent from main menu

WalletWasabi.Gui/Tabs/WalletManager/WalletManagerViewModel.cs
Breakdown of this to isolate the Codescene issue.
https://github.com/zkSNACKs/WalletWasabi/pull/3381
=> Dispose WalletManagerView properly

WalletWasabi.Gui/Controls/WalletExplorer/HistoryTabViewModel.cs
=> Fix HistoryTab not updating

WalletWasabi.Gui/Controls/WalletExplorer/WalletExplorerViewModel.cs
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/3408
=> Prevent opening stopped wallets

WalletWasabi.Gui/Controls/WalletExplorer/CoinJoinTabView.xaml
as reported by @bharmat coinjoin page doest resize correctly. This fixes that.
=> fix resizing of coinjoin page.

WalletWasabi.Gui/Behaviors/BindWindowSizeBehavior.cs, WalletWasabi.Gui/MainWindow.xaml, WalletWasabi.Gui/MainWindow.xaml.cs, WalletWasabi.Gui/ViewModels/MainWindowViewModel.cs
=> Fix Window oversize: Use a behaviour to bind window size.

WalletWasabi.Gui/Tabs/WalletManager/HardwareWallets/ConnectHardwareWalletViewModel.cs
Fixing https://github.com/zkSNACKs/WalletWasabi/issues/3468
=> Fix hardware loading the wrong hardware wallet

WalletWasabi.Backend/wwwroot/index.html, WalletWasabi/Helpers/Constants.cs
Preparation to release tomorrow.
=> Dump version to v1.1.11

WalletWasabi.Gui/Controls/WalletExplorer/SendControlViewModel.cs
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/3447
=> Make Max Amount consistent

WalletWasabi.Gui/Controls/TogglePasswordBox.cs, WalletWasabi.Gui/Controls/TogglePasswordBox.xaml
Togglepasswordbox now uses global eye icons and hide/show messages are generic "show/hide characters" to accommodate uses for passwords and pins/other secrets.
=> Changed togglepassworbox component

WalletWasabi/Wallets/WalletManager.cs
Fixes: https://github.com/zkSNACKs/WalletWasabi/issues/3378
=> Remove saving of the non-opened wallets on quit.

WalletWasabi.Tests/UnitTests/BitcoinCore/RpcBasedTests.cs
=> Fix CI warnings

WalletWasabi.Gui/Rpc/WasabiJsonRpcService.cs
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/3346
```sh
$ curl -s --data-binary '{"jsonrpc":"2.0","method":"selectwallet", "params" : ["TestNet Password"]}' http://127.0.0.1:37128/
$ curl -s --data-binary '{"jsonrpc":"2.0","id":"1","method":"listunspentcoins"}' http://127.0.0.1:37128/ | jq
{
"jsonrpc": "2.0",
"result": [
{
"txid": "78f65ddef524a17dd7e82888fc98078bb1c1423c7d30773b6c8c0f3e63fa1ab7",
"index": 0,
"amount": 1002698,
"anonymitySet": 1,
"confirmed": false,
"label": "Test1",
"keyPath": "84'/0'/0'/0/0",
"address": "tb1q5senlaggu6rq26679mdmv0t69ffy47vkcjyvw4"
}
],
"id": "1"
}
$
$ curl -s --data-binary '{"jsonrpc":"2.0","id":"1","method":"enqueue", "params": { "coins": [{"transactionId": "78f65ddef524a17dd7e82888fc98078bb1c1423c7d30773b6c8c0f3e63fa1ab7", "index":"0"}], …
```
=> Add password to Enqueue method

WalletWasabi/Helpers/Constants.cs
Fixes: https://github.com/zkSNACKs/WalletWasabi/issues/3545
Related: https://github.com/bitcoin-core/HWI/pull/319
=> Fixing Trezor issues with 2.3 firmware

WalletWasabi.Gui/Tabs/WalletManager/LoadWallets/LoadWalletViewModel.cs
=> Fix WalletManager error notification

WalletWasabi.Gui/Rpc/WasabiJsonRpcService.cs, WalletWasabi/Blockchain/TransactionOutputs/SmartCoin.cs
Implements the changes discussed in #3608.
=> [RPC] Add "confirmations" field to "listunspentcoins" json response

WalletWasabi.Packager/Program.cs
Looking at CodeFactor issues there is some duplicate code https://www.codefactor.io/repository/github/zksnacks/walletwasabi/issues/master?category=Duplication
Most of the duplicate code is in the `WalletWasabi.Test` project which is fine I think.
This PR removes the duplicate code in `WalletWasabi.Packager/Program.cs` file.
https://www.codefactor.io/repository/github/zksnacks/walletwasabi/source/master/WalletWasabi.Packager/Program.cs#L120
https://www.codefactor.io/repository/github/zksnacks/walletwasabi/source/master/WalletWasabi.Packager/Program.cs#L166
=> Remove duplicate code

Settings.StyleCop
https://documentation.help/StyleCop/SA1515.html
=> Enable SingleLineCommentMustBePrecededByBlankLine

WalletWasabi/Crypto/SchnorrBlindingSignature.cs
Applied our coding conventions.
Run the `SchnorrBlindindSignatureTests` and they both pass.
=> Refactor SchnorrBlinding class

WalletWasabi.Gui/ViewModels/StatusBarViewModel.cs
this notification only says the outcome, the legal docs could not be downloaded, but not the reason, the backend is not connected.
=> make error notification clear

WalletWasabi/CoinJoin/Coordinator/Rounds/CoordinatorRound.cs
These things were logged from the beginning, but as the volume grew, they made the server logs suped duper noisy and I can't recall them ever being useful for anything.
=> Log Debug instead of Info

Settings.StyleCop
https://documentation.help/StyleCop/SA1204.html
=> Enable StaticElementsMustAppearBeforeInstanceElements

Settings.StyleCop
https://documentation.help/StyleCop/SA1502.html
=> Enable ElementMustNotBeOnSingleLine

WalletWasabi.Backend/Controllers/BlockchainController.cs, WalletWasabi.Tests/RegressionTests/BackendTests.cs, WalletWasabi/Blockchain/BlockFilters/IndexBuilderService.cs
Fixes: https://github.com/zkSNACKs/WalletWasabi/pull/3654#issuecomment-636794298
The simplest solution to fix the status test.
Dropped alternatives:
https://github.com/zkSNACKs/WalletWasabi/pull/3721
https://github.com/zkSNACKs/WalletWasabi/pull/3717
=> Fix StatusRequestTestAsync [Naive]

WalletWasabi.Backend/wwwroot/index.html
Just a couple of edits to tweak on-page SEO:
and:
=> Small SEO tweaks

WalletWasabi.Backend/wwwroot/index.html
=> Add Onion-Location HTTP header

Settings.StyleCop
https://documentation.help/StyleCop/SA1116.html
=> Enable SplitParametersMustStartOnLineAfterDeclaration

Settings.StyleCop
https://documentation.help/StyleCop/SA1203.html
=> [StyleCop] Enable ConstantsMustAppearBeforeFields

WalletWasabi.Gui/Global.cs
=> Add missing .ConfigureAwait(false) to Global.cs

WalletWasabi.Gui/CommandLine/CommandInterpreter.cs, WalletWasabi.Gui/CommandLine/MixerCommand.cs, WalletWasabi.Gui/CommandLine/PasswordFinderCommand.cs, WalletWasabi.Gui/Program.cs, WalletWasabi.Tests/UnitTests/GUI/CommandInterpreterTest.cs
Hi,
this is a small PR that improves `CommandInterpreter` and adds a unit test. It also fixes a very minor bug: an NPE here: https://github.com/zkSNACKs/WalletWasabi/compare/master...kiminuo:feature/2020-06-refactor-CommandInterpreter?expand=1#diff-cead841831d74ca08289cde13b85701fL48
Cheers!
=> Refactor CommandInterpreter class

Settings.StyleCop
https://documentation.help/StyleCop/SA1117.html
=> [Stylecop] Enable ParametersMustBeOnSameLineOrSeparateLines

WalletWasabi.Gui/CommandLine/MixerCommand.cs
Closes https://github.com/zkSNACKs/WalletWasabi/issues/3788
=> Make wallet name argument required

WalletWasabi.Gui/Global.cs, WalletWasabi.Gui/Program.cs
This PR makes `Global` constructor very complex. However, it is a first step - very simple by design - to continue cleaning `Global` class. In the next steps, the number of parameters will slowly decrease.
=> [DI] Refactor `Global` a bit

WalletWasabi.Backend/wwwroot/index.html
SEO tweak (optimizing keywords in the description)
=> Update website description

WalletWasabi.Gui/Controls/EditableTextBlock.cs, WalletWasabi.Gui/Controls/WalletExplorer/ReceiveTabViewModel.cs, WalletWasabi.Gui/Controls/WalletExplorer/TransactionBroadcasterViewModel.cs
Please hide whitespace changes when reviewing.
https://github.com/zkSNACKs/WalletWasabi/pull/3801/files?diff=unified&w=1
=> Put parameters on different lines

WalletWasabi/CoinJoin/Coordinator/Rounds/CoordinatorRound.cs
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/3808
I can imagine more elegant solutions, but I think small diff is preferable for a code that's going to be obsolated soon.
=> Adjust down the new base denomination by 1sat in case collision

WalletWasabi.Tests/IntegrationTests/P2pTests.cs, WalletWasabi.Tests/UnitTests/Transactions/PayjoinTests.cs, WalletWasabi.Tests/UnitTests/Transactions/TransactionFactoryTests.cs, WalletWasabi/Blockchain/Transactions/AllTransactionStore.cs, WalletWasabi/Blockchain/Transactions/AllTransactionStoreMock.cs, WalletWasabi/Blockchain/Transactions/TransactionFactory.cs, WalletWasabi/Hwi/HwiClient.cs, WalletWasabi/Hwi/Parsers/HwiParser.cs, WalletWasabi/Stores/BitcoinStore.cs, WalletWasabi/Stores/BitcoinStoreMock.cs, WalletWasabi/Wallets/Wallet.cs
This PR resolves the Trezor hardware wallet issue. Fixes #3734 
Depends on https://github.com/zkSNACKs/WalletWasabi/pull/3821
=> Add NonWitness UTXO in PSBT for Trezor compat

WalletWasabi.Backend/Config.cs, WalletWasabi.Backend/Global.cs, WalletWasabi.Gui/Controls/WalletExplorer/ClosedWalletViewModel.cs, WalletWasabi.Gui/Controls/WalletExplorer/ReceiveTabViewModel.cs, WalletWasabi.Gui/Helpers/AvaloniaThreadingExtensions.cs, WalletWasabi.Gui/Tabs/WalletManager/GenerateWallets/GenerateWalletSuccessViewModel.cs, WalletWasabi.Tests/RpcTests.cs, WalletWasabi.Tests/UnitTests/HashChainTests.cs, WalletWasabi.Tests/UnitTests/Transactions/AllTransactionStoreTests.cs, WalletWasabi.Tests/UnitTests/Transactions/TransactionFactoryTests.cs, WalletWasabi/Blockchain/Transactions/SmartTransaction.cs, WalletWasabi/Helpers/RuntimeParams.cs, WalletWasabi/Mono/OptionValueCollection.cs, WalletWasabi/Nito/AsyncEx/AsyncWaitQueueExtensions.cs
Please hide whitespace changes to easily review
https://github.com/zkSNACKs/WalletWasabi/pull/3828/files?diff=unified&w=1
Ignore the `7 issues found` by CodeFactor, they should be fixed by #3827
=> Put first parameter on new line

WalletWasabi.Gui/Tabs/WalletManager/HardwareWallets/ConnectHardwareWalletView.xaml
Reason: https://github.com/zkSNACKs/WalletWasabi/blob/master/WalletWasabi.Documentation/WasabiCompatibility.md
=> Update supported hw list.

WalletWasabi.Gui/Controls/WalletExplorer/ClosedWalletViewModel.cs
=> Test wallet password if it was not tested

WalletWasabi.Tests/UnitTests/GuardTests.cs, WalletWasabi/Helpers/Guard.cs
This is a breakdown of PR https://github.com/zkSNACKs/WalletWasabi/pull/3851
=> Implement True/False guards

WalletWasabi.Gui/Converters/PrivacyLevelValueConverter.cs, WalletWasabi.Gui/Rpc/JsonRpcService.cs, WalletWasabi.Tests/RegressionTests/Common.cs, WalletWasabi/BitcoinCore/RpcParser.cs, WalletWasabi/Mono/OptionSet.cs
Use index operator
Use pattern matching
Add `pragma warning disable`
Remove redundant assignment
=> Small refactoring

WalletWasabi/Hwi/Models/HwiCommands.cs
Taken from: https://github.com/bitcoin-core/HWI/blob/master/hwilib/hwwclient.py
=> Document HwiCommands.cs

WalletWasabi.Gui/CrashReport/ViewModels/CrashReportWindowViewModel.cs
This ready for review branch rewords the crash report system to be a little more beautiful.
#3733
=> reword the crash report message

WalletWasabi.Gui/Tabs/AboutViewModel.cs, WalletWasabi/Services/HostedServices.cs
Fixes: https://github.com/zkSNACKs/WalletWasabi/pull/3843#issuecomment-653764985
=> Fix exception when opening About before initialization

CONTRIBUTING.md
As @jmacato suggested here https://github.com/zkSNACKs/WalletWasabi/pull/3833#issuecomment-655535385
=> Add empty quotes convention

WalletWasabi.Documentation/Guides/DeterministicBuildGuide.md
As @kiminuo suggested here: https://github.com/zkSNACKs/WalletWasabi/pull/3919#discussion_r454385536
=> Change comment style

WalletWasabi.Gui/Controls/QrCode.cs
=> Add title in dialog for QR Code prompt to avoid NRE.

WalletWasabi.Gui/Program.cs
Initialises the shell and sets the colour theme.
=> Fix crash reporter on OSX.

WalletWasabi.Gui/Controls/WalletExplorer/WalletInfoView.xaml, WalletWasabi.Gui/Controls/WalletExplorer/WalletInfoViewModel.cs
=> tidy up the wallet info view layout.

WalletWasabi.Gui/Global.cs, WalletWasabi.Tests/Helpers/TestNodeBuilder.cs, WalletWasabi/BitcoinCore/CoreNode.cs, WalletWasabi/BitcoinCore/CoreNodeParams.cs, WalletWasabi/Helpers/Constants.cs
Draft because need NBitcoin release for this, too.
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/3699
=> Update to Bitcoin Knots 20

WalletWasabi.Gui/Controls/WalletExplorer/TransactionBroadcasterView.xaml, WalletWasabi.Gui/Controls/WalletExplorer/TransactionBroadcasterViewModel.cs
Also changes the button text: `Paste From Clipboard` -> `Paste Signed Transaction`
=> Remove unnecessary return

WalletWasabi.Tests/UnitTests/Transactions/PayjoinTests.cs, WalletWasabi/Blockchain/Transactions/TransactionFactory.cs, WalletWasabi/Extensions/ExceptionExtensions.cs
=> Ignore payjoin server errors

WalletWasabi.Gui/Controls/WalletExplorer/SendTabViewModel.cs
Hack Fixes: https://github.com/zkSNACKs/WalletWasabi/issues/3995
If Wasabi detects the specified issue it will remove the input transactions from the PSBT. With that Ledger will sign the tx correctly. Note that there will be a warning message on Ledger "Unverified Inputs" and the user will have to accept the tx again. 
I contacted Ledger and NBitcoin, probably this will go deep and will take a lot of time. With this PR we can go with the v1.1.12 release.
=> Add fall back mode to Ledger signing

WalletWasabi.Documentation/BackendDeployment.md, WalletWasabi.Gui/Global.cs, WalletWasabi.Tests/Helpers/TestNodeBuilder.cs, WalletWasabi.Tests/UnitTests/BitcoinCore/RpcBasedTests.cs, WalletWasabi.Tests/UnitTests/MockRpcClient.cs, WalletWasabi/BitcoinCore/CoreNode.cs, WalletWasabi/BitcoinCore/CoreNodeParams.cs, WalletWasabi/BitcoinCore/IRPCClient.cs, WalletWasabi/BitcoinCore/RpcClientBase.cs
https://github.com/MetacoSA/NBitcoin/pull/884#issuecomment-663620290
=> Add mempoolreplacement and double spend test

WalletWasabi.Gui/Controls/WalletExplorer/CoinInfoTabView.xaml, WalletWasabi.Gui/Controls/WalletExplorer/CoinListView.xaml, WalletWasabi.Gui/Controls/WalletExplorer/ReceiveTabView.xaml, WalletWasabi.Gui/Controls/WalletExplorer/ReceiveTabViewModel.cs, WalletWasabi.Gui/Controls/WalletExplorer/SendControlViewModel.cs, WalletWasabi.Gui/Suggestions/SuggestLabelView.xaml, WalletWasabi/Blockchain/Keys/KeyManager.cs
=> Rename UI elements Observers -> Known by

WalletWasabi/BitcoinCore/Processes/BitcoindRpcProcessBridge.cs, WalletWasabi/TorSocks5/TorProcessManager.cs, WalletWasabi/TorSocks5/TorSocks5Client.cs
I believe this is correct way add quotes so that #4048 is fixed or at least improved.
=> TorProcessManager & quotes.

WalletWasabi.Gui/packages.lock.json, WalletWasabi/packages.lock.json
After running the packager nuget added more packages so their hashes recorded to the lock file.
=> Add Linux and macOs package hashes to packages.lock.json

WalletWasabi.Gui/WalletWasabi.Gui.csproj, WalletWasabi.Packager/Program.cs
Quick fix for https://github.com/zkSNACKs/WalletWasabi/pull/4083
=> Packager fix for App icon path

WalletWasabi.Tests/UnitTests/MemoryTests.cs
Related: https://github.com/zkSNACKs/WalletWasabi/pull/4088
=> Add more tests to AtomicGetOrCreateAsync

WalletWasabi.Gui/Controls/WalletExplorer/CoinListView.xaml
Reverts zkSNACKs/WalletWasabi#3988
=> Revert "Limit coin detail double-click behavior to a focus target control ins…"

WalletWasabi.Backend/Controllers/ChaumianCoinJoinController.cs, WalletWasabi/CoinJoin/Coordinator/Rounds/CoordinatorRound.cs
Related: https://github.com/zkSNACKs/WalletWasabi/issues/4124
=> Better logging for coordinator round

WalletWasabi.Tests/UnitTests/AllFeeEstimateTests.cs, WalletWasabi/BitcoinCore/CachedRpcClient.cs, WalletWasabi/Blockchain/Analysis/FeesEstimation/AllFeeEstimate.cs, WalletWasabi/Extensions/RPCClientExtensions.cs
Not perfect optimization, but server is freezing because it cannot handle the number of estimatesmartfee requests.
=> Optimize estimate all fee

WalletWasabi.Backend/Controllers/BlockchainController.cs
Calling AtomicGetOrCreateAsync from AtomicGetOrCreateAsync is not a good idea. This needs to be fixed. For now I must deploy this.
=> Server Load Hotfix

WalletWasabi.Tests/UnitTests/TorSocks5/TorSettingsTests.cs, WalletWasabi/TorSocks5/TorProcessManager.cs, WalletWasabi/TorSocks5/TorSettings.cs
`TorProcessManager` is quite big. This PR makes it a bit shorter and adds a test.
=> Refactoring: TorSettings

WalletWasabi/Extensions/ExceptionExtensions.cs
Fixes #3908
Add user friendly notification message when sign transaction is canceled (hardware wallets)
=> User friendly notification message

WalletWasabi/Wallets/Wallet.cs
I propose to remove this method as there are no references.
=> Wallet.cs: Remove unused method.

WalletWasabi.Documentation/BackendDeployment.md
This introduces provides more information in the bash prompt letting the maintainers know the branch that is checkout-ed.
=> Show checkouted branch

CONTRIBUTING.md
This a breakdown of #4104
Adds the notice in CONTRIBUTING.MD so that other devs can be guided accordingly when making new UI elements later.
cc: @lontivero
=> [1/3] Add contributing guide for using Grid sparingly.

WalletWasabi.Documentation/Guides/HowToDebug.md
Fixes #https://github.com/zkSNACKs/WalletWasabi/issues/4118
=> Add sourceFileMap to debug

WalletWasabi.Gui/App.xaml, WalletWasabi.Gui/Controls/BusyIndicator.xaml, WalletWasabi.Gui/Controls/EditableTextBlock.xaml, WalletWasabi.Gui/Controls/LockScreen/PinLockScreenView.xaml, WalletWasabi.Gui/Controls/LockScreen/SlideLock.cs, WalletWasabi.Gui/Controls/LockScreen/SlideLock.xaml, WalletWasabi.Gui/Controls/LockScreen/SlideLockScreenView.xaml, WalletWasabi.Gui/Controls/ModalDialog.xaml, WalletWasabi.Gui/Controls/MultiTextBox.xaml, WalletWasabi.Gui/Controls/Spinner.xaml, WalletWasabi.Gui/Controls/StatusBar.xaml, WalletWasabi.Gui/Controls/TogglePasswordBox.xaml, WalletWasabi.Gui/Controls/WalletExplorer/ReceiveTabView.xaml, WalletWasabi.Gui/Controls/WalletExplorer/SendControlView.xaml, WalletWasabi.Gui/CrashReport/Views/CrashReportWindow.xaml, WalletWasabi.Gui/Dialogs/GenSocksServFailDialogView.xaml, WalletWasabi.Gui/Tabs/LegalDocumentsView.xaml, WalletWasabi.Gui/Tabs/WalletManager/GenerateWallets/GenerateWalletView.xaml, WalletWasabi.Gui/Tabs/WalletManager/HardwareWallets/ConnectHardwareWalletView.xaml, WalletWasabi.Gui/Tabs/WalletManager/WalletManagerView.xaml
Part 2 of #4104 
cc @lontivero
=> [2/3] Replacing Trivial Grids with Panel

WalletWasabi.Gui/Controls/TransactionDetails/ViewModels/TransactionDetailsViewModel.cs, WalletWasabi.Gui/Controls/WalletExplorer/HistoryTabViewModel.cs, WalletWasabi.Gui/Controls/WalletExplorer/TransactionViewModel.cs
=> Open Transaction Details tab based on wallet name

WalletWasabi.Gui/ViewModels/StatusBarViewModel.cs
Fixes #3758
Clarify notification message when there is a connection problem.
=> Clarify notification message

WalletWasabi.Gui/Controls/WalletExplorer/SendTabViewModel.cs, WalletWasabi.Gui/Tabs/AboutView.xaml
`Hidden Service` is no longer officially used.
`.onion website` seems to be the right term.
=> Change Tor to .onion website

WalletWasabi.Tests/UnitTests/Transactions/TransactionFactoryTests.cs, WalletWasabi.Tests/UnitTests/Wallet/LockTimeSelectorTests.cs, WalletWasabi/Wallets/LockTimeSelector.cs, WalletWasabi/Wallets/Wallet.cs
Refactoring for Wallet class to decrease its complexity a bit.
=> Add LockTimeSelector + unit test.

WalletWasabi.Packager/ArgsProcessor.cs, WalletWasabi/Crypto/UnblindedSignature.cs, WalletWasabi/WebClients/Bitstamp/BitstampExchangeRate.cs, WalletWasabi/WebClients/Bitstamp/BitstampExchangeRateProvider.cs, WalletWasabi/WebClients/CoinGecko/CoinGeckoExchangeRate.cs, WalletWasabi/WebClients/CoinGecko/CoinGeckoExchangeRateProvider.cs, WalletWasabi/WebClients/ExchangeRateProviders.cs
Since https://github.com/zkSNACKs/WalletWasabi/pull/3873 is merged, this isn't necessary anymore.
=> Remove #nullable enable

WalletWasabi.Gui/Controls/WalletExplorer/HistoryTabViewModel.cs, WalletWasabi.Gui/UiConfig.cs
=> Change History Tab's default sorting to decreasing

Settings.StyleCop
https://documentation.help/StyleCop/SA1115.html
=> [StyleCop] Enable ParameterMustFollowComma

Settings.StyleCop
=> Make PropertySummaryDocumentationMustMatchAccessors false

WalletWasabi.Documentation/WasabikaCodex.md
I added a table where you can find a quick link for each developer's Valhalla assignees.
And I also added Git tips paragraph with two scripts.
=> Valhalla assignee table and Git tips added to WasabikaCodex.md

WalletWasabi.Gui/ViewModels/StatusBarViewModel.cs
https://github.com/zkSNACKs/WalletWasabi/pull/4044#issuecomment-663832180
https://github.com/zkSNACKs/WalletWasabi/pull/4044#discussion_r469795166
=> Remove setter

Settings.StyleCop
https://documentation.help/StyleCop/SA1123.html
=> [StyleCop] Enable DoNotPlaceRegionsWithinElements

Settings.StyleCop
As discussed with @molnard & @lontivero in #3837
=> Make StaticElementsMustAppearBeforeInstanceElements false

README.md
=> Update blockchain privacy features

WalletWasabi.Documentation/Guides/HardwareWalletIntegration.md
Still work in progress, any comments appreciated.
=> Add Hardware Wallet integration guidance

WalletWasabi.Tests/UnitTests/BitcoinCore/NodeBuildingTests.cs, WalletWasabi.Tests/UnitTests/BitcoinCore/SerialNodeBuildingTests.cs, WalletWasabi.Tests/UnitTests/Hwi/DefaultResponseTests.cs, WalletWasabi.Tests/UnitTests/Hwi/SerialDefaultResponseTests.cs, WalletWasabi.Tests/XunitConfiguration/SerialCollectionDefinition.cs
This is part of #4152 project.
Resources:
* https://github.com/xunit/xunit/pull/1411
*  https://github.com/xunit/xunit/blob/main/src/xunit.v2.tests/Acceptance/Xunit2AcceptanceTests.cs
* https://xunit.net/docs/running-tests-in-parallel.html
=> Make some tests to run in serial mode.

WalletWasabi/BitcoinCore/Processes/BitcoindRpcProcessBridge.cs, WalletWasabi/BitcoinCore/Processes/PidFile.cs
Add new `PidFile` class to make it generally useful.
This PR is an attempt to make #3863 smaller to make review easier.
=> Refactoring: PidFile class.

WalletWasabi/TorSocks5/TorProcessManager.cs
This PR is an attempt to make #3863 smaller by shaving off useful bits to smaller PRs to make review easier.
=> Add waitForExit info to make it clear what it does.

WalletWasabi.Gui/CrashReport/ViewModels/CrashReportWindowViewModel.cs, WalletWasabi.Gui/CrashReport/Views/CrashReportWindow.xaml
fix #4182 
DockPanel changed to Grid.
=> Crash report layout fix

WalletWasabi.Tests/UnitTests/Microservices/ProcessAsyncTest.cs, WalletWasabi/Microservices/ProcessAsync.cs, WalletWasabi/Microservices/ProcessInvoker.cs, WalletWasabi/Microservices/ProcessStartInfoFactory.cs
This PR is an attempt to make #3863 smaller by shaving off useful bits to smaller PRs to make review easier.
=> Add new async process API that is supposed to replace ProcessBridge API.

WalletWasabi/Helpers/EnvironmentHelpers.cs
This PR is an attempt to make #3863 smaller by shaving off useful bits to smaller PRs to make review easier.
See: https://github.com/zkSNACKs/WalletWasabi/pull/3863#discussion_r467530959
PLEASE TEST THAT IT WORKS FOR YOU AS IT TOUCHES CODE THAT RUNS TOR.
=> Use more portable variant of `/bin/sh`.

WalletWasabi.Gui/Validation/Validations.cs, WalletWasabi.Gui/ViewModels/ViewModelBase.cs, WalletWasabi/Helpers/PasswordHelper.cs
=> Nullable Reference Types - nits.

WalletWasabi/Helpers/EnvironmentHelpers.cs
=> Shell path on Mac fix

WalletWasabi.Backend/Controllers/BatchController.cs
fixes https://github.com/zkSNACKs/WalletWasabi/issues/4227
closes https://github.com/zkSNACKs/WalletWasabi/pull/4228/
=> Fix GetSynchronizeAsync

WalletWasabi.Backend/Controllers/BatchController.cs
Related: https://github.com/zkSNACKs/WalletWasabi/issues/4227
Will add this to swagger
=> Add default value to estimateSmartFeeMode

WalletWasabi.Gui/Program.cs, WalletWasabi.Gui/ViewModels/StatusBarViewModel.cs
This is part of #4219 to make review easier.
=> Replace BitcoinStore with SmartHeaderChain in StatusBarViewModel.

WalletWasabi.Gui/Controls/WalletExplorer/ReceiveTabView.xaml, WalletWasabi.Gui/Controls/WalletExplorer/SendControlView.xaml, WalletWasabi.Gui/Controls/WalletExplorer/TransactionBroadcasterView.xaml, WalletWasabi.Gui/Tabs/WalletManager/LoadWallets/LoadWalletView.xaml
- Removes <Empty> </Empty> xaml tags.
- Removes hack where empty grid is used inside dockpanel to produce desired layout, correct implemenation used.
=> Some XAML clean up.

WalletWasabi.Packager/Program.cs
I tried to run the `WalletWasabi.Packeger` but it fails because on my machine the wasabi project is on drive D not on C.
This will fix it.
=> Packager will work on every drive

.github/stale.yml
Fixes: https://github.com/zkSNACKs/WalletWasabi/issues/4153
See stalebot repo here https://github.com/probot/stale
=> Adding stalebot conf file to the repository

WalletWasabi.Packager/BitnodesApi.cs, WalletWasabi.Packager/Program.cs, WalletWasabi.Tests/UnitTests/Packager/BitnodesApiTests.cs
* Makes Packager `async`.
* Refactor BitnodesApi to a standalone class with a simple unit test.
=> Refactor out BitnodesApi class to make it testable.

WalletWasabi.Gui/Rpc/WasabiJsonRpcService.cs
Fixes #4247.
Closes https://github.com/zkSNACKs/WalletWasabi/pull/4250
Someone test this please because I didn't.
=> [RPC] Add the address to the returned values when calling listkeys method

WalletWasabi.Gui/Controls/WalletExplorer/CoinInfoTabView.xaml, WalletWasabi.Gui/Tabs/SettingsView.xaml
Fixes #4054 & #4269
Review without the white space changes https://github.com/zkSNACKs/WalletWasabi/pull/4272/files?diff=unified&w=1
=> Fix horizontal scroll bar issues

WalletWasabi.Gui/Controls/StatusBar.xaml
=> Change "Price" to "BTC/USD"

WalletWasabi.Tests/UnitTests/Crypto/ZeroKnowledge/LinearRelationTests.cs, WalletWasabi/Crypto/Extensions.cs, WalletWasabi/Crypto/GroupElementVector.cs, WalletWasabi/Crypto/ScalarVector.cs, WalletWasabi/Crypto/ZeroKnowledge/LinearRelation/Equation.cs, WalletWasabi/Crypto/ZeroKnowledge/LinearRelation/Knowledge.cs, WalletWasabi/Crypto/ZeroKnowledge/LinearRelation/Statement.cs
This pull request completes the interactive Sigma protocol for generalized linear relations with n equations.
Depends on #4277
=> [WabiSabi] Linear relation

WalletWasabi.Gui/Tabs/WalletManager/LoadWallets/LoadWalletViewModel.cs
Most of you guys were against it anyway and I have to say I was wrong. Time has proved that it's very annoying behavior.
=> Don't order wallets by wallet state

WalletWasabi/Wallets/Wallet.cs
Just want to see the diff for now.
=> Apply VS Code Cleanup

WalletWasabi.Tests/UnitTests/Crypto/TranscriptTests.cs, WalletWasabi/Crypto/ZeroKnowledge/SyntheticPublicNoncesProvider.cs, WalletWasabi/Crypto/ZeroKnowledge/SyntheticSecretNonceProvider.cs, WalletWasabi/Crypto/ZeroKnowledge/Transcript.cs
Replace nonce generation interface for a more object-oriented one in order to provide multiple methods to get synthetic nonces.
=> [WabiSabi] Improve Transcript API

WalletWasabi/Helpers/IoHelpers.cs
This PR should be on the trivial side as it should not change any behavior.
=> IoHelpers: add missing ConfigureAwait(false).

WalletWasabi.Tests/IntegrationTests/TorTests.cs, WalletWasabi.Tests/RegressionTests/CoinJoinTests.cs
Otherwise:
```
Message: 
Microsoft.CSharp.RuntimeBinder.RuntimeBinderException : 'System.Array' does not contain a definition for 'Any'
Stack Trace: 
CallSite.Target(Closure , CallSite , Object )
UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
CoinJoinTests.CcjFeeTestsAsync() line 1178
--- End of stack trace from previous location where exception was thrown ---
```
And anyway, let's just use a strongly typed language.
=> Fix CcjFeeTestsAsync

WalletWasabi.Packager/ArgsProcessor.cs, WalletWasabi.Packager/Program.cs, azure-pipelines-cd.yml
Thi PR is about creating a Continuous delivery for every PR.
Here you can see the new pipeline at work. 
https://github.com/molnard/WalletWasabi/pull/21
Next steps:
- Provide additional packages that can easily be verified in the manner of deterministic builds. For example to have something for macOS, where apple signing prevents proper det. builds. 
- Continuous delivery after every master branch commits.
- Deterministic build CI. 
I added a command-line argument --cdelivery, that will be used at azure pipelines for continuous delivery.
=> Publish binaries in zip format

WalletWasabi/TorSocks5/TorProcessManager.cs
This is part of #4244 project where I would actually like to get rid of those await `Task.Delay(3000);` delays in `TorTests` and enforce that when you start Tor and you ask for `ensureRunning` it will be started or an exception will be thrown. This PR paves the path to that goal.
This PR does not change behavior but subjectively makes it easier to understand code meaning. I wrongly thought, at first, that `_running` denoted state of Tor process so maybe this is clearer now.
=> Use constants for state in TorProcessManager.

WalletWasabi/Crypto/SchnorrBlindingSignature.cs
=> Ignore if addition overflowed because it is irrelevant

WalletWasabi.Gui/Controls/WalletExplorer/HistoryTabViewModel.cs, WalletWasabi.Gui/Controls/WalletExplorer/TransactionBroadcasterViewModel.cs, WalletWasabi.Tests/RegressionTests/CoinJoinTests.cs, WalletWasabi/Blockchain/BlockFilters/IndexBuilderService.cs, WalletWasabi/Blockchain/Keys/KeyManager.cs, WalletWasabi/Blockchain/Mempool/MempoolService.cs, WalletWasabi/Extensions/LinqExtensions.cs, WalletWasabi/Extensions/ListExtensions.cs, WalletWasabi/Extensions/NBitcoinExtensions.cs, WalletWasabi/Gma/QrCodeNet/Encoding/DataEncodation/DataEncode.cs, WalletWasabi/Gma/QrCodeNet/Encoding/DataEncodation/InputRecognition/InputRecognise.cs, WalletWasabi/Gma/QrCodeNet/Encoding/ReedSolomon/ReedSolomonEncoder.cs, WalletWasabi/Gma/QrCodeNet/Encoding/Versions/ErrorCorrectionBlocks.cs, WalletWasabi/Helpers/Guard.cs, WalletWasabi/Helpers/IoHelpers.cs, WalletWasabi/Helpers/PasswordHelper.cs, WalletWasabi/Io/DigestableSafeMutexIoManager.cs, WalletWasabi/Mono/CommandSet.cs, WalletWasabi/Mono/OptionSet.cs, WalletWasabi/Mono/StringCoda.cs, WalletWasabi/Nito/AsyncEx/Synchronous/SynchronousTaskExtensions.cs, WalletWasabi/Nito/Collections/CollectionHelpers.cs, WalletWasabi/Nito/Collections/Deque.cs, WalletWasabi/Stores/IndexStore.cs, WalletWasabi/Tor/Http/Helpers/HttpMessageHelper.cs, WalletWasabi/Tor/Http/TorHttpClient.cs, WalletWasabi/Tor/Socks5/TorSocks5Client.cs
Mostly: https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/null-coalescing-operator
=> Use some null syntax sugars to simplify the codebase

WalletWasabi.Tests/UnitTests/Crypto/ProofSystemTests.cs, WalletWasabi/Crypto/CoordinatorSecretKey.cs, WalletWasabi/Crypto/Mac.cs, WalletWasabi/Crypto/ZeroKnowledge/LinearRelation/Statement.cs, WalletWasabi/Crypto/ZeroKnowledge/ProofSystem.cs, WalletWasabi/Crypto/ZeroKnowledge/Transcript.cs
This PR is a first attempt to create and to verify proofs of iparams (proofs that prove that a given mac was created using the secret key corresponding to the public iparams).
=> Proof of iparams

azure-pipelines-detbuild.yml
Same but with clean commit history https://github.com/zkSNACKs/WalletWasabi/pull/4345
=> Check deterministic builds with CI 2

WalletWasabi.Gui/Controls/WalletExplorer/CoinListViewModel.cs, WalletWasabi.Gui/Controls/WalletExplorer/WalletExplorerViewModel.cs, WalletWasabi.Gui/ViewModels/StatusBarViewModel.cs, WalletWasabi.Tests/UnitTests/Hwi/HwiProcessBridgeMock.cs, WalletWasabi/Hwi/Parsers/HwiParser.cs
It would be easier to review without whitespace changes:
https://github.com/zkSNACKs/WalletWasabi/pull/4307/files?diff=unified&w=1
=> Fix formatting

WalletWasabi.Gui/Tabs/WalletManager/LoadWallets/LoadWalletViewModel.cs
=> Don't change the selected wallet when loading

WalletWasabi/Tor/TorInstallator.cs
This is part of #4244 project where I would actually like to get rid of those `await Task.Delay(3000);` delays in `TorTests` and enforce that when you start Tor and you ask for `ensureRunning` it will be started or an exception will be thrown. This PR paves the path to that goal.
Notes:
* This PR simplifies code logic in `TorInstaller`.
* It is easier to review using side-by-side view: https://github.com/zkSNACKs/WalletWasabi/pull/4374/files?diff=split&w=1
=> Remove code duplication from TorInstallator.

WalletWasabi/CoinJoin/Client/Rounds/ClientState.cs
Not a fan of touching the CJ code, but this one seems like a nobrainer.
=> Simplify AnyCoinsQueued

WalletWasabi.Gui/Controls/WalletExplorer/SendControlViewModel.cs
This code was added in #4060 but that PR was "reverted" with #4346.
=> Remove leftover code

WalletWasabi.Tests/UnitTests/Crypto/TranscriptTests.cs, WalletWasabi.Tests/UnitTests/Crypto/ZeroKnowledge/LinearRelationTests.cs, WalletWasabi/Crypto/ZeroKnowledge/LinearRelation/Equation.cs, WalletWasabi/Crypto/ZeroKnowledge/LinearRelation/Knowledge.cs, WalletWasabi/Crypto/ZeroKnowledge/LinearRelation/Statement.cs, WalletWasabi/Crypto/ZeroKnowledge/NonInteractive/FiatShamirTransform/Prover.cs, WalletWasabi/Crypto/ZeroKnowledge/NonInteractive/Proof.cs, WalletWasabi/Crypto/ZeroKnowledge/SyntheticSecretNonceProvider.cs, WalletWasabi/Helpers/Guard.cs
This PR contains the first set of commits from the _big_mess_ PR #4377
=> [WabiSabi] Remove Simulators and refactor ResponseToChallenge

WalletWasabi.Tests/UnitTests/Crypto/ZeroKnowledge/LinearRelationTests.cs, WalletWasabi/Crypto/Mac.cs, WalletWasabi/Crypto/ZeroKnowledge/LinearRelation/Equation.cs, WalletWasabi/Crypto/ZeroKnowledge/LinearRelation/Knowledge.cs, WalletWasabi/Crypto/ZeroKnowledge/LinearRelation/Statement.cs
=> Wabi sabi/small improvements

WalletWasabi.Gui/Controls/WalletExplorer/SendControlView.xaml
I removed two controls because seemingly they are not in use.
@danwalmsley Can you take a look at it? Can it be something Avalonia magic hack?
=> Remove unnecessary controls in SendControlView.xaml

WalletWasabi.Backend/wwwroot/index.html
SEO / open graph social optimization
=> Add site_name metatag og to the website

WalletWasabi.Tests/UnitTests/Crypto/ProofSystemTests.cs, WalletWasabi/Crypto/ZeroKnowledge/ProofSystem.cs
opening instead of #4401 because I can't push to that branch
=> Add balance proof

WalletWasabi.Tests/UnitTests/Crypto/ZeroKnowledge/LinearRelationTests.cs, WalletWasabi/Crypto/ZeroKnowledge/LinearRelation/Equation.cs, WalletWasabi/Crypto/ZeroKnowledge/LinearRelation/Knowledge.cs
More comprehensive tests for verifier rejection.
=> [WabiSabi] Improve LinearRelation.Equation tests

WalletWasabi.Gui/Controls/WalletExplorer/SendControlViewModel.cs
=> Remove initialvalue

WalletWasabi/Tor/Socks5/TorSocks5Client.cs
This is part of work on #4421 where I try to simplify the code first. 
This PR is an attempt to get feedback on removing some dead code from `TorSocks5Client`. It may still be useful (even unused) or it may not. I don't know. Hence the PR to find out.
=> TorSocks5Client: Remove unused code.

WalletWasabi/Wallets/P2pBlockProvider.cs
That commented out code was added in #3512 
@lontivero Is there a reason you left it there?
=> Remove commented out code

WalletWasabi/Tor/Http/TorHttpClient.cs
This PR adds minor changes to make #4446 PR smaller.
The PR does not change behavior. It only removes `Create` method and as such removes various nullable warnings.
=> Merge constructors in TorHttpClient.

WalletWasabi.Gui/Global.cs, WalletWasabi/Blockchain/Analysis/FeesEstimation/FeeProviders.cs
Small refactoring of the `FeeProviders` class.
=> Move event invocation outside of Lock

WalletWasabi.Gui/Controls/WalletExplorer/HistoryTabViewModel.cs, WalletWasabi.Gui/Controls/WalletExplorer/TransactionInfoTabViewModel.cs, WalletWasabi.Gui/Controls/WalletExplorer/TransactionViewModel.cs
=> Fix lurking wife mode in transaction details

WalletWasabi.Backend/Global.cs, WalletWasabi.Backend/Startup.cs
Reverts zkSNACKs/WalletWasabi#4474
It's actually needed for the regtests.
=> Revert "Remove leftover code"

WalletWasabi.Backend/Global.cs
This part of https://github.com/zkSNACKs/WalletWasabi/pull/4479 still good.
=> Remove unused ctor

WalletWasabi.Fluent/App.xaml, WalletWasabi.Fluent/Styles/Styles.xaml, WalletWasabi.Fluent/Styles/Themes/BaseDark.xaml, WalletWasabi.Fluent/Styles/Themes/BaseLight.xaml, WalletWasabi.Fluent/Views/MainView.axaml, WalletWasabi.Fluent/Views/NavBar.axaml, WalletWasabi.Fluent/Views/StatusBar.axaml
You can try the light theme by changing the `BaseDark.xaml` to `BaseLight.xaml` in `App.xaml`.
=> [Fluent] Dark and Light theme prework

WalletWasabi.Backend/Controllers/LegacyController.cs
I got this request. Apparently external applications are using this call.
=> Add legacy get all fees API

WalletWasabi.Backend/Controllers/LegacyController.cs
Another things needed for someone.
=> Add legacy exchange-rate API

WalletWasabi.Backend/wwwroot/index.html
On-page SEO. This PR updates `title` and `h1` tags with the aim of improving the ranking of certain keywords.
Feel free to propose something else if you don't like the actual title/slogan.
=> Update and optimize title and h1

WalletWasabi/Tor/Socks5/TorSocks5Client.cs
=> Tor restart.

WalletWasabi.Gui/Controls/TransactionDetails/Views/TransactionDetails.xaml, WalletWasabi.Gui/Controls/WalletExplorer/CoinJoinTabView.xaml, WalletWasabi.Gui/Controls/WalletExplorer/CoinJoinTabViewModel.cs, WalletWasabi.Gui/Controls/WalletExplorer/CoinListView.xaml, WalletWasabi.Gui/Controls/WalletExplorer/CoinListViewModel.cs, WalletWasabi.Gui/Controls/WalletExplorer/CoinViewModel.cs, WalletWasabi.Gui/Controls/WalletExplorer/HistoryTabView.xaml, WalletWasabi.Gui/Controls/WalletExplorer/HistoryTabViewModel.cs, WalletWasabi.Gui/Controls/WalletExplorer/ReceiveTabView.xaml, WalletWasabi.Gui/Controls/WalletExplorer/TransactionInfoTabView.xaml, WalletWasabi.Gui/Controls/WalletExplorer/TransactionInfoTabViewModel.cs, WalletWasabi.Gui/Controls/WalletExplorer/TransactionViewerView.xaml, WalletWasabi.Gui/Controls/WalletExplorer/TransactionViewerViewModel.cs, WalletWasabi.Gui/Controls/WalletExplorer/WalletExplorerView.xaml, WalletWasabi.Gui/Controls/WalletExplorer/WalletExplorerViewModel.cs, WalletWasabi.Gui/Controls/WalletExplorer/WalletInfoView.xaml, WalletWasabi.Gui/Controls/WalletExplorer/WalletInfoViewModel.cs, WalletWasabi.Gui/Controls/WalletExplorer/WalletViewModel.cs, WalletWasabi.Gui/Converters/PrivacyModeStringConverter.cs, WalletWasabi.Gui/Global.cs, WalletWasabi.Gui/UiConfig.cs, WalletWasabi.Gui/ViewModels/AddressViewModel.cs, WalletWasabi.Tests/UnitTests/MemoryTests.cs, WalletWasabi.Tests/UnitTests/NBitcoinTests.cs, WalletWasabi/Extensions/NBitcoinExtensions.cs
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/4527
=> Rename to PrivacyMode

.shellcheckrc
According to this https://github.com/koalaman/shellcheck/blob/master/shellcheck.1.md#rc-files
=> Add CodeFactor shell checker config

WalletWasabi.Gui/UiConfig.cs
Fixing: 
https://github.com/zkSNACKs/WalletWasabi/pull/4528#issuecomment-707155584
=> Rename to privacy mode in UiConfig

WalletWasabi.Fluent/ViewModels/WalletViewModel.cs
=> [Fluent] Rename LWM to Privacy Mode

WalletWasabi.Fluent.Desktop/WalletWasabi.Fluent.Desktop.csproj, WalletWasabi.Fluent/WalletWasabi.Fluent.csproj
Should we also add other configurations to these csproj files, like:
```
<LangVersion>latest</LangVersion>
<NoWarn>1701;1702;1705;1591;CA1031</NoWarn>
```
=> Add Nullable reference types to new projects (Fluent)

WalletWasabi/CoinJoin/Coordinator/Rounds/CoordinatorRound.cs
Removed `then no need to pay it.` from the comment because if Alice doesn't have enough btc she would pay whatever she can.
=> [Trivial] Correct comment

WalletWasabi/Tor/Socks5/Models/Messages/TorSocks5Request.cs
=> TorSocks5Request: Remove unused constructor.

WalletWasabi/Services/WasabiSynchronizer.cs
This PR only adds a few missing `ConfigureAwait(false)` in `WasabiSynchronizer` class.
=> WasabiSynchronizer: Add missing ConfigureAwait(false).

WalletWasabi.Backend/WalletWasabi.Backend.csproj, WalletWasabi.Fluent.Desktop/WalletWasabi.Fluent.Desktop.csproj, WalletWasabi.Fluent/WalletWasabi.Fluent.csproj, WalletWasabi.Gui/WalletWasabi.Gui.csproj, WalletWasabi.Packager/WalletWasabi.Packager.csproj, WalletWasabi.Tests/WalletWasabi.Tests.csproj, WalletWasabi/WalletWasabi.csproj
I also fixed the indentation of the csproj files so please review without whitespace changes: https://github.com/zkSNACKs/WalletWasabi/pull/4548/files?diff=split&w=1
=> [Fluent] Add some common csproj settings

WalletWasabi.Gui/Global.cs
This PR make scope of variables shorter and thus prevents possible mistakes.
=> Use shorter syntax in Global class.

WalletWasabi.Tests/UnitTests/BitcoinCore/P2pBasedTests.cs, WalletWasabi/BitcoinCore/Rpc/IRPCClient.cs, WalletWasabi/BitcoinCore/Rpc/RpcClientBase.cs, WalletWasabi/Blockchain/Mempool/MempoolService.cs, WalletWasabi/Services/HostedServices.cs
`MempoolNotifiesAsync` is flaky test. This PR:
* Documents more the test.
* Increases timeout from 21 to 30 seconds.
* Fixes several nullability warnings.
This does not fix the test, I need dig a little deeper to understand the issue.
=> Document more `MempoolNotifiesAsync` test.

WalletWasabi.Gui/Controls/WalletExplorer/ReceiveTabViewModel.cs
Fixes: https://github.com/zkSNACKs/WalletWasabi/issues/4007
=> QR without extra click

WalletWasabi.Gui/Helpers/NotificationHelpers.cs
This PR only fixes a few instances of nullability warnings.
=> trivial: Fix nullability issues in NotificationHelpers.cs

WalletWasabi/Tor/Socks5/TorSocks5Client.cs
=> trivial: Use new syntax in TorSocks5Client.cs

WalletWasabi.Gui/Program.cs
Part of https://github.com/zkSNACKs/WalletWasabi/issues/4553
Make program.cs execution path straight by removing control statements.
=> Remove control statements from Main()

WalletWasabi/Tor/Socks5/Models/Fields/OctetFields/NMethodsField.cs, WalletWasabi/Tor/Socks5/Models/Messages/VersionMethodRequest.cs
This PR refactors VersionMethodRequest & NMethodsField to accept parameters via constructor.
The PR is easier to review commit by commit.
=> VersionMethodRequest & NMethodsField refactoring.

WalletWasabi/Tor/Socks5/TorSocks5Client.cs
Please review #4507 first.
This PR changes only accessibility modifiers to allow me to do further refactorings.
=> TorSocks5Client: Adjust accessibility modifiers.

WalletWasabi.Gui/Controls/StatusBar.xaml, WalletWasabi.Gui/Controls/WalletExplorer/CoinInfoTabView.xaml, WalletWasabi.Gui/Controls/WalletExplorer/HistoryTabViewModel.cs, WalletWasabi.Gui/Controls/WalletExplorer/SendTabViewModel.cs, WalletWasabi.Gui/Controls/WalletExplorer/WalletInfoView.xaml, WalletWasabi.Gui/CrashReport/ViewModels/CrashReportWindowViewModel.cs, WalletWasabi.Gui/CrashReport/Views/CrashReportWindow.xaml, WalletWasabi.Gui/Tabs/AboutView.xaml, WalletWasabi.Gui/Tabs/LegalDocumentsView.xaml, WalletWasabi.Gui/Tabs/SettingsView.xaml, WalletWasabi.Gui/UiConfig.cs, WalletWasabi.Gui/ViewModels/StatusBarViewModel.cs, WalletWasabi/Blockchain/Transactions/TransactionFactory.cs, WalletWasabi/CoinJoin/Client/Clients/CoinJoinClient.cs, WalletWasabi/Hwi/Models/HardwareWalletModels.cs, WalletWasabi/Legal/Assets/LegalDocuments.txt, WalletWasabi/TorSocks5/TorHttpClient.cs, WalletWasabi/WebClients/PayJoin/PayjoinClient.cs
According to this: https://github.com/zkSNACKs/WalletWasabi/projects/19
- **UI improvements** https://github.com/zkSNACKs/WalletWasabi/pull/4272 https://github.com/zkSNACKs/WalletWasabi/pull/4186 https://github.com/zkSNACKs/WalletWasabi/pull/4323 https://github.com/zkSNACKs/WalletWasabi/pull/4334 https://github.com/zkSNACKs/WalletWasabi/pull/4283 https://github.com/zkSNACKs/WalletWasabi/pull/4163 https://github.com/zkSNACKs/WalletWasabi/pull/4285 https://github.com/zkSNACKs/WalletWasabi/pull/4316 https://github.com/zkSNACKs/WalletWasabi/pull/4286 https://github.com/zkSNACKs/WalletWasabi/pull/4404
- **PayJoin** https://github.com/zkSNACKs/WalletWasabi/pull/4427 
- **Business logic improvements** https://github.com/zkSNACKs/WalletWasabi/pull/4525 …
=> [Backport] Cherry picking changes to v1.1.1.12.1

WalletWasabi.Backend/wwwroot/index.html, WalletWasabi/Helpers/Constants.cs
@RiccardoMasutti can you create the corresponding PR to the docs? 🙏
=> Dump version to v1.1.12.1 backport release

WalletWasabi.Fluent/ViewModels/WalletViewModel.cs, WalletWasabi.Gui/Controls/QrCode.cs, WalletWasabi.Gui/Controls/WalletExplorer/CoinJoinTabViewModel.cs, WalletWasabi.Gui/Controls/WalletExplorer/HistoryTabViewModel.cs, WalletWasabi.Gui/Controls/WalletExplorer/SendControlViewModel.cs, WalletWasabi.Gui/Controls/WalletExplorer/TransactionBroadcasterViewModel.cs, WalletWasabi.Gui/Controls/WalletExplorer/WalletViewModel.cs, WalletWasabi.Gui/Tabs/SettingsViewModel.cs, WalletWasabi.Gui/Tabs/WalletManager/HardwareWallets/ConnectHardwareWalletViewModel.cs, WalletWasabi.Gui/Tabs/WalletManager/LoadWallets/LoadWalletViewModel.cs, WalletWasabi.Gui/ViewModels/MainWindowViewModel.cs, WalletWasabi.Gui/ViewModels/StatusBarViewModel.cs, WalletWasabi/Blockchain/Analysis/Clustering/Cluster.cs
This will get rid of some null warnings.
I tested coinjoining and sending and different stuff and everything worked properly.
=> Initialize the backing field instead of the property in the constructor

WalletWasabi/CoinJoin/Client/Clients/CoinJoinClient.cs
This PR makes it easier to understand stopping logic of `CoinJoinClient`.
=> CoinJoinClient: Constants for state & dispose cleanup

WalletWasabi/Tor/Socks5/Models/Bases/ByteArraySerializableBase.cs, WalletWasabi/Tor/Socks5/Models/Fields/ByteArrayFields/PasswdField.cs, WalletWasabi/Tor/Socks5/Models/Fields/OctetFields/PLenField.cs, WalletWasabi/Tor/Socks5/Models/Fields/OctetFields/ULenField.cs, WalletWasabi/Tor/Socks5/Models/Messages/TorSocks5Response.cs, WalletWasabi/Tor/Socks5/Models/Messages/UsernamePasswordRequest.cs, WalletWasabi/Tor/Socks5/Models/Messages/UsernamePasswordResponse.cs
Similar to #4582 & #4602 this PR removes some unused constructors.
=> Remove some unused constructors

WalletWasabi.Gui/Controls/WalletExplorer/CoinJoinTabViewModel.cs, WalletWasabi.Gui/Controls/WalletExplorer/CoinListViewModel.cs, WalletWasabi.Gui/Controls/WalletExplorer/SendControlViewModel.cs
Pass the needed dependencies via constructor so that the code is testable.
https://github.com/zkSNACKs/WalletWasabi/pull/4444#discussion_r497392960
https://github.com/zkSNACKs/WalletWasabi/pull/3756#issuecomment-652442279
=> Pass dependencies via constructor in CoinListViewModel (remove Locator)

WalletWasabi.Fluent.Desktop/WalletWasabi.Fluent.Desktop.csproj, WalletWasabi.Fluent/Styles/Styles.xaml, WalletWasabi.Fluent/WalletWasabi.Fluent.csproj
cc @danwalmsley @soosr @molnard
=> Add Label Styles + move fontsize values to resources

WalletWasabi.Gui/packages.lock.json, WalletWasabi.Packager/packages.lock.json, WalletWasabi/WalletWasabi.csproj, WalletWasabi/packages.lock.json
It's been added to .NET Core so no need for it anymore.
=> Remove registry package

WalletWasabi.Gui/Controls/WalletExplorer/CoinJoinTabViewModel.cs, WalletWasabi.Gui/MainWindow.xaml.cs, WalletWasabi.Gui/ViewModels/MainWindowViewModel.cs
Use `Global.WalletManager.AnyCoinJoinInProgress()` that is more general.
=> Remove the canClose property

WalletWasabi.Fluent.Desktop/Program.cs
Similar to https://github.com/zkSNACKs/WalletWasabi/pull/4604/commits/d35f376dbe4490bfa8fd4328a7495c467056ad75
=> Fix nullable warnings

WalletWasabi/Tor/Socks5/TorSocks5Client.cs
* This is continuation of #4581.
* The docs slightly helps distinguish what is sent where over which stream.
=> TorSocks5Client: Add missing cancellation token + some docs.

WalletWasabi/Tor/Http/TorHttpClient.cs
=> [trivial] Remove superfluous command.

WalletWasabi.Gui/Controls/WalletExplorer/CoinViewModel.cs, WalletWasabi.Gui/Global.cs, WalletWasabi.Gui/Rpc/WasabiJsonRpcService.cs, WalletWasabi.Tests/Common.cs, WalletWasabi.Tests/RegressionTests/BuildTests.cs, WalletWasabi.Tests/RegressionTests/CoinJoinTests.cs, WalletWasabi.Tests/RegressionTests/SendTests.cs, WalletWasabi.Tests/RegressionTests/WalletTests.cs, WalletWasabi.Tests/UnitTests/SmartCoinTests.cs, WalletWasabi.Tests/UnitTests/Transactions/AllTransactionStoreTests.cs, WalletWasabi.Tests/UnitTests/Transactions/OperationMergerTests.cs, WalletWasabi.Tests/UnitTests/Transactions/PayjoinTests.cs, WalletWasabi.Tests/UnitTests/Transactions/TransactionFactoryTests.cs, WalletWasabi.Tests/UnitTests/Transactions/TransactionProcessorTests.cs, WalletWasabi.Tests/UnitTests/Transactions/TransactionStoreTests.cs, WalletWasabi/Blockchain/Analysis/Clustering/Cluster.cs, WalletWasabi/Blockchain/TransactionBuilding/BuildTransactionResult.cs, WalletWasabi/Blockchain/TransactionBuilding/SmartCoinSelector.cs, WalletWasabi/Blockchain/TransactionOutputs/CoinsRegistry.cs, WalletWasabi/Blockchain/TransactionOutputs/CoinsView.cs, WalletWasabi/Blockchain/TransactionOutputs/SmartCoin.cs, WalletWasabi/Blockchain/TransactionProcessing/TransactionProcessor.cs, WalletWasabi/Blockchain/Transactions/TransactionFactory.cs, WalletWasabi/Blockchain/Transactions/TransactionHistoryBuilder.cs, WalletWasabi/Blockchain/Transactions/TransactionSummary.cs, WalletWasabi/CoinJoin/Client/Clients/CoinJoinClient.cs, WalletWasabi/CoinJoin/Client/Rounds/ClientState.cs, WalletWasabi/Extensions/NBitcoinExtensions.cs, WalletWasabi/Wallets/Wallet.cs
- I'm trying to improve performance in https://github.com/zkSNACKs/WalletWasabi/pull/4631
- In order to do so, I figured `SmartCoin` must know a couple of things it didn't know before.  
- In order to add that capability I want to bring a few things into a new `Links` object.  
This PR is a `SmartCoin` refactoring PR to put down the basics. It has 2 main goals, `SmartCoin` to point to the `SmartTransaction` it is included in and its spender `SmartTransaction`.
=> Refactor SmartCoin

WalletWasabi/Blockchain/TransactionOutputs/SmartCoin.cs
It's correct, but couldn't notice much performance gain :(
=> Lazy coins

WalletWasabi.Tests/RegressionTests/BackendTests.cs, WalletWasabi/Tor/Http/Interfaces/ITorHttpClient.cs, WalletWasabi/WebClients/Wasabi/WasabiClient.cs
See: https://github.com/zkSNACKs/WalletWasabi/pull/4642#discussion_r518130537
=> Remove ITorHttpClient.SendAndRetryAsync.

WalletWasabi.Tests/UnitTests/Transactions/PayjoinTests.cs, WalletWasabi/Tor/Http/Interfaces/ITorHttpClient.cs, WalletWasabi/Tor/Http/TorHttpClient.cs, WalletWasabi/WebClients/PayJoin/PayjoinClient.cs
**Notes:**
* Removes three properties from `ITorHttpClient` interface [[here](https://github.com/zkSNACKs/WalletWasabi/pull/4692/files#diff-f537d33fa752a5c57e24cb564f756348ce20485026e18da16111d62cf9b62379L11)]. This is useful for my further refactorings.
=> Slim down ITorHttpClient.

WalletWasabi/Tor/Http/TorHttpClient.cs, WalletWasabi/Tor/Socks5/TorSocks5Client.cs
This PR improves encapsulation of TorSocks5Client properties. It's rather trivial but helpful for my next PRs.
=> TorSocks5Client: Stream encapsulation

WalletWasabi.Backend/wwwroot/index.html
Hey guys, updating the link to my personal website as the old link no longer exists. Also, added "website" to the sentence to make sure I'm not accidentally given undue credit for all of your hard work. Cheers!
=> Update footer link on website

WalletWasabi/Nito/AsyncEx/AsyncLock.cs
See https://github.com/StephenCleary/AsyncEx/blob/8a73d0467d40ca41f9f9cf827c7a35702243abb8/src/Nito.AsyncEx.Coordination/AsyncLock.cs#L81
=> [trivial] AsyncLock: Fix nullability issue.

WalletWasabi.Tests/RegressionTests/BackendTests.cs, WalletWasabi.Tests/UnitTests/Clients/MockTorHttpClient.cs, WalletWasabi.Tests/UnitTests/Transactions/PayjoinTests.cs, WalletWasabi/Tor/Http/BackendHttpClient.cs, WalletWasabi/Tor/Http/ClearnetHttpClient.cs, WalletWasabi/Tor/Http/IRelativeHttpClient.cs, WalletWasabi/Tor/Http/Interfaces/ITorHttpClient.cs, WalletWasabi/Tor/Http/TorHttpClient.cs
https://github.com/zkSNACKs/WalletWasabi/pull/4698 was reverted because of a compilation error. That build error is most likely a result of merging another PR because when I published the original PR it worked OK.
=> Add IRelativeHttpClient (2)

WalletWasabi.Fluent/ViewModels/AddWallet/ConfirmRecoveryWordsViewModel.cs, WalletWasabi.Fluent/ViewModels/AddWallet/RecoverWalletViewModel.cs, WalletWasabi.Fluent/ViewModels/AddWallet/RecoveryWordsViewModel.cs, WalletWasabi.Fluent/ViewModels/AddWalletPageViewModel.cs, WalletWasabi.Fluent/ViewModels/Dialogs/TestDialogViewModel.cs, WalletWasabi.Fluent/ViewModels/NavBar/NavBarItemViewModel.cs, WalletWasabi.Fluent/ViewModels/NavBar/NavBarViewModel.cs, WalletWasabi.Fluent/ViewModels/RoutableViewModel.cs, WalletWasabi.Fluent/ViewModels/SettingsPageViewModel.cs
`RoutableViewModel` navigation helper methods:
```C#
void NavigateTo(RoutableViewModel viewModel, NavigationTarget navigationTarget, bool resetNavigation = false);
void NavigateToSelf();
void NavigateToSelfAndReset();
void GoBack(NavigationTarget navigationTarget);
void GoBack();
void ClearNavigation(NavigationTarget navigationTarget);
void ClearNavigation();
```
=> [Fluent] Added and refactored RoutableViewModel navigation helper methods
