WalletWasabi/WalletWasabi

- WalletWasabi/WebClients/Wasabi/WasabiClient.cs
This allows to use WasabiClient more easily with clearnet HTTP client.
> [trivial] Use IRelativeHttpClient instead of ITorHttpClient in WasabiClient.

- WalletWasabi.Gui/Tabs/WalletManager/LoadWallets/LoadWalletViewModel.cs
- WalletWasabi.Gui/Tabs/WalletManager/WalletManagerViewModel.cs
To make the code testable.
https://github.com/zkSNACKs/WalletWasabi/pull/4444#discussion_r497392960
https://github.com/zkSNACKs/WalletWasabi/pull/3756#issuecomment-652442279
> Pass dependency via constructor (remove Locator)

- WalletWasabi.Tests/RegressionTests/BackendTests.cs
> [easy] Backend tests to use ClearnetHttpClient

- WalletWasabi/Io/MutexIoManager.cs
Not sure what happened here. Thanks for @yahiheb to notice it: https://github.com/zkSNACKs/WalletWasabi/pull/4730/files#diff-5256e8e84e712b5721d8b586447977648432cefd5c3d43d682c9e8f0998a0414
> Fix off by one bug

- WalletWasabi.Fluent.Desktop/WalletWasabi.Fluent.Desktop.csproj
- WalletWasabi.Fluent/App.xaml
- WalletWasabi.Fluent/Views/HomePageView.axaml
- WalletWasabi.Fluent/Views/MainView.axaml
- WalletWasabi.Fluent/Views/MainWindow.axaml
- WalletWasabi.Fluent/Views/NavBar/NavBar.axaml
- WalletWasabi.Fluent/WalletWasabi.Fluent.csproj
> Unify the Navbar on OSX and Windows

- WalletWasabi.Tests/UnitTests/Clients/MockTorHttpClient.cs
- WalletWasabi/Tor/Http/Interfaces/ITorHttpClient.cs
- WalletWasabi/Tor/Http/TorHttpClient.cs
This PR only remove no-longer used property.
> [trivial] ITorHttpClient: Remove IsTorUsed property.

- WalletWasabi.Gui/Global.cs
Added missing `cancel.ThrowIfCancellationRequested();` between long/awaited initializations.
> Improve cancellation of initialization

- WalletWasabi.Gui/Tabs/WalletManager/RecoverWallets/RecoverWalletViewModel.cs
> Recover button CanExecute logic

- WalletWasabi.Fluent/App.xaml
- WalletWasabi.Fluent/Controls/Dialog.xaml
- WalletWasabi.Fluent/Controls/ProgressRing.xaml
- WalletWasabi.Fluent/Styles/Styles.xaml
> [Fluent] Use standardized fluent easing in resources

- WalletWasabi.Fluent/Controls/ProgressRingArc.xaml
> [Fluent] Make endcaps on progress ring indicator round.

- WalletWasabi.Tests/UnitTests/BlockchainAnalysis/PubKeyReuseAnonScoreTests.cs
- WalletWasabi/Blockchain/Analysis/BlockchainAnalyzer.cs
> Add sanity check to BlockchainAnalyzer.AdjustWalletInputs

- .editorconfig
- WalletWasabi/Bases/PeriodicRunner.cs
- WalletWasabi/BitcoinCore/CoreNode.cs
- WalletWasabi/BitcoinCore/P2pNode.cs
- WalletWasabi/BitcoinCore/Processes/BitcoindRpcProcessBridge.cs
- WalletWasabi/Blockchain/Transactions/TransactionStore.cs
- WalletWasabi/Stores/IndexStore.cs
- WalletWasabi/Tor/Http/TorHttpClient.cs
- WalletWasabi/Tor/Socks5/TorSocks5Client.cs
- WalletWasabi/Wallets/FileSystemBlockRepository.cs
- WalletWasabi/Wallets/Wallet.cs
- WalletWasabi/WebClients/PayJoin/PayjoinClient.cs
This PR adds the CancellationToken forwarding rule (CA2016) to .editorconfig, and applies it through the code base.
https://github.com/zkSNACKs/WalletWasabi/issues/4752#issuecomment-733712110
https://github.com/zkSNACKs/WalletWasabi/issues/4752#issuecomment-734338337
> Add CancellationToken forwarding rule (CA2016)

- WalletWasabi.Fluent/ViewModels/MainViewModel.cs
- WalletWasabi.Fluent/ViewModels/NavBar/NavBarViewModel.cs
- WalletWasabi.Fluent/Views/MainView.axaml
> [Fluent] Collapse navbar view when there are no wallets available.

- WalletWasabi.Fluent.Desktop/WalletWasabi.Fluent.sln
When I load the solution with VS on windows I got this:
> Some of the properties associated with the solution could not be read.
Seemingly everything is working but the error keeps coming at every SLN load.
This fixes the problem caused by Solution Items
> [Fluent] Fix solution file

- WalletWasabi.Fluent.Generators/NavigationMetaDataGenerator.cs
- WalletWasabi.Fluent/ViewModels/AboutViewModel.cs
- WalletWasabi.Fluent/ViewModels/AddWallet/AddWalletPageViewModel.cs
- WalletWasabi.Fluent/ViewModels/AddWallet/LegalDocumentsViewModel.cs
- WalletWasabi.Fluent/ViewModels/HomePageViewModel.cs
- WalletWasabi.Fluent/ViewModels/MainViewModel.cs
- WalletWasabi.Fluent/ViewModels/NavBar/NavBarItemViewModel.cs
- WalletWasabi.Fluent/ViewModels/Navigation/NavigationState.cs
- WalletWasabi.Fluent/ViewModels/Navigation/RoutableViewModel.cs
- WalletWasabi.Fluent/ViewModels/Search/SearchPageViewModel.cs
- WalletWasabi.Fluent/ViewModels/Settings/BitcoinTabSettingsViewModel.cs
- WalletWasabi.Fluent/ViewModels/Settings/SettingsPageViewModel.cs
- WalletWasabi.Fluent/Views/Settings/BitcoinSettingsView.xaml
- WalletWasabi.Fluent/Views/Settings/SettingsPageView.xaml
> Fluent: more metadata.

- WalletWasabi.Documentation/Guides/20180719DemoGuide.md
- WalletWasabi.Documentation/Guides/20190416HardwareWalletTestingGuide.md
- WalletWasabi.Documentation/Guides/20190617ContributionGame.md
Removed old/broken guides and links.
> Clean documentation

- WalletWasabi.Tests/UnitTests/Transactions/TransactionFactoryTests.cs
> TransactionFactoryTests: Fix usings.

- WalletWasabi.Backend/wwwroot/index.html
- WalletWasabi/Helpers/Constants.cs
Changelist https://github.com/zkSNACKs/WalletWasabi/compare/bcd267c17a60c038c4ca5f091bd4df361137f831...backport
This silent release fixes Ledger incompatibility.
- **Ledger hardware wallet fix for Ledger 1.5.1 firmware**
While setting up Wasabi is straightforward, even a Linux wizard with the longest beard can get stuck on the most basic tasks. Consider taking a look at the [Installation Instructions](https://docs.wasabiwallet.io/using-wasabi/InstallPackage.html) guide.
If you want to build Wasabi from source code or update the source code check out [these instructions.](https://docs.wasabiwallet.io/using-wasabi/BuildSource.html)
From version 1.1.3 Wasabi also introduces [reproducible builds](https://reproducible-builds.org/): [Deterministic Build …
> Dump version to 1.1.12.3

- .editorconfig
https://github.com/zkSNACKs/WalletWasabi/pull/4865#issuecomment-739891625
> Add rule to disable CA1816 warnings

- WalletWasabi/Microservices/ProcessAsync.cs
It's better to use API shipped with .NET 5 rather than our implementation.
> Use Process.WaitForExitAsync from .NET 5.

- WalletWasabi.Fluent/Styles/TextBox.xaml
- WalletWasabi.Fluent/Views/AddWallet/RecoverWalletView.axaml
- WalletWasabi.Fluent/Views/Dialogs/AdvancedRecoveryOptionsView.axaml
- Advanced rec opt buttons margins.
- Error text shifts the control
cc @danwalmsley
> Fluent layout minifixes

- WalletWasabi.Fluent/Views/Search/SearchPageView.axaml
> [Fluent] Action Center layout optimization

- WalletWasabi.Fluent/ViewModels/AboutViewModel.cs
- WalletWasabi.Fluent/ViewModels/AddWallet/AddWalletPageViewModel.cs
- WalletWasabi.Fluent/ViewModels/AddWallet/RecoverWalletViewModel.cs
- WalletWasabi.Fluent/ViewModels/Dialogs/AdvancedRecoveryOptionsViewModel.cs
- WalletWasabi.Fluent/ViewModels/Dialogs/DialogResult.cs
- WalletWasabi.Fluent/ViewModels/Dialogs/DialogResultKind.cs
- WalletWasabi.Fluent/ViewModels/Dialogs/DialogViewModelBaseOfTResult.cs
- WalletWasabi.Fluent/ViewModels/Dialogs/EnterPasswordViewModel.cs
- WalletWasabi.Fluent/ViewModels/Dialogs/TestDialogViewModel.cs
- WalletWasabi.Fluent/ViewModels/MainViewModel.cs
- WalletWasabi.Fluent/ViewModels/Navigation/RoutableViewModel.cs
- WalletWasabi.Fluent/ViewModels/Navigation/TargettedNavigationStack.cs
- WalletWasabi.Fluent/ViewModels/TransactionBroadcasting/LoadTransactionViewModel.cs
Allows us to know if dialogs were cancelled or back button was pressed.
> Fluent implement a DialogResult<T>

- WalletWasabi/Blockchain/TransactionBroadcasting/TransactionBroadcaster.cs
This is in attempt to fix the following issues: #4766 & #4955
https://github.com/zkSNACKs/WalletWasabi/issues/4766#issuecomment-748582660
> Add trivial logs to catch null exception (backport)

- WalletWasabi.Tests/UnitTests/Hwi/HwiBinaryHashesTests.cs
- WalletWasabi/Microservices/MicroserviceHelpers.cs
> Implement HWI checksums checking.

- WalletWasabi.Tests/UnitTests/Transactions/TransactionProcessorTests.cs
Similar to #4861.
It is better to review this PR commit by commit.
> Transaction processor tests usings

- WalletWasabi.Gui/Controls/WalletExplorer/SendTabViewModel.cs
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/3866
> Do not try to send again on user Cancel

- WalletWasabi.Fluent/ViewModels/AddWallet/RecoverWalletViewModel.cs
- WalletWasabi.Gui/Tabs/WalletManager/RecoverWallets/RecoverWalletViewModel.cs
A user encountered this issue and didn't know what's wrong.
> Correct capitalized mnemonic

- WalletWasabi.Fluent/ViewModels/AddWallet/HardwareWallet/ConnectHardwareWalletViewModel.cs
Fixes: https://github.com/zkSNACKs/WalletWasabi/issues/4632
Due to a bug in code logic setup was not triggered in Fluent. (worked fine in GUI project)
> Fix Trezor T initialization in Fluent

- WalletWasabi.Fluent/Views/Login/LoginView.axaml
On my machine I have noticed login button being clipped.
@soosr 
Before
After
> [Fluent] Use DockPanel in login view and do not set height

- WalletWasabi/BitcoinCore/CoreNode.cs
fixes https://github.com/zkSNACKs/WalletWasabi/issues/3588
closes https://github.com/zkSNACKs/WalletWasabi/pull/4997
I was gonna fix codescene with https://github.com/zkSNACKs/WalletWasabi/pull/4997, but found an even better oneliner solution.
> Disable daemon mode of Core on Client side

- WalletWasabi.Gui/Controls/ExtendedTextBox.cs
- WalletWasabi.Gui/Controls/WalletExplorer/SendTabViewModel.cs
- WalletWasabi.Gui/Converters/ErrorDescriptorToBorderColorConverter.cs
- WalletWasabi.Gui/Converters/ErrorSeverityColorConverter.cs
- WalletWasabi.Gui/Tabs/WalletManager/HardwareWallets/ConnectHardwareWalletViewModel.cs
- WalletWasabi.Gui/Tabs/WalletManager/LoadWallets/LoadWalletViewModel.cs
- WalletWasabi.Tests/UnitTests/BitcoinCore/ConfigTranslatorTests.cs
- WalletWasabi/BitcoinCore/Configuration/CoreConfigTranslator.cs
- WalletWasabi/BitcoinCore/CoreNode.cs
- WalletWasabi/CoinJoin/Client/Clients/CoinJoinClient.cs
- WalletWasabi/CoinJoin/Coordinator/Banning/UtxoReferee.cs
- WalletWasabi/Extensions/RPCClientExtensions.cs
- WalletWasabi/Extensions/TextReaderExtensions.cs
- WalletWasabi/Helpers/ByteHelpers.cs
- WalletWasabi/JsonConverters/BitcoinEncryptedSecretNoECJsonConverter.cs
- WalletWasabi/JsonConverters/BlockCypherDateTimeOffsetJsonConverter.cs
- WalletWasabi/JsonConverters/ByteArrayJsonConverter.cs
- WalletWasabi/JsonConverters/HDFingerprintJsonConverter.cs
- WalletWasabi/JsonConverters/KeyPathJsonConverter.cs
- WalletWasabi/JsonConverters/RoundStateResponseJsonConverter.cs
- WalletWasabi/Legal/LegalDocuments.cs
- WalletWasabi/Tor/Http/Extensions/HttpResponseMessageExtensions.cs
- WalletWasabi/Tor/Http/Helpers/HttpMessageHelper.cs
- WalletWasabi/Wallets/P2pBlockProvider.cs
- WalletWasabi/WebClients/PayJoin/IPayjoinClient.cs
- WalletWasabi/WebClients/PayJoin/PayjoinClient.cs
https://github.com/zkSNACKs/WalletWasabi/pull/5006#issuecomment-759546881
> Fix returned type of methods that return null

- WalletWasabi/Crypto/Groups/Generators.cs
- WalletWasabi/Crypto/Groups/GroupElement.cs
- WalletWasabi/Crypto/ScalarVector.cs
- WalletWasabi/Crypto/ZeroKnowledge/Credential.cs
- WalletWasabi/Crypto/ZeroKnowledge/ProofSystem.cs
- WalletWasabi/WabiSabi/Crypto/WabiSabiClient.cs
- WalletWasabi/WalletWasabi.csproj
Improves the WabiSabi credentials range proofs performance.
```
|  Method |           Job |       Runtime |    Toolchain | k |    Mean |    Error |   StdDev | Rank |
|-------- |-------------- |-------------- |------------- |-- |--------:|---------:|---------:|-----:|
| Process |    Job-OHFFZZ | .NET Core 5.0 | netcoreapp50 | 2 | 8.758 s | 0.2226 s | 0.6494 s |    1 |
```
```
|  Method |           Job |       Runtime |    Toolchain | k |    Mean |    Error |   StdDev | Rank |
|-------- |-------------- |-------------- |------------- |-- |--------:|---------:|---------:|-----:|
| Process |    Job-WTFSTS | .NET Core 5.0 | netcoreapp50 | 2 | 1.042 s | 0.0080 s | 0.0071 s |    1 |
```
> Wabisabi performance improvement

- WalletWasabi/Tor/Socks5/TorSocks5Client.cs
This PR removes `AssertConnectedAsync`.
The idea behind `AssertConnectedAsync` is that when `TcpClient.Connected` reports `false`, it tries to reconnect. 
* This is not in line with how `TcpClient` is [supposed to be used](https://stackoverflow.com/a/39402050). You should use `TcpClient` for only one connection and when it is lost, you need to create a new `TcpClient`.
* note: It seems that POSIX sockets and Windows sockets behave differently, the former does not support reconnecting on sockets and the later one does (related: https://github.com/dotnet/runtime/issues/16263#issue-558048255).
* Note also https://docs.microsoft.com/en-us/dotnet/api/system.net.sockets.tcpclient.connected?view=net-5.0#remarks 
> Because the Connected property only reflects the state of the connection as of the …
> Tor parallel bits - part 10: TorSocks5Client: Remove AssertConnectedAsync.

- WalletWasabi.Tests/UnitTests/Crypto/GroupElements/GeneralTests.cs
- WalletWasabi/Crypto/SchnorrBlindingSignature.cs
Review using: https://github.com/zkSNACKs/WalletWasabi/pull/5063/files?diff=split&w=1
> Crypto - Nits

- WalletWasabi.Tests/UnitTests/Crypto/GroupElements/GeneralTests.cs
- WalletWasabi/Helpers/ByteHelpers.cs
https://github.com/zkSNACKs/WalletWasabi/pull/5034#discussion_r558826590
Similar to #5062
> ByteHelpers: ToHex(): Do not retun null

- WalletWasabi.Fluent.Desktop/packages.lock.json
- WalletWasabi.Fluent/packages.lock.json
- WalletWasabi.Gui/packages.lock.json
- WalletWasabi.Packager/packages.lock.json
- WalletWasabi/packages.lock.json
- azure-pipelines-linux.yml
- azure-pipelines-osx.yml
- azure-pipelines-windows.yml
See https://developercommunity.visualstudio.com/content/problem/1236629/dotnetcorecli-restore-task-locked-mode.html
Inspired by https://github.com/zkSNACKs/WalletWasabi/pull/5061.
> CI: "--locked-mode" is ignored. Fix it.

- WalletWasabi.Documentation/WasabikaCodex.md
https://github.com/zkSNACKs/WalletWasabi/pull/5046#issuecomment-765526878
I took the content of #5046 and added it to the [WasabikaCodex](https://github.com/zkSNACKs/WalletWasabi/blob/master/WalletWasabi.Documentation/WasabikaCodex.md) document.
> Add productivity tips

- WalletWasabi/Blockchain/TransactionOutputs/SmartCoin.cs
Closes #5072.
Details here: https://github.com/zkSNACKs/WalletWasabi/issues/5072#issuecomment-766650574
> Fix SelectMostPrivateIndependentlyOfCluster flaky test

- WalletWasabi.Tests/UnitTests/WabiSabi/Backend/UtxoPrisonWardenTests.cs
- WalletWasabi/WabiSabi/Backend/Banning/Warden.cs
Testing this change: https://github.com/zkSNACKs/WalletWasabi/pull/5087
> Add LastKnownChange correct behavior test

- WalletWasabi.Tests/UnitTests/WabiSabi/Backend/UtxoPrisonTests.cs
This makes the test non-flaky for me. 
@nopara73 What do you think?
> Fix PrisonChangeTracking test.

- WalletWasabi.Tests/UnitTests/WabiSabi/Backend/UtxoPrisonWardenTests.cs
- WalletWasabi.Tests/UnitTests/Wabisabi/Backend/ConfigTests.cs
- WalletWasabi/Bases/PeriodicRunner.cs
Closes https://github.com/zkSNACKs/WalletWasabi/pull/5094
> Make tests exact

- WalletWasabi/Helpers/Guard.cs
Guard.cs is now free of warnings.
> [trivial] Guard: Fix nullability issues.

- WalletWasabi.Fluent/Controls/LineChart.cs
> [Fluent] [LineChart] Show drag cursor on pointer over event

- WalletWasabi.Fluent/Validation/IRegisterValidationMethod.cs
- WalletWasabi.Fluent/Validation/IValidations.cs
- WalletWasabi.Fluent/Validation/ValidationExtensions.cs
- WalletWasabi.Fluent/Validation/Validations.cs
- WalletWasabi.Fluent/ViewLocator.cs
- WalletWasabi.Fluent/ViewModels/AddWallet/AddWalletPageViewModel.cs
- WalletWasabi.Fluent/ViewModels/AddWallet/Create/RecoveryWordViewModel.cs
- WalletWasabi.Fluent/ViewModels/AddWallet/RecoverWalletViewModel.cs
- WalletWasabi.Fluent/ViewModels/Dialogs/AdvancedRecoveryOptionsViewModel.cs
- WalletWasabi.Fluent/ViewModels/Dialogs/EnterPasswordViewModel.cs
- WalletWasabi.Fluent/ViewModels/Settings/BitcoinTabSettingsViewModel.cs
- WalletWasabi.Fluent/ViewModels/Settings/NetworkSettingsTabViewModel.cs
- WalletWasabi.Fluent/ViewModels/ViewModelBase.cs
This PR copies the [Validation](https://github.com/zkSNACKs/WalletWasabi/tree/master/WalletWasabi.Gui/Validation) folder to the Fluent project.
https://github.com/zkSNACKs/WalletWasabi/pull/5058#issuecomment-770697515
> Move validation folder to Fluent project

- WalletWasabi.Gui/Controls/WalletExplorer/SendTabViewModel.cs
- WalletWasabi.Gui/Global.cs
- WalletWasabi.Tests/IntegrationTests/P2pTests.cs
- WalletWasabi.Tests/RegressionTests/BuildTests.cs
- WalletWasabi.Tests/RegressionTests/CoinJoinTests.cs
- WalletWasabi.Tests/RegressionTests/SendTests.cs
- WalletWasabi.Tests/RegressionTests/WalletTests.cs
- WalletWasabi/Blockchain/Mempool/MempoolService.cs
- WalletWasabi/Blockchain/TransactionBroadcasting/TransactionBroadcaster.cs
- WalletWasabi/CoinJoin/Client/Clients/CoinJoinClient.cs
- WalletWasabi/CoinJoin/Client/CoinJoinProcessor.cs
- WalletWasabi/Services/UpdateChecker.cs
- WalletWasabi/Services/WasabiSynchronizer.cs
- WalletWasabi/Wallets/P2pBlockProvider.cs
- WalletWasabi/Wallets/Wallet.cs
- WalletWasabi/WebClients/Wasabi/HttpClientFactory.cs
This PR makes it easier to understand the purpose of `HttpClientFactory`.
> [trivial] Rename: WasabiClientFactory ->HttpClientFactory

- WalletWasabi.Fluent/ViewModels/AddWallet/AddedWalletPageViewModel.cs
- WalletWasabi.Fluent/ViewModels/WalletManagerViewModel.cs
This fixes the issue when the newly created wallet acts like a logged-in wallet.
> [Fluent] Fix wallet navigation issue when wallet is created

- WalletWasabi.Fluent/Controls/TagsBox.axaml.cs
- WalletWasabi.Fluent/ViewModels/AddWallet/RecoverWalletViewModel.cs
- WalletWasabi.Fluent/Views/AddWallet/RecoverWalletView.axaml
> [Fluent] Tagsbox fixes round 3

- WalletWasabi.Fluent/ViewModels/Wallets/Send/SendViewModel.cs
closes https://github.com/zkSNACKs/WalletWasabi/issues/5190
> [Fluent] Implement Send Navigation Logic

- WalletWasabi/Legal/Assets/LegalDocuments.txt
Related: https://github.com/zkSNACKs/WalletWasabi/issues/5177
> Update Legal docs support

- WalletWasabi.Fluent/Controls/TagsBox.axaml
> [Fluent] TagsBox fixes part 4

- WalletWasabi.Tests/UnitTests/BitcoinCore/BitcoindBinaryHashesTests.cs
- WalletWasabi.Tests/UnitTests/BitcoinCore/P2pBasedTests.cs
- WalletWasabi.Tests/UnitTests/BitcoinCore/RpcBasedTests.cs
- WalletWasabi.Tests/UnitTests/MockRpcClient.cs
- WalletWasabi.Tests/XunitConfiguration/RegTestFixture.cs
- WalletWasabi/BitcoinCore/IRPCClient.cs
- WalletWasabi/BitcoinCore/RpcClientBase.cs
- WalletWasabi/Helpers/Constants.cs
- WalletWasabi/Microservices/MicroserviceHelpers.cs
Related: https://github.com/zkSNACKs/WalletWasabi/pull/5112
> [Backport v1.1.12.4] Update Knots 

- WalletWasabi.Fluent/Controls/CurrencyEntryBox.axaml
- WalletWasabi.Fluent/Controls/CurrencyEntryBox.axaml.cs
- WalletWasabi.Fluent/Controls/TagsBox.axaml.cs
cc @danwalmsley @MaxHillebrand
> [Fluent] Currency Box Fixes part 2

- WalletWasabi.Fluent/Controls/CurrencyEntryBox.axaml.cs
> [Fluent] Currency Box part 3

- WalletWasabi.Gui/Dialogs/CannotCloseDialogViewModel.cs
- WalletWasabi.Packager/MacSignTools.cs
- WalletWasabi.Tests/UnitTests/Crypto/StrobeTests.cs
It is easier to review with whitespace change hidden: https://github.com/zkSNACKs/WalletWasabi/pull/5208/files?diff=unified&w=1
> Fix codefactor issues

- WalletWasabi.Gui/Tabs/WalletManager/RecoverWallets/RecoverWalletViewModel.cs
- WalletWasabi/Crypto/SchnorrBlindingSignature.cs
This just orders elements, to fix some CodeFactor issues.
> [CodeFactor] Order Elements

- WalletWasabi.Fluent/ViewModels/Login/LoginViewModel.cs
- WalletWasabi.Tests/RegressionTests/CoinJoinTests.cs
- WalletWasabi/CoinJoin/Client/Clients/CoinJoinClient.cs
- WalletWasabi/Wallets/Kitchen.cs
- WalletWasabi/Wallets/Wallet.cs
This is about to have Kitchen in the Wallet, see we will be able to have the SaltSoup there. I did not bother myself to refactor CoinJoinClient as it will be removed anyway by WabiSabi - so I just passed the Kitchen to it.
> Adding Gordon Ramsey's Kitchen to wallet

- WalletWasabi.Tests/RegressionTests/CoinJoinTests.cs
TorHttpClient no longer handles localhost HTTP requests. This PR fixes that.
> Fix CcjTestsAsync test.

- WalletWasabi.Fluent/Controls/LineChart.Properties.cs
- WalletWasabi.Fluent/Controls/LineChart.cs
- WalletWasabi.Fluent/ViewModels/LineChartDemo/SendLineChartViewModel.cs
- WalletWasabi.Fluent/ViewModels/LineChartDemo/XYLineChartViewModel.cs
- WalletWasabi.Fluent/Views/LineChartDemo/SendLineChartView.axaml
- WalletWasabi.Fluent/Views/LineChartDemo/SendLineChartView.axaml.cs
- WalletWasabi.Fluent/Views/LineChartDemo/XYLineChartView.axaml
- WalletWasabi.Fluent/Views/LineChartDemo/XYLineChartView.axaml.cs
- WalletWasabi.Fluent/Views/Wallets/Send/SendView.axaml
> [Fluent] [LineChart] Update

- WalletWasabi.Fluent/MathNet/CubicSpline.cs
- WalletWasabi.Fluent/MathNet/Precision.Equality.cs
- WalletWasabi.Fluent/MathNet/Precision.cs
- WalletWasabi.Fluent/MathNet/SplineBoundaryCondition.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Send/SendViewModel.cs
From the conducted interpolation test the CubicSpline (Pchip) seems to provide the best results.
x | y
-- | --
2 | 123
6 | 117
18 | 107
36 | 92
72 | 33
144 | 32
432 | 8
1008 | 7
> [Fluent] Spline interpolation update

- WalletWasabi/Wallets/Kitchen.cs
- WalletWasabi/Wallets/Wallet.cs
Partially put back this https://github.com/zkSNACKs/WalletWasabi/pull/5219/commits/06ac07ede59ce2292b5c6fe5ffef931f87607571.
> Clean up after cooking

- WalletWasabi.Fluent/ViewModels/AddWallet/AddWalletPageViewModel.cs
- WalletWasabi.Fluent/ViewModels/AddWallet/HardwareWallet/ConnectHardwareWalletViewModel.cs
- WalletWasabi.Fluent/ViewModels/AddWallet/HardwareWallet/DetectedHardwareWalletViewModel.cs
- WalletWasabi.Fluent/ViewModels/Login/PasswordFinder/SearchPasswordViewModel.cs
- WalletWasabi.Fluent/ViewModels/Navigation/RoutableViewModel.cs
- WalletWasabi.Fluent/ViewModels/Settings/SettingsPageViewModel.cs
- WalletWasabi.Fluent/ViewModels/TriggerCommandViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Receive/ReceiveAddressesViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Receive/ReceiveViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Send/SendViewModel.cs
https://github.com/zkSNACKs/WalletWasabi/pull/5161#discussion_r578451373
> [Fluent][Trivial] Rename inStack to isInHistory

- WalletWasabi.Fluent/ViewModels/MainViewModel.cs
- WalletWasabi.Gui/Global.cs
- WalletWasabi.Tests/RegressionTests/BuildTests.cs
- WalletWasabi.Tests/RegressionTests/SendTests.cs
- WalletWasabi/Blockchain/TransactionBroadcasting/TransactionBroadcaster.cs
To be able to pass the reference, this PR separates the initialization of the tx broadcaster.
> Create tx broadcaster in global ctor

- WalletWasabi.Fluent/ViewModels/AddWallet/RecoverWalletViewModel.cs
- WalletWasabi.Fluent/ViewModels/AddWallet/TermsAndConditionsViewModel.cs
- WalletWasabi.Fluent/ViewModels/Dialogs/AboutAdvancedInfoViewModel.cs
- WalletWasabi.Fluent/ViewModels/Dialogs/AdvancedRecoveryOptionsViewModel.cs
- WalletWasabi.Fluent/ViewModels/Dialogs/Base/DialogResult.cs
- WalletWasabi.Fluent/ViewModels/Dialogs/Base/DialogResultKind.cs
- WalletWasabi.Fluent/ViewModels/Dialogs/Base/DialogScreenViewModel.cs
- WalletWasabi.Fluent/ViewModels/Dialogs/Base/DialogViewModelBase.cs
- WalletWasabi.Fluent/ViewModels/Dialogs/Base/DialogViewModelBaseOfTResult.cs
- WalletWasabi.Fluent/ViewModels/Dialogs/Base/IDialogHost.cs
- WalletWasabi.Fluent/ViewModels/Dialogs/ConfirmHideAddressViewModel.cs
- WalletWasabi.Fluent/ViewModels/Dialogs/CreatePasswordDialogViewModel.cs
- WalletWasabi.Fluent/ViewModels/Dialogs/EnterPasswordDialogViewModel.cs
- WalletWasabi.Fluent/ViewModels/Dialogs/ShowErrorDialogViewModel.cs
- WalletWasabi.Fluent/ViewModels/Login/PasswordFinder/PasswordFinderIntroduceViewModel.cs
- WalletWasabi.Fluent/ViewModels/MainViewModel.cs
- WalletWasabi.Fluent/ViewModels/Navigation/NavigationState.cs
- WalletWasabi.Fluent/ViewModels/Navigation/RoutableViewModel.cs
- WalletWasabi.Fluent/ViewModels/Navigation/TargettedNavigationStack.cs
- WalletWasabi.Fluent/ViewModels/TransactionBroadcasting/LoadTransactionViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionPreviewViewModel.cs
The `Dialogs` folder is starting to be a mess. This PR puts the base files into the `Base` subfolder to make it much cleaner.
> [Fluent] Organize 'ViewModels\Dialogs' folder 

- WalletWasabi.Fluent/Controls/CurrencyEntryBox.axaml
- WalletWasabi.Fluent/Controls/CurrencyEntryBox.axaml.cs
> [Fluent] Disable CurrencyEntryBox's conversion when exchange rate is empty.

- WalletWasabi.Gui/Global.cs
- WalletWasabi/Tor/Http/TorHttpClient.cs
- WalletWasabi/Tor/TorMonitor.cs
Use HttpClientFactory to obtain TorHttpClient.
> TorMonitor: Use HttpClientFactory.

- .gitattributes
- WalletWasabi/Microservices/Binaries/osx64/Tor/tor
> Fix line endings in Tor sh file

- WalletWasabi.Gui/Global.cs
- WalletWasabi.Tests/UnitTests/AllFeeEstimateTests.cs
This PR addresses https://github.com/zkSNACKs/WalletWasabi/pull/5236#discussion_r585663796.
> [easy] Add HttpClientFactory to Global.

- WalletWasabi.Fluent/Validation/Validations.cs
- WalletWasabi.Fluent/ViewModels/ViewModelBase.cs
- WalletWasabi.Fluent/Views/Wallets/Send/SendView.axaml
Validations were broken when I implemented Clear method.
> Fix validations, fix warnings

- WalletWasabi.Gui/Controls/WalletExplorer/SendTabViewModel.cs
- WalletWasabi.Gui/Global.cs
- WalletWasabi.Tests/IntegrationTests/P2pTests.cs
- WalletWasabi.Tests/RegressionTests/BuildTests.cs
- WalletWasabi.Tests/RegressionTests/CoinJoinTests.cs
- WalletWasabi.Tests/RegressionTests/SendTests.cs
- WalletWasabi.Tests/RegressionTests/WalletTests.cs
- WalletWasabi/Blockchain/TransactionBroadcasting/TransactionBroadcaster.cs
- WalletWasabi/Wallets/P2pBlockProvider.cs
This PR addresses https://github.com/zkSNACKs/WalletWasabi/pull/5305#issuecomment-789779107
`CoinJoinMultipleRoundTestsAsync` test doesn't pass on this PR and on master.
> Use Global.HttpClientFactory instead of Synchronizer.HttpClientFactory

- WalletWasabi.Tests/UnitTests/Crypto/Slip21NodeTests.cs
- WalletWasabi/Crypto/Slip21Node.cs
Implements https://github.com/satoshilabs/slips/blob/master/slip-0021.md just in case we decide to use it in the client, even when the client maintains state.
> SLIP-0021 Implementation

- WalletWasabi.Fluent/Controls/Dialog.axaml
- WalletWasabi.Fluent/ViewModels/Dialogs/Authorization/HardwareWalletAuthDialogViewModel.cs
- WalletWasabi.Fluent/ViewModels/Dialogs/Base/DialogScreenViewModel.cs
- WalletWasabi.Fluent/ViewModels/MainViewModel.cs
- WalletWasabi.Fluent/Views/Dialogs/Authorization/HardwareWalletAuthDialogView.axaml
- WalletWasabi.Fluent/Views/MainView.axaml
> [Fluent] Show HW wallet auth dialog in CompactDialogScreen

- WalletWasabi.Fluent/Views/Dialogs/Authorization/PasswordAuthDialogView.axaml
cc @danwalmsley @soosr @wieslawsoltes
> [Fluent] Make PasswordAuthDialogView's size fixed

- WalletWasabi.Fluent/Views/Wallets/Send/OptimisePrivacyView.axaml
- WalletWasabi.Fluent/Views/Wallets/Send/PrivacyControlView.axaml
- WalletWasabi.Fluent/Views/Wallets/Send/TransactionPreviewView.axaml
> Send Page Titles

- WalletWasabi.Backend/Controllers/BlockchainController.cs
Got rid of Possible nullable warnings in BlockchainController, hopefully i didn't break anything.
Part of #4241
> Eliminated warnings in BlockchainController

- WalletWasabi.Tests/UnitTests/Hwi/DefaultResponseTests.cs
- WalletWasabi/Hwi/HwiClient.cs
- WalletWasabi/Hwi/Parsers/HwiParser.cs
Closes https://github.com/zkSNACKs/WalletWasabi/pull/5350
> Fix nullability warnings in HwiClient

- WalletWasabi.Fluent/Styles/DataGrid.axaml
- WalletWasabi.Fluent/Styles/Themes/Base.axaml
- WalletWasabi.Fluent/Views/Wallets/Send/PrivacyControlView.axaml
This PR hides the row selection effect in the Privacy Control view.
> [Fluent] DataGrid hide row selection

- WalletWasabi.Fluent/ViewModels/AddWallet/RecoverWalletViewModel.cs
- WalletWasabi.Fluent/ViewModels/HelpAndSupport/AboutViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Receive/ReceiveViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Send/SendViewModel.cs
- WalletWasabi.Fluent/Views/Dialogs/AdvancedRecoveryOptionsView.axaml
- WalletWasabi.Fluent/Views/Wallets/Send/OptimisePrivacyView.axaml
- WalletWasabi.Fluent/Views/Wallets/Send/PrivacyControlView.axaml
- WalletWasabi.Fluent/Views/Wallets/Send/SendView.axaml
- WalletWasabi.Fluent/Views/Wallets/Send/TransactionPreviewView.axaml
Important concept here for transitive processes, dialogs provide the following benefits:
Context, the user knows they are still in the same process, even multi steps.
helps with layout...
user sees non transitive screens behind.
locating where you are in the software.
> Transitive Dialogs for Send / Rx

- WalletWasabi.Fluent/ViewModels/Wallets/Send/OptimisePrivacyViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Send/PrivacyControlViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Send/SendViewModel.cs
- WalletWasabi.Fluent/Views/Wallets/Send/OptimisePrivacyView.axaml
- WalletWasabi.Fluent/Views/Wallets/Send/PrivacyControlView.axaml
- WalletWasabi.Fluent/Views/Wallets/Send/SendView.axaml
This PR eliminates the UI freezes during Send procedure.
> [Fluent] Smooth Send

- WalletWasabi.Tests/UnitTests/Wabisabi/Backend/CoordinatorTests.cs
Fix #https://github.com/zkSNACKs/WalletWasabi/issues/5365
> Fix NRE in CoordinatorTests

- WalletWasabi.Fluent/ViewModels/HelpAndSupport/AboutViewModel.cs
- WalletWasabi.Gui/Shell/Commands/HelpCommands.cs
- WalletWasabi.Gui/Tabs/AboutViewModel.cs
- WalletWasabi.WindowsInstaller/Product.wxs
Related https://github.com/zkSNACKs/WalletWasabi/issues/5177
> Change support links

- WalletWasabi/WabiSabi/Backend/Banning/Inmate.cs
- WalletWasabi/WabiSabi/Backend/Models/Bob.cs
- WalletWasabi/WabiSabi/Backend/Rounds/Round.cs
- WalletWasabi/WabiSabi/Backend/WabiSabiConfig.cs
- WalletWasabi/WabiSabi/Models/ConnectionConfirmationRequest.cs
- WalletWasabi/WabiSabi/Models/ConnectionConfirmationResponse.cs
- WalletWasabi/WabiSabi/Models/InputRoundSignaturePair.cs
- WalletWasabi/WabiSabi/Models/InputWitnessPair.cs
- WalletWasabi/WabiSabi/Models/InputsRegistrationRequest.cs
- WalletWasabi/WabiSabi/Models/InputsRegistrationResponse.cs
- WalletWasabi/WabiSabi/Models/InputsRemovalRequest.cs
- WalletWasabi/WabiSabi/Models/OutputRegistrationRequest.cs
- WalletWasabi/WabiSabi/Models/OutputRegistrationResponse.cs
- WalletWasabi/WabiSabi/Models/TransactionSignaturesRequest.cs
It contains small changes for WabiSabi code. The most important one is the change of already readonly classes to records because they are less verbose, implement `GetHashCode` and comparison operators (and Equals too) automatically for free and also guarantee immutability.
> WabiSabi refactoring I

- WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
Introduced by https://github.com/zkSNACKs/WalletWasabi/pull/5325
> Remove super noisy logs

- WalletWasabi.Fluent/Views/Wallets/Send/SendView.axaml
Note: Did not indent properly view for better clarity, after it's ready this will be reformatted.
> [Fluent] Send view layout optimization

- WalletWasabi.Backend/wwwroot/index.html
https://github.com/zkSNACKs/WalletWasabi/pull/5414 missed to update this line.
> Bump version to v1.1.12.6

- WalletWasabi.Fluent/Styles/Themes/BaseDark.axaml
- WalletWasabi.Fluent/Styles/Themes/BaseLight.axaml
- WalletWasabi.Fluent/Views/Wallets/Send/OptimisePrivacyView.axaml
- WalletWasabi.Fluent/Views/Wallets/Send/PrivacySuggestionControl.axaml
Fixes the separator color in the `PrivacySuggestionControl`
Fixes the selection color of the `PrivacySuggestionControl`
> [Fluent] More light theme fixes

- WalletWasabi.Fluent/Controls/NavBarListBox.cs
- WalletWasabi.Fluent/ViewModels/NavBar/NavBarViewModel.cs
This fixes the following navigation scenario:
- Open Send/Receive
- Cose the dialog
- Unable the open again Send/Receive
https://user-images.githubusercontent.com/2297442/111365068-52f3f900-8692-11eb-8f68-76a8ab128363.mp4
> [Fluent] Reselect already selected NavBarListBox item

- WalletWasabi/Stores/BitcoinStore.cs
- WalletWasabi/Wallets/Wallet.cs
Fixes #5431 by removing extra initialization check.
> Wallet: Remove extra initialization check.

- WalletWasabi/Wallets/P2pBlockProvider.cs
Closes #2677
A solution to show block height in logs.
> Show BLockHeight in logs

- WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterOutputTests.cs
- WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
- WalletWasabi/WabiSabi/Backend/Rounds/Round.cs
- WalletWasabi/WabiSabi/Models/OutputRegistrationResponse.cs
As per the last call, we will revisit this when we get to the transport layer concerns.
> [WabiSabi] Trivial: Remove EncryptedCoinJoin round property for now

- WalletWasabi.Fluent/App.axaml
- WalletWasabi.Fluent/Controls/PreviewItem.axaml
- WalletWasabi.Fluent/Controls/PreviewItem.axaml.cs
- WalletWasabi.Fluent/ViewModels/Dialogs/InsufficientBalanceDialogViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionPreviewViewModel.cs
- WalletWasabi.Fluent/Views/Dialogs/InsufficientBalanceDialogView.axaml
- WalletWasabi.Fluent/Views/Wallets/Send/TransactionPreviewView.axaml
> [Fluent] Preview item control

- WalletWasabi.Tests/UnitTests/Hwi/HwiProcessBridgeMock.cs
Even though replacing this class with Moq PR got closed, the refactor part is still valid.
Replaced redundant ifs with switch expression.
Hwi tests are passing as before.
IMO this is more readable and easier to change if change is needed.
> HwiProcesssBridgeMock refactor

- WalletWasabi.Fluent/Views/Login/PasswordFinder/PasswordFinderIntroduceView.axaml
> [Fluent] PW finder intro text font size adjusment

- WalletWasabi.Fluent/ViewModels/Wallets/Send/SendSuccessViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionPreviewViewModel.cs
- WalletWasabi.Fluent/Views/Wallets/Send/SendSuccessView.axaml
- WalletWasabi.Fluent/Views/Wallets/Send/SendSuccessView.axaml.cs
> [Fluent] Send success page

- WalletWasabi.Tests/UnitTests/WabiSabi/Client/ArenaClientTests.cs
- WalletWasabi/WabiSabi/Client/ArenaClient.cs
Recreation of this: https://github.com/zkSNACKs/WalletWasabi/pull/5446
I am only checking what is strictly required to make the request, nothing more. Outputs, amounts, fees should be checked before this call.
> [WabiSabi] Add SignTransactionAsync

- WalletWasabi.Fluent/ViewModels/Dialogs/Authorization/PasswordAuthDialogViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionPreviewViewModel.cs
> [Fluent] Don't authorize when there is no password

- WalletWasabi.Fluent/Controls/PreviewItem.axaml
> change preview item emphasis

- WalletWasabi.Fluent/ViewModels/Wallets/Send/SendViewModel.cs
- WalletWasabi.Fluent/Views/Wallets/Send/SendView.axaml
> [Fluent] Send view fee chart updates

- WalletWasabi.Fluent/ViewModels/Wallets/Send/SendViewModel.cs
cc @molnard @danwalmsley 
fixes no. 11 in todo-list (TagsBox not finding labels for some reason.)
> [Fluent] Fix SendViewModel.cs label sources

- WalletWasabi.Fluent/Styles/Themes/Base.axaml
- WalletWasabi.Fluent/ViewModels/Wallets/Send/PrivacyControlViewModel.cs
- WalletWasabi.Fluent/Views/Wallets/Send/PrivacyControlView.axaml
- Fix typo Know -> Known
- Only show a single warning at a time.
> Fluent: SendUX - Tidy and fix Privacy Control

- WalletWasabi.Fluent/Behaviors/ExecuteCommandOnClickBehavior.cs
- WalletWasabi.Fluent/ViewModels/WalletManagerViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Send/SendViewModel.cs
- WalletWasabi.Fluent/Views/Wallets/Send/SendView.axaml
If the user clicks on the TextBox the address gets pasted.
Paste it on click only if:
- Auto Copy/Paste is enabled
- TextBox is empty
- A valid address is in the clipboard
> [Fluent] Send auto paste

- WalletWasabi.Tests/UnitTests/WabiSabi/Backend/ConfigTests.cs
> [WabiSabi] Fix NRE in WabiSabi ConfigTests

- WalletWasabi.Tests/Helpers/WabiSabiFactory.cs
- WalletWasabi/WabiSabi/Client/ArenaClient.cs
- WalletWasabi/WabiSabi/Crypto/CredentialRequesting/CredentialsResponseValidation.cs
- WalletWasabi/WabiSabi/Crypto/CredentialRequesting/RealCredentialsRequestData.cs
- WalletWasabi/WabiSabi/Crypto/CredentialRequesting/ZeroCredentialsRequestData.cs
- WalletWasabi/WabiSabi/Crypto/WabiSabiClient.cs
Use a named type in `CredentialClient` to return as part of `CreateRequestForZeroAmount` and `CreateRequest`.
> [WabiSabi] `CredentialClient` methods return record type

- WalletWasabi.Fluent/ViewModels/AddWallet/RecoverWalletViewModel.cs
- WalletWasabi.Fluent/Views/AddWallet/RecoverWalletView.axaml
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/5541
cc @danwalmsley @lontivero
> [Fluent] Add multiple recovery words limit from Gui project

- WalletWasabi.Tests/UnitTests/CoordinatorRoundTests.cs
They were failing because of inner logic change.
> Fix XxAsync and SsAsync tests

- WalletWasabi.Tests/UnitTests/CoordinatorRoundTests.cs
> Use better names for UTs

- WalletWasabi/WabiSabi/Client/AliceClient.cs
https://github.com/zkSNACKs/WalletWasabi/pull/5544#discussion_r610647830
> [WabiSabi] Fix inputRemainingWeights in AliceClient

- WalletWasabi.Backend/Global.cs
- WalletWasabi.Gui/Global.cs
- WalletWasabi.Gui/ViewModels/StatusBarViewModel.cs
- WalletWasabi.Tests/RegressionTests/BackendTests.cs
- WalletWasabi.Tests/RegressionTests/CoinJoinTests.cs
- WalletWasabi.Tests/UnitTests/BitcoinCore/P2pBasedTests.cs
- WalletWasabi/BitcoinCore/CoreNode.cs
- WalletWasabi/Services/HostedServices.cs
This is a breakdown of https://github.com/zkSNACKs/WalletWasabi/pull/5591 into small parts.
In this PR I disallow registering the same service twice to the `HostedServices` and allow getting services before they are started. With this, a bug came out where we had multiple `UpdateChecker`s, this PR fixes it.
> Improve HostedServices

- WalletWasabi.Backend/Global.cs
- WalletWasabi.Gui/Global.cs
- WalletWasabi.Tests/Helpers/TestNodeBuilder.cs
- WalletWasabi.Tests/UnitTests/BitcoinCore/NodeBuildingTests.cs
- WalletWasabi.Tests/UnitTests/BitcoinCore/P2pBasedTests.cs
- WalletWasabi.Tests/UnitTests/BitcoinCore/RpcBasedTests.cs
- WalletWasabi.Tests/XunitConfiguration/RegTestFixture.cs
- WalletWasabi/BitcoinCore/CoreNode.cs
- WalletWasabi/BitcoinCore/CoreNodeParams.cs
> Take out hosted services registration from core node

- WalletWasabi.Tests/Helpers/WabiSabiFactory.cs
- WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepTransactionSigningTests.cs
- WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/ConfirmConnectionTests.cs
- WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterInputFailureTests.cs
- WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RemoveInputTests.cs
- WalletWasabi.Tests/UnitTests/WabiSabi/Client/ArenaClientTests.cs
- WalletWasabi/WabiSabi/Backend/Models/WabiSabiProtocolErrorCode.cs
- WalletWasabi/WabiSabi/Backend/PostRequests/InputRegistrationHandler.cs
- WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
- WalletWasabi/WabiSabi/Client/ArenaClient.cs
there were a few missing renamings needed to close https://github.com/zkSNACKs/WalletWasabi/issues/5570
> [WabiSabi] Missing weight renaming

- WalletWasabi.Backend/Controllers/ChaumianCoinJoinController.cs
- WalletWasabi.Gui/Controls/WalletExplorer/CoinViewModel.cs
- WalletWasabi.Gui/Controls/WalletExplorer/SendControlViewModel.cs
- WalletWasabi/Blockchain/TransactionBuilding/PaymentIntent.cs
- WalletWasabi/CoinJoin/Client/Clients/CoinJoinClient.cs
- WalletWasabi/CoinJoin/Coordinator/Rounds/CoordinatorRound.cs
- WalletWasabi/Gma/QrCodeNet/Encoding/Masking/PatternFactory.cs
- WalletWasabi/Services/SingleInstanceChecker.cs
https://twitter.com/nopara73/status/1382653858556612611 :)
> Adjust impossible exception messages

- WalletWasabi/CoinJoin/Coordinator/Rounds/CoordinatorRound.cs
> [Trivial] Modify impossibru log message

- WalletWasabi/WabiSabi/Client/AliceClient.cs
I had something bigger in mind but I need BobClient first so, this is just a tiny fix.
> [WabiSabi] Minor refactorings ii

- WalletWasabi.Gui/Global.cs
- WalletWasabi.Tests/IntegrationTests/LiveServerTests.cs
- WalletWasabi.Tests/IntegrationTests/TorTests.cs
- WalletWasabi/Tor/TorMonitor.cs
- WalletWasabi/Tor/TorProcessManager.cs
- WalletWasabi/Tor/TorSettings.cs
- Remove unused param
- Remove useless comments
Better diff: https://github.com/zkSNACKs/WalletWasabi/pull/5649/files?w=1
> Nitpick on Tor stuff

- WalletWasabi/Tor/TorProcessManager.cs
I left the other side of this PR here: https://github.com/zkSNACKs/WalletWasabi/pull/5649/files?w=1#diff-4266962092b2860ce0d2a3b93231d9cc64ae4c833720b76b1659e26409d9ddd7
> Remove EnsureContainingDirectoryExists because it's the responsibility of someone else.

- WalletWasabi.Backend/WalletWasabi.Backend.csproj
- WalletWasabi.Fluent.Desktop/packages.lock.json
- WalletWasabi.Fluent/packages.lock.json
- WalletWasabi.Gui/packages.lock.json
- WalletWasabi.Packager/packages.lock.json
- WalletWasabi.Tests/WalletWasabi.Tests.csproj
- WalletWasabi/WalletWasabi.csproj
- WalletWasabi/packages.lock.json
Updated NuGet packages except in UI projects
> Update NuGet packages

- WalletWasabi.Documentation/WasabikaCodex.md
Previously:
```sh
git del branch1
git del branch2
```
Now:
```sh
git del branch1 branch2
```
> Make deleting multiple branches at once possible

- WalletWasabi.Fluent/Controls/CurrencyEntryBox.axaml.cs
- WalletWasabi.Fluent/Controls/LineChart.cs
- WalletWasabi.Fluent/Controls/ProgressRingArc.axaml.cs
- WalletWasabi.Fluent/Controls/ResponsivePanel.cs
- WalletWasabi.Fluent/Controls/RingChartControl.cs
- WalletWasabi.Fluent/Controls/TagsBox.axaml.cs
- WalletWasabi.Fluent/Converters/WalletIconConverter.cs
- WalletWasabi.Fluent/MathNet/CubicSpline.cs
- WalletWasabi.Fluent/ViewModels/AddWallet/AddWalletPageViewModel.cs
- WalletWasabi.Fluent/ViewModels/AddWallet/RecoverWalletViewModel.cs
- WalletWasabi.Fluent/ViewModels/Dialogs/CreatePasswordDialogViewModel.cs
- WalletWasabi.Fluent/ViewModels/Login/PasswordFinder/SearchPasswordViewModel.cs
- WalletWasabi.Fluent/ViewModels/Login/PasswordFinder/SelectCharsetViewModel.cs
- WalletWasabi.Fluent/ViewModels/Navigation/NavigationManager.cs
- WalletWasabi.Fluent/ViewModels/Search/SearchPageViewModel.cs
- WalletWasabi.Fluent/ViewModels/Settings/GeneralSettingsTabViewModel.cs
- WalletWasabi.Fluent/ViewModels/Settings/SettingsTabViewModelBase.cs
- WalletWasabi.Fluent/ViewModels/TransactionBroadcasting/LoadTransactionViewModel.cs
- WalletWasabi.Fluent/ViewModels/WalletManagerViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/ClosedWalletViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItemViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Home/History/TransactionDetailsViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/WalletBalanceChartTileViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Send/OptimisePrivacyViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModelBase.cs
Better diff: https://github.com/zkSNACKs/WalletWasabi/pull/5664/files?diff=unified&w=1
> [Fluent] Fix formatting

- WalletWasabi.Fluent/Controls/NavBarItem.axaml
- WalletWasabi.Fluent/Controls/NavBarItem.axaml.cs
- WalletWasabi.Fluent/Views/NavBar/NavBar.axaml
Added `:horizontal` and `:vertical` pseudo-classes for `NavBarItem` and reorganized `NavBar` xaml file styles related to `NavBarItem`.
> [Fluent] NavBarItem control updates

- WalletWasabi.Tests/Helpers/WabiSabiFactory.cs
- WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepOutputRegistrationTests.cs
- WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepTransactionSigningTests.cs
- WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterInputFailureTests.cs
- WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterInputSuccessTests.cs
- WalletWasabi.Tests/UnitTests/WabiSabi/Client/ArenaClientTests.cs
- WalletWasabi.Tests/UnitTests/WabiSabi/Models/SerializationTests.cs
- WalletWasabi/Crypto/OwnershipProof.cs
- WalletWasabi/JsonConverters/OwnershipProofJsonConverter.cs
- WalletWasabi/JsonConverters/WitScriptJsonConverter.cs
- WalletWasabi/WabiSabi/Backend/Models/Alice.cs
- WalletWasabi/WabiSabi/Backend/Models/WabiSabiProtocolErrorCode.cs
- WalletWasabi/WabiSabi/Backend/PostRequests/ArenaRequestHandler.cs
- WalletWasabi/WabiSabi/Backend/PostRequests/InputRegistrationHandler.cs
- WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
- WalletWasabi/WabiSabi/Client/ArenaClient.cs
- WalletWasabi/WabiSabi/Client/HttpRequestHandlerProxy.cs
- WalletWasabi/WabiSabi/Crypto/CredentialRequesting/CredentialsRequest.cs
- WalletWasabi/WabiSabi/Models/InputRegistrationRequest.cs
Implements the high-level protocol messages' serialization and a tiny http client (no server-side part, except some credential request model validations).
> [WabiSabi] Arena HttpClient skeleton

- WalletWasabi.Fluent/ViewModels/MainViewModel.cs
- WalletWasabi.Fluent/Views/MainWindow.axaml
- WalletWasabi.Gui/Converters/WindowStateAfterStartJsonConverter.cs
- WalletWasabi.Gui/MainWindow.xaml.cs
- WalletWasabi.Gui/UiConfig.cs
- WalletWasabi.Gui/ViewModels/MainWindowViewModel.cs
This PR:
- makes the UiConfig compatible with the Fluent
- if the value in UiConfig is corrupted or `Minimized` then the software will start on `Maximized`
> [Fluent] Fluent remember window state

- WalletWasabi.Fluent/Controls/TagsBox.axaml
- WalletWasabi.Fluent/Controls/TagsBox.axaml.cs
- WalletWasabi.Fluent/Views/Wallets/Send/SendView.axaml
> SendUX: add a watermark to labels to make it really obvious.

- WalletWasabi.Gui/Global.cs
- WalletWasabi.Tests/Helpers/Common.cs
- WalletWasabi.Tests/UnitTests/Tor/TorSettingsTests.cs
- WalletWasabi/Tor/TorProcessManager.cs
- WalletWasabi/Tor/TorSettings.cs
This PR is only refactoring and the idea is to have all Tor related settings in `TorSettings` class.
Somewhat related to #5681.
> Add `terminateOnExit` to `TorSettings`

- README.md
https://github.com/zkSNACKs/WalletWasabi/pull/5732#discussion_r625184883
> Make Telementry disabling obvious

- WalletWasabi/WabiSabi/Backend/Models/Bob.cs
- Removed unused imports
- Fixed XML documentation warning
> Minor cleanup in Bob

- WalletWasabi.Fluent/Controls/AnimatedButton.axaml.cs
- WalletWasabi.Fluent/ViewModels/WalletManagerViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Receive/AddressViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Receive/ReceiveAddressViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Receive/ReceiveAddressesViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Receive/ReceiveViewModel.cs
- WalletWasabi.Fluent/Views/Wallets/Receive/ReceiveAddressView.axaml
Copy the address automatically after creation/opening when the option is enabled in Settings.
> [Fluent] Receive autocopy

- WalletWasabi.Backend/Controllers/WabiSabiController.cs
> Fix backend

- WalletWasabi.Backend/Controllers/WabiSabiController.cs
- WalletWasabi.Backend/Startup.cs
- Backend is not running on the current master. 
```
fail: Microsoft.AspNetCore.Server.Kestrel[13]
Connection id "0HM8JJ2FND2OJ", Request id "0HM8JJ2FND2OJ:00000003": An unhandled exception was thrown by the application.
Swashbuckle.AspNetCore.SwaggerGen.SwaggerGeneratorException: Ambiguous HTTP method for action - WalletWasabi.Backend.Controllers.WabiSabiController.ConfirmConnectionAsync (WalletWasabi.Backend). Actions require an explicit HttpMethod binding for Swagger/OpenAPI 3.0
at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateOperations(IEnumerable`1 apiDescriptions, SchemaRepository schemaRepository)
at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GeneratePaths(IEnumerable`1 apiDescriptions, SchemaRepository schemaRepository)
at …
```
> Fix WabiSabiController

- WalletWasabi.Tests/UnitTests/Transactions/TransactionFactoryTests.cs
We didn't awaited anything in the test, so i wrote it back to synchronous.
> Fix warning in TransactionFactoryTests.cs

- WalletWasabi.Fluent.Desktop/packages.lock.json
- WalletWasabi.Fluent/packages.lock.json
- WalletWasabi.Gui/packages.lock.json
- WalletWasabi.Packager/packages.lock.json
- WalletWasabi/WalletWasabi.csproj
- WalletWasabi/packages.lock.json
This should solve the Tails issue: https://github.com/MetacoSA/NBitcoin/pull/1003
> Update NBitcoin (Tails Fix)

- WalletWasabi.Fluent/Behaviors/RegisterNotificationHostBehavior.cs
- WalletWasabi.Fluent/Converters/MoneyConverters.cs
- WalletWasabi.Fluent/Helpers/NotificationHelpers.cs
- WalletWasabi.Fluent/Helpers/TextHelpers.cs
- WalletWasabi.Fluent/Helpers/TransactionHelpers.cs
- WalletWasabi.Fluent/Styles/Themes/Base.axaml
- WalletWasabi.Fluent/Styles/Themes/BaseDark.axaml
- WalletWasabi.Fluent/Styles/Themes/BaseLight.axaml
- WalletWasabi.Fluent/ViewModels/WalletManagerViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModel.cs
- WalletWasabi.Fluent/Views/MainWindow.axaml
- Pop a notification if a transaction has received
- Pop a notification if a transaction has sent
- Clicking on the notification will navigate to the wallet home page, and highlight/select the transaction
> [Fluent] Notifications

- WalletWasabi.Fluent/Controls/ResponsivePanelState.cs
- WalletWasabi.Fluent/Controls/TagsBox.axaml.cs
- WalletWasabi.Fluent/Helpers/AdornerHelper.cs
- WalletWasabi.Fluent/Helpers/EnumerableExtensions.cs
- WalletWasabi.Fluent/Helpers/StraightLineFormula.cs
- WalletWasabi.Fluent/Helpers/TextHelpers.cs
- WalletWasabi.Fluent/ViewModels/MainViewModel.cs
- WalletWasabi.Fluent/ViewModels/WalletManagerViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItemViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/WalletBalanceChartTileViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/WalletPieChartTileViewModel.cs
Review with white space changes off https://github.com/zkSNACKs/WalletWasabi/pull/5792/files?diff=unified&w=1
> [Trivial] [Fluent] Fix formatting and use tabs instead of spaces

- WalletWasabi.Fluent.Desktop/packages.lock.json
- WalletWasabi.Fluent/packages.lock.json
- WalletWasabi.Gui/packages.lock.json
- WalletWasabi.Packager/packages.lock.json
- WalletWasabi/WalletWasabi.csproj
- WalletWasabi/packages.lock.json
This: https://github.com/MetacoSA/NBitcoin/pull/991
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/5512
> Update NBitcoin (Up-to-date Seeds)

- WalletWasabi.Fluent/ViewModels/AddWallet/AddWalletPageViewModel.cs
- WalletWasabi.Fluent/ViewModels/AddWallet/HardwareWallet/ConnectHardwareWalletViewModel.cs
- WalletWasabi.Fluent/ViewModels/MainViewModel.cs
- WalletWasabi.Fluent/ViewModels/NavBar/NavBarViewModel.cs
- WalletWasabi.Fluent/ViewModels/UiServices.cs
- WalletWasabi.Fluent/ViewModels/WalletManagerViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Receive/AddressViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Receive/ReceiveAddressViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Receive/ReceiveAddressesViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Receive/ReceiveViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Send/OptimisePrivacyViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Send/PrivacyControlViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Send/SendSuccessViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Send/SendViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionPreviewViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModel.cs
Begginings of organising, navigation, wallet management stuff.
> Fluent UiServices

- WalletWasabi.Fluent/Behaviors/AddClassAction.cs
- WalletWasabi.Fluent/Controls/AnimatedButton.axaml.cs
- WalletWasabi.Fluent/Controls/NonVirtualizingResponsiveLayout.cs
- WalletWasabi.Fluent/Controls/ResponsivePanel.cs
- WalletWasabi.Fluent/Controls/ResponsivePanelState.cs
- WalletWasabi.Fluent/Helpers/AuthorizationHelpers.cs
- WalletWasabi.Fluent/MathNet/CubicSpline.cs
- WalletWasabi.Fluent/MathNet/SplineBoundaryCondition.cs
- WalletWasabi.Fluent/Model/TransactionAuthorizationInfo.cs
- WalletWasabi.Fluent/Services.cs
- WalletWasabi.Fluent/ViewModels/Dialogs/Authorization/AuthorizationDialogBase.cs
- WalletWasabi.Fluent/ViewModels/Dialogs/Authorization/HardwareWalletAuthDialogViewModel.cs
- WalletWasabi.Fluent/ViewModels/Dialogs/ConfirmHideAddressViewModel.cs
- WalletWasabi.Fluent/ViewModels/Dialogs/InsufficientBalanceDialogViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Receive/AddressViewModel.cs
- WalletWasabi.Fluent/Views/ResponsivePanelDemo/ResponsiveLayoutDemoView.axaml.cs
- WalletWasabi.Fluent/Views/ResponsivePanelDemo/ResponsivePanelDemoView.axaml.cs
- WalletWasabi/Models/FriendlyNameAttribute.cs
> Fix line endings

- README.md
> Update YouTube url

- WalletWasabi.Fluent/Views/AddWallet/AddWalletPageView.axaml
It didn't work before due to an Avalonia bug, now it is fixed.
> [Trivial][Fluent] Set binding in style

- WalletWasabi.Tests/UnitTests/WabiSabi/Client/GreedyDecomposerTests.cs
- WalletWasabi/WabiSabi/Client/GreedyDecomposer.cs
This PR is a simplified stateless version of #5822 (greedy decomposer). It doesn't deal with fee rates nor costs because the costs depend on the scriptPubKey type (size) and both, the fee rate and script type, can vary from output to output.
> [WabiSabi] Add alternative stateless decomposer

- WalletWasabi.Tests/UnitTests/WabiSabi/Client/CoinJoinClientTests.cs
- WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiHttpApiIntegrationTests.cs
- WalletWasabi.Tests/UnitTests/WabiSabi/Models/RoundStatusUpdaterTests.cs
- WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
- WalletWasabi/WabiSabi/Client/RoundStateAwaiter.cs
- WalletWasabi/WabiSabi/Client/RoundStateUpdater.cs
- WalletWasabi/WabiSabi/Client/RoundStatusUpdater.cs
As title, don't review in detail just the concept.
> [WabiSabi] Add RoundStatusUpdater

- WalletWasabi.Fluent/ViewModels/WalletManagerViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryViewModel.cs
A simpler version of https://github.com/zkSNACKs/WalletWasabi/pull/5832
- Flash the row when new txn received
- If multiple received a time, flash all row and selected the latest one
https://user-images.githubusercontent.com/16364053/119666874-0cf7a600-be36-11eb-810a-00cc5803ddb5.mp4
https://user-images.githubusercontent.com/16364053/119666572-c7d37400-be35-11eb-9d9f-bf3c0ec6ae2c.mp4
> [Fluent] Transaction History - flash row on receive

- WalletWasabi.Tests/UnitTests/WabiSabi/Models/RoundStateUpdaterTests.cs
- WalletWasabi/WabiSabi/Client/RoundStateAwaiter.cs
- WalletWasabi/WabiSabi/Client/RoundStateUpdater.cs
Addressing https://github.com/zkSNACKs/WalletWasabi/pull/5852#discussion_r640692733
> [WabiSabi] Simplify RoundStateUpdater

- WalletWasabi.Tests/UnitTests/WabiSabi/Models/MultipartyTransactionTests.cs
- WalletWasabi/WabiSabi/Backend/Rounds/Round.cs
- WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
- WalletWasabi/WabiSabi/Models/MultipartyTransaction/ConstructionState.cs
- WalletWasabi/WabiSabi/Models/MultipartyTransaction/MultipartyTransactionParameters.cs
- WalletWasabi/WabiSabi/Models/RoundState.cs
Implements the change requested in:
https://github.com/zkSNACKs/WalletWasabi/pull/5854#pullrequestreview-672559468
> [WabiSabi] Move `ConnectionConfirmationTimeOut` to `RoundState`

- WalletWasabi.Tests/Helpers/DependencyGraphExtensions.cs
- WalletWasabi.Tests/UnitTests/WabiSabi/Client/CredentialDependencyTests.cs
- WalletWasabi/WabiSabi/Client/CredentialDependencies/DependencyGraph.cs
Addressing: https://github.com/zkSNACKs/WalletWasabi/pull/5726#issuecomment-852555668
> [WabiSabi] DependencyGraph format fixes

- WalletWasabi.Tests/Helpers/DependencyGraphExtensions.cs
- WalletWasabi.Tests/UnitTests/WabiSabi/Client/CredentialDependencyTests.cs
- WalletWasabi/WabiSabi/Client/CredentialDependencies/DependencyGraph.cs
Based on https://github.com/zkSNACKs/WalletWasabi/pull/5876
> [WabiSabi] Simplify aggregation

- WalletWasabi.Tests/UnitTests/WabiSabi/Client/ArenaClientTests.cs
- WalletWasabi/WabiSabi/Client/AliceClient.cs
- WalletWasabi/WabiSabi/Client/ArenaClient.cs
I was reading this code and found these distracting.
> [WabiSabi] Trivial cleanups

- WalletWasabi.Backend/wwwroot/index.html
- WalletWasabi/Helpers/Constants.cs
Related https://github.com/zkSNACKs/WalletWasabi/pull/5880
> Update version to 1.1.12.9

- WalletWasabi.Tests/UnitTests/WabiSabi/Client/ArenaClientTests.cs
- WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiHttpApiIntegrationTests.cs
- WalletWasabi/WabiSabi/Client/AliceClient.cs
- WalletWasabi/WabiSabi/Client/ArenaClient.cs
- WalletWasabi/WabiSabi/Client/BobClient.cs
Implements reissuance in BobClient.
> [WabiSabi] Remove script from reissuance

- WalletWasabi.Tests/IntegrationTests/BlockstreamInfoTests.cs
- WalletWasabi.Tests/UnitTests/Tor/Socks5/TorTcpConnectionFactoryTests.cs
This PR removes debug code that was not removed by accident.
> trivial: Remove debug code

- WalletWasabi.Tests/Helpers/WabiSabiFactory.cs
- WalletWasabi/WabiSabi/Models/RoundState.cs
To get rid of some of suggestions in VS.
> [Trivial] Simplify 'new' expression

- WalletWasabi.Fluent/ViewModels/AddWallet/Create/ConfirmRecoveryWordsViewModel.cs
Part of https://github.com/zkSNACKs/WalletWasabi/issues/5939
> [Fluent] Create Wallet - 3 words to confirm instead of 4

- WalletWasabi/Tor/TorProcessManager.cs
This PR does not change behavior. The purpose is only to prepare theground for my next PRs regarding:
* `TorMonitor` and improved Tor Control functionality, and 
* making sure that Tor process can crash and we will recover correctly.
The PR should be easy to follow commit by commit as the changes are mostly *move code only*.
> TorProcessManager: Split `StartAsync` method

- WalletWasabi.Tests/UnitTests/Crypto/ProofSystemTests.cs
- WalletWasabi/Crypto/ZeroKnowledge/Credential.cs
- WalletWasabi/Crypto/ZeroKnowledge/ProofSystem.cs
- WalletWasabi/WabiSabi/Client/ArenaClient.cs
- WalletWasabi/WabiSabi/Client/SmartRequestNode.cs
- WalletWasabi/WabiSabi/Crypto/IssuanceValidationData.cs
- WalletWasabi/WabiSabi/Crypto/WabiSabiClient.cs
- WalletWasabi/WabiSabi/Crypto/ZeroCredentialPool.cs
> Credential bikeshedding

- WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepOutputRegistrationTests.cs
- WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepTransactionSigningTests.cs
- WalletWasabi.Tests/UnitTests/WabiSabi/Client/AliceClientTests.cs
- WalletWasabi.Tests/UnitTests/WabiSabi/Client/BobClientTests.cs
- WalletWasabi/WabiSabi/Client/AliceClient.cs
Closes https://github.com/zkSNACKs/WalletWasabi/issues/5961
> [WabiSabi] Remove obsolete `ConfirmConnectionAsync` method

- WalletWasabi.Backend/Program.cs
- WalletWasabi.Packager/Program.cs
- WalletWasabi/Tor/Control/Messages/CircuitStatus/CircStatus.cs
This PR removes unnecessary suppression message attributes.
> [Trivial] Remove unnecessary suppression

- WalletWasabi.Fluent/Styles/SettingsLayout.axaml
- WalletWasabi.Fluent/Styles/Styles.axaml
- WalletWasabi.Fluent/ViewModels/Wallets/Advanced/WalletInfoViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/WalletSettingsViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModel.cs
- WalletWasabi.Fluent/Views/Settings/BitcoinTabSettingsView.axaml
- WalletWasabi.Fluent/Views/Settings/GeneralSettingsTabView.axaml
- WalletWasabi.Fluent/Views/Settings/NetworkSettingsTabView.axaml
- WalletWasabi.Fluent/Views/Settings/PrivacySettingsTabView.axaml
- WalletWasabi.Fluent/Views/Wallets/Advanced/WalletInfoView.axaml
- WalletWasabi.Fluent/Views/Wallets/WalletSettingsView.axaml
- WalletWasabi.Fluent/Views/Wallets/WalletSettingsView.axaml.cs
- WalletWasabi.Fluent/Views/Wallets/WalletView.axaml
Initial implementation of Wallet Settings. Wallet-specific settings can be put here.
> [Fluent] Wallet settings

- WalletWasabi.Fluent/Behaviors/RemoveClassAction.cs
This is opposite to AddClassAction action.
> [Fluent] [Trivial] Add RemoveClassAction action

- WalletWasabi.Fluent/Controls/NavBarItem.axaml
- WalletWasabi.Fluent/Controls/QuestionControl.axaml
- WalletWasabi.Fluent/Styles/BalanceLineChart.axaml
- WalletWasabi.Fluent/Styles/Button.axaml
- WalletWasabi.Fluent/Styles/Checkmark.axaml
- WalletWasabi.Fluent/Styles/Themes/Base.axaml
- WalletWasabi.Fluent/Styles/Themes/BaseDark.axaml
- WalletWasabi.Fluent/Styles/Themes/BaseLight.axaml
- WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/WalletPieChartTileViewModel.cs
- WalletWasabi.Fluent/Views/LineChartDemo/SendLineChartView.axaml
- WalletWasabi.Fluent/Views/Login/PasswordFinder/PasswordFoundView.axaml
- WalletWasabi.Fluent/Views/MainView.axaml
- WalletWasabi.Fluent/Views/NavBar/NavBar.axaml
- WalletWasabi.Fluent/Views/Wallets/Home/History/HistoryTable.axaml
- WalletWasabi.Fluent/Views/Wallets/Home/Tiles/WalletBalanceChart/WalletBalanceChartLargeTileView.axaml
- WalletWasabi.Fluent/Views/Wallets/Home/Tiles/WalletBalanceChart/WalletBalanceChartMediumTileView.axaml
- WalletWasabi.Fluent/Views/Wallets/Home/Tiles/WalletBalanceChart/WalletBalanceChartWideTileView.axaml
- WalletWasabi.Fluent/Views/Wallets/Send/SendView.axaml
> [Fluent] New brand colours (light theme only)

- WalletWasabi.Fluent/Behaviors/RemoveClassAction.cs
- WalletWasabi.Fluent/ViewModels/HelpAndSupport/AboutViewModel.cs
- WalletWasabi.Fluent/ViewModels/HelpAndSupport/LinkViewModel.cs
- WalletWasabi.Fluent/ViewModels/HelpAndSupport/SeparatorViewModel.cs
- WalletWasabi.Fluent/Views/Dialogs/AboutAdvancedInfoView.axaml
- WalletWasabi.Fluent/Views/HelpAndSupport/AboutView.axaml
- WalletWasabi.Fluent/Views/HelpAndSupport/LinkView.axaml
- WalletWasabi.Fluent/Views/HelpAndSupport/LinkView.axaml.cs
Part of https://github.com/zkSNACKs/WalletWasabi/issues/5974
> [Fluent] About - Layout fixes

- WalletWasabi.Fluent/Views/MainWindow.axaml
Increase it from 520x420 to 640x480.
640x480 is the lowest that the Windows and Mac support (I assume the same on Linux).
> [Fluent] Increase minimum window size

- WalletWasabi.Fluent/Views/Wallets/Receive/ReceiveAddressView.axaml
https://github.com/zkSNACKs/WalletWasabi/issues/5974
```
[6] Receive
- QR code is not visible (I am not sure if is it an issue)
- QR code save button margin
```
> [Fluent] Receive - Layout fixes

- WalletWasabi/Tor/TorProcessManager.cs
> TorProcessManager: Do not log exception.

- WalletWasabi.Tests/UnitTests/BitcoinCore/BitcoindBinaryHashesTests.cs
- WalletWasabi/Helpers/Constants.cs
> Update to Bitcoin Knots 0.21.1

- WalletWasabi.Fluent/Styles/Themes/Base.axaml
- WalletWasabi.Fluent/Styles/Themes/BaseDark.axaml
- WalletWasabi.Fluent/Styles/Themes/BaseLight.axaml
> [Fluent] Adjust toggleswitch colors to match accents

- WalletWasabi.Backend/wwwroot/index.html
Based on the rough conclusion of the following conversations: https://github.com/zkSNACKs/WalletWasabi/pull/5928, https://old.reddit.com/r/Bitcoin/comments/ogsn1d/wasabi_wallet_20_in_the_finish_line_introduction/h4l1krb/
Having PGP fingerprint on the website is good (best?) practice. The PGP can be got from GitHub and it can be checked against the fingerprint on the website. This setup distributes trust.
Since the website is directly deployed from GitHub, it's questionable if this adds any extra security. Probably it does in some edge cases, e.g. if the internet provider would server its own fake GitHub instead of the real one.
On Windows and OSX the native code signing procedure is a replacement of PGP. It must be noted, it has weaker trust model though, but PGP's practical utility is …
> Add PGP Fingerprint to website

- WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/WalletPieChartTileViewModel.cs
cc @soosr @danwalmsley @kiminuo
> Fix divide by zero bug on pie chart when balance is empty

- WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/WalletBalanceTileViewModel.cs
- WalletWasabi.Fluent/Views/Wallets/Home/Tiles/WalletPieChart/WalletPieChartLargeTileView.axaml
- WalletWasabi.Fluent/Views/Wallets/Home/Tiles/WalletPieChart/WalletPieChartWideTileView.axaml
fixes https://github.com/zkSNACKs/WalletWasabi/issues/6047
> [Fluent] Fix amount display inconsistency

- WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiHttpApiIntegrationTests.cs
This is trivial self-explaining change.
> [WabiSabi] Make log less verbose for multi-client test

- WalletWasabi.Fluent/ViewModels/Wallets/Receive/ReceiveViewModel.cs
The CodeFactor complains in this PR https://github.com/zkSNACKs/WalletWasabi/pull/6078, despite those lines were not touched there.
I fix them here.
> [Trivial] Fix codefactor

- WalletWasabi.Fluent/Styles/Slider.axaml
- WalletWasabi.Fluent/Styles/Styles.axaml
- WalletWasabi.Fluent/Styles/Themes/Base.axaml
- WalletWasabi.Fluent/Styles/Themes/BaseDark.axaml
- WalletWasabi.Fluent/Styles/Themes/BaseLight.axaml
> [Fluent] Styling slider

- WalletWasabi.Tests/Helpers/ArenaRequestHandlerAdapter.cs
- WalletWasabi/WabiSabi/Backend/PostRequests/ArenaRequestHandler.cs
- WalletWasabi/WabiSabi/Backend/PostRequests/InputRegistrationHandler.cs
- WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
Closes https://github.com/zkSNACKs/WalletWasabi/issues/5991
Once NBitcoin is released we will be able to pass this CT to RPC calls too.
> [WabiSabi] Pass cancellationToken down

- WalletWasabi.Fluent/ViewModels/MainViewModel.cs
fixes https://github.com/zkSNACKs/WalletWasabi/issues/6106.
based on https://github.com/zkSNACKs/WalletWasabi/issues/6106#issuecomment-888167776
> [Fluent] fix dialog overlay issue

- WalletWasabi.Fluent/ViewModels/MainViewModel.cs
> [Fluent] Clear compact dialog navigation stack too

- WalletWasabi.Tests/Helpers/WabiSabiFactory.cs
- WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepInputRegistrationTests.cs
- WalletWasabi.Tests/UnitTests/WabiSabi/Client/ArenaClientTests.cs
- WalletWasabi/WabiSabi/Backend/Banning/Prison.cs
- WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
Closes https://github.com/zkSNACKs/WalletWasabi/issues/6074
In case at least one Alice spent the coin those alices are noticed and the round is ended.
> [WabiSabi] Recheck that all the Txo are unspent

- WalletWasabi/Blockchain/Keys/KeyManager.cs
- WalletWasabi/Wallets/Wallet.cs
Based on Lucas' [comment](https://github.com/zkSNACKs/WalletWasabi/issues/5188#issuecomment-891208631).
This is supposed to fix #5188
> Use ToList() to prevent the collection that is being iterated to get modified

- WalletWasabi/Stores/IndexStore.cs
Similar to https://github.com/zkSNACKs/WalletWasabi/pull/6131
> The same problem could happen (i didn't checked it very carefully) here: https://github.com/molnard/WalletWasabi/blob/d088736d49eaea65ea4a8816f346bca601f13090/WalletWasabi/Stores/IndexStore.cs#L294.
https://github.com/zkSNACKs/WalletWasabi/issues/5188#issuecomment-891208631
> Clone collection to prevent it from being mutated

- WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiHttpApiIntegrationTests.cs
This is a trivial code removal PR. 
I have discussed this with @nothingmuch and he said it should no longer be needed.
> `WabiSabiHttpApiIntegrationTests`: Remove unused `GetStatefullMockRpc`

- WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
- WalletWasabi/WabiSabi/Crypto/CredentialIssuer.cs
Related https://github.com/zkSNACKs/WalletWasabi/pull/6065
> [WabiSabi] Reduce ReissuanceAsync lock-contention

- WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
> [WabiSabi] Reduce ReadyToSignAsync lock-contention

- WalletWasabi.Fluent/ViewModels/Wallets/Send/SendViewModel.cs
- WalletWasabi.Fluent/Views/Wallets/Send/SendView.axaml
> [Fluent] Hide QR scan button on unsupported OS

- WalletWasabi.Fluent/Controls/TagsBox.axaml
- WalletWasabi.Fluent/Views/Wallets/Home/History/HistoryTable.axaml
- WalletWasabi.Fluent/Views/Wallets/Send/TransactionPreviewView.axaml
https://github.com/zkSNACKs/WalletWasabi/issues/6073#issuecomment-886634178
> [Fluent] Tagsbox consistent margin

- WalletWasabi.Fluent/Views/Wallets/Send/PrivacyControlView.axaml
This PR adds the usual fade in/out animation for warning messages.
> [Fluent] Privacy Control - increase smoothness

- WalletWasabi.Fluent/ViewModels/Dialogs/Authorization/HardwareWalletAuthDialogViewModel.cs
It is the first page, makes no sense to have a navigate back button.
> [Fluent] HW auth dialog - remove back button

- WalletWasabi.Fluent/Controls/CurrencyEntryBox.axaml
Same as https://github.com/zkSNACKs/WalletWasabi/pull/6190, but on the `CurrencyEntryBox`
> [Fluent] Validation error message fixes 2

- WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
- WalletWasabi/WabiSabi/Crypto/CredentialIssuer.cs
> [WabiSabi] Rename Task<CredentialResponse> HandleRequest{,Async}

- WalletWasabi.Fluent/ViewModels/AddWallet/AddedWalletPageViewModel.cs
I have made a tiny modification in `AddedWalletPageViewModel` because a silent exception happened on the success page when I clicked Done.
- Now the wallet gets added when the success page appears (instead of when clicking Done) which makes more sense since the page says "Success" so let it be "success" from the first time, not just when the button is clicked.
- During creating a HW wallet it automatically gets added to the software so no need to add it again on the success screen. I added a check for it.
> [Fluent] Fix add hw wallet

- WalletWasabi.Fluent/Controls/TagsBox.axaml.cs
> fix auto complete box appearing when it shouldnt on osx.

- WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiHttpApiIntegrationTests.cs
- WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
> Privatize StartRoundAsync

- WalletWasabi.Fluent/Views/Settings/SettingsPageView.axaml
> [Fluent] Make Settings tabs not draggable

- WalletWasabi.Tests/UnitTests/WabiSabi/Backend/AliceTimeoutTests.cs
- WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepOutputRegistrationTests.cs
- WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepTransactionSigningTests.cs
- WalletWasabi.Tests/UnitTests/WabiSabi/Client/BobClientTests.cs
- WalletWasabi/WabiSabi/Client/AliceClient.cs
- WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
Make AliceId secret again, so we will be able to use it as proof of identity.
> Create AliceClient with input registration

- WalletWasabi.Fluent/ViewModels/AddWallet/AddWalletPageViewModel.cs
- WalletWasabi.Fluent/ViewModels/Dialogs/Base/DialogViewModelBase.cs
- WalletWasabi.Fluent/ViewModels/Dialogs/Base/DialogViewModelBaseOfTResult.cs
- WalletWasabi.Fluent/ViewModels/Navigation/NavigationStack.cs
- WalletWasabi.Fluent/ViewModels/Navigation/TargettedNavigationStack.cs
We cover the main ui with nice background image when user is in the add wallet experience, to prevent distractions.
this alleviates issues like: https://github.com/zkSNACKs/WalletWasabi/issues/6266
> always show the oobe background during add wallet procedure.

- WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
- WalletWasabi/Wallets/Wallet.cs
https://github.com/zkSNACKs/WalletWasabi/issues/5957
> Add manual CoinJoin codeonly

- WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
- WalletWasabi/Wallets/Wallet.cs
> Better naming for IsManualCoinJoinEnabled

- WalletWasabi/Logging/Logger.cs
This is a trivial PR that helps with debugging. 
WDYT?
> logger: Increase time granularity to milliseconds.

- WalletWasabi.Fluent.Desktop/Program.cs
- WalletWasabi.Fluent/App.axaml.cs
- WalletWasabi.Fluent/Behaviors/HideShowBehavior.cs
- WalletWasabi.Fluent/Services.cs
- WalletWasabi.Fluent/ViewModels/MainViewModel.cs
- WalletWasabi.Fluent/ViewModels/Settings/GeneralSettingsTabViewModel.cs
- WalletWasabi.Fluent/Views/MainWindow.axaml
- WalletWasabi.Fluent/Views/Settings/GeneralSettingsTabView.axaml
- WalletWasabi.Gui/UiConfig.cs
Part of https://github.com/zkSNACKs/WalletWasabi/issues/4591
> Add HideOnClose setting on windows

- WalletWasabi.Fluent/Controls/TagControl.axaml
fixes https://github.com/zkSNACKs/WalletWasabi/issues/6302
> [Fluent] Fix weird behavior with labels

- WalletWasabi.Fluent/Views/Wallets/ClosedWatchOnlyWalletView.axaml
- WalletWasabi.Fluent/Views/Wallets/ClosedWatchOnlyWalletView.axaml.cs
- WalletWasabi.Fluent/Views/Wallets/WatchOnlyWalletView.axaml
- WalletWasabi.Fluent/Views/Wallets/WatchOnlyWalletView.axaml.cs
fixes https://github.com/zkSNACKs/WalletWasabi/issues/6328
> [Fluent] Fix watch only wallet view

- WalletWasabi.Fluent/ViewModels/AddWallet/Create/ConfirmRecoveryWordsViewModel.cs
- WalletWasabi.Fluent/ViewModels/AddWallet/Create/RecoveryWordsViewModel.cs
- WalletWasabi.Fluent/ViewModels/AddWallet/HardwareWallet/ConnectHardwareWalletViewModel.cs
- WalletWasabi.Fluent/ViewModels/AddWallet/HardwareWallet/DetectedHardwareWalletViewModel.cs
- WalletWasabi.Fluent/ViewModels/AddWallet/RecoverWalletViewModel.cs
- WalletWasabi.Fluent/ViewModels/AddWallet/SelectWalletCreationOptionViewModel.cs
- WalletWasabi.Fluent/ViewModels/Dialogs/CreatePasswordDialogViewModel.cs
Same as we did on Send pages.
closes https://github.com/zkSNACKs/WalletWasabi/issues/6266.
> [Fluent] secure canceling on add wallet pages

- WalletWasabi.Fluent/Controls/QrCode.cs
Fixes #6220
@zkSNACKs/visual-design-group
> [Fluent] Fix export of QR Code when Wasabi's in private mode

- WalletWasabi.Fluent/Views/Wallets/Home/History/HistoryTable.axaml
fixes https://github.com/zkSNACKs/WalletWasabi/issues/6363
> [Fluent] better icon for pending

- WalletWasabi.Fluent/Styles/Button.axaml
fixes https://github.com/zkSNACKs/WalletWasabi/issues/6372
> [Fluent] Correct function button disabled look

- WalletWasabi.Fluent/ViewModels/Wallets/Receive/ReceiveAddressViewModel.cs
fixes https://github.com/zkSNACKs/WalletWasabi/issues/6355
> [Fluent] close the dialog if the selected address gets used

- WalletWasabi.Fluent/Controls/TagControl.axaml
- WalletWasabi.Fluent/Controls/TagControl.axaml.cs
- WalletWasabi.Fluent/Controls/TagsBox.axaml
- WalletWasabi.Fluent/Controls/TagsBox.axaml.cs
- WalletWasabi.Fluent/Views/AddWallet/RecoverWalletView.axaml
> [Fluent] Add counter to recovery words

- WalletWasabi.Fluent/Models/WebcamQrReader.cs
Fixes an incorrectly synchronized variable.
> `WebCamQrReader`: Fix threading issue

- WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
During a coinjoin session  I noticed that after some Tor exceptions the CJM stopped working. This PR await for the completed tasks (faulted or not) just to make sure all the transactions are unwrapped and rethrown locally and handled (swallowed) in try-catch block.
> [WabiSabi] Make sure to handle the faulted tasks

- WalletWasabi.Tests/UnitTests/WabiSabi/Models/MultipartyTransactionTests.cs
The test assumed the order of the inputs and outputs in the transaction.
> [WabiSabi] Fix test that was passing just by chance

- WalletWasabi.Tests/UnitTests/WabiSabi/Integration/Participant.cs
- WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiHttpApiIntegrationTests.cs
- WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
- WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
- WalletWasabi/WebClients/Wasabi/HttpClientFactory.cs
- WalletWasabi/WebClients/Wasabi/IHttpClientFactory.cs
This PR makes sure that every Alice has its own long-live dedicated tor connection while Bob uses a new circuit for each request.
> [WabiSabi] Implement proper Tor Isolation for Alice and Bob

- WalletWasabi.Fluent.Desktop/packages.lock.json
- WalletWasabi.Fluent/packages.lock.json
- WalletWasabi.Gui/packages.lock.json
- WalletWasabi.Packager/packages.lock.json
- WalletWasabi.Tests/RegressionTests/BuildTests.cs
- WalletWasabi.Tests/RegressionTests/CoinJoinTests.cs
- WalletWasabi.Tests/RegressionTests/DosTests.cs
- WalletWasabi.Tests/RegressionTests/SendTests.cs
- WalletWasabi.Tests/UnitTests/BitcoinCore/P2pBasedTests.cs
- WalletWasabi.Tests/UnitTests/BlockNotifierTests.cs
- WalletWasabi.Tests/UnitTests/CoordinatorRoundTests.cs
- WalletWasabi.Tests/UnitTests/InvalidTxExceptionTests.cs
- WalletWasabi.Tests/UnitTests/MockRpcClient.cs
- WalletWasabi.Tests/UnitTests/SmartBlockProviderTests.cs
- WalletWasabi.Tests/UnitTests/Transactions/PayjoinTests.cs
- WalletWasabi.Tests/UnitTests/Transactions/TransactionFactoryTests.cs
- WalletWasabi.Tests/UnitTests/Transactions/TransactionProcessorTests.cs
- WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterInputFailureTests.cs
- WalletWasabi/BitcoinCore/Rpc/IRPCClient.cs
- WalletWasabi/BitcoinCore/Rpc/RpcClientBase.cs
- WalletWasabi/Blockchain/Keys/HdPubKey.cs
- WalletWasabi/Crypto/Bip322Signature.cs
- WalletWasabi/Extensions/RPCClientExtensions.cs
- WalletWasabi/JsonConverters/BitcoinEncryptedSecretNoECJsonConverter.cs
- WalletWasabi/WabiSabi/Models/OutputRegistrationRequest.cs
- WalletWasabi/WalletWasabi.csproj
- WalletWasabi/packages.lock.json
> Update to latest NBitcoin version (6.0.8)

- WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiHttpApiIntegrationTests.cs
Also, simulate the client to fail with an exception to make the thing
more real.
> Uncomment test commented by error

- WalletWasabi.Fluent/ViewModels/HelpAndSupport/BugReportLinkViewModel.cs
- WalletWasabi.Fluent/ViewModels/HelpAndSupport/DocsLinkViewModel.cs
- WalletWasabi.Fluent/ViewModels/HelpAndSupport/UserSupportViewModel.cs
fixes https://github.com/zkSNACKs/WalletWasabi/issues/6364
> [Fluent] add captions for buttons that open websites

- WalletWasabi.Fluent/Styles/TextBox.axaml
- WalletWasabi.Fluent/ViewModels/Wallets/Home/History/TransactionDetailsViewModel.cs
- WalletWasabi.Fluent/Views/Wallets/Home/History/TransactionDetailsView.axaml
- WalletWasabi.Fluent/Views/Wallets/Receive/ReceiveAddressView.axaml
- WalletWasabi.Fluent/Views/Wallets/Send/TransactionPreviewView.axaml
fixes https://github.com/zkSNACKs/WalletWasabi/issues/6359
> [Fluent] Make texts selectable

- WalletWasabi.Gui/Global.cs
- WalletWasabi/Services/SleepInhibitor.cs
- WalletWasabi/Services/SystemAwakeChecker.cs
First part of the `SystemAwakeChecker`'s refactoring process.
Edit: `SystemAwakeChecker.cs` -> `SleepInhibitor.cs`
> Clean up in SystemAwakeChecker

- WalletWasabi.Fluent/ViewModels/Dialogs/ShowQrCameraDialogViewModel.cs
Add missing dispose.
(Requires careful review, I don't know Avalonia too much.)
> `ShowQrCameraDialogViewModel`: Move code to `OnNavigatedTo` and add dispose logic

- WalletWasabi.Fluent/Styles/Button.axaml
- WalletWasabi.Fluent/ViewModels/Wallets/Receive/AddressViewModel.cs
- WalletWasabi.Fluent/Views/Wallets/Home/History/HistoryTable.axaml
- WalletWasabi.Fluent/Views/Wallets/Receive/ReceiveAddressesView.axaml
Wrap receive addresses view labels same as in transaction history table.
> [Fluent] Wrap receive addresses view labels

- WalletWasabi.Fluent/Controls/TagControl.axaml
fixes https://github.com/zkSNACKs/WalletWasabi/issues/6403
> [Fluent] Fix missing delete button on long Label

- WalletWasabi.Fluent/Views/NavBar/NavBar.axaml
fixes https://github.com/zkSNACKs/WalletWasabi/issues/6369
https://user-images.githubusercontent.com/16364053/134041032-f32c248a-d48c-47b5-a2c4-e12d2759c969.mp4
> [Fluent] Navigation bar - Expand/Collapse manually 

- WalletWasabi.Fluent/Controls/TagsBox.axaml.cs
- WalletWasabi.Fluent/ViewModels/AddWallet/RecoverWalletViewModel.cs
fixes https://github.com/zkSNACKs/WalletWasabi/issues/6263
~~fixes: It was not possible to add a recovery word by pressing the TagSeparator key (space) - I broke it during refactoring -~~
> [Fluent] Recover wallet fixes

- WalletWasabi/Wallets/Wallet.cs
Fixes #6246
Best to review with whitespace off: https://github.com/zkSNACKs/WalletWasabi/pull/6434/files?diff=split&w=1
> `Wallet`: Make it impossible to stop twice

- WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
- WalletWasabi/WabiSabi/Client/WalletStatusChangedEventArgs.cs
This PR creates a new event `WalletStatusChanged`, to get whenever a Wallet has been added or removed to/from a CoinJoin.
> Add Wallet CoinJoin status

- WalletWasabi.Fluent/Controls/TagsBox.axaml
- WalletWasabi.Fluent/Controls/TagsBox.axaml.cs
- WalletWasabi.Fluent/Views/Wallets/Receive/ReceiveView.axaml
- WalletWasabi.Fluent/Views/Wallets/Send/SendView.axaml
part of https://github.com/zkSNACKs/WalletWasabi/issues/6422
The max label length will be 50 chars.
> [Fluent] Labels length limitation

- WalletWasabi.Backend/Controllers/ChaumianCoinJoinController.cs
- WalletWasabi.Tests/RegressionTests/CoinJoinTests.cs
- WalletWasabi.Tests/RegressionTests/DosTests.cs
- WalletWasabi/CoinJoin/Coordinator/Coordinator.cs
I think we should really aim to fix all these nullability warnings in WabiSabi. They show us real issues where the annotations are not correct and then it is not clear whether a type is nullable or not.
> WabiSabi: Fix some nullability warnings

- WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
This PR closes https://github.com/zkSNACKs/WalletWasabi/issues/6074.
> [WabiSabi] Recheck inputs for spend status during connection confirmation

- WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
As the title says, this PR is for scheduling Alices' `SignTransaction` requests in the same way `RegisterInputs` does it. This PR depends on https://github.com/zkSNACKs/WalletWasabi/pull/6443 which has to be merged first.
> [WabiSabi] Schedule SignTransaction requests

- WalletWasabi.Documentation/WasabiCompatibility.md
Four grammar fixes at lines 3, 42, 46, and 51.
> Update WasabiCompatibility.md - grammar fixes

- WalletWasabi/Crypto/Extensions.cs
- WalletWasabi/Extensions/TaskExtensions.cs
- WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
- WalletWasabi/WabiSabi/Client/DependencyGraphTaskScheduler.cs
As the title says, this PR is for scheduling Bobs' `OutputRegistration` requests in the same way RegisterInputs does it. This PR depends on #6443 which has to be merged first.
> [WabiSabi] Schedule Output Registration requests

- WalletWasabi.Backend/Controllers/WabiSabiController.cs
- WalletWasabi.Tests/UnitTests/WabiSabi/Backend/AliceTimeoutTests.cs
- WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/ConfirmConnectionTests.cs
- WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterInputFailureTests.cs
- WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterInputToBlameRoundTests.cs
- WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterOutputTests.cs
- WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RemoveInputTests.cs
- WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/SignTransactionTests.cs
- WalletWasabi.Tests/UnitTests/WabiSabi/Backend/RequestHandlerDisposeTests.cs
- WalletWasabi.Tests/UnitTests/WabiSabi/Client/ArenaClientTests.cs
- WalletWasabi.Tests/UnitTests/WabiSabi/Client/BobClientTests.cs
- WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiHttpApiIntegrationTests.cs
- WalletWasabi/WabiSabi/Backend/PostRequests/ArenaRequestHandler.cs
- WalletWasabi/WabiSabi/WabiSabiCoordinator.cs
This is a part of work on #6257. 
Please review commit-by-commit.
> `ArenaRequestHandler`: Cleanup

- WalletWasabi/WabiSabi/WabiSabiCoordinator.cs
Another minor cleanup. 
It was found when researching the order in which things are disposed in WabiSabi.
> `WabiSabiCoordinator`: Clean up.

- WalletWasabi.Backend/wwwroot/index.html
- WalletWasabi/Helpers/Constants.cs
> Bump client version to 1.1.13.0

- WalletWasabi.Fluent/Behaviors/RandomizedWorldPointsBehavior.cs
> [Fluent] Fix Null Exception on some cases in RandomizedWorldBehavior

- WalletWasabi/Tor/Http/Models/HeaderSection.cs
Partial port of #6572 from WW1.
> [forward-port] Make HTTP header names case-insensitive

- WalletWasabi.Documentation/WasabikaCodex.md
Tried to make `Create a Pull Request` process more non-dev friendly.
Introduced `How to Fork a repo`, `How to clone the forked repo` and expanded `How to create a PR` section.
If you think it's still scary and not friendly at all, please suggest changes.
> Updated WasabikaCodex for non-devs

- WalletWasabi.Fluent/ViewModels/Login/PasswordFinder/SearchPasswordViewModel.cs
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/6647
> Add `LogTrace` in catch block

- WalletWasabi.Tests/UnitTests/Transactions/TransactionFactoryTests.cs
- WalletWasabi/Blockchain/Transactions/TransactionFactory.cs
> [Trivial] Correct transaction fee message

- WalletWasabi.Backend/Global.cs
- WalletWasabi.Tests/IntegrationTests/LiveServerTests.cs
- WalletWasabi.Tests/RegressionTests/CoinJoinTests.cs
- WalletWasabi.Tests/RegressionTests/DosTests.cs
- WalletWasabi/CoinJoin/Client/Clients/AliceClient4.cs
- WalletWasabi/CoinJoin/Client/Clients/AliceClientBase.cs
- WalletWasabi/CoinJoin/Client/Clients/BobClient.cs
- WalletWasabi/CoinJoin/Client/Clients/CoinJoinClient.cs
- WalletWasabi/CoinJoin/Client/Clients/SatoshiClient.cs
- WalletWasabi/CoinJoin/Client/Rounds/ClientRound.cs
- WalletWasabi/CoinJoin/Client/Rounds/ClientRoundRegistration.cs
- WalletWasabi/CoinJoin/Client/Rounds/ClientState.cs
- WalletWasabi/CoinJoin/Coordinator/Coordinator.cs
- WalletWasabi/CoinJoin/Coordinator/RoundBootstrapper.cs
There is a deadlock in the code - this tries to fix this. It is not ready yet - Tests are failing but the direction is this.
> Fix ZeroLink on Backend

- WalletWasabi/Blockchain/TransactionOutputs/CoinsRegistry.cs
- WalletWasabi/Blockchain/TransactionOutputs/CoinsView.cs
- WalletWasabi/Blockchain/TransactionOutputs/ICoinsView.cs
- WalletWasabi/Blockchain/TransactionProcessing/TransactionProcessor.cs
- WalletWasabi/Wallets/WalletManager.cs
Based on https://github.com/zkSNACKs/WalletWasabi/pull/6677
fixes https://github.com/zkSNACKs/WalletWasabi/issues/4955
fixes https://github.com/zkSNACKs/WalletWasabi/issues/4955
> Fix coin may be null

- WalletWasabi/Blockchain/TransactionBroadcasting/TransactionBroadcaster.cs
- WalletWasabi/Blockchain/TransactionOutputs/CoinsRegistry.cs
- WalletWasabi/Blockchain/TransactionOutputs/CoinsView.cs
- WalletWasabi/Blockchain/TransactionOutputs/ICoinsView.cs
- WalletWasabi/Blockchain/TransactionProcessing/TransactionProcessor.cs
- WalletWasabi/Wallets/WalletManager.cs
> [Backport] Fix coin may be null

- WalletWasabi.Fluent/Controls/RingChartControl.cs
Fixes CodeFactor issues in #6695
This PR was opened separately to keep the diff of #6695 clean, therefor it should be merged before it (if #6695 is to be merged).
> [Trivial] Fix CodeFactor issues in RingChartControl.cs

- WalletWasabi.Fluent/Views/Wallets/Advanced/WalletInfoView.axaml
Fixes #6693
Title says it all. 😄
> [Fluent] Hide private output descriptors

- WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionPreviewViewModel.cs
https://github.com/zkSNACKs/WalletWasabi/pull/6551#issuecomment-953639672
> [VDG] Show privacy optimization option in self-spend case as well

- WalletWasabi.Tests/UnitTests/Tor/Http/Helpers/HttpStatusCodeHelperTests.cs
- WalletWasabi/Tor/Http/Helpers/HttpStatusCodeHelper.cs
I have noticed this when looking around to fix #6576.
We might save an allocation in the process. Not that it matters too much.
> `HttpStatusCodeHelper`: Very minor optimization

- WalletWasabi.Fluent/Views/Wallets/Advanced/WalletInfoView.axaml
Addresses https://github.com/zkSNACKs/WalletWasabi/pull/6698#pullrequestreview-805857635
> [Fluent] Add missing ForceShow to public output descriptors

- WalletWasabi/Blockchain/Keys/KeyManager.cs
As suggested by @kiminuo here https://github.com/zkSNACKs/WalletWasabi/pull/6524#issuecomment-944963522
> Fix nullability warnings

- WalletWasabi/Tor/Http/Helpers/HttpMessageHelper.cs
- WalletWasabi/Tor/Http/Models/HeaderField.cs
- WalletWasabi/Tor/Http/Models/HeaderSection.cs
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/6576#issuecomment-974108491
#6576 should be fixed with this PR.
> `HeaderField`: Introduce `IsNameEqual`.

- WalletWasabi.Tests/UnitTests/ImmutableValueSequenceTests.cs
- WalletWasabi/Extensions/ImmutableValueSequenceExtensions.cs
- WalletWasabi/Models/ImmutableValueSequence.cs
- WalletWasabi/WabiSabi/Crypto/CredentialRequesting/CredentialsRequest.cs
- WalletWasabi/WabiSabi/Crypto/CredentialRequesting/RealCredentialsRequest.cs
- WalletWasabi/WabiSabi/Crypto/CredentialRequesting/ZeroCredentialsRequest.cs
Allows to have arrays that are comparable by value.
> Enumerable with value semantic

- WalletWasabi.Backend/Controllers/HomeController.cs
- WalletWasabi.Tests/UnitTests/Userfacing/ParserTests.cs
This contains only fixes for warnings. As suggested in https://github.com/zkSNACKs/WalletWasabi/pull/6726#issuecomment-976361455
> Fix some null warnings

- WalletWasabi.Gui/Global.cs
Fixes #6733
This allows WW to recover gracefully from these issues:
https://github.com/zkSNACKs/WalletWasabi/issues/5255
https://github.com/zkSNACKs/WalletWasabi/discussions/6625
https://www.reddit.com/r/WasabiWallet/comments/qt0mgz/crashing_on_open/
Note that this is for the backport branch.
If this gets merged I will do the same with the master branch.
> Catch ArgumentException & EndOfStreamException if AddressManager gets corrupted

- WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/SignTransactionTests.cs
- WalletWasabi.Tests/UnitTests/WabiSabi/Models/SerializationTests.cs
- WalletWasabi.Tests/UnitTests/WabiSabi/Models/TransactionSignaturesRequestTests.cs
- WalletWasabi/WabiSabi/Backend/Rounds/Arena.Partial.cs
- WalletWasabi/WabiSabi/Client/ArenaClient.cs
- WalletWasabi/WabiSabi/Models/InputWitnessPair.cs
- WalletWasabi/WabiSabi/Models/TransactionSignaturesRequest.cs
We don't need multiple pairs, just an index and a witness (and in the future possibly a scriptSig).
> [WabiSabi] Remove InputWitnessPair

- WalletWasabi.Fluent/Helpers/FileDialogHelper.cs
> Fix ArgumentNullException exception when cancelling importing a wallet

- WalletWasabi.Tests/UnitTests/WabiSabi/Models/TransactionSignaturesRequestTests.cs
> [trivial] Fix test comment.

- WalletWasabi.Packager/Program.cs
Minor improvement given that `Main` is already `async` in Packager.
> Use `async` code Packager

- WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/ReadyToSignRequestRequestTests.cs
- WalletWasabi.Tests/UnitTests/WabiSabi/Crypto/CredentialRequesting/RealCredentialsRequestTests.cs
- WalletWasabi.Tests/UnitTests/WabiSabi/Crypto/CredentialRequesting/ZeroCredentialsRequestTests.cs
- WalletWasabi.Tests/UnitTests/WabiSabi/Crypto/OwnershipProofTests.cs
- WalletWasabi/Crypto/OwnershipIdentifier.cs
- WalletWasabi/Crypto/OwnershipProof.cs
- WalletWasabi/Extensions/ImmutableValueSequenceExtensions.cs
- WalletWasabi/Models/ImmutableValueSequence.cs
- WalletWasabi/WabiSabi/Crypto/CredentialRequesting/ZeroCredentialsRequest.cs
- WalletWasabi/WabiSabi/Crypto/IssuanceRequest.cs
- WalletWasabi/WabiSabi/Models/ReadyToSignRequestRequest.cs
- WalletWasabi/WabiSabi/Models/ReissueCredentialRequest.cs
Follow up to #6659.
These tests are not strictly needed but they will help us make sure that the idempotency feature really works. For that reason I find it useful, even if it is more code.
> [test] Idempotency: Add more tests

- WalletWasabi/Wallets/WalletManager.cs
Closes #6605
Addresses https://github.com/zkSNACKs/WalletWasabi/issues/6605#issuecomment-974048437
> Throw OpCancelledExc instead of InvalidOpExc in WalletManager.cs

- WalletWasabi.Fluent/ViewModels/WalletManagerViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryViewModel.cs
For some reason, I was not able to do a CJ. 
Can someone test this?
> [VDG] Flash CJ row in transaction history when new happened

- WalletWasabi.Tests/UnitTests/EventSourcing/InMemoryEventRepositoryTests.cs
- WalletWasabi.Tests/UnitTests/EventSourcing/TestDomain/TestInMemoryEventRepository.cs
- WalletWasabi/EventSourcing/InMemoryEventRepository.cs
- WalletWasabi/EventSourcing/WrappedEvent.cs
- WalletWasabi/Interfaces/EventSourcing/IEventRepository.cs
Contains a lot of formatting changes.
> Event sourcing: Formatting

- WalletWasabi/Tor/Socks5/Pool/TorHttpPool.cs
- WalletWasabi/Tor/Socks5/TorTcpConnection.cs
Related to #6874
This PR attempts to improve logging so that we know which TCP connections are open so that we can check whether the connections are valid or not.
> TorHttpPool: Improve logging.

- WalletWasabi.Gui/GlobalUsings.cs
> [Trivial] Remove GlobalUsings for GUI project

- WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/PrivacyControlTileViewModel.cs
A proper fix to https://github.com/zkSNACKs/WalletWasabi/pull/6903#issuecomment-996879845
> Fix 0 privacy percentage issue

- WalletWasabi.Fluent/Controls/CurrencyEntryBox.axaml.cs
- WalletWasabi/Blockchain/Mempool/MempoolService.cs
- WalletWasabi/Blockchain/TransactionOutputs/SmartCoin.cs
- WalletWasabi/Crypto/UnblindedSignature.cs
- WalletWasabi/Extensions/StringExtensions.cs
- WalletWasabi/Tor/Control/TorControlReplyReader.cs
- WalletWasabi/Userfacing/BitcoinInput.cs
- WalletWasabi/Userfacing/PasswordHelper.cs
- WalletWasabi/WabiSabi/Backend/Rounds/Utils/CoinJoinTransactionArchiver.cs
- WalletWasabi/Wallets/Wallet.cs
This PR fixes a couple of warnings.
>  [Trivial] Use range operator

- WalletWasabi.Fluent/Rpc/WasabiJsonRpcService.cs
> [Trivial] Remove unused variable

- WalletWasabi/Blockchain/Transactions/TransactionFactory.cs
> [Backport] Remove feerate different sanity check

- WalletWasabi.Fluent/Views/Dialogs/AboutAdvancedInfoView.axaml
To be clear that we only support one version.
> [Trivial] Edit compatible full node version text

- WalletWasabi.Fluent/Views/Wallets/Receive/ReceiveAddressesView.axaml
> Move hide address button to the Left side

- WalletWasabi.Tests/Helpers/WabiSabiFactory.cs
- WalletWasabi.Tests/RegressionTests/CoinJoinTests.cs
- WalletWasabi.Tests/UnitTests/MockRpcClient.cs
- WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
This is just some formatting and fixing typos
> [Trivial] Cleanup

- WalletWasabi.Fluent/Views/Wallets/Home/History/CoinJoinDetailsView.axaml
fixes https://github.com/zkSNACKs/WalletWasabi/issues/7009
> fix missing txn chars in coinjoin details dialog

- WalletWasabi.Tests/UnitTests/BitcoinCore/BitcoindBinaryHashesTests.cs
- WalletWasabi/Helpers/Constants.cs
> [backport] Update Knots to 21.2

- WalletWasabi.Backend/Config.cs
- WalletWasabi.Fluent/Config.cs
- WalletWasabi/Bases/ConfigBase.cs
Follow-up to #7000.
Fixes ~50 warnings (actually it's about 25 because we do Debug & Release builds).
> Fix a few nullability warnings in `Config` classes

- WalletWasabi.Tests/RegressionTests/SendTests.cs
- WalletWasabi/Wallets/Wallet.cs
- WalletWasabi/Wallets/WalletManager.cs
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/6663
Master Branch:
```
2021-12-24 18:14:54.510 [13] INFO       WalletManager.StartWalletAsync (164)    Starting Wallet...
```
PR Branch:
```
2021-12-25 06:41:28.807 [21] INFO       WalletManager.StartWalletAsync (164)    Starting wallet 'w8'...
```
> add wallet name in logs

- WalletWasabi.Backend/Startup.cs
- WalletWasabi.Fluent.Generators/NavigationMetaDataGenerator.cs
- WalletWasabi.Fluent.Generators/StaticViewLocatorGenerator.cs
- WalletWasabi.Fluent/Behaviors/ButtonExecuteCommandOnKeyDownBehavior.cs
- WalletWasabi.Fluent/Behaviors/HistoryItemDetailsBehavior.cs
- WalletWasabi.Fluent/Behaviors/RandomizedWorldPointsBehavior.cs
- WalletWasabi.Fluent/CrashReport/ViewModels/CrashReportWindowViewModel.cs
- WalletWasabi.Fluent/ViewModels/Dialogs/ShowQrCameraDialogViewModel.cs
- WalletWasabi.Fluent/ViewModels/NavBar/NavBarViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Receive/AddressViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Send/SendFeeViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionSummaryViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModel.cs
- WalletWasabi.Tests/UnitTests/WabiSabi/Integration/Startup.cs
- WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiApiApplicationFactory.cs
- WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiHttpApiIntegrationTests.cs
Turn off whitespace changes for to easily review this.
https://github.com/zkSNACKs/WalletWasabi/pull/7024/files?diff=unified&w=1
> Fix warnings: Use expression body for lambda expressions

- WalletWasabi.Fluent/Models/WebcamQrReader.cs
- WalletWasabi.Fluent/Morph/PolyLine.cs
- WalletWasabi.Fluent/ViewModels/AddWallet/HardwareWallet/DetectedHardwareWalletViewModel.cs
- WalletWasabi.Fluent/ViewModels/Dialogs/ShowQrCameraDialogViewModel.cs
- WalletWasabi.Fluent/ViewModels/Login/PasswordFinder/SearchPasswordViewModel.cs
- WalletWasabi/WabiSabi/Client/AmountDecomposer.cs
- WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
Based on @kiminuo 's https://github.com/zkSNACKs/WalletWasabi/pull/7000#pullrequestreview-849095176
This PR fixes some typos and renames variables.
> [Trivial] Fix Typos

- WalletWasabi.Fluent/Views/Login/LoginView.axaml
Related to #6895 and #6911
[Comment](https://github.com/zkSNACKs/WalletWasabi/pull/6911#issuecomment-1012021460)
> Change Login to Open.

- WalletWasabi.Fluent/ViewModels/Login/LoginViewModel.cs
https://github.com/zkSNACKs/WalletWasabi/pull/7037#issuecomment-1012516600
> Change Login to Open

- WalletWasabi.Tests/UnitTests/Blockchain/TransactionBuilding/ChangelessTransactionCoinSelectorTests.cs
- WalletWasabi/Blockchain/TransactionBuilding/ChangelessTransactionCoinSelector.cs
The variable stands for max extra payment and not fee.
> [Trivial] Correct variable name for clarification

- WalletWasabi.Tests/Helpers/ArenaBuilder.cs
> [trivial] Add missing nullability info

- WalletWasabi.Fluent/Behaviors/PasteButtonFlashBehavior.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Send/SendViewModel.cs
This PR fixes two bugs.
First:
1. There is an address already in the input field.
2. Copy a new one.
3. Select all in the input field, press ~ctl+a~ ctrl+v.
4. On the preview screen you will see the first address, and not the second.
Second:
1. There is an address already in the input field.
2. Copy a new one.
3. Select all in the input field, press ~ctl+a~ ctrl+v.
4. The paste button stayed green.
> [VDG] Send address input fixes

- WalletWasabi.Fluent/Global.cs
- WalletWasabi.Tests/IntegrationTests/P2pTests.cs
- WalletWasabi.Tests/UnitTests/BitcoinCore/P2pBasedTests.cs
- WalletWasabi/BitcoinCore/CoreNodeParams.cs
- WalletWasabi/Stores/BitcoinStore.cs
Fix more warnings in `Global.cs`
> `Global`: Fix a few warnings

- WalletWasabi.Tests/UnitTests/WabiSabi/Client/KeyChainTests.cs
- WalletWasabi/WabiSabi/Client/IDestinationProvider.cs
- WalletWasabi/WabiSabi/Client/IKeyChain.cs
- WalletWasabi/WabiSabi/Client/InternalDestinationProvider.cs
- WalletWasabi/WabiSabi/Client/KeyChain.cs
Please review with whitespace turned off: https://github.com/zkSNACKs/WalletWasabi/pull/7086/files?diff=split&w=1
> [trivial] Convert to file-scoped namespaces.

- WalletWasabi.Fluent.Desktop/WalletWasabi.Fluent.Desktop.csproj
- WalletWasabi.Fluent.Desktop/packages.lock.json
- WalletWasabi.Fluent/WalletWasabi.Fluent.csproj
- WalletWasabi.Fluent/packages.lock.json
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/7033
- Fixes preventing close on osx with quit menu item. (at least the avalonia side)
> update avalonia to 0.10.12 with critical fixes

- WalletWasabi.Tests/UnitTests/Blockchain/Blocks/SmarthHeaderChainTests.cs
- WalletWasabi.Tests/UnitTests/TestWallet.cs
- WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
- WalletWasabi/WabiSabi/Client/IKeyChain.cs
This PR removes a const and an Assert that are not needed, and fixes few typos.
> [Trivial] Remove unnecessary const and Assert

- WalletWasabi.Tests/Helpers/WabiSabiFactory.cs
- WalletWasabi.Tests/UnitTests/WabiSabi/Backend/AliceTimeoutTests.cs
- WalletWasabi.Tests/UnitTests/WabiSabi/Client/ArenaClientTests.cs
- WalletWasabi.Tests/UnitTests/WabiSabi/Client/BobClientTests.cs
- WalletWasabi.Tests/UnitTests/WabiSabi/Client/KeyChainTests.cs
- WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiHttpApiIntegrationTests.cs
- WalletWasabi/WabiSabi/Client/CoinJoinTrackerFactory.cs
- WalletWasabi/WabiSabi/Client/KeyChain.cs
- WalletWasabi/Wallets/Kitchen.cs
Fixes: https://github.com/zkSNACKs/WalletWasabi/issues/7132
> Pass wallet passphrase to KeyChain

- WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
- WalletWasabi/WabiSabi/Client/CoinJoinTrackerFactory.cs
> When To Mix - Last minute

- WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
This was removed previously in #7125 but it was added (mistakenly) again in #7133
> [Trivial] Remove unnecessary const

- WalletWasabi.Packager/Program.cs
Fixes: https://github.com/zkSNACKs/WalletWasabi/pull/6810#issuecomment-1023207914
> Run git on Solution directory

- azure-pipelines-detbuild.yml
Git directory was not copied to the Cloned solution repository - causing https://github.com/zkSNACKs/WalletWasabi/pull/6810#issuecomment-1023207914
> Copy Git dir as well

- WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionSummaryViewModel.cs
`bitcoin` instead of _bitcoins_ at `Preview Transaction`
> bitcoin at preview transaction

- WalletWasabi.Fluent/ViewModels/Wallets/Send/SendViewModel.cs
Set `IsUserInSendWorkflow` to true when the user is in send workflow. Set to false, when they finished with it.
> set `IsUserInSendWorkflow` when sending

- WalletWasabi.Fluent/Styles/Button.axaml
Fixes : #7081 
Changed `StaticResource `to `DynamicResource `in Button.axaml where `TagsBoxBorderBrush `is used
> Changed StaticResource to DynamicResource in Button.axaml

- WalletWasabi.Fluent/ViewModels/Settings/PrivacySettingsTabViewModel.cs
- WalletWasabi/Models/ServiceConfiguration.cs
> [Trivial] Remove leftover code of #7175

- WalletWasabi.Fluent/ViewModels/Wallets/WalletSettingsViewModel.cs
- WalletWasabi/Blockchain/Keys/KeyManager.cs
> Fix Anon Score Targets crash

- WalletWasabi.Fluent/ViewModels/Wallets/Send/PrivacySuggestionsFlyoutViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionPreviewViewModel.cs
(Tries to) Address: https://github.com/zkSNACKs/WalletWasabi/pull/7068#discussion_r797428850 and https://github.com/zkSNACKs/WalletWasabi/pull/7068#issuecomment-1027771045
Created a linked token source to handle timeout and user cancellation.
Also, the suggestion is now disappering after clicking on it.
> Small fixes when generating suggestions

- WalletWasabi.Tests/UnitTests/WabiSabi/Models/RoundStateUpdaterTests.cs
- WalletWasabi/WabiSabi/Client/AliceClient.cs
- WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
- WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
- WalletWasabi/WabiSabi/Client/RoundStateAwaiter.cs
- WalletWasabi/WabiSabi/Client/RoundStateUpdater.cs
Based on: https://github.com/zkSNACKs/WalletWasabi/pull/7193
This PR is an important step to fix the failing SoloCoinJoin tests in CI.
> Do not wait for a Round Phase that is already Ended

- WalletWasabi/Blockchain/Keys/KeyManager.cs
> Fix default values

- WalletWasabi.Fluent/Views/Wallets/Send/SendFeeView.axaml
> [VDG] [Fluent] Fix SendView YAxisLabelOffset

- WalletWasabi.Fluent/ViewModels/Wallets/Send/LabelSelectionViewModel.cs
- WalletWasabi.Tests/UnitTests/UserInterfaceTest/PocketSelectionTests.cs
fixes https://github.com/zkSNACKs/WalletWasabi/issues/7246
> [VDG] Fix `EnoughSelected` calculation

- WalletWasabi.Fluent/Helpers/CoinHelpers.cs
- WalletWasabi.Fluent/Helpers/CoinPocketHelper.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Send/LabelSelectionViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Send/LabelViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Send/PrivacyControlViewModel.cs
- WalletWasabi.Fluent/Views/Wallets/Send/PrivacyControlView.axaml
- WalletWasabi.Tests/UnitTests/UserInterfaceTest/PocketSelectionTests.cs
`Unlabelled Funds` will be presented as `Unknown People` with a custom tooltip.
> [VDG] Handle the unlabelled pockets

- WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItems/CoinJoinsHistoryItemViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItems/TransactionHistoryItemViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModel.cs
This cannot be more trivial.
They showed up as errors, although they never broke the building.
Anyway, this PR removes them.
> [Trivial] Remove redundant casts

- WalletWasabi.Fluent/ViewModels/Wallets/Send/AdvancedSendOptionsViewModel.cs
- WalletWasabi.Fluent/Views/Wallets/Send/AdvancedSendOptionsView.axaml
fixes https://github.com/zkSNACKs/WalletWasabi/issues/7127
> [VDG] Custom Fee - accept chars but show error

- WalletWasabi.Fluent/ViewModels/Wallets/Advanced/WalletCoins/WalletCoinViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Advanced/WalletCoins/WalletCoinsViewModel.cs
- WalletWasabi.Fluent/Views/Wallets/Advanced/WalletCoins/WalletCoinsView.axaml.cs
Review with whitespace change off: https://github.com/zkSNACKs/WalletWasabi/pull/7274/files?diff=unified&w=1
> [Trivial] Convert to file-scoped namespaces

- WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/PrivacyControlTileViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModel.cs
> Update PrivacyLevel on Anon Score Target change

- WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiHttpApiIntegrationTests.cs
> [`SoloCoinJoinTestAsync`] Bump timeout.

- WalletWasabi.Fluent/Views/Wallets/Advanced/WalletCoins/WalletCoinsView.axaml
fixes https://github.com/zkSNACKs/WalletWasabi/issues/7275
> [VDG] Wallet coins - Remove redundant scrollbars

- WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionPreviewViewModel.cs
fixes https://github.com/zkSNACKs/WalletWasabi/issues/7299
> [VDG] Start generating suggestion before dialog is closing

- WalletWasabi.Fluent/CrashReport/Views/CrashReportWindow.axaml
> [Trivial] Remove Width/Height cap in CrashReportWindow

- WalletWasabi.Fluent/ViewModels/Wallets/Send/SendViewModel.cs
> Fix NRE when sending

- WalletWasabi.Fluent/ViewModels/AddWallet/HardwareWallet/ConnectHardwareWalletViewModel.cs
- WalletWasabi.Fluent/Views/AddWallet/HardwareWallet/ConnectHardwareWalletView.axaml
> "Rescan" instead of "Continue" in Add HW Wallet view

- WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryViewModel.cs
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/6661
> Fix self coinjoining with multiple wallets display

- WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItems/CoinJoinsHistoryItemViewModel.cs
If there's one technical term we can expect our users to know about, then it is coinjoin.
> Rename Privacy Boost label to Coinjoins

- WalletWasabi.Fluent/Views/Login/PasswordFinder/PasswordFinderIntroduceView.axaml
- WalletWasabi.Fluent/Views/Login/PasswordFinder/SearchPasswordView.axaml
nitpick
Better wording for non-custodial
> Password finder

- WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItems/CoinJoinsHistoryItemViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItems/HistoryItemViewModelBase.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItems/TransactionHistoryItemViewModel.cs
- WalletWasabi.Fluent/Views/Wallets/Home/History/HistoryTable.axaml
fixes https://github.com/zkSNACKs/WalletWasabi/issues/7319
> [VDG] History - Fix out of range ex

- WalletWasabi.Fluent/App.axaml
- WalletWasabi.Fluent/Styles/Styles.axaml
- WalletWasabi.Fluent/Styles/ToolTip.axaml
> Added application-wide style for ToolTip to prevent text clipping

- WalletWasabi.Fluent.Desktop/packages.lock.json
- WalletWasabi.Fluent/Behaviors/AttachedToVisualTreeBehavior.cs
- WalletWasabi.Fluent/WalletWasabi.Fluent.csproj
- WalletWasabi.Fluent/packages.lock.json
> [VDG] [Fluent] Update Avalonia behaviors package to latest 0.10.12.2 release

- WalletWasabi.Fluent/ViewModels/AddWallet/RecoverWalletViewModel.cs
- WalletWasabi.Fluent/ViewModels/AddWallet/WalletNamePageViewModel.cs
- WalletWasabi.Fluent/ViewModels/Dialogs/CreatePasswordDialogViewModel.cs
- WalletWasabi.Fluent/ViewModels/Login/LoginViewModel.cs
- WalletWasabi.Fluent/ViewModels/Login/PasswordFinder/PasswordFinderIntroduceViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/VerifyRecoveryWordsViewModel.cs
- WalletWasabi.Fluent/Views/AddWallet/Create/ConfirmRecoveryWordsView.axaml
- WalletWasabi.Fluent/Views/AddWallet/RecoverWalletView.axaml
- WalletWasabi.Fluent/Views/AddWallet/WalletNamePageView.axaml
- WalletWasabi.Fluent/Views/Dialogs/AdvancedRecoveryOptionsView.axaml
- WalletWasabi.Fluent/Views/HelpAndSupport/AboutView.axaml
- WalletWasabi.Fluent/Views/Login/LoginView.axaml
- WalletWasabi.Fluent/Views/Wallets/Home/History/HistoryTable.axaml
- WalletWasabi.Fluent/Views/Wallets/VerifyRecoveryWordsView.axaml
This PR removes redundant captions and labels, unifies titles and watermarks and capitalization of words.
> [VDG] Remove redundant captions and labels

- WalletWasabi/Tor/Http/Helpers/HttpMessageHelper.cs
This is an attempt to fix #6870. Not fully as it would deserve but in a reasonable manner.
There are several things to explain:
* "Invalid StatusLine: ?" does not actually mean that we received `?` character from Tor. It only means that a network stream reached its end.
* "Invalid StatusLine: ?" exception can be reproduced on master by simply turning off your Internet connection and waiting a bit. There are probably other ways to get that exception but certainly one scenario is that Tor does not have Internet connectivity and a Tor's stream (connection) fails. Debugging https://github.com/torproject/tor, I think, the sequence is something like this:
* A Tor's OR[^1] connection (let's call it C1) fails. On my machine it is typically …
> Check end of stream in `HttpMessageHelper`.

- WalletWasabi.Fluent/ViewModels/AddWallet/RecoverWalletViewModel.cs
This tends to solve issues in practice. I have a wallet where it was needed and also a user reported it.
> Increase MinGapLimit from 63 to 100 at recovery

- WalletWasabi.Fluent/Views/Settings/BitcoinTabSettingsView.axaml
This feature is half finished. Filter creation on client side is still missing
> Mark FN integration EXPERIMENTAL

- WalletWasabi.Fluent/Views/Wallets/Advanced/WalletStatsView.axaml
> [VDG] [Trivial] Reorder items for wallet stats

- WalletWasabi.Fluent/ViewModels/AddWallet/AddWalletPageViewModel.cs
- WalletWasabi.Fluent/ViewModels/NavBar/NavBarViewModel.cs
> De-select at Privacy Toggle

- WalletWasabi.Fluent/Models/WebcamQrReader.cs
- WalletWasabi.Fluent/Models/Windows/DirectShow.cs
- WalletWasabi.Fluent/Models/Windows/WindowsCapture.cs
https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1416
> Fix CA1416 Validate platform compatibility warnings

- WalletWasabi.Fluent/ViewModels/Wallets/Advanced/WalletStatsViewModel.cs
- WalletWasabi.Fluent/Views/Wallets/Advanced/WalletStatsView.axaml
> [VDG] Wallet Stats copy

- WalletWasabi.Fluent/ViewModels/Login/LoginViewModel.cs
- WalletWasabi.Fluent/Views/Login/LoginView.axaml
Currently, `Forgot Password?` is always displayed at login.
With this PR `Forgot Password?` will become visible after the user inserts an incorrect password.
_(thanks to @soosr for the help)_
> [VDG] Forgot password visible after incorrect password

- WalletWasabi.Fluent/ViewModels/Wallets/Send/LabelSelectionViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Send/PrivacyControlViewModel.cs
Fixes the issue that @yahiheb mentioned on Slack:
```
I am trying to send from a wallet that has a bunch of coins with anonymity set 1 (non private)
In the "Control your privacy" dialog no pocket is in the "Could see this tx" and if I add some pockets and click "Continue"  and comeback again none is in that section.
```
> [VDG] fix logic for `SetUsedLabel()`

- WalletWasabi.Fluent/Views/Wallets/LoadingControl.axaml
> [VDG] [Trivial] Clarify wallet loading text

- WalletWasabi.Fluent/Controls/ContentArea.axaml
- WalletWasabi.Fluent/ViewModels/AddWallet/WelcomePageViewModel.cs
- WalletWasabi.Fluent/Views/AddWallet/WelcomePageView.axaml
> [VDG] Welcome Page Improvements

- WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/PrivacyControlTileViewModel.cs
- warning fixes
- remove obsoleted code
> [VDG] PrivacyControlTile - Cleanup

- WalletWasabi.Fluent.Desktop/WalletWasabi.Fluent.Desktop.csproj
- WalletWasabi.Fluent.Desktop/packages.lock.json
- WalletWasabi.Fluent/WalletWasabi.Fluent.csproj
- WalletWasabi.Fluent/packages.lock.json
unfortunately wasnt able to get this released in time for testnet release.
> use official release of latest avalonia 0.10.13

- WalletWasabi/Helpers/Constants.cs
Add 21.1 & 22.0
https://github.com/bitcoin/bitcoin/releases
> Add latest Bitcoin Core versions to constants

- WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
- Added checks for blame rounds as well.
- Throw if something wrong instead of waiting forever.
- Cleaner code.
> Properly handling blame rounds with checks

- WalletWasabi.Fluent/ViewModels/Wallets/CoinJoinStateViewModel.cs
> [VDG] Trivial: Fix music box TimeSpan format

- WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
- WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
- WalletWasabi/WabiSabi/Client/CoinJoinTracker.cs
We do mark it when the mempool tx gets propagated to us. However sometimes it does not get and that can cause issues. Luckily we know when a CJ is finished successfully so we can mark it already.
> Mark destinations used when CJ successfully finished

- WalletWasabi.Fluent/ViewModels/Wallets/CoinJoinStateViewModel.cs
> [Trivial] [VDG] Add space to separate the amount and unit

- WalletWasabi.Fluent/Controls/BlurBehind.cs
- WalletWasabi.Fluent/Controls/Spectrum/SpectrumControl.cs
This PR fixes some warnings.
Review with white-space changes of https://github.com/zkSNACKs/WalletWasabi/pull/7477/files?diff=unified&w=1
> Use simple using statement

- WalletWasabi.Fluent/Controls/PrivacyContentControl.axaml.cs
- WalletWasabi.Fluent/Helpers/TextHelpers.cs
- WalletWasabi.Fluent/ViewModels/UIConstants.cs
- WalletWasabi.Fluent/ViewModels/Wallets/CoinJoinStateViewModel.cs
> [VDG] Add privacy for Music Box balance

- WalletWasabi.Fluent/ViewModels/Wallets/CoinJoinStateViewModel.cs
It was showing the progress incorrectly in the progress bar
> [VDG] Fix coinjoin autostart progress

- WalletWasabi.Tests/UnitTests/WabiSabi/Models/RoundStateUpdaterTests.cs
- WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
- WalletWasabi/WabiSabi/Client/RoundStateAwaiter.cs
- WalletWasabi/WabiSabi/Client/UnexpectedRoundPhaseException.cs
Solving> https://github.com/zkSNACKs/WalletWasabi/discussions/7424#discussioncomment-2304802
> Do not indicate error on new round creation.

- WalletWasabi.Fluent/Views/Wallets/MusicControlsView.axaml
Fixes the privacy mode properly, using specific controls in the UI
Linked to https://github.com/zkSNACKs/WalletWasabi/pull/7479, previously merged by accident
Thanks @soosr for the suggestion!
> [VDG] Fix Music Box balance privacy mode (alternate fix)

- WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
- WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
- WalletWasabi/WabiSabi/Client/CoinJoinTracker.cs
Those properties are no longer used after #7500
> Remove dead code

- WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
The end time was calculated much later than the phase change. This could lead to the client believing it has time to register, but it was not true, thus missing the timeframe. 
The error depended on the time taken by `ResolveCredentialDependencies` and `StartReissuancesAsync`, so the bigger the wallet the probability of the error increased, and also it was salted with the Poisson distribution. This can be an explanation of what we have encountered on TestNet release day - the more complex the wallet the bigger chance of failing. 
UPDATE!
I was wrong there was no timing at all in that code at output reg and readytosign so it was not possible to have the problem mentioned above. Anyway, this PR ensures the correct behavior. 
https://github.com/zkSNACKs/WalletWasabi/blob/c3883ede11f68c07b92a4 …
> Fixing wrong calculation of Output reg end time

- WalletWasabi.Fluent/Converters/ThicknessConverters.cs
- WalletWasabi.Fluent/Views/MainView.axaml
So elements have the same offset when in full screen.
Fixes #6922
> [VDG] Add margin to adorner canvas

- WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
@nopara73 asked me to do this change to reduce the time from 30s to 10s. For actions after phase change.
> [WabiSabi] Maximum Request Delay set to 10 secs

- WalletWasabi.Tests/Helpers/WabiSabiFactory.cs
- WalletWasabi.Tests/UnitTests/WabiSabi/Integration/Participant.cs
- WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiHttpApiIntegrationTests.cs
- WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
8 min => 1.6 min
Based on https://github.com/zkSNACKs/WalletWasabi/pull/7522
> Quick CoinJoinClient in Tests

- WalletWasabi.Tests/UnitTests/WabiSabi/Backend/AliceTimeoutTests.cs
It seems like this was not trivial... my bad 
Added missing line: https://github.com/zkSNACKs/WalletWasabi/pull/7532
> The test should throw if nothing was throwen

- WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
based on https://github.com/zkSNACKs/WalletWasabi/pull/7533
> Improve CoinJoinClient by extracting Signing Phase related progress

- WalletWasabi.Tests/UnitTests/Wallet/SmartCoinSelectorTests.cs
- WalletWasabi/Blockchain/TransactionBuilding/SmartCoinSelector.cs
Closes #7452 Do not select more coins than strictly necessary.
Ping @MaxHillebrand
> Select a better set of coins

- WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
based on https://github.com/zkSNACKs/WalletWasabi/pull/7533
> Improve CoinJoinClient by extracting Input reg Phase related progress

- WalletWasabi/WabiSabi/Client/WabiSabiHttpApiClient.cs
During the CJ tests, I noticed that the client able to recover from network errors by trying again. This PR is not solving the root of the problem but it will reduce the number of fatal network failures. Also, it will be easier to debug Tor-related problems, by observing if this actually improving the situation or not.
> Try more times before giving up

- WalletWasabi.Fluent/Controls/BlurBehind.cs
- WalletWasabi.Fluent/Controls/Spectrum/SpectrumControl.cs
- WalletWasabi/BitcoinCore/CoreNode.cs
- WalletWasabi/CoinJoin/Client/Clients/CoinJoinClient.cs
- WalletWasabi/Helpers/RuntimeParams.cs
- WalletWasabi/Nito/.editorconfig
Cleaner version of #7531 with some smaller fixes.
Pragma fixes in BlurBehind and SpectrumControl are for the DrawTo and CreateDrawingContext which will be changed later with newer Avalonia version.
The JsonConverter fixes got removed as they will be fixed all in one PR.
> Fluent warning fixes

- WalletWasabi.Fluent/Behaviors/ExecuteCommandOnKeyDownBehavior.cs
- WalletWasabi.Fluent/Views/Wallets/Send/SendFeeView.axaml
> [VDG] Fixed fee slider keyboard behavior

- WalletWasabi/Blockchain/BlockFilters/FilterProcessor.cs
- WalletWasabi/Blockchain/Blocks/SmartHeaderChain.cs
- WalletWasabi/Io/DigestableSafeIoManager.cs
- WalletWasabi/Io/IoManager.cs
- WalletWasabi/Io/SafeIoManager.cs
- WalletWasabi/Stores/IndexStore.cs
These small PR contains small changes that should be non-controversial before attempting to decrease number of IO operations needed to append lines to the mature index.
> Minor changes regarding `IndexStore`

- WalletWasabi.Fluent/Extensions/TransactionSummaryExtension.cs
- WalletWasabi.Fluent/Models/FeeDisplayUnit.cs
- WalletWasabi.Fluent/UiConfig.cs
- WalletWasabi.Fluent/ViewModels/Settings/GeneralSettingsTabViewModel.cs
- WalletWasabi.Fluent/ViewModels/TransactionBroadcasting/BroadcastTransactionViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Home/History/CoinJoinDetailsViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionSummaryViewModel.cs
- WalletWasabi.Fluent/Views/Settings/GeneralSettingsTabView.axaml
> [VDG] Rename Fee display format to Fee display unit

- WalletWasabi.Fluent/ViewModels/HelpAndSupport/AboutViewModel.cs
>  [VDG] [TRIVIAL] Help&Support - FAQ

- WalletWasabi.Fluent/Behaviors/NumberBoxBehavior.cs
- WalletWasabi.Fluent/Behaviors/PasteButtonFlashBehavior.cs
- WalletWasabi.Fluent/Controls/PreviewItem.axaml.cs
- WalletWasabi.Fluent/Extensions/ObservableExtension.cs
- WalletWasabi.Fluent/ViewModels/Dialogs/ShowQrCameraDialogViewModel.cs
- WalletWasabi.Fluent/ViewModels/WalletManagerViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItems/HistoryItemViewModelBase.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Home/History/TransactionDetailsViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/LoadingViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionPreviewViewModel.cs
Based on the discussions here https://github.com/dotnet/reactive/issues/459
> [VDG] Fix non-awaited async calls

- WalletWasabi.Fluent/ViewModels/Wallets/CoinJoinStateViewModel.cs
- WalletWasabi.Fluent/Views/Wallets/MusicControlsView.axaml
fixes https://github.com/zkSNACKs/WalletWasabi/issues/7508
> [VDG] Music box - only show privacy chars when balance is displayed

- WalletWasabi.Fluent/ViewModels/Wallets/Home/History/CoinJoinDetailsViewModel.cs
> [VDG] [TRIVIAL] Coinjoin Details- Coinjoin writing

- WalletWasabi.Fluent/Behaviors/NavBarSelectedIndicatorState.cs
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/6921
> [VDG] do not mark item as selected if cancellation happened

- WalletWasabi.Fluent/Helpers/CurrencyUtils.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/BtcPriceTileViewModel.cs
> [VDG] Make usd price whole number

- WalletWasabi.Fluent/ViewModels/AddWallet/Create/ConfirmRecoveryWordsViewModel.cs
- WalletWasabi.Tests/Helpers/CryptoHelpers.cs
- WalletWasabi.Tests/Helpers/MempoolInfoGenerator.cs
- WalletWasabi.Tests/UnitTests/IoTests.cs
- WalletWasabi.Tests/UnitTests/KeyManagementTests.cs
- WalletWasabi.Tests/UnitTests/Tor/Socks5/Pool/TorHttpPoolTests.cs
- WalletWasabi.Tests/UnitTests/WabiSabi/Client/CredentialDependencyTests.cs
- WalletWasabi.Tests/UnitTests/Wallet/LockTimeSelectorTests.cs
- WalletWasabi/Blockchain/TransactionBuilding/BranchAndBound.cs
- WalletWasabi/CoinJoin/Client/Clients/CoinJoinClient.cs
- WalletWasabi/Extensions/LinqExtensions.cs
- WalletWasabi/WabiSabi/Client/AmountDecomposer.cs
- WalletWasabi/Wallets/LockTimeSelector.cs
Follow up to #7654
See https://github.com/zkSNACKs/WalletWasabi/pull/7654#issuecomment-1082333041 for motivation.
> Replace `new Random()` with `Random.Shared`

- WalletWasabi.Fluent/ZXing/.editorconfig
> More correct `.editorconfig` for `zXing`

- WalletWasabi.Fluent/Views/AddWallet/TermsAndConditionsView.axaml
Handles enter key in the Terms and Conditions screen
Fixes #7689
> [VDG] [Trivial] Terms and Conditions - next on enter key

- WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
Break down of https://github.com/zkSNACKs/WalletWasabi/pull/7663
No modification, just restructuring.
> Improve CoinJoinManager CodeScene score

- WalletWasabi/Helpers/JsonHelpers.cs
- WalletWasabi/Hwi/Parsers/HwiParser.cs
This is #7595 reborn.
363 warnings -> 351 warnings.
> Fix a few warnings in `HwiParser`

- WalletWasabi.Backend/Global.cs
- WalletWasabi.Backend/Startup.cs
Prerequisite for future plans, also a good to have.
> Introduce IDisposable to Backend `Global`

- WalletWasabi.Fluent/ViewModels/Wallets/Send/LabelSelectionViewModel.cs
- WalletWasabi.Tests/UnitTests/UserInterfaceTest/PocketSelectionTests.cs
fixes https://github.com/zkSNACKs/WalletWasabi/pull/7039#pullrequestreview-931889334
It did not find the `LabelViewModel` due to case sensitivity.
> [VDG] Fix case sensitive label issue

- WalletWasabi.Fluent/Controls/DualCurrencyEntryBox.axaml.cs
> [VDG] Fix DualCurrencyInput not properly updating text value

- WalletWasabi.Fluent/Views/SearchBar/SearchBarDropdown.axaml
> [VDG] Hand Cursor for Searchbar dropdown items

- WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionPreviewViewModel.cs
fixes https://github.com/zkSNACKs/WalletWasabi/issues/7732
> [VDG] Improve error message

- WalletWasabi.Fluent.Desktop/packages.lock.json
- WalletWasabi.Fluent/packages.lock.json
- WalletWasabi.Packager/packages.lock.json
- WalletWasabi.Tests/RegressionTests/CoinJoinTests.cs
- WalletWasabi.Tests/UnitTests/JsonConverters/ByteArrayJsonConverterTests.cs
- WalletWasabi.Tests/UnitTests/WabiSabi/JsonConverters/CompactSignatureJsonConverterTests.cs
- WalletWasabi/CoinJoin/Common/Models/InputProofModel.cs
- WalletWasabi/Extensions/NBitcoinExtensions.cs
- WalletWasabi/JsonConverters/CompactSignatureJsonConverter.cs
- WalletWasabi/WalletWasabi.csproj
- WalletWasabi/packages.lock.json
Attempts to move an inch forward #7376 PR
Changes are based on https://github.com/MetacoSA/NBitcoin/commit/48341d508ef306dd7cfc1f50539acbd3b847ba23 commit.
* First commit adds a test 
* Second commit upgrades NBitcoin from version 6 to version 7 and makes sure that serialized data doesn't change (what Lucas proposed)
I don't understand all details here so feedback is certainly welcome
> Update to NBitcoin 7.0.6 (take 2)

- WalletWasabi.Fluent/ViewModels/AddWallet/AddWalletPageViewModel.cs
- WalletWasabi.Fluent/ViewModels/SearchBar/SearchItemProvider.cs
This gives the same UX from SearchBar and NavBar.
Fixes #7770
> [VDG] Add custom logic to display OOBE background on Add Wallet from SearchBar

- WalletWasabi.Fluent/Behaviors/TextBoxAutoSelectTextBehavior.cs
- WalletWasabi.Fluent/ViewModels/SearchBar/SearchBarViewModel.cs
- WalletWasabi.Fluent/Views/SearchBar/SearchBar.axaml
Adds a new behavior that automatically selects the existing text on focus/pointer released
Fixes #7755
> [VDG] Add SearchBar TextBox behavior to select text on focus

- WalletWasabi.Fluent.Desktop/Program.cs
Could not find any usage of Global via locator in codebase.
> [VDG] [Fluent] Don't register Global with locator

- WalletWasabi.Fluent/Views/Wallets/Send/SendView.axaml
Pasting a large chunk of vertical text in the "To" input of the Send View breaks layout.
Master:
This PR:
> [VDG] [Trivial] SendView - To input max height

- WalletWasabi.Fluent/Helpers/CoinPocketHelper.cs
- WalletWasabi.Tests/UnitTests/Transactions/TransactionProcessorTests.cs
fixes https://github.com/zkSNACKs/WalletWasabi/issues/7729
> [VDG] Ignore case during pocket selection

- WalletWasabi.Fluent/Controls/DualCurrencyEntryBox.axaml
> [VDG] Fix missing error message in Dual Currency Input

- WalletWasabi.Fluent/ViewModels/Wallets/Send/LabelSelectionViewModel.cs
- WalletWasabi.Tests/UnitTests/UserInterfaceTest/PocketSelectionTests.cs
closes https://github.com/zkSNACKs/WalletWasabi/issues/7729
fixes https://github.com/zkSNACKs/WalletWasabi/issues/7729#issuecomment-1104515409
The private pocket wasn't taken into account during setting the used labels when it was autoselected.
> [VDG] Take private pocket into account when it was autoselected

- WalletWasabi.Fluent/Views/NavBar/NavBar.axaml
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/7806
> [VDG] Fix flickering button

- WalletWasabi.Fluent/Controls/Dialog.axaml
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/7812
> [VDG] Fix dialog border on full screen

- WalletWasabi.Fluent/ViewModels/Login/LoginViewModel.cs
- WalletWasabi/Wallets/Wallet.cs
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/7766
> Correct password before checking

- WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/CredentialReissuanceTests.cs
- WalletWasabi/WabiSabi/Backend/Rounds/Arena.Partial.cs
- WalletWasabi/WabiSabi/Client/ArenaClient.cs
Continue with https://github.com/zkSNACKs/WalletWasabi/pull/7822
This adds a test and verifies requests in the clien-side ArenaClient too.
> Vsize credentials fix

- WalletWasabi.Tests/Helpers/BitcoinFactory.cs
- WalletWasabi.Tests/UnitTests/BlockchainAnalysis/CoinJoinAnonscoreTests.cs
- WalletWasabi/Blockchain/Analysis/BlockchainAnalyzer.cs
- WalletWasabi/Blockchain/Transactions/SmartTransaction.cs
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/7635
Pair programmed with @andrewkozlik and @onvej-sl.
> Consider sybils for anonymity score calculation

- WalletWasabi.Fluent/Helpers/EnumerableExtensions.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Send/LabelSelectionViewModel.cs
- WalletWasabi.Tests/UnitTests/UserInterfaceTest/PocketSelectionTests.cs
Closes https://github.com/zkSNACKs/WalletWasabi/issues/7729
> [VDG] Improve private pocket autoselection logic

- WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/6884
> Update the list of coins with the successfully registered ones.

- WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
probably missed by https://github.com/zkSNACKs/WalletWasabi/pull/7089
> [TRIVIAL] WabiSabi Client coinjoin writing

- WalletWasabi.Fluent/UiConfig.cs
An idea of a workaround for #7828
> `UiConfig`: Switch from `TaskPoolScheduler` to `MainThreadScheduler`

- WalletWasabi.Fluent.Desktop/WalletWasabi.Fluent.Desktop.csproj
- WalletWasabi.Packager/ArgsProcessor.cs
- WalletWasabi.Packager/Program.cs
This PR is a part of #7778. 
It should be fairly trivial and #7778 should become much smaller.
> `Packager`: Minor changes regarding documentation and minor improvements

- WalletWasabi.Packager/MacSignTools.cs
- WalletWasabi.Packager/Program.cs
Break down of https://github.com/zkSNACKs/WalletWasabi/pull/7778
> [Packager] Use macOS instead of OSX

- WalletWasabi.Packager/ArgsProcessor.cs
- WalletWasabi.Packager/MacSignTools.cs
- WalletWasabi.Packager/Program.cs
Break down of https://github.com/zkSNACKs/WalletWasabi/pull/7778
> [Packager] Add feature to pass appleId in CLI

- WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
Waiting for the blame round was never timed out because the wrong cancellation token was used.
> Waiting for Blame round never times out

- WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
- WalletWasabi/WabiSabi/Backend/Rounds/CoinJoinStorage/CoinJoinTransactionArchiver.cs
missed by https://github.com/zkSNACKs/WalletWasabi/pull/7089
> [TRIVIAL] WabiSabi backend coinjoin writing

- WalletWasabi/Blockchain/Analysis/Clustering/Cluster.cs
- WalletWasabi/WabiSabi/Crypto/WabiSabiClient.cs
> [trivial] Fix warnings and a typo

- WalletWasabi.Tests/UnitTests/Crypto/BlindingTests.cs
This PR follows how NewtonSoft.JSON [actually tests](https://github.com/JamesNK/Newtonsoft.Json/blob/52190a3a3de6ef9a556583cbcb2381073e7197bc/Src/Newtonsoft.Json.Tests/Converters/RegexConverterTests.cs) its converters.
Removes about 14 warnings.
> Fix warnings in blinding tests.

- WalletWasabi.Tests/UnitTests/Crypto/MacTests.cs
- WalletWasabi.Tests/UnitTests/Crypto/ProofSystemTests.cs
- WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/CredentialReissuanceTests.cs
- WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
- WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
Fix some CodeFactor issues in #7837 #7860
> [Trivial] Fix CodeFactor issues

- WalletWasabi.Fluent/ViewModels/Wallets/LoadingViewModel.cs
- WalletWasabi.Fluent/Views/Wallets/LoadingControl.axaml
> [VDG] Add wallet name to Loading screen

- WalletWasabi.Fluent/ViewModels/Wallets/Send/ChangeAvoidanceSuggestionViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Send/PrivacySuggestionsFlyoutViewModel.cs
- WalletWasabi/Services/WasabiSynchronizer.cs
Somewhat similar to #7870
Having dynamic exchange rate can lead to weird BnB results as less/more might not be as expected.
Review with [whitespace off](https://github.com/zkSNACKs/WalletWasabi/pull/7886/files?diff=split&w=1).
> BnB: Do not allow modifying BTC/USD exchange rate during computations

- WalletWasabi.Fluent/ViewModels/SearchBar/Patterns/ComposedKey.cs
- WalletWasabi.Fluent/ViewModels/SearchBar/SearchBarDesignViewModel.cs
- WalletWasabi.Fluent/ViewModels/SearchBar/SearchItems/ActionableItem.cs
- WalletWasabi.Fluent/ViewModels/SearchBar/SearchItems/NonActionableSearchItem.cs
- WalletWasabi.Fluent/ViewModels/Wallets/CoinJoinStateViewModel.cs
- WalletWasabi.Tests/UnitTests/WabiSabi/Models/RoundStateUpdaterTests.cs
Based on #7904. This fixes more CodeFactor issues.
I have just moved the order of some elements.
> [Trivial] Place elements in correct order

- WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
We're coinjoining little amounts a lot. This ensures we're only coinjoining if our largest 3 coinjoinable coins are playing. Otherwise we'd be just wasting users' money.
Note that this code is ugly. Feel free to clean it up. Unfortunately, I have no time for that.
> Do not coinjoin insignificant amounts

- WalletWasabi.Fluent/ViewModels/Wallets/CoinJoinStateViewModel.cs
Fixes https://github.com/zkSNACKs/WalletWasabi/pull/7640#issuecomment-1117529193
> [trivial] Shorten music box message

- WalletWasabi.Fluent/Helpers/NotificationHelpers.cs
Fixes #7898 
Now the self transfer fee is displayed in _sats_ when _sats_ is selected at `Fee display unit` in Settings.
> [VDG] Remove fee from self transfer notifications

- WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
It's been one of the most requested thing so far. Not sure how low we can go with this, but certainly we can go lower than the defaults were.
> Lower min and max non-private UTXO target from 35 to 21 and from 150 to 100

- WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
https://github.com/zkSNACKs/WalletWasabi/pull/7915 introduced the problem of largest amounts getting so much anonymity sets that the wallet will keep "ruining" anonymity in advanced progress "privacy" mode.  
https://github.com/zkSNACKs/WalletWasabi/pull/7928 lowered the coin count, which led to a smaller number of choices for coin selection, which made the issue even worse.  
As it was noted in https://github.com/zkSNACKs/WalletWasabi/pull/7915, the code added there was ugly, so this PR cleans that up at first, but then introduces a cleaner logic that won't fall into the same pitfall as the previous one.
Unfortunately, the issue here is deeper than what this PR fixes. The issue is that our anonymity calculation ruins -rightly so - anonymity sets for consolidations: it always takes the …
> Cleanup coin selection

- WalletWasabi.Fluent/Helpers/TextHelpers.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/WalletBalanceTileViewModel.cs
As discussed in today's meeting.
> [VDG] Remove decimals from Balance Tile fiat amount when >= 10

- WalletWasabi/Extensions/EventHandlerExtensions.cs
- WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
- WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
- WalletWasabi/WabiSabi/Client/CoinJoinProgressEventArgs.cs
- WalletWasabi/WabiSabi/Client/CoinJoinTracker.cs
- WalletWasabi/WabiSabi/Client/Events/CoinJoinStatusEventArgs.cs
Supremacy of 
https://github.com/zkSNACKs/WalletWasabi/pull/7674
https://github.com/zkSNACKs/WalletWasabi/pull/7909
> Let CoinJoinClient communicate using events

- WalletWasabi/WabiSabi/Client/RoundStateAwaiters/RoundStateAwaiter.cs
- WalletWasabi/WabiSabi/Client/RoundStateAwaiters/RoundStateUpdater.cs
This is something that I will need in an upcoming PR. The feature makes general sense as well.
> Add possibility to get latest status of rounds

- WalletWasabi.Fluent/ViewModels/Wallets/CoinJoinStateViewModel.cs
This is a prework for displaying coinjoin phases and their remaining times.
> Musicbox - make countdown reusable

- WalletWasabi.Fluent/ViewModels/Wallets/CoinJoinStateViewModel.cs
- WalletWasabi.Fluent/Views/MainView.axaml
- WalletWasabi/WabiSabi/Client/CoinJoinProgressEvents/CoinJoinProgressEventArgs.cs
- WalletWasabi/WabiSabi/Client/CoinJoinTracker.cs
https://user-images.githubusercontent.com/16554748/167660137-08b654ee-0c95-4873-bb07-3561852bf293.mp4
> [VDG] Music Box - fire like animation in critical phase 

- WalletWasabi.Fluent/ViewModels/ApplicationViewModel.cs
The macOS one looks kinda janky right now, might as well use the same one everywhere :)
cc @danwalmsley
> [VDG] Use the colored version of TrayIcon in all platforms.

- WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
I ve also applied renaming and a small bugfix at finalroundState
> Add timeout for connection confirmation phase as well

- WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
https://github.com/zkSNACKs/WalletWasabi/pull/7962#discussion_r870364095
> [Trivial] Rename CancellationTokenSource variables

- WalletWasabi.Fluent/Views/Wallets/LoadingControl.axaml
> [VDG] [TRIVIAL] Better wallet loading text

- WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryViewModel.cs
Possible fix for
```
2022-05-11 15:04:32.847 [2] DEBUG       Program.TaskScheduler_UnobservedTaskException (180)     System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (Call from invalid thread)
---> System.InvalidOperationException: Call from invalid thread
at Avalonia.Threading.Dispatcher.VerifyAccess() in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 48
at Avalonia.Controls.Primitives.TreeDataGridRowsPresenter.UpdateSelection() in /_/src/Avalonia.Controls.TreeDataGrid/Primitives/TreeDataGridRowsPresenter.cs:line 97
at Avalonia.Controls.Primitives.TreeDataGridRowsPresenter.OnSelectionChanged(Object sender, EventArgs e) in …
```
> [VDG] [Fluent] Set SelectedIndex for TreeDataGrid from UIThread

- WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
https://github.com/zkSNACKs/WalletWasabi/pull/8031#issuecomment-1128688550
> Use Interlocked to prevent multiple invocations

- WalletWasabi/Blockchain/TransactionOutputs/SmartCoin.cs
- WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
- WalletWasabi/WabiSabi/Client/StatusChangedEvents/StatusChangedEventArgs.cs
- WalletWasabi/Wallets/WalletManager.cs
Just filters out the immature coins from selection.
> Do not try to use immature coins for coinjoins

- WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryViewModel.cs
> [VDG] [TRIVIAL] Update CanUserSort

- WalletWasabi.Fluent/ViewModels/Wallets/CoinJoinStateViewModel.cs
fixes https://github.com/zkSNACKs/WalletWasabi/issues/8013
> [VDG] MusicBox - disable indeterminate progressbar when counting has finished

- WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
Fixes https://github.com/zkSNACKs/WalletWasabi/pull/8044
> Fix coin selector bug

- WalletWasabi.Fluent/Styles/TreeDataGrid.axaml
> [VDG] TreeDataGrid - adjust shorticon position

- WalletWasabi.Fluent/Views/SearchBar/SearchBar.axaml
Fix weird SearchBar state when app is maximized and taskbar icon is clicked.
Fixes #7997
> [VDG] Fix weird SearchBar state

- WalletWasabi/Blockchain/Keys/KeyManager.cs
This is missing from https://github.com/zkSNACKs/WalletWasabi/pull/8033
> Recovered wallet must be synchronized

- WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
- WalletWasabi/WabiSabi/LoggerTools.cs
With this PR the messages are yellow, not red. These errors are usually not permanent and solved by retrying more. For example, the current one is coming from I do not have enough confirmed coins.
> Make cj log better

- WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
> [WabiSabi] Do not try to register uneconomical inputs

- WalletWasabi.Fluent/Behaviors/SearchBarBehavior.cs
This PR fixes https://github.com/zkSNACKs/WalletWasabi/issues/7752:
In Windows 10, if you click the Wasabi icon in the Windows Taskbar while the SearchBar results popup is visible, the popup becomes "disconnected", where it should be hidden.
> [VDG] Fix SearchBar Flyout that stays open-misplaced on taskbar click (Win10)

- WalletWasabi.Fluent.Desktop/Program.cs
- WalletWasabi/Services/Terminate/TerminateService.cs
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/8020
> [VDG] Fix termination threading issue

- WalletWasabi.Fluent/ViewModels/Wallets/Advanced/WalletCoins/WalletCoinsViewModel.cs
To have icon displayed when sorting. 
I´ve also added a `MaxWidth` to the Labels Column, otherwise it would sometimes overlap with the scrollbar.
https://user-images.githubusercontent.com/93143998/169514067-587c2f89-d30a-4d15-b4d4-04c89aa876d5.mp4
https://user-images.githubusercontent.com/93143998/169513563-328cde46-e9ce-493f-9d9d-67df2ca42852.mp4
> [VDG] Wallet Coins - Increase Anonymity Score column width

- WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
- WalletWasabi/WabiSabi/Client/StatusChangedEvents/StatusChangedEventArgs.cs
In this PR I am adding the notification that will stop the mixing in Manual CoinJoin mode. 
The code only contains the notification, later in next PRs the state machine will command stop to the CoinJoinManager.
> Report AllCoinsPrivate

- WalletWasabi.Fluent/Controls/PreviewItem.axaml
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/8012
> [VDG] Fix margins in PreviewItem

- WalletWasabi.Fluent/Views/NavBar/NavBar.axaml
> [VDG] Adjust status indicator margin

- WalletWasabi.Fluent/Behaviors/SearchBarBehavior.cs
> [VDG] Set IsSearchPanelOpen flag in Show/Hide Flyout

- WalletWasabi.Fluent/Views/Wallets/MusicControlsView.axaml
This is an attempt to improve colors in MusicBox.
Current:
This PR:
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/8000
@zkSNACKs/visual-design-group
> [VDG] Improve MusicBox colors

- WalletWasabi.Fluent/ViewModels/MainViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModel.cs
- WalletWasabi.Fluent/Views/Shell/MainView.axaml
- WalletWasabi.Fluent/Views/Wallets/MusicControlsView.axaml
https://github.com/zkSNACKs/WalletWasabi/pull/8097#issuecomment-1134457334
> [VDG] Don't use Oaph

- NuGet.Config
- WalletWasabi.Fluent.Desktop/packages.lock.json
- WalletWasabi.Fluent/Views/MainWindow.axaml
- WalletWasabi.Fluent/WalletWasabi.Fluent.csproj
- WalletWasabi.Fluent/packages.lock.json
Fixes #7878
Fixes #7553
Workaround https://github.com/zkSNACKs/WalletWasabi/commit/3a22d9052777078845a84a98560feaba9a7140ea is no longer needed.
> [VDG] Update Avalonia.Controls.TreeDataGrid to version 0.10.14

- WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
The result of pair programming in the research club.
> Consolidate more heavily

- WalletWasabi.Fluent/Views/Wallets/Home/History/Details/CoinJoinDetailsView.axaml
- WalletWasabi.Fluent/Views/Wallets/Home/History/Details/CoinJoinsDetailsView.axaml
> [VDG] Copy coinjoin fee in sats

- WalletWasabi.Fluent/ViewModels/Wallets/CoinJoinStateViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModel.cs
- WalletWasabi.Fluent/Views/Wallets/MusicControlsView.axaml
- WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
- WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
- WalletWasabi/WabiSabi/Client/CoinJoinTracker.cs
- WalletWasabi/WabiSabi/Client/RoundStateAwaiters/NoCoinsToMixException.cs
- WalletWasabi/WabiSabi/Client/StatusChangedEvents/WalletStartedCoinJoinEventArgs.cs
- WalletWasabi/WabiSabi/Client/StatusChangedEvents/WalletStoppedCoinJoinEventArgs.cs
- WalletWasabi/Wallets/Wallet.cs
Continuation of https://github.com/zkSNACKs/WalletWasabi/pull/8112
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/8032
> Refactoring musicbox

- WalletWasabi.Fluent/Config.cs
- WalletWasabi/Helpers/Constants.cs
Elaborated on this as well https://github.com/zkSNACKs/WalletWasabi/projects/31
Currently:
DefaultPlebStopThreshold = Money.Coins(0.001m);
> Bump Internal Main v1.99.1

- WalletWasabi.Fluent/Behaviors/SearchBarBehavior.cs
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/7897
> [VDG] Make SearchBar handle window resize correctly

- WalletWasabi/Services/SleepInhibitor.cs
- WalletWasabi/Tor/Socks5/TorTcpConnectionFactory.cs
> Add Win10+ checks

- WalletWasabi.Fluent/Views/Wallets/Home/History/Details/TransactionDetailsView.axaml
> [VDG] Privacy mode Amount Transaction Details

- WalletWasabi/WabiSabi/Backend/Models/WrongPhaseException.cs
In case the round ended we use the ending time to calculate how late it arrived.
Closes #8153
> Late requests after round ended.

- WalletWasabi.Fluent/Views/Wallets/Home/History/Details/TransactionDetailsView.axaml
> [trivial] tx details - Amount instead of Incoming amount

- WalletWasabi.Fluent/ViewModels/Wallets/CoinJoinStateViewModel.cs
- WalletWasabi.Fluent/Views/Wallets/MusicControlsView.axaml
During refactoring, we broke them.
cc @zkSNACKs/visual-design-group for review.
> [VDG] MusicBox - fix indicators

- WalletWasabi/WabiSabi/Backend/WabiSabiConfig.cs
I was not able to change the xpub, with this I will be able to.
> Make CoordinatorExtPubKey writable

- WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
Please read https://github.com/zkSNACKs/WalletWasabi/issues/8171 in order to get context. I think this is not a solution but I agreed to implement it during team meeting so, here it is.
It would be good if you can provide feedback. IMO we should identify the problem as clearly as possible and work on the identified problem.
> Sign all but one input in case inconsistent coordinator.

- WalletWasabi.Fluent/Views/Wallets/Receive/ReceiveAddressView.axaml
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/8244
> [VDG] Receive - label is not visible fix

- WalletWasabi.Fluent.Desktop/Extensions/AppBuilderExtension.cs
- WalletWasabi.Fluent.Desktop/Program.cs
- WalletWasabi.Fluent/Services.cs
- WalletWasabi/Blockchain/Analysis/BlockchainAnalyzer.cs
... to avoid issues with accessing uninitialized `MainViewModel`.
Alternative to #8190
Testing: Could anybody make sure that avalonia's designer is OK with this change?
> [VDG] Check two instances sooner

- WalletWasabi.Fluent/Controls/TileButton.axaml
for consistency with other dialogs like `Add Wallet`
> [VDG] [trivial] Handcursor tx broadcaster

- WalletWasabi.Tests/UnitTests/Transactions/TransactionProcessorTests.cs
- WalletWasabi/Blockchain/TransactionProcessing/TransactionProcessor.cs
This PR prevents tiny outputs under the dust attack prevention threshold to be treat as dust when the we are the senders (for example when we receive small change after spending or when the output comes from a coinjoin in which we have participated).
> Solve problem with small denominations in change.

- WalletWasabi.Fluent/ViewModels/Wallets/Labels/SuggestionLabelsViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Receive/AddressLabelEditViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Receive/ReceiveAddressesViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Receive/ReceiveViewModel.cs
- WalletWasabi.Fluent/Views/Wallets/Receive/AddressLabelEditView.axaml
> [VDG] Receive Address - Edit Label - Suggestions

- WalletWasabi.Fluent/Views/CoinJoinProfiles/CoinJoinProfilesView.axaml
> [VDG] CoinjoinProfile drop shadow clip fix

- WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModelBase.cs
fixes https://github.com/zkSNACKs/WalletWasabi/issues/8259
> [VDG] Fix wallet ordering

- WalletWasabi.Fluent.Desktop/Program.cs
- WalletWasabi.Fluent/ApplicationStateManager.cs
- WalletWasabi.Fluent/Services.cs
fixes https://github.com/zkSNACKs/WalletWasabi/issues/8252
ping @zkSNACKs/visual-design-group for review.
> [VDG] Bring Wasabi front on the second start

- WalletWasabi/Rpc/JsonRpcServer.cs
Closes https://github.com/zkSNACKs/WalletWasabi/issues/8207 by allowing anonymous users.
> Allow unauthenticated access to RPC

- WalletWasabi.Fluent/Controls/HistoryPlaceholderPanel.axaml
- WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryViewModel.cs
> [VDG] [TRIVIAL] Fix history placeholder column widths

- WalletWasabi.Fluent/Views/SearchBar/SearchBarDropdown.axaml
Should fix #8289 
cc @molnard @soosr
> [VDG] Remove the Icon workaround on Search Bar

- WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryViewModel.cs
fixes https://github.com/zkSNACKs/WalletWasabi/issues/8164
> [VDG] Fix ordering of history list

- WalletWasabi.Fluent/Views/SearchBar/SearchBarDropdown.axaml
The Panel is no longer needed. 
*Rendering should be slightly faster :)*
> [VDG] Simplify layout for SearchBar dropdown results (icon)

- WalletWasabi.Fluent/Views/Dialogs/ManualCoinJoinProfileDialogView.axaml
> [trivial] unify manualCJprofile & settings

- WalletWasabi.Fluent/Views/AddWallet/Create/RecoveryWordsView.axaml
> Recovery Words - caption text

- WalletWasabi.Backend/Global.cs
- WalletWasabi.Tests/UnitTests/WabiSabi/Backend/ConfigTests.cs
- WalletWasabi.Tests/UnitTests/WabiSabi/Backend/CoordinatorTests.cs
- WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiApiApplicationFactory.cs
- WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiHttpApiIntegrationTests.cs
- WalletWasabi/Tor/Http/Extensions/HttpResponseMessageExtensions.cs
- WalletWasabi/WabiSabi/Backend/Statistics/CoinJoinScriptStore.cs
- WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
- WalletWasabi/WabiSabi/Client/DependencyGraphTaskScheduler.cs
- WalletWasabi/WabiSabi/Client/WabiSabiHttpApiClient.cs
- WalletWasabi/WabiSabi/LoggerTools.cs
- WalletWasabi/WabiSabi/WabiSabiCoordinator.cs
Reverts zkSNACKs/WalletWasabi#8237
The PR is not only broken but also shows problems a problem in `Arena` that needs to be fixed and that is why even when #8237 is wrong the tests pass.
> Revert "[WabiSabi] Do not reveal common ownership in case of errors"

- WalletWasabi.Fluent/Behaviors/PasteButtonFlashBehavior.cs
- WalletWasabi.Fluent/Helpers/WalletHelpers.cs
- WalletWasabi.Fluent/ViewModels/Dialogs/LabelEntryDialogViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Labels/SuggestionLabelsViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Receive/AddressLabelEditViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Receive/ReceiveViewModel.cs
- WalletWasabi/Blockchain/Keys/KeyManager.cs
- WalletWasabi/Blockchain/Transactions/AllTransactionStore.cs
This PR introduces time dimension for suggestions: not only frequency, but also recency counts. (Not perfect implementation.)
This PR introduces wallet dimension for suggestions: not only frequency, but also the wallet it was called from also counts. (Not perfect implementation.)
Hopefully the suggestions are somewhat useful now.
This PR also fixes a critical crash on send when null was returned from the clipboard.
> Make suggestions hopefully useful

- WalletWasabi.Fluent/ViewModels/Wallets/Send/SendViewModel.cs
fixes https://github.com/zkSNACKs/WalletWasabi/issues/8312
> [VDG] Fix double paste address

- WalletWasabi.Fluent/Controls/QuestionControl.axaml
It worked the order way around.
> [VDG] Fix `QuestionControl` highlight button

- WalletWasabi.Fluent/ViewModels/Wallets/Send/PrivacySuggestionsFlyoutViewModel.cs
Fixes: https://github.com/zkSNACKs/WalletWasabi/issues/8336
> Bnb Input count limiting

- WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
In some situations the client doesn't sign all but one of the registered inputs and in those cases it should participate in the blame round only with those Alices that signed the failing round.
This PR contains commits that are also in #8334 and for that reason that PR should be merged before this one.
> Participate in blame round with signers only

- WalletWasabi.Fluent/Helpers/CoinHelpers.cs
- WalletWasabi.Fluent/Helpers/CoinPocketHelper.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Send/LabelSelectionViewModel.cs
- WalletWasabi.Tests/UnitTests/Transactions/TransactionProcessorTests.cs
- WalletWasabi.Tests/UnitTests/UserInterfaceTest/PocketSelectionTests.cs
Closes https://github.com/zkSNACKs/WalletWasabi/issues/8306
We discussed the issue with @nopara73 and agreed introducing the semi private pockets can solve it.
Good luck to understand the PR... I tried to add many tests to cover every case...
- Coins that participated in CJ but didn't reach the threshold yet will be in the Semi-Private pocket.
- Semi-private pocket handled silently in the background
This PR makes it totally clear, that a lot of logic should be moved to the SmartCoinSelector, this can be a future plan.
> [VDG] Semi private pocket

- WalletWasabi.Fluent/ViewModels/Wallets/Advanced/WalletStatsViewModel.cs
- WalletWasabi.Fluent/Views/Wallets/Advanced/WalletStatsView.axaml
- WalletWasabi.Tests/UnitTests/KeyManagementTests.cs
- WalletWasabi/Blockchain/Keys/KeyManager.cs
> Add key stats for wallet stats

- WalletWasabi.Fluent/ViewModels/Wallets/Advanced/WalletInfoViewModel.cs
- WalletWasabi.Fluent/Views/Wallets/Advanced/WalletInfoView.axaml
Tempfix for release. Disable OutputDescriptors for WatchOnly wallets.
> [VDG][TempFix] Make WalletInfo usable for WatchOnly wallets

- WalletWasabi.Fluent/Views/Wallets/Send/SendView.axaml
Somehow the scrollbars are showing up in the address textbox of SendView. This PR disables those and fixes #8314
cc @molnard @zkSNACKs/visual-design-group
> [VDG] Disable scrollviewer scrollbars in the send address textbox

- WalletWasabi.Fluent/ViewModels/AddWallet/RecoverWalletViewModel.cs
> Move FilePath setting in RecoverWalletViewModel

- WalletWasabi.Fluent/Controls/Spectrum/SpectrumControl.cs
Reduces cpu and gpu usage significantly
> Use very small texture for Aura

- WalletWasabi/Helpers/Constants.cs
- WalletWasabi/Legal/Assets/LegalDocumentsWw2.txt
Do not care with the left side of the docs, it was just a placeholder content. 
Easier to see the document here: https://github.com/zkSNACKs/WalletWasabi/blob/ww2legal/WalletWasabi/Legal/Assets/LegalDocumentsWw2.txt
You can only make comments in the Files changed section
> Update WW2 legal docs

- WalletWasabi/Legal/Assets/LegalDocumentsWw2.txt
> WW2 Legal docs small typo

- WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
> Improve backend log a bit

- WalletWasabi.Backend/wwwroot/index.html
- WalletWasabi.Backend/wwwroot/onion-index.html
`Privacy Policy` in the footer forwards you to a non-existing file.
Sorry about the format changes, it was not intended.
@CAnorbo
> Fix LegalDocs link in website

- WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
The client aborted the process in case of errors during IR or CC.
> [Fix] Registration halt

- WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
- WalletWasabi/WabiSabi/Backend/Rounds/Round.cs
- WalletWasabi/WabiSabi/Backend/Rounds/TimeFrame.cs
Resolves https://github.com/zkSNACKs/WalletWasabi/issues/8422
> Add buffer times

- WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
- WalletWasabi/WabiSabi/Backend/Rounds/Round.cs
- WalletWasabi/WabiSabi/Backend/Rounds/TimeFrame.cs
We thought previously we couldn't achieve this, but by tracking a bug I realized all we need to do to get into blame here to send NotAllAlicesSign.
> Send NotAllAlicesSign so people get into blame round

- WalletWasabi/WabiSabi/Backend/Rounds/TimeFrame.cs
This is as conservative as it gets. We seem to only have problem with output reg, so let's only buffer there.
> Add buffer for output reg

- WalletWasabi.Documentation/ClientDeployment.md
Related: https://github.com/zkSNACKs/WalletWasabi/issues/8420
> Never release during a Tor network disruption

- WalletWasabi/Tor/Socks5/Pool/Circuits/DefaultCircuit.cs
- WalletWasabi/Tor/Socks5/Pool/Circuits/ICircuit.cs
- WalletWasabi/Tor/Socks5/Pool/Circuits/PersonCircuit.cs
- WalletWasabi/Tor/Socks5/Pool/TorHttpPool.cs
- WalletWasabi/Tor/TorMonitor.cs
- WalletWasabi/WabiSabi/Client/WabiSabiHttpApiClient.cs
> TorHttpPool: Split lock to allow concurrent Tor circuits creation [dev 2.0.1]

- WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
Fixes: #8446
Not the best solution, but this is what I could come up with.
If someone has a better solution to this, please close this PR or tell me about it.
> Decrease input reg available time, so the clients hurry up.

- WalletWasabi/Tor/Http/TorHttpClient.cs
- WalletWasabi/Tor/TorMonitor.cs
> `TorMonitor`: Verify using software-versions API [dev 2.0.1]

- .editorconfig
This is a part of #8476 
Credits to @SuperJMN. I have just extracted it as it is a standalone change.
> `.editorconfig`: Insert final newline to all files

- WalletWasabi/WabiSabi/Client/AliceClient.cs
Close https://github.com/zkSNACKs/WalletWasabi/issues/8477
This PR should be review after https://github.com/zkSNACKs/WalletWasabi/pull/8489 is merged because it is a continuation of that one.
> Do not unregister wrong phase

- WalletWasabi/WabiSabi/Client/AliceClient.cs
- WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
Review without whitespaces https://github.com/zkSNACKs/WalletWasabi/pull/8512/files?w=1
> Try fix tokens around registration

- WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
Thus making WW2.0.1 clients prefer different rounds from WW2.0.0 clients.
This PR is the last piece to facilitate a graceful migration strategy from to WW2.0.1, described here: https://github.com/zkSNACKs/WalletWasabi/pull/8517#issuecomment-1166252712
> Make WW2.0.0 client most preferred round to be the last

- WalletWasabi.Backend/wwwroot/index.html
- WalletWasabi.Backend/wwwroot/onion-index.html
> 2.0.1 download links

- WalletWasabi.Fluent/ViewModels/AddWallet/HardwareWallet/ConnectHardwareWalletViewModel.cs
- WalletWasabi.Fluent/Views/AddWallet/HardwareWallet/ConnectHardwareWalletView.axaml
- No one expects that it will open a web page in the browser.
- Some users only open links in Tor, this didn't support it.
- It opened documentation for 1.0, makes no sense.
> [VDG] Remove hyperlink from add HW wallet

- WalletWasabi.Fluent/ViewModels/Dialogs/ShowQrCameraDialogViewModel.cs
- WalletWasabi.Fluent/ViewModels/Navigation/RoutableViewModel.cs
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/8519
ping @zkSNACKs/visual-design-group for review.
> [VDG] Display error in compact dialog if it happened there

- WalletWasabi.Fluent/Extensions/TransactionSummaryExtension.cs
- WalletWasabi.Fluent/Helpers/CoinHelpers.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Advanced/WalletCoins/WalletCoinViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Home/History/Details/TransactionDetailsViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItems/CoinJoinHistoryItemViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItems/HistoryItemViewModelBase.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItems/TransactionHistoryItemViewModel.cs
- WalletWasabi.Fluent/Views/Wallets/Advanced/WalletCoins/Columns/IndicatorsColumnView.axaml
- WalletWasabi.Fluent/Views/Wallets/Home/History/Columns/IndicatorsColumnView.axaml
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/8210
@zkSNACKs/visual-design-group review
> [VDG] add confirmation numbers

- WalletWasabi.Fluent/ViewModels/Wallets/Advanced/WalletCoins/WalletCoinsViewModel.cs
Sorts coins by amount (descending).
Fixes #8205
> [VDG] Sort coins in Coin List by amount

- WalletWasabi.Backend/wwwroot/index.html
- WalletWasabi.Backend/wwwroot/onion-index.html
> Clarify a sentence in website text.

- WalletWasabi.Fluent/Views/Settings/BitcoinTabSettingsView.axaml
- WalletWasabi.Fluent/Views/Wallets/WalletSettingsView.axaml
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/3485
Check dust threshold in settings or automatic CJ threshold in wallet settings.
@zkSNACKs/visual-design-group review
> [VDG] limit btc value decimals

- WalletWasabi.Tests/UnitTests/WabiSabi/Backend/AliceTimeoutTests.cs
Follow-up to https://github.com/zkSNACKs/WalletWasabi/pull/8489#discussion_r904725917
> Tests: AliceTimeoutTests - minor improvements

- WalletWasabi.Backend/Controllers/WabiSabiController.cs
- WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
- WalletWasabi/WabiSabi/Backend/Statistics/RequestTimeStatista.cs
Singleton pattern was taken from here: https://csharpindepth.com/articles/singleton
> Measure arena period as well

- WalletWasabi.Fluent/Controls/CurrencyEntryBox.axaml.cs
This PR allows users to enter a dot "." to enter "0.".
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/8575
> [VDG] Add implicit zero for decimal numbers

- WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/8523
> Bias random coin selection towards larger amounts

- WalletWasabi.Fluent/ViewModels/CoinJoinProfiles/CoinJoinProfileViewModelBase.cs
- WalletWasabi.Fluent/ViewModels/CoinJoinProfiles/PrivateCoinJoinProfileViewModel.cs
- WalletWasabi.Fluent/ViewModels/Dialogs/ManualCoinJoinProfileDialogViewModel.cs
Addresses: https://github.com/zkSNACKs/WalletWasabi/pull/8522#pullrequestreview-1029876420
> Update CoinJoinProfile equalities + remove redundant code

- WalletWasabi.Tests/UnitTests/Tor/Socks5/TorTcpConnectionFactoryTests.cs
- WalletWasabi/Tor/Socks5/TorTcpConnectionFactory.cs
Fixes #8513
There should be no visible effect of this PR.
> Use `NoAuthenticationRequired` for DefaultCircuit

- WalletWasabi.Fluent.Desktop/WalletWasabi.Fluent.Desktop.csproj
- WalletWasabi.Fluent.Desktop/packages.lock.json
- WalletWasabi.Fluent/WalletWasabi.Fluent.csproj
- WalletWasabi.Fluent/packages.lock.json
- fixes https://github.com/zkSNACKs/WalletWasabi/issues/8385
- Should improve a bit perf when switching wallets with large amount of transaction
https://github.com/AvaloniaUI/Avalonia/compare/0.10.15...0.10.16
Some other notable fixes:
- Random rare crash in deferred renderer
- smoother resizing on linux
- reduce cpu usage during layout passes (noticeable on resize)
- mac os issues with window positioning and sizing on load.
- mac os, shadow on popups that was not there before
- some other perf improvements.
> [VDG] Update to Avalonia 0.10.16

- WalletWasabi.Fluent/Views/Wallets/Advanced/WalletStatsView.axaml
> [VDG] wallet stats lowercase writing

- WalletWasabi/Tor/TorProcessManager.cs
- WalletWasabi/Tor/TorSettings.cs
Fixes #8630
Repro: https://github.com/zkSNACKs/WalletWasabi/issues/8630#issuecomment-1179525904
@adamPetho Could you please try this PR if it solves the issue for you on macOS? If I understand the issue well, it should. 🤞
> [draft] macOS: Tor control failed to initialize

- WalletWasabi.Fluent/Views/Dialogs/ManualCoinJoinProfileDialogView.axaml
> [VDG] tooltip coinjoin time preference

- WalletWasabi.Fluent/Helpers/ConfirmationTimeLabel.cs
- WalletWasabi.Fluent/Helpers/TimeSpanFormatter.cs
- WalletWasabi.Fluent/Views/Wallets/Send/SendFeeView.axaml
fixes https://github.com/zkSNACKs/WalletWasabi/issues/8694
> [VDG] Fee Slider - full labels

- WalletWasabi.Fluent/Behaviors/WindowSizeBehavior.cs
- WalletWasabi.Fluent/UiConfig.cs
- WalletWasabi.Fluent/Views/MainWindow.axaml
Lite version of https://github.com/zkSNACKs/WalletWasabi/pull/7526 with some additional fixes.
Expected behavior:
1. Fallback mechanism
- It is the current behavior on master, meaning we let Avalonia choose the window size and position.
2. Window width and height are stored in the UI config.
3. The stored values will be applied if they are valid.
- The values are valid if the desired window size fits the screen.
~~- Scaling is taken into account.~~
- If the values are not valid or don't exist, the fallback mechanism will happen.
4. The window position will be always centralized.
> [VDG] Remember window size

- WalletWasabi.Fluent/ViewModels/Wallets/Receive/ReceiveAddressViewModel.cs
> [VDG] hww not connected text wording

- WalletWasabi.Fluent/Helpers/ConfirmationTimeLabel.cs
> [VDG] Fee Chart - Fix labels plural form

- WalletWasabi.Fluent/ViewModels/Wallets/Advanced/WalletCoins/WalletCoinsViewModel.cs
- WalletWasabi.Fluent/Views/Wallets/Advanced/WalletCoins/WalletCoinsView.axaml
Small change to improve the observable pipeline using Dynamic Data.
> [VDG] Simplify AnySelected in Coins List

- WalletWasabi.Fluent/Views/Wallets/Advanced/WalletCoins/Columns/IndicatorsColumnView.axaml
> [VDG] lowercase writing not coinjoining tooltip

- WalletWasabi.Fluent/Controls/CurrencyEntryBox.axaml.cs
> [VDG] CurrencyEntryBox - fix divide by zero crash

- WalletWasabi.Fluent/Controls/DualCurrencyEntryBox.axaml
- WalletWasabi.Fluent/Controls/DualCurrencyEntryBox.axaml.cs
> [VDG] Fix DualCurrencyEntryBox bug when ConversionRate is zero

- WalletWasabi.Fluent/Extensions/DynamicDataMixin.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Advanced/WalletCoins/WalletCoinsViewModel.cs
- WalletWasabi.Fluent/Views/Wallets/Advanced/WalletCoins/WalletCoinsView.axaml
This PR is a full revision of the Coin List to mitigate some problems.
It's also and improvement to make it fit better to reactive programming. 
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/8744
> [VDG] Improve Coin List

- WalletWasabi/Helpers/Constants.cs
Add version 23.0
https://github.com/bitcoin/bitcoin/releases
Review with whitespace changes off: https://github.com/zkSNACKs/WalletWasabi/pull/8826/files?diff=split&w=1
> [Trivial] Add latest Bitcoin Core version to Constants.UserAgents

- WalletWasabi.Fluent/Helpers/TransactionHelpers.cs
> Display user friendly exception message

- WalletWasabi.Fluent/Global.cs
- WalletWasabi/Services/UpdateManager.cs
Addresses comment [here](https://github.com/zkSNACKs/WalletWasabi/pull/8741#discussion_r935606143).
> Introduce CancellationToken to UpdateManager

- WalletWasabi.Fluent/ViewModels/Wallets/Advanced/WalletCoins/WalletCoinViewModel.cs
> [VDG] Show formatted "until" date for banned coins

- WalletWasabi.Fluent/ViewModels/AddWallet/Create/ConfirmRecoveryWordsViewModel.cs
- WalletWasabi.Fluent/ViewModels/AddWallet/Create/RecoveryWordsViewModel.cs
- WalletWasabi.Fluent/ViewModels/AddWallet/WalletNamePageViewModel.cs
- WalletWasabi/Blockchain/Keys/KeyManager.cs
- WalletWasabi/Blockchain/Keys/WalletGenerator.cs
Fixes #6930
Closes https://github.com/zkSNACKs/WalletWasabi/issues/6294
Match the UX that most bitcoin wallets and hardware wallets has where user has to confirm and save the seed words before setting a password.
cc @nopara73 @zkSNACKs/visual-design-group
> [VDG] Change the wallet creation ux to set the password later

- WalletWasabi/Backend/Models/FilterModel.cs
> More user friendly error message for Invalid Hex String error

- WalletWasabi.Tests/IntegrationTests/TorTests.cs
- WalletWasabi.Tests/UnitTests/Tor/TorProcessManagerTests.cs
- WalletWasabi/Tor/Control/TorControlClientFactory.cs
- WalletWasabi/Tor/Control/Utils/TcpClientConnector.cs
- WalletWasabi/Tor/Http/TorHttpClient.cs
- WalletWasabi/Tor/Socks5/Pool/TorHttpPool.cs
- WalletWasabi/Tor/Socks5/TcpClientSocks5Connector.cs
- WalletWasabi/Tor/Socks5/TorTcpConnectionFactory.cs
- WalletWasabi/Tor/TcpClientConnector.cs
- WalletWasabi/Tor/TorMonitor.cs
- WalletWasabi/Tor/TorProcessManager.cs
- WalletWasabi/Tor/TorSettings.cs
- WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
- WalletWasabi/WabiSabi/Client/CoinJoinTrackerFactory.cs
- WalletWasabi/Wallets/IWallet.cs
- WalletWasabi/Wallets/Wallet.cs
Resolve conflicts of and closes https://github.com/zkSNACKs/WalletWasabi/pull/8851
> Fixup Support DnsEndpoint for Tor

- WalletWasabi.Fluent/ViewModels/Wallets/CoinJoinSettingsViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/WalletSettingsViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModel.cs
Regression introduced in https://github.com/zkSNACKs/WalletWasabi/pull/8849
Fixes #8889.
> [VDG] Update % when AnonScore changes in CJ settings

- WalletWasabi.Fluent/ViewModels/Wallets/Advanced/WalletCoins/WalletCoinsViewModel.cs
- WalletWasabi.Fluent/Views/Wallets/Advanced/WalletCoins/WalletCoinsView.axaml
No longer need to use RxUI ObservableAsPropertyHelper.
> [VDG] Remove OAPH from Coin List

- WalletWasabi.Fluent/Controls/LabelControl.axaml
- WalletWasabi.Fluent/Controls/LabelsListBox.axaml
> [VDG] Fix scrolling issues with mouse wheel in UTXO list (and other lists) when labels are under mouse

- WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
A possible solution to this https://github.com/zkSNACKs/WalletWasabi/issues/8544
CancellationToken coming from CoinJoinManager only triggered by CoinJoinTracker.Stop. For example when the user pressed the Stop button or the software exit. 
The CancellationToken mentioned above is now linked with a timeout as well. The timeout is added when the CoinJoinClient has found a round and the timeout interval is set according to the sum of the timeouts in the round.
> Add total timeout for one coinjoin round

- WalletWasabi.Tests/UnitTests/BlockchainAnalysis/PubKeyReuseAnonScoreTests.cs
- WalletWasabi.Tests/UnitTests/Transactions/SmartTransactionTests.cs
- WalletWasabi/Blockchain/Analysis/BlockchainAnalyzer.cs
- WalletWasabi/Blockchain/TransactionOutputs/WalletVirtualInput.cs
- WalletWasabi/Blockchain/TransactionOutputs/WalletVirtualOutput.cs
- WalletWasabi/Blockchain/Transactions/SmartTransaction.cs
Co-authored by @onvej-sl, progression of https://github.com/zkSNACKs/WalletWasabi/pull/7932
Covers https://github.com/zkSNACKs/WalletWasabi/pull/7932/commits/4e27681c2a8b3d98a7b209d2f178b4948f7e39e5
> Use virtual wallet input and outputs concepts

- WalletWasabi.Tests/Helpers/AnalyzedTransaction/AnalyzedTransaction.cs
- WalletWasabi.Tests/Helpers/AnalyzedTransaction/ForeignOutput.cs
- WalletWasabi.Tests/Helpers/AnalyzedTransaction/WalletOutput.cs
- WalletWasabi.Tests/UnitTests/BlockchainAnalysis/CoinJoinAnonscoreTests.cs
- WalletWasabi/Blockchain/Analysis/BlockchainAnalyzer.cs
- WalletWasabi/Blockchain/Analysis/CoinjoinAnalyzer.cs
- WalletWasabi/Blockchain/TransactionOutputs/WalletVirtualInput.cs
This PR builds on top of https://github.com/zkSNACKs/WalletWasabi/pull/8932.
Closes https://github.com/zkSNACKs/WalletWasabi/pull/7932/
Closes https://github.com/zkSNACKs/WalletWasabi/pull/7841
Closes https://github.com/zkSNACKs/WalletWasabi/issues/7635
Closes https://github.com/zkSNACKs/WalletWasabi/issues/7913
Closes https://github.com/zkSNACKs/WalletWasabi/pull/8099
Closes https://github.com/zkSNACKs/WalletWasabi/issues/8051
> Anonymity improvement tests

- WalletWasabi.Tests/Helpers/AnalyzedTransaction/AnalyzedTransaction.cs
- WalletWasabi.Tests/Helpers/AnalyzedTransaction/ForeignOutput.cs
- WalletWasabi.Tests/Helpers/AnalyzedTransaction/WalletOutput.cs
- WalletWasabi.Tests/UnitTests/BlockchainAnalysis/CoinJoinAnonscoreTests.cs
- WalletWasabi/Blockchain/Analysis/BlockchainAnalyzer.cs
- WalletWasabi/Blockchain/Analysis/CoinjoinAnalyzer.cs
- WalletWasabi/Blockchain/TransactionOutputs/WalletVirtualInput.cs
Co-authored with @onvej-sl and @andrewkozlik
Closes https://github.com/zkSNACKs/WalletWasabi/pull/7932/
Closes https://github.com/zkSNACKs/WalletWasabi/pull/7841
Closes https://github.com/zkSNACKs/WalletWasabi/issues/7635
Closes https://github.com/zkSNACKs/WalletWasabi/issues/7913
Closes https://github.com/zkSNACKs/WalletWasabi/pull/8099
Closes https://github.com/zkSNACKs/WalletWasabi/issues/8051
> Improvement of anonymity computation

- WalletWasabi.Fluent.Desktop/WalletWasabi.Fluent.Desktop.csproj
- WalletWasabi.Fluent.Desktop/packages.lock.json
- WalletWasabi.Fluent/WalletWasabi.Fluent.csproj
- WalletWasabi.Fluent/packages.lock.json
> Update to Avalonia 0.10.18

- WalletWasabi.Fluent/Rpc/WasabiJsonRpcService.cs
It's makes possible to pass a password for "Login" into the wallet before starting a cj.
> Add password parameter

- WalletWasabi.Fluent/Views/TransactionBroadcasting/LoadTransactionView.axaml
> [VDG] tx broadcast caption text

- WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/ReadyToSignRequestRequestTests.cs
- WalletWasabi/WabiSabi/Models/ReadyToSignRequestRequest.cs
> Fix namespace of `ReadyToSignRequestRequest`

- WalletWasabi.Fluent/ViewModels/Wallets/Send/SendViewModel.cs
> [VDG] SendViewModel - fix reentrance problem in TryParseUrl()

- WalletWasabi.Fluent/Controls/DualCurrencyEntryBox.axaml
> [VDG] DualCurrencyEntryBox - small layout correction for readonly style

- WalletWasabi/Blockchain/Keys/KeyManager.cs
> Tiny changes to clean the `KeyManager`

- WalletWasabi.Fluent/Behaviors/PasteButtonFlashBehavior.cs
> [VDG] Send - fix paste button flashing after pasting PayJoin address

- WalletWasabi.Backend/Global.cs
- WalletWasabi.Backend/InitConfigStartupTask.cs
- WalletWasabi.Backend/Startup.cs
Reverts zkSNACKs/WalletWasabi#8100
> Revert "Fix warnings in Backend project (take 2)"

- README.md
Addresses the first point in #8973
The command clones only the master branch.
> [Trivial] Edit command for faster cloning of the repo (README.md)

- WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionPreviewViewModel.cs
Fixes error at Send
```
ERROR TransactionPreviewViewModel.OnConfirmAsync (457) System.ObjectDisposedException: The CancellationTokenSource has been disposed. at System.Threading.CancellationTokenSource.Cancel() at WalletWasabi.Fluent.ViewModels.Wallets.Send.TransactionPreviewViewModel.OnConfirmAsync() in WalletWasabi.Fluent\ViewModels\Wallets\Send\TransactionPreviewViewModel.cs:line 452
```
> Check if cts is disposed

- WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
- WalletWasabi/WabiSabi/LoggerTools.cs
> Log on Trace level when every coin is mixed

- WalletWasabi.Backend/Controllers/BlockchainController.cs
- WalletWasabi.Tests/UnitTests/AllFeeEstimateTests.cs
- WalletWasabi.Tests/UnitTests/BitcoinCore/RpcBasedTests.cs
- WalletWasabi/BitcoinCore/CoreNode.cs
- WalletWasabi/BitcoinCore/Monitoring/RpcFeeProvider.cs
- WalletWasabi/BitcoinCore/Monitoring/RpcMonitor.cs
- WalletWasabi/CoinJoin/Client/CoinJoinProcessor.cs
- WalletWasabi/Extensions/RPCClientExtensions.cs
- WalletWasabi/WabiSabi/Backend/Statistics/CoinJoinFeeRateStatStore.cs
> Fix namespace of `RPCClientExtensions`

- WalletWasabi/Blockchain/Keys/KeyManager.cs
Implemented the reviews for https://github.com/zkSNACKs/WalletWasabi/pull/8994. Closes https://github.com/zkSNACKs/WalletWasabi/pull/8994
> Act on reviews of 8994

- WalletWasabi.Backend/Global.cs
- WalletWasabi.Backend/InitConfigStartupTask.cs
- WalletWasabi.Backend/Startup.cs
Fixes #8100 which had issues and was reverted for that reason #9027.
> Fix warnings in Backend project (take 3) 

- WalletWasabi.Fluent/Global.cs
- WalletWasabi.Fluent/Models/Windows/DirectShow.cs
- WalletWasabi.Fluent/ViewModels/Dialogs/ShowQrCameraDialogViewModel.cs
- WalletWasabi.Fluent/ViewModels/StatusIcon/StatusIconViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/CoinJoinStateViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModelBase.cs
- WalletWasabi.Tests/UnitTests/WabiSabi/Integration/IWebHostBuilderExtensions.cs
- WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiApiApplicationFactory.cs
- WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiHttpApiIntegrationTests.cs
This is just some core refactoring.
> [Trivial] Use expression body for lambda expressions

- WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/9039
On the backend side, we are not banning the input just response to the error. 
https://github.com/zkSNACKs/WalletWasabi/blob/master/WalletWasabi/WabiSabi/Backend/Rounds/Arena.Partial.cs#L302
> Bypass WitnessAlreadyProvided exception

- WalletWasabi.Fluent/ViewModels/Wallets/CoinJoinStateViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModel.cs
Hide MusicBox when wallet is private
> [VDG] Hide MusicBox when wallet is private

- WalletWasabi.Fluent/Views/CoinJoinProfiles/CoinJoinProfilesView.axaml
small improvement for noobs
also for consistency with the docs
> [trivial] improve coinjoin strategy text a bit

- WalletWasabi.Tests/IntegrationTests/LiveServerTests.cs
- WalletWasabi/WebClients/Wasabi/WasabiClient.cs
Follow-up to https://github.com/zkSNACKs/WalletWasabi/pull/9034#discussion_r959525170
> Remove unused `GetExchangeRateAsync` method

- WalletWasabi/Blockchain/TransactionOutputs/CoinsRegistry.cs
- WalletWasabi/Blockchain/TransactionOutputs/SmartCoin.cs
- WalletWasabi/Blockchain/Transactions/SmartTransaction.cs
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/8877
@wieslawsoltes takes this PR over
> Fix tx processing

- WalletWasabi.Fluent/ViewModels/Wallets/Advanced/WalletCoins/WalletCoinViewModel.cs
current is causing a lot of confusion and causes custodial nerves to newbs :D
PR
> [VDG] clarify coinjoin ban tooltip

- WalletWasabi.Tests/UnitTests/WabiSabi/Client/CredentialDependencyTests.cs
- WalletWasabi/WabiSabi/Client/CredentialDependencies/DependencyGraph.cs
- WalletWasabi/WabiSabi/Client/WabiSabiHttpApiClient.cs
[Here](https://github.com/zkSNACKs/WalletWasabi/blob/45a1aa5ecefba8d6ff4699f67496663c2530eeb6/WalletWasabi/WabiSabi/Client/WabiSabiHttpApiClient.cs#L88-L96) we mention `action` too.
> [trivial] `WabiSabiHttpApiClient`: Add info about action

- WalletWasabi.Fluent.Desktop/Extensions/AppBuilderExtension.cs
Superseeds https://github.com/zkSNACKs/WalletWasabi/pull/9118
> [VDG] Fix Avalonia previewer

- WalletWasabi.Backend/Global.cs
- WalletWasabi.Tests/UnitTests/WabiSabi/Backend/CoinVerifierTests.cs
- WalletWasabi/WabiSabi/Backend/Banning/CoinVerifier.cs
- WalletWasabi/WabiSabi/Backend/WabiSabiConfig.cs
> Put flags into the Config file

- WalletWasabi/Tor/Socks5/Pool/TorHttpPool.cs
- WalletWasabi/Tor/Socks5/TorTcpConnectionFactory.cs
- WalletWasabi/Tor/TorMonitor.cs
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/8513#issuecomment-1250937778
> Fix `SocketException`s being thrown when using `DefaultCircuit`

- WalletWasabi.Fluent/Views/Wallets/Home/History/Details/CoinJoinsDetailsView.axaml
nit
to match the rest, like tx details and wallet statistics
> [VDG] [trivial] lowercase writing in cj details

- WalletWasabi.Tests/UnitTests/LinqExtensionsTests.cs
> Make sure the test CombinationsWithoutRepetition can finish on CI

- WalletWasabi.Fluent/ViewModels/CoinJoinProfiles/CoinJoinProfilesViewModel.cs
- WalletWasabi.Fluent/ViewModels/Dialogs/ManualCoinJoinProfileDialogViewModel.cs
- WalletWasabi.Fluent/Views/Dialogs/ManualCoinJoinProfileDialogView.axaml
> [VDG] Remove Automatically start coinjoin toggle from the coinjoin profile settings

- WalletWasabi.Fluent/CrashReport/CrashReporter.cs
- WalletWasabi.Fluent/ViewModels/AddWallet/AddWalletPageViewModel.cs
- WalletWasabi.Fluent/ViewModels/AddWallet/WalletNamePageViewModel.cs
- WalletWasabi.Fluent/ViewModels/TransactionBroadcasting/BroadcastTransactionViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/HardwareWalletViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Receive/ReceiveAddressViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionPreviewViewModel.cs
- WalletWasabi.Tests/UnitTests/SerializableExceptionTests.cs
- WalletWasabi/Bases/PeriodicRunner.cs
- WalletWasabi/Extensions/ExceptionExtensions.cs
- WalletWasabi/Services/Terminate/TerminateService.cs
> Fix namespace for `ExceptionExtensions`

- WalletWasabi.Backend/Global.cs
- WalletWasabi/JsonConverters/DefaultValueIntegerArrayAttribute.cs
- WalletWasabi/JsonConverters/IntegerArrayJsonConverter.cs
- WalletWasabi/WabiSabi/Backend/WabiSabiConfig.cs
Supersedes https://github.com/zkSNACKs/WalletWasabi/pull/9167
> Use explicit json converter for Risk flags

- WalletWasabi.Packager/scripts/Wasabi_release.ps1
Related with https://github.com/zkSNACKs/WalletWasabi/pull/9121
> Use vs2022 for building the MSI

- WalletWasabi.Fluent/ViewModels/Wallets/Send/LabelSelectionViewModel.cs
- WalletWasabi.Tests/UnitTests/UserInterfaceTest/PocketSelectionTests.cs
part of https://github.com/zkSNACKs/WalletWasabi/issues/9184
> [VDG] Fix `TryGetBestKnownByRecipientPockets`

- WalletWasabi/CoinJoin/Coordinator/Rounds/CoordinatorRound.cs
This is the real fix https://github.com/zkSNACKs/WalletWasabi/pull/9196
> ToArray to not have collection modified error

- .github/ISSUE_TEMPLATE/bug-report.md
fixes #9175
updates the issue template to 2.0
> remove old version command from issue template

- WalletWasabi.Tests/UnitTests/Clients/SingleInstanceCheckerTests.cs
- WalletWasabi/Services/SingleInstanceChecker.cs
> [Fix CI] Increase SingleInstanceChecker timeouts for CI

- WalletWasabi/WabiSabi/Client/ArenaClient.cs
- WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
Follow-up to https://github.com/zkSNACKs/WalletWasabi/pull/8827#issuecomment-1229177664
With #9020 merged, we should see whether we have fixed all the issues that we worked around with #8846.
To validate that this is a good idea, we should:
1. Test this PR as all other PRs
2. Run the same experiment as we did here #8870
> Revert "[Tor] Experiment no.1"

- WalletWasabi.Fluent/ViewModels/Wallets/CoinJoinStateViewModel.cs
This PR removes some messages from the music box.
Connection confirmation, output reg, signing phase will have the same message `Coinjoin in progress` and the timer is also adjusted as a phase finished.
> [VDG] MusicBox - simplify messages
