WalletWasabi/WalletWasabi

WalletWasabi.Tests/UnitTests/Hwi/HwiBinaryHashesTests.cs
WalletWasabi/Helpers/Constants.cs

This release fixes Trezor T on device passphrase entry issue. https://github.com/bitcoin-core/HWI/pull/495
All the [HWI unit tests](https://github.com/zkSNACKs/WalletWasabi/tree/master/WalletWasabi.Tests/UnitTests/Hwi) pass.
The Trezor T Kata doesn't pass, error:
```
Message: 
WalletWasabi.Hwi.Exceptions.HwiException : No path supplied matched device keys
Stack Trace: 
HwiClient.ThrowIfError(String responseString, IEnumerable`1 options, String arguments, Int32 exitCode) line 284
HwiClient.SendCommandAsync(IEnumerable`1 options, Nullable`1 command, String commandArguments, Boolean openConsole, CancellationToken cancel, Boolean isRecursion, Action`1 standardInputWriter) line 52
HwiClient.DisplayAddressImplAsync(Nullable`1 deviceType, String devicePath, Nullable`1 fingerprint, KeyPath …
```

Update HWI to 2.0.1

---

WalletWasabi.Tests/AcceptanceTests/HwiKatas.cs

We cannot use the old static readonly DefaultAccountKeyPath in KeyManager, because the new firmware expects a longer keypath.I introduced two local keypath for the Trezor T kata only, either this or make two more public static readonly field in KeyManager.
The first refuse action where we expected an exception got deleted because with the new firmware there is no way to cancel or decline a Display Address action only "confirm", so no exception will be thrown by user action (maybe if we plug the device out in the meantime, but that's not ideal).

Trezor T Kata fix for TestNet

---

WalletWasabi.Backend/Global.cs

Fixing this log message when starting the backend:
`2021-03-31 10:20:42 [13] INFO   Global (96)     Chaumian CoinJoin Coordinator is successfully initialized and started two new rounds.`

Fix backend log message "two rounds"

---

WalletWasabi.Gui/Tabs/WalletManager/RecoverWallets/RecoverWalletViewModel.cs

The new backport introduced a silly bug. Users cannot recover their wallets entirely. 
The bug was made by me. It is getting hard to cherry-pick the changes from the master, the diff is too big. I did it manually on the last 3 releases because cherry-pick was impossible caused the number of conflicts. The backport is still on .NET Core 3.1.
Next week there will be another backport release with this fix.

[Backport] Fix recovery recovery word bug

---

WalletWasabi.Tests/UnitTests/WabiSabi/Client/ArenaClientTests.cs
WalletWasabi/WabiSabi/Crypto/WabiSabiClient.cs

Allow to inject the `CredentialPool` in `WabiSabiClient` to make it stateless and allow higher level clients use the credentials as they please.

Inject `CredentialPool`

---

WalletWasabi.Tests/UnitTests/WabiSabi/Client/ArenaClientTests.cs
WalletWasabi/WabiSabi/Client/ArenaClient.cs

`ArenaClient` creates its `WabiSabiClient` instances because higher level abstractions should know nothing about this low-level crypto clients.

[WabiSabi] `ArenaClient` creates `WabiSabiClient`s

---

WalletWasabi.Gui/Global.cs

closes https://github.com/zkSNACKs/WalletWasabi/pull/5496
If our internal data structures in the Bitcoin Store gets corrupted, then it's better to rescan all the wallets.

Autorescan wallets when internal data structure corrups.

---

WalletWasabi.Fluent/Controls/Dialog.axaml.cs

This adds delay for dialog EnableCancelOnPressed  feature to eliminate accidental dialog closing on double-click event.

[Fluent] Add delay for EnableCancelOnPressed dialog feature

---

WalletWasabi.Tests/RegressionTests/CoinJoinTests.cs
WalletWasabi/CoinJoin/Coordinator/Rounds/CoordinatorRound.cs
WalletWasabi/Extensions/RPCClientExtensions.cs
WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs

When the developer is in regtest mode and runnign the bitcoin core, there was an exception showing up continiously, saying the estimationfee cannot be calculated. I just added an if expression in CreateRoundAsync, and it seems it solved this issue
closes https://github.com/zkSNACKs/WalletWasabi/issues/5494

The estimation fee doesnt show anymore in Regtest

---

WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/ConfirmConnectionTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/CredentialTests.cs
WalletWasabi/WabiSabi/Backend/PostRequests/InputRegistrationHandler.cs
WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
WalletWasabi/WabiSabi/Crypto/CredentialIssuer.cs

Because we are now using two credential issuers, `HandleRequest` means the effects of one credential request will be applied before the other is validated.
This PR modifies the arena request flow to first prepare handling of both kinds of credential requests, and then commit them after both have been validated by splitting `HandleRequest` into `PrepareRequest` and a delegate with no arguments, `CommitRequest`.

[WabiSabi] Split `CredentialIssuer.HandleRequest` into two phases

---

WalletWasabi.Fluent/ViewModels/Wallets/Send/PrivacyControlViewModel.cs
WalletWasabi.Fluent/ViewModels/Wallets/Send/SendViewModel.cs
WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionInfo.cs

Do not store the default `Unlabelled Funds` and `Private Funds` as if the user was typed them in when selecting a pocket.

[Fluent] Do not store default labels

---

WalletWasabi.Fluent/Controls/ResponsivePanel.cs

Fixes IDE1006 (Naming rule violation) error/warning for Item struct used in ResponsivePanel

[Fluent] [Trivial] Fix naming rule violation in ResponsivePanel

---

WalletWasabi/WabiSabi/Backend/PostRequests/InputRegistrationHandler.cs
WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
WalletWasabi/WabiSabi/Crypto/CredentialIssuer.cs
WalletWasabi/WabiSabi/Crypto/ICommitableCredentialsResponse.cs

This is the first attempt to eliminate the use of a `delegate` in `CredentialIssuer` by a more OOP approach: https://github.com/zkSNACKs/WalletWasabi/pull/5504#issuecomment-811957428

[WabiSabi] Remove delegate from `CredentialIssuer`

---

WalletWasabi.Tests/UnitTests/WabiSabi/Client/AliceClientTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Client/ArenaClientTests.cs
WalletWasabi/WabiSabi/Client/ArenaClient.cs

> `ArenaClient` has to be private as in `AliceClient`. Anyway, clients have to create their own `ArenaClient` instances because the `IRequestHandler` is different for Alice, Bod and Satoshi. What the all share is the `CredentialPool`.

[WabiSabi] Inject CredentialPool into ArenaClient

---

WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterInputFailureTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterInputSuccessTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RemoveInputTests.cs
WalletWasabi/WabiSabi/Backend/Models/WabiSabiProtocolErrorCode.cs
WalletWasabi/WabiSabi/Backend/PostRequests/InputRegistrationHandler.cs
WalletWasabi/WabiSabi/Backend/Rounds/Round.cs
WalletWasabi/WabiSabi/Backend/Rounds/RoundParameters.cs
WalletWasabi/WabiSabi/Backend/WabiSabiConfig.cs

I decided to leave the `AddAlice` refactor for a later since keeping track of the allocated weight as a computed property based on `Alices.Count` resolved the tension of keeping the integer in sync with the collection, it's best done as part of #5531, which can also address a TODO comment this PR introduces.
Continuation of #5487.
Fixes #5438.

[WabiSabi] Constrain registration vsize

---

WalletWasabi/WabiSabi/Backend/PostRequests/InputRegistrationHandler.cs

This method simplifies code that removes the duplicated alices by flattering the hierarchical structure as:
| Round | Alice | Outpoint |
|----------|--------|-------------|
| r1        | a1    | o1  |
| r1        | a1    | o2  |
| r1        | a2    | ox  |
| r1        | a2    | oy  |
After that it filters the table by outpoint that belong to the specified alice.

[WabiSabi] Simplify `RemoveDuplicatedAlices` method

---

WalletWasabi.Tests/UnitTests/WabiSabi/Backend/ConfigTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Backend/CoordinatorTests.cs

There is a NRE when you run WabiSabi UTs. This is the third time I fix this exact same error in less than a month so, we should find a way to make the UT to fail when something bad happens inside a PeriodicRunner instead of continue silently (even when that's what we want in production). See also:
- https://github.com/zkSNACKs/WalletWasabi/pull/5519
- https://github.com/zkSNACKs/WalletWasabi/pull/5366
Any idea?

[WabiSabi] Fix NRE in UTs

---

WalletWasabi.Backend/Controllers/BatchController.cs
WalletWasabi.Backend/Controllers/ChaumianCoinJoinController.cs
WalletWasabi/CoinJoin/Coordinator/Coordinator.cs

I think the problem is that sometimes the response are awaiting for the `CoinJoinsLock`. I made sure it doesn't do that anymore.
I think it's either this or the exchange rate stuff that blocks the response.
Related https://github.com/zkSNACKs/WalletWasabi/issues/5071

Fix backend micro unresponsiveness

---

WalletWasabi.Tests/UnitTests/Crypto/ProofSystemTests.cs
WalletWasabi.Tests/UnitTests/Crypto/ZeroKnowledge/KnowledgeOfRepTests.cs
WalletWasabi.Tests/UnitTests/Crypto/ZeroKnowledge/LinearRelationTests.cs
WalletWasabi/Crypto/ZeroKnowledge/LinearRelation/Equation.cs
WalletWasabi/Crypto/ZeroKnowledge/LinearRelation/Knowledge.cs

Commit 5ba9b54c0971c264aa0160c8401c15db5fab417c changed the prover side
to only verify its own proofs in debug builds, since these checks are
very expensive for range proofs.
This means that the tests fail in release builds, since an exception is
not thrown (reported by @kiminuo).
This change removes the automatic self checking altogether and makes the
check method unconditional so that it can be called explicitly in tests
or in code that uses the prover.
Allowing the prover to create invalid proofs is perhaps not as misuse
resistant as it could be, but this makes it possible for the tests to
confirm that the verifier rejects such invalid proofs without
duplicating the prover code or manually constructing invalid range
proofs in the tests, and it is more important for the security of the …

[WabiSabi] Fix range proof tests in Release builds

---

azure-pipelines-linux.yml

This makes it possible to run HWI in CI again to avoid:
```
Error loading Python lib '/tmp/_MEIwuJ4Gx/libpython3.6m.so.1.0': dlopen: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /tmp/_MEIwuJ4Gx/libpython3.6m.so.1.0)
```

Bump Linux CI from Ubuntu 16.04 to 20.04.

---

WalletWasabi.Fluent/Controls/PreviewItem.axaml
WalletWasabi.Fluent/Controls/PreviewItem.axaml.cs
WalletWasabi.Fluent/Views/Wallets/Home/History/TransactionDetailsView.axaml

https://github.com/zkSNACKs/WalletWasabi/pull/5599#pullrequestreview-637698621
This PR adds a copy button to the `PreviewItem` control, thus if the control's `CopyParameter` is set to something, the user will be able to copy that.
https://user-images.githubusercontent.com/16364053/115374163-dc847280-a1cc-11eb-815a-251b8a542cd3.mp4

[Fluent] Add copy button to `PreviewItem`

---

WalletWasabi.Tests/Helpers/WabiSabiFactory.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Backend/AliceTimeoutTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepInputRegistrationTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepOutputRegistrationTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepTransactionSigningTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterInputFailureTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterInputSuccessTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterInputToBlameRoundTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterOutputTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/SignTransactionTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Client/AliceClientTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Client/ArenaClientTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Client/BobClientTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Models/MultipartyTransactionTests.cs
WalletWasabi/WabiSabi/Backend/Banning/Prison.cs
WalletWasabi/WabiSabi/Backend/Models/Alice.cs
WalletWasabi/WabiSabi/Backend/PostRequests/ArenaRequestHandler.cs
WalletWasabi/WabiSabi/Backend/PostRequests/IArenaRequestHandler.cs
WalletWasabi/WabiSabi/Backend/PostRequests/InputRegistrationHandler.cs
WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
WalletWasabi/WabiSabi/Backend/Rounds/Round.cs
WalletWasabi/WabiSabi/Backend/Rounds/RoundParameters.cs
WalletWasabi/WabiSabi/Client/AliceClient.cs
WalletWasabi/WabiSabi/Client/ArenaClient.cs
WalletWasabi/WabiSabi/Models/InputRegistrationRequest.cs
WalletWasabi/WabiSabi/Models/InputRegistrationResponse.cs
WalletWasabi/WabiSabi/Models/InputRoundSignaturePair.cs

As discussed in last week's call, this PR removes support for multiple inputs because it is a premature optimization that is slowing down progress.
TODO

[WabiSabi] Allow only one input per alice for now

---

WalletWasabi.Fluent/ViewModels/WalletManagerViewModel.cs

This fixed bug that resurfaced after updated to Avalonia 0.10.2 (it is actually present in 0.10.0 if you strip down the xaml in NavBar, but for some reason was mitigated by something else).

[Fluent] [Trivial] Set SelectedWallet after it is added to SelectedWallets collection

---

WalletWasabi.Tests/IntegrationTests/BlockstreamInfoTests.cs
WalletWasabi/WebClients/BlockstreamInfo/BlockstreamInfoClient.cs
WalletWasabi/WebClients/Wasabi/HttpClientFactory.cs

@nopara73 Is this what you wanted to achieve?
PS: An alternative and nicer (imo) way would be to pass `IHttpClient` to `BlockstreamInfoClient` but then 
```csharp
using HttpResponseMessage response = await HttpClient.SendAsync(HttpMethod.Get, "api/fee-estimates", null, cancel).ConfigureAwait(false);
```
would be something like:
```csharp
using HttpRequestMessage request = new(HttpMethod.Get, new Uri(baseUri, "api/fee-estimates"));
using HttpResponseMessage response = await HttpClient.SendAsync(request, cancel).ConfigureAwait(false);
```
I'm not sure if you would like to use absolute URIs.
Related to #5591

[draft] BlockstreamInfoClient with HttpClientFactory

---

WalletWasabi.Backend/Controllers/BlockchainController.cs
WalletWasabi.Tests/UnitTests/AllFeeEstimateTests.cs
WalletWasabi.Tests/UnitTests/BitcoinCore/RpcBasedTests.cs
WalletWasabi.Tests/UnitTests/MockRpcClient.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Backend/ConfigTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Backend/CoordinatorTests.cs
WalletWasabi/BitcoinCore/Monitoring/RpcFeeProvider.cs
WalletWasabi/BitcoinCore/Rpc/CachedRpcClient.cs
WalletWasabi/BitcoinCore/Rpc/IRPCClient.cs
WalletWasabi/BitcoinCore/Rpc/RpcClientBase.cs
WalletWasabi/Extensions/RPCClientExtensions.cs

This PR makes the EstimateAllFee method cancellable with CancelationToken.
**Note:** 
I did not use this CancelationToken so far, so please tell me if the token should go deeper into the separate functions or if the token should be an optional  parameter for the method or this is completely wrong and this is not the way it should be used.

Make RPC EstimateAllFee cancellable

---

WalletWasabi/WebClients/Wasabi/HttpClientFactory.cs

This PR adds missing dispose call for `TorHttpPool`. 
This is part of #5681 where I noticed that.

Dispose TorHttpPool in HttpClientFactory.

---

WalletWasabi/Microservices/Binaries/lin64/Tor/LICENSE
WalletWasabi/Microservices/Binaries/osx64/Tor/LICENSE
WalletWasabi/Microservices/Binaries/win64/Tor/LICENSE

https://2019.www.torproject.org/docs/faq.html.en#DistributingTor mentions that 
> However, if you want to redistribute the Tor software you must follow our LICENSE. Essentially this means that you need to include our LICENSE file along with whatever part of the Tor software you're distributing. 
This PR adds the license file to all Tor distribution folders. It duplicates the file but on the other hand when WW is installed, you will see the file where it is expected. There is an alternative solution, to put the Tor license file in https://github.com/zkSNACKs/WalletWasabi/tree/master/WalletWasabi/Legal/Assets. I'm not sure which solution is better. Especially, I did not want to introduce any new step in Packager project not to introduce new complexity.
I tested that …

Tor: Add LICENSE file

---

WalletWasabi.Gui/Global.cs
WalletWasabi/Tor/TorMonitor.cs
WalletWasabi/Tor/TorProcessManager.cs

This PR should be safe because it just makes potential waiting in `StartAsync` shorter if cancel is requested. 
This is part of #5681 where I noticed that.

TorProcessManager: Add cancellation token to `StartAsync`.

---

WalletWasabi/Tor/Socks5/Pool/TorHttpPool.cs

This PR is a cosmetics one. Cancelling an HTTP request does not require printing stacktrace in logs (when TRACE level is on) as it is not an exceptional state and nothing wrong happened.
This is part of #5681.

TorHttpPool: Add logs for OperationCanceledException.

---

WalletWasabi.Tests/UnitTests/Hwi/MockedDeviceTests.cs

Variable was never used and had a `Nullable value type may be null` warning attached to it.

Remove unused variable in MockedDeviceTests

---

WalletWasabi.Tests/UnitTests/Tor/Control/Messages/ProtocolInfoReplyTests.cs
WalletWasabi.Tests/UnitTests/Tor/Control/PipeWriterExtensions.cs
WalletWasabi.Tests/UnitTests/Tor/Control/TorControlReplyReaderTests.cs
WalletWasabi/Tor/Control/Exceptions/TorControlException.cs
WalletWasabi/Tor/Control/Exceptions/TorControlReplyParseException.cs
WalletWasabi/Tor/Control/Messages/ProtocolInfoReply.cs
WalletWasabi/Tor/Control/Messages/TorControlReply.cs
WalletWasabi/Tor/Control/PipeReaderLineReaderExtension.cs
WalletWasabi/Tor/Control/ReplyCode.cs
WalletWasabi/Tor/Control/TorControlReplyReader.cs
WalletWasabi/Tor/Control/Utils/Tokenizer.cs

This PR attempts to get merged subset of changes from #5681.
This PR introduces parsing capability for Tor control replies:
* `WalletWasabi.Tor.Control.TorControlReplyReader` is supposed to read raw text data received (line by line) from Tor and return a `TorControlReply` data object.
* `WalletWasabi.Tor.Control.Utils.Tokenizer` is used as a helper class.
* `WalletWasabi.Tor.Control.Messages.ProtocolInfoReply` which gives user friendly version of `TorControlReply` for `PROTOCOLINFO 1` command.
* In general, this PR attempts to be quite strictly spec-compatible. The rationale is to avoid a scenarion like this: Tor implementation changes, our code breaks, yet the Tor implementation change is valid according to Tor spec.
The PR takes advantage of `System.IO.Pipelines` API and not …

Tor control: Add Tokenizer and TorControlReplyReader.

---

WalletWasabi/Gma/QrCodeNet/Encoding/DataEncodation/DataEncode.cs
WalletWasabi/Gma/QrCodeNet/Encoding/DataEncodation/EncodationStruct.cs

The ```BitList DataCodewords``` could be easily added in the constructor of ```EncodationStruct```, and thus lets us remove the ```this()``` call, as all fields are declared in the constructor already.

Refactor EncodationStruct

---

azure-pipelines-linux.yml
azure-pipelines-osx.yml

This uses the native cobertura output as described in
WalletWasabi.Documentation/CodeCoverage.md.
The `PublishCodeCoverageResults` azure pipeline task is able to generate HTML
from cobertura reports, which can be viewed in the pipeline task. For the report
generation to work `PathMap` needs to be disabled when generating the coverage
outputs.
On Windows coverage data is generated and can be downloaded for use with visual
studio, but I haven't found a way of generating HTML reports easily, so this is
not included for now.

Produce coverage reports in Linux & OSX Azure pipelines

---

WalletWasabi.Fluent/ViewModels/Wallets/Receive/ReceiveAddressViewModel.cs
WalletWasabi.Gui/ViewModels/AddressViewModel.cs

[BIP 173](https://github.com/bitcoin/bips/blob/master/bip-0173.mediawiki#bech32) subsection Uppercase/lowercase says:
> For presentation, lowercase is usually preferable, but inside QR codes
> uppercase SHOULD be used, as those permit the use of alphanumeric
> mode, which is 45% more compact than the normal byte mode.

Uppercase QR encoded bech32 addresses

---

WalletWasabi/Wallets/CachedBlockProvider.cs
WalletWasabi/Wallets/FileSystemBlockRepository.cs
WalletWasabi/Wallets/IRepository.cs

- In ```CachedBlockProvider``` we had to make sure that the ```Block``` is nullable, as it is okay if it gets back null, we make sure to have an acceptable value in the next line anyhow.
- In ```FileSystemBlockRepository``` we had to make the Block in ```Task<Block>``` nullable for the same reason before. (To achive that correctly, we had to change the original interface's function in ```IRepository``` to accept null)
- Also at line 224 we gave ```FilePath``` a discard variable to remove the warning "it is not used anywhere".

Remove warnings related to FileSystemBlockRepository

---

WalletWasabi/Wallets/CachedBlockProvider.cs
WalletWasabi/Wallets/FileSystemBlockRepository.cs
WalletWasabi/Wallets/IRepository.cs

As @nopara73 mentioned [here](https://github.com/zkSNACKs/WalletWasabi/pull/5744/files#r626394991), ```TryGetAsync``` would be a better name, as it reflects that it returns null in case the block was not found.

Rename GetAsync related to IRepository

---

WalletWasabi.Fluent/Controls/Dialog.axaml.cs

Before this, when a dialog was opened and I clicked on the maximized/minimized button on the top right, the window state has changed and the dialog got closed.
The dialog won't close from now.

[Fluent] Fix dialog closing when changing window state

---

WalletWasabi.Gui/Controls/ExtendedTextBox.cs

Making `_pasteItem` nullable as it accepts null.

Fix null warning

---

WalletWasabi/JsonConverters/BitcoinAddressJsonConverter.cs

If `string.IsNullOrWhiteSpace(bitcoinAddressString)` gives back true, we return `default`, which in case of an object is null, so this should be nullable as well.

Resolve null warning in BitcoinAddressJsonConverter.cs

---

WalletWasabi.Gui/Global.cs
WalletWasabi.Tests/RegressionTests/BuildTests.cs
WalletWasabi.Tests/RegressionTests/CoinJoinTests.cs
WalletWasabi.Tests/RegressionTests/SendTests.cs
WalletWasabi.Tests/RegressionTests/WalletTests.cs
WalletWasabi/Blockchain/BlockFilters/FilterProcessor.cs
WalletWasabi/Services/WasabiSynchronizer.cs

Fixes https://github.com/zkSNACKs/WalletWasabi/issues/5785
Drawback: It's slower because now we are waiting for the FilterProcessor to finish processing the filters before we'd make our next request to the synchronizer.

Move FilterProcessor inside the Synchronizer

---

WalletWasabi.Tests/UnitTests/Transactions/TransactionFactoryTests.cs

#5784 made `SelectSameClusterCoinsAsync()` synchronous, so the Async suffix should be removed.

[Trivial] Remove Async prefix from method

---

WalletWasabi/JsonConverters/FilterModelJsonConverter.cs
WalletWasabi/JsonConverters/KeyJsonConverter.cs
WalletWasabi/JsonConverters/NetworkJsonConverter.cs
WalletWasabi/JsonConverters/Uint256JsonConverter.cs

Similar to #5781, these methods might return `default` which in case of an `object` it is null, so the return type should be `object?`.

Fix null warnings

---

WalletWasabi.Tests/RegressionTests/CoinJoinTests.cs

No need to initialize `ClientRoundRegistration first` to null.
`transactionId` is initialized to null so make it nullable.

Fix some null warnings in CoinJoinTests.cs

---

WalletWasabi.Fluent/Controls/QuestionControl.axaml
WalletWasabi.Fluent/Controls/QuestionControl.axaml.cs
WalletWasabi.Fluent/Views/AddWallet/HardwareWallet/DetectedHardwareWalletView.axaml
WalletWasabi.Fluent/Views/Dialogs/ConfirmHideAddressView.axaml
WalletWasabi.Fluent/Views/Dialogs/InsufficientBalanceDialogView.axaml
WalletWasabi.Fluent/Views/Login/PasswordFinder/ContainsNumbersView.axaml
WalletWasabi.Fluent/Views/Login/PasswordFinder/ContainsSymbolsView.axaml
WalletWasabi.Fluent/Views/Login/PasswordFinder/PasswordNotFoundView.axaml

I refactored the control a bit to make the usage more obvious.
Before:
- `QuestionContent` was the question.
- `Content` was the custom icon.
- `Icon` was the image icon.
Now:
- The `Content` is the question.
- `ImageIcon` -> obviously an image that will show up as the icon.
- `IconContent` -> Any other custom icon can be set here.
Also fixed a layout issue:
Before:
After:

[Fluent] QuestionControl fixes

---

WalletWasabi.Tests/UnitTests/Transactions/TransactionStoreTests.cs

We didn't dispose `txStore` before all reference to it are out of scope (when the test is finished).

Fix warning in TransactionStoreTests.cs

---

WalletWasabi.Tests/UnitTests/Userfacing/ParserTests.cs

`result` is not null when `TryParseBitcoinUrl` returns true.

Fix some null warnings

---

WalletWasabi.Fluent/Converters/WalletIconConverter.cs
WalletWasabi.Fluent/Helpers/WalletHelpers.cs
WalletWasabi.Fluent/ViewModels/AddWallet/AddedWalletPageViewModel.cs
WalletWasabi.Fluent/ViewModels/Dialogs/Authorization/HardwareWalletAuthDialogViewModel.cs
WalletWasabi.Fluent/ViewModels/Login/LoginViewModel.cs
WalletWasabi.Fluent/Views/AddWallet/AddedWalletPageView.axaml
WalletWasabi.Fluent/Views/Dialogs/Authorization/HardwareWalletAuthDialogView.axaml
WalletWasabi.Fluent/Views/Login/LoginView.axaml

This PR fixes the issue when the `Normal` wallet icons appeared instead of the `Generic` icon on a Hardware wallet.
Also simplify the whole wallet icon logic.
Before:
After:

[Fluent] Fix `Generic` wallet icon

---

WalletWasabi.Documentation/WasabiCompatibility.md

**Ubuntu Linux 16.04 LTS is no longer supported**
> Ubuntu Linux 16.04 LTS reached the end of its five-year LTS window on April 30th 2021 and is no longer supported by its vendor, Canonical except through a paid annual Extended Security Maintenance (ESM). At that time, Ubuntu 16.04 LTS stopped receiving security patches or other software updates through our standard software support.
https://computing.cs.cmu.edu/news/2020/eol-ubuntu-1604

Remove Ubuntu 16.04 from compatibility list

---

WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/WalletBalanceChartTileViewModel.cs

X axis labels in `1W` resolution.
Before: `Wednesday Jun-2`
After: `Wed Jun-2`

[Fluent] Balance Chart - short named days

---

WalletWasabi.Gui/Global.cs
WalletWasabi.Gui/Tabs/WalletManager/RecoverWallets/RecoverWalletViewModel.cs
WalletWasabi.Gui/packages.lock.json
WalletWasabi.Packager/packages.lock.json
WalletWasabi/Helpers/Constants.cs
WalletWasabi/WalletWasabi.csproj
WalletWasabi/packages.lock.json
azure-pipelines-linux.yml

This commit also belongs here: 
https://github.com/zkSNACKs/WalletWasabi/commit/70a393e5437dba705e11e8f88b621be737b47b8f
Project board https://github.com/zkSNACKs/WalletWasabi/projects/26
Release note draft: https://github.com/molnard/WalletWasabi/releases/tag/v1.1.12.9
- Recover a wallet with an invalid keypath.
- Try to use Wasabi on Whonix (only Tor).
- Make the txstore file corrupt and check if wallet rescan.

[Backport 1.1.12.9] Cherry-picking

---

WalletWasabi.Tests/UnitTests/BitcoinCore/IndexBuilderServiceTests.cs
WalletWasabi/Blockchain/BlockFilters/IndexBuilderService.cs

CI tests were slowed down for a long time, thousands of these messages were created in CI logs. It can be noticed only in LogLevel.Debug and only in CI. The error was unnoticeable as `IndexBuilderService` was failing inside, in an infinite loop. 
```
2021-05-28 05:49:29 [26] DEBUG	IndexBuilderService (207)	System.UnauthorizedAccessException: Access to the path 'D:\a\1\s\WalletWasabi.Tests\bin\Debug\net5.0' is denied.
at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
at System.IO.File.AsyncStreamWriter(String path, Encoding encoding, Boolean …
```

Fix IndexBuilderService  Access to the path is denied

---

WalletWasabi/WabiSabi/Backend/PostRequests/InputRegistrationHandler.cs
WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs

The usage of this param was removed in  https://github.com/zkSNACKs/WalletWasabi/commit/210d73efad63b98227635cf4026ec8d25bc5d2ef

Remove unused parameter

---

WalletWasabi.Tests/UnitTests/Tor/Control/TorControlClientTests.cs
WalletWasabi.Tests/UnitTests/Tor/Control/TorControlFactoryTests.cs
WalletWasabi/Tor/Control/ReplyCode.cs
WalletWasabi/Tor/Control/TorControlClient.cs
WalletWasabi/Tor/Control/TorControlClientFactory.cs
WalletWasabi/Tor/TorProcessManager.cs

This PR adds support for subscribing of [Tor async events](https://gitweb.torproject.org/torspec.git/tree/control-spec.txt) (see *4.1. Asynchronous events*).
This PR is heavily inspired by Tor Stem project [implementation](https://github.com/torproject/stem/blob/faab143a3ebe6dddc9c7bed08bfd00eed14ae0f0/stem/control.py#L632) and Lucas's [Torino](https://github.com/lontivero/Torino/blob/05b5bb7282750209909d768a4afee85a96b075f0/src/TorController.cs#L434). My implementation is still slightly different though.
From the API client perspective, there is only one new method:
```csharp
// TorControlClient
public async IAsyncEnumerable<TorControlReply> ReadEventsAsync([EnumeratorCancellation] CancellationToken cancellationToken = default)
```
and nothing changes (from the user perspective) wrt …

Tor control: Support for async Tor events

---

WalletWasabi/Logging/Logger.cs

This PR may prove useful for debugging by developers and for cases when users supply their logs too.
The proposed change simply adds a *method name* denoting where the corresponding `Logger.Log*` call was called to each log line.
It's easier to understand non-trivial operations when you can see method names in logs. 
Note that I have `Trace` log level is enabled in these samples which is not default behavior.
<details>
<summary>Log output without the patch</summary>
```
2021-06-03 22:13:58 [1] INFO	Program (48)	Wasabi GUI started (51f0607b-5cdc-42da-87ac-df3d3cc6aba5).
2021-06-03 22:13:59 [1] INFO	TransactionStore (34)	MempoolStore.InitializeAsync finished in 16 milliseconds.
2021-06-03 22:13:59 [1] INFO	TransactionStore (34)	ConfirmedStore.InitializeAsync finished in 0 milliseconds. …
```

Logger: Add `CallerMemberName` information to logs

---

WalletWasabi.Tests/UnitTests/Transactions/SmartTransactionTests.cs
WalletWasabi/Blockchain/Transactions/SmartTransaction.cs

In `SmartTransactionLineDeserialization()` test we are testing that calling `SmartTransaction.FromLine(input, network)` with `input = null` and/or `network = null` should throw an exception, so i let `string input` and `Network network` to be null
**in the test file**.

Fix warnings in SmartTransactionTests.cs

---

WalletWasabi.Backend/Controllers/BlockchainController.cs
WalletWasabi.Tests/UnitTests/BitcoinCore/RpcBasedTests.cs
WalletWasabi.Tests/UnitTests/MockRpcClient.cs
WalletWasabi/BitcoinCore/Rpc/IRPCClient.cs
WalletWasabi/BitcoinCore/Rpc/RpcClientBase.cs

Prerequisite for the mempool mirror: https://github.com/zkSNACKs/WalletWasabi/pull/5765
The idea is to forget P2P and get txs through RPC instead.

Add batch acquiring txs from RPC

---

WalletWasabi.Tests/Helpers/ArenaRequestHandlerAdapter.cs
WalletWasabi.Tests/Helpers/WabiSabiFactory.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Backend/AliceTimeoutTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepOutputRegistrationTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepTransactionSigningTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/ConfirmConnectionTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterInputFailureTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterInputSuccessTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterInputToBlameRoundTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterOutputTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Client/AliceClientTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Client/ArenaClientTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Client/BobClientTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Models/MultipartyTransactionTests.cs
WalletWasabi/WabiSabi/Backend/PostRequests/ArenaRequestHandler.cs
WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs

This PR contains improvements and clean ups for existing WabiSabi unit tests.
Given the coordinator code was written first, at the time there were no clients available to abstract away the complexities for the creation of credentials and keep tract of the amounts, etc. For that reason the `WabiSabiFactory` was created but now we have the `ArenaClient`, a much higher-level component that can do just that, in fact we also have the `AliceClient` and `BobClient` too so, these are better (in most of the cases) than the `WabiSabiFactory`.
There are other important changes:
* `MockRpcClient` is not used anymore (we have to use `Moq`) and,
* The `output -> coin` conversion was moved to a better place what forced us to configure the RPC for all the tests (before this that code was bypassed)

[WabiSabi] Improve Unit Test

---

WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterInputFailureTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterInputSuccessTests.cs
WalletWasabi/WabiSabi/Backend/PostRequests/InputRegistrationHandler.cs
WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs

Currently a client can use a coin to repeatedly request an Alice registration and forcing the coordinator to verify the ownership proof (what requires to hit the Bitcoin full node) and verify the credentials' range proofs before detecting the coin was already used. This is imo a security bug that can facilitate DoS attacks.
This mechanism could have made sense in earlier versions of WabiSabi coordinator implementation that allowed the registration of multiple coins by the same Alice but that is not the case anymore.

[WabiSabi] Prevent DoS attacks

---

.editorconfig

Currently if you edit .axaml files using Visual Studio and you save your changes the files will be mixed with tabs and spaces.
This PR fixes that (kinda like bitcoin fixes everything).
Maybe the `indent_size` should be `2` instead of `4` like with `.xaml` files.

Update .editorconfig for *.axaml files

---

WalletWasabi.Fluent/Controls/InfoMessage.axaml
WalletWasabi.Fluent/Views/Settings/SettingsPageView.axaml

[Fluent] Tweak infomessage in Settings page

---

WalletWasabi.Tests/UnitTests/WabiSabi/Client/CredentialDependencyTests.cs
WalletWasabi/WabiSabi/Client/CredentialDependencies/CredentialEdgeSet.cs
WalletWasabi/WabiSabi/Client/CredentialDependencies/DependencyGraph.cs
WalletWasabi/WabiSabi/ProtocolContants.cs

This is a proper fix for the issue with the dependency graph that 498de7a0ba615cb432c193e9803b9f491af72e62 is a workaround for.
I gave up trying to clean up the way that `ProtocolConstants.MaxAmountPerAlice`, `MaxRegistrableVsize`, `MaxRegistrableAmount`, and (new for this PR) `ProtocolConstants.MaxVsizeCredentialValue` work, or make the test agnostic of these values and just added another constant, and did not make this configurable in the dependency graph construction. Arguably it should be, but these values are used somewhat inconsistently and I didn't want to compound that, and I don't think it should be made configurable until we clean that up.

[WabiSabi] Enforce range proof constraints in dependency graph

---

WalletWasabi.Tests/UnitTests/Tor/Control/PipeWriterExtensions.cs
WalletWasabi.Tests/UnitTests/Tor/Control/TorControlClientTests.cs
WalletWasabi.Tests/UnitTests/Tor/Control/TorControlFactoryTests.cs
WalletWasabi.Tests/UnitTests/Tor/Control/TorControlReplyReaderTests.cs
WalletWasabi.Tests/UnitTests/Tor/Control/Utils/AsyncEventParserTests.cs
WalletWasabi/Tor/Control/Messages/Events/IAsyncEvent.cs
WalletWasabi/Tor/Control/TorControlClient.cs
WalletWasabi/Tor/Control/Utils/AsyncEventParser.cs

This PR adds several improvements
* Adds several missing `.ConfigureAwait(false)` in `TorControlClientTests.cs` which should help with the test flakiness + added missing flush operations.
* It adds `AsyncEventParser` which takes an event an dispatches it to a proper parser.
* Adds `TorControlClient.{SubscribeEventsAsync|UnsubscribeEventsAsync}` methods to correctly subscribe events.
*  One can think that you can just call `SETEVENTS some-streams-here` but that might affect other subscribers, so I added a mechanism that counts subscriptions for each particular event name and basically the (un)subscription operation is now a logical one so if you subscribe to an event, no one else will affect you.
* All Tor control streams are unsubscribed when `TorControlClient` is disposed. This is not …

Tor control: Subscription API for events.

---

WalletWasabi.Fluent.Desktop/Program.cs
WalletWasabi.Gui/Global.cs
WalletWasabi.Gui/Program.cs
WalletWasabi.Tests/Helpers/Common.cs
WalletWasabi.Tests/UnitTests/Tor/TorSettingsTests.cs
WalletWasabi/Tor/TorSettings.cs

This PR simplifies instantiating of `TorSettings` class by not setting Tor log file path directly but by letting it to be computed from already provided data directory.

TorSettings: Compute Tor logs file path from data dir.

---

WalletWasabi.Tests/UnitTests/Tor/Control/PipeWriterExtensions.cs
WalletWasabi.Tests/UnitTests/Tor/Control/TorControlClientTests.cs
WalletWasabi/Tor/Control/TorControlClient.cs

🤦‍♂️ 
This PR should, finally, make `ReceiveTorAsyncEventsUsingForeachAsync` non-flaky.

PipeWriterExtensions: Add missing `.ConfigureAwait(false)`.

---

WalletWasabi.Fluent/Controls/CurrencyEntryBox.axaml.cs

The usage of this parameter was removed in https://github.com/zkSNACKs/WalletWasabi/commit/db5f1cc9ac4e5b0e9d4c00ff807ef6be420a4b83

[Fluent] Remove unused parameter

---

WalletWasabi.Tests/UnitTests/Tor/TorProcessManagerTests.cs
WalletWasabi/Microservices/ProcessAsync.cs
WalletWasabi/Tor/Socks5/TorTcpConnectionFactory.cs
WalletWasabi/Tor/TorProcessManager.cs

The goal of this PR is to make `TorProcessManager` testable. The test does not do much and it is not that useful by itself, but it is a prerequisite for testing things like:
* IF "Tor process is started and after a while the Tor process is killed (e.g. by a user)" THEN we should re-initialize everything correctly.
* IF "Tor should be terminated when WW terminates" THEN there is should be a request to Tor control
* etc.

Add a test class for `TorProcessManager`.

---

WalletWasabi.Fluent/Controls/TagsBox.axaml

Fixed #5952,
this was caused by having the concatenated control not visible, hence we didnt need ConcatenatingWrapPanel anyway.
simply use a much simpler template in readonly mode.

fix crash in tagsbox control caused by invisible concatenated control.

---

WalletWasabi.Fluent/Views/Search/SearchPageView.axaml

The box shadow for items of left side has been clipped.

[Fluent] Fix action center box shadow clipping for items

---

WalletWasabi.Fluent/Controls/TagsBox.axaml

TagsBox wrapping function did not work when `IsReadOnly` was `true`. This PR fixes it.

[Fluent] Fix `TagsBox` wrapping 

---

WalletWasabi.Gui/Global.cs
WalletWasabi.Tests/IntegrationTests/BlockstreamInfoTests.cs
WalletWasabi.Tests/IntegrationTests/LiveServerTests.cs
WalletWasabi.Tests/IntegrationTests/TorTests.cs
WalletWasabi.Tests/UnitTests/Tor/CancellationTokenExtensions.cs
WalletWasabi.Tests/UnitTests/Tor/Control/TorControlClientTests.cs
WalletWasabi.Tests/UnitTests/Tor/TorProcessManagerTests.cs
WalletWasabi/Microservices/ProcessAsync.cs
WalletWasabi/Tor/Control/TorControlClient.cs
WalletWasabi/Tor/Control/TorControlReplyReader.cs
WalletWasabi/Tor/TorMonitor.cs
WalletWasabi/Tor/TorProcessManager.cs

The code in the current master branch works as follows: `TorProcessManager` starts the Tor program and `TorMonitor` checks whether HTTP requests pass through and when they don't it calls `TorProcessManager.StartAsync()` to start Tor again. However, `TorMonitor` does not know whether Tor process was actually killed/terminated/etc. It's a somewhat heuristic approach.
This PR attempts to change this behavior in the following way: `TorProcessManager` starts the Tor program and when Tor is killed/stopped/etc. `TorProcessManager` starts it again. 
The main reason why this change makes sense is because we need a reliable way to work with Tor control. @nopara73 mentioned that we want to be able to recover from Tor process terminations (crashes, killed by user, etc.). So when Tor process …

Move a part of `TorMonitor` functionality to `TorProcessManager`.

---

WalletWasabi.Fluent/ViewModels/Wallets/WalletSettingsViewModel.cs

Every time when the Wallet Settings got open, the KeyManager was serialized. This PR fixes it.

Do not save `KeyManager` on Wallet Settings opening

---

WalletWasabi.Tests/UnitTests/Transactions/TransactionProcessorTests.cs
WalletWasabi/Blockchain/TransactionProcessing/TransactionProcessor.cs

Cleaner solution to closes https://github.com/zkSNACKs/WalletWasabi/pull/5981
I noticed labels only show up properly in the history tab if the txs are unconfirmed or over 100 confirmation. The same is true for the Date Time entry (FirstSeen). The reason is because we load txs from transaction store only for current height - 100 blocks and mempool transactions. Here I ensure that if we have the transaction already, then we use that instead of working with a new one.

Fix label show in history for >1 & <100 confirmations

---

WalletWasabi.Fluent/Views/Wallets/Send/OptimisePrivacyView.axaml
WalletWasabi.Fluent/Views/Wallets/Send/PrivacyControlView.axaml
WalletWasabi.Fluent/Views/Wallets/Send/SendSuccessView.axaml

https://github.com/zkSNACKs/WalletWasabi/issues/5974
```
- Optimize privacy screen is unusable
- Success page - green thick size should depend on the dialog size
- Privacy control page is unusable
```
Following PR:
The dialog will be shown on fullscreen when it reaches a specific small size.

[Fluent] Send - Layout fixes part 1

---

WalletWasabi.Fluent/Controls/Dialog.axaml
WalletWasabi.Fluent/Controls/Dialog.axaml.cs
WalletWasabi.Fluent/Styles/Themes/Base.axaml

On 600x600 resolution the Dialog will lose its margins and fills the whole window.

[Fluent] Dialog to fullwindow on small resolution

---

WalletWasabi.Fluent/Views/NavBar/NavBar.axaml

Part of https://github.com/zkSNACKs/WalletWasabi/issues/5974

[Fluent] NavBar - Layout fixes

---

WalletWasabi.Fluent/Views/TransactionBroadcasting/LoadTransactionView.axaml

https://github.com/zkSNACKs/WalletWasabi/issues/5974
```
[3] Transaction Broadcaster
- Load transaction page - completely broken
```
On the smallest size, the buttons were not fully visible, now they are.

[Fluent] Transaction Broadcaster - Load transaction layout fix

---

WalletWasabi.Backend/Controllers/WabiSabiController.cs
WalletWasabi/WabiSabi/Backend/PostRequests/ArenaRequestHandler.cs
WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs

Since status requests access internal mutable structures of `Arena` they
need to be protected by the async lock to avoid reading inconsistent
states.

[WabiSabi] Make status requests concurrency safe

---

WalletWasabi.Fluent/Views/Wallets/Home/History/TransactionDetailsView.axaml

Similar to issue #3878
Currently when a transction is not confirmed/pending we display block height 0 in the transaction details which is wrong.
Master:
This PR:

[Fluent] Hide block height if the transaction is not confirmed

---

WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryViewModel.cs

When a transaction happens and the row is flashing in the list, at this point if the user navigates away, NRE will occur when we are trying to cancel the flashing animation.

[Fluent] fix NRE in transaction history

---

WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItemViewModel.cs
WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryViewModel.cs

Home screen loading caused UI freeze which mostly was because of the transaction history DataGrid.
I made a few changes which made the loading twice faster.
- Fixed the issue where the History was updated twice.
- Instead of clearing and building up the list every time, build up once then update the items that changed.

[Fluent] Transaction history performance improvement

---

WalletWasabi.Tests/Helpers/HttpClientWrapper.cs
WalletWasabi.Tests/Helpers/TestNodeBuilder.cs
WalletWasabi.Tests/UnitTests/MockRpcClient.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Integration/Participant.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiApiApplicationFactory.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiHttpApiIntegrationTests.cs
WalletWasabi.Tests/WalletWasabi.Tests.csproj
WalletWasabi/BitcoinCore/CoreNode.cs
WalletWasabi/BitcoinCore/CoreNodeParams.cs

This is a first version for a real multi-client test. At this early stage all components (clients and server) use the same single fake rpc interface. Once the concept is validated that instance can be replaced by real regtest nodes.
There is currently a problem in the CJC because it cannot handle very well the errors that it receives from the coordinator. For example, the test creates a round with a maximum of 10 inputs and there are 10 participants with 2 coins each (20 coins in total), when all the participants register their first coin none of them can register the second one and we have a deadlock that is solved by a timeout.
Just as a side note, the test seems to be really slow (i didn't measure it)

[WabiSabi] Multi client test

---

WalletWasabi.Fluent/ViewModels/Wallets/Send/SendFeeViewModel.cs

part of https://github.com/zkSNACKs/WalletWasabi/issues/6073.
The selected value is now remembered when the user navigates away and back to the slider page.

[Fluent] Send - Remember fee slider value

---

WalletWasabi/WabiSabi/Client/CoinJoinClient.cs

`MultiClientsCoinJoinTestAsync` runtime reduced from 8.4 minutes to 1.8 minutes with this change. Maybe other tests time went down I did not measure those. 
I think the reason is that many of the clients get into [TryConfirmConnectionAsync](https://github.com/molnard/WalletWasabi/blob/1d5eaa20eda260aa18712b87c5935c501b7f2602/WalletWasabi/WabiSabi/Client/AliceClient.cs#L59) and eating up the backend resources, meanwhile clients trying to confirm their inputs are not able to do and just wait. 
For example, when debugging 8 out of 10 Alice ConfirmedConnection were true but 2 was simply not able to confirm for the first time a decent amount of time because the other 8 were keeping the backend busy.

[WabiSabi] Wait for connection confirmation

---

WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiHttpApiIntegrationTests.cs

This PR makes sure each simulated participant use a new  `HttpClient` instance. In other words, participants don't share the same http client instance as before, what makes the test more real and increase concurrency.

[WabiSabi] One http client per participant

---

WalletWasabi.Fluent/Controls/CurrencyEntryBox.axaml.cs

part of https://github.com/zkSNACKs/WalletWasabi/issues/6073.
- swapping should place the caret at the end of the amount.

[Fluent] Send - place the caret at the end when swapping amount

---

WalletWasabi.Fluent/Controls/TagsBox.axaml.cs

part of https://github.com/zkSNACKs/WalletWasabi/issues/6073
Fixes:
- Clicking on a suggestion adds the typed text as a label and types the clicked suggestion as a text

[Fluent] Labels - fix weird behavior when selecting from dropdown

---

WalletWasabi.Fluent/Controls/Dialog.axaml
WalletWasabi.Fluent/Controls/Dialog.axaml.cs
WalletWasabi.Fluent/Views/MainView.axaml

This PR
- adds an increased width state for the dialogs. When the width reaches a specific limit the margins on the sides will be lower. 
Part of https://github.com/zkSNACKs/WalletWasabi/issues/6073 ("99999999.99999999" BTC text crossing the swap button and USD amount not fully visible on the narrowest dialog size (without fullscreen dialog trigger))
- fixes the compact dialogs content alignment when the fullscreen mode is triggered.

[Fluent] Dialog size fixes

---

WalletWasabi.Fluent/Behaviors/DynamicHeightBehavior.cs
WalletWasabi.Fluent/Views/AddWallet/Create/ConfirmRecoveryWordsView.axaml
WalletWasabi.Fluent/Views/AddWallet/Create/RecoveryWordsView.axaml
WalletWasabi.Fluent/Views/AddWallet/HardwareWallet/ConnectHardwareWalletView.axaml

https://github.com/zkSNACKs/WalletWasabi/issues/5974
```
[1] Add Wallet
- Recovery words are not fully visible on the smallest size.
- Textbox padding is different on the smallest size on the Confirm rec words page
- Too big progress ring (while searching) on add HW wallet page
```
Note:
- The HW wallet fix was required more changes to get it to work in every case.
- During searching
- When an error message is visible
- When an already added wallet found

[Fluent] Add Wallet - Layout fixes

---

WalletWasabi.Fluent/Controls/LineChart.cs
WalletWasabi.Fluent/ViewModels/Wallets/Send/SendFeeViewModel.cs
WalletWasabi.Fluent/Views/Wallets/Send/SendFeeView.axaml

Fixes: https://github.com/zkSNACKs/WalletWasabi/issues/6069
The crash occurs when estimates array is less than 3 items long (CubicSpline.InterpolatePchipSorted input array must be at least 3 long).

[Fluent] Fix send fee estimations crash

---

WalletWasabi/WabiSabi/Backend/Models/Alice.cs
WalletWasabi/WabiSabi/Client/AliceClient.cs

Since `Alice` is a part of `Arena`'s internal state, constructing it from `AliceClient` in order to compute the hash means that it can't be modified (the motivating case is to be able to add a non nullable `Round` property as part of #6065).
This results in minor code duplication that can be cleaned up in followup work by moving the calculation into a new shared type under the `Models` namespace, as arguably it is a shared model even though it's computed independently by both client and server and not actually sent on the wire.

[WabiSabi] Calculate AliceId without using backend class

---

WalletWasabi.Fluent/ViewModels/Wallets/Send/SendFeeViewModel.cs

Reverts https://github.com/zkSNACKs/WalletWasabi/pull/6096
Restores functionality from https://github.com/zkSNACKs/WalletWasabi/pull/6079
The property was renamed from `XAxisCurrentValue` to `CurrentConfirmationTarget` and field from `_lastXAxisCurrentValue` to `_lastConfirmationTarget` in https://github.com/zkSNACKs/WalletWasabi/pull/6071

[Fluent] [Trivial] Fix SendFeeViewModel

---

WalletWasabi.Fluent/Controls/ContentArea.axaml
WalletWasabi.Fluent/Controls/TagsBox.axaml.cs
WalletWasabi.Fluent/Views/Wallets/Send/SendView.axaml

Part of https://github.com/zkSNACKs/WalletWasabi/issues/6073
[3] Label
Pressing tab key enters the label but the focus jumps to the back button (only if the text that the users enter has highlighted part - The AutoCompleteBox tries to complete it.)

[Fluent] Send - fix tab key navigation

---

WalletWasabi.Tests/Helpers/WabiSabiFactory.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Backend/AliceTimeoutTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepConnectionConfirmationTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepInputRegistrationTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepOutputRegistrationTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepTransactionSigningTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/ConfirmConnectionTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterInputFailureTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterInputSuccessTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterInputToBlameRoundTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterOutputTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RemoveInputTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/SignTransactionTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Backend/RoundCreationTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Client/ArenaClientTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Models/MultipartyTransactionTests.cs
WalletWasabi/WabiSabi/Backend/Models/Alice.cs
WalletWasabi/WabiSabi/Backend/PostRequests/InputRegistrationHandler.cs

This pull request introduces a `Round` property to `Alice`, needed for #6065, where alices are looked up by ID and by outpoint, and this change allows the arena to ensure that it belongs to the right round without requiring a lock on the round itself. Apart from being cleaner and simpler, that also ensuring that invalid requests don't compete over exclusive locks to coordinator state with valid ones.
This does not at all address and slightly exacerbates the problem of white box unit tests modifying `Arena`'s internal state to achieve certain results, the appropriate round parameter was simply added to all of these, but this problem really needs to be addressed independently because `Arena`'s public API is effectively every single implementation detail of `Arena`, …

[WabiSabi] Round property for Alice

---

WalletWasabi.Tests/UnitTests/WabiSabi/Backend/AliceTimeoutTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepOutputRegistrationTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepTransactionSigningTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Client/AliceClientTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Client/BobClientTests.cs
WalletWasabi/WabiSabi/Client/AliceClient.cs
WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
WalletWasabi/WabiSabi/Client/DependencyGraphTaskScheduler.cs
WalletWasabi/WabiSabi/Client/SmartRequestNode.cs

Continuation of this https://github.com/zkSNACKs/WalletWasabi/pull/6082
I have found the real reason for slow tests. The first few participants get here early where the round is still in input-registration, and execute the delay. The timeout is about 13 minutes and halved = ~6 minutes.
https://github.com/zkSNACKs/WalletWasabi/blob/master/WalletWasabi/WabiSabi/Client/AliceClient.cs#L55
This delay is not affected by the `RoundState` so it will wait 6 more minutes until the confirmation.

[WabiSabi] Wait or detect connection confirmation 

---

WalletWasabi/WabiSabi/Crypto/CredentialIssuer.cs

First self contained preparation PR for #6065.
This doesn't fix the bottleneck, it only removes the implicit assumption that `CredentialIssuer` is only safe to use while holding some exclusive lock (i.e. the `Arena.AsyncLock`).

[WabiSabi] Make CredentialIssuer concurrency safe

---

WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiHttpApiIntegrationTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Models/RoundStateUpdaterTests.cs
WalletWasabi/WabiSabi/Client/RoundStateUpdater.cs

This PR attempts to simplify `RoundStateUpdater` as the operations there seem redundant.

`RoundStateUpdater`: Simplify

---

WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiApiApplicationFactory.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiHttpApiIntegrationTests.cs

This PR disables the logs for all the WabiSabi integration tests and not only for the Multiclients one.

[WabiSabi] Disable ASP.NET logs in tests

---

WalletWasabi.Fluent/Controls/ContentArea.axaml

fixes https://github.com/zkSNACKs/WalletWasabi/issues/6120

[Fluent] do not allow to click through on the compact dialog's overlay

---

WalletWasabi.Fluent/Controls/PrivacyContentControl.axaml.cs

This is a bug fix for the PCC coz it's  crashing on Rider's Avalonia Preview plugin.
cc @soosr @danwalmsley @wieslawsoltes

Fix PrivacyContentControl crash on designer mode.

---

WalletWasabi.Tests/UnitTests/Nito/AsyncEx/RunningTasksTests.cs
WalletWasabi/Nito/AsyncEx/AbandonedTasks.cs
WalletWasabi/Nito/AsyncEx/RunningTasks.cs

This PR fixes `RunningTasks` class which on the master branch actually does basically nothing as there is only one instance of `TaskCompletionSource` per application in `RunningTasks`.
This PR can be reviewed commit by commit.

`RunningTasks`: Fix the implementation

---

WalletWasabi.Tests/UnitTests/WabiSabi/SerializationTests.cs
WalletWasabi/JsonConverters/Bitcoin/MoneySatoshiJsonConverter.cs
WalletWasabi/WabiSabi/Models/Serialization/JsonSerializationOptions.cs

This PR attempts to increase test coverage for `MoneySatoshiJsonConverter`. It seems to be the case that the `MoneySatoshiJsonConverter` class is tested indirectly but I have not found any *direct* tests.
It is certainly interesting to me how many different exceptions can be thrown by the JSON converter. Just for comparison, when you write a custom converter for `System.Text.JSON`, you typically throw only `JsonException`. I guess that `Newtonsoft.Json` differs in this regard.
`Assert.Null(JsonConvert.DeserializeObject<Money>("", converters));` surprised me as well. 
If you spot any weird (de)serialization in the test, please let me know.
Anyway, I hope this is useful.
Edit: I changed `JsonConverter` to `JsonConverter<T>`. I expect that this is preferred way to do this. If you like it, I …

WabiSabi: Add tests for `MoneySatoshiJsonConverter`

---

WalletWasabi.Backend/Filters/IdempotentActionFilterAttributeImpl.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiHttpApiIntegrationTests.cs

`IdempotentActionFilterAttributeImpl` is implemented in a way that if two requests are requested "at the same time", `IdempotentActionFilterAttributeImpl` will not give you the cached version of the "first" request but it lets the second request to be processed again. 
This is the reason why the `RegisterCoinIdempotencyAsync` test is flaky at the moment.
I cache `TaskCompletionSource<IActionResult>` before the first request is processed, so that the other request waits until the first one is processed. I'm aware that this is not a foolproof solution, so I would like to get some feedback on what you guys think about it. 
Note: An obvious hard case is when the first request throws an exception or takes very long.
Can be reviewed commit-by-commit.

`IdempotentActionFilterImpl` & concurrency

---

WalletWasabi.Gui/Global.cs
WalletWasabi.Tests/UnitTests/Crypto/RandomTests.cs
WalletWasabi.Tests/UnitTests/Helpers/PowerSaving/LinuxInhibitorTests.cs
WalletWasabi/Helpers/IPowerSavingInhibitorTask.cs
WalletWasabi/Helpers/PowerSaving/LinuxInhibitorTask.cs
WalletWasabi/Microservices/ProcessAsync.cs
WalletWasabi/Services/SystemAwakeChecker.cs
WalletWasabi/Tor/TorProcessManager.cs

Related to #4704
* Start old GUI project (not the Fluent one)
* Make sure that you are doing a coinjoin.
* Now you should see a `systemd-inhibit` (or `gnome-session-inhibit` or `mate-session-inhibit`) process in the list of running processes (`ps auxf | grep systemd-inhibit` / `ps auxf | grep gnome-session-inhibit` / `ps auxf | grep mate-session-inhibit`)
* Testing (Edit: fe7e68a5a60650e9918f815bfc837f72e6211233 switched from All to Idle only)
* **Scenario 1**: In your terminal, run `systemctl reboot` command to attempt to reboot your operating system.
* If you try to do `sudo shutdown now` (note the `sudo`), your computer will reboot as `systemd-inhibit` process is not run under root user in WW. 
* <s>You may also try `shutdown now` (that was also correctly inhibited on my Ubuntu 20.04 …

Inhibit sleep/shutdown on Linux

---

WalletWasabi.Fluent/Views/AddWallet/RecoverWalletView.axaml

We use the `TagsBox` control for entering labels and for entering recovery words, and while I was fixing bugs regarding Labels I forgot to enable `AllowDuplication` at Recover Wallet.

[Fluent] Allow enter a recovery word twice

---

WalletWasabi.Fluent/Styles/TextBox.axaml

- When the error message appeared, it pushed the other controls by 1 pixel. I fixed it.
- I decreased the gap between the TextBox and the error message. Usually, the message was closer to another control than to its owner.
Before:
After:

[Fluent] Validation error message fixes

---

WalletWasabi.Fluent/Views/Wallets/Send/OptimisePrivacyView.axaml

- Add a fade in/out animation
- Add fixed height to prevent the message to push other controls when gets visible

[Fluent] OptimisePrivacyScreen warning message fixes

---

WalletWasabi.Fluent/Views/Wallets/WalletView.axaml

The `Broadcast` button didn't show up when PSBT workflow was enabled.

[Fluent] fix `Broadcast` button visibility

---

WalletWasabi.Fluent/Controls/ContentArea.axaml

Since we are handling the cancelation in `Dialog.axaml.cs`, no need to `IsCancel` be set, thus some issue gets fixed:
- It was possible to close the dialog while `IsBusy` was true on TransactionPreview screen. (while the progress ring is visible after the confirmation)
- Pressing ESC triggers the Restart Wasabi button. https://github.com/zkSNACKs/WalletWasabi/pull/4842#pullrequestreview-729383303
- And probably at other places.

[Fleunt] ContentArea - Remove `IsCancel` from cancel button

---

WalletWasabi.Fluent/ViewModels/Wallets/Send/PrivacyControlViewModel.cs

If there is only one cluster the user has nothing to do on that screen. It will automatically jump to the next page and will automatically jump to the previous page (when back navigation happens).
Just like if it would be sent from private funds.
https://user-images.githubusercontent.com/16364053/129679333-5bb7a956-1739-4e98-bc90-77204b847047.mp4

[Fluent] Privacy Control - skip screen if there is only one cluster

---

WalletWasabi.Fluent/ViewModels/Wallets/Send/PrivacyControlViewModel.cs

When an `InsufficientBalanceException` happened on the privacy control screen and the user clicked `No`, it navigated to the fee screen instead of the first screen if there was only one pocket.

[Fluent] Fix navigation issue after `InsufficientBalanceException`

---

WalletWasabi.Fluent/ViewModels/Wallets/Send/SendFeeViewModel.cs

The stored fee rate was incorrect until the slider didn't move.
This PR fixes it, and now the correct fee rate will be stored immediately.

[Fluent] Fee Slider - fix invalid feerate

---

WalletWasabi.Tests/UnitTests/WabiSabi/Integration/Participant.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiHttpApiIntegrationTests.cs
WalletWasabi/WabiSabi/Client/CoinJoinClient.cs

When the round is full then in the Input-Registration phase, it is likely that some clients' Coins will be rejected. The client-side should not fail in that case either and just take the rest of the coins and go forward with the CoinJoin procedure. 
I also made input reg requests in descending order to have the biggest coin first. To be able to ensure this the requests have to be done sequentially.

[WabiSabi] Handle Input registration failures 

---

WalletWasabi.Fluent/Views/AddWallet/RecoverWalletView.axaml

fixes https://github.com/zkSNACKs/WalletWasabi/issues/6223
I modified the layout a bit, it might match better to the style. (We have this layout elsewhere too, i.e. HW wallet, receive)
- Advanced button changed to a hyperlink button
- checkmark vertically aligned
- TagsBox validation error message now won't push any control

[Fluent] Recover Wallet - layout fixes

---

WalletWasabi.Tests/Helpers/WabiSabiFactory.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterInputSuccessTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RemoveInputTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Client/ArenaClientTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiHttpApiIntegrationTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Models/SerializationTests.cs
WalletWasabi/WabiSabi/Backend/Models/Alice.cs
WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
WalletWasabi/WabiSabi/Client/AliceClient.cs
WalletWasabi/WabiSabi/Client/ArenaClient.cs
WalletWasabi/WabiSabi/Models/ConnectionConfirmationRequest.cs
WalletWasabi/WabiSabi/Models/InputRegistrationResponse.cs
WalletWasabi/WabiSabi/Models/InputsRemovalRequest.cs
WalletWasabi/WabiSabi/Models/ReadyToSignRequestRequest.cs

[WabiSabi] Properly authenticate ReadyToSign requests by making AliceId secret again

---

WalletWasabi.Tests/Helpers/WabiSabiFactory.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Backend/AliceTimeoutTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepOutputRegistrationTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepTransactionSigningTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Client/BobClientTests.cs
WalletWasabi/WabiSabi/Client/AliceClient.cs
WalletWasabi/WabiSabi/Client/CoinJoinClient.cs

This PR makes `AliceClient` aware of `SmartCoin` in order to update the coin state depending on the coordinator responses during a coinjoin session interaction.
Additionally is tries to unregister Alice in case a cancellarion request is received during InputRegistration or ConnectionConfirmation phases.
Finally it moved some relevant error handling from `CoinJoinClient` to `AliceClient`.

[WabiSabi] Unregister Alice

---

WalletWasabi.Fluent/Controls/LineChart.Properties.cs
WalletWasabi.Fluent/Controls/LineChart.cs
WalletWasabi.Fluent/Styles/BalanceLineChart.axaml
WalletWasabi.Fluent/Views/Wallets/Send/SendFeeView.axaml

This adds LabelAlignment enum for LineChart labels alignment, currently the alignment was using TextAlignment enum but we could not customize the alignments for better looking chart so I have added new option `LabelAlignment.Auto` that aligns labels in custom way (first label start from XAxis 0 point , last label ends at XAxis end, the rest of labels are center aligned, similar for Y axis).

[Fluent] [LineChart] Auto label alignment

---

WalletWasabi.Fluent/Helpers/EnumerableExtensions.cs
WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/WalletBalanceChartTileViewModel.cs

Fixes #6216.
-  Actually, the graph does update when I click smaller time frames like "1D" but the time is still 3h earlier than in history. https://github.com/zkSNACKs/WalletWasabi/issues/6216#issuecomment-905010370
- Fixes the issue when the chart was not fully built. 
Upcoming PR: 
- Improve the algorithm to not miss the key transactions.

[Fluent] Wallet Balance Chart fixes

---

WalletWasabi.Gui/Rpc/WasabiJsonRpcService.cs

WW2.0 will not have a way to manually select the coins to enqueue/dequeue because that depends on a complex cost function. I remove these two methods. We can add this functionality in the future if possible.

[WabiSabi][RPC] Remove `enqueue` and `dequeue` rpc methods

---

WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiHttpApiIntegrationTests.cs
WalletWasabi/WabiSabi/Client/CoinJoinClient.cs

Reverts zkSNACKs/WalletWasabi#6275
On the CI because it is slower, it is registering into a different round, so the change is not stable.

Revert "Privatize StartRoundAsync"

---

WalletWasabi.Fluent/ViewModels/Dialogs/ShowQrCameraDialogViewModel.cs
WalletWasabi.Fluent/Views/Dialogs/ShowQrCameraDialogView.axaml

This PR fixes an "issue", when an incorrect QR image is read (TestNet address on MainNet, URL, random text etc.), the camera closes and automatically inserts the content.
This PR leaves the camera open and should display an error message, indicating that the QR code's content is invalid for a transaction.

[Fluent] QR camera stays visible if content is not correct

---

WalletWasabi/WabiSabi/Client/CoinJoinManager.cs

Disable it to prevent accidents once the new coordinator version is deployed.

[WabiSabi] Disable WabiSabi coinjoin manager on mainet

---

WalletWasabi/Extensions/StreamExtensions.cs
WalletWasabi/Tor/Http/Extensions/HttpResponseMessageExtensions.cs
WalletWasabi/Tor/Http/Helpers/HttpMessageHelper.cs
WalletWasabi/Tor/Socks5/Exceptions/TorConnectionReadException.cs
WalletWasabi/Tor/Socks5/Pool/TorHttpPool.cs
WalletWasabi/Tor/Socks5/TorTcpConnection.cs

This is a part of work on #6215. This PR is to be reviewed commit-by-commit. 
The main change is that we want `TorHttpPool.SendAsync` method to throw either `HttpRequestException` or `OperationCanceledException`. On the master branch, this is not true as other exceptions can be thrown - like parsing errors for an HTTP response is being received.
This PR also fixes a bug (8dc8e93089e3883b2005018ac86e51b13b4fb8fa) because the Tor TCP connection dispose operation did not remove that connection from a list of available connections correctly.
This PR also adds missing cancellation token propagation (4df6c245f8701f472b2ab6d67864d8e55200106e) which should help with speed of cancelling and also prevent situation like "WW is shutting down, TorHttpPool ignores cancellation request and reads even …

Exceptions when application is shutting down (2)

---

WalletWasabi.Gui/Global.cs
WalletWasabi/Services/WasabiSynchronizer.cs
WalletWasabi/Tor/Http/Extensions/HttpResponseMessageExtensions.cs
WalletWasabi/Tor/Http/Helpers/HttpMessageHelper.cs

This is a part of work on https://github.com/zkSNACKs/WalletWasabi/issues/6215.
This PR fixes three things
* `ExternalHttpClientFactory` in Global.cs is supposed to be disposed.
* When WasabiSynchronizer is stopping, it can throw `TorConnectionException` but that may just scare user for nothing. This is not certainly elegant but I don't know about a better solution at the moment.
* A few CA2000 warning suppressions were added as IMHO it distracts from other warnings in `Global.cs` which may be actually valid issues. Anyway, if you don't like this commit, I'll revert it.

Exceptions when application is shutting down (1)

---

WalletWasabi/Tor/Http/Extensions/HttpResponseMessageExtensions.cs
WalletWasabi/WebClients/Wasabi/WasabiClient.cs

This is a part of work on #6215.
This fixes several warnings that we do not forward cancellation tokens.

`WasabiClient`: Add missing cancellation tokens.

---

WalletWasabi.Fluent/App.axaml.cs
WalletWasabi.Fluent/ViewModels/ApplicationViewModel.cs

Closes #6308
With this, the `DesktopOnShutdownRequested` event handler gets called.
How to test:
1. Enable AutoCoinJoin on Testnet/Place a breakpoint to LOC81 https://github.com/zkSNACKs/WalletWasabi/blob/4a3bf2c447c927b3444253951dafea69adaa2f6d/WalletWasabi.Fluent/App.axaml.cs#L81
2. Try to logout of your OS or shut down your PC.
AFAIK Windows and macOS is supported on Avalonia's side. Linux is not yet implemented.

Wire up DesktopOnShutdownRequested event handler

---

WalletWasabi/Services/WasabiSynchronizer.cs
WalletWasabi/WebClients/BlockstreamInfo/BlockstreamInfoClient.cs

This is a part of work on #6215.
This PR proposes not to use `WithAwaitCancellationAsync` in WasabiSynchronizer as we now have cancellation tokens propagated very well down to TorHttpClient and in many other places. 
The advantage of `.WithAwaitCancellationAsync(StopCts.Token, 300)` is that we may stop sooner when WW terminates but then `TorHttpPool` may be fast enough to dispose the actual TCP connection and an exception may be reported in console to the user. 
As `GetSynchronizeAsync` varies a lot in how long it takes, I'm not exactly sure but it *looks* like the proposed code behaves essentially the same. Also, we don't really use `WithAwaitCancellationAsync` everywhere when we send HTTP requests so even in this regard, it seems reasonable to change this (or propose a different …

`WasabiSynchronizer`: Remove `WithAwaitCancellationAsync`

---

WalletWasabi.Gui/Global.cs
WalletWasabi/Services/Terminate/TerminateService.cs

This is a part of work on #6215.
The problem `WalletWasabi.Gui/Global.cs` is that we can actually start initializing and disposing at the same time. I think we should consider putting those two phases under an async lock so that we know that we no longer initializing stuff when disposal is happening.
Review with whitespace turned off: https://github.com/zkSNACKs/WalletWasabi/pull/6310/files?diff=split&w=1
Consequences: I think this PR can help with issues like https://github.com/zkSNACKs/WalletWasabi/issues/3552. I'm not saying it solves the issue but in general, the PR *may* prevent corruptions from happening when user starts WW and stops it immediately which I think is not that rare as one may expect.
```
2021-09-07 09:37:41.194 [1] INFO	WalletManager:Dispose (28)	.ctor finished in 222 …
```

Safe app init & dispose

---

WalletWasabi.Gui/Global.cs
WalletWasabi/Services/SystemAwakeChecker.cs
WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
WalletWasabi/WabiSabi/Client/CoinJoinClientState.cs
WalletWasabi/WabiSabi/Client/CoinJoinManager.cs

Another concept for https://github.com/zkSNACKs/WalletWasabi/pull/6277
Do not review `SystemAwakeChecker` changes. There will be a complete refactor there because the Shutdown prevention was brought by Avalonia, so we need to refactor that with the new possibilities. 
StateChanged event can be added to later if we need faster reaction but this also depends on the "new" SystemAwakeChecker .

Evaluate if CoinJoin is in critical phase 2

---

WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryViewModel.cs
WalletWasabi.Fluent/Views/Wallets/WalletView.axaml

After the loading screen the `Empty wallet screen` was visible just for a moment even if the wallet is not empty. It felt really weird.
Note: A UI freeze is still noticeable, the loading has to be improved.

[Fluent[ fix when empty wallet screen shows up for a moment

---

WalletWasabi.Fluent/Views/AddWallet/RecoverWalletView.axaml
WalletWasabi.Fluent/Views/Dialogs/AdvancedRecoveryOptionsView.axaml

The text doesn't match the buttons, so this PR fixes that.

[Fluent][Trivial] Match text with button

---

WalletWasabi/WabiSabi/Client/AliceClient.cs

Mark a coin as `CoinjoinInProgress` only if it was successfully registered.
Related https://github.com/zkSNACKs/WalletWasabi/issues/6329

Mark coin as `InCoinJoin` only after registered

---

WalletWasabi.Fluent/App.axaml.cs
WalletWasabi.Fluent/ViewModels/ApplicationViewModel.cs

**This PR is important only IF the different CJ Phases and the new** `SystemAwakeChecker` **don't get merged before the PREVIEW release.**
The shutdown prevention logic on master right now is the opposite of what we want.
If https://github.com/zkSNACKs/WalletWasabi/blob/08fa77093c94ec56e1f94a66a24c0d122742c484/WalletWasabi.Fluent/ViewModels/ApplicationViewModel.cs#L7
returns `false`, then
https://github.com/zkSNACKs/WalletWasabi/blob/08fa77093c94ec56e1f94a66a24c0d122742c484/WalletWasabi.Fluent/App.axaml.cs#L85
will change it to `true` and try to cancel the shutdown/logout.
But we don't want to do that.

Fix shutdown prevention logic for Preview

---

WalletWasabi.Fluent/Controls/TagControl.axaml
WalletWasabi.Fluent/Controls/TagControl.axaml.cs
WalletWasabi.Fluent/Controls/TagsBox.axaml
WalletWasabi.Fluent/Controls/TagsBox.axaml.cs
WalletWasabi.Fluent/Views/AddWallet/RecoverWalletView.axaml

Fixes https://github.com/zkSNACKs/WalletWasabi/issues/6256.
Hiding the delete button fixed issue 3, but it still presents other places, I will take a deeper look in another PR.
In a separate PR, I will add a counter for the words.

[Fluent] Fix recover wallet issues

---

WalletWasabi.Fluent/Helpers/TileHelper.cs
WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModel.cs
WalletWasabi.Fluent/Views/Wallets/Home/Tiles/WalletPieChart/WalletPieChartWideTileView.axaml

- Reorganize the tiles to not have empty gaps
- Make a difference between normal wallet and hardware (watch only) wallet tiles (and their layout)
- Wallet privacy warning was missing on the wide piechart tile, I fixed that.
Once all priority stuff is finished let's do a brainstorming about new tile ideas.
fixes: https://github.com/zkSNACKs/WalletWasabi/issues/6244

[Fluent] Home screen - Tile fixes

---

WalletWasabi.Fluent/ViewModels/Settings/SettingsPageViewModel.cs
WalletWasabi.Fluent/Views/Settings/SettingsPageView.axaml

fixes https://github.com/zkSNACKs/WalletWasabi/issues/6361
and also:
- adds back the settings shortcut to the navbar
- removes the back button from settings page

[Fluent] Settings updates

---

WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/WalletBalanceChartTileViewModel.cs
WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/WalletBalanceTileViewModel.cs
WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/WalletPieChartTileViewModel.cs

I noticed some tiles update function is executed several times... for example the balance chart as many as transaction I have (334).
On login:
```
Tile		times
--------------------------
Balance		2	
BTC rate	1	
PieChart	2	
Recent tx	334 (Is this working btw?)	
Update Chart	334	
```
Re open the wallet:
```
Tile		times
--------------------------
Balance		2	
BTC rate	1	
PieChart	2	
Recent tx	1
Update Chart	1
```
This PR fixes it so all tiles get updated only once a time.

[Fluent] Improve homescreen loading time

---

WalletWasabi/WabiSabi/Client/AliceClient.cs
WalletWasabi/WabiSabi/Client/CoinJoinClient.cs

The `CoinJoinManager` selects the coins based on whether they are available (`CoinjoinInProgress`) or not. This means we have to make sure to unmark the coins once the coinjoin fails (no matter the if successfully or not), otherwise they will not be selected in case they need to participate in a blame round.

[WabiSabi] Unmark coins as unavailable

---

WalletWasabi.Fluent/Styles/Themes/Base.axaml

There is no `Wasabi Inc`.
Not sure if `Pizza Inc` is understandable either - I think the goal is to show the user that this can be a company too?

Remove Wasabi Inc label suggestion

---

WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/SignTransactionTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Models/MultipartyTransactionTests.cs
WalletWasabi/Helpers/ByteArrayComparer.cs
WalletWasabi/WabiSabi/Models/MultipartyTransaction/SigningState.cs

This PR sorts the coinjoin transaction's inputs and outpus. Given each client builds the coinjoin transaction independently, it is important to make sure that all of them build exactly the same transaction, for that reason `inputs` are sorted amount in a descending order and then by `prevout` lexicographically (like words in a dictionary) in an ascending order while `outputs` are sorted value in descending order and then  by `scriptPubKey` lexicographically in ascending order.
Tests were aware of the order and assumed the first input added was always in the first position and the same for the outputs, that's why a few test were updated. There was also a redundant test that was removed.
**Note:** the inputs/ouputs sorting cannot be changed easily after deploy without requiring **all** …

[WabiSabi] Sort inputs and outputs

---

WalletWasabi.Fluent/Controls/TagControl.axaml
WalletWasabi.Fluent/Controls/TagControl.axaml.cs
WalletWasabi.Fluent/Controls/TagsBox.axaml
WalletWasabi.Fluent/Controls/TagsBox.axaml.cs
WalletWasabi.Fluent/Converters/IntConverter.cs
WalletWasabi.Fluent/Views/AddWallet/RecoverWalletView.axaml

So yeah... TagsBox control is with us from the very beginning of the Fluent project. This control evolved very very much... There were tons of issues with it and it was really hard to touch it without breaking something else. 
Thanks to the refactor some improvements happened:
- The user cannot type whitespace or TagSeparator as the first char.
- In Recover page, if the next typed char would lead to a word that is not possible, then the char won't be typed.
- Fix the issue when there were two same words, and the user wanted to delete the second one, but the first one got deleted.
- Fixes https://github.com/zkSNACKs/WalletWasabi/issues/6353
- Fixes https://github.com/zkSNACKs/WalletWasabi/issues/6351
I remember there were OS specific bugs with this control, I hope I did not break anything …

[Fluent] Refactor `TagsBox`

---

WalletWasabi/Helpers/PowerSaving/WindowsPowerAvailabilityTask.cs

According to this: 
https://docs.microsoft.com/en-us/windows/win32/api/handleapi/nf-handleapi-closehandle
> If the function succeeds, the return value is nonzero.
> If the function fails, the return value is zero.
Which feels like it's in reverse, but that's how it's implemented AFAIK.
_Review without whitespace changes is helpful here._

Fix logging logic in WindowsPowerAvailability

---

WalletWasabi.Backend/Controllers/ChaumianCoinJoinController.cs
WalletWasabi.Backend/Global.cs
WalletWasabi.Tests/Helpers/WabiSabiFactory.cs
WalletWasabi.Tests/UnitTests/AllFeeEstimateTests.cs
WalletWasabi.Tests/UnitTests/BitcoinCore/RpcBasedTests.cs
WalletWasabi.Tests/UnitTests/MockRpcClient.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Backend/ConfigTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Backend/CoordinatorTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepInputRegistrationTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepTransactionSigningTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterInputFailureTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Client/ArenaClientTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Integration/Participant.cs
WalletWasabi/BitcoinCore/CoreNode.cs
WalletWasabi/BitcoinCore/Mempool/MempoolMirror.cs
WalletWasabi/BitcoinCore/Monitoring/RpcFeeProvider.cs
WalletWasabi/BitcoinCore/Processes/BitcoindRpcProcessBridge.cs
WalletWasabi/BitcoinCore/Rpc/CachedRpcClient.cs
WalletWasabi/BitcoinCore/Rpc/IRPCClient.cs
WalletWasabi/BitcoinCore/Rpc/RpcClientBase.cs
WalletWasabi/Blockchain/Blocks/BlockNotifier.cs
WalletWasabi/CoinJoin/Coordinator/Rounds/CoordinatorRound.cs
WalletWasabi/Extensions/RPCClientExtensions.cs
WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
WalletWasabi/Wallets/P2pBlockProvider.cs

NBitcoin 6.0.8 (merged recenty) allows cancellable RPC calls. This PR passes cancellation tokens when possible. The idea is not to pass tokens in every single rpc call but just in those that are more relevant and that don't require to modify all the chain of async methods.

Make all RPC calls cancellable

---

WalletWasabi.Tests/Helpers/WabiSabiFactory.cs
WalletWasabi.Tests/UnitTests/Crypto/OwnershipProofTest.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Backend/AliceTimeoutTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepOutputRegistrationTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepTransactionSigningTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterInputFailureTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterInputSuccessTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Client/ArenaClientTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Client/BobClientTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiHttpApiIntegrationTests.cs
WalletWasabi/Crypto/OwnershipIdentifier.cs
WalletWasabi/Crypto/OwnershipProof.cs
WalletWasabi/WabiSabi/Client/AliceClient.cs
WalletWasabi/WabiSabi/Client/ArenaClient.cs
WalletWasabi/WabiSabi/Client/CoinJoinClient.cs

We were using an empty ownership identifier to generate the prrof of ownerships and for that reason it made no sense to pass it as parameter all the way down trough the chain of calls, however, if one day HWs provide the ownership proofs then we would need to receive it and pass to the coordinator. This PR goes in that direction.
In practical terms it means that instead of passing a `key` to the `RegisterInput` method we pass the already computed `OwnershipProof`.

[WabiSabi] Use `OwnershipIdentifier`

---

WalletWasabi.Fluent/Views/AddWallet/RecoverWalletView.axaml

Wasabi generates 12 word recovery words, but can recover 12 or 15 or 18 or 21 or 24 words according to BIP39.
This was pointed out by Lucas on slack.

[Fluent][Trivial] Fix recovery words message

---

WalletWasabi.Fluent/ViewModels/Wallets/Advanced/WalletInfoViewModel.cs
WalletWasabi.Fluent/Views/Wallets/Advanced/WalletInfoView.axaml
WalletWasabi.Tests/UnitTests/Blockchain/Keys/WpkhOutputDescriptorHelperTests.cs
WalletWasabi/Blockchain/Keys/KeyManager.cs
WalletWasabi/Blockchain/Keys/WpkhOutputDescriptorHelper.cs

This PR is for displaying the wallet descriptors. Currently all the descriptors are shown but only the public ones should be visible while the private ones should be displayed only is the user wants to see the sensitive information because with the private wallet descriptor you can recover your wallet.
I think we need different icons for these pieces of info and also remove redundancy basically because the wallet descriptors contain everything so, all the rest is redundant. We could keep it just for convenience.
@danwalmsley could someone from the UI team help to finish this in a decent way?

[Fluent] Add output descriptors

---

WalletWasabi/WabiSabi/Client/CoinJoinManager.cs

This PR makes sure to dispose the cts only when it gets removed from the tracked list. 
Before it called the `Dispose()` for the second time too because the task was not finished in time, and then an exception happened, thus the CoinJoinManager stopped.
It especially happened when you turn ON then OFF the autoCJ.

Fix `CoinJoinManager` stopped

---

WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
WalletWasabi/WabiSabi/Client/CoinRefrigerator.cs

Continuation of https://github.com/zkSNACKs/WalletWasabi/pull/6405
Small helper class to detain coins until we are not sure about the CoinJoin they were participating in. Basically we are waiting for the mempool to get the CJ to make sure it was broadcast by the backend. 
It is basically the same but in a different class. I was not able to figure out any breakthrough, so I guess this is it.

Add CoinRefrigerator to CoinJoinManager

---

WalletWasabi/Crypto/StrobeProtocol/StrobeHasher.cs
WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
WalletWasabi/WabiSabi/Backend/Rounds/Round.cs
WalletWasabi/WabiSabi/Crypto/RoundHasher.cs
WalletWasabi/WabiSabi/Models/RoundState.cs
WalletWasabi/WabiSabi/ProtocolContants.cs

This PR computes the round hash on the client side too, it was missing and that's an important mistake. Additionally round hash commits to missing parameters and to timeouts that are required to calculate and to schedule the communication delays.

[WabiSabi] Compute round hash

---

WalletWasabi.Tests/Helpers/ArenaBuilder.cs
WalletWasabi.Tests/Helpers/WabiSabiFactory.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepConnectionConfirmationTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepTransactionSigningTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterInputFailureTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterInputToBlameRoundTests.cs
WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs

The goal of this PR is to make it more clear what the public API of `Arena` is: `Arena.Prison` should not be accessible publicly. 
More importantly though, we should not make `Arena.Rounds` publicly accessible (not this PR). Any change to the property outside of proper lock may lead to breaking of `Arena` functionality.

`WabiSabi`: `ArenaBuilder` in tests.

---

WalletWasabi/Extensions/TimeSpanExtensions.cs
WalletWasabi/WabiSabi/Client/CoinJoinClient.cs

This bug found by @MaxHillebrand 
```
2021-10-04 16:39:53.311 [17] ERROR	CoinJoinManager:ExecuteAsync (134)	Wallet: `Business` - Coinjoin client failed with exception: Exception: System.ArgumentException: Range of random number does not contain at least one possibility.
at System.Security.Cryptography.RandomNumberGenerator.GetInt32(Int32 fromInclusive, Int32 toExclusive)
at WalletWasabi.Crypto.Randomness.SecureRandom.GetInt(Int32 fromInclusive, Int32 toExclusive) in WalletWasabi/Crypto/Randomness/SecureRandom.cs:line 21
at System.TimeSpanExtensions.<>c__DisplayClass0_0.<Sample>b__0(Int32 _) in WalletWasabi/Extensions/TimeSpanExtensions.cs:line 15
at System.Linq.Enumerable.SelectRangeIterator`1.ToArray()
at System.Linq.OrderedEnumerable`1.ToArray()
at …
```

[WabiSabi] Fix edge case when there is not remaining time

---

WalletWasabi.Tests/UnitTests/WabiSabi/Backend/AliceTimeoutTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/ConfirmConnectionTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterInputFailureTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterInputToBlameRoundTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterOutputTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RemoveInputTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/SignTransactionTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Backend/RequestHandlerDisposeTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Client/ArenaClientTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Client/BobClientTests.cs
WalletWasabi/WabiSabi/Backend/PostRequests/ArenaRequestHandler.cs
WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
WalletWasabi/WabiSabi/WabiSabiCoordinator.cs

This is a follow-up PR to #6462
The main change is that `IRPCClient Rpc { get; }` is now `private` as it should not be publicly accessible.
Best to review commit-by-commit.

`ArenaBuilder` & `Arena.IRPCClient` 

---

WalletWasabi.Backend/InitConfigStartupTask.cs
WalletWasabi.Fluent.Desktop/Program.cs

Just two warnings fixed in the same way as:
https://github.com/zkSNACKs/WalletWasabi/blob/f9fd1a655d8ce1977f98baac3216c57404e53b94/WalletWasabi.Fluent.Desktop/Program.cs#L179-L193

`InitConfigStartupTask`: Fix two warnings.

---

WalletWasabi.Fluent/Styles/HyperlinkButton.axaml

It was lost after an Avalonia update.
Before:
After:

[VDG] fix hyperlink underline

---

WalletWasabi.Fluent/Helpers/TransactionFeeHelper.cs
WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionPreviewViewModel.cs

Transaction fees are considered to be equal if the first and last estimations are equal.

[Trivial] Fix AreTransactionFeesEqual() logic

---

WalletWasabi.Fluent/ViewModels/AddWallet/RecoverWalletViewModel.cs
WalletWasabi.Fluent/ViewModels/Dialogs/AdvancedRecoveryOptionsViewModel.cs
WalletWasabi.Tests/AcceptanceTests/HwiKatas.cs
WalletWasabi.Tests/Helpers/ServiceFactory.cs
WalletWasabi.Tests/IntegrationTests/P2pTests.cs
WalletWasabi.Tests/RegressionTests/BuildTests.cs
WalletWasabi.Tests/RegressionTests/SendTests.cs
WalletWasabi.Tests/RegressionTests/WalletTests.cs
WalletWasabi.Tests/UnitTests/Hwi/HwiProcessBridgeMock.cs
WalletWasabi.Tests/UnitTests/Hwi/MockedDeviceTests.cs
WalletWasabi.Tests/UnitTests/KeyManagementTests.cs
WalletWasabi.Tests/UnitTests/SmartCoinTests.cs
WalletWasabi.Tests/UnitTests/Transactions/PayjoinTests.cs
WalletWasabi.Tests/UnitTests/Transactions/TransactionProcessorTests.cs
WalletWasabi.Tests/UnitTests/Userfacing/PasswordTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Integration/Participant.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiHttpApiIntegrationTests.cs
WalletWasabi/Blockchain/Keys/BlockchainState.cs
WalletWasabi/Blockchain/Keys/KeyManager.cs
WalletWasabi/Blockchain/Keys/WalletGenerator.cs
WalletWasabi/Blockchain/Transactions/TransactionFactory.cs
WalletWasabi/Helpers/HardwareWalletOperationHelpers.cs
WalletWasabi/Helpers/ImportWalletHelper.cs

Related to issue #6218 
When creating a _Wallet_, regardless of having a property that indicates if the wallet is used on **Main**- or **TestNet**, the `AccountKeyPath` for all wallets are set to be the same. `"84'/0'/0'"`, which is the default **KeyPath** for **MainNet**.
But as discussed in the issue above, this keeps the users from using _Trezor One_ on **TestNet**, because the Trezor rules are strict for BIP44, and will deny transactions and cause exception that has wrong **KeyPath**.
This PR should solve this issue. Altough **it won't touch older wallets** for the purpose of not risking to mess up files and the user's money, all wallets - including **hot** and _cold_ - that's generated afterwards on **TestNet** will have KeyPath set to `"84'/1'/0'"`, thus fixing the Trezor One issue …

Change KeyPath for TestNet

---

WalletWasabi/WabiSabi/Client/CoinJoinClient.cs

Since constructing circuits can take several seconds, take that into
account when randomizing the delays. If connections pre-established so
that the circuit building latency no longer affects requests, this can
be reduced to an estimated round trip latency, which is significantly
shorter.

[WabiSabi] Don't register inputs too close to the timeout

---

WalletWasabi.Tests/UnitTests/BitcoinCore/IndexBuilderServiceTests.cs
WalletWasabi/Blockchain/BlockFilters/IndexBuilderService.cs

Our bech32 client side filters are currently 1 GB. This is one of the technological bottlenecks of Wasabi Wallet. A while ago we included taproot outputs in our filters, despite we never used it. Since taproot is a special address type we cannot change to it and it comes with no direct benefits. The size pros are negligible. LN integration is not around the corner and we'll have to change address type again when cross input signature aggregation arrives to Bitcoin.
When LN or similar script heavy stuff is going to be integrated to Wasabi we can always turn these on.
- Takes less blockspace (negligible)
- Inevitable for LN integration (at least half a decade away)
- Most wallets can't send money to these outputs (expect to be like this for half a decade)
- When cross input signature …

Slow the growth of client side filters

---

WalletWasabi/WabiSabi/Client/WabiSabiHttpApiClient.cs

This helps rounds succeed when there are tor related errors, which for me are quite frequent (unstable internet connection).
A more complete approach would be to only retry in some circumstances. For standard HTTP things, the behavior described in [this blog post](https://sergeyakopov.com/transient-http-error-retry/) for instance seems like a good policy. In addition to that we will also want to catch `TorException`, and perhaps others, and only treat those exceptions as transient (e.g. if sending a request generates `InvalidOperationException`, it makes no sense to retry).
Note that there are no unit tests, but in manual testing this has made it possible for me to reliably complete testnet coinjoins.

[WabiSabi] Retry requests that fail due to transport errors

---

WalletWasabi/WabiSabi/Client/AmountDecomposer.cs

The following code expects a frequency table. You wanted to be smart and use some biased weight instead, but you forgot to actually use it. I don't know how to fix it by leaving the weight in the code, but this code expects a frequency table:
```cs
var denoms = histogram
. OrderByDescending(x => x.Key)
. Where(x => x.Value > 1)
. Select(x => x.Key)
. ToArray();
```

Remove weight bias, because it ruins the algorithm

---

WalletWasabi.Tests/UnitTests/WabiSabi/Models/RoundStateUpdaterTests.cs
WalletWasabi/WabiSabi/Client/RoundStateUpdater.cs

Before this PR the `RoundStateUpdater` reported that the round was not running anymore when it received an exception.

[WabiSabi] Fix blocked round updater

---

WalletWasabi/Tor/Socks5/TorTcpConnectionFactory.cs

This PR is for making sure the Wasabi Client's connection to the Tor socks proxy remain alive, what reduces the number reseted connections when signaling ready to sign.
The problem is still there, not sure why, but the frequency of the occurrences does down by a significant number.

Improve reliability for alices

---

WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepConnectionConfirmationTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepInputRegistrationTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepTransactionSigningTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Backend/Rounds/Utils/ArenaExtensions.cs
WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs

It was used only for unit testing so, it had to be moved to somewhere else.

Remove `ActiveRounds` property from arena

---

WalletWasabi/Tor/Http/IHttpClient.cs

This PR attempts to make the clear expectations what exceptions are expected to be thrown when working with `IHttpClient`.
Addresses https://github.com/zkSNACKs/WalletWasabi/pull/6649#discussion_r746622571.

Add documentation for `IHttpClient`.

---

WalletWasabi.Fluent/Views/AddWallet/Create/ConfirmRecoveryWordsView.axaml
WalletWasabi.Fluent/Views/AddWallet/Create/RecoveryWordsView.axaml
WalletWasabi.Fluent/Views/Login/PasswordFinder/SearchPasswordView.axaml
WalletWasabi.Fluent/Views/StatusBar/StatusBar.axaml
WalletWasabi.Fluent/Views/Wallets/Home/History/CoinJoinDetailsView.axaml
WalletWasabi.Fluent/Views/Wallets/Home/History/TransactionDetailsView.axaml

Fix crash that Marnix found!
Exception: TwoWay Bindings do not support string format.

explicitly specify one way bindings where string format is used.

---

WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryViewModel.cs
WalletWasabi/Blockchain/Transactions/TransactionHistoryBuilder.cs

Fixes #6661
Before:  
https://github.com/zkSNACKs/WalletWasabi/blob/10fa57e360d99c99356d8e7cfb6b6934044f6cf8/WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryViewModel.cs#L109
After a successful CJ, this line was called with wrong object type. We assigned wrong type, because its `TransactionSummary` was falsely built.
Because of the wrong type, this sanity check threw the exc.
https://github.com/zkSNACKs/WalletWasabi/blob/10fa57e360d99c99356d8e7cfb6b6934044f6cf8/WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItems/CoinJoinsHistoryItemViewModel.cs#L53

Fix "Not the same type!" issue

---

WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryViewModel.cs

During the history building, we group the consecutive CJs into a group and add that group to the history list once a non CJ txn is the next. If all the last txn was CJ, the group adding never happened.

[VDG] fix missing last CJ item in transaction history

---

WalletWasabi.Fluent/Models/WebcamQrReader.cs

Addresses https://github.com/zkSNACKs/WalletWasabi/pull/6710#issuecomment-976299111
With this PR, we catch every OpenCV exception and we don't compare strings.

Catch OpenCV exception and show user friendly error message.

---

WalletWasabi/JsonConverters/EndPointJsonConverter.cs

This is similar to what @kiminuo did in https://github.com/zkSNACKs/WalletWasabi/pull/6158 and a better way to fix warning than #6728

Switch 'EndPointJsonConverter' from 'JsonConverter' to 'JsonConverter<T>'

---

WalletWasabi.Fluent.Desktop/WalletWasabi.Fluent.Desktop.csproj
WalletWasabi.Fluent.Desktop/packages.lock.json
WalletWasabi.Fluent/WalletWasabi.Fluent.csproj
WalletWasabi.Fluent/packages.lock.json

Updates Avalonia allowing us to run on Apple sillicon again (was broken by net6 support).
Also provides
- Shutdown prevention on Linux.
- Fix rendering issues on apple sillicon and nvideo 3000 series gpus.
- Paves way for properly closing window when in background.
Note: 
This is avalonia 0.10.11-rc.1 which uses an RC version of skiasharp.
We will only make a final release once skiasharp releases.
Talked to skiasharp and their release schedule seems it wont cause us issues.

update avalonia to restore apple sillicon support.

---

WalletWasabi.Fluent/Helpers/NotificationHelpers.cs
WalletWasabi.Fluent/ViewModels/WalletManagerViewModel.cs

closes https://github.com/zkSNACKs/WalletWasabi/issues/6360
Notification title will be only the wallet name and the message will be more accurate.

[VDG] Update Notifications

---

WalletWasabi.Fluent/Views/Wallets/Send/TransactionPreviewView.axaml

Small typo fix at `Send - Preview Transaction` screen: _To Bitcoin address_ instead of current _via Bitcoin address_

Typo fix-'To Bitcoin address' instead of 'Via'

---

WalletWasabi/WabiSabi/Client/CoinJoinClient.cs

Some times no inputs are registered and in that case the CJC throws an `InvalidOperationException` when in fact it is not necessarily an exceptional condition or error.

[WabiSabi] Do not throw exceptions when no Alice is available

---

WalletWasabi.Fluent/Controls/Dialog.axaml
WalletWasabi.Fluent/Controls/Dialog.axaml.cs
WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItems/TransactionHistoryItemViewModel.cs
WalletWasabi.Fluent/Views/MainView.axaml

Partial fix for #6690
This is split from work done in https://github.com/zkSNACKs/WalletWasabi/pull/6730
This PR enables controlling dialog sizing depending on bounds width and height.
Using CompactDialogScreen didn't really help as it sizes dialog content to minimal width and height. Additional dialog size saving can be achieved if necessary by bottom button repositioning, that work will continue in https://github.com/zkSNACKs/WalletWasabi/pull/6730
https://user-images.githubusercontent.com/2297442/144048312-367d90c8-c7cb-4271-a916-dd4f8bbd0a84.mp4

[VDG] [Fluent] Dialog screen size optimization - width and height thresholds

---

WalletWasabi.Fluent/Views/Dialogs/Authorization/PasswordAuthDialogView.axaml

If you type a long password this is how the password dialog looks on Master:
This PR fixes that.

Set Width and Height for PasswordAuthDialog

---

WalletWasabi.Fluent/Controls/TagControl.axaml
WalletWasabi.Fluent/Views/Wallets/Receive/ReceiveAddressesView.axaml

Fixes the tagsbox not cutting its text off when it's too long. 120px is a good enough MaxWidth i suppose.

Fix TagControl's text wrapping

---

WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
WalletWasabi/WabiSabi/LoggerTools.cs

This PR makes sure that in case of any unexpected error the round will fail and Arena can continue updating other rounds. 
There were 2 pieces of 3 day old Rounds, one was in `InputRegistration`, the other one was in `OutputRegistration`. The rounds stacked without state updates. 
The reason was that an exception happened somewhere between lines:
https://github.com/zkSNACKs/WalletWasabi/blob/954f25302cd7d9b62a94cdd33bcb923b9b0fdd0b/WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs#L169-L182
In this case, the `Arena.ActionAsync` which is called periodically, fails and stops managing the states of the Rounds.
Fixes: https://github.com/zkSNACKs/WalletWasabi/issues/6853

Add try/catch to Arena step methods

---

WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItems/CoinJoinsHistoryItemViewModel.cs
WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryViewModel.cs

The history list in the wallet dashboard is batching CJ transactions. With this PR unconfirmed CJ transactions will be shown as well and flashing the line in the history. Also, I reversed the order at the tx details: the newest on top

Show unconfirmed CJ in history list

---

WalletWasabi/Hwi/Parsers/HwiParser.cs

Reason: 
`string.IsNullOrEmpty(string)` is called on the result of `string.Trim()`.
Example: 
https://github.com/zkSNACKs/WalletWasabi/blob/99bb5d5ac0ed7e1cea4423fbdd6974896ef9c926/WalletWasabi/Hwi/Parsers/HwiParser.cs#L228
https://github.com/zkSNACKs/WalletWasabi/blob/99bb5d5ac0ed7e1cea4423fbdd6974896ef9c926/WalletWasabi/Hwi/Parsers/HwiParser.cs#L250
The call to `string.Trim()` may allocate a new string. This allocation can be avoided by calling `string.IsNullOrWhiteSpace(string)`. Not only does that avoid the **memory allocation**, it is also **faster** in most cases and never slower.
https://github.com/u2uconsult/codeanalyzers/blob/master/docs/U2U1113.md

Replace `IsNullOrEmpty()` with `IsNullOrWhiteSpace()`

---

WalletWasabi/Blockchain/BlockFilters/IndexBuilderService.cs

Fixes: https://github.com/zkSNACKs/WalletWasabi/issues/6863
The bug was added by https://github.com/zkSNACKs/WalletWasabi/pull/5875
When reorg happened on the network or block burst the `IndexBuilderService .Synchronize` method got called rapidly and there was a concurrency problem. 
Reorging the index files was still running but Synchronize got called by BlockNotifier_OnBlock so the file permission check failed. The check intended to fix the problem when the IndexFile location has a permission problem in general so I moved that to the ctor.
This is a quick fix  - PoC to refactor index builder in the far future https://github.com/zkSNACKs/WalletWasabi/pull/6866

Fix IndexBuilder exception when Reorging

---

WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/PrivacyControlTileViewModel.cs

idk if this is gonna work but let's try it anyway
this is a quick fix, but it could be that the problem is on a deeper level than this... 
anyways, this clamps the values to valid range (0d<->1d) that can be displayed and formatted well in string.Format.
cc @MaxHillebrand @yahiheb @zkSNACKs/visual-design-group

[Fluent] Try fixing missing privacy percent values in some systems

---

WalletWasabi/Crypto/UnblindedSignature.cs

Both https://github.com/zkSNACKs/WalletWasabi/blob/master/WalletWasabi/Crypto/UnblindedSignature.cs#L18 and https://github.com/zkSNACKs/WalletWasabi/blob/master/WalletWasabi/Crypto/UnblindedSignature.cs#L62 out a non null `UnblindedSignature` when `true`.

Remove unnecessary condition

---

WalletWasabi.Tests/UnitTests/Transactions/TransactionFactoryTests.cs
WalletWasabi/Blockchain/TransactionBuilding/PaymentIntent.cs
WalletWasabi/Blockchain/Transactions/TransactionFactory.cs

This test simulates the `InvalidTxException: Invalid transaction` As suggested here https://github.com/zkSNACKs/WalletWasabi/issues/6750#issuecomment-988917870

Add FeesDifferentThanExpected test to TransactionFactoryTests

---

WalletWasabi.Tests/UnitTests/Transactions/TransactionFactoryTests.cs
WalletWasabi/Blockchain/Transactions/TransactionFactory.cs

#6871 should be merged first.
Fixes #6750
When we try to make a transaction we first assume that it creates 2 outputs, 1 as a payment and 1 as a change, thus it has an estimated size and estimated fee.
In an edge case and with certain selected fee rate the built transaction creates only 1 output because the one that is supposed to be a change is uneconomical (less than dust 294 sat), so the transaction builder adds that change to the fee which results in a difference of fees between the expected fee and the actual one.
More context about this in #2116 where this part of the code was added.

Remove feerate different sanity check

---

WalletWasabi.Backend/WalletWasabi.Backend.csproj
WalletWasabi.Packager/WalletWasabi.Packager.csproj
WalletWasabi.Tests/WalletWasabi.Tests.csproj

Without the proposed change one cannot run Backend or Tests on arm64 platforms. Dropping the setting allows this.
Before the change:
```
$ dotnet run --project WalletWasabi.Backend
Unhandled exception. System.BadImageFormatException: Could not load file or assembly '/Users/stick/work/zksnacks/WalletWasabi/WalletWasabi.Backend/bin/Debug/net6.0/WalletWasabi.Backend.dll'. An attempt was made to load a program with an incorrect format.
File name: '/.../WalletWasabi/WalletWasabi.Backend/bin/Debug/net6.0/WalletWasabi.Backend.dll'
```
After the change:
```
$ dotnet run --project WalletWasabi.Backend
2021-12-18 18:55:39.984 [1] INFO	InitConfigStartupTask.ExecuteAsync (31)	Wasabi Backend started ...
...
```

Remove PlatformTarget from Backend, Packager, Tests

---

WalletWasabi.Tests/UnitTests/Crypto/StringCipherTests.cs
WalletWasabi/Crypto/StringCipher.cs

Fixes: #6732
This PR fixes a bug in the `StringCipher::Decrypt`. Basically the it was not reading all the decrypted stream and ignored the byte's counter returned by the `Stream.Read` method.
This should close #6936 and #6946

Fix string cipher

---

WalletWasabi.Tests/UnitTests/WabiSabi/Models/RoundStateUpdaterTests.cs

When Moq is not well configured it returns `null` after the sequence of configured returns reaches its limit,
```
2021-12-30 16:05:22.669 [19] ERROR	RoundStateUpdater.ActionAsync (47)	System.NullReferenceException: Object reference not set to an instance of an object.
at WalletWasabi.WabiSabi.Client.RoundStateUpdater.ActionAsync(CancellationToken cancellationToken) in /mnt/data/GitHub/WalletWasabi/WalletWasabi/WabiSabi/Client/RoundStateUpdater.cs:line 34
```

Fix NRE in UT

---

WalletWasabi/JsonConverters/Bitcoin/FeeRateJsonConverter.cs
WalletWasabi/JsonConverters/Bitcoin/MoneyBtcJsonConverter.cs
WalletWasabi/JsonConverters/Bitcoin/MoneySatoshiJsonConverter.cs
WalletWasabi/JsonConverters/Bitcoin/ScriptJsonConverter.cs
WalletWasabi/JsonConverters/BitcoinAddressJsonConverter.cs
WalletWasabi/JsonConverters/BitcoinEncryptedSecretNoECJsonConverter.cs
WalletWasabi/JsonConverters/EndPointJsonConverter.cs

According to https://github.com/zkSNACKs/WalletWasabi/pull/6806#discussion_r767552159 and https://github.com/zkSNACKs/WalletWasabi/pull/6806#discussion_r770871670 we should:
> keep the original behavior: throw an exception in case of null
> I think we shouldn't change the existing behavior if we are not sure that that is correct. I assumed (wrongly?) that it was writing null before but if that's not the case and as @molnard says it was throwing an exception before then it has to throw an exception now too (and the same exception, btw)
We changed the behavior in [previous PRs](https://github.com/zkSNACKs/WalletWasabi/pulls?q=is%3Apr+author%3Ayahiheb+is%3Aclosed+from+%27JsonConverter%27+to+%27JsonConverter%3CT%3E%27+) and PR fixes that.

Throw exception if value is null (JsonConverters)

---

WalletWasabi.Tests/UnitTests/Crypto/StringCipherTests.cs
WalletWasabi/Crypto/StringCipher.cs

This PR is based on the @kiminuo's #6946 PR and is the result of applying the best of that PR into the existing one and applying some extra goodness recently available in the dotnet library, what allowed me to simplify the code even more.
This implementation respects the previous data format so, it is compatible with older versions (even when we don't really need it at all).

Improve StringCipher code and correctness

---

WalletWasabi/Logging/Logger.cs

Running the software with LogLevel Trace increments the log size at a pace that hits the limit in a few hours (~10). Unfortunately, if the limit is reached the whole file is deleted and started over. 
This is a temporary solution as this does not scale.

Increase the log size in case of TraceLevel

---

WalletWasabi.Fluent.Desktop/Program.cs
WalletWasabi/Services/SingleInstanceChecker.cs

Closes: https://github.com/zkSNACKs/WalletWasabi/pull/6998
The suppress comments have to be added because of an analyzer bug:
https://issueexplorer.com/issue/dotnet/roslyn-analyzers/5712

Dispose SingleInstanceChecker in synchronously  

---

WalletWasabi/JsonConverters/HDFingerprintJsonConverter.cs

This PR tries to fix and issue introduced after #7006 was merged.
Now you get the following in the logs file if you have a watch-only wallet:
```
2022-01-10 01:24:54.680 [1] WARNING	WalletManager.AddWallet (207)	Wallet got corrupted.
Wallet Filepath: C:\Users\chihe\AppData\Roaming\WalletWasabi\Client\Wallets\TestNet\WatchOnly - Ashes.json
Trying to recover it from backup.
Backup path: C:\Users\chihe\AppData\Roaming\WalletWasabi\Client\WalletBackups\TestNet\WatchOnly - Ashes.json
Exception: System.ArgumentNullException: Value cannot be null. (Parameter 'Value')
at WalletWasabi.JsonConverters.HDFingerprintJsonConverter.ReadJson(JsonReader reader, Type objectType, HDFingerprint existingValue, Boolean hasExistingValue, JsonSerializer serializer) in …
```

Fix ReadJson method in HDFingerprintJsonConverter

---

WalletWasabi.Tests/UnitTests/Crypto/CredentialIssuerKeyTests.cs
WalletWasabi.Tests/UnitTests/Crypto/RandomTests.cs
WalletWasabi/Crypto/CredentialIssuerSecretKey.cs
WalletWasabi/Crypto/Randomness/WasabiRandom.cs
WalletWasabi/Crypto/ZeroKnowledge/SyntheticSecretNonceProvider.cs
WalletWasabi/Crypto/ZeroKnowledge/Transcript.cs
WalletWasabi/WabiSabi/Crypto/WabiSabiClient.cs

In this PR we introduce the audit recommendations
* In ProofSystem.cs, typo line 169: it should be rb_i -> r_i * b_i
This is incorrect because the 3rd terms are called `rb` (`r` times `b`) everywhere and its `i`th component is also called `rb_i`.
* In `CredentialIssuerSecretKey()`, we recommend to check that scalars are non-zero, as it would be an insecure key and would reveal other problems (with the PRNG). 
We have already discussed this thing a million times and we know zero is a valid number and that the chances of getting a zero are much much lower than winning the national lottery a million times in a row.   
Anyway, I checked for zero in the constructor, write the UTs that verify it and made sure the `GetScalar` never returns zero.
* The `GetInt()` implementation used in …

Implement code review suggestions

---

WalletWasabi/Helpers/Constants.cs

I could not find the recovery words for the TestNet fallback wallet. Created a new wallet that I am aware of the recovery words. 
Keep in mind that this xpub will be only used if someone forgets to change the coordinator fee xpub before going into production - which is not likely.

Change the default fallback address

---

azure-pipelines-osx.yml

https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml
> In December 2021, we removed the following Azure Pipelines hosted image:
> macOS X Mojave 10.14 (macOS-10.14)

Fix macOS CI pipeline

---

WalletWasabi.Tests/UnitTests/WabiSabi/Client/AmountDecomposerTests.cs
WalletWasabi/WabiSabi/Client/AliceClient.cs
WalletWasabi/WabiSabi/Client/AmountDecomposer.cs
WalletWasabi/WabiSabi/Client/CoinJoinClient.cs

In harmony with our plans regarding coordination fees - the input fee calculation will require more parameters that won't be available inside the amount decomposer nor belong to there - thus this PR born. 
Part of https://github.com/zkSNACKs/WalletWasabi/pull/6953

Remove EffectiveValue calculation form AmoutDecomposer

---

WalletWasabi.Fluent/ViewModels/Wallets/Send/ChangeAvoidanceSuggestionViewModel.cs
WalletWasabi/Blockchain/Transactions/TransactionFactory.cs

Leftouts from: #7012
Addressing: https://github.com/zkSNACKs/WalletWasabi/pull/7012#issuecomment-1008921089
and https://github.com/zkSNACKs/WalletWasabi/pull/7012#issuecomment-1008923513
The `Change Avoidance Suggestions` were missing the `trySign: false` param, so they got signed right after creation, which is not neccessary.
To make it super clear, we **will** sign the TXs, when the user clicks on the `Confirm` button.

Do not sign Change Avoidence Suggestions when created

---

WalletWasabi/JsonConverters/HDFingerprintJsonConverter.cs

According to @kiminuo in `KeyManager` https://github.com/zkSNACKs/WalletWasabi/blob/eabc03b9c339e2daa8b30f7788c79e1134d15077/WalletWasabi/Blockchain/Keys/KeyManager.cs#L107-L109 we expect to get either `HDFingerprint` or `null`, but in the master branch, we return always `HDFingerprint` and never `null` (which was changed in #7006)
This PR fixes that.

Switch HDFingerprintJsonConverter from 'JsonConverter<T>' to 'JsonConverter<T?>'

---

WalletWasabi.Fluent/Controls/CurrencyEntryBox.axaml.cs
WalletWasabi.Fluent/ViewModels/Wallets/Send/SendViewModel.cs
WalletWasabi.Fluent/Views/Wallets/Send/SendView.axaml

Fixes #6982 by keeping track of CurrencyEntryBox's state in the SendViewModel object.
cc @MarnixCroes @zkSNACKs/visual-design-group

[Fluent] Persist Fiat to BTC setting on CurrencyEntryBox

---

WalletWasabi.Tests/Helpers/ArenaBuilder.cs
WalletWasabi.Tests/Helpers/WabiSabiFactory.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Backend/AliceTimeoutTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepConnectionConfirmationTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepInputRegistrationTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepOutputRegistrationTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepTransactionSigningTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/ConfirmConnectionTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterInputFailureTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterInputSuccessTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterInputToBlameRoundTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterOutputTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RemoveInputTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/SignTransactionTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Client/ArenaClientTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Client/BobClientTests.cs
WalletWasabi/WabiSabi/Backend/Banning/Prison.cs
WalletWasabi/WabiSabi/Backend/Models/WabiSabiProtocolErrorCode.cs
WalletWasabi/WabiSabi/Backend/Rounds/Arena.Partial.cs

This PR improves the DoS protection by banning those alices that are clearly trying to fool the coordinator. The cleaner examples are those where the client is sending invalid cryptographic proofs, credentials or serial numbers. In this case it makes no sense to allow those coins to be used again because they are in control of an attacker.
Additionally, this PR removes duplicated code from `WabiSabiFactory` and uses the more convenient `ArenaBuilder`.

[WabiSabi] Ban alices that are clearly cheating.

---

WalletWasabi.Tests/Helpers/WabiSabiFactory.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Backend/AliceTimeoutTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepOutputRegistrationTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepTransactionSigningTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Client/ArenaClientTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Client/BobClientTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Client/KeyChainTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Integration/Participant.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiHttpApiIntegrationTests.cs
WalletWasabi/Blockchain/TransactionOutputs/SmartCoin.cs
WalletWasabi/WabiSabi/Client/AliceClient.cs
WalletWasabi/WabiSabi/Client/ArenaClient.cs
WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
WalletWasabi/WabiSabi/Client/IDestinationProvider.cs
WalletWasabi/WabiSabi/Client/IKeyChain.cs
WalletWasabi/WabiSabi/Client/InternalDestinationProvider.cs
WalletWasabi/WabiSabi/Client/KeyChain.cs

Right now the `CoinJoinClient` creates the ownership proofs, handles private keys, uses those private keys to sign inputs among other things that are out of its responsibilities. This is a well-known design problem[¹]  that has gone under radar simply because prioritization but it is important to improve code by moving those parts to where they suite better.
As another side note, this work is compatible with the vision regarding interfacing with other hardware/software as described here: https://github.com/zkSNACKs/WalletWasabi/discussions/6467
Things like providing the `ownership proof` for  a given `scriptPubKey` is something that has to be done by the device (physical or logical, it doesn't really matter) that knows the corresponding private keys. The same is true for signing the …

[WabiSabi] CoinJoinClient interface simplification

---

WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiApiApplicationFactory.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiHttpApiIntegrationTests.cs

Fixes:
```
2022-01-24 08:04:52.748 [76] WARNING	Arena.Log (259)	Round (5d58ce5d9322ff70720a58116ac1fca08d40ecbcd1baae05685a9bbb5a1e1c4b): Signing phase failed, reason: 'System.NotSupportedException: FilePath is not set. Use SetFilePath to set it.
at WalletWasabi.Bases.ConfigBase.AssertFilePathSet() in WalletWasabi\Bases\ConfigBase.cs:line 31
at WalletWasabi.Bases.ConfigBase.ToFile() in WalletWasabi\Bases\ConfigBase.cs:line 110
at WalletWasabi.WabiSabi.Backend.WabiSabiConfig.MakeNextCoordinatorScriptDirty() in WalletWasabi\WabiSabi\Backend\WabiSabiConfig.cs:line 107
at WalletWasabi.WabiSabi.Backend.Rounds.Arena.StepTransactionSigningPhaseAsync(CancellationToken cancellationToken) in WalletWasabi\WabiSabi\Backend\Rounds\Arena.cs:line 243'.
```

`WabiSabiHttpApiIntegrationTests`: Fix NSE in `MultiClientsCoinJoinTestAsync`

---

WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs

The log message was not true. Sometimes it is possible to add blame script output despite that all Alices signaled readiness. For example when those small accepted losses accumulated from clients and reach the `AllowedOutputAmounts.Min`.
However, we can consider letting this amount go to the miners.

Better logs in AddBlameScript 

---

WalletWasabi.Tests/UnitTests/WabiSabi/Models/SerializationTests.cs
WalletWasabi/JsonConverters/Bitcoin/CoinJsonConverter.cs
WalletWasabi/JsonConverters/Bitcoin/CoinJsonConverter.cs.cs
WalletWasabi/WabiSabi/Models/Serialization/JsonSerializationOptions.cs

Fixes #6856.
The `NBitcoin.Coin` class was serialized with the default serializer and then all the properties were included.
```json
{
"isMalleable": false,
"canGetScriptCode": true,
"outpoint": "61FEF11BC15B0A9F37C8C72F595BE12D1FFE20CD2B2AE0490D37A9A5028C104E15000000",
"txOut": {
"scriptPubKey": "0 fb1667cc73c57c4dbf28f1ef667a1c174d7954fb",
"value": 177147
},
"amount": 177147,
"scriptPubKey": "0 fb1667cc73c57c4dbf28f1ef667a1c174d7954fb"
}
```
```json
{
"outpoint": "61FEF11BC15B0A9F37C8C72F595BE12D1FFE20CD2B2AE0490D37A9A5028C104E15000000",
"txOut": {
"scriptPubKey": "0 fb1667cc73c57c4dbf28f1ef667a1c174d7954fb",
"value": 177147
}
}
```
---------
`NBitcoin.Coin` is a thrid-party class and for that reason we cannot decorate its properties with `[JsonIgnore]` and while the popular wisdom in …

Do not serialize redundant properties in `NBitcoin.Coin`

---

WalletWasabi.Tests/UnitTests/TestWallet.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Integration/Participant.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiHttpApiIntegrationTests.cs
WalletWasabi/WabiSabi/Client/CoinJoinClient.cs

This PR simplifies the `MultiClientsCoinJoinTest` test by moving reusable logic from `Participant` class  to `TestWallet` class. `TestWallet` is a tiny wallet similar to the Bitcoin Core `MiniWallet` that is used for testing.
By playing with this I found a few bugs that worth to mention:
* [BUG] When clients register more than one output using the same scriptPubKey the coordinator consolidates them in a single output but the client's sanity check was not aware of that behavior and detected there were missing outputs and for that reason it aborted and didn't sign the coinjoin transaction. **FIXED**
* [BUG] in `CoinJoinClient::SelectCoinsForRound` there are many ways end up with a `Sequence contains no elements` exceptions. The one that repeated more happens when `groups` is empty. I didn't …

[WabiSabi] Refactor MultiClient test and fix bug

---

WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiHttpApiIntegrationTests.cs

`SoloCoinJoinTest` fails too often. Lets try by increasing the timeout just a bit.

Increase a 10% the `SoloCoinJoinTest` timeout

---

WalletWasabi.Tests/RegressionTests/CoinJoinTests.cs
WalletWasabi.Tests/UnitTests/BlockchainAnalysis/CoinJoinAnonscoreTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Client/ArenaClientTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiHttpApiIntegrationTests.cs

Write "coinjoin" with small letters unless it starts a sentence or is part of name etc.
Breaking down #7047 in to smaller pieces.

Fix typos in test files

---

WalletWasabi/CoinJoin/Client/Clients/AliceClientBase.cs
WalletWasabi/CoinJoin/Coordinator/Rounds/CoordinatorRound.cs
WalletWasabi/WabiSabi/Backend/Rounds/Arena.Partial.cs
WalletWasabi/WabiSabi/Client/CoinJoinClient.cs

Write "coinjoin" with small letters unless it starts a sentence or is part of name etc.
Includes spacing changes in WalletWasabi/CoinJoin/Coordinator/Rounds/CoordinatorRound.cs by my Visual Studio.
Breaking down #7047 in to smaller pieces.

Fix typos in WabiSabi and CoinJoin folders

---

WalletWasabi.Backend/Controllers/BlockchainController.cs
WalletWasabi.Backend/Controllers/ChaumianCoinJoinController.cs
WalletWasabi.Backend/wwwroot/css/style.css
WalletWasabi.Backend/wwwroot/index.html

Write "coinjoin" with small letters unless it starts a sentence or is part of name etc.
Desktop with small "d" unless it starts a sentence.
Breaking down #7047 in to smaller pieces.

Fix typos in backend files

---

WalletWasabi/WabiSabi/LoggerTools.cs

This makes the log lines contain the place where the logging command was called.
Found when trying to understand why #7080 does not passes tests.

`LoggerTools`: Pass `callerMemberName`.

---

WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs

This PR fixes the confusion log message on the backend when nobody is paying fees in the round. 
The current master will display this warning message: 
`2022-01-24 13:34:02.415 [93] WARNING	Arena.Log (392)	Round (): Coordinator fee wasn't taken, because it was too small: coordinationFee: -62.`
However nothing to warn about, so after this PR the message will be:
` Coordination fee wasn't taken, because it was free for everyone. Hurray!`
Better to review without whitespace changes: https://github.com/zkSNACKs/WalletWasabi/pull/7109/files?diff=split&w=1

Proper backend log message when the round is free for everyone

---

WalletWasabi.Fluent/Controls/LineChart.cs

Requires https://github.com/zkSNACKs/WalletWasabi/pull/7129
The https://github.com/AvaloniaUI/Avalonia/commit/c04f90685fe0e89c4579d4014cfc9e74b2552369 fixed text alignment issue in avalonia 0.10.12 
This PR remove workaround for above text alignment.

Fix LineChart.DrawYAxisLabels after 0.10.12 Avalonia update

---

WalletWasabi.Packager/Program.cs

Git is not a required component for packager - it is something good to have. CI was failing because of this but in any case, it is better to handle these calls in an error-prone way - this PR does that. 
Fixes: https://github.com/zkSNACKs/WalletWasabi/pull/6810#issuecomment-1023207914

Fix Packager if Git is missing

---

WalletWasabi/WabiSabi/Client/CoinJoinManager.cs

This PR adds `IsUserInSendWorkflow` and extracts out AutoCJ conditions into a separate function. The UI part is not connected yet but @danwalmsley said adding a boolean is the way to do this - so they will set it externally. 
- `IsUserInSendWorkflow` is not wallet-dependant but a global one. I think it makes sense to save resources on sending and not start CoinJoin in the background even if it is another wallet. 
See https://github.com/zkSNACKs/WalletWasabi/issues/7122 - Do not start while sending

When To Mix - Do not start while sending

---

WalletWasabi.Fluent/Views/AddWallet/AddWalletPageView.axaml

Fixes #7154 
Decrease MaxLength to 50 characters at add wallet, so wallet name is always properly displayed

Decrease MaxLength to 50 characters, at add wallet

---

WalletWasabi.Backend/Controllers/WabiSabiController.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Backend/Rounds/MultipartyTransactionStateTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Client/ArenaClientTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiApiApplicationFactory.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiHttpApiIntegrationTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Models/MultipartyTransactionTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Models/RoundStateUpdaterTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Models/SerializationTests.cs
WalletWasabi/WabiSabi/Backend/PostRequests/IWabiSabiApiRequestHandler.cs
WalletWasabi/WabiSabi/Backend/Rounds/Arena.Partial.cs
WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
WalletWasabi/WabiSabi/Client/ArenaClient.cs
WalletWasabi/WabiSabi/Client/RoundStateUpdater.cs
WalletWasabi/WabiSabi/Client/WabiSabiHttpApiClient.cs
WalletWasabi/WabiSabi/Models/MultipartyTransaction/ConstructionState.cs
WalletWasabi/WabiSabi/Models/MultipartyTransaction/MultipartyTransactionState.cs
WalletWasabi/WabiSabi/Models/MultipartyTransaction/SigningState.cs
WalletWasabi/WabiSabi/Models/RoundState.cs
WalletWasabi/WabiSabi/Models/RoundStateRequest.cs
WalletWasabi/WabiSabi/Models/Serialization/CoinJoinEventJsonConverter.cs
WalletWasabi/WabiSabi/Models/Serialization/GenericInterfaceJsonConverter.cs
WalletWasabi/WabiSabi/Models/Serialization/JsonSerializationOptions.cs
WalletWasabi/WabiSabi/Models/Serialization/MultipartyTransactionStateJsonConverter.cs

This PR allows the clients to fetch updates (news) regarding to new inputs and outputs from the coordinator instead of fetch everything all the time. As a result the bandwidth requirements are much lower.
The WabiSabi coinjoin clients need to be updated regularly about the status of the different coordinator's rounds. These updates contains information such as the current phase of the round and the registered inputs and outputs, among other data. The component responsible for keeping the coinjoin clients updated with this information is the `RoundStateUpdater` which hits the coordinator frequently (5 seconds) and fetches the rounds.
In a real-world(TM) scenario where the number of inputs and outputs in a coinjoin transaction can be in the order of hundreads, fetching all that data with …

[WabiSabi] Stream status 4

---

WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiHttpApiIntegrationTests.cs

This PR adds two log lines to `SoloCoinJoinTestAsync` just to confirm (or discard) the assumption that it fails because of NBitcoin.SCrypt.

Add log to `SoloCoinjoinTestAsync`

---

WalletWasabi.Fluent.Desktop/packages.lock.json
WalletWasabi.Fluent/ViewModels/Wallets/Send/SendViewModel.cs
WalletWasabi.Fluent/packages.lock.json
WalletWasabi.Packager/packages.lock.json
WalletWasabi/BestEffortEndpointConnector.cs
WalletWasabi/Blockchain/Transactions/TransactionFactory.cs
WalletWasabi/WabiSabi/Models/MultipartyTransaction/ConstructionState.cs
WalletWasabi/WalletWasabi.csproj
WalletWasabi/Wallets/PasswordFinder/PasswordFinderHelper.cs
WalletWasabi/packages.lock.json

#7058 recently [touched](https://github.com/zkSNACKs/WalletWasabi/pull/7058/files#diff-23f66197c41b2d2d7b25e00ac706928acd1eebc3b580f3692973acf810133e9eR143) `IndexStore`. I have found no significant impact of that change. However, it lead me to thinking how to speed up index loading a bit because [it takes 4 seconds on my machine to load the mature index](https://github.com/zkSNACKs/WalletWasabi/blob/756f6e930ae5ea317552b91501aa9e9c14c456d1/WalletWasabi/Stores/IndexStore.cs#L143). The startup of the wallet is impacted by that so it might be useful to invest a bit time to shave some overhead off.
One quite easy way to make it faster is to switch to the newer NBitcoin version because it contains the following commit:
https://github.com/MetacoSA/NBitcoin/commit/1a3f5c63ec7a596f2e8af3b702c4d27 …

Upgrade NBitcoin to `6.0.19` from `6.0.8`

---

WalletWasabi/Blockchain/Transactions/TransactionFactory.cs

@nopara73 mentioned that this should be executed only for payjoin tx.
> > I wonder whether builder.CoinFinder = (outpoint) => psbt.Inputs.Select(x => x.GetCoin()).Single(x => x?.Outpoint == outpoint)!; should be executed only when there is actually a payjoin involved. But I don't know an answer for that.
> 
> It is. The "fix" happened in the `TransactionFactory`.
https://github.com/zkSNACKs/WalletWasabi/pull/7136#issuecomment-1030771671
The `HonestPayjoinServerTest` does pass.

Execute 'builder.CoinFinder' when payjoin tx only

---

WalletWasabi.Tests/UnitTests/Filters/IndexStoreTests.cs
WalletWasabi/Backend/Models/FilterModel.cs
WalletWasabi/Blockchain/BlockFilters/StartingFilters.cs
WalletWasabi/Blockchain/Blocks/SmartHeader.cs

This PR improves startup time by shaving off a bit of work when loading mature index. The PR builds on knowledge that I got when working on #7136.
| git commit | elapsed time (lower is better)| 
|---------|-----------------|
| master |  5.22 seconds |
| with 1st commit |  4.42 seconds |
| with 2nd commit |  4 seconds |
note: Measured in `Debug` configuration (not `Release` configuration). The time it tooks in `Release` configuration with the 2nd commit is `3.71` seconds.
I know, we have new priorities now, but I did not want to lose this changes as they seem useful.

Optimize startup time a bit more

---

WalletWasabi/Crypto/CoinJoinInputCommitmentData.cs

This PR changes the way `coordinatorIdentifier` is prefixed with its length in `CoinJoinInputCommitmentData`:
* Before this PR, the class used `BitConverter` to convert the length of `coordinatorIdentifier` to bytes. This is not recommended when transmitting the bytes between computers, since the bytes depend on computer architecture. See [this](https://docs.microsoft.com/en-us/dotnet/api/system.bitconverter?view=net-6.0):
> Because the return value of some methods depends on system architecture, be careful when transmitting byte data beyond machine boundaries: [...]
* After this PR, the class uses [variable length integer](https://en.bitcoin.it/wiki/Protocol_documentation#Variable_length_integer) that is platform independent, widely used in Bitcoin protocol and supported probably by …

Use variable length integer in CoinJoinInputCommitmentData

---

WalletWasabi/Crypto/CoinJoinInputCommitmentData.cs

I found a little inconsistency in encoding of round identifier (of type `uint256`):
* The class `Uint256JsonConverter` that converts `uint256` to json and vice verse uses big-endian encoding.
* The class `CoinJoinInputCommitmentData` that concatenates a coordinator identifier with a round identifier uses little-endian encoding.
This PR fixes `CoinJoinInputCommitmentData` so it uses big endian too.
I hope it won't break any tests: I have some issues with running the tests on my computer and your Azure pipelines doesn't seem to work properly.

Reverse byte order of round id in commitment data

---

WalletWasabi.Fluent/Views/Wallets/WalletSettingsView.axaml

This PR adds a separator and removes the caption text because IMO it just clutters that dialog.

[Fluent] Beautify wallet settings dialog

---

WalletWasabi.Fluent/Views/Wallets/Send/SendFeeView.axaml

At the Transaction fee slider, the vertical axis should be named `Fee Rate` instead of "Increasing Cost".

Txfee slider: Name vertical axis "Fee Rate"

---

WalletWasabi/Blockchain/Analysis/BlockchainAnalyzer.cs
WalletWasabi/Blockchain/TransactionProcessing/ProcessedResult.cs
WalletWasabi/Blockchain/Transactions/TransactionHistoryBuilder.cs
WalletWasabi/Extensions/NBitcoinExtensions.cs

Fixes #7167
_This PR slightly improves the functionality of the `isLikelyCoinjoin()` function._
**Related to label problems.**
Here we prevent merging labels in case of a CoinJoin transaction.
We don't want to merge them, as in theory, the exact opposite happens, as a coin will be less known by the people after CJ.

Improve `isLikelyCoinjoin`

---

WalletWasabi/Extensions/NBitcoinExtensions.cs

I made this change before merge of https://github.com/zkSNACKs/WalletWasabi/pull/7215, but somehow it was missing. Fixed.

Add missing output check

---

WalletWasabi.Documentation/DeveloperFeatures.md
WalletWasabi.Fluent/Views/MainWindow.axaml

Pressing (left)CTRL + D + C on the wallet home screen will pop the dialog. The old was conflicting on Qubes. Resolves https://github.com/zkSNACKs/WalletWasabi/pull/7205#pullrequestreview-874436625

Change key combo for Coinlist

---

WalletWasabi.Fluent/ViewModels/AddWallet/RecoverWalletViewModel.cs
WalletWasabi/Blockchain/Keys/KeyManager.cs
WalletWasabi/Blockchain/Keys/WalletGenerator.cs

The correct behavior of autocoinjoin is for new and recovered wallets it should default to true, but for existing wallets it should default to false to keep the behavior of the old wasabi wallets unchanged and not cause surprises for old users.

Make autoCJ default sophisticated

---

WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionPreviewViewModel.cs

We broke it here https://github.com/zkSNACKs/WalletWasabi/pull/7070.
If the user wants to change their pockets when first got to the preview screen, and then they change their mind by pressing back button. The `BuildPrivacySuggestionsAsync` didn't get called.

generate suggestions even if user doesn't change the pockets

---

WalletWasabi.Fluent/Models/Windows/DirectShow.cs
WalletWasabi.Fluent/Models/Windows/WindowsCapture.cs

There were a lot of warnings and errors in files `DirectShow.cs` & `WindowsCapture.cs`. Previusly we disabled the warnings, now I managed to get rid of the most "famous" ones:
- **IDE0011** : _Add braces_
- **IDE0019** : _Use pattern matching_
- **IDE1006** : _Naming Styles_
Most of the warnings got resolved, only some IDE1006 problems stayed that I couldn't manage to get rid of.

Get rid of most of DirectShow warnings

---

WalletWasabi/WabiSabi/Client/CoinJoinManager.cs

This log message was always confusing for me, I thought it indicates that a coinjoin round was successful.
So I propose to change it to:
`Wallet: TestWallet - Coinjoin client finished!` instead of `Wallet: TestWallet - Coinjoin client finished successfully!` to be less confusing.

[Trivial] Improve confusing log message

---

WalletWasabi.Tests/UnitTests/UserInterfaceTest/PocketSelectionTests.cs

[Fact] attribute was mistakenly removed by https://github.com/zkSNACKs/WalletWasabi/commit/ec9779f0aa604371d358d4e6fe6cf770bfeb34c6
This PR adds it back, and fixes some warnings (unnecessary assignment).

[Trivial] Mark method as a fact

---

WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiHttpApiIntegrationTests.cs

This is a very trivial PR.
https://github.com/zkSNACKs/WalletWasabi/commit/8e97184ab4aadc67742b974d9b138fec1214d102 should be reverted. I added it to test that #7288 fixes the `SoloCoinJoinTestAsync` issue.

[Trivial] User 'Assert.Equal' instead of 'Assert.True'

---

WalletWasabi.Fluent/App.axaml
WalletWasabi.Fluent/ViewModels/ApplicationViewModel.cs
WalletWasabi.Fluent/ViewModels/HelpAndSupport/AboutViewModel.cs
WalletWasabi.Fluent/Views/HelpAndSupport/AboutView.axaml

Replaces the "About Avalonia" entry in global app menu in macOS and KDE based Linux distros with our own that triggers the About page dialog.

[Fluent] macOS/KDE-Linux default AppMenu items replacement 

---

WalletWasabi.Fluent/Rpc/WasabiJsonRpcService.cs
WalletWasabi.Fluent/ViewModels/WalletManagerViewModel.cs
WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItems/CoinJoinsHistoryItemViewModel.cs
WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryViewModel.cs
WalletWasabi.Tests/UnitTests/Transactions/TransactionProcessorTests.cs
WalletWasabi/Blockchain/TransactionProcessing/ProcessedResult.cs
WalletWasabi/Blockchain/Transactions/SmartTransaction.cs
WalletWasabi/Blockchain/Transactions/TransactionHistoryBuilder.cs
WalletWasabi/Blockchain/Transactions/TransactionSummary.cs
WalletWasabi/Extensions/NBitcoinExtensions.cs

Closes https://github.com/zkSNACKs/WalletWasabi/pull/7302
Closes https://github.com/zkSNACKs/WalletWasabi/pull/7291
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/7277 (but not satisfactorily, explained here: https://github.com/zkSNACKs/WalletWasabi/pull/7302#issue-1139694405)
This PR perfects the `IsLikelyCoinjoin` method. It is now `IsOwnCoinjoin`. No "likely" there and no general coinjoin, but own coinjoin there.
This is more dangerous, but it fixes more display issues. The only one left that may bother people on testnet is that self spend coinjoins aren't coinjoins, but that's not a bug, it's a feature. If someone does a self coinjoin, then that's not really a coinjoin.

IsLikelyCoinjoin -> IsOwnCoinjoin 

---

WalletWasabi/WabiSabi/Client/CoinJoinClient.cs

This PR makes the Wasabi client to do not trust on the min allowed output value provided by the coordinator and only consider rounds with min allowed output below a threshold.

Ignore rounds w/ too high min allowed output

---

WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionPreviewViewModel.cs

I made a mistake here https://github.com/zkSNACKs/WalletWasabi/pull/7304/. If the BnB algorithm is running for seconds, the dialog is blocked until then.

do not block dialog while BnB is running

---

WalletWasabi.Fluent/Controls/ContentArea.axaml

The layout problem mentioned [here](https://github.com/zkSNACKs/WalletWasabi/pull/7314#issuecomment-1043174558) was not specific to that particular screen, but rather a general problem found in the `ContentArea` control, as evidenced by the screenshot:
Where depending on whether the `Continue` button is visible there is an additional margin causing an undesired layout change.
This PR removes the additional margin thus fixing the problem.

[VDG] ContentArea Layout problem fix

---

WalletWasabi.Fluent/Views/AddWallet/LegalDocumentsView.axaml

cc @zkSNACKs/visual-design-group 
before:
after:

[Fluent] Use monospaced font for legal text.

---

WalletWasabi.Fluent/ViewModels/Wallets/Send/PrivacySuggestionsFlyoutViewModel.cs
WalletWasabi/Blockchain/TransactionBuilding/BranchAndBound.cs
WalletWasabi/Blockchain/TransactionBuilding/ChangelessTransactionCoinSelector.cs

Same intention as #7328
It felt weird that we use cancellation token, but do not throw `OperationCanceledException`.
With this PR we can throw the exception and still get back the best result the algorithm found so far.

Bnb: Throw exception at cancellation request

---

WalletWasabi/BitcoinCore/Mempool/MempoolMirror.cs

Previous to this PR the `GetRawTransactionsAsync` is called with an enumerable that is modified by the caller.
```
Feb 22 14:29:24 WalletWasabi walletwasabi-backend[21295]: 2022-02-22 14:29:24.700 [80] ERROR#011PeriodicRunner:ExecuteAsync (100)#011System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
Feb 22 14:29:24 WalletWasabi walletwasabi-backend[21295]:    at System.Collections.Generic.Dictionary`2.KeyCollection.Enumerator.MoveNext()
Feb 22 14:29:24 WalletWasabi walletwasabi-backend[21295]:    at System.Collections.Generic.HashSet`1.UnionWith(IEnumerable`1 other)
Feb 22 14:29:24 WalletWasabi walletwasabi-backend[21295]:    at System.Collections.Generic.HashSet`1..ctor(IEnumerable`1 collection, IEqualityComparer`1 comparer)
Feb 22 14:29:24 …
```

Fix server-side exception

---

WalletWasabi.Fluent/Controls/TagsBox.axaml.cs

Fixes : #7050 
Mention : #7169

Fixing CheckIsCurrentTextValid execution when the dialog is closing (Results in crash)

---

WalletWasabi/Blockchain/Keys/KeyManager.cs

Lower `DefaultPlebStopThreshold` on `Client` side, so the Testnet Release users can enjoy auto CJ, even if their Faucet gave them low amount of `tBTC`.
Idea came from @MaxHillebrand

Lower DefaultPlebStopThreshold on Client side

---

WalletWasabi.Fluent/Views/Wallets/Home/History/Columns/IndicatorsColumnView.axaml

Nitpick
Everywhere else it is lower cases

[VDG] Coinjoin writing ToolTip

---

WalletWasabi/WabiSabi/Client/CoinJoinManager.cs

Before this PR the filter to determine which wallet isn't tracked was done based on  the `trackedCoinJoins` which was modify in a `foreach` loop causing coinjoins to be cancelled.

Fix coinjoin tracking

---

WalletWasabi.Fluent/ViewModels/Wallets/CoinJoinStateViewModel.cs

Fixes crash when opening a wallet.
The old configuration adds state re-entrancy, that isn't allowed.

Fix bad StateMachine configuration

---

WalletWasabi/Helpers/Constants.cs

To make sure we don't re-use addresses. 
ZeroLink and WabiSabi use the same xpub, this might cause us trouble in the future.
After this:
- Need to save the seed words in a cold storage.
- Change the `WabiSabiConfig.json` on the servers.

Change WabiSabi coordinator xpub

---

WalletWasabi.Tests/UnitTests/TestWallet.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Integration/Participant.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiHttpApiIntegrationTests.cs

Reenable `MultiClientsCoinJoinTestAsync` (The most important test we have). To do that `TestWallet` had been modified to behave as a HD wallet and generate different keys/scripts.

Make TestWallet behave like a HD wallet

---

WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/PrivacyControlTileViewModel.cs

https://github.com/zkSNACKs/WalletWasabi/pull/7431:
> A fine touch on the wallet privacy score calculation. This PR considers anonset weighted amounts instead of just amounts > privacy threshold. This results in better user experience, as initial anonset gains are barely shown in our current implementation and that can cause frustration:
> 
> ![image](https://user-images.githubusercontent.com/9156103/156399402-51f92587-27de-4a0c-a50f-85147ebfc19b.png)

[VDG] Privacy tile improvements

---

WalletWasabi.Fluent/Views/HelpAndSupport/LinkView.axaml

With this PR  the user can see what link is at the hyperlink when hovering over it with cursor.

[VDG] [Trivial] Action Center - About - Add ToolTip for link

---

WalletWasabi.Packager/Program.cs

Fixes #7427
Previously:
After installing the `Testnet Release` on a Linux distro, somehow you didn't have permission to run `wassabee`.
This PR makes sure that the executables are executable for everyone.
`chmod u+x some_file` will grant only the owner of that file execution permissions,
whereas `chmod +x some_file` will grant everyone execution permission.
How to test:
- Grab this PR and run the `Packager` project in a computer.
- Move the `.deb` file to another PC and install it.
- See that there is no permission errors and wassabee is runnable by default.

Fix wassabee permission on Linux distros

---

WalletWasabi.Fluent/Views/NavBar/NavBar.axaml

This adds a tooltip to clarify the meaning of the icon in the wallet item (Navigation Bar).

[VDG] [Trivial] Add coinjoining tooltip to CJ icon

---

WalletWasabi.Tests/UnitTests/Tor/TorSettingsTests.cs
WalletWasabi/Tor/Socks5/Models/Fields/OctetFields/RepField.cs
WalletWasabi/Tor/Socks5/Models/ReplyType.cs
WalletWasabi/Tor/TorSettings.cs

Contributes to #7434
The idea of this PR is to get more useful error codes. David's log provided in #7434 contains:
```log
2022-03-01 16:48:05.173 [39] WARNING	TorTcpConnectionFactory.ConnectToDestinationAsync (258)	Connection response indicates a failure. Actual response is: 'GeneralSocksServerFailure'. Request: 'testwnp3fugjln6vh5vpj7mvq3lkqqwjj3c2aafyu7laxz42kgwh2rad.onion:80'.
```
with this PR, it should report a more precise error code I believe. Thus we might be able to dig deeper into the issue.
* https://github.com/torproject/tor/blob/331b2aa34874d5ef57b45ff591e1f64b695ff06c/doc/man/tor.1.txt#L1581-L1627

Tor: Add `ExtendedErrors`

---

WalletWasabi.Tests/UnitTests/WabiSabi/Backend/AliceTimeoutTests.cs

It is OK to throw WabiSabiProtocolException. It is a rare case but if the conn-confirm request is in progress and the backend removed Alice already, then it will answer WabiSabiProtocolException. In most cases, the cancel kicks in thus getting OperationCanceledException.

Fix rarely failing test AliceTimesoutAsync 

---

WalletWasabi/WabiSabi/Client/CoinJoinClient.cs

based on https://github.com/zkSNACKs/WalletWasabi/pull/7529
I've also added a phase-specific timeout cancellationToken.

Improve CoinJoinClient by extracting OutputRegistration Phase related progress

---

WalletWasabi.Fluent/ViewModels/Wallets/Advanced/WalletCoins/WalletCoinsViewModel.cs
WalletWasabi.Fluent/Views/Wallets/Advanced/WalletStatsView.axaml

https://github.com/zkSNACKs/WalletWasabi/issues/7451#issuecomment-1059243688
Since these dialogs are for advanced users it makes sense to use the word UTXOs there.

[Trivial] [VDG] Add 'UTXOs' to wallet info dialog

---

WalletWasabi.Backend/Controllers/WabiSabiController.cs
WalletWasabi.Backend/Filters/LateResponseLoggerFilter.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/ConfirmConnectionTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterInputFailureTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterOutputTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RemoveInputTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/SignTransactionTests.cs
WalletWasabi/WabiSabi/Backend/Models/WrongPhaseException.cs
WalletWasabi/WabiSabi/Backend/Rounds/Arena.Partial.cs
WalletWasabi/WabiSabi/Backend/Rounds/TimeFrame.cs

Another implementation of https://github.com/zkSNACKs/WalletWasabi/pull/7561
Example:
`2022-03-17 15:26:22.052 [57] INFO       LateResponseLoggerFilter.OnException (18)       Request 'ReadyToSign' missing the phase 'OutputRegistration' by '00:00:08.4190598'. Round id '250505a8fc3b7633e3f6687042de6ee17e56e17f11d6db881a330d4ff7225cc5' is in phase 'TransactionSigning'.`

Loglatefancy

---

WalletWasabi.Backend/Controllers/WabiSabi/IdempotencyRequestCache.cs

Attempts to fix #7113
Alternative to #7569
Test code
This is a simple test case to demonstrate that an unobserved exception happens (should be useful for testing):
```cs
/// <summary>
/// Make sure an unobserved exception is thrown.
/// </summary>
[Fact]
public async Task UnobservedExceptionAsync()
{
TaskCompletionSource<string> tcs = new();
TaskScheduler.UnobservedTaskException += (sender, eventArgs) =>
{
tcs.TrySetResult($"Unobserved: {eventArgs.Exception.InnerException?.Message}");
};
_ = Task.Factory.StartNew(() =>
{
TaskCompletionSource experimentTcs = new();
experimentTcs.SetException(new Exception("Derp."));
// And then uncomment this.
// try {  await experimentTcs.Task.ConfigureAwait(false); } catch { }
});
await Task.Delay(2_000).ConfigureAwait(true);
GC.Collect(); …
```

`IdempotencyRequestCache`: Await task so that it's observed

---

WalletWasabi.Fluent/Views/Wallets/LoadingControl.axaml

Fixes a layout glitch that occurs when "downloading blockchain data" screen displays "% complete" text

[VDG] Fix Downloading map resize issue

---

WalletWasabi.Fluent/Behaviors/MainWindowPersistPositionBehavior.cs
WalletWasabi.Fluent/UiConfig.cs
WalletWasabi.Fluent/ViewModels/MainViewModel.cs
WalletWasabi.Fluent/Views/MainWindow.axaml

Fixes #6923 
Initial implementation. 
Stores MainWindow X, Y, Left and Width in UIConfig.json
Covers:
- Multi monitor scenarios
- if the secondary Monitor has been disabled between restarts and previous window location is no longer visible, main window will be centered on primary screen.
- DPI or screen resolution changes:
- if the window size exceeds screen size due to DPI or screen resolution changes between restarts, it will be maximized. The user can then choose another size and position

[VDG] Remember MainWindow Position

---

WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/PrivacyControlTileViewModel.cs
WalletWasabi.Fluent/Views/Wallets/Home/Tiles/PrivacyControlTileView.axaml

The current privacy level format is very confusing. It looks like the anonymity score of coins.
Master:
PR:

[Trivial] [VDG] Display privacy level in format ##%

---

WalletWasabi.Fluent/ViewModels/Wallets/Send/ConfirmLabelsDialogViewModel.cs
WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionPreviewViewModel.cs

In this PR the dialog below can be closed by pressing esc.
Since pressing ESC calls the `CancelCommand`, I had to reverse the logic to make it work.

[VDG] Allow labels dialog to be closed by pressing ESC

---

WalletWasabi/WabiSabi/Client/CoinJoinClient.cs

Fixes:
- AliceClients were disposed right after the ConnectionConfirmation phase. 
- Same Tor identity was used for all the AliceClients.
```
2022-03-21 22:22:10.196 [20] ERROR      CoinJoinManager.ExecuteAsync (187)      Wallet: `Test0312` - Coinjoin client failed with exception: Exception: WalletWasabi.Tor.Socks5.Exceptions.TorCircuitExpiredException: Exception of type 'WalletWasabi.Tor.Socks5.Exceptions.TorCircuitExpiredException' was thrown.
at WalletWasabi.Tor.Socks5.Pool.TorHttpPool.ObtainFreeConnectionAsync(HttpRequestMessage request, ICircuit circuit, CancellationToken token) in WalletWasabi\Tor\Socks5\Pool\TorHttpPool.cs:line 236
at WalletWasabi.Tor.Socks5.Pool.TorHttpPool.SendAsync(HttpRequestMessage request, ICircuit circuit, CancellationToken cancellationToken) in …
```

Use different AliceClients for every coin

---

WalletWasabi/WabiSabi/Client/AmountDecomposer.cs
WalletWasabi/WabiSabi/Client/Decomposer.cs

- Removed static from decomposer, it was modified by multiple clients at the same time. 
- Add check to not try to decompose in case of maxNumberOfOutputsAllowed is less than 2.

Remove static from decomposer

---

WalletWasabi.Fluent/Extensions/TimeSpanMixin.cs
WalletWasabi.Fluent/Helpers/MathUtils.cs
WalletWasabi.Fluent/ZXing/MathUtils.cs
WalletWasabi.Tests/UnitTests/Extensions/TimeSpanMixinTests.cs
WalletWasabi.Tests/UnitTests/Helpers/MathUtilsTests.cs

Improves the time estimation rounding in labels.
This is an improvement over
https://github.com/zkSNACKs/WalletWasabi/pull/7570#issuecomment-1076299249
The following rounding is made for time spans:
- When it contains a number of days, it will round to full days
- Else if it contains hours, it will take full hours and round minutes in 30 time intervals: 
Eg. 
8:10h => 8:00h
8:35h => 8:30h
8:50h => 9:00h 
- Else, it will take full minutes

[VDG] Improved rounding

---

WalletWasabi.Backend/wwwroot/index.html

According to https://github.com/dotnet/core/blob/main/release-notes/3.1/3.1-supported-os.md#macos the Mac OS X supported version for .NET Core 3.1 should be 10.15+

Update the required macOS version on website

---

WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModel.cs
WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
WalletWasabi/WabiSabi/Client/WalletStatusChangedEventArgs.cs

This PR unifies the status event and event args used by the coinjoin manager. Basically removes one of the events.
@danwalmsley could you please take a look? How can I test it. 
Btw, I need to clean the code a bit before starting the redesign for Start[Manual|Auto], Stop and that's why I am doing this.

Unify source of coinjoin related events

---

WalletWasabi/WabiSabi/Client/CoinJoinClient.cs

This PR corrects the calculation of the total and the effective differences to not get negative values.
With the 2nd commit (amounts displayed with trailing zeros):
```
Input total: +0.00010000 Eff: +0.00009862 NetwFee: +0.00000138 CoordF: 0.00000000
Outpu total: +0.00008192 Eff: +0.00008130 NetwFee: +0.00000062
Total diff : +0.00001808
Effec diff : +0.00001732
Total fee  : +0.00000200
```
Instead of:
```
Input total: +0.0001 Eff: +0.00009862 NetwFee: +0.00000138 CoordF: 0.00
Outpu total: +0.00008192 Eff: +0.0000813 NetwFee: +0.00000062
Total diff : -0.00001808
Effec diff : -0.00001732
Total fee  : +0.000002
```

[Trivial] Correct calculation for cj debug information

---

WalletWasabi/Io/DigestableSafeIoManager.cs
WalletWasabi/Io/SafeIoManager.cs
WalletWasabi/Stores/IndexStore.cs

The idea of testing this PR is:
1. Open `C:\Users\USER\AppData\Roaming\WalletWasabi\Client\BitcoinStore\TestNet\IndexStore` folder
2. Copy `MatureIndex.dat` somewhere as a backup + delete non-trivial amount of trailing lines (say 10000) so that it needs to be re-downloaded. 
3. `C:\Users\USER\AppData\Roaming\WalletWasabi\Client\BitcoinStore\TestNet\IndexStore` delete all files from this folder and copy your `MatureIndex.dat` file here.
4. Run WW with first, second and third commit respectively and watch for `TODO-DELETE-ME: Total time:` numbers in `Logs.txt`.
Numbers on my machine for testnet mature index:
| git commit | elapsed time (lower is better)| 
|---------|-----------------|
| 1st commit (baseline) |  1.3329037 seconds |
| 2nd commit |  1.0063391 seconds (25% faster) |
| 3rd …

Optimize mature index appending

---

WalletWasabi.Tests/UnitTests/WabiSabi/Client/AmountDecomposerTests.cs
WalletWasabi/WabiSabi/Backend/WabiSabiConfig.cs
WalletWasabi/WabiSabi/Client/AmountDecomposer.cs
WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
WalletWasabi/WabiSabi/ProtocolContants.cs

While coinjoining we can see that every new credential reissuance request takes more time than the previous one.
It seems the coordinator cannot keep up with the amount of work required to reissue the credentials and that makes the reissuance requests to take more and more time to complete. 
The new max amount per Alice is 1,343.75 BTCs.
There is not good reason for any specific number and requires to be tested and validated in real world. Take into account that while it is possible to reduce it even further, at the extreme it become really inexpensive in CPU terms, this is not THE solution because the real problem is the coordinator is single threaded at this point.

[WabiSabi] Reduce the `RangeProof` by 5 bits

---

WalletWasabi/Crypto/Randomness/InsecureRandom.cs

I was looking for the reason why the tests `TimeoutSufficientPeersAsync` and `TimeoutInsufficientPeersAsync` nondeterministically fails with:
```
[xUnit.net 00:00:04.75]     TimeoutInsufficientPeersAsync [FAIL]
Failed TimeoutInsufficientPeersAsync [3 s]
Error Message:
WalletWasabi.WabiSabi.Crypto.WabiSabiCryptoException : Serial number reused
Stack Trace:
at WalletWasabi.WabiSabi.Crypto.CredentialIssuer.HandleRequest(ICredentialsRequest registrationRequest) in WalletWasabi/WabiSabi/Crypto/CredentialIssuer.cs:line 170
at WalletWasabi.WabiSabi.Crypto.CredentialIssuer.<>c__DisplayClass27_0.<HandleRequestAsync>b__0() in WalletWasabi/WabiSabi/Crypto/CredentialIssuer.cs:line 102
at System.Threading.Tasks.Task`1.InnerInvoke()
at System.Threading.Tasks.Task.<>c.<.cctor>b__271_0(Object obj)
at …
```

Thread safe random number generator

---

WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionPreviewViewModel.cs

fixes https://github.com/zkSNACKs/WalletWasabi/issues/7648
BnB cancellation was called immediately when the user pressed the `Confirm` button, which caused a crash in the case when the user canceled the confirmation dialog and tried to modify something (something that cause a rebuild).
I moved the cancellation call after the broadcasting because if that finishes successfully we can make sure there is no need anymore for the BnB.

[VDG] Call BnB cancellation when it is safe

---

WalletWasabi/WabiSabi/Client/CoinJoinManager.cs

In case the UI is not caring about cancellationToken at least cancel the while loop when we quit the software. The change makes sense also when Wasabi is used with the RPC.

Makes sure to stop StartAutomaticallyAsync

---

WalletWasabi.Fluent/Views/HelpAndSupport/AboutView.axaml

For consistency, everywhere in the GUI `advanced` is displayed at the bottom
Current
This PR

[VDG] Help&Support - Move Advanded Information to the bottom

---

WalletWasabi/Nito/.editorconfig

Related to #7595
Number of warnings seems to drop by 20 (477 -> 457).
* https://til.cazzulino.com/dotnet/disable-diagnostic-analyzers-for-entire-folder-submodules

More correct `.editorconfig` for `WalletWasabi/Nito`

---

WalletWasabi/Gma/.editorconfig

Similar to #7664 and #7677.
End result[^1]: 457 warnings -> 449 warnings
[^1]: I don't vouch for the `.editorconfig` being "minimal". Some lines might be extra but I don't think we should spend more time on this. In this case I think we just want to get the job done.

Add `.editorconfig` for the external `Gma` library

---

WalletWasabi.Fluent/Controls/CurrencyEntryBox.axaml.cs

Master:
the Paste command inside the `ContextMenu` of the amount input in the send view is always disabled, since it's bound to a "ModifiedPaste" command which doesn't really exist in the Control.
This PR:
adds the missing command thus making the `ContextMenu` work properly
Should play nicely with #7690

[VDG] [Trivial] Fixes Paste command not working in CurrencyEntryBox

---

WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItems/CoinJoinsHistoryItemViewModel.cs
WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItems/HistoryItemViewModelBase.cs
WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryViewModel.cs

When we were using `DataGrid` and performance was questionable it made sense to not clear all the items from the `DataGrid` but just update the ones that changed. The downside of it was that sometimes the newly received raw history list was different compared to the previous one (CJ transaction detected as normal or vice versa, outgoing amount detected as incoming, etc), and it caused exceptions and weird information in the list.
With the new `TreeDataGrid` control, all this logic can be removed since the performance is way better and there is no benefit to having them, rather just a complex code and maintenance burden. By this, there won't be exceptions and different information.
Although there is still something to improve somewhere because the cases above should not happen.

[VDG] Transaction History - huge cleanup

---

WalletWasabi.Fluent/Converters/WindowStateAfterStartJsonConverter.cs
WalletWasabi/JsonConverters/KeyPathJsonConverter.cs
WalletWasabi/JsonConverters/NetworkJsonConverter.cs
WalletWasabi/JsonConverters/OutPointAsTxoRefJsonConverter.cs
WalletWasabi/JsonConverters/OutPointJsonConverter.cs
WalletWasabi/JsonConverters/PubKeyJsonConverter.cs
WalletWasabi/JsonConverters/SmartLabelJsonConverter.cs
WalletWasabi/JsonConverters/Timing/TimeSpanJsonConverter.cs
WalletWasabi/JsonConverters/TransactionJsonConverter.cs
WalletWasabi/JsonConverters/Uint256JsonConverter.cs
WalletWasabi/JsonConverters/UnblindedSignatureJsonConverter.cs
WalletWasabi/WabiSabi/Crypto/Serialization/GroupElementJsonConverter.cs
WalletWasabi/WabiSabi/Crypto/Serialization/ScalarJsonConverter.cs
WalletWasabi/WabiSabi/Models/Serialization/OwnershipProofJsonConverter.cs
WalletWasabi/WabiSabi/Models/Serialization/WitScriptJsonConverter.cs

Recreated #7587 but without [RoundStateResponseJsonConverter.cs](https://github.com/zkSNACKs/WalletWasabi/pull/7587/files#diff-60daa71b531cde53a0c042c863b05d56783bf290f8abac83d0824e9818faa7b2) which caused an issue that lead to #7665.

Switch JsonConverters from 'JsonConverter' to 'JsonConverter<T>'

---

WalletWasabi.Fluent/App.axaml
WalletWasabi.Fluent/Controls/ClipboardCopyButton.axaml
WalletWasabi.Fluent/Controls/ClipboardCopyButton.axaml.cs
WalletWasabi.Fluent/Controls/PreviewItem.axaml
WalletWasabi.Fluent/Controls/PreviewItem.axaml.cs
WalletWasabi.Fluent/Views/TransactionBroadcasting/BroadcastTransactionView.axaml
WalletWasabi.Fluent/Views/Wallets/Advanced/WalletInfoView.axaml
WalletWasabi.Fluent/Views/Wallets/Advanced/WalletStatsView.axaml
WalletWasabi.Fluent/Views/Wallets/Home/History/CoinJoinDetailsView.axaml
WalletWasabi.Fluent/Views/Wallets/Home/History/TransactionDetailsView.axaml
WalletWasabi.Fluent/Views/Wallets/Send/TransactionSummary.axaml

This replaces the workaround introduced in https://github.com/zkSNACKs/WalletWasabi/pull/7578 with a proper solution.
- The logic has been reviewed to improve the design and simplify it.
- The clipboard copy logic has been segregated into a different specialized control `ClipboardCopyButton` that will enable us to better adhere to the SRP.
~~- Improved UX: when the user copies the text to the clipboard, a small feedback popup appears showing "Copied" for 2 seconds and disappears. This behavior is similar a many applications/websites like GitHub's copy repo URL button.~~
- Usage of `PrewiewItem` is now consistent in transaction detail views.
- Eliminated the need to pass `CommandParameter`'s, that makes code less obvious.
https://user-images.githubusercontent.com/3109851/160582342-2bcef3e1- …

[VDG] Fix SubscribeAsync workaround in PreviewItem

---

WalletWasabi.Backend/Controllers/ChaumianCoinJoinController.cs

I understand the file is legacy and will be removed in the future, so we can just ignore nullability warnings here.
363 warnings -> 353 warnings

`ChaumianCoinJoinController`: Suppress warnings.

---

WalletWasabi.Fluent/Controls/FadeOutTextBlock.cs
WalletWasabi.Fluent/Views/NavBar/NavBar.axaml

Make the header text's fadeout a little less aggressive.
cc @MaxHillebrand @zkSNACKs/visual-design-group

Adjust wallet header text fade out

---

WalletWasabi.Backend/Startup.cs

The compiler doesn't realize that `Global` is registered to be disposed during shutdown, because it's out of the scope of creation.

Add warning suppress in `Startup.cs`

---

WalletWasabi.Tests/UnitTests/TestWallet.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Client/AmountDecomposerTests.cs
WalletWasabi/Helpers/Constants.cs
WalletWasabi/WabiSabi/Client/CoinJoinClient.cs

This PR is a part of a larger changes that I'm going to do in a near future (see https://github.com/trezor/WalletWasabi/commit/eea7ae9d092895c057c635d6b919d75982360aa5). Until that it would helps us if would merge this PR so we can avoid complicated rebase.

Rename P2wpkhOutputSizeInBytes to P2wpkhOutputVirtualSize

---

WalletWasabi.Backend/Global.cs
WalletWasabi.Tests/Helpers/ArenaBuilder.cs
WalletWasabi.Tests/UnitTests/CoinjoinIdStoreTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Backend/ConfigTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Backend/CoordinatorTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterInputSuccessTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Backend/RoundCreationTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiApiApplicationFactory.cs
WalletWasabi/WabiSabi/Backend/Rounds/Arena.Partial.cs
WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
WalletWasabi/WabiSabi/Backend/Rounds/CoinJoinStorage/CoinJoinIdStore.cs
WalletWasabi/WabiSabi/Backend/Rounds/CoinJoinStorage/ICoinJoinIdStore.cs
WalletWasabi/WabiSabi/Backend/Rounds/CoinJoinStorage/InMemoryCoinJoinIdStore.cs
WalletWasabi/WabiSabi/WabiSabiCoordinator.cs

Prerequisite for future works.
Also it makes it easier to implement the _Pay-no-fee_ and _Friends-dont-pay_ for coinjoins.
This class wires up both old- and new coinjoins to store all of them, in file & memory.
Had to tinker and add `CoinJoinIdStore` at some places in the tests to make them pass.

Add `CoinJoinIdStore` to store old and new coinjoins at one place

---

WalletWasabi.Fluent/Rpc/WasabiJsonRpcService.cs

This PR adds a new RPC call `listcoins` to dump **all** the wallet's coins (spent and unspent). This is useful to analyze the wallet composition and history.
Initially the idea was not to make a PR with this and simply keep it in a branch but it had been used more and more by me and recently by @MaxHillebrand and the RPC looks like the place to add things for the power users.

Add Wallet coin list dump RPC

---

WalletWasabi/Crypto/Randomness/InsecureRandom.cs
WalletWasabi/Crypto/Randomness/SecureRandom.cs

Follow-up to #7654 (and my [comment](https://github.com/zkSNACKs/WalletWasabi/pull/7654#issuecomment-1082333041))
An initial stab to address thread-safety concerns regarding [RandomNumberGenerator](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.randomnumbergenerator?view=net-6.0).
The gist of possible issue is that `RandomNumberGenerator` is not documented to be thread-safe[^1]. To be on a safe side, we should make sure that it really thread-safe is, otherwise we risk #7117 scenario and probably many other bad scenarios.
So there are several ways to make really sure we are safe and that is:
1) Wrap `SecureRandom` internal calls to `RandomNumberGenerator` in `lock` blocks and be done with it.
* The disadvantage of this approach is that if multiple threads re-use …

Re-implement `SecureRandom`

---

WalletWasabi.Fluent/ViewModels/Dialogs/Authorization/AuthorizationDialogBase.cs
WalletWasabi.Fluent/ViewModels/Dialogs/Authorization/HardwareWalletAuthDialogViewModel.cs
WalletWasabi.Fluent/ViewModels/Dialogs/Authorization/PasswordAuthDialogViewModel.cs
WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionPreviewViewModel.cs
WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModel.cs
WalletWasabi.Fluent/Views/Dialogs/Authorization/HardwareWalletAuthDialogView.axaml
WalletWasabi.Fluent/Views/Dialogs/Authorization/PasswordAuthDialogView.axaml

This is similar as https://github.com/zkSNACKs/WalletWasabi/pull/7679, but with "in-place" wrong password message, as requested by @soosr and @MaxHillebrand.
This means that there is no navigation at all when the user enters a wrong password.
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/7507

[VDG] Retry after wrong password entry for wallet authorization

---

WalletWasabi.Backend/Controllers/BlockchainController.cs
WalletWasabi.Backend/Global.cs
WalletWasabi/Backend/Models/Responses/StatusResponse.cs
WalletWasabi/WabiSabi/WabiSabiCoordinator.cs

Similar to ZeroLink CoinJoin monitor. If there are no coinjoins for a specific time period the status API request will indicate that. The time period is twice the input reg period but at least 1 hour.

Add WabiSabi CoinJoin monitor to status request API

---

WalletWasabi.Fluent/Views/MainView.axaml

This is a **regression** that was introduced with the new design. Don't worry, it's a minor one :)
It fixes https://github.com/zkSNACKs/WalletWasabi/issues/6922

[VDG] Put back correct margin to AdornerCanvas

---

WalletWasabi.Fluent/Views/MainView.axaml

*This is a regression introduced with the new "Store" style.*
When a dialog is visible, the user can still interact with the items behind. This **fixes that** by disabling the behind content when a dialog is shown.
This fixes https://github.com/zkSNACKs/WalletWasabi/issues/7763

[VDG] Fix wrong dialog behavior

---

WalletWasabi.Backend/WalletWasabi.Backend.csproj
WalletWasabi.Fluent.Desktop/WalletWasabi.Fluent.Desktop.csproj
WalletWasabi.Fluent.Desktop/packages.lock.json
WalletWasabi.Fluent.Generators/WalletWasabi.Fluent.Generators.csproj
WalletWasabi.Fluent.Generators/packages.lock.json
WalletWasabi.Fluent/WalletWasabi.Fluent.csproj
WalletWasabi.Fluent/packages.lock.json
WalletWasabi.Packager/Program.cs
WalletWasabi.Packager/WalletWasabi.Packager.csproj
WalletWasabi.Packager/packages.lock.json
WalletWasabi.Tests/WalletWasabi.Tests.csproj
WalletWasabi/WalletWasabi.csproj
WalletWasabi/packages.lock.json

Part of #7778 to ease review.
The goal of the PR is to be able to run WW on macOS arm64 machines without emulation.
I'm not sure if we can make this PR smaller, I don't really have an idea how to make it smaller.
cc @jmacato 
btw: List of existing RIDs is [here](https://github.com/dotnet/runtime/blob/main/src/libraries/Microsoft.NETCore.Platforms/src/runtime.json).

Add runtime support for Apple Silicon.

---

WalletWasabi.Fluent/ViewModels/Wallets/LoadingViewModel.cs

When a wallet is loading,
with this PR it will not display the seconds when the estimated loading time is more than 1hr.
fixed together with @soosr

[VDG] Loading wallet - no seconds displayed when more than 1 hr 

---

WalletWasabi.Fluent/ViewModels/Wallets/Send/LabelSelectionViewModel.cs
WalletWasabi.Tests/UnitTests/UserInterfaceTest/PocketSelectionTests.cs

`_privatePocket` can't be null, so no need to check for null.
This PR also fixes a warning.

[Trivial] Remove unnecessary null check

---

WalletWasabi/WabiSabi/Client/CoinJoinManager.cs

AutoCoinJoin stops after a while. On the logs I see nothing so I added a couple of log messages and also make possible issues detectable, like Task.WhenAll will wait even if one task failed with an exception. I also added the missing handlers for tasks whose results were unobserved in some cases.

Make AutoCoinJoin business logic more robust

---

WalletWasabi.Fluent/ViewModels/CoinJoinProfiles/PrivateCoinJoinProfileViewModel.cs
WalletWasabi.Tests/UnitTests/Crypto/MacTests.cs
WalletWasabi.Tests/UnitTests/Crypto/ProofSystemTests.cs
WalletWasabi.Tests/UnitTests/Crypto/RandomTests.cs
WalletWasabi.Tests/UnitTests/Crypto/TranscriptTests.cs
WalletWasabi.Tests/UnitTests/Crypto/ZeroKnowledge/KnowledgeOfDlogTests.cs
WalletWasabi.Tests/UnitTests/Crypto/ZeroKnowledge/KnowledgeOfRepTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Client/ArenaClientTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Client/BobClientTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/CredentialTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/SerializationTests.cs
WalletWasabi/Crypto/Randomness/InsecureRandom.cs
WalletWasabi/Crypto/Randomness/RandomString.cs
WalletWasabi/Crypto/Randomness/SecureRandom.cs
WalletWasabi/Crypto/Randomness/WasabiRandom.cs
WalletWasabi/Crypto/StringCipher.cs
WalletWasabi/Extensions/TimeSpanExtensions.cs
WalletWasabi/WabiSabi/Backend/Rounds/Arena.Partial.cs
WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs

After #7688, it is no longer necessary to have `WasabiRandom` as `IDisposable` which in turn should fix a few warnings where we do not dispose properly.
Removes 12 warnings (355 remains)

`WasabiRandom` is no longer `IDisposable`

---

WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepOutputRegistrationTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepTransactionSigningTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterOutputTests.cs
WalletWasabi/WabiSabi/Backend/Rounds/Arena.Partial.cs
WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
WalletWasabi/WabiSabi/Models/RoundState.cs

PoC of this PR with measurements https://github.com/zkSNACKs/WalletWasabi/pull/7852
GetStatus is one of the main blocking requests in Arena. From the tests, it is clear that because of the lock it slows down and prevents the progress of other requests. 
With this PR, not just the lock goes away but generating the state response and updating it became more simple. 
UPDATE
Tests are failing sometimes in CI (I assume it is only a test related issue)- until the fix, take this PR as a concept.

[Arena] Get the status from RoundStates instead of Rounds

---

WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
WalletWasabi/WabiSabi/Client/CoinJoinTracker.cs

Continuation of https://github.com/zkSNACKs/WalletWasabi/pull/7881
In the case of AutoCoin, it will only stop when:
- Stop command was intentionally called. 
- The whole CoinJoinManager was canceled.

Only stop restarting if round was intentionally stopped

---

WalletWasabi.Tests/UnitTests/WabiSabi/Models/RoundStateUpdaterTests.cs

Just a test to verify the `RoundStateUpdater` respects the cancellation token.

Add test to verify round awaiter can be cancelled

---

WalletWasabi.Fluent/Styles/FlyoutPresenter.axaml
WalletWasabi.Fluent/Views/SearchBar/SearchBarDropdown.axaml

Monospaced font was set explicitly as the font for Flyouts. This fixes it as requested in https://github.com/zkSNACKs/WalletWasabi/pull/7797#pullrequestreview-951591041

[VDG] [Trivial] Unset default monospaced font for Flyouts

---

WalletWasabi.Fluent/ViewModels/Wallets/CoinJoinStateViewModel.cs

AFAICT this message is displayed when the non private balance is less than the automatic coinjoin threshold (PlebStopThreshold), so the following message makes more sense.

[VDG] Correct music status message

---

WalletWasabi/Blockchain/Analysis/BlockchainAnalyzer.cs

This PR turns off the heavy consolidation penalty we incur for input merging when it happens during coinjoins. In this PR we'd only punish anonscores in coinjoins to the smallest inputs' anonscore.
@MaxHillebrand @BTCparadigm @MarnixCroes If you have a wallet in privacy mode with a high anonymity percentage. Can you check if this PR changes the privacy percentage?
@andrewkozlik @onvej-sl

Tune down consolidation penalty in coinjoins

---

WalletWasabi.Fluent/Views/Wallets/MusicControlsView.axaml

With the help of @jmacato, we debugged what is responsible for the high CPU and GPU usage. And it seems the MusicBox control contained a redundant blur effect. 
I removed it and waited until 12 peers connected.
My test results are the following:
This PR:
```
CPU	GPU
no CJ:	2-4.5%	3.7%
CJ:	3-6%	3.7%
```
Master:
```
CPU	GPU
no CJ:	10-12%	9.6%
CJ:	9-14%	9.8%
```

[VDG] decrease CPU & GPU usage

---

WalletWasabi/WabiSabi/Backend/Banning/Inmate.cs

While testing the software I realized that `Inmate.isLongBan` has a bug.
As long as the backend is not restarted, the cached `Inmate`s will have the assigned value, so the release logic is correct.
But the `isLongBan` value is not saved, so after restart, all `Inmate`s will have `false` for `isLongBan`, as it is the default, so people would be freed much faster.

Fix `isLongBan` missing after restart

---

WalletWasabi.Fluent/Styles/Themes/BaseDark.axaml
WalletWasabi.Fluent/Styles/Themes/BaseLight.axaml
WalletWasabi.Fluent/Views/MainView.axaml
WalletWasabi.Fluent/Views/NavBar/NavBar.axaml

- Fixes the icon's foreground on Light mode.
- Adjust the tint colors on Dark mode so that it shows the blur behind it a bit better.
Windows
Mac

[VDG] Adjust navbar tint colors & Fix icon foreground

---

WalletWasabi/WabiSabi/Client/CoinJoinProgressEvents/EnteringInputRegistrationPhase.cs
WalletWasabi/WabiSabi/Client/CoinJoinProgressEvents/EnteringOutputRegistrationPhase.cs
WalletWasabi/WabiSabi/Client/CoinJoinProgressEvents/EnteringSigningPhase.cs
WalletWasabi/WabiSabi/Client/CoinJoinProgressEvents/RoundStateChanged.cs
WalletWasabi/WabiSabi/Client/CoinJoinProgressEvents/WaitingForBlameRound.cs
WalletWasabi/WabiSabi/Client/StatusChangedEvents/CoinJoinStatusEventArgs.cs

- `CoinJoinStatusEventArgs` to public to be accessible
- `timeout` -> `timeoutAt` for better readability as `timeout` at most places is a timespan.

Coinjoin Phase event nits

---

WalletWasabi.Fluent/Views/SearchBar/SearchBar.axaml

Previous:
Wrong caret brush in SearchBox (dark caret)
This PR:
Correct brush is used (light caret)

[VDG] [Trivial] Fix SearchBar caret brush in Light Mode

---

WalletWasabi.Fluent/ViewModels/ApplicationViewModel.cs

@SuperJMN and @danwalmsley discovered a bug in which a code that I introduced here:
https://github.com/zkSNACKs/WalletWasabi/commit/99a79d28d30c19097992abbc366eaedae67af5da
Held instances of previously closed dialog VM's in memory until the app closes. This PR hopefully solves that issue.

[VDG] Fix dialog VM being retained in memory 

---

WalletWasabi.Fluent/Controls/TileControl.axaml
WalletWasabi.Fluent/Views/Wallets/Home/Tiles/BtcPriceTileView.axaml
WalletWasabi.Fluent/Views/Wallets/Home/Tiles/WalletBalanceTileView.axaml

It doesnt fit the aesthetic there honestly. 

[VDG] Dont use monospace on all text in TileControl

---

WalletWasabi.Fluent/WalletWasabi.Fluent.csproj
WalletWasabi.Packager/Program.cs
azure-pipelines-linux.yml
azure-pipelines-osx.yml
azure-pipelines-windows.yml

This PR supersedes #6881 and fixes #6679 properly - i.e. it should be allowed now to define `<PackageReference>` that are "debug only" like:
```xml
<PackageReference Include="Avalonia.Diagnostics" Version="$(AvaloniaVersion)" Condition="'$(Configuration)' == 'Debug'" />
```
The PR #6881 was clumsy. The concept there would require to change workflow how people use `dotnet restore` when adding/modifying dependencies[^1].
There are several pieces of information that are vital to know:
* `dotnet restore` does not support `dotnet restore -c <Configuration>` (notably not `dotnet restore -c Release`). That means that the restore operation is common for all configurations[^2]
* Call `dotnet restore --locked-mode`, modify a `packages.lock.json`, call `dotnet restore --locked-mode` again and it ... …

Debug-only `<PackageReference>` and packages.lock.json files

---

WalletWasabi/WabiSabi/Client/CoinJoinManager.cs

The previous log message is misleading, because you might have coins but they are not confirmed or not available ...

[Trivial] Clarify log message

---

WalletWasabi.Fluent/ViewModels/Wallets/CoinJoinStateViewModel.cs
WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
WalletWasabi/WabiSabi/Client/CoinJoinProgressEvents/EnteringConnectionConfirmationPhase.cs
WalletWasabi/WabiSabi/Client/CoinJoinProgressEvents/EnteringCriticalPhase.cs
WalletWasabi/WabiSabi/Client/CoinJoinProgressEvents/EnteringOutputRegistrationPhase.cs
WalletWasabi/WabiSabi/Client/CoinJoinProgressEvents/EnteringSigningPhase.cs
WalletWasabi/WabiSabi/Client/CoinJoinProgressEvents/LeavingCriticalPhase.cs
WalletWasabi/WabiSabi/Client/CoinJoinTracker.cs

I know we are moving around this topic a lot, but this is the final concept on this. Entering and leaving the critical should be as close as possible to the actual time and not always related to a phase change. For example it is much safer to report LaevingCritical in the finally clause - it will always happen.

Add Entering and Leaving critical events

---

WalletWasabi.Fluent/ViewModels/Wallets/CoinJoinStateViewModel.cs
WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
WalletWasabi/WabiSabi/Client/CoinJoinProgressEvents/RoundEnded.cs

Solving the issue of getting this message right after the CoinJoin round finished:
`No candidate coins available to mix for wallet`
The problem was that we first reported the round as ended and just later (few secs) set the `SmartCoin.IsCoinJoinInProgress` flag to false. But MusicBox immediately instructed CoinJoinManager to Start mixing and it ended up with the message above and stopped as it was an end condition - thus stopping the CoinJoins permanently in Manual CJ mode.
In CoinJoinManager I did not change anything except the order of some code snippets.

Set CoinJoinInProgress false before report RoundEnded

---

WalletWasabi.Fluent/Views/Wallets/Home/Tiles/WalletBalanceTileView.axaml

Fixes: https://github.com/zkSNACKs/WalletWasabi/issues/7939
Long:
Short:
Privacy Mode:

[VDG] Handle long balance text

---

WalletWasabi.Fluent/ViewModels/SearchBar/SearchBarViewModel.cs

Correct reference type. Was mistakenly removed in https://github.com/zkSNACKs/WalletWasabi/pull/7797

[VDG] [Trivial] Set initial value of SearchText to empty string

---

WalletWasabi.Fluent/Styles/Styles.axaml
WalletWasabi.Fluent/Styles/ToggleSwitch.axaml

[VDG] HandCursor ToggleSwitch

---

WalletWasabi.Backend/Filters/ExceptionTranslateFilter.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterInputFailureTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Backend/UtxoPrisonTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiHttpApiIntegrationTests.cs
WalletWasabi/Tor/Http/Extensions/HttpResponseMessageExtensions.cs
WalletWasabi/WabiSabi/Backend/Banning/Inmate.cs
WalletWasabi/WabiSabi/Backend/Banning/Prison.cs
WalletWasabi/WabiSabi/Backend/Banning/Punishment.cs
WalletWasabi/WabiSabi/Backend/Models/ExceptionData.cs
WalletWasabi/WabiSabi/Backend/Models/InputBannedExceptionData.cs
WalletWasabi/WabiSabi/Backend/Models/WabiSabiProtocolErrorCode.cs
WalletWasabi/WabiSabi/Backend/Models/WabiSabiProtocolException.cs
WalletWasabi/WabiSabi/Backend/Rounds/Arena.Partial.cs
WalletWasabi/WabiSabi/Client/AliceClient.cs
WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
WalletWasabi/WabiSabi/Models/Error.cs
WalletWasabi/WabiSabi/Models/Serialization/ExceptionDataJsonConverter.cs
WalletWasabi/WabiSabi/Models/Serialization/JsonSerializationOptions.cs

Send `bannedUntil` info to the client.
PR contains: 
- Backend sends the `bannedUntil` property to the client in `DateTimeOffset`
- Adds `ExceptionData` property to the `WabiSabiProtocolException`, so we can send additional data to the client if needed.
- Client marks the coin as banned.
- CjManager won't choose banned coins.
- Clean up in `Prison` and `Inmate` + `Prison Tests`
First part of https://github.com/zkSNACKs/WalletWasabi/pull/7921#issuecomment-1119413770

Differentiate normal and long ban

---

WalletWasabi.Fluent/ViewModels/Login/LoginViewModel.cs
WalletWasabi/Blockchain/Keys/KeyManager.cs

Even if it shouldn't be possible my wallet was created before the coinjoin profiles and the autocoinjoin was enabled so it happened the profile selection popped on login (in real life, it won't) and it didn't feel good. 
It didn't feel good because I didn't want to coinjoin at all. So instead of not allowing the user to log in until they select a profile, just let them in and disable the autocoinjoin. After all, this is the question, how the autocoinjoin can be enabled without a profile.
This PR disables the autocoinjoin and lets the user in and relays the other safety checks, when they want to do coinjoin (or enable it) the dialog will pop and they must select one before conjoining.

Disable `AutoCoinJoin` when coinjoin profile is not selected

---

WalletWasabi.Gui/Tabs/WalletManager/RecoverWallets/RecoverWalletViewModel.cs

Fixes #7375
This is a back port of #4106 which was added to backport tasks but was never backported.

[Backport] Suggest same words multiple times when typing recovery words

---

WalletWasabi.Fluent/ViewModels/CoinJoinProfiles/CoinJoinProfileViewModelBase.cs
WalletWasabi.Fluent/ViewModels/CoinJoinProfiles/CoinJoinProfilesViewModel.cs
WalletWasabi.Fluent/ViewModels/CoinJoinProfiles/ManualCoinJoinProfileViewModel.cs
WalletWasabi.Fluent/ViewModels/CoinJoinProfiles/PrivateCoinJoinProfileViewModel.cs
WalletWasabi.Fluent/ViewModels/Dialogs/ManualCoinJoinProfileDialogViewModel.cs
WalletWasabi.Fluent/ViewModels/Wallets/CoinJoinStateViewModel.cs
WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/PrivacyControlTileViewModel.cs
WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/WalletBalanceTileViewModel.cs
WalletWasabi.Fluent/ViewModels/Wallets/Send/PrivacyControlViewModel.cs
WalletWasabi.Fluent/ViewModels/Wallets/Send/PrivacySuggestionsFlyoutViewModel.cs
WalletWasabi.Fluent/ViewModels/Wallets/Send/SendViewModel.cs
WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionInfo.cs
WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionPreviewViewModel.cs
WalletWasabi.Fluent/ViewModels/Wallets/WalletSettingsViewModel.cs
WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModel.cs
WalletWasabi.Fluent/Views/Dialogs/ManualCoinJoinProfileDialogView.axaml
WalletWasabi.Fluent/Views/Wallets/WalletSettingsView.axaml
WalletWasabi.Tests/UnitTests/WabiSabi/Client/CoinJoinCoinSelectionTests.cs
WalletWasabi/Blockchain/Analysis/BlockchainAnalyzer.cs
WalletWasabi/Blockchain/Keys/KeyManager.cs
WalletWasabi/CoinJoin/Client/Rounds/ClientState.cs
WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
WalletWasabi/WabiSabi/Client/CoinJoinTrackerFactory.cs
WalletWasabi/Wallets/Wallet.cs

This PR at its core changes the anonymity calculation in case of coinjoins during registration of multiple inputs. Previously the anonymity scores of outputs started from the lowest input's anonscore. In this PR, it uses amount weighted averages of the input anonscores. While it may seem like a trivial change, it does come with a plethora of implications.
An alternative way to think about this PR is that it drops the conservative assumption of common input ownership heuristics in coinjoins.
- From this PR on the privacy progress percentage is never going to go down after a coinjoin. This enables us to have a wallet 100% coinjoined out, which previously it was often not possible, except at a great cost of coinjoining insignificant amounts, effectively spamming the blockchain.
- From this …

Use weighted average for consolidation in coinjoin

---

WalletWasabi.Fluent/ApplicationStateManager.cs

Apparently, the wrong state was being set.
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/8040

[VDG] Enter correct state in ApplicationStateManager

---

WalletWasabi.Backend/Global.cs

I tried to test something in RegTest, but couldn't start the backend locally.
The error was `Backend/Global.cs: ArgumentNullException: Parameter is null. (Parameter: Coordinator)` so the `Guard.NotNull` throw the exception as it's expected.
PR fixes this by moving the `Guard` and the `ConfigWatcher` init further down.
Git shows the diff quiet stupidly, all I did was cut the `Guard` and the `ConfigWatcher` stuff and pasted it under the Coordinator initialization.

Fix Backend Global

---

WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryViewModel.cs

https://github.com/zkSNACKs/WalletWasabi/pull/7994#issuecomment-1131308123
Increase `MinWidth` is to prevent jumping when sorting (https://github.com/zkSNACKs/WalletWasabi/pull/7994#issuecomment-1126693947)
Increase `MaxWidth` is for the whales;) 
(MaxWidth is only relevant when there are bigger amounts, as it can auto size to bigger amounts as the column has set Auto sizing)
https://user-images.githubusercontent.com/93143998/169250304-1fb9df15-2112-480c-b3a8-31cc44dc2970.mp4

[VDG] Increase BTC columns width

---

WalletWasabi.Fluent/Controls/NavBarItem.axaml
WalletWasabi.Fluent/Views/NavBar/NavBar.axaml

Fixes #8002
cc @zkSNACKs/visual-design-group @nopara73

[VDG] Widen up the navbar to accomodate the bottom menu text

---

WalletWasabi.Fluent/State/StateMachine.cs
WalletWasabi.Tests/UnitTests/StateMachineTests.cs

@molnard reported that AutoCoinJoinState.OnEntry was getting called after each round, this caused auto cj to stop incorrectly.
I confirmed this was the case, this is incorrect behavior.
It turns out that I had forgotten to update a method to be compatible with child states.. so it was unable to detect we are in a parent state from a child state correctly.
This meant that the Parent states OnEntry could be called... despite already being in that state.
AutoCoinJoin now works continuously. StateMachine now behaves as per spec... (https://github.com/dotnet-state-machine/stateless)

Fix StateMachine IsInState logic

---

WalletWasabi/WabiSabi/Client/CoinJoinClient.cs

This PR fixes a mistake in the calculation of IR remaining time. This is why we see things like the following:
```
2022-05-19 12:53:03.488 [41] INFO       AliceClient.ReadyToSignAsync (243)      Round (d6a18b9688754cd4a3113454cf01f453066c0c94e350ea4b4a87b3426c855b27), Alice (5f86b452-e51e-95c5-2d15-9b228ef73810): Ready to sign.
2022-05-19 12:53:03.491 [41] DEBUG      CoinJoinClient.ProceedWithOutputRegistrationPhaseAsync (637)    Round (d6a18b9688754cd4a3113454cf01f453066c0c94e350ea4b4a87b3426c855b27): Alices(2) are ready to sign.
2022-05-19 12:53:04.225 [62] DEBUG      CoinJoinClient.CreateRegisterAndConfirmCoinsAsync (289) Round (d6a18b9688754cd4a3113454cf01f453066c0c94e350ea4b4a87b3426c855b27): Input registration started - it will end in: 00:00:21.
```

Fix remaining time for IR

---

WalletWasabi/WabiSabi/Client/CoinJoinManager.cs

Fixes: https://github.com/zkSNACKs/WalletWasabi/issues/8068
We were running the CoinJoinClient twice! It is started exactly at the same time by the music box. This PR not fixing the music box but the business logic to prevent that kind of situation. 
The real bug here was the: `!tracker.IsCompleted` because at the time of the check it was even not started, so it was indicating false and let go of the code. I am not sure why that condition was added at all. 
https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.task.iscompleted?view=net-6.0
Also, I changed AddOrUpdate to TryAdd to detect any problems. @lontivero was there a reason to specifically use AddOrUpdate?

Do not let and detect double start of CoinJoinClient

---

WalletWasabi.Fluent/ViewModels/Wallets/CoinJoinStateViewModel.cs

For the sake of consistency, we use `DateTimeOffset.UtcNow` everywhere else.
https://github.com/zkSNACKs/WalletWasabi/pull/8070#issuecomment-1132938211

[Trivial] Use DateTimeOffset.UtcNow instead of DateTimeOffset.Now

---

WalletWasabi.Fluent/ViewModels/SearchBar/Sources/ActionsSource.cs
WalletWasabi.Fluent/ViewModels/TriggerCommandViewModel.cs

Fixes https://github.com/zkSNACKs/WalletWasabi/issues/7983
I still disagree with the fact that `TriggerCommandViewModel` is a `RoutableViewModel` but it seems it has to be that because of the NavigationMetaData. Removing the navigation hack and calling its command properly fixes the issue.

[VDG] Fix splash animation triggered by the SearchBar

---

WalletWasabi.Fluent/ViewModels/Wallets/WalletSettingsViewModel.cs

Fixes #8098
With old wallets, when we choose a CoinJoinProfile, the AnonScoreTarget will be changed in the background, but the `WalletSettingsViewModel` used the default `5` value when created. That should be updated upon navigation.

Update `AnonScoreTarget` upon opening Wallet Settings

---

WalletWasabi/WabiSabi/Client/CoinJoinClient.cs

- Problem 1: During the end of our coinjoining sessions in "privacy profile" there were a lot of small < anontarget coins remaining and the final percentages were going up very slowly.
- Problem 2: There were a lot of small little mix coins.
- Solution for Problem 1: Make sure to always include a good number of < anontarget coins and > anontarget coins.
- Solution for Problem 2: Remove ordering by amounts.
Drawback: smaller coinjoin volumes :(

Improve Coin Selection For Coinjoins

---

WalletWasabi.Fluent/ViewModels/Wallets/CoinJoinStateViewModel.cs
WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
WalletWasabi/WabiSabi/Client/RoundStateAwaiters/RoundStateAwaiter.cs
WalletWasabi/WabiSabi/Client/RoundStateAwaiters/UnexpectedRoundPhaseException.cs

This PR clarifies and display a better readable message in Logs and in the Music box for the users. This is one of the most frequent cases (at least in TestNet) and I got many questions with the original error message (unexpected phase change) - if that is a bug or not.

Make NotEnoughAlicesMessage visible and clear

---

WalletWasabi.Fluent.Desktop/Program.cs

Currently, the Avalonia Previewer is broken:
> 16:45:52.366 [Information] 0 Starting previewer process for '"E:\Repos\SuperJMN\WalletWasabi\WalletWasabi.Fluent.Desktop\bin\Debug\net6.0\WalletWasabi.Fluent.Desktop.dll"'
16:45:52.368 [Information] 5152 Started previewer process for '"E:\Repos\SuperJMN\WalletWasabi\WalletWasabi.Fluent.Desktop\bin\Debug\net6.0\WalletWasabi.Fluent.Desktop.dll"'. Waiting for connection to be initialized.
16:45:52.466 [Information] 5152 Connection initialized
16:45:52.482 [Error] 5152 <= "WalletWasabi.Fluent.Desktop.Program doesn't have a method named BuildAvaloniaApp"
16:45:52.485 [Information]  Process exited
16:45:52.487 [Information]  Stopping previewer process
This adds a simple bootstrap code to enable the Avalonia Previewer.

[VDG] [Trivial] Enable Avalonia Previewer

---

WalletWasabi.Fluent/ViewModels/SearchBar/SearchBarViewModel.cs

What I realized and was personaly bothering me, is that if I search "help" in the search bar, nothing came up, altough "Help & Support" is a valid category. If Im not sure how to look for help, well, searching for "help" would be obvious.

Add option to search Category in Searchbar

---

WalletWasabi.Fluent/ViewModels/Wallets/CoinJoinStateViewModel.cs
WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
WalletWasabi/WabiSabi/Client/CoinJoinTracker.cs

part of https://github.com/zkSNACKs/WalletWasabi/pull/8112
Taking away the responsibility of restarting and stopping the CoinJoins from the state machine. 
Review commit by commit.

Improve CoinJoinManager 

---

WalletWasabi.Fluent/Views/Wallets/LoadingControl.axaml

This PR makes the World Map animation (loading screen) a bit less sensible to height.
https://user-images.githubusercontent.com/3109851/170286752-fd6d25e8-8268-416e-a58a-b065bda25b0f.mp4
https://user-images.githubusercontent.com/3109851/170287125-c5add0fe-644b-45a4-981c-3f332e1016e6.mp4

[VDG] [Trivial] Make World Map animation don't disappear with enough size

---

WalletWasabi.Backend/InitConfigStartupTask.cs

Yesterday while testing the logs were completely flooded with:
```
2022-03-24 14:43:38.756 [2] DEBUG   Program.TaskScheduler_UnobservedTaskException (169) System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing       its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (Operation canceled)
388  ---> System.Net.Sockets.SocketException (125): Operation canceled
389    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
390    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
391    at …
```

Change unobserved task exception logging level

---

WalletWasabi.Tests/IntegrationTests/LiveServerTests.cs
WalletWasabi.Tests/UnitTests/LinqExtensionsTests.cs
WalletWasabi.Tests/UnitTests/Transactions/AllTransactionStoreTests.cs
WalletWasabi/BitcoinCore/Rpc/RpcClientBase.cs
WalletWasabi/BitcoinP2p/P2pNetwork.cs
WalletWasabi/Blockchain/TransactionBroadcasting/TransactionBroadcaster.cs
WalletWasabi/Blockchain/TransactionBuilding/SmartCoinSelector.cs
WalletWasabi/Blockchain/Transactions/AllTransactionStore.cs
WalletWasabi/Blockchain/Transactions/TransactionHistoryBuilder.cs
WalletWasabi/Blockchain/Transactions/TransactionStore.cs
WalletWasabi/CoinJoin/Client/Clients/CoinJoinClient.cs
WalletWasabi/CoinJoin/Client/Rounds/ClientState.cs
WalletWasabi/CoinJoin/Coordinator/Rounds/CoordinatorRound.cs
WalletWasabi/Exceptions/InvalidTxException.cs
WalletWasabi/Extensions/LinqExtensions.cs
WalletWasabi/Extensions/RPCClientExtensions.cs
WalletWasabi/Tor/Http/Extensions/HttpRequestMessageExtensions.cs
WalletWasabi/Tor/Http/Helpers/HttpMessageHelper.cs
WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
WalletWasabi/WabiSabi/Client/AmountDecomposer.cs
WalletWasabi/Wallets/P2pBlockProvider.cs
WalletWasabi/WebClients/Wasabi/WasabiClient.cs

[trivial] Change namespace of `LinqExtensions` file

---

WalletWasabi.Fluent/Views/Wallets/Send/TransactionSummary.axaml

I was sending to `Rafe` but I don't see that in the tx preview:
IMO a better solution would be to display the recipient label also.

Improve message for entities that know about the tx

---

WalletWasabi.Fluent/ViewModels/Wallets/CoinJoinStateViewModel.cs
WalletWasabi.Fluent/Views/Wallets/MusicControlsView.axaml

IMO this fits better the Music Player concept, as in the real world there is no player without a button. (also less code)
Active:
Disabled:
Fixes a minor layout issue, the indicator was not centralized when there was no button:
cc @zkSNACKs/visual-design-group for review.

[VDG] MusicBox - disable button instead of hide in critical phase

---

WalletWasabi/WabiSabi/Client/CoinJoinManager.cs

Currently in the logs there is nothing that indicates that a coinjoin round was successful.
This improves that a bit.

[Trivial] Improve log when coinjoin is successul

---

WalletWasabi.Fluent/Views/Dialogs/ManualCoinJoinProfileDialogView.axaml
WalletWasabi.Fluent/Views/Wallets/WalletSettingsView.axaml

I tried to change the anonymity score to a higher number in the config, but opening the settings changed it back to the max: 150. This is not good as people will want to have unreasonably high anonymity sets for sure.

Increase max anonscore from 150 to 300

---

WalletWasabi.Fluent/ViewModels/SearchBar/SearchBarViewModel.cs
WalletWasabi.Fluent/ViewModels/SearchBar/SearchItemGroup.cs
WalletWasabi.Fluent/Views/SearchBar/SearchBarDropdown.axaml

Fixes #7956
The observed behavior was **very** strange. I had to implement a "clever" workaround to avoid the problem.
Apparently, the problem is related with this Style setter:
```xml
<Style Selector="ItemsControl:empty">
<Setter Property="Template">
<Setter.Value>
<ControlTemplate>
<TextBlock Margin="10">No results</TextBlock>
</ControlTemplate>
</Setter.Value>
</Setter>
</Style>
```
*According to the repro steps detailed here https://github.com/zkSNACKs/WalletWasabi/issues/7956*
First, you type a search text in the `SearchBar` that has no results ("ff" for instance). In such case, this setter will be applied. Then, you toggle the Theme via **Settings**. Nothing bad happens yet. The problem comes when this style setter no longer applies and the default `Template` needs to be set back. …

[VDG] Fix threading issue related to Theme switch

---

WalletWasabi.Fluent/App.axaml
WalletWasabi.Fluent/ApplicationStateManager.cs
WalletWasabi.Fluent/Providers/IMainWindowService.cs
WalletWasabi.Fluent/ViewModels/ApplicationViewModel.cs
WalletWasabi.Fluent/ViewModels/MainViewModel.cs

Fixes https://github.com/zkSNACKs/WalletWasabi/issues/8228
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/8232
I have modified the state machine because the only difference between the background mode and the normal mode is how the close button should work. There is no point in having many states.
Some refactor and cleanup were needed...
Note: Tray menu stays on the screen when the window gets hidden from the Tray, even on master, need to investigate it.
cc @zkSNACKs/visual-design-group for review.

[VDG] Tray - fix hide

---

WalletWasabi/Helpers/Constants.cs

Some users are confused about the message on the status bar that there is a new version to download.
Similar to https://github.com/zkSNACKs/WalletWasabi/pull/8109 this PR changes back the client version to not disturb existing ww1 users.

Change client version back to 1.1.13.1

---

WalletWasabi.Fluent/Views/NavBar/NavBar.axaml

nit
not needed anymore because of the recent NavBar width increase

[VDG] Remove tooltip NavBar

---

WalletWasabi.Fluent/Views/SearchBar/SearchBarDropdown.axaml

When SearchBar is open, the text "No results" flicks for a very short time, that gives a wrong feeling to the UX.
*Fixes a regression caused by this: https://github.com/zkSNACKs/WalletWasabi/pull/8155*

[VDG] [Trivial] Fix flicking "No results" title in SearchBar

---

WalletWasabi.Fluent/Extensions/TransactionSummaryExtension.cs
WalletWasabi.Fluent/ViewModels/Wallets/Send/ChangeAvoidanceSuggestionViewModel.cs
WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionSummaryViewModel.cs
WalletWasabi.Fluent/Views/Wallets/Send/TransactionSummary.axaml

This PR fixes @BTCparadigm 's report on the meeting regarding inconsistent formatting of all BTC values compared to the ones we have in Tiles. This PR should fix that.
cc @BTCparadigm @zkSNACKs/visual-design-group

[VDG] Fix amount/fee formatting in TxnPreview

---

WalletWasabi/WabiSabi/Client/CoinJoinClient.cs

This information is useful to have in the logs when using the release version.

[Trivial] Use LogInfo to be able to see successful CoinJoin txid

---

WalletWasabi/Blockchain/Analysis/BlockchainAnalyzer.cs

Forget clusters when no unique outputs created in coinjoins, otherwise in half mixed wallets all the labels quickly gravitate into a single cluster making pocket selection unusable.

Forget clusters when no unique outputs created in coinjoins

---

WalletWasabi.Fluent/ViewModels/Settings/PrivacyModeViewModel.cs
WalletWasabi.Fluent/Views/NavBar/NavBar.axaml

Ledger uses this terminology, which is infinitely better than "privacy mode." Unfortunately, it doesn't have enough space. Not sure what to do about it.

Rename Privacy Mode to Discreet Mode

---

WalletWasabi.Fluent/Views/Login/PasswordFinder/PasswordFinderIntroduceView.axaml

Partially fixes #8274:
> Enter keystroke is not working on the first dialog.

[VDG] Fix enter key in password finder

---

WalletWasabi.Fluent/ViewModels/Login/PasswordFinder/SearchPasswordViewModel.cs

Fixes a threading related crash that occurs when password finder reaches 100%
Addresses one of the issues reported in #8274: 
> The result dialog is empty

[VDG] Password finder crash fix

---

WalletWasabi.Fluent/Controls/TileButton.axaml
WalletWasabi.Fluent/ViewModels/AddWallet/AddWalletPageViewModel.cs
WalletWasabi.Fluent/Views/AddWallet/AddWalletPageView.axaml

- Reverted back to clickable buttons in the Add wallet UI
- Restyled `TileButton` to look similar to the options in the Coinjoin Profiles selection UI
- Addresses #8176

[VDG] Single click add wallet UI

---

WalletWasabi/WabiSabi/Client/CoinJoinManager.cs

Fixes https://github.com/zkSNACKs/WalletWasabi/issues/8278#issuecomment-1147188899
In before weighted anonset calculation it was impossible to reach 100% mixability without great cost so we added a safety feature to not eat up the user's balance for little benefit. It's not the case anymore, so this PR removes that hack.

Remove obsolated hack

---

WalletWasabi.Fluent/Controls/LabelControl.axaml
WalletWasabi.Fluent/Controls/LabelsListBox.axaml
WalletWasabi.Fluent/Styles/Button.axaml

- Closes https://github.com/zkSNACKs/WalletWasabi/issues/8271 - I removed the button flyout as the tooltip on hover is enough.
- ToolTips were missing, which are required especially when a label is too long and it gets cut off like `LongLabeeeeeeeeeee...`.
ping @zkSNACKs/visual-design-group for review.

[VDG] Label fixes

---

WalletWasabi.Fluent/Behaviors/PasteButtonFlashBehavior.cs

Fixes
```
Object reference not set to an instance of an object.
at WalletWasabi.Fluent.Behaviors.PasteButtonFlashBehavior.CheckClipboardForValidAddressAsync(Boolean forceCheck)
at WalletWasabi.Fluent.Behaviors.PasteButtonFlashBehavior.<OnAttachedToVisualTree>b__9_7(Unit _)
at System.Reactive.PlatformServices.ExceptionServicesImpl.Rethrow(Exception exception) in /_/Rx.NET/Source/src/System.Reactive/Internal/ExceptionServicesImpl.cs:line 19
at System.Reactive.ExceptionHelpers.Throw(Exception exception) in /_/Rx.NET/Source/src/System.Reactive/Internal/ExceptionServices.cs:line 16
at System.Reactive.Stubs.<>c.<.cctor>b__2_1(Exception ex) in /_/Rx.NET/Source/src/System.Reactive/Internal/Stubs.cs:line 16
at System.Reactive.AnonymousObserver`1.OnErrorCore(Exception error) in …
```

[VDG] AutoPaste - fix NRE when trimming

---

WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs

In case some alices fail to sign before the timeout then create a blame round. Otherwise, if there is any other kind of problem, bug or whatever then simply finish the round with appropriated end state.

Create blame round only when appropiated

---

WalletWasabi.Backend/Global.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Backend/ConfigTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Backend/CoordinatorTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Integration/IWebHostBuilderExtensions.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiApiApplicationFactory.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiHttpApiIntegrationTests.cs
WalletWasabi/WabiSabi/Backend/Statistics/CoinJoinScriptStore.cs
WalletWasabi/WabiSabi/WabiSabiCoordinator.cs

Adds a unit test that verifies the client is not revealing common ownership of inputs in case of errors.
Note: it is important to notice that in this specific case, in the test, the client ignores the fact that the coordinator has already seen the output and then, in the end of the process, it doesn't know what was wrong and only see there are missing outputs. 
IMO it is important to know that it is the client the one that is misbehaving and not the coordinator because in case we implement the banning of misbehaving coordinators (i think we should) then the client would ban it.

Unit test to verify we don't reveal common ownership of inputs

---

WalletWasabi.Fluent/ViewModels/Wallets/Advanced/WalletStatsViewModel.cs
WalletWasabi.Fluent/Views/Wallets/Advanced/WalletStatsView.axaml

There's no good name for it, because it's quite a special thing. Also maybe it's redundant assuming the code is correct and the gaps are increased accordingly.

Remove MinGapLimit from Wallet Stats

---

WalletWasabi.Fluent/ViewModels/AddWallet/RecoverWalletViewModel.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiHttpApiIntegrationTests.cs
WalletWasabi/Blockchain/Keys/KeyManager.cs
WalletWasabi/Blockchain/TransactionProcessing/TransactionProcessor.cs
WalletWasabi/Blockchain/Transactions/TransactionFactory.cs
WalletWasabi/Wallets/Wallet.cs

WW1 and WW2's locked key usage differs. This addresses https://github.com/zkSNACKs/WalletWasabi/pull/8348#issuecomment-1153115851.
One of the major changes is that we won't assure to have locked keys available at all times anymore, rather WW2 coinjoins are going to ask for them on-demand. WW1 coinjoins were expecting them to be available. As a consequence I had to increase the recovery `MinGapLimit` by 14 as 14 locked internal keys were generated previously (thus also indexed.) Which resolves https://github.com/zkSNACKs/WalletWasabi/issues/7550

Improve locked key usage

---

WalletWasabi/Extensions/StreamExtensions.cs
WalletWasabi/Tor/Socks5/TorTcpConnectionFactory.cs

Related to #8354 (improves the log part, not the "Object was already disposed" part)
This PR attempts to improve the cancelling behavior of `StreamExtensions.ReadByteAsync(..)` in the way that `OperationCancelledException` is thrown (as it should be) rather than returning `-1` (denoting that no data are available for reading).
The effect of this PR should be that `OperationCancelledException` is logged on trace level and normally it should not be seen in logs. So we should have cleaner logs when the app is shutting down. 
The PR should not affect anything else than logs really.

`StreamExtensions`: Improve cancellation.

---

WalletWasabi.Fluent/Styles/CuedScrollViewer.axaml

*(this is a fix for a regression introduced by https://github.com/zkSNACKs/WalletWasabi/pull/7326)*
The Styles in CuedScrollViewer.xaml are supposed to be applied only to the NavBar, but some of them are applied to controls outside it.
Current: 
This PR:
Please, notice how the arrow buttons (Repeaters)

[VDG] Make styles of NavBar's ScrollBar more restrictive

---

WalletWasabi.Fluent.Desktop/Extensions/AppBuilderExtension.cs

Confirmed, this fixes resize issues on Intel OSX, @bharmat

increase the amount of gpu memory allowable for assets.

---

WalletWasabi.Tests/UnitTests/BlockchainAnalysis/CoinJoinAnonscoreTests.cs
WalletWasabi/Blockchain/Analysis/BlockchainAnalyzer.cs

As discussed on research meeting with @MaxHillebrand and @BTCparadigm weighted anonscore was implemented with WW2 in mind. I realized it'd ruin WW1 anonscore calculations. This PR fixes it by making sure we only use weighted anonscores for non-unique outputs. For unique outputs I'm basically reintroducing the anonymity punishment. This could also be important for edge cases in WW2. Note that testnet anonscore percentages in the privacy profile are basically halved by this PR, though for my mainnet wallet this did not result in a change.

Don't use weighted anonscore for change outputs (WW1 anonscore fix)

---

WalletWasabi/Bases/ConfigBase.cs

The following issue caused a crash after starting Wasabi
```
2022-06-13 13:15:53.335 [1] DEBUG	Program.Main (41)	Wasabi was started with these argument(s): none.
2022-06-13 13:15:55.848 [14] WARNING	Program.CurrentDomain_UnhandledException (209)	System.IO.IOException: The process cannot access the file 'C:\Users\user\AppData\Roaming\WalletWasabi\Client\UiConfig.json' because it is being used by another process.
at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode …
```

Add simple lock to ConfigBase

---

WalletWasabi.Tests/UnitTests/Wallet/SmartCoinSelectorTests.cs
WalletWasabi/Blockchain/TransactionBuilding/SmartCoinSelector.cs

Related #8103
This PR eliminates the chance of having a problem with sequences being evaluated more than once. However this code does NOT solve the problem described by #8103 because it was impossible to reproduce still.

Materilize sequences to prevent multiple evaluations

---

WalletWasabi.Tests/UnitTests/WabiSabi/Backend/Rounds/MultipartyTransactionStateTests.cs
WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
WalletWasabi/WabiSabi/Backend/Rounds/MaxSuggestedAmountProvider.cs

- First and most important change, variate the MaxSuggested Amount every time when a round is created. Before we only changed the value when the round successfully got into Conn-confirm. If there were not enough users in the round we never changed the MaxSuggested thus bigger coins never tries to register. 
- Current master generates the round with MaxSuggestedAmount starting with the smallest base value for example 0.1 BTC. This PR let the first round starts with the largest amount which is 1375 BTC. 
- Do not increase the counter in case of Blame round.

Optimize MaxSuggestedAmount variation

---

WalletWasabi.Tests/Helpers/WabiSabiFactory.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterInputFailureTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Backend/Rounds/MultipartyTransactionStateTests.cs
WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
WalletWasabi/WabiSabi/Backend/Rounds/MaxSuggestedAmountProvider.cs
WalletWasabi/WabiSabi/Backend/Rounds/RoundParameterFactory.cs

- After many unsuccessful rounds because of not enough inputs, we should end up with the largest MaxSuggestedAmount  (1375 BTC) to let everyone join the round and keep that value until successful input-reg.
- The logic became more sophisticated so it was moved into MaxSuggestedAmountProvider and slightly refactored the way how it works. 
- MaxSuggestedAmountProvider moved out of CreateRoundParameter
I would begin the review with the Test.

Keep largest MaxSuggestedAmount until successful input reg

---

WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs

Removing these, because these were consistent with the remaining log entries, so no error was to be found there.

Remove unnecessary log

---

WalletWasabi.Backend/Controllers/WabiSabi/RequestTimeStatista.cs

We've seen the initial numbers. Note that normally it should be probably one day.

Increase statista time to 60 minutes

---

WalletWasabi/WabiSabi/Backend/Rounds/TimeFrame.cs

I noticed only me getting into the blame rounds, because others are thinking the signing ends and I am using the master. Since testnet mixes were also with the master, it didn't come out at testnet deployment.

Reduce buffer of signing to zero

---

WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
WalletWasabi/WabiSabi/Backend/Rounds/Round.cs
WalletWasabi/WabiSabi/Backend/Rounds/RoundParameters.cs
WalletWasabi/WabiSabi/Backend/WabiSabiConfig.cs

When we already know that the previous phase failed, then we have an opportunity to make the followup phases faster to blame. 
fixes https://github.com/zkSNACKs/WalletWasabi/issues/8447 
fixes https://github.com/zkSNACKs/WalletWasabi/issues/8448 
fixes https://github.com/zkSNACKs/WalletWasabi/issues/8450
fixes https://github.com/zkSNACKs/WalletWasabi/issues/8451

Timeout fast when previous phase failed

---

WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
WalletWasabi/WabiSabi/Backend/Rounds/Round.cs
WalletWasabi/WabiSabi/Backend/Rounds/TimeFrame.cs

It turns out buffer time makes no sense at all. For input registration it misbehaves, for conn conf I don't remember, but probably it also misbehaves, one might test this, but for the rest the Poisson does not extend to the full length of the timeouts, so with the buffer time we cannot make the software to hurry.
Resolves https://github.com/zkSNACKs/WalletWasabi/issues/8429
Resolves https://github.com/zkSNACKs/WalletWasabi/issues/8422

Revert buffer time

---

WalletWasabi.Backend/Filters/LateResponseLoggerFilter.cs
WalletWasabi/WabiSabi/Backend/Models/WrongPhaseException.cs

Fixes: #8449
So we can analyze it and fine-tune the config if it's needed.

Log phase duration in case of late requests, so we can analyze it

---

WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
WalletWasabi/WabiSabi/Backend/Rounds/TimeFrame.cs
WalletWasabi/WabiSabi/Backend/WabiSabiConfig.cs
WalletWasabi/WabiSabi/Client/RoundStateAwaiters/RoundStateAwaiter.cs
WalletWasabi/WabiSabi/Client/RoundStateAwaiters/RoundStateUpdater.cs

Now coinjoins are failing because we have too many users. This PR introduces the concept of running multiple rounds in parallel depending on the configuration.
This also orders the round state response based on input count so the first state will be returned has the least amount of inputs so we can balance the load.  
This does not work on regtest in the sense that my clients still keep registering to the exact same round and I am not sure why that's happening as when I reviewed the client code it seemed to be keeping the order it got from the server. I have a theory though: maybe that it's because the regtest wallets share the same status response and that's somehow ensures old order. We'll have to test this on testnet.
Edit: it won't work. It'll help a bit though. The good news is that …

Implement parallel rounds

---

WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
WalletWasabi/WabiSabi/Backend/WabiSabiConfig.cs

Our latest issue is having too many inputs registered to coinjoins. So many that we rounds are almost failing for sure.
This PR implements a load balancer that is compatible with WW2.0.0 coinjoin clients. The tricky thing there is that they accidentally enforce ordering with `ToImmutableDictionary` and so when we want them to prefer a smaller input count round we must create a round that is ordered to the beginning by `ToImmutableDictionary`.

Implement WW2.0.0 Compatible CJ Load Balancer

---

WalletWasabi/WabiSabi/Client/CoinJoinClient.cs

There's an ongoing DDoS attack on the Tor network. This effectively simulates a DDoS attack on the protocol. We observe that blame rounds not concluding to `minInputCount`, but stop execution after 6 times often prevents coinjoins from happening at all. This PR fixes this DDoS (as well as centralized DoS) attack vector.
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/8498

Improve DDoS Protection

---

WalletWasabi.Tests/UnitTests/WabiSabi/Backend/AliceTimeoutTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepOutputRegistrationTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepTransactionSigningTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Client/BobClientTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiHttpApiIntegrationTests.cs
WalletWasabi/WabiSabi/Backend/Models/WrongPhaseException.cs
WalletWasabi/WabiSabi/Backend/Models/WrongPhaseExceptionData.cs
WalletWasabi/WabiSabi/Client/AliceClient.cs
WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
WalletWasabi/WabiSabi/Models/Serialization/ExceptionDataJsonConverter.cs

Closes #8487
When received a WrongPhase error from the coordinator the client now cancels all pending input registration requests and connection confirmation requests depending on the current phase.

Abort pending requests when we are late

---

WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiHttpApiIntegrationTests.cs
WalletWasabi/WabiSabi/Client/WabiSabiHttpApiClient.cs

This PR is for retying http requests until they are cancelled. Given that during coinjoins each phase has its own cancellation tokens that are automatically cancelled when the phases finishes all retries are cancelled once the phase timeouts.
Closes https://github.com/zkSNACKs/WalletWasabi/issues/8500

Continue retrying requests until the phase finishes

---

WalletWasabi.Tests/WalletWasabi.Tests.csproj

The latest available version has [NRT](https://docs.microsoft.com/en-us/dotnet/csharp/nullable-references) support which is nice because `Assert.NotNull(variable)` makes analyzers aware of the fact that `variable` is later certainly not `null`.
The version is called `pre` but it works as good as the current version. By the way, dotnet/runtime is on a pre version too https://github.com/dotnet/runtime/pull/63948.
* https://github.com/xunit/xunit/discussions/2414

Upgrade xUnit to get NRT support

---

WalletWasabi/WabiSabi/Client/DependencyGraphTaskScheduler.cs

Visual Studio shows an analyzer error without this patch. It's distracting. No need to merge any time soon.

[trivial] Fix analyzer error.

---

WalletWasabi/Tor/TorMonitor.cs

We say in our logs that we're switching to clearnet, which is not true. We're still over Tor, it's just we utilize an exit node, that's all. This PR clarifies wording, as well it increases the time from 7 to 21 sec before we do this.

Clarify wording + Increase Time

---

WalletWasabi/WabiSabi/Client/CoinJoinClient.cs

1. Step: look at the code
2. Step: read this -->
First note that I am not sure about this change, because the logic here is a bit complex, but here's my take:
For connection confirmation cancellation:
- I believe the original code said: "I want to cancel all ongoing connection confirmation requests, because I am in connection confirmation already."  
- I believe this should say: "I want to cancel all ongoing connection confirmation requests, because I am NOT in input registration, nor in connection confirmation anymore."
`confirmationsCts.Token` is linked up with `connConfTimeoutCancel` and `cancel` tokens, which results in `linkedConfirmationsCts`, which's token flows through all the alices' `RegisterInputAsync`s, `CreateRegisterAndConfirmInputAsync`s to finally cancel …

Cancel when not conn conf

---

WalletWasabi.Fluent/Global.cs
WalletWasabi/Tor/TorMonitor.cs

Closes https://github.com/zkSNACKs/WalletWasabi/issues/8430
Back in the day when we switched from onion v2 to onion v3 we experienced many days of downtime every month. This PR removes the temporary measures those were taken to keep the system up. With @lontivero we decided to remove them. I'm also deploying merging this quickly, because we need a whole day of testing before tomorrow's release.

Avoid exit nodes

---

WalletWasabi.Fluent/ViewModels/MainViewModel.cs

Wasabi was unable to close normally, even though in the logs it said it stopped gracefully.
This PR fixes that problem.

Fix for Tor Checker preventing application from closing normally

---

WalletWasabi.Fluent/Controls/StatusItem.axaml
WalletWasabi.Fluent/Controls/StatusItem.axaml.cs
WalletWasabi.Fluent/Views/StatusIcon/TorIssuesControl.axaml

As stated by @yahiheb, the Tor network **issues warning symbol** looks smaller than the rest of the items.
This PR makes it have the correct size.
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/8527

[VDG] Make TorIssuesControl have a proper size in StatusIcon

---

WalletWasabi/WabiSabi/Client/WabiSabiHttpApiClient.cs

During yesterday's testnet testing session I noticed I DoS attacked the round in signing phase: I got an exception and instead of keep retrying to signing I did not even though I still had a lot of time to do that.
```
2022-06-26 19:04:51.955 [384] DEBUG     CoinJoinClient.ProceedWithSigningStateAsync (760)       Round (5a624f4b4d7fce071218570b0cc836575e015f8bb8cd078d47afa273135b2dd9): 7 out of 7 Alices have signed the coinjoin tx.
2022-06-26 19:06:32.960 [312] WARNING   TorTcpConnectionFactory.ConnectToDestinationAsync (265) Connection response indicates a failure. Actual response is: 'TtlExpired'. Request: 'testwnp3fugjln6vh5vpj7mvq3lkqqwjj3c2aafyu7laxz42kgwh2rad.onion:80'.
2022-06-26 19:06:32.964 [312] ERROR     TorTcpConnectionFactory.ConnectToDestinationAsync (288) Exception occurred …
```

Keep retrying for any transport exception

---

WalletWasabi.Backend/wwwroot/css/style.css

We recognized a bug on the Firefox browser that can't handle the backdrop-filter CSS attribute, so on Firefox, there is a bit different effect.

Firefox blur effect fixes

---

WalletWasabi.Fluent/Views/StatusIcon/StatusIcon.axaml

Causes string to display instead of the icon.
Fixes this problem:

[VDG] Fix bad StatusIcon icon

---

WalletWasabi.Fluent/Behaviors/SearchBarBehavior.cs

Theme switching from the SearchBar makes the flyout appear in the wrong position.
The problem is that the behavior is detached and reattached. This causes issues with visuals (as popup locating in the wrong place).
This PR is a quick fix for the bad behavior. 
It could have been more elegant (reopen after reattaching of previously detached). Unfortunately, it seems it's more complex than it initially looked. 
Anyways, the behavior after this PR is completely acceptable, in my opinion.
I wouldn't like to spend too much time on this, because I would like to fully rewrite the popup behavior logic.
Fixes #8321

[VDG] Fix bad flyout behavior after theme switch

---

WalletWasabi.Backend/Program.cs

This allows an override of the wasabi backend with an env var, to allow binding the backend to ips dynamically (it is currently impossible to run the backend in a docker image as i need to bind to 0.0.0.0)

Allow override of backend url

---

WalletWasabi.Tests/Helpers/BitcoinFactory.cs
WalletWasabi.Tests/UnitTests/BlockchainAnalysis/CoinJoinAnonscoreTests.cs
WalletWasabi/Blockchain/Analysis/BlockchainAnalyzer.cs
WalletWasabi/Blockchain/TransactionOutputs/SmartCoin.cs
WalletWasabi/Blockchain/Transactions/SmartTransaction.cs
WalletWasabi/Blockchain/Transactions/TransactionFactory.cs

Following the suggestion (https://github.com/zkSNACKs/WalletWasabi/pull/7932#issuecomment-1139666528) of @onvej-sl this PR brings in the first bunch of commits to the Wasabi repository. My modifications do not touch the logic, the goals were to keep things consistent and to avoid directly accessing private members.
Skipped https://github.com/zkSNACKs/WalletWasabi/commit/d24c7d264fe8c9489d3558ac8569c77eb57d029a as it was reverted later.  
Skipped https://github.com/zkSNACKs/WalletWasabi/commit/f7fc29423ab95670a7f30258b1135c6f239a7dac as this code isn't in the master anymore and https://github.com/zkSNACKs/WalletWasabi/commit/c46ee54a1e8c895bd60504ec56f563130361ae37 as it makes no sense without the previous code.

Preparation for anonymity calculation improvement

---

WalletWasabi/Services/Terminate/TerminateService.cs

Second attempt after #5253
`IsTerminateRequested` was used in the `Daemon` class which was removed.

Remove dead code

---

WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepConnectionConfirmationTests.cs
WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
WalletWasabi/WabiSabi/Backend/Rounds/Round.cs

This removes the temporary fix of ending the round we introduced recently due to a bug in 2.0.0 clients. I believe now we have enough 2.0.1 clients so that going into the blame chain is more preferable than bailing out early on. This is also the blocker of bringing back the max suggested input count concept.

Filter out WW2.0.0 Clients in the First Round

---

WalletWasabi/WabiSabi/Client/WabiSabiHttpApiClient.cs

So we don't get this noise in the debug logs:
```
2022-07-02 22:02:24.043 [74] DEBUG	WabiSabiHttpApiClient.SendWithRetriesAsync (113)	Attempt 1 failed with exception System.Threading.Tasks.TaskCanceledException: A task was canceled.
at System.Net.Http.HttpContent.LoadIntoBufferAsyncCore(Task serializeToStreamTask, MemoryStream tempBuffer)
at System.Net.Http.HttpContent.WaitAndReturnAsync[TState,TResult](Task waitTask, TState state, Func`2 returnFunc)
at WalletWasabi.Tor.Http.Extensions.HttpRequestMessageExtensions.ToHttpStringAsync(HttpRequestMessage request, CancellationToken cancellationToken) in WalletWasabi\Tor\Http\Extensions\HttpRequestMessageExtensions.cs:line 80
at WalletWasabi.Tor.Socks5.Pool.TorHttpPool.SendCoreAsync(TorTcpConnection connection, HttpRequestMessage request, …
```

Only logtrace OperationCanceledException

---

WalletWasabi/WabiSabi/Client/AliceClient.cs
WalletWasabi/WabiSabi/Client/CoinJoinClient.cs

All clients (2.0.x) continue with inputs registration/confirmation even after receiving a `RoundNotFound` error.

Abort registrations on ended rounds

---

WalletWasabi.Fluent/Styles/SettingsLayout.axaml
WalletWasabi.Fluent/ViewModels/Settings/SettingsPageViewModel.cs
WalletWasabi.Fluent/Views/Settings/SettingsPageView.axaml

Fixes #8573 
- Settings UI is now a dialog:
As per [this comment](https://github.com/zkSNACKs/WalletWasabi/issues/8573#issue-1288609034) this could have caused a problem where settings would have required a "live refresh" behavior if they were used in possible active screens throughout the software, which would remain active since there is no longer a navigation occurring when you open the settings UI.
- All settings currently available in the UI have been tracked, and fall into one of these categories:
- The setting is used in the UI, but inside a dialog (such as send or receive dialog), and therefore does not need "live refresh"
- The setting requires a restart, therefore it does not need "live refresh"
Therefore no further action is required.

[VDG] Settings dialog

---

WalletWasabi.Fluent/Behaviors/HorizontalScrollViewerBehavior.cs
WalletWasabi.Fluent/Controls/LabelsListBox.axaml

Fixes #8562 
This seems to be an Avalonia bug, since `HorizontalScrollBarVisibility="Disabled"` does not restrict <kbd>Shift</kbd>+ mouse wheel scrolling.

[VDG] LabelsList scroll fix

---

WalletWasabi.Tests/AssertAsync.cs
WalletWasabi.Tests/UnitTests/LinqExtensionsTests.cs
WalletWasabi/Extensions/LinqExtensions.cs

Fixes https://github.com/zkSNACKs/WalletWasabi/issues/8619.
https://github.com/zkSNACKs/WalletWasabi/commit/4d05490b85ce7d8feb12d3f6e629bca80f9dc5bf and https://github.com/zkSNACKs/WalletWasabi/commit/76a58f9aef77aa80879df3c9d55fca205e31c685 test the desired behaviour. Feel free to remove them if you think they are not needed.
https://github.com/zkSNACKs/WalletWasabi/commit/b8ca7461658d61025ee69be6ba0d73c051e95f09 is mere refactoring commit.
https://github.com/zkSNACKs/WalletWasabi/commit/141d5cc45bcecfea263dcfc6b0b3f374ab5e586b actually fixes the bug.

Fix of CombinationsWithoutRepetition()

---

WalletWasabi/Tor/Socks5/TorTcpConnectionFactory.cs

Related to #8617
This PR should reduce repeated exception logs. We log an exception in `TorTcpConnectionFactory` to log it again in `TorHttpPool` basically.

`TorTcpConnectionFactory`: Log only on trace level

---

WalletWasabi/Services/WasabiSynchronizer.cs
WalletWasabi/Wallets/Wallet.cs

<s>Depends on #8639</s>
Request blocking is no longer used in WW2 code. 
[Review with whitespace off](https://github.com/zkSNACKs/WalletWasabi/pull/8640/files?diff=split&w=1).

`WasabiSynchronizer`: Remove request blocking

---

WalletWasabi.Fluent/Config.cs
WalletWasabi.Fluent/Global.cs
WalletWasabi.Tests/Helpers/WabiSabiFactory.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepOutputRegistrationTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepTransactionSigningTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterInputFailureTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterInputSuccessTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/SignTransactionTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Backend/Rounds/MultipartyTransactionStateTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Client/ArenaClientTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Client/BobClientTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Crypto/OwnershipProofTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiApiApplicationFactory.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Models/InputRegistrationRequestTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Models/MultipartyTransactionTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Models/SerializationTests.cs
WalletWasabi/WabiSabi/Backend/Rounds/Arena.Partial.cs
WalletWasabi/WabiSabi/Backend/Rounds/Round.cs
WalletWasabi/WabiSabi/Backend/Rounds/RoundParameters.cs
WalletWasabi/WabiSabi/Backend/WabiSabiConfig.cs
WalletWasabi/WabiSabi/Client/AliceClient.cs
WalletWasabi/WabiSabi/Client/ArenaClient.cs
WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
WalletWasabi/WabiSabi/Client/CoinJoinTrackerFactory.cs
WalletWasabi/WabiSabi/Crypto/RoundHasher.cs
WalletWasabi/WabiSabi/Models/MultipartyTransaction/ConstructionState.cs
WalletWasabi/WabiSabi/Models/MultipartyTransaction/MultipartyTransactionState.cs
WalletWasabi/WabiSabi/ProtocolConstants.cs

Reverts zkSNACKs/WalletWasabi#8635
The reverted PR breaks client-coordinator compatibility in two ways:
1. It prevents clients on the master from coinjoining with the currently running coordinator. This would not mean there's something wrong with the PR, it'd just mean that the backend has to be deployed at the same time of merging the reverted PR. However...
2. It also prevents clients currently deployed to users from coinjoining with the coordinator running from the master. This must be fixed.

Revert "Return ownership proofs"

---

WalletWasabi/WabiSabi/Client/CoinJoinClient.cs

When input registration is unsuccessful we don't know why (or even that it was unsuccessful) from the logs.  
I am experiencing an issue that only a portion of my input registrations go through and I have no idea why. This should tell me. 
Update: The issue I was experiencing: https://github.com/zkSNACKs/WalletWasabi/issues/8674

Don't swallow exception

---

WalletWasabi/WabiSabi/Client/AliceClient.cs
WalletWasabi/WabiSabi/Client/CoinJoinClient.cs

Fixes: #8674
But this raises a big question.
We had these scenarios to handle the exceptions in the past. Worked quite well, when I implemented the client-side banning "feature".
https://github.com/zkSNACKs/WalletWasabi/blob/master/WalletWasabi/WabiSabi/Client/AliceClient.cs#L105-L145
But those cases are never ever hit anymore. Why?
What happened to them? Why aren't we catching and handling exceptions in `AliceClient` anymore?

Make AliceClient handle Protocol exceptions

---

WalletWasabi/Services/WasabiSynchronizer.cs
WalletWasabi/Tor/Socks5/Exceptions/TorConnectCommandFailedException.cs
WalletWasabi/Tor/Socks5/Models/ReplyType.cs

Hopefully improves #8618
I believe that what can happen is simply:
1. https://github.com/zkSNACKs/WalletWasabi/blob/b72765fe834e068fa6d8feae83473bc0ef05ccbb/WalletWasabi/Services/WasabiSynchronizer.cs#L168-L170 throws because Tor circuit dies (TTL expiration) or fails in any way.
2. We get here https://github.com/zkSNACKs/WalletWasabi/blob/b72765fe834e068fa6d8feae83473bc0ef05ccbb/WalletWasabi/Services/WasabiSynchronizer.cs#L177-L184
3. We throw https://github.com/zkSNACKs/WalletWasabi/blob/b72765fe834e068fa6d8feae83473bc0ef05ccbb/WalletWasabi/Services/WasabiSynchronizer.cs#L183
4. https://github.com/zkSNACKs/WalletWasabi/blob/b72765fe834e068fa6d8feae83473bc0ef05ccbb/WalletWasabi/Services/WasabiSynchronizer.cs#L273 is executed and an exception is logged.
However, #8553 should make it less …

`WasabiSynchronizer`: Improve exception handling

---

WalletWasabi.Fluent/Controls/LabelsPanel.cs

Fixes https://github.com/zkSNACKs/WalletWasabi/issues/8331
The issue was with long labels no item height was taken into calculation of ellipsis control so it had height equal zero, this PR fixes that and takes first label item height to arrange ellipsis control.
Now with long labels the ellipsis control is displayed correctly each time.

[VDG] Fix LabelsPanel not displaying all items

---

WalletWasabi/Extensions/LinqExtensions.cs
WalletWasabi/WabiSabi/Client/CoinJoinClient.cs

Best to review commit by commit.
In order to mix AS of selected coins, previously a quick solution was used for coin selection that was altering high and low AS coins. This PR changes the alternation pattern to shuffling while biasing towards lower AS.
In this PR I also limit the number of private coins those might participate to `desired input count - 1`. `-1` because a non-private coins' place must be always ensured.

Weakly consider AS for coin selection

---

WalletWasabi/Tor/TorMonitor.cs

This PR replaces #8655 and adds the missing Tor restarting capability.
[Review with whitespace off.](https://github.com/zkSNACKs/WalletWasabi/pull/8669/files?diff=split&w=1)
To test this PR, one can use this branch https://github.com/kiminuo/WalletWasabi/tree/feature/2022-07-08-TorMonitor-testing-code and most notably the commit https://github.com/kiminuo/WalletWasabi/commit/80adf02670106565e2e5ae446fffd5c68eac0317 so that one:
1. Starts WW and watches running processes
2. After a minute you should see that Tor process disappears and it is started again + the WW logs should describe the same things really.

`TorMonitor`: Add restarting capability

---

WalletWasabi.Fluent.Desktop/Program.cs
WalletWasabi.Fluent/ViewModels/Wallets/Send/ChangeAvoidanceSuggestionViewModel.cs
WalletWasabi.Fluent/ViewModels/Wallets/Send/PrivacySuggestionsFlyoutViewModel.cs
WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionPreviewViewModel.cs

Fixes: #8565
Alternative to: #8567
Review with [whitespace changes off](https://github.com/zkSNACKs/WalletWasabi/pull/8594/files?diff=split&w=1)
Current master allows to call `PrivacySuggestionsFlyoutViewModel.BuildPrivacySuggestionsAsync` method multiple times because `BuildPrivacySuggestionsAsync` contains method calls with `ConfigureAwait(false)`. It is not optimal because it seems it leads to exceptions like the one mentioned in #8565 but also it leads to higher use of CPU than necessary (only for limited amount of time though).

Allow only single run of `PrivacySuggestionsFlyoutViewModel.BuildPrivacySuggestionsAsync`

---

WalletWasabi.Fluent/Views/Shell/DialogsView.axaml

@wieslawsoltes found this bug while we were working on https://github.com/zkSNACKs/WalletWasabi/pull/8580. Not sure why Avalonia stable versions were still working with this bug in.

[VDG] Remove null style setter

---

WalletWasabi.Backend/Controllers/BlockchainController.cs

We get a lot of notifications on our monitoring service, which is an annoyance. Also note that unlike in WW1 where a round happened every hour, in WW2 we aren't relying on such timeouts anymore, rather on reaching required input count instead.

Change WW2 monitor timeout from 1h to 3h

---

WalletWasabi/Tor/Control/Messages/Events/StatusEvents/StatusEvent.cs
WalletWasabi/Tor/TorMonitor.cs

This PR is meant to improve our understanding that something is wrong with Tor circuit building.
I did not add any rate limiting because it looks to me that the event should be reported only once in (long) while.

`TorMonitor`: Report that "we are no longer confident that we can build Tor circuits"

---

WalletWasabi.Fluent/ViewModels/Wallets/Advanced/WalletCoins/WalletCoinsViewModel.cs

A set of priorities have been assigned to the different indicators. This enables sorting for the indicators column:
These are the values:
```
1: Coinjoining
2: Banned
3: Unconfirmed (!Confirmed)
```
This is just a value to discriminate the possible states, so the sorting can know which elements are grouped. 
Different priority values give similar results in the GUI, but I have considered these are giving the desired outcome.
Fixes #8758

[VDG] Add ability to sort coins in Coin List by indicators

---

WalletWasabi.Fluent/Behaviors/SearchBarBehavior.cs

A workaround we introduced for W10 causes focus to be lost when the application window is deactivated.
With this PR, it should no longer happen. 
Presumably fixes #8733

[VDG] Fix for focus loss after window becomes inactive

---

WalletWasabi.Fluent/Views/CoinJoinProfiles/CoinJoinProfilesView.axaml

When using DataTemplate without DataType we should use ItemTemplate instead of DataTemplates i(n Avalonia 11 it will throw exception).

[VDG] Use ItemTemplate instead of DataTemplates

---

WalletWasabi.Documentation/WasabiCompatibility.md

Added disclaimer about trezor model T and model one no longer being supported

Update compatibiltiy information

---

WalletWasabi.Tests/UnitTests/Tor/TorSettingsTests.cs
WalletWasabi/Tor/TorSettings.cs

My hope is that we might alleviate the signing issue with this PR. The change is trivial but the implications might affect privacy so please review carefully.
This is the signing issue as I can see it in logs:
```log
2022-07-29 18:25:16.953 [29] TRACE	TorHttpPool.ReportCircuitStatus (436)	Tor circuit was built: #531 ('[PersonCircuit: TQ98BYW60WN3E5GYEZL91]').
// NOTE THAT TEN MINUTES ELAPSED!
2022-07-29 18:35:37.116 [52] TRACE	TorHttpPool.ObtainFreeConnectionAsync (281)	> request='http://wasabiukrxmkdgve5kynjztuovbg43uxcbcxn6y2okcrsg7gb6jdmbad.onion/wabisabi/transaction-signature', circuit=[PersonCircuit: TQ98BYW60WN3E5GYEZL91]
2022-07-29 18:35:37.116 [52] TRACE	TorHttpPool.ObtainFreeConnectionAsync (297)	[OLD PC#0089#TQ98BYW60W]['http://wasabiukrxmkdgve5kynjztuovbg43uxcbcxn6y2okcrsg7gb6jd …
```

`TorSettings`: Use `KeepAliveIsolateSOCKSAuth` flag

---

WalletWasabi/Services/WasabiSynchronizer.cs

Yahia's [comment ](https://github.com/zkSNACKs/WalletWasabi/pull/8810#issuecomment-1200053304) shows that we do not handle proper exception and thus when stopping WW we might show an exception stacktrace when it's not needed. 
This PR should correct that slightly.

`WasabiSynchronizer`: Fix exception being handled.

---

WalletWasabi.Fluent.Desktop/Program.cs
WalletWasabi.Fluent/CrashReport/ViewModels/CrashReportWindowViewModel.cs
WalletWasabi/Models/SerializableException.cs

I made modifications so we don't lose important information when a crash happens.
The stack trace was being ovewritten, so we never had the chance to see what really happened.
To illustrate the fix, here is what the Crash Reporter shows to the user with and without this fix.
> Wallet with the same name was already added: Wallet 24.
> 
>    at WalletWasabi.Fluent.Desktop.Program.<>c__DisplayClass1_1.<Main>b__4() in WalletWasabi.Fluent.Desktop\Program.cs:line 106
>    at System.Reactive.Concurrency.Scheduler.Invoke(Action action) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/Scheduler.Simple.cs:line 253
>    at System.Reactive.Concurrency.Scheduler.<>c.<Schedule>b__74_0(IScheduler _, Action a) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/Scheduler.Simple.cs:line 37
>    at …

[VDG] Trace all info in exception on app crash

---

WalletWasabi/Tor/Http/Helpers/HttpMessageHelper.cs
WalletWasabi/Tor/Socks5/Pool/TorHttpPool.cs

Related to #6215
This PR changes the exception being thrown in `HttpMessageHelper` from `NotSupportedException` (denoting unexpected failure) to `TorConnectionReadException` (denoting failure that is expected to happen from time to time).
The reason for this change is this (combined) log:
```log
Jul 28 09:23:00.824 [info] circuit_launch_by_extend_info(): Cannibalizing circ 2258840194 (id: 249) for purpose 9 (Hidden service client: Establishing rendezvous point)
Jul 28 09:23:00.852 [info] connection_ap_handshake_attach_circuit(): Intro 3003528868 (id: 256) and rend circuit 2258840194 (id: 249) circuits are not both ready. Stalling conn. (0 sec old)
Jul 28 09:23:01.957 [info] connection_ap_handshake_attach_circuit(): Intro 3003528868 (id: 256) and rend circuit 2258840194 (id: 249) circuits …
```

`HttpMessageHelper`: Change exception being thrown

---

WalletWasabi.Fluent/Views/Wallets/Advanced/WalletCoins/Columns/IndicatorsColumnView.axaml

The only usage remaining seems to be the indicator column in Coin List.
Fixes #6986

[VDG] [Trivial] Replace coinjoin icon

---

WalletWasabi.Fluent.Desktop/Program.cs
WalletWasabi.Fluent/Config.cs
WalletWasabi.Fluent/Global.cs
WalletWasabi.Fluent/Services.cs
WalletWasabi.Fluent/ViewModels/Settings/GeneralSettingsTabViewModel.cs
WalletWasabi.Fluent/ViewModels/StatusIcon/StatusIconViewModel.cs
WalletWasabi.Fluent/Views/Settings/GeneralSettingsTabView.axaml
WalletWasabi.Fluent/Views/StatusIcon/StatusIcon.axaml
WalletWasabi/Models/UpdateStatus.cs
WalletWasabi/Services/UpdateChecker.cs
WalletWasabi/Services/UpdateManager.cs

This PR implements an `UpdateManager.cs` class which makes updating after a new release easier.
**Old flow:**
1. In case of new version, Wasabi indicates to "Update".
2. Click on "Update" button.
3. Get redirected to Wasabi website.
4. Find your version to download based on OS.
5. Install manualy.
**New flow** is somewhat simpler:
1. In case of new version, Wasabi downloads the version you need in the background, then indicates "Close and Update".
2. Click on "Close and Update".
3. Upon closing, the installer will start automatically.
1. Find `WalletWasabi/Helpers/Constants.cs`.
2. Change `ClientVersion` to: `new(2, 0, 0, 1)` or any other version thats smaller then current.
3. Start Wasabi and go through the steps above.
4. You can also double check logs and see if …

Make software update flow better

---

WalletWasabi.Fluent/ViewModels/AddWallet/HardwareWallet/DetectedHardwareWalletViewModel.cs
WalletWasabi.Tests/AcceptanceTests/HwiKatas.cs
WalletWasabi/Hwi/Models/HardwareWalletModels.cs

This PR aims to add support for the new Ledger Nano S+, enabled by the #7791 HWI Update PR.
cc @nopara73 @Szpoti @zkSNACKs/code-team

Add support for Ledger Nano S+

---

WalletWasabi.Fluent/ViewModels/Wallets/Advanced/WalletCoins/WalletCoinsViewModel.cs
WalletWasabi.Fluent/ViewModels/Wallets/CoinJoinSettingsViewModel.cs
WalletWasabi.Fluent/ViewModels/Wallets/CoinJoinStateViewModel.cs
WalletWasabi.Fluent/ViewModels/Wallets/Send/SendFeeViewModel.cs
WalletWasabi.Fluent/ViewModels/Wallets/WalletSettingsViewModel.cs
WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModel.cs
WalletWasabi.Fluent/Views/Wallets/CoinJoinSettingsView.axaml
WalletWasabi.Fluent/Views/Wallets/CoinJoinSettingsView.axaml.cs
WalletWasabi.Fluent/Views/Wallets/MusicControlsView.axaml
WalletWasabi.Fluent/Views/Wallets/WalletSettingsView.axaml
WalletWasabi.Fluent/Views/Wallets/WalletView.axaml

**Adds a separate Coinjoin Settings page** as a new dialog.
*As requested in the WW2.0 meeting held on 01/08/2022.*
- Moves every coinjoin related setting from the Wallet Settings to this new Coinjoin Settings.
- For watch-only wallets (hardware wallets are included, they are also watch-only wallets) it's not visible.
- Reachable from the ... menu next to the Send and Receive button.
~~Bonus: A tiny faded/semi-transparent settings icon on the MusicBox. Please, check how it looks. It is just an idea yet.~~

[VDG] Add Coinjoin Settings dialog

---

WalletWasabi/Tor/Socks5/Pool/TorHttpPool.cs

These exceptions are being logged in `TorHttpPool.SendAsync` so we log them twice and logs look worse than they are.
Allows us to see how long it takes to create a new Tor SOCKS5 connection:
```log
2022-08-03 00:13:25.630 [34] TRACE	TorHttpPool.CreateNewConnectionAsync (286)	[NEW DC#0001#NLV34Q4JQ4]['https://status.torproject.org/index.xml'] Created new Tor SOCKS5 connection in 00:00:01.8913407.
2022-08-03 00:13:41.658 [34] TRACE	TorHttpPool.CreateNewConnectionAsync (286)	[NEW PC#0002#66NZVM1LC9]['http://wasabiukrxmkdgve5kynjztuovbg43uxcbcxn6y2okcrsg7gb6jdmbad.onion/wabisabi/status'] Created new Tor SOCKS5 connection in 00:00:17.8907451.
2022-08-03 00:13:42.081 [34] TRACE	TorHttpPool.CreateNewConnectionAsync (286)	[NEW DC#0003#NLV34Q4JQ4]['http://wasabiukrxmkdgve5kynjztuovbg43uxcbcxn6y2okc …
```

Simplify `TorHttpPool.CreateNewConnectionAsync`

---

WalletWasabi.Fluent.Desktop/Program.cs

This simple PR TraceLogs all unobserved `SocketExceptions`, e.g. when a peer disconects, so it won't get overwhelmed in the logs during debuging.
Until better handling gets added on NBitcoin's side, this is the best way not to get burried alive in these exceptions.

[Trivial] Hide overwhelming `SocketExceptions`

---

WalletWasabi.Backend/docker-compose.yml
WalletWasabi.Fluent/Global.cs
WalletWasabi.Fluent/ViewModels/WalletManagerViewModel.cs
WalletWasabi.Tests/UnitTests/TestWallet.cs
WalletWasabi/Services/WasabiSynchronizer.cs
WalletWasabi/Tor/Control/TorControlClientFactory.cs
WalletWasabi/Tor/TorProcessManager.cs
WalletWasabi/Tor/TorSettings.cs
WalletWasabi/WabiSabi/Client/BaseKeyChain.cs
WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
WalletWasabi/WabiSabi/Client/CoinJoinTracker.cs
WalletWasabi/WabiSabi/Client/CoinJoinTrackerFactory.cs
WalletWasabi/WabiSabi/Client/DependencyGraphTaskScheduler.cs
WalletWasabi/WabiSabi/Client/IKeyChain.cs
WalletWasabi/WabiSabi/Client/IWalletProvider.cs
WalletWasabi/WabiSabi/Client/IWasabiBackendStatusProvider.cs
WalletWasabi/WabiSabi/Client/KeyChain.cs
WalletWasabi/WabiSabi/Client/StatusChangedEvents/CoinJoinStatusEventArgs.cs
WalletWasabi/WabiSabi/Client/StatusChangedEvents/CompletedEventArgs.cs
WalletWasabi/WabiSabi/Client/StatusChangedEvents/LoadedEventArgs.cs
WalletWasabi/WabiSabi/Client/StatusChangedEvents/StartErrorEventArgs.cs
WalletWasabi/WabiSabi/Client/StatusChangedEvents/StartedEventArgs.cs
WalletWasabi/WabiSabi/Client/StatusChangedEvents/StatusChangedEventArgs.cs
WalletWasabi/WabiSabi/Client/StatusChangedEvents/StoppedEventArgs.cs
WalletWasabi/WabiSabi/Client/StatusChangedEvents/WalletStartedCoinJoinEventArgs.cs
WalletWasabi/WabiSabi/Client/StatusChangedEvents/WalletStoppedCoinJoinEventArgs.cs
WalletWasabi/WabiSabi/LoggerTools.cs
WalletWasabi/Wallets/IWallet.cs
WalletWasabi/Wallets/Wallet.cs
WalletWasabi/Wallets/WalletManager.cs

This PR introduces as few changes as possible to reuse wabisabi client code (including decomposer) without using Wasabi's blockchain indexer and wallet structure. 
Notable changes:
* New interface  `IWasabiBackendStatusProvider` : This allows me to fetch backend status without needing the synchronizer as I do not need the filters.
*  `TorControlClientFactory` now takes an `EndPoint` instead of only an IP, as wabisabi client / Tor are often running in docker containers which use DNS names (e.g. `tor:9050`)
* New interface `IWallet` which provides the coinjoin settings. This interface is probably the bulk of the changes as I had to replace direct usage of `Wallet`.
* New abstract class `BaseKeyChain`, as ownership proof magic code is reusable but not if it is coupled with `KeyManager`
* a …

Abstractify enough to reuse Wabisabi without Wasabi wallet

---

WalletWasabi.Fluent/ViewModels/SearchBar/SearchBarViewModel.cs
WalletWasabi.Fluent/Views/SearchBar/SearchBarDropdown.axaml

No longer need to use RxUI ObservableAsPropertyHelper.

[VDG] Remove OAPH from SearchBar

---

WalletWasabi/WabiSabi/Client/CoinJoinClient.cs

When the backend aborts the round with Not enough inputs - on the client side the log contains warnings for every input. However, nothing to warn about is just a new round. 
```
2022-08-09 09:30:42.053 [49] DEBUG      WabiSabiHttpApiClient.SendWithRetriesAsync (100)        Received a response for ConfirmConnection in 0.9s.
2022-08-09 09:30:45.392 [49] DEBUG      WabiSabiHttpApiClient.SendWithRetriesAsync (100)        Received a response for ConfirmConnection in 0.67s.
2022-08-09 09:30:47.497 [49] DEBUG      WabiSabiHttpApiClient.SendWithRetriesAsync (100)        Received a response for ConfirmConnection in 1.32s.
2022-08-09 09:30:49.978 [49] DEBUG      WabiSabiHttpApiClient.SendWithRetriesAsync (100)        Received a response for ConfirmConnection in 0.66s.
2022-08-09 09:30:54.306 [49] …
```

Better log messages when round aborted with not enough alices

---

WalletWasabi/WabiSabi/Client/WabiSabiHttpApiClient.cs

Continuation of https://github.com/zkSNACKs/WalletWasabi/pull/8878
Tests result from https://github.com/zkSNACKs/WalletWasabi/pull/8878#issuecomment-1207759447
```
2022-08-08 09:14:00.816 [108] INFO      RequestTimeStatista2.Display (61)       Response times for the last 3862 minutes:
2022-08-08 09:14:00.821 [108] INFO      RequestTimeStatista2.Display (72)       Responded to 'XXX-API-OK-GetStatus'      21060 times. Median: 0.7s Average: 1.0s Largest 40.0s SuccessRatio: 1 FatalFails: 17
2022-08-08 09:14:00.824 [108] INFO      RequestTimeStatista2.Display (72)       Responded to 'XXX-API-OK-ConfirmConnection'      9033 times. Median: 0.9s Average: 1.7s Largest 212.4s SuccessRatio: 1 FatalFails: 9
2022-08-08 09:14:00.825 [108] INFO      RequestTimeStatista2.Display (72)       Responded to …
```

Add retry timeouts to CoinJoin requests

---

WalletWasabi/Tor/Socks5/TorTcpConnectionFactory.cs

This shows how the overloads work: https://github.com/dotnet/runtime/blob/0ec02c8c96e2eda06dc5b5edfdbdba0f36415082/src/libraries/System.Net.Security/src/System/Net/Security/SslStream.cs#L381-L422
.NET documentation: https://docs.microsoft.com/en-us/dotnet/api/system.net.security.sslstream.authenticateasclientasync?view=net-6.0#system-net-security-sslstream-authenticateasclientasync(system-net-security-sslclientauthenticationoptions-system-threading-cancellationtoken) -- unfortunately, they don't say what exception is thrown when the cancellation token is hit.

`TorTcpConnectionFactory`: Add missing cancellation token

---

WalletWasabi.Tests/UnitTests/Tor/TorProcessManagerTests.cs
WalletWasabi/Tor/Socks5/TcpClientSocks5Connector.cs
WalletWasabi/Tor/Socks5/TorTcpConnectionFactory.cs
WalletWasabi/Tor/TcpClientConnector.cs

Follow-up to #8851 and #8888
<s>Contains #8896 changes (just a test fix)</s>
Contains some changes from https://github.com/kiminuo/WalletWasabi/commit/23f26d718c021fbf9b67951b4ecb695139d934fe
Tor team responded to our [question](https://gitlab.torproject.org/tpo/core/tor/-/issues/40653) and we specifically asked whether it makes sense to use keep-alive functionality and:
>> Is it necessary to specify that keep-alive options? Is it recommended? Is it useless?
>
> I'm going to go with 'no', 'no', and 'unclear'.
So this PR removes that. The code for doing keep-alives were added with the hope that it changes something but nobody was able to say why it should improve anything (long story short: it cannot really). I actually did some test runs and I could not spot any difference with and …

Tor SOCKS5: Remove "keepalive" functionality

---

WalletWasabi.Tests/UnitTests/WabiSabi/Integration/Participant.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiHttpApiIntegrationTests.cs
WalletWasabi/BitcoinCore/Rpc/RpcClientBase.cs

This is fixing MultiClientsCoinJoinTestAsync for the CI. 
The test is good, just need to wait a bit more for the CoinJoin to be propagated into the mempool.

Fix CI - Wait a bit more for the CoinJoin

---

WalletWasabi/Tor/Socks5/Pool/TorHttpPool.cs
WalletWasabi/WabiSabi/Client/WabiSabiHttpApiClient.cs

`IHttpClient.SendAsync(..)` is not allowed to throw any `TorException`s. All such exceptions are wrapped in `HttpRequestException`.

`WabiSabiHttpApiClient`: Remove extra `catch`

---

WalletWasabi.Fluent/Controls/PrivacyContentControl.axaml

This PR splits PrivacyContentControl template into separate text and icon templates and also do not use IsVisible to hide privacy control contents, just use opacity. It was causing scrolling performance issues when labels presenter was included in the table cell and when visibility between text and icon controls was shared in same template (probably causing some weird layout invalidations in labels item presenter).
Fixes: #8378
Uploading screencast 2022-08-12 00-00-05.mp4…

[VDG] Optimize PrivacyContentControl template

---

.github/workflows/auto-add-to-projcet.yml

This action should add all the new issues to the Prioritization project board automatically.
Keep in mind the organization should have a token that called `AUTO_ADD_TO_PROJECT_TOKEN` with the right privileges in order to make the action work. I don't have the right to create one so someone should do it.
It only requires reading access to the projects:
More info here: https://github.com/marketplace/actions/add-to-github-projects

[GitHub Action] Add issues automatically to the project board

---

WalletWasabi.Fluent/Rpc/WasabiJsonRpcService.cs

Closes #8942
This PR add two new RPC calls `startcoinjoin` and `stopcoinjoin`. As all other rpc methods, these work at a wallet level so, the user has to select the wallet first with `selectwallet` and then call the new methods. 
The easiest way to test it is by using the [wcli.sh](https://github.com/lontivero/Wiki/blob/master/src/wasabi/wcli.md) 
Here is a session:
```
[lontivero@nixos:~/Projects/WalletWasabi]$ ~/wcli.sh selectwallet TestNet
null
[lontivero@nixos:~/Projects/WalletWasabi]$ ~/wcli.sh startcoinjoin 
2 parameters were expected but 0 were received.
[lontivero@nixos:~/Projects/WalletWasabi]$ ~/wcli.sh startcoinjoin true true
null
[lontivero@nixos:~/Projects/WalletWasabi]$ ~/wcli.sh stopcoinjoin
null
```
The `startcoinjoin` takes to parameters: `stopWhenAllMixed` and …

Add RPC `Start` and `Stop` coinjoin

---

WalletWasabi.Fluent/Views/StatusIcon/StatusIcon.axaml

A warning should first say what's wrong, and then why.

Prioritize warning

---

WalletWasabi.Fluent/Views/Wallets/Send/CustomFeeRateDialogView.axaml

1sat/vByte is the minimum, thus displaying 1 instead of 0

[VDG] custom fee CurrencyEntryBox improvement

---

WalletWasabi/WabiSabi/Backend/Banning/CoinVerifier.cs
WalletWasabi/WabiSabi/Backend/Banning/CoinVerifierApiClient.cs
WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs

The bug:
```
2022-08-19 18:26:35.320 [280] ERROR     Arena.StepInputRegistrationPhaseAsync (168)     System.ArgumentException: An item with the same key has already been added. Key: 0 a83cebbe930033ff4899bd6b4efd19074ccbb377
at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](List`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
at WalletWasabi.WabiSabi.Backend.Rounds.Arena.StepInputRegistrationPhaseAsync(CancellationToken cancel)
```
I made a mistake, when I thought `ScriptPubKey` will always be unique.
This commit https://github.com/zkSNACKs/WalletWasabi/pull/8981/commits/545f1a5fbf71605524ed2aec22b224196756bfbf fixes this by using `Coin` …

Adjust Timeouts + fix backend bug

---

WalletWasabi.Tests/UnitTests/Tor/Control/Messages/Events/StreamEventTests.cs
WalletWasabi.Tests/UnitTests/Tor/Control/Utils/AsyncEventParserTests.cs
WalletWasabi/Tor/Control/Messages/CircuitStatus/BuildFlag.cs
WalletWasabi/Tor/Control/Messages/CircuitStatus/CircStatus.cs
WalletWasabi/Tor/Control/Messages/CircuitStatus/CircuitInfo.cs
WalletWasabi/Tor/Control/Messages/CircuitStatus/HsState.cs
WalletWasabi/Tor/Control/Messages/CircuitStatus/Purpose.cs
WalletWasabi/Tor/Control/Messages/CircuitStatus/Reason.cs
WalletWasabi/Tor/Control/Messages/Events/StreamEvent.cs
WalletWasabi/Tor/Control/Messages/StreamStatus/ClientProtocol.cs
WalletWasabi/Tor/Control/Messages/StreamStatus/IsoFieldFlag.cs
WalletWasabi/Tor/Control/Messages/StreamStatus/Purpose.cs
WalletWasabi/Tor/Control/Messages/StreamStatus/Reason.cs
WalletWasabi/Tor/Control/Messages/StreamStatus/StreamInfo.cs
WalletWasabi/Tor/Control/Messages/StreamStatus/StreamStatusFlag.cs
WalletWasabi/Tor/Control/TorControlClientFactory.cs
WalletWasabi/Tor/Control/Utils/AsyncEventParser.cs
WalletWasabi/Tor/Control/Utils/Tokenizer.cs
WalletWasabi/Tor/TorMonitor.cs

This PR implements receiving of async [`STREAM` Tor events](https://github.com/torproject/torspec/blob/79da008392caed38736c73d839df7aa80628b645/control-spec.txt#L2403) for debugging purposes. It actually should allow us to map Tor circuits to our Tor SOCKS5 TCP connections so that we will know easily what went wrong with a TCP connection. Unfortunately, we have not implemented this much sooner as it would allow us to debug the issues we were/are having easier.
This PR does not have any user visible effect. 
Event examples:
```
650 STREAM 24 CLOSED 13 [2600:1f11:b5e:2a00:c289:d72:428f:b3be]:8333 REASON=END REMOTE_REASON=DONE SOCKS_USERNAME="GNT18N1AGE9A96WX7U2O2" SOCKS_PASSWORD="GNT18N1AGE9A96WX7U2O2" CLIENT_PROTOCOL=SOCKS5 NYM_EPOCH=0 SESSION_GROUP=-4 …
```

Subscribe Tor Control `STREAM` events

---

WalletWasabi.sln

https://docs.microsoft.com/en-us/visualstudio/extensibility/internals/solution-dot-sln-file?view=vs-2022
> The full version of Visual Studio that (most recently) saved the solution file. If the solution file is saved by a newer version of Visual Studio that has the same major version, this value is not updated so as to lessen churn in the file.
Bumped VS solution version to the one that VS2022 creates as a template by default

[Trivial] Bump VS version

---

WalletWasabi.Fluent/Rpc/WasabiJsonRpcService.cs
WalletWasabi.Tests/Helpers/ServiceFactory.cs
WalletWasabi.Tests/UnitTests/KeyManagementTests.cs
WalletWasabi.Tests/UnitTests/Transactions/TransactionFactoryTests.cs
WalletWasabi.Tests/UnitTests/UserInterfaceTest/LabelTestExtensions.cs
WalletWasabi/Blockchain/Keys/KeyManager.cs
WalletWasabi/Blockchain/TransactionProcessing/TransactionProcessor.cs
WalletWasabi/Blockchain/Transactions/TransactionFactory.cs
WalletWasabi/WabiSabi/Client/InternalDestinationProvider.cs
WalletWasabi/Wallets/Wallet.cs

This PR is the one of a sequence of PRs to add support for taproot. The idea is simplify the `KeyManager` in little steps in order to make the real implementation simpler and less risky by doing all these small changes before.
In this case we remove redundant calls to `ToFile()`. In tests we almost never want to persist the keys so, no need to call persistent methods.

[Taproot support] Separate persistent methods

---

WalletWasabi.Fluent/ViewModels/AddWallet/HardwareWallet/ConnectHardwareWalletViewModel.cs

The wallet icon was displayed instead of the generic HW wallet icon.

[TRIVIAL] Fix incorrect icon on HW wallet page

---

WalletWasabi.Fluent.Desktop/Program.cs

Fixes #8967
The end effect is that users won't see the mentioned exception in logs. No other user visible effect is expected.

Do not log `System.OperationCanceledException: The peer has been disconnected` on debug level

---

WalletWasabi.Fluent/Global.cs

This PR removes benchmark code because there is nothing to benchmark really as the constructor in question does not do any heavy lifting as can be seen in the logs:
```
2022-08-26 19:10:26.668 [1] INFO        Global.Dispose (73)     .ctor finished in 44 milliseconds.
```
Please review with [whitespace off](https://github.com/zkSNACKs/WalletWasabi/pull/9006/files?diff=split&w=1).

[trivial] Remove benchmark code

---

WalletWasabi.Fluent/ViewModels/AddWallet/Create/ConfirmRecoveryWordsViewModel.cs

Fixes #9008 
I made it using preprocessor directives, these directives were already used in the codebase (for example in Logger.cs)
I kept `|| System.Diagnostics.Debugger.IsAttached` if someone wants to use debugguer in release mode.

Enable "skip" for seed confirmation in debug mode

---

WalletWasabi.Tests/UnitTests/Tor/Socks5/Pool/TorHttpPoolTests.cs
WalletWasabi/Tor/Control/Messages/StreamStatus/StreamStatusFlag.cs
WalletWasabi/Tor/Socks5/Pool/Circuits/AnyOneOffCircuit.cs
WalletWasabi/Tor/Socks5/Pool/TorHttpPool.cs
WalletWasabi/Tor/Socks5/TorTcpConnectionFactory.cs
WalletWasabi/Tor/TorProcessManager.cs

This PR fixes uses of `AnyOneOffCircuit`. The bug was introduced in #8827.

Tor: Fix use of `AnyOneOffCircuit`

---

WalletWasabi/Tor/Socks5/Pool/TorHttpPool.cs
WalletWasabi/Tor/Socks5/TorTcpConnection.cs
WalletWasabi/Tor/TorMonitor.cs

This PR is meant to fix `SocketException`s that we have kept seeing:
```log
2022-07-29 09:13:02.042 [76] TRACE	TorHttpPool.SendAsync (199)	['PC#0008#GETZVMTKJG'] Could not get/read an HTTP response from Tor. Exception: WalletWasabi.Tor.Socks5.Exceptions.TorConnectionReadException: Could not read HTTP response.
---> System.IO.IOException: Unable to read data from the transport connection: An established connection was aborted by the software in your host machine..
---> System.Net.Sockets.SocketException (10053): An established connection was aborted by the software in your host machine.
at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.CreateException(SocketError error, Boolean forAsyncThrow)
```
before #8846 was merged.

Tor: Proper matching of `TorTcpConnection`s and Tor's streams (circuits)

---

WalletWasabi/Bases/PeriodicRunner.cs
WalletWasabi/BitcoinCore/Monitoring/RpcFeeProvider.cs

Fixes #9010 
It can only be caught in the PeriodicRunner because all exceptions are logged as error right after, which is what we want to avoid.
Maybe it would be better in the message to add that fee estimation will be asked to the HybridFeeProvider?
A better fix would be to test upfront if Bitcoin Core is ready to provide the estimation to avoid the exception to be raised in the first place.

[Trivial] LogInfo for NoEstimationException

---

WalletWasabi.Fluent/ViewModels/AddWallet/RecoverWalletViewModel.cs
WalletWasabi/Blockchain/Keys/KeyManager.cs
WalletWasabi/Blockchain/Keys/WalletGenerator.cs

The first commit removes the `SetNetwork` method because the network should never be changed and it is always known.
The second commit just move a block of properties.

Small changes in `KeyManager`

---

WalletWasabi.Fluent/ViewModels/Wallets/CoinJoinStateViewModel.cs
WalletWasabi.Fluent/Views/Wallets/MusicControlsView.axaml
WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
WalletWasabi/WabiSabi/Client/CoinJoinProgressEvents/RoundEnded.cs
WalletWasabi/WabiSabi/Client/CoinJoinProgressEvents/RoundEndedUserPressedPause.cs
WalletWasabi/WabiSabi/Client/CoinJoinTracker.cs

First of a several PRs to fix the messages of the MusicBox.
This one fixes #8769 
`if(!result.IsDefaultOrEmpty){...}` at the end of `CoinJoinClient` is to avoid having the message "Peparing CoinJoin" displayed for a small time if pause is pressed after the registration of the inputs.
Some "questions" on this:
1) Maybe `RoundEndedUserPressedPause` could have a better name? Even a proper folder (I will probably have to add another class heriting `RoundEnded` in another PR)? Or should I add a parameter to RoundEnd instead of creating an herited class?
2) Maybe I should add some logs? The obvious place is in `CoinJoinClient:236` but it's not really possible to know what caused the `OperationCanceledException` there.
3) `_stateMachine.Fire(Trigger.WalletStoppedCoinJoin);` will be ran twice …

[MusicBox] Don't display "Round finished..." when user presses pause during InputRegPhase

---

WalletWasabi.Fluent/Views/Settings/BitcoinTabSettingsView.axaml

What node you are connected to is sensitive info.
It should be part of _Discreet Mode_, for the paranoid user.

[VDG] Discreet Mode for BitcoinP2PEndPoint in Settings

---

WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModel.cs

The original goal of this ObserveOn call is to execute subscribed code in the UI thread. Please, notice how it's placed incorrectly.
This is dangerous. For example, this will use a different thread:
```csharp
Observable.FromEventPattern(Wallet, nameof(Wallet.NewFilterProcessed)
```
Consumers of this sequence could incorrectly assume that subscriptions will use the UI thread, it it won't in some cases (like the one above).
This PR fixes that.

[VDG] [Trivial] Use ObserveOn correctly

---

WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/PrivacyControlTileViewModel.cs
WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/PrivacyRing/PrivacyRingViewModel.cs
WalletWasabi.Fluent/Views/Wallets/Home/Tiles/PrivacyControlTileView.axaml
WalletWasabi.Fluent/Views/Wallets/Home/Tiles/PrivacyRing/PrivacyRingView.axaml

- Fixes [layout glitch](https://github.com/zkSNACKs/WalletWasabi/pull/8956#issuecomment-1220490343) caused by reuse of tile viewmodel
- Removes the Privacy Bar inside the Privacy ring (as per [this comment](https://github.com/zkSNACKs/WalletWasabi/pull/9032#pullrequestreview-1091562897))
- Centers the Labels inside the coin tile (as per [this comment](https://github.com/zkSNACKs/WalletWasabi/pull/8832#issuecomment-1229210693))

[VDG] Privacy Ring + Privacy Bar improvements

---

WalletWasabi/Wallets/Wallet.cs

The Wallet InitializingChanged static event is not used anymore, for initialization we have StateChanged event.

Remove unused Wallet.InitializingChanged static event

---

WalletWasabi.Tests/Helpers/AnalyzedTransaction/AnalyzedTransaction.cs
WalletWasabi.Tests/Helpers/AnalyzedTransaction/ForeignOutput.cs
WalletWasabi.Tests/Helpers/AnalyzedTransaction/WalletOutput.cs
WalletWasabi.Tests/UnitTests/BlockchainAnalysis/CoinJoinAnonscoreTests.cs
WalletWasabi/Blockchain/Analysis/BlockchainAnalyzer.cs
WalletWasabi/Blockchain/Analysis/CoinjoinAnalyzer.cs
WalletWasabi/Blockchain/TransactionOutputs/WalletVirtualInput.cs
WalletWasabi/Extensions/LinqExtensions.cs

This PR builds on top of https://github.com/zkSNACKs/WalletWasabi/pull/8933 (which was reverted in https://github.com/zkSNACKs/WalletWasabi/pull/8948) and addresses issues that were the cause of the revert.
* https://github.com/zkSNACKs/WalletWasabi/commit/23b026326314e1b382c6d7a9d44687dd265f1b40 reapplies https://github.com/zkSNACKs/WalletWasabi/pull/8933.
* https://github.com/zkSNACKs/WalletWasabi/commit/ad2388e91728871bb8ebb85d6622b11341dbe74d limits the the recursion depth in `ComputeInputSanction` which should make the wallet loading faster.
* https://github.com/zkSNACKs/WalletWasabi/commit/50175442599d768a02dad4295953b2bc6c9870a3 and https://github.com/zkSNACKs/WalletWasabi/commit/14edd2bea018dfad8a1bafb2b5fdb6efa73da416 should solve the problem with the negative anonymity.
* Other …

Anonymity computation again

---

WalletWasabi/Tor/Control/TorControlClient.cs
WalletWasabi/Tor/Control/TorControlReplyReader.cs
WalletWasabi/Tor/Http/Extensions/HttpResponseMessageExtensions.cs
WalletWasabi/Tor/Http/Helpers/HttpMessageHelper.cs
WalletWasabi/Tor/Http/IHttpClient.cs
WalletWasabi/Tor/Socks5/TorTcpConnectionFactory.cs
WalletWasabi/Tor/TorProcessManager.cs
WalletWasabi/WebClients/Wasabi/WasabiClient.cs

Follow-up to https://github.com/zkSNACKs/WalletWasabi/pull/8979#discussion_r951224641 so that it's hard to *not propagate* a cancellation token all the way down.
And unifies:
* `CancellationToken cancel` -> `CancellationToken cancellationToken`
* `CancellationToken token` -> `CancellationToken cancellationToken`
in Tor code. I find `CancellationToken cancel` weird because `cancel` is a verb and the thing is a noun (a token).

Remove `default` CTs from Tor code

---

WalletWasabi.Documentation/Guides/UpgradeTorDaemons.md
WalletWasabi/Microservices/Binaries/UpgradeTorBinaries.ps1

Fixes #9000
```powershell
cd WalletWasabi/Microservices/Binaries
.\UpgradeTorBinaries.ps1 -version "11.5.2"
.\UpgradeTorBinaries.ps1 -version "11.5.2" -skipDownloading -skipExtractingBrowserArchives -skipExtractingTorBinaries -skipReplacingTorBinaries 
```

`UpgradeTorBinaries`: Add support for GEOIP upgrade

---

WalletWasabi/Helpers/RuntimeParams.cs
WalletWasabi/Wallets/P2pBlockProvider.cs

With good bandwidth, waiting for P2P node timeout is currently what's consuming most of the blocks dl time as this waiting time is sync.
This PR reduces minimum depending network and tor status. In case few nodes are connected, timeout is more permissive to avoid node exhaustion. 
The values are conservative and were tested with good and bad bandwidth. Minimums could probably be further reduced and adjusting mecanism further improved.

[BLOCKS DL] Decrease min p2p dl timeout

---

WalletWasabi/WabiSabi/Client/CoinJoinClient.cs

for reference, current:
`2022-09-15 09:45:11.429 [22] DEBUG      CoinJoinClient.SelectCoinsForRound (803)        Selected the final selection candidate: 10 coins, 0.0001, 0.00006561, 0.0001, 0.00039094, 0.00016384, 0.00006561, 0.0002, 0.00005, 0.00177147, 0.00059049 bitcoins.`
also to match the rest of the logs

use BTC as unit in CoinJoinClient Log

---

WalletWasabi.Fluent/ViewModels/UIConstants.cs
WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/PrivacyRing/PrivacyBarItemViewModel.cs
WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/PrivacyRing/PrivacyBarViewModel.cs
WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/PrivacyRing/PrivacyRingItemViewModel.cs
WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/PrivacyRing/PrivacyRingViewModel.cs
WalletWasabi.Fluent/Views/Wallets/Home/Tiles/PrivacyBar/PrivacyBar.axaml
WalletWasabi.Fluent/Views/Wallets/Home/Tiles/PrivacyBar/PrivacyBar.axaml.cs
WalletWasabi.Fluent/Views/Wallets/Home/Tiles/PrivacyControlTileView.axaml
WalletWasabi.Fluent/Views/Wallets/Home/Tiles/PrivacyRing/PrivacyRingView.axaml

- Establishes a maximum coin count of 100 to render the Privacy Bar and Privacy Ring
- If this maximum is exceeded, renders one segment per pocket, instead of one segment per coin
- Prevents the UI from hanging when trying to render too many segments for wallets with a very high number of coins
- Code cleanup and best practices: removes inheritance of bar and ring item viewmodels from `WalletCoinViewModel` and uses composition instead
- Fixes #9055 
- Fixes #9056
- Fixes #9101

[VDG] Privacy bar and Privacy Ring render threshold

---

WalletWasabi/Tor/Socks5/Pool/TorHttpPool.cs

Trivial PR not to log `OperationCancelledException`. It adds no value and adds noise when reading logs

`TorHttpPool`: Do not log OperationCancelledException

---

WalletWasabi.WindowsInstaller/WalletWasabi.WindowsInstaller.wixproj

Currently building `WalletWasabi.WindowsInstaller` leads to crashing of VS2022. With the help of [this workaround](https://github.com/wixtoolset/issues/issues/6636#issuecomment-984886136), it seems it works. 
I'm not sure if it behaves as it used to work because it's not something I've been involved in a lot.

wix3: Bugfix to avoid VS2022 crash

---

WalletWasabi/Tor/Socks5/Pool/TorHttpPool.cs

Another PR that attempts to improve logging so that a stacktrace is shown only when there is really a problem.

Improve logging with regard to TTL expired.

---

WalletWasabi.Fluent/ApplicationStateManager.cs
WalletWasabi.Fluent/CrashReport/ViewModels/CrashReportWindowViewModel.cs
WalletWasabi.Fluent/Helpers/AppLifetimeHelper.cs
WalletWasabi.Fluent/Providers/IMainWindowService.cs
WalletWasabi.Fluent/ViewModels/ApplicationViewModel.cs
WalletWasabi.Fluent/ViewModels/Dialogs/ShuttingDownViewModel.cs
WalletWasabi.Fluent/ViewModels/SearchBar/Settings/RestartViewModel.cs
WalletWasabi.Fluent/ViewModels/Settings/SettingsPageViewModel.cs
WalletWasabi.Fluent/ViewModels/StatusIcon/StatusIconViewModel.cs

Fixes https://github.com/zkSNACKs/WalletWasabi/issues/9025, and when the user clicks on the update button from now the shutdown prevention will be taken into account.
The solution looks ugly, it is because the state machine cannot receive params ~~and because there are many Shutdown methods and hard to follow...~~
I am open to any suggestions that would make the solution easier to understand.

[VDG] Restart with shutdown prevention

---

WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModel.cs

Fixes #9136 
Just throttling the event to avoid firing every time.
I'm not sure this hasn't side effects, made the PR mainly to show exactly where the issue was coming from.
This works, but why are we listening to this event in the first place? 
Intuitively it feels enough just to listen to `WalletRelevantTransactionProcessed` and therefore to remove completely listening to this event there instead of throttling
_Nb: Codemaid changed using order_

throttle newfilterprocessed event

---

WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/PrivacyRing/PrivacyBarViewModel.cs
WalletWasabi.Fluent/Views/Wallets/Home/Tiles/PrivacyBar/PrivacyBar.axaml

currently when the user has an empty wallet, the PrivacyBar is not visible, but it is still clickable:
this PR fixes this (making invisible PrivacyBar not clickable) 
thanks @soosr for the help

[VDG] make PrivacyBar not clickable when wallet is empty

---

WalletWasabi.Backend/Controllers/BlockchainController.cs

I found this while messing on RegTest.
Swagger documentation couldn't be generated because of `BlockchainController.TryGetIndexer()`

[Backend] Fix swagger 

---

WalletWasabi/CoinJoin/Coordinator/Rounds/CoordinatorRound.cs

The bug:
```
2022-09-27 12:45:45.762 [510] ERROR	CoordinatorRound.ExecuteNextPhaseAsync (290)	System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
at System.Collections.Generic.List`1.Enumerator.MoveNext()
at System.Linq.Enumerable.WhereListIterator`1.MoveNext()
at WalletWasabi.CoinJoin.Coordinator.Rounds.CoordinatorRound.RemoveAliceIfCoinsAreNaughtyAsync()
at WalletWasabi.CoinJoin.Coordinator.Rounds.CoordinatorRound.MoveToConnectionConfirmationAsync()
at WalletWasabi.CoinJoin.Coordinator.Rounds.CoordinatorRound.ExecuteNextPhaseAsync(RoundPhase expectedPhase)
2022-09-27 12:45:45.762 [510] WARNING	CoordinatorRound.KickTimeout (398)	Round (55420): InputRegistration timeout failed.
```
Stupid mistake.
We removed `Alices` without the …

Use lock when we remove Alices, fix backend bug

---

WalletWasabi/CoinJoin/Coordinator/Rounds/CoordinatorRound.cs

This is not good. It results in a deadlock. `ExecuteNextPhaseAsync` also holds `RoundSynchronizerLock`

Revert "Use lock when we remove Alices, fix backend bug"

---

WalletWasabi/Exceptions/TransactionSizeException.cs

for logs current was ok, this is mainly a more user friendly message for the GUI

[trivial] improve TransactionSizeException message

---

WalletWasabi/WabiSabi/Client/WabiSabiHttpApiClient.cs

Originally `requestTimeoutCts` was created from `retryTimeout` if not null or `totalTimeout`. However `totalTimeout` is already in use through `combinedToken`. So it makes no sense to use it again.

Remove redundant timeot

---

WalletWasabi.Tests/UnitTests/Tor/TorSettingsTests.cs
WalletWasabi/Tor/TorSettings.cs

This PR was discussed yesterday with @nopara73.
Why this might make sense? The reason is that Tor selects only a few guard nodes (first Tor circuit hops) and it does that because there are attacks that might lead to de-anonymizing the Tor user. The problem with selecting guard nodes in the strict way as Tor does it seems to be that if the guard nodes are overloaded we are having hard time to send requests. 
The balance here is: We should get more performance but we don't know how much privacy we might lose (how feasible is to achieve that Tor attacks). Certainly, this should be considered to be a temporary workaround as we are in a dumpster fire situation.
* Ideally, we should measure it in the same way as we did it here: https://github.com/zkSNACKs/WalletWasabi/pull/9035#issuecomment-1266 …

Disable Tor's `UseEntryGuards` feature

---

WalletWasabi.Fluent/Views/Shell/TitleBarView.axaml

Since custom window chrome doesnt work properly on most linux distros yet (I probably should try to fix that in a later PR...), lets add a custom template for linux without the extra margins that is needed on Windows.
Before:
After:

[VDG] Dont add spacing on TitleBarView on linuxes 

---

WalletWasabi.Tests/UnitTests/Tor/TorSettingsTests.cs
WalletWasabi/Tor/TorSettings.cs

Reverts #9240
See:
* https://github.com/zkSNACKs/WalletWasabi/pull/9240#issuecomment-1268256231
* https://github.com/zkSNACKs/WalletWasabi/pull/9240#issuecomment-1268653693
* https://blog.torproject.org/improving-tors-anonymity-changing-guard-parameters/
btw: https://lists.torproject.org/pipermail/tor-relays/2022-June/020682.html - the number of guards was increased from 1 to 2 via a consensus parameter to help mitigate the DDoS attack by the Tor developers. We don't need to change anything here.

Revert "Disable Tor's `UseEntryGuards` feature"

---

WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs

Fixes #9062 
Alternate of #9241 but backend side.
This is an hack of an hack of an hack, extremely bad code.
The only change is to call first `TryMine` for `smallRound` then for `bigRound`
The idea is to force 2.0.0 users to prefer the `bigRound` (so not the right one) instead of forcing `smallRound` so that newer clients will de-prioritize this one (due to behavior introduced in #8521) and therefore select the good round first (small inputs round)
All this weird behavior must be changed and probably compatibility with 2.0.0 completely dropped, it makes most of our rounds to fail.
Also, I would still suggest to set  `"WW200CompatibleLoadBalancingInputSplit": 0.925,` in `WabiSabiConfig.json` instead of `0.85`. (to have more clients in the small inputs round)
@nopara73

When load balancing make 2.0.0 select the wrong round so newer versions prioritize the good one

---

WalletWasabi.Backend/wwwroot/index.html

On the docs the URLs have changed, so we have to update them on the website ASAP because they are running to a 404 page right now.

Updated docs links

---

WalletWasabi.Tests/UnitTests/Tor/TorSettingsTests.cs
WalletWasabi/Tor/TorSettings.cs

Additional question: Is the default value of [MaxClientCircuitsPending](https://github.com/torproject/tor/blob/01b0954b2335b8f1fe672c2d64666937876bb845/doc/man/tor.1.txt#L1309-L1312) (i.e. `32`) sufficient?

Tor: Increase `MaxCircuitDirtiness`

---

WalletWasabi.Fluent/Helpers/TransactionHelpers.cs

If the building does not succeed the minimum required amount is the payment and not zero.

[VDG] [Trivial] Set the payment amount instead of zero as default during prebuild

---

WalletWasabi.Fluent/Helpers/CoinPocketHelper.cs
WalletWasabi.Fluent/ViewModels/Wallets/Advanced/WalletCoins/WalletCoinsViewModel.cs
WalletWasabi.Fluent/ViewModels/Wallets/CoinJoinSettingsViewModel.cs
WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/PrivacyControlTileViewModel.cs
WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/PrivacyRing/PrivacyBarItemViewModel.cs
WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/PrivacyRing/PrivacyRingItemViewModel.cs
WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/WalletBalanceTileViewModel.cs
WalletWasabi.Fluent/ViewModels/Wallets/Send/PrivacyControlViewModel.cs
WalletWasabi/Wallets/Wallet.cs

`AnonScoreTarget` property was added to the `Wallet` class in #8754 so now it can be used instead of `KeyManager.AnonScoreTarget`.

Use Wallet.AnonScoreTarget instead of KeyManager.AnonScoreTarget

---

WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepOutputRegistrationTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepTransactionSigningTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Client/BobClientTests.cs
WalletWasabi/Bases/PeriodicRunner.cs
WalletWasabi/Helpers/EventAwaiter.cs
WalletWasabi/Helpers/EventsAwaiter.cs

I've tried 3 different options:
- TimeOut parameter on Fact
[Fact(TimeOut = 10000)]
https://github.com/xunit/xunit/issues/2222
"
It does not work unfortunately, it only seems like it. 
When timeout is reached it simply completes the task, reporting the failure. 
But the code is running on the background until it finishes, or until all tests in that assembly are finished and the process is killed.
" 
- ComplatesIn
Note: Task.WaitAll doesn't terminate all task just return a flag every each task is in complete in allotted time. 
It doesn't break the while loop if every each task is complete in time but the phase update is not happened.
- CancellationToken
Note: If you would like to cancel parallel tasks is the perfect solution.
This idea comes from @molnard.
In that case the cancellation …

Implement CancellationToken in StepTransactionSigningTests,StepOutputRegistrationTests and BobClientTests

---

WalletWasabi.Tests/UnitTests/BitcoinCore/P2pBasedTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Client/CredentialDependencyTests.cs

Many test runs seem to fail because of these two timeouts.

[CI] Increase timeouts

---

WalletWasabi/WabiSabi/Client/KeyChain.cs
WalletWasabi/Wallets/Wallet.cs

Improves https://github.com/zkSNACKs/WalletWasabi/issues/9339

Store MasterKey instead of Decrypt every time
