HiddenWallet.ChaumianTumbler/TumblerHub.cs
HiddenWallet.ChaumianTumbler/TumblerPhaseBroadcaster.cs

Made connected client count available through TumblerPhaseBroadcaster for future use.
Checked and this works with javascript and the C# client. Connections are added to count and disconnects (closed tab, closed C# client) are removed.

Added connected client count

---

.gitignore

This created when you run npm install for the first time. Not needed in github.

Added package-lock.json to gitignore

---

HiddenWallet.Daemon/Controllers/WalletController.cs
HiddenWallet.Daemon/Models/TumbleRequest.cs
HiddenWallet.Daemon/Wrappers/WalletWrapper.cs
HiddenWallet.FullSpvWallet/ChaumianCoinJoin/CoinJoinService.cs
HiddenWallet.Gui/app/html/wallet-content.html
HiddenWallet.Gui/app/js/wallet-phase.ts
HiddenWallet/ChaumianCoinJoin/Models/StatusResponse.cs

How it links together shown below. Known issue in to do list at end...
GETTING THE STATUS AND TUMBLER DETAILS:
WalletController.TumblerserverAsync
calls
WalletWrapper.GetTumblerStatusAsync
calls
[_walletJob].CoinJoinService.GetStatusAsync
calls
TumblerClient.GetStatusAsync
NOTES: 
Using fully qualified ChaumianCoinJoin.Models.StatusResponse in WalletController and WalletWrapper doesn't feel right.
Unqualified StatusResponse in those classes refers to the Daemon's class of the same name - so I fuly qulified it for the CCJ one.
I guess we could rename the CCJ StatusResponse class if this is an issue.
CoinJoinService.GetStatusAsync - not sure if this needs a CancellationToken param passed in. Currently I'm using default.
SUBMITTING THE INPUTS:
WalletController.TumbleAsync
calls …

GUi to server linking for CCJ

---

WalletWasabi/Logging/Logger.cs

That's how a log entry looks now:
```
2018-04-13 04:58:45Z INFO IndexDownloader: Downloaded filters for blocks from 101 to 102.
```

Uses class name instead of fullyqualified name

---

WalletWasabi.Tests/NodeBuilding/CoreNode.cs
WalletWasabi.Tests/RegTests.cs
WalletWasabi.Tests/SmartModelTests.cs
WalletWasabi/Converters/FunnyBoolConverter.cs
WalletWasabi/Models/SmartCoin.cs
WalletWasabi/Services/WalletService.cs

This PR aims to fix this PR: https://github.com/zkSNACKs/WalletWasabi/pull/152
There was 2 problems.  
Originally the coin list was updated like this:
```
iterate tx
if came to our keys
if already have the coin
if mempool
continue
else
update height
continue
else 
add coin
```
The new algo to update the coinlist is this:
```
iterate tx
if already have the coin
if NOT mempool
update height
if double spend
if mempool
if all double spent coins are mempool and RBF
remove double spent coins (if other coin spends it, remove that too and so on) // will add later if they came to our keys
else 
return
else // new confirmation always enjoys priority
remove double spent coins recursively (if other coin spends it, remove that too and so on)// will add later if they came to our keys
iterate tx
if came …
```

Test wallet after reorgs - Fixed

---

WalletWasabi.Tests/NodeBuilding/CoreNode.cs
WalletWasabi.Tests/RegTests.cs
WalletWasabi/Services/WalletService.cs

@nopara73 could you please take a look at this test? I'm not sure if i am understanding well here but i think after we have a fork, the wallet's coins in the now orphan chain should not be in the `Wallet.Coins` collection.
This test does the following:
1. Creates a chain with 102 blocks.  In the block 102 we send 1 BTC to our wallet and so, it is listed in the `Wallet.Coins` collection 
```
98 ---> 99 ---> 100 ---> 101 ---> 102 (coin)
```
2. Creates a larger (and more difficult) chain of 10 blocks from block 100, this is a fork.
```
98 ---> 99  ---> 100 ---> 101 ---> 102 (coin)    // this is orphan
\
+ ---> 101 ---> 102 ---> 103 ---> .... ---> 110
```
After this, the wallet still contains the coin in the orphan chain. Probably that coin should go back to the mempool (i'm not sure) but the …

Test wallet after reorgs (for review)

---

WalletWasabi/Logging/Logger.cs

Logs register local time instead of utc, this removes the Z sufix (I tried to push it directly but I have no permissions)

Use localtime for logs

---

WalletWasabi.Tests/RegTests.cs

This fixes the #169 issue. The crypto is okay but the test was doing it wrong. The client (in this case, the test) has to blind the message using the pubkey corresponding to the server privkey otherwise it wll fail at the end of the process. It used to fail randomly because from time to time the blinded message generated by the client was out of the server privkey finite field (blindeddata > server_priv_key_module)

Fix chaumian coinjoin controller test

---

README.md

This PR shows one possible alternative fo displaying separated badges for Linux ans OSX (issue https://github.com/zkSNACKs/WalletWasabi/issues/183). This is how it looks like:

Shows alternative for different badgets

---

WalletWasabi.Tests/RegTests.cs

This PR is part of #144 to increase code coverage of WalletService.BuildTransactionAsync
The only code coverage excluded currently is the exception path when checking the HttpStatusCode when connecting to the tor client, and the following check:
`			TransactionPolicyError[] checkResults = builder.Check(tx, fee);
if (checkResults.Length > 0)
{
throw new InvalidTxException(tx, checkResults);
}`
SelectCoinsToSpend (invoked like 610) seems to block being able to assert InvalidTxException is thrown as it already checks whether enough fees are present, leading to a InsufficientBalanceException getting in the way.
Tests that invoke BuildTransactionAsync have had a DisplayName added to isolate tests if needed.
To run just the test that invoke BuildTransactionAsync, modify line 19 of coverage.sh …

Increase code coverage of WalletService.BuildTransactionAsync for #144

---

WalletWasabi.Backend/Controllers/ChaumianCoinJoinController.cs
WalletWasabi/Models/ChaumianCoinJoin/Alice.cs
WalletWasabi/Services/CcjClient.cs
WalletWasabi/Services/WalletService.cs

This PR is for preventing the creation of new Money instances when we sum collections of Money.
Money class overload arithmetical operations (+, -, *, /, etc) such that they returns a new Money instance as result. At the same time, the Money class constructors performs some minimal validations so, if we have a collection `c` with 1000 Money instances and we sum them with `c.Sum()` we are creating (and destroying) 1000 new Money instances just for storing the intermediate results. This is could be important if we work with many collections of money. 
For that reason NBitcoin provides its own `Money Sum(IEnumerable<Money>)` method which sums the satoshis and creates only one Money instance with the result.

Minor improvemnet in multiples Money additions

---

WalletWasabi.Backend/Controllers/ChaumianCoinJoinController.cs
WalletWasabi/Backend/Models/FilterModel.cs
WalletWasabi/Bases/ByteArraySerializableBase.cs
WalletWasabi/Bases/OctetSerializableBase.cs
WalletWasabi/Extensions/StreamExtensions.cs
WalletWasabi/Extensions/StringExtensions.cs
WalletWasabi/Helpers/HttpMessageHelper.cs
WalletWasabi/Http/Models/HeaderSection.cs
WalletWasabi/KeyManagement/KeyManager.cs
WalletWasabi/Models/ChaumianCoinJoin/CcjClientState.cs
WalletWasabi/Models/ChaumianCoinJoin/CcjRound.cs
WalletWasabi/Models/ChaumianCoinJoin/CcjRoundPhase.cs
WalletWasabi/Models/Height.cs
WalletWasabi/Services/CcjClient.cs
WalletWasabi/Services/CcjCoordinator.cs
WalletWasabi/Services/IndexBuilderService.cs
WalletWasabi/Services/IndexDownloader.cs
WalletWasabi/TorSocks5/Models/Fields/ByteArrayFields/AddrField.cs
WalletWasabi/TorSocks5/TorSocks5Client.cs
WalletWasabi/WebClients/ChaumianCoinJoin/AliceClient.cs
WalletWasabi/WebClients/ChaumianCoinJoin/BobClient.cs
WalletWasabi/WebClients/ChaumianCoinJoin/SatoshiClient.cs
WalletWasabi/WebClients/ExchangeRateProviders.cs

This PR removes many lines of code containing redundant `else` statements. Also, reduces the level of indentation in those methods that start with an `if` statement. By last, it simplifies the a bit teh Satoshi, Alice and Bob clients in the way they check errors and create exception messages.

Remove redundant conditional statements

---

WalletWasabi.Tests/RegTests.cs
WalletWasabi/Helpers/HttpMessageHelper.cs
WalletWasabi/Services/CcjCoordinator.cs
WalletWasabi/Services/MemPoolBehavior.cs
WalletWasabi/Services/UtxoReferee.cs
WalletWasabi/Services/WalletService.cs

This PR changes replaces calls to `IEnumerable.Count()` method by `List<>.Count` property or `Array.Length` property depending on the concrete type. There are also a few other minor changes.

Use Collection Count property when possible

---

WalletWasabi/Helpers/HttpMessageHelper.cs

I've didn't changed the commit included in this PR because i still think it is the correct thing to do (in case of disagreement we can skip it)
The point is that the method `ReadBytesTillLengthAsync` receives a `CancellationToken` that is never used in the method's body. So, there are two alternatives:
* We can use it, as we do in all the rest of the methods belonging to the same class (this PR) or,
* We can remove the CancellationToken from the method's parameter list.
Removing this parameter form the parameter list moves the problem to the calling method `GetContentTillLengthAsync` and so on, I mean, it requires a short chain of changes.
@nopara73 please take a look at this and let me know.
The last alternative requires we remove the cancelation token in all the chain of methods that

Use unused CancelationToken

---

WalletWasabi/Logging/Logger.cs

This PR change the way the `_logerFailed` static field is initialized. Given static fields are initialized to their default value the first time the class is referenced, the previous initialization was using the field's initial value as base value to initialize it.

Change static field initialization

---

WalletWasabi/Helpers/NBitcoinHelpers.cs
WalletWasabi/Models/ChaumianCoinJoin/CcjClientState.cs

This PR fixes situations where `IEnumeration.OrderBy` calls are chained because the last one overrides all the previous ones. That's why `IOrderedEnumerable` enumerables provide the `IOrderedEnumerable.ThenBy' and `IOrderedEnumerable.ThenByDescending` extensions.

Fix meaningless OrderBy chain

---

WalletWasabi/Services/CcjClient.cs

Trivial change. Given roundIds are `long` we use that data type instead of casting them to `int`.

Fix possible invalid cast exception

---

WalletWasabi/Extensions/NBitcoinExtensions.cs
WalletWasabi/Models/ChaumianCoinJoin/CcjRound.cs
WalletWasabi/Services/CcjClient.cs

This PR introduces a new `NBitcoin.Money` extension method called `Percentage` to simplify the calculation of fees and, at the same time, improve the code readability such that the following expression:
```c#
var onePercent = Money.Coins(actualDenomination.ToDecimal(MoneyUnit.BTC) * 0.01m);
```
can be rewritten as:
```c#
var onePercent = actualDenomination.Percentange(1m);
```

Simplify fee calculations

---

WalletWasabi.Backend/Controllers/ChaumianCoinJoinController.cs
WalletWasabi.Tests/RegTests.cs
WalletWasabi/Services/CcjCoordinator.cs
WalletWasabi/Services/WalletService.cs

Done for performance as no duplicate items are guaranteed due to the collection types, so the entire list does not need to be enumerated to find duplicates.
For #275

Using FirstOrDefault in place of SingleOrDefault on unique collections for performance

---

WalletWasabi/Services/IndexDownloader.cs

Index file can be corrupted after an unexpected exit. When that
happened, the wallet client couldn't open anymore.

Recover broken index file

---

.coverage.sh
.gitignore
WalletWasabi.Tests/WalletWasabi.Tests.csproj
appveyor.yml

Added Coverlet dep.
Added back a coverage script.
Set CopyLocalLockFileAssemblies to true.
Updated .gitignore
Note: use the shell script as the output file name/type needs to be changed from  `coverage.json` to `lcov.info` for the Visual Studio Code extension Coverage Gutters to work.
Ref: #316

Added Coverlet

---

WalletWasabi.Gui/Controls/StatusBar.xaml
WalletWasabi.Gui/Converters/StatusColorConvertor.cs

Using `ConverterParameter` to get value of item being checked, as cannot rely on type for filters, blocks, or peers.
`FiltersLeft` is being cast to a string to handle "--".
Ref: #371

Update status text color for filters, blocks, peers

---

WalletWasabi.Gui/Controls/WalletExplorer/CoinListView.xaml
WalletWasabi.Gui/Controls/WalletExplorer/HistoryTabView.xaml
WalletWasabi.Gui/Controls/WalletExplorer/SendTabView.xaml

This PR contains the following small improvements:
* Change the columns order for Transaction Id and Label
* Resize the columns width in Send and History tabs
* Align the Build Transaction panel to the right
* Increase the Amount textbox width
* Add header to the coin selection list

WIP - Small UI improvements

---

WalletWasabi.Gui/Controls/StatusBar.xaml
WalletWasabi.Gui/Converters/StatusColorConvertor.cs

Entire text is yellow if status condition is met.
Added todo as StringFormat is not yet supported in Avalonia, but once it is we can use it to use just one TextBlock and have the binded text and static text.
Ref: #371

Entire text is yellow if status condition is met

---

WalletWasabi.Gui/Controls/WalletExplorer/CoinListView.xaml
WalletWasabi.Gui/Controls/WalletExplorer/CoinViewModel.cs

This PR changes the 'Address copied to clipboard' message by 'Transaction ID copied to clipboard' message.
Add `CoinJoin in progress` info to the coin list tooltip.

fixes 'copied to clipboard' message

---

WalletWasabi.Gui/Controls/WalletExplorer/HistoryTabViewModel.cs

Tested this locally and it works.
The space and comma need to only be present if `found.label` is not empty.

[WIP] Fix leading comma bug

---

WalletWasabi.Gui/Behaviors/FocusOnVisibleBehavior.cs
WalletWasabi.Gui/Controls/WalletExplorer/ReceiveTabView.xaml
WalletWasabi.Gui/ViewModels/WasabiDocumentTabViewModel.cs

This PR is for issue #458. The Label textbox gets the focus when the Receive tab is clicked . It could be a bit overengineered so, it could be a good idea to have a review by @danwalmsley

Set focus on Label when tab is visible

---

WalletWasabi.Gui/Controls/WalletExplorer/WalletViewModel.cs

Event listener now listens for new processed blocks and spent or confirmed coins.
Fixes: #499

Fix incorrect balance

---

README.md

no need for submodule update --init if you clone with --recursive.
done build will also do a restore for you, so remove explicit restore command.
btw worth noting, that dotnet run = compile and run.
app would load much faster if you run dotnet WalletWasabi.Gui.dll from the bin directory.

simplify clone and build instructions.

---

WalletWasabi.Gui/Tabs/WalletManager/LoadWalletView.xaml

The LoadWallet page looked different than the GenerateWallet and RecoveryWallet pages. This PR changes that.

Make Load page look like the rest

---

WalletWasabi.Gui/Config.cs
WalletWasabi.Gui/Global.cs

Initially I neglected to modify LoadOrCreateDefault method on Config to also copy the parameters, so my config file kept getting mysteriously overwritten.
Maybe this method should be moved outside the IConfig interface?  Because it's essentially the same method for any IConfig implementation.  Anyway for this commit I moved the copy stuff to OverwriteWith, but would be nice to get rid of it completely somehow.

Add client config entries for specifying tor end point ip address and port

---

WalletWasabi.Gui/Styles/Styles.xaml

Reverts zkSNACKs/WalletWasabi#607
Because all the buttons are changed.

Revert "Hightlight tab's close buttom"

---

WalletWasabi/Helpers/IoHelpers.cs
WalletWasabi/KeyManagement/KeyManager.cs

Prevent broken wallet files after unexpected problems. Uses the _Safe file write_ technique described by Jon Skeet's answer in StackOverflow https://stackoverflow.com/questions/7957544/how-to-ensure-that-data-doesnt-get-corrupted-when-saving-to-file
**Note:**  the IoHelpers static class contains more methods than what are necessary for this PR but the idea is using them for fixing the broken filters issue (working on that one right now)

Safe wallet write

---

WalletWasabi/Helpers/IoHelpers.cs
WalletWasabi/Services/IndexDownloader.cs

This PR fixes the corrupted index file problem that happens when the wallet is closed unexpectedly while downloading the missing indexes. It is easy to reproduce simply doing CTRL+C in the console.

Fix broken index file

---

WalletWasabi.Tests/RegTests.cs
WalletWasabi/Helpers/Constants.cs
WalletWasabi/WalletWasabi.csproj

This PR updates the NBitcoin version which contains the [change](https://github.com/MetacoSA/NBitcoin/pull/510) for making sure DER-encoded digital ECDSA signatures are at most 71 bytes length (before that change they were able to be 72 bytes length).
we already discussed about this in the issue https://github.com/zkSNACKs/WalletWasabi/issues/222#issuecomment-413549499. Please review it.

Update NBitcoin version

---

WalletWasabi.Gui/Global.cs

This PR dequeue coins registered for coinjoin when the Wallet Wasabi process receives a signal indicating it will be killed.

Dequeue coins when process is killed

---

WalletWasabi/Services/CcjClient.cs
WalletWasabi/Services/WalletService.cs

This PR implements small changes to reduce the required time to load a wallet. In my machine, and using my personal wallet, it reduced the loading time from 25 seconds to 14 seconds (still not good enough IMO).   
@nopara73 please review the double spending prevention part.

Load wallet performance improvement

---

WalletWasabi.Gui/WalletWasabi.Gui.csproj

Adds runtime identifiers, (win7-x64 needs to be used for windows)
Adds PreserveCompilationContext = true in csproj.
This means that MEF when it loads all the composition components knows which DLLs were present at compilation and will only evaluate dlls that were available at compilation. Without this it wont evaluate any dlls, hence the exception.

Allow published app to correctly load components

---

WalletWasabi/KeyManagement/KeyManager.cs
WalletWasabi/Services/WalletService.cs

This PR improves the transaction processing time and it is specially important for those user with wallets containing hundred of addresses.
I've tested it with a 500 keys wallet and the loading time went from 41 seconds to 28 seconds.

Improve HdPubkeys lookup mechanism

---

WalletWasabi/Extensions/NBitcoinExtensions.cs
WalletWasabi/Services/WalletService.cs

This PR is for finxing a problem with the identification, and filtering, of segwit transactions.

Assumes segwit tx when txin.ScriptSig is empty

---

Directory.Build.targets

This fixes the seemingly random failure of paste operations.
The cause was two-fold as stated here: 
1) strings being gced by objective c runtime before .net code could access it.
2) strings being treated as ansi strings when they are really utf8.
See https://github.com/AvaloniaUI/Avalonia/pull/2082/files for fix.

update avalonia with text encoding fixes affecting clipboard.

---

WalletWasabi.Gui/Controls/WalletExplorer/SendTabView.xaml
WalletWasabi.Gui/Controls/WalletExplorer/SendTabViewModel.cs

This PR closes #806. When you press the `Max` button it disable the `Label` textbox. Should it clear the `Label` content if it contains text?

Disable Label textbox when spend whole coins

---

WalletWasabi.Gui/Tabs/WalletManager/GenerateWalletView.xaml
WalletWasabi.Gui/Tabs/WalletManager/RecoverWalletView.xaml

Closes #849.
Allow to paste clipboard content on passwords controls in the same way that is implemented in other places.

Allow paste passwords

---

WalletWasabi.Gui/Tabs/SettingsViewModel.cs
WalletWasabi/TorSocks5/TorProcessManager.cs
WalletWasabi/TorSocks5/TorSocks5Client.cs

Closes #853
Closes #852
It allows to connect to Tor Socks proxy over IPv4 and IPv6. It also can start the Tor client bound to given IP address. I've tested it with IPv4 addresses 127.0.0.1 and 192.168.100.5 and IPv6 [::1]
Note: the Setting window allowed us to specify an IP address or a host name but currently specifying a host name doesn't work (it fails when Wasabi starts) and the user have to edit the config file manually; otherwise he cannot launch the wallet again. Should we allow host names too or only IP addresses?

Support Tor socks proxy over IPv6

---

WalletWasabi.Gui/Behaviors/PasteAddressOnClickBehavior.cs

Fixes a NRE
<details><summary>Stack trace:</summary>
```
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
at WalletWasabi.Gui.Behaviors.PasteAddressOnClickBehavior.IsThereABitcoinAddressOnTheClipboardAsync() in /home/lontivero/GitHub/WalletWasabi/WalletWasabi.Gui/Behaviors/PasteAddressOnClickBehavior.cs:line 68
at WalletWasabi.Gui.Behaviors.PasteAddressOnClickBehavior.<OnAttached>b__9_1(PointerEventArgs pointerEnter) in /home/lontivero/GitHub/WalletWasabi/WalletWasabi.Gui/Behaviors/PasteAddressOnClickBehavior.cs:line 127
at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in D:\a\1\s\src\Avalonia.Base\Threading\JobRunner.cs:line 40
at Avalonia.Gtk3.Gtk3Platform.<>c__DisplayClass29_0.<Signal>b__0() in …
```

Fix NRE when clipboard is empty

---

WalletWasabi/Extensions/LinqExtensions.cs
WalletWasabi/Models/ChaumianCoinJoin/CcjClientState.cs

@lontivero @molnard I refactored how we select coins for mixing. Can one of you review it?

Implement better mix coin selection

---

WalletWasabi.Gui/Global.cs

This PR closes #748. 
When we kill internet Wasabi cannot connect to peers and that's why  after one minute it tries to discover new peers aggressively, that process uses a lot of cpu because the not IO operations happening when no internet is available.
AddressManager works as a nodes address' cache that make unnecessary to rediscover peers again and again. The discovery process is only needed the first time we run Wasabi after a clean installation. 
For this reason, if we can load the peers addresses from the file (cache) we can disable the discovery mechanism.

Disable peer discovery if cache exists

---

WalletWasabi.Gui/ViewModels/AddressViewModel.cs

Because it seems that a higher level of redundancy makes it harder
for some devices/apps to decode it. Anyway, gioven this QR is displayed
in the screen and not printed, we don't need such a high redundancy.
Tested manually with 20 addresses.
Closes #869

Reduce error correction level

---

WalletWasabi.Backend/Controllers/ChaumianCoinJoinController.cs
WalletWasabi.Tests/RegTests.cs

This PR is for preventing DoS attacks by reusing/posting coins with invalid proof, because the pubkey extraction from compact signature and the signature verification is expensive. This makes this attacks more expensive.

Ban coins if proof verifycation fails

---

WalletWasabi.Backend/Controllers/ChaumianCoinJoinController.cs
WalletWasabi.Tests/RegTests.cs

Removes code that could be use by attackers to make the coordinator to ban somebody else's coins.

Remove anti-dos mechanism

---

WalletWasabi.Gui/Controls/WalletExplorer/CoinListView.xaml
WalletWasabi.Gui/Controls/WalletExplorer/CoinViewModel.cs
WalletWasabi.Gui/Controls/WalletExplorer/ReceiveTabView.xaml
WalletWasabi.Gui/ViewModels/AddressViewModel.cs
WalletWasabi/Models/SmartCoin.cs
WalletWasabi/Services/WalletService.cs

This PR is for adding more info in the receive address details where previously we only displayed the QR code. This is useful IMO because it can help users to understand the derivation scheme and prevent misunderstanding and let them find an address in tools such as the [Ian Coleman bip39 tool]( https://iancoleman.io/bip39/).

Display Public key and Key path

---

WalletWasabi.Gui/MainWindow.xaml

Resolves https://github.com/zkSNACKs/WalletWasabi/issues/1146
I changed the `WasabiLogo.png` to `WasabiLogo256.png`, because I saw that's how @danwalmsley's AvalonStudio is doing. This fixed #1146. @danwalmsley could I get an ACK to merge?

Fix logo on Linux

---

WalletWasabi.Packager/Program.cs
WalletWasabi.Packager/Tools.cs

https://natemcmaster.com/blog/2017/12/21/netcore-primitives/
Problem is that WalletWasabi.Gui.deps.jsons are different on every computer.
https://stackoverflow.com/questions/54538068/dotnet-core-what-are-the-sha512-and-shapath-properties-used-for-in-deps-json

Emptied SHA512 tags in WalletWasabi.Gui.deps.json (deterministic build)

---

WalletWasabi/Helpers/IoHelpers.cs

When opening files in Linux Wasabi was waiting for forked process to finish while in Windows and OSX that was different. This PR changes that. 
Closes #1206

do not wait for exit  when opening log file

---

WalletWasabi.Backend/Config.cs
WalletWasabi.Backend/Program.cs
WalletWasabi.Documentation/BackendDeployment.md
WalletWasabi.Tests/XunitConfiguration/RegTestFixture.cs

Since `rpcuser` and `rpcpassword` are deprecated we should use the cookie file instead.
The backend `Config.json` file should look like the one below:
```json
﻿{
"Network": "RegTest",
"BitcoinRpcConnectionString": "cookiefile=/home/<username>/.bitcoin/.cookie"
}
``` 
**Note**: NBitcoin allows us to use `rpcuser` and `rpcpassword` here as follow:
```json
﻿{
"Network": "RegTest",
"BitcoinRpcConnectionString": "user:password"
}
```

Uses RPC cookie file instead of rpcuser:rpcpassword

---

WalletWasabi.Backend/Program.cs

closes #1217 
If this is not fast enough we should consider to save the coinjoin transaction instead of the txid.

Make RPC calls in batch

---

WalletWasabi/Services/CcjClient.cs

Currently we are not providing good enough feedback to the users when Wasabi dequeue coins for reasons other than banned. This PR will address the issue https://github.com/zkSNACKs/WalletWasabi/issues/1244 but it would be good to know how to give visual feedback (if https://github.com/zkSNACKs/WalletWasabi/pull/1260 is merged I will use it).

Small refactoring for centralizing feedback

---

WalletWasabi/Services/MemPoolBehavior.cs

When Wasabi receives an `inventory` message without transactions or with transactions that it already has in the mempool, it responde with a `getdata` message with 0 items. We can see it in the traffic dump  in issue https://github.com/zkSNACKs/WalletWasabi/issues/1273.
This is not a big problem at all because it doesn't use any significant bandwidth but it something to fix anyway.

Do not send getdata messages with 0 items

---

WalletWasabi/Models/ChaumianCoinJoin/CcjRound.cs
WalletWasabi/Services/CcjCoordinator.cs

Closes https://github.com/zkSNACKs/WalletWasabi/issues/1155
@lontivero this attempts to resolve your "Coinjoin Transactions Network Fee" with your "Alternative 2."
The idea is: depending on the number of unconfirmed coinjoins I halven the fee target every time a new round is created.

Optimize confirmation times

---

WalletWasabi.Gui/ViewModels/StatusBarViewModel.cs

There was a bug in the ViewModel of the status bar. Local variable was used inside the Subscribe() function. [Data were taken from outside of the Observable stream.](https://medium.com/@paynoattn/3-common-mistakes-i-see-people-use-in-rx-and-the-observable-pattern-ba55fee3d031). It is a bad practice.

Fix: peer count zero on RegTest

---

WalletWasabi.Gui/CommandLine/Daemon.cs
WalletWasabi.Gui/Controls/WalletExplorer/CoinJoinTabViewModel.cs
WalletWasabi.Gui/Controls/WalletExplorer/SendTabViewModel.cs
WalletWasabi.Gui/Dialogs/CannotCloseDialogViewModel.cs
WalletWasabi.Gui/Global.cs
WalletWasabi.Tests/RegTests.cs
WalletWasabi/Services/CcjClient.cs

This PR is for registering the reason why a coin is dequeued. Currently this only write an entry in the log file but once the notifications are ready we will be able to give a UI feedback to the user.
Closes #1244

Provide reason for remove coins

---

WalletWasabi.Community/Dojo.md

Matt and Marty have been educating the listeners of the Tales from the Crypt podcast about the importance of privacy and the nuances of Wasabi. Not only do they break down the best practices of this complex software to be accessible for regular users, but they also provide compelling arguments for privacy focused Bitcoin tools in general.
They have repeatedly proven their honor, and have well earned their part in the Dojo.

Promoting Matt Odell and Marty Bent

---

WalletWasabi/Extensions/ProcessExtensions.cs
WalletWasabi/Helpers/ProcessHelpers.cs
WalletWasabi/Hwi/HwiProcessManager.cs

Closes: https://github.com/zkSNACKs/WalletWasabi/issues/1363
1. Checkout Tag 1.1.4.
2. Delete .walletwasabi folder (backup your wallets before doing that!).
3. Dotnet run.
4. Wait for the UI hangs while searching for Hardware Wallets.
For some reason on Mac we get a deadlock randomly with this line:
https://github.com/zkSNACKs/WalletWasabi/blob/0fb49c8b6145acf1bd2402b765ed1edcd1e8a895/WalletWasabi/Helpers/ProcessHelpers.cs#L18
According to my experience it is happening more often if the Filters are being downloaded meanwhile so there is another operation which is refreshing the UI and put some tasks to UI dispatcher. That is the reason why it is not likely to happen after the first run. After some investigation I have found that this is not an unknown issue. …

Mac deadlock fix.

---

WalletWasabi.Gui/CommandLine/CommandInterpreter.cs
WalletWasabi.Gui/Global.cs
WalletWasabi.Gui/Program.cs
WalletWasabi/Mono/CommandSet.cs
WalletWasabi/Services/WalletService.cs

**Disclaimer:** This PR is for validating the idea and the code was not tested enough.
Related to: #763
-----
This allow us to specify `--datadir` for all the options (gui, deamon, password finder). For example, to lunch the Wasabi GUI client and use the `/home/007/topsecret` folder we use: 
```
$ wassabee --datadir:/home/007/topsecret
```
To lunch the daemon:
```
$ wassabee mix --datadir:/home/007/topsecret --wallet:chaos --keepalive --mixall
```
And so on.

Allow to specify --datadir

---

WalletWasabi.Tests/NodeBuilding/NodeBuilder.cs
WalletWasabi/WalletWasabi.csproj

Bitcoin Core 18 is out: https://bitcoincore.org/en/releases/0.18.0/
The first blocker issue I encountered is that they removed the `generate` RPC (there may be more.) https://github.com/bitcoin/bitcoin/pull/15492
> generate is deprecated and will be fully removed in a subsequent major version. This RPC is only used for testing, but its implementation reached across multiple subsystems (wallet and mining), so it is being deprecated to simplify the wallet-node interface. Projects that are using generate for testing purposes should transition to using the generatetoaddress RPC, which does not require or use the wallet component. Calling generatetoaddress with an address returned by the getnewaddress RPC gives the same functionality as the old generate RPC. To continue using generate in this …

Update to Bitcoin 18

---

WalletWasabi.Gui/Tabs/WalletManager/RecoverWalletView.xaml
WalletWasabi.Gui/Tabs/WalletManager/RecoverWalletViewModel.cs
WalletWasabi.Tests/KeyManagementTests.cs
WalletWasabi/JsonConverters/KeyPathJsonConverter.cs
WalletWasabi/KeyManagement/HdPubKey.cs
WalletWasabi/KeyManagement/KeyManager.cs

This PR adds two new "advanced options" to the tab "Recover Wallet":
* "**Account Key Path**": Useful if an existing BIP39 wallet should be imported that was created with a different software and used a different derivation path.
* "**Number of keys to generate**": Determines how many keys will be generated/derived when the wallet is created. Useful if a wallet should be imported/restored that has been used a lot already.
I plan to add additional PRs with more advanced options in the "Recover Wallet" tab to support different derivation methods used by other wallet software. I hope that's in the general interest of the project since people might want to import their existing wallet rather than create a new one and send funds to it.

Add advanced options on Recover Wallet tab

---

WalletWasabi/Services/WasabiSynchronizer.cs
WalletWasabi/TorSocks5/TorHttpClient.cs

When I am on RegTest and my local Backend is not running, my Wasabi still indicating that my Backend is connected. It is better to set the connected state only if we got the first synchronization packet. Despite of the solution is trivial for some reason it was not fixed until now. This fact leads me to think there is hidden complexity behind this.

Fix connected status when not.

---

WalletWasabi.Gui/Global.cs

When something wrong happens while processing a wallet (inside `WalletService.InitializeAsync`) the exception bubbles and disposes the `CancelWalletServiceInitialization` so, we ends with an unprocessed `WalletService` but, given it is not `null` Wasabi displays "There is an already opened wallet".
In other words: when there is an exception while processing the wallet, it doesn't display the correct exception message but the misleading "There is an already opened wallet" error instead.
Related #1413

Do not cancel disposed TokenSource

---

WalletWasabi.Gui/Controls/WalletExplorer/SendTabViewModel.cs
WalletWasabi.Gui/Controls/WalletExplorer/TransactionBroadcasterViewModel.cs
WalletWasabi.Gui/Tabs/WalletManager/LoadWalletViewModel.cs
WalletWasabi.Gui/ViewModels/StatusBarViewModel.cs

I think it's not controversial. Can I get an approve from someone?
- Renamed `SetWalletStates` to `TrySetWalletStates` and encapsulated with a try catch.
- Moved the setter logic from `IsBusy` to subscription.

Set statuses in subscribe instead of in the setter

---

WalletWasabi.Gui/Controls/StatusBar.xaml
WalletWasabi.Gui/Controls/WalletExplorer/SendTabViewModel.cs
WalletWasabi.Gui/Controls/WalletExplorer/TransactionBroadcasterViewModel.cs
WalletWasabi.Gui/Converters/StatusBarStatusStringConverter.cs
WalletWasabi.Gui/Models/StatusBarStatus.cs
WalletWasabi.Gui/Tabs/WalletManager/LoadWalletViewModel.cs
WalletWasabi.Gui/ViewModels/StatusBarViewModel.cs

In the StatusBar, for statuses, it'd be better to use enum instead of strings and the converter.  
I also added a lock to the animation, which fixes an annoying bug, where the Loading... got stuck often.

Use enum instead of strings + fix status gets stucked issue

---

WalletWasabi.Documentation/BackendDeployment.md
WalletWasabi.Tests/RegTests.cs
WalletWasabi.Tests/XunitConfiguration/RegTestFixture.cs
WalletWasabi/Extensions/RPCClientExtensions.cs
WalletWasabi/Models/ChaumianCoinJoin/CcjRound.cs
WalletWasabi/Models/ChaumianCoinJoin/CcjRoundConfig.cs
WalletWasabi/Services/CcjCoordinator.cs

Closes https://github.com/zkSNACKs/WalletWasabi/issues/1155
- CoinJoin fees may be getting unbearable with the current mempool state: https://old.reddit.com/r/WasabiWallet/comments/bqy2sw/got_charged_000115_for_one_mix/
- We pay high fees when we have many unconfirmed transactions, even when only confirmed outputs are spent in a CJ. (https://github.com/zkSNACKs/WalletWasabi/issues/1155)
There are 2 changes here.
As described and implemented in issue https://github.com/zkSNACKs/WalletWasabi/issues/1155 we halvened coinjoin fee target based on the number of unconfirmed coinjoins. In this PR I multiply by 0.7 instead of halvening. This may be somewhat controversial in itself, but I believe change 2 justifies it.
The problem with optimizing CJ fee target when a round is created is that we …

Optimize CoinJoin Fees

---

WalletWasabi/Nito/AsyncEx/AsyncMutex.cs

Fixes: https://github.com/zkSNACKs/WalletWasabi/issues/1458
Basically it was a trivial problem with the timeout. But during the debug I discovered more bottlenecks so I fixed them too.

Fix Not Implemented Exception on Linux

---

WalletWasabi.Gui/Controls/WalletExplorer/CoinListViewModel.cs
WalletWasabi.Gui/Controls/WalletExplorer/WalletViewModel.cs
WalletWasabi/Models/SmartCoin.cs
WalletWasabi/Services/WalletService.cs

This PR is for changing the way Wasabi deals with dust coins. Currently Wasabi keeps the dust coins but with a mark that can be queried to know when it is relevant or not. With this PR dust coins are completely ignored by Wasabi as if they have never existed.
Close #1383

Change dust control

---

WalletWasabi.Gui/Config.cs
WalletWasabi.Tests/P2pTests.cs
WalletWasabi.Tests/RegTests.cs
WalletWasabi/Helpers/Constants.cs
WalletWasabi/Models/ServiceConfiguration.cs
WalletWasabi/Services/WalletService.cs

@lontivero's PR (https://github.com/zkSNACKs/WalletWasabi/pull/1384) enabled us to make the DustThreshold configurable.  
This is a straightforward PR.

Make DustThreshold configurable.

---

WalletWasabi.Gui/Controls/NoparaPasswordBox.xaml

Fixes #1430.
Background: The small button that is used to show the password is focusable but when it gets the focus for some reason the whole text is selected.
Quick fix is to not give the "Show password" button the focus.
If this button should be usable when navigating the forms with the keyboard, then a more elaborate fix needs to be implemented.

Bugfix: Fix focus on NoparaPasswordBox that selects text instead of navigating to next field

---

WalletWasabi.Gui/Tabs/WalletManager/RecoverWalletViewModel.cs

We had many recovery issues lately. In this PR I propose to elevate the MinGapLimit at recovery. @lontivero @guggero thoughts?
Turns out the last issue (incorrect balance) with the Mac Stability was that the user was trying to work with recovered wallet, not with the original wallet file. https://github.com/zkSNACKs/WalletWasabi/issues/1404
Other recent issue regarding this: https://github.com/zkSNACKs/WalletWasabi/issues/1470

Elevate mingaplimit at recovery

---

WalletWasabi.Tests/RegTests.cs
WalletWasabi/Models/ChaumianCoinJoin/ActiveOutput.cs
WalletWasabi/Models/ChaumianCoinJoin/ClientRoundRegistration.cs
WalletWasabi/Services/CcjClient.cs
WalletWasabi/WebClients/Wasabi/ChaumianCoinJoin/AliceClient.cs
WalletWasabi/WebClients/Wasabi/ChaumianCoinJoin/BobClient.cs

Title says it all. Should be straightforward.

Create ActiveOutput class (instead of the touple we used previously.)

---

WalletWasabi.Gui/Global.cs
WalletWasabi/Extensions/NBitcoinExtensions.cs
WalletWasabi/Helpers/NBitcoinHelpers.cs

This gains 500ms in startup time, since the address manager loading happens now in parallel with other tasks.
The main takeaway here is that I copied Nicolas's NBitcoin code and changed 2 stream read operation from Read to ReadAsync.

Load AddressManager asynchronously

---

WalletWasabi/KeyManagement/HdPubKey.cs

I got this on console.
```
PS C:\WORK\WalletWasabi\WalletWasabi.Gui> dotnet run
KeyManagement\HdPubKey.cs(111,67): warning CS0618: 'PubKey.GetAddress(Network)' is obsolete: 'Use GetAddress(ScriptPubKeyType.Legacy, network) instead' [C:\WORK\WalletWasabi\WalletWasabi\WalletWasabi.csproj]
2019-06-03 14:42:47 INFO 3b5e1cd5-edad-4fc3-8df1-f46766993b18: Wasabi GUI is starting...
2019-06-03 14:42:50 INFO Config: Config is successfully initialized.
```
Function only used in tests, runs fine after the fix.

Obsolate warning removal from console.

---

WalletWasabi.Gui/Global.cs
WalletWasabi/Nito/AsyncEx/AsyncMutex.cs

fixes: https://github.com/zkSNACKs/WalletWasabi/issues/1519
We have `Logger.TurnOff()` which completely disable logging. Instead of that I prefer checking if there any mutex to release and if not then there is no log message on console.
Why? 
1. I want to keep the logging system on in any case of error there.
2. At `Global.DisposeAsync()` we are doing the same with Managers so better do something similar -> Only execute dispose/close/release if required else no Log message.

Hide Log message on console when --version

---

WalletWasabi/Services/MemPoolService.cs
WalletWasabi/Services/WalletService.cs
WalletWasabi/WebClients/Wasabi/WasabiClient.cs

Closes #1425 - This PR change the cleaning up process from **m*O(n)** to **m*O(1)**

Fix high CPU load

---

WalletWasabi/Models/ChaumianCoinJoin/CcjClientState.cs
WalletWasabi/Services/WalletService.cs

Checking the "ZeroLink" special label is not only a code smell, but it actually enables Attack 1 (Remix Attacks), that Udi described in his presentation on Breaking Bitcoin. https://www.youtube.com/watch?v=DqhxPWsJFZE  
This change removes the label reliance and tries to check if the new coin that arrived spends a coin that is already enqueued instead.

Remove reliance on "ZeroLink" special label

---

WalletWasabi.Documentation/FAQ.md

The current Twitter hyperlink sends you nowhere.

Correct Twitter hyperlink

---

WalletWasabi.Gui/Controls/WalletExplorer/ReceiveTabViewModel.cs

Closes #1542 
There are other places where this same thing can happen, specially when invoke `WalletService`. However I am not sure adding this check everywhere is the best.

Prevents NRE with WalletService

---

WalletWasabi/Services/WalletService.cs

PR https://github.com/zkSNACKs/WalletWasabi/pull/1549 introduces a code smell, because now we shouldn't run enqueue asynchronously, but in order to await it we need to make the functions above it async, too.

Remove Task.Run

---

WalletWasabi.Gui/Controls/WalletExplorer/CoinListView.xaml
WalletWasabi.Gui/Controls/WalletExplorer/CoinListViewModel.cs
WalletWasabi.Gui/Converters/LurkingWifeModeStringConverter.cs

Closes https://github.com/zkSNACKs/WalletWasabi/issues/1561   
Closes https://github.com/zkSNACKs/WalletWasabi/issues/1262
The sum of the selected coins is displayed next to the selection checkboxes.
Related #1561 #1262 #1369

Display the sum of selected coins' amount

---

WalletWasabi/Services/CcjClient.cs

Closes https://github.com/zkSNACKs/WalletWasabi/issues/1379
The quickfix suggested by @NicolasDorier for issue https://github.com/zkSNACKs/WalletWasabi/issues/1379 to upper cap the peer limit and check that on the client side.
Such client side limitations can be problematic in the future and it's clear this is not the best way to go about it, yet I wonder if there're any downsides doing this anyway. We won't be able to go over 100 peers like ever. There are just so many practical issues (IsStandard, Tor, too-long-mempool-chain) with this.  
Note I did 110 instead of 100 to give some wiggle room.

Add more client side checks

---

WalletWasabi/Extensions/NBitcoinExtensions.cs
WalletWasabi/Services/WalletService.cs

BTCPayServer users run a pruned node, which mean that without this pull request, the block download would hang 64 seconds before connecting to another peer.
This PR disconnects immediately if the remote node does not have the block.
NBitcoin `GetBlocks` method has been developed to download the most blocks simultaneously, it is overkill if you only want one block.

Fix hanging block download

---

WalletWasabi/Extensions/NBitcoinExtensions.cs
WalletWasabi/Services/WalletService.cs

Two issues were found:
* Misbehaving clients because we were not properly handshaking before downloading blocks (https://github.com/zkSNACKs/WalletWasabi/issues/1582)
* Tests error caused by this line https://github.com/zkSNACKs/WalletWasabi/pull/1585/files#r294717275
Somehow in tests the runtime params are not set and make tests fail.

Revert the revert hanging block, and fix the issues

---

WalletWasabi.Gui/Global.cs
WalletWasabi.Tests/P2pTests.cs
WalletWasabi.Tests/RegTests.cs
WalletWasabi/Services/WalletService.cs

Closes https://github.com/zkSNACKs/WalletWasabi/issues/1580
Closes https://github.com/zkSNACKs/WalletWasabi/issues/1541
Closes https://github.com/zkSNACKs/WalletWasabi/issues/1514
Closes https://github.com/zkSNACKs/WalletWasabi/issues/1558
Closes https://github.com/zkSNACKs/WalletWasabi/issues/1536
It's a draft, because I want to either make a nice PR or brake this down into multiple parts.
This fixes the "spent" issue with unconfirmed transactions. The issue wasn't that we serialized them improperly, but we deserialized and then serialized them before we would've initialized them properly.

Don't lose unconfirmed transactions.

---

.vscode/settings.json

There isn't a real reason for a `.vscode` folder or a `.editorconfig` to be in the repo.  If you want these to be excluded from something like `git add -A` then you can follow [this guide](https://github.com/bitcoin/bitcoin/blob/master/doc/developer-notes.md#ignoring-ideeditor-files) to exclude desired files/folders.

Remove IDE/Editor folders and files

---

WalletWasabi.Gui/Controls/WalletExplorer/CoinListViewModel.cs
WalletWasabi.Gui/Controls/WalletExplorer/CoinViewModel.cs

This PR unsubscribe the coins events after they are removed from the `CoinListViewModel`. Please review.
Related https://github.com/zkSNACKs/WalletWasabi/issues/1594

Unsubscribe coin events

---

WalletWasabi/Extensions/LinqExtensions.cs
WalletWasabi/Models/ChaumianCoinJoin/CcjClientState.cs

Closes https://github.com/zkSNACKs/WalletWasabi/issues/1594
- optimizes permutations
- if permutation is expected to take too long we'll not do that

Optimize permutations

---

WalletWasabi.Gui/Controls/QrCode.cs
WalletWasabi.Gui/Controls/WalletExplorer/ReceiveTabView.xaml
WalletWasabi.Gui/ViewModels/AddressViewModel.cs

This PR increases the QR code size by increasing a bit the white border around the code. This is one of the reason mentioned in several sites why a qr code can fail to be decoded. Anyway, I tested it with different mobile wallets and it works okay.

Increase QR code size and border

---

WalletWasabi.Gui/Controls/WalletExplorer/SendTabViewModel.cs
WalletWasabi/Extensions/ExceptionExtensions.cs

This PR is for displaying a bit less scary messages to the final user. For example, instead of displaying **too-long-mempool-chain** we display the more human **At least one coin you are trying to spend is part of long chain of unconfirmed transactions. You must wait for some previous transactions to confirm.**

Transalate errors in send message

---

WalletWasabi.Gui/Tabs/WalletManager/GenerateWalletView.xaml

The current line signifies that the Privacy Policy and the Legal Issues are 1 item, by adding the comma after Privacy Policy it signifies that the two are separate.

Fix gramatical error in GenerateWalletView

---

WalletWasabi.Gui/Behaviors/CommandOnEnterBehavior.cs

Addresses some comments in #1450

bugfix: fix CommandOnEnterBehavior not detecting 'enter' key

---

WalletWasabi.Gui/Behaviors/CommandOnEnterBehavior.cs
WalletWasabi.Gui/Controls/WalletExplorer/CoinJoinTabView.xaml
WalletWasabi.Gui/Controls/WalletExplorer/SendTabView.xaml

Closes #1450 
@Transisto [commented](https://github.com/zkSNACKs/WalletWasabi/issues/1450#issuecomment-493221365) that return characters that are copy pasted should not be read, this is done automatically by the textbox it seems.
I added `65ac1e6` so it can be tested with the bugfix.

Confirm password with 'enter' for sending and enqueueing coinjoins

---

WalletWasabi.Gui/App.xaml
WalletWasabi.Gui/Behaviors/CommandOnFirstVisible.cs
WalletWasabi.Gui/Controls/BusyIndicator.cs
WalletWasabi.Gui/Controls/BusyIndicator.xaml
WalletWasabi.Gui/Controls/WalletExplorer/CoinJoinTabViewModel.cs
WalletWasabi.Gui/Controls/WalletExplorer/CoinListView.xaml
WalletWasabi.Gui/Controls/WalletExplorer/CoinListViewModel.cs
WalletWasabi.Gui/Controls/WalletExplorer/HistoryTabView.xaml
WalletWasabi.Gui/Controls/WalletExplorer/HistoryTabViewModel.cs
WalletWasabi.Gui/Controls/WalletExplorer/SendTabViewModel.cs

Binding the list items to the Visual component (ExtendedListBox) can take several seconds. The Tab control loads the items before the Tab actually displayed. As a result when the user clicks to the Send/CoinJoin/History Tab for the first time it is not displayed immediately but seconds later. 
With the PR the Tab is displayed immediately and then start the loading. I also added a Loading animation too.

Display loading animation for CoinList and History list.

---

WalletWasabi.Gui/Controls/WalletExplorer/WalletInfoView.xaml

Looks like I missed this in #1623

Allow 'enter' on show sensitive wallet info

---

WalletWasabi.Gui/Tabs/SettingsView.xaml

Added tooltip, changed title

---

WalletWasabi/WebClients/BlockCypher/BlockCypherClient.cs

Connect with the Blockcypher API over https instead of http

Connect with the Blockcypher API over https instead of http

---

WalletWasabi.Gui/Controls/WalletExplorer/WalletInfoView.xaml
WalletWasabi.Gui/Controls/WalletExplorer/WalletInfoViewModel.cs
WalletWasabi.Gui/Converters/ShowHideSensitiveKeysBoolConverter.cs

Added the ability to hide the sensitive keys after unlocking them. Prior to this PR you would need to close the advanced wallet info tab and re open it for you to hide the keys

Toggle sensitive data on advanced wallet info

---

WalletWasabi/Extensions/NBitcoinExtensions.cs
WalletWasabi/Models/ChaumianCoinJoin/CcjRound.cs

This PR sorts the coinjoin outputs by amount (after shuffling). So it'll look better in a block explorer. This partly addresses what Aviv said about "it's nice to show people how coinjoins work in the CJ transaction" but it does not ruin the shuffling.

Sort coinjoin outputs by amount.

---

WalletWasabi.Gui/Controls/WalletExplorer/CoinJoinTabViewModel.cs

There is a recursive-ish RX call. Works on every OP system but on OSX it freezes the UI after a few minutes at this line:
https://github.com/zkSNACKs/WalletWasabi/blob/80acd15e13696b431ea722badb88f9f3e8a2cc16/WalletWasabi.Gui/Controls/WalletExplorer/CoinJoinTabViewModel.cs#L140

Fix the freeze on OSX related to CJ countdown

---

WalletWasabi.Backend/UnversionedWebBuilder.cs
WalletWasabi.Gui/Controls/WalletExplorer/WalletInfoViewModel.cs
WalletWasabi.Gui/Converters/PrivacyLevelValueConverter.cs
WalletWasabi.Gui/Global.cs
WalletWasabi.Gui/Tabs/AboutViewModel.cs
WalletWasabi.Packager/Program.cs
WalletWasabi.Tests/ExternalApiTests.cs
WalletWasabi/Exceptions/TypeArgumentException.cs
WalletWasabi/KeyManagement/KeyManager.cs
WalletWasabi/Stores/IndexStore.cs

More succinct, avoid duplicate toString call in some instances.

Removed redundant tostring call, avoid duplicate call in some instances

---

WalletWasabi.Gui/Tabs/WalletManager/LoadWalletView.xaml

The current line signifies that the Terzor One and the Terzor T are 1 item, by adding the comma after Tezor One it signifies that the two are separate.

Grammatical error fix

---

WalletWasabi.Documentation/FAQ.md

Added some Q&A on the general beginner level. 
I’m a little worried that I am breaking the existing structure of the FAQ (“Will my coins be fully private after mixing with Wasabi?” might belong into the “post-mix” section, f.ex), but it is made up by the significance of those questions to a beginner who just heard about Wasabi/coinjoin, that’s why I think it’s good to have them on top. If the “pre-install” section is wrong for those, perhaps we could create a new section called “general” or something like that?

Adding new Q&A to the FAQ (documentation)

---

WalletWasabi.Gui/Controls/WalletExplorer/CoinListView.xaml

@benthecarman Good catch, but PR https://github.com/zkSNACKs/WalletWasabi/pull/1828/ is not good. Only if anonset 1 is when the warning should be shown. If anonset 2, then the heuristic is only 50% accurate, so warning message should not be shown. What can be improved is the message itself.
Closes https://github.com/zkSNACKs/WalletWasabi/issues/1826
Closes https://github.com/zkSNACKs/WalletWasabi/pull/1828/

Fix message

---

WalletWasabi.Gui/Tabs/SettingsViewModel.cs

#1785
Validates that the dust threshold is positive, as well as that the port numbers are not a reserved port

Some settings validation

---

WalletWasabi.Gui/Controls/WalletExplorer/WalletInfoView.xaml

I think it is easier to distinguish the sensitive data when it is displayed in a different color.

Display sensitive data in red color

---

WalletWasabi.Gui/Controls/WalletExplorer/CoinListView.xaml
WalletWasabi.Gui/Controls/WalletExplorer/CoinListViewModel.cs
WalletWasabi.Gui/Controls/WalletExplorer/SendTabView.xaml
WalletWasabi.Gui/Controls/WalletExplorer/SendTabViewModel.cs
WalletWasabi.Gui/Converters/AmountForegroundConverter.cs
WalletWasabi.Gui/Converters/LurkingWifeModeStringConverter.cs
WalletWasabi.Gui/Converters/UsdExchangeRateAmountToolTipConverter.cs

@benthecarman has created this PR https://github.com/zkSNACKs/WalletWasabi/pull/1857
closes https://github.com/zkSNACKs/WalletWasabi/pull/1857 (cherry picked @benthecarman's solution.)
Here I've been trying to refactor a couple of things to make sure the code doesn't rot. It still does, but at least I leave the code better than I found it. Anyhow, I started refactoring the `SendTabViewModel` under Ben's PR, but I am afraid I may have made some mistakes there, so I cherry-picked the safest cleanups and so this PR is born.

(Safe) Cleanup of SendTabViewModel

---

WalletWasabi.Gui/Controls/WalletExplorer/CoinListView.xaml

Confirmations on confirmed checkmark tooltip

---

WalletWasabi.Gui/Program.cs
WalletWasabi.Packager/Program.cs

Fixes: #1239 
I cannot test this without creating a release and installing it (I don't know how to do that), but I believe this will fix the issue.

Fix linux dock issue

---

WalletWasabi.Gui/Controls/WalletExplorer/SendTabViewModel.cs
WalletWasabi/Extensions/NBitcoinExtensions.cs

Please bear in mind I am not sure about these changes.
If they are correct shouldn't we use `else if (feeTarget >= 1008)` instead of `else if (feeTarget == 1008)`

Correct possible mistakes

---

.gitignore
WalletWasabi.Gui/Converters/WindowStateAfterSartJsonConverter.cs
WalletWasabi.Gui/UiConfig.cs
WalletWasabi.Gui/ViewModels/StatusBarViewModel.cs
WalletWasabi/Gma/QrCodeNet/Encoding/Positioning/PositioninngPatternBuilder.cs
WalletWasabi/Gma/QrCodeNet/Encoding/QRCodeEncode.cs
WalletWasabi/Models/AllFeeEstimate.cs
WalletWasabi/Services/CcjCoordinator.cs
WalletWasabi/WebClients/Wasabi/WasabiClient.cs

Note that the comment inside `SetTor()` method in the `StatusBarViewModel.cs` file says: `// Set peers to 0 if Tor is ...` it should be modified I think.

Corret some typos

---

WalletWasabi/Models/ChaumianCoinJoin/CcjRound.cs

Addresses https://github.com/MetacoSA/NBitcoin/issues/713#issuecomment-507549321

Fix shuffle on coin join inputs and outputs

---

WalletWasabi.Gui/Controls/WalletExplorer/CoinListView.xaml
WalletWasabi.Gui/Controls/WalletExplorer/CoinListViewModel.cs

Select Private/Non-Private checkboxes use Target Privacy instead of Privacy Level Strong

---

WalletWasabi.Tests/RegTests.cs
WalletWasabi/Extensions/NBitcoinExtensions.cs
WalletWasabi/Models/ChaumianCoinJoin/CcjRound.cs

Thanks @lontivero for telling me how to do this correctly

Sort inputs by amount in CoinJoin

---

WalletWasabi.Gui/Controls/WalletExplorer/WalletInfoView.xaml

Privacy Warning In Wallet Info Tab

---

WalletWasabi/Services/WalletService.cs

We are attempting to remove `toRemove.SpenderTransactionId` but that should be queued up to remove in the recursive calls. We are removing the coin from out personal list of coins and then should remove the same coin from our mempool.

Potential spent coins issue fix

---

WalletWasabi.Gui/Behaviors/PasteAddressOnClickBehavior.cs
WalletWasabi.Gui/Controls/ExtendedTextBox.cs
WalletWasabi.Gui/Controls/WalletExplorer/SendTabView.xaml
WalletWasabi.Gui/Controls/WalletExplorer/SendTabViewModel.cs
WalletWasabi.Tests/ParserTests.cs
WalletWasabi/Helpers/AddressStringParser.cs

Closes #732
Works similar to when you have an address on your clipboard.  If you have a bitcoin url on your clipboard and click the address field, it will auto fill the address, label, and amount using the url's respective fields.  The message field is currently ignored, unsure if we should concatenate this with the label, display it elsewhere, or simply continue ignoring it.

Bitcoin URL support

---

WalletWasabi/Services/WalletService.cs

These lines mess with the VSCode C# linter, this formatting change fixes it.  
Not really a pressing change, would help me read the code though.

Code formatting fix to help linter

---

WalletWasabi/KeyManagement/KeyManager.cs

This is consistent this KeyManager.CreateNew. Doing so allows for front end ignorance to the implementation of KeyManager. It shouldn't have to handle NullReferenceException or initialize the password to empty string.

GetMasterExtKey(password==null) => password = ""

---

.editorconfig

Local variables and parameters should be `camelCase`.

Add local variables and parameters naming rule

---

WalletWasabi.Gui/Global.cs

People get confused when they see notifications saying they received xxx.yyyBTC after a successful coinjoin participation. This PR do not display those notifications when the received coin is a ZeroLink coin.

No notification of ZeroLink coins

---

WalletWasabi.Gui/Config.cs
WalletWasabi/Helpers/Constants.cs

We should explicitly check that it is the regtest network, future networks could be added, segnet for example.

Explicitly check for regtest network

---

WalletWasabi.Gui/Controls/WalletExplorer/CoinViewModel.cs
WalletWasabi/Models/SmartCoin.cs

Currently we never update the coin's status to check if the ban has elapsed.  This PR will recheck it every time `GetSmartCoinStatus()`, which should be called at least every block because it is called when a coin receives a confirmation.

Check if coin is still banned when updating status

---

WalletWasabi/Services/WalletService.cs

In case a transaction is replaced (RBF) by other one or when there is a chain reorg the coins created by those transactions are removed from the Coins list. The transactions that created those coins has to be removed too.

Remove Replaced transactions from cache

---

WalletWasabi.Gui/Controls/WalletExplorer/HistoryTabViewModel.cs
WalletWasabi.Gui/Controls/WalletExplorer/WalletViewModel.cs
WalletWasabi.Tests/TransactionProcessorTests.cs
WalletWasabi/Services/TransactionProcessor.cs
WalletWasabi/Services/WalletService.cs
azure-pipelines-linux.yml
azure-pipelines-osx.yml
azure-pipelines-windows.yml

Move the transaction processing code from `WalletService` to a new testeable `TransactionProcessor` class and creates tests for each scenario. This is important because this piece of code is `complex` and has been modified many times in the past to improve performance, add support for RBF, check for transaction relevance, detect coinjoins, fix TransactionCache status and other small changes and fixes; and it is also a `critical` in the sense that a bug here can have big consecuences. That's why IMO we need unit tests here.

Test transaction processing code

---

WalletWasabi.Gui/Shell/Commands/HelpCommands.cs
WalletWasabi.Gui/Shell/Commands/ToolCommands.cs
WalletWasabi.Gui/Shell/MainMenu/HelpMainMenuItems.cs
WalletWasabi.Gui/Shell/MainMenu/ToolsMainMenuItems.cs

In `ToolCommands.cs` should I create a `devToolsCommand` variable and then `.Merge(devToolsCommand.ThrownExceptions)`?

Move Dev Tools MenuItem from Help to Tools

---

WalletWasabi/Extensions/HttpRequestMessageExtensions.cs
WalletWasabi/Extensions/HttpResponseMessageExtensions.cs
WalletWasabi/Helpers/HttpMessageHelper.cs
WalletWasabi/Http/Models/HeaderField.cs
WalletWasabi/Http/Models/HeaderSection.cs
WalletWasabi/Http/Models/RequestLine.cs
WalletWasabi/Http/Models/StartLine.cs
WalletWasabi/Http/Models/StatusLine.cs
WalletWasabi/TorSocks5/TorHttpClient.cs
WalletWasabi/TorSocks5/TorProcessManager.cs
WalletWasabi/TorSocks5/TorSocks5Client.cs

This PR has 3 changes in 3 commits. They can be merged altogether or cherry-picked separately.  
In commits https://github.com/zkSNACKs/WalletWasabi/commit/0fac56e07299151b77574450fe8a21b49927d18f and https://github.com/zkSNACKs/WalletWasabi/commit/950df84c5876425f9cdd5c9011ee454b19d1dba9 I made sure we use the non-blocking version of `ReadToEnd`, which is `ReadToEndAsync`.  
In commit https://github.com/zkSNACKs/WalletWasabi/commit/6bb7d252ebab34e4d4ef3f5251d57a8c83089bec I made sure the Tor library is consistently using `ConfigureAwait(false)`, since it does not have to synchronize back the context ever. This may result in some performance increase.  
This PR follows the same pattern as the HWI PR does. I'm `ConfigureAwait(false)`-ing there, too: …

Apply async best practices to Tor library

---

WalletWasabi.Tests/TorTests.cs

The w3.org service is often unavailable, so I thought it'd be better to replace the test with another tester website.

Replace chunked encoding test url

---

WalletWasabi.Gui/Tabs/WalletManager/LoadWalletViewModel.cs

Maybe it should used somewhere, I don't know.

Remove unused member

---

WalletWasabi.Gui/Controls/WalletExplorer/SendTabViewModel.cs

If you do not have a `.`  in the amount text, then `dotIndex` will be `-1` so the substring will only allow you to have an amount of 9,999,999 (7 digits)
If this edge case every actually happens that person owes me 1 btc

Allow entering amounts over 10,000,000 btc

---

WalletWasabi.Packager/Program.cs
WalletWasabi/Services/WalletService.cs

and rename `iconpath` to `iconPath`

Fix formatting

---

WalletWasabi.Gui/Controls/WalletExplorer/SendTabView.xaml
WalletWasabi.Gui/Controls/WalletExplorer/SendTabViewModel.cs
WalletWasabi.Gui/Converters/FeeTargetTimeConverter.cs

Confirmation Expected Text moved to FeeTarget Converter

---

WalletWasabi.Gui/Controls/WalletExplorer/SendTabViewModel.cs

Fixes: https://github.com/zkSNACKs/WalletWasabi/issues/2184
When I added the compatibility/notification functions I also added a Password check before the BuildTx which cannot be done with watch-only wallets.
https://github.com/zkSNACKs/WalletWasabi/commit/d7fde2d8a0b2c0c1dfc58ed7529a16014feacb08#diff-bc431b4bc31acb6d49cd62c6288310e7R321

No password check in WatchOnly wallets

---

WalletWasabi.Packager/Program.cs

As discussed with @nopara73 in #2161

Refactor code (remove redundant check)

---

WalletWasabi/Models/ConcurrentHashSet.cs

If this is ugly I can surround the `Tables` and `Node` classes with the pragma warning.

Add pragma warning

---

WalletWasabi.Documentation/BackendDeployment.md

This PR documents the steps to:
* Rotate Bitcoin Core node `debug.log` log file. This is done on a daily basis and compressing the oldest files.
* Letting the maintainers know which server they have logged in by adding a _Welcome Banner_ and also indicating the [PROD|TEST] environment in the prompt.

Add optional settings

---

WalletWasabi.Gui/Controls/WalletExplorer/TransactionBroadcasterViewModel.cs
WalletWasabi/Helpers/NBitcoinHelpers.cs
WalletWasabi/WalletWasabi.csproj

Fixes #2203
cc: @NicolasDorier  
Related: https://github.com/zkSNACKs/WalletWasabi/issues/2193

Handle PSBTExceptions in TransactionBroadcaster + NBitcoin dependency update.

---

WalletWasabi.Gui/UiConfig.cs

The UIConfig file is instantly updated when setting values are modified, except in the case of `Autocopy`. This PR fixes that.

Autocopy property raise event when changes

---

WalletWasabi.Gui/Behaviors/CommandOnKeyUpBehavior.cs

Here we just only want to detect the key-up but do not want to interrupt the bubbling or tunneling of it.  Before this on OSX when you pressed the arrows the cursor in the textbox not moved.

Let the keyup event tunneling deeper

---

WalletWasabi.Gui/Config.cs

Fixes https://github.com/zkSNACKs/WalletWasabi/issues/2262. When the Config.json file does not exist (first-time installation) the `ServiceConfiguration` is `null`.

Fix ANE when new installations

---

WalletWasabi.Tests/UnitTests/LoggerTests.cs
WalletWasabi/Logging/Logger.cs

Extract filename independentlu of the OS

---

WalletWasabi.Gui/Controls/LockScreen/PinLockScreen.xaml
WalletWasabi.Gui/Controls/LockScreen/SlideLockScreen.xaml

This fixes the problem when a dev wants to debug the controls via Dev Tools and the hidden lockscreens are eating the focus up.
Fixes #2086

Hide the lockscreens on visual tree when not displayed.

---

WalletWasabi.Gui/Behaviors/BindSelectedTextBehavior.cs
WalletWasabi.Gui/Behaviors/ClearPropertyOnLostFocusBehavior.cs
WalletWasabi.Gui/Behaviors/CommandOnFirstVisible.cs
WalletWasabi.Gui/Behaviors/FocusBehavior.cs

Is this more readable. If so I would like to do that with the rest of extension methods that can be written in one line.

Stylistic changes

---

WalletWasabi/Services/UtxoReferee.cs

This fixes a serialization bug in the banned utxo file. Entries were serialized with two different formats (see below) and then when loaded after a restart the file was considered always broken. 
```
$ cat BannedUtxosMain.txt 
[fc693cf83ee579a02610ac08239783a7253a1f91ca834509d07dc7052d895bbd-43, 2019-09-15 23-11-04:1:43:fc693cf83ee579a02610ac08239783a7253a1f91ca834509d07dc7052d895bbd:True:9577]
[32d0f39f10116587b0d268c74544a490da9b30aa18522f9b4d7f35665ffa070d-25, 2019-09-14 18-37-02:1:25:32d0f39f10116587b0d268c74544a490da9b30aa18522f9b4d7f35665ffa070d:True:9548]
2019-09-16 09-27-27:1:14:3a0b48a4ef5a4282f846fca8c9ee6e95fede25cd135758b8b009da6567eb2dbd:True:9587
2019-09-16 09-34-15:1:111:e29d088dac20326dc1d155fb2e86a797aea16796053ffff2af3424bb781190a5:True:9589
```

Fix incompatible serialization

---

WalletWasabi.Gui/Converters/AmountForegroundConverter.cs
WalletWasabi.Gui/Converters/BooleanStringConverter.cs
WalletWasabi.Gui/Converters/CoinItemExpanderColorConverter.cs
WalletWasabi.Gui/Converters/CoinJoinedVisibilityConverter.cs
WalletWasabi.Gui/Converters/CoinStatusBorderBrushConverter.cs
WalletWasabi.Gui/Converters/CoinStatusColorConverter.cs
WalletWasabi.Gui/Converters/CoinStatusForegroundConverter.cs
WalletWasabi.Gui/Converters/CoinStatusStringConverter.cs
WalletWasabi.Gui/Converters/FeeTargetTimeConverter.cs
WalletWasabi.Gui/Converters/FilterLeftStatusConverter.cs
WalletWasabi.Gui/Converters/InverseBooleanConverter.cs
WalletWasabi.Gui/Converters/MoneyBrushConverter.cs
WalletWasabi.Gui/Converters/MoneyStringConverter.cs
WalletWasabi.Gui/Converters/NetworkStringConverter.cs
WalletWasabi.Gui/Converters/PhaseStringConverter.cs
WalletWasabi.Gui/Converters/PrivacyLevelValueConverter.cs
WalletWasabi.Gui/Converters/StatusBarStatusStringConverter.cs
WalletWasabi.Gui/Converters/TimeSpanStringConverter.cs
WalletWasabi.Gui/Converters/TimeSpanVisibilityConverter.cs
WalletWasabi.Gui/Converters/UsdExchangeRateAmountToolTipConverter.cs
WalletWasabi/Exceptions/TypeArgumentException.cs

If this is correct should I do the same for all the classes in `\WalletWasabi\WalletWasabi\Extensions` folder?
Note that `TorHttpClientExtensions` class doesn't have a namespace.

Correct TypeArgumentException's namespace

---

WalletWasabi.Backend/Controllers/BatchController.cs

There are some NRE in the server logs. This PR fixes that.
```
Sep 14 03:01:18 WalletWasabi walletwasabi-backend[9532]: System.NullReferenceException: Object reference not set to an instance of an object.
Sep 14 03:01:18 WalletWasabi walletwasabi-backend[9532]:    at NBitcoin.uint256..ctor(String str)
Sep 14 03:01:18 WalletWasabi walletwasabi-backend[9532]:    at WalletWasabi.Backend.Controllers.BatchController.GetSynchronizeAsync(String bestKnownBlockHash, Int32 maxNumberOfFilters, String estimateSmartFeeMode)
```

Returns BadRequest when invalid bestKnownBlockHash

---

WalletWasabi.Tests/IntegrationTests/RegTests.cs

I decided to break down PR #2188 to reviewable parts. In this PR I simplify and improve logging a lot.
First improvement is because the test was randomly failing, it was asserting the wrong thing.  
Second improvement is just syntax sugar.

Improve RegTests (MempoolStore Breakdown Part 9)

---

WalletWasabi.Gui/Controls/QrCode.cs
WalletWasabi.Gui/Controls/WalletExplorer/ReceiveTabView.xaml

Split up fixes from https://github.com/zkSNACKs/WalletWasabi/pull/2316
This fixes up the gaps between the address QR code blocks and make it pixel-perfect.

Fix QRCode render issues (part 1 of n)

---

WalletWasabi/KeyManagement/KeyManager.cs

This PR introduces a minor performance improvement in the new key generation algorithm by using a O(n) approach. This is important only for really huge wallets (lots of pubkeys). 
This is how this works: lets say our wallet contains keys with the following indexes: `KI=[0, 1, 2, 3, 7, 4, 8, 9, 12, 10]`. All keys with index greater than 12 are available however we can see that there are gaps in our key list that should be filled (`[5, 6]` and `[11]`).  The first available key index is 5.
The new algorithm gets the greater used index (12) and creates a boolean array `present` of 13: `[F, F, F, F, F, F, F, F, F, F, F, F, F]` and iterates the array `KI` flagging the presence of its index key in the `present` array, this is: `present[KI[i].Index] = true`. So, after this step the `present` …

Faster search of empty keys gap

---

WalletWasabi.Tests/UnitTests/AsyncMutexTests.cs
WalletWasabi.Tests/UnitTests/IoTests.cs
WalletWasabi/Nito/AsyncEx/AsyncMutex.cs
azure-pipelines-linux.yml
azure-pipelines-osx.yml
azure-pipelines-windows.yml

Continuation of this PR: https://github.com/zkSNACKs/WalletWasabi/pull/2346
- Instead of constant wait, detect the start of the task. This will improve stability if the CI is slow.
- Define exact dotnet core version in yaml.

Fix CI on linux

---

WalletWasabi.Documentation/BackendDeployment.md

@nopara73 please confirm if `--with-http_sub_module` submodule is packaged with nginx on the server (and your local machine for testing) by running `ngingx -V`. 
Then update the nginx configuration at `/etc/nginx/sites-available/default` with the one in this PR.
Please test locally before updating the server's nginx config. 
It should add `<meta name="robots" content="noindex, nofollow" />` in the `<head>` of HTML served by all the domains except www.wasabiwallet.io.

Disable search engine crawling on secondary domains

---

WalletWasabi/Models/SmartTransaction.cs
WalletWasabi/Services/TransactionProcessor.cs
WalletWasabi/Services/WalletService.cs

It merges labels for example, so if one wallet sets label, then the other wallet can pick it up and merge them (after the TransactionStore PR)

Replace SmartTransaction SetHeight with Update

---

WalletWasabi.Gui/Tabs/WalletManager/LoadWalletViewModel.cs

If the HW search or load failed for some reason there will be an error message. This message should be cleared after the search button pressed again.

Clear warning message before search hw.

---

WalletWasabi/Services/TransactionProcessor.cs

When a confirmed transaction is received and we were already aware of it (it was already processed before) it is not necessary to reprocess it; we can update the Height of its coins and abort the process.

Simplify transaction processing code

---

WalletWasabi/Services/WalletService.cs

I removed `return await Task.FromResult(TransactionProcessor.Process(tx));` to be sync as it is. Everything else are just adjustments to this.

Don't async needlessly

---

.editorconfig

[Here](https://github.com/zkSNACKs/WalletWasabi/pull/1919#issuecomment-512223958) nopara suggested to remove `local function` from the rule but I think we should add them because they are used sometimes.

Add local function to the naming rule that enforces them to be PascalCase

---

WalletWasabi/Transactions/TransactionStore.cs

It enables things like (after txstore is used) if we're sending from one of our wallet to another one of our wallet that the labels to be merged from both wallets instead of preferring randomly one.

Make sure to update transactions those would be processed as duplicate.

---

WalletWasabi.Gui/Tabs/AboutViewModel.cs

Currently, uptime robot registration is under my personal account. Change it to zkSNACKs'.
The new link is here:
https://stats.uptimerobot.com/YQqGyUL8A7
Also, we can consider adding something like a redirection URL like we did at docs.wasabiwallet.io.
status.wasabiwallet.io and add the uptime robot link there.
In Wasabi we could link status.wasabiwallet.io in this way we would have more control on the status page.

Status page change the link to zkSNACKs.

---

WalletWasabi.Backend/Global.cs

This makes a bit easier to find the Wasabi Coordinator connection when we do `bitcoin-cli getpeerinfo`. Currently we are using the `/NBitcoin:4.0.14/` user agent.
Basically, we can check if wasabi backend is connected to the bitcoin full node by doing something like:
```
$ bitcoin-cli getpeerinfo | grep Wasabi 
```

Make easier to identify backend connection

---

azure-pipelines-linux.yml
azure-pipelines-osx.yml
azure-pipelines-windows.yml

There is a new 3.1 preview release that messed up azure versioning. 
Had to change 3.x to 3.0.x. 
"The issue seems with the latest 3.1 version which is in preview state."
https://github.com/microsoft/azure-pipelines-tasks/issues/11569

Fix azure CI dotnet core 3 install

---

WalletWasabi/Services/TransactionFactory.cs

This PR is to start discussing a first step to address the https://github.com/zkSNACKs/WalletWasabi/issues/1543.
The idea is to opt-in RBF in the 10% of the Wasabi wallet transactions. IMO this is better for privacy that do not having any RBF at all because in that case the WW txs are even more obvious.

Opt-in RBF in 2% of transactions

---

WalletWasabi/Models/ChaumianCoinJoin/CcjRound.cs

In the server log file there are several entries like the following:
```
2019-10-15 09:57:18 WARNING	CcjRound (771)	Failed to optimize fees. Fallback to normal fees.
2019-10-15 09:57:18 WARNING	CcjRound (772)	System.ArgumentOutOfRangeException: Cannot be less than 0.
Parameter name: feePaid
at NBitcoin.FeeRate..ctor(Money feePaid, Int32 size)
at WalletWasabi.Models.ChaumianCoinJoin.CcjRound.TryOptimizeFeesAsync(IEnumerable`1 spentCoins)
```
That error occurs when the `sum(inputs.value) < sum(output.value)`. In other words, we have a bug or `NBitcoin` has a bug. I will take a look at `NBitcoin` code just in case.

Better log for coinjoin tx fee errors.

---

WalletWasabi.WindowsInstaller/Product.wxs

Fixes: https://github.com/zkSNACKs/WalletWasabi/issues/2433
> This is useful when two product versions differ only in the fourth version field. MSI specifically ignores that field when comparing product versions, so two products that differ only in the fourth version field are the same product and need this attribute set to yes to be detected.
WARNING!
> Note that because MSI ignores the fourth product version field, setting this attribute to yes also allows downgrades when the first three product version fields are identical. For example, product version 1.0.0.1 will "upgrade" 1.0.0.2998 because they're seen as the same version (1.0.0). That could reintroduce serious bugs so the safest choice is to change the first three version fields and omit this attribute to get the default of no. …

Remove previous versions after installing a new version of Wasabi

---

WalletWasabi/Coins/CoinsRegistry.cs
WalletWasabi/Coins/CoinsView.cs
WalletWasabi/Coins/ICoinsView.cs

Correct capitalization

---

WalletWasabi.Gui/Controls/WalletExplorer/CoinViewModel.cs
WalletWasabi.Gui/Controls/WalletExplorer/ReceiveTabViewModel.cs
WalletWasabi.Gui/Controls/WalletExplorer/SendTabViewModel.cs
WalletWasabi.Gui/ViewModels/AddressViewModel.cs
WalletWasabi.Tests/IntegrationTests/RegTests.cs
WalletWasabi.Tests/UnitTests/KeyManagementTests.cs
WalletWasabi.Tests/UnitTests/LinqExtensionsTests.cs
WalletWasabi.Tests/UnitTests/SmartCoinTests.cs
WalletWasabi.Tests/UnitTests/SmartLabelTests.cs
WalletWasabi.Tests/UnitTests/Transactions/AllTransactionStoreTests.cs
WalletWasabi.Tests/UnitTests/Transactions/SmartTransactionTests.cs
WalletWasabi.Tests/UnitTests/Transactions/TransactionFactoryTests.cs
WalletWasabi.Tests/UnitTests/Transactions/TransactionProcessorTests.cs
WalletWasabi.Tests/UnitTests/Transactions/TransactionStoreTests.cs
WalletWasabi/BlockchainAnalysis/Cluster.cs
WalletWasabi/BlockchainAnalysis/SmartLabel.cs
WalletWasabi/Coins/SmartCoin.cs
WalletWasabi/Extensions/LinqExtensions.cs
WalletWasabi/JsonConverters/SmartLabelJsonConverter.cs
WalletWasabi/Transactions/TransactionBuilding/SmartCoinSelector.cs
WalletWasabi/Transactions/TransactionHistoryBuilder.cs

This PR builds transactions with a better privacy level by taking the coins' cluster information into account during the coins selection process.
* Coins with the same `ScriptPubKey` belong always to the same cluster
* Coins with anonymity set higher than the `StrongPrivacyThreshold` belong to a one-element cluster (a cluster with only one coin)
The `SmartCoinSelector` tries to avoid merging coins from different clusters in order to minimize the number of people/entities that can know about the built transaction. It does that by creating a small set of clusters combinations sorted by their privacy levels and selecting the best cluster (or clusters combination) big enough to cover the spending target. 
In case no cluster, nor clusters combination, candidate is found it fallback to the …

Improve transaction privacy by taking clusters info into account

---

WalletWasabi/JsonConverters/TransactionJsonConverter.cs
WalletWasabi/Transactions/SmartTransaction.cs

~70%~ 40% of my CPU is consumed calculating transaction hashes.
This PR make NBitcoin cache the hash after first computation. This is safe as there is no reason to modify transactions that we deserialize.

Precompute transaction hashes on deserialization

---

WalletWasabi.Backend/wwwroot/index.html

Sorry @mayankchhabra but I think we should add `rel="nofollow"` to weareblockspace link.
Please listen to [Google Webmaster Video at 19:47](https://www.youtube.com/watch?v=vfSFcImNFX4#t=1187).
Google's John Mueller said "definitely put a nofollow rule for those links." That is even if the site owner wants the link there, you should still nofollow it.
For those unfamiliar with the importance of nofollow SEO links:
[https://ahrefs.com/blog/nofollow-links/](https://ahrefs.com/blog/nofollow-links/)

Add rel="nofollow" to weareblockspace link

---

WalletWasabi/Helpers/Constants.cs
WalletWasabi/Transactions/TransactionFactory.cs

This will be need to be changed in the future either due to the rise or fall in transactions signaling rbf or needing to be reassessed because wasabi switches to a future segwit version.  I think it makes more sense to have things like this in the constants file.

Move RBF rate to Constants.cs

---

WalletWasabi/Coins/CoinsView.cs

The current version on master only deletes two levels of coins (children and children's children)

Fix recursive coin deletion

---

WalletWasabi.Gui/ViewModels/StatusBarViewModel.cs

Issue: Whenever you click on the status bar, it opens the download link even though there's no updates available yet. This fixes that issue by checking the `UpdateAvailable` & `CriticalUpdateAvailable` properties.
cc: @molnard @nopara73

StatusBar fixes (Part I)

---

WalletWasabi.Backend/Global.cs
WalletWasabi.Backend/Startup.cs
WalletWasabi.Tests/IntegrationTests/RegTests.cs
WalletWasabi.Tests/UnitTests/BitcoinCore/P2pBasedTests.cs
WalletWasabi.Tests/XunitConfiguration/RegTestFixture.cs
WalletWasabi/Bases/PeriodicRunner.cs
WalletWasabi/BitcoinCore/CoreNode.cs
WalletWasabi/BitcoinCore/Monitoring/RpcFeeProvider.cs
WalletWasabi/BitcoinCore/Monitoring/RpcMonitor.cs
WalletWasabi/Blockchain/BlockFilters/History/ActionHistoryHelper.cs
WalletWasabi/Blockchain/BlockFilters/History/ActionItem.cs
WalletWasabi/Blockchain/BlockFilters/History/Operation.cs
WalletWasabi/Blockchain/BlockFilters/IndexBuilderService.cs
WalletWasabi/Blockchain/BlockFilters/SyncInfo.cs
WalletWasabi/Blockchain/Blocks/BlockNotifier.cs
WalletWasabi/CoinJoin/Coordinator/Coordinator.cs
WalletWasabi/Services/ConfigWatcher.cs
WalletWasabi/Services/IndexBuilderService.cs
WalletWasabi/Services/TrustedNodeNotifyingBehavior.cs
WalletWasabi/Services/UpdateChecker.cs

Periodically query block notifications through RPC, except if they're triggered manually by P2P.
Closes https://github.com/zkSNACKs/WalletWasabi/pull/2523
It is a workaround for this bug/safety measure: https://github.com/bitcoin/bitcoin/issues/17451

Make Block notifications reliable

---

WalletWasabi.Gui/App.xaml
WalletWasabi.Gui/Controls/BusyIndicator.cs
WalletWasabi.Gui/Controls/BusyIndicator.xaml
WalletWasabi.Gui/Controls/WalletExplorer/CoinListView.xaml
WalletWasabi.Gui/Controls/WalletExplorer/CoinListViewModel.cs

In some specific wallets with a lot of coins, the loading time is still a lot. This PR put back the loading animation into the CoinList of SendTab and CoinJoin tab. 
History tab will remain as it is now, it is fast. 
The delay not caused by the business logic instead of the UI elements creation and binding. 
Virtualization or optimization of the list can solve this, but until that BusyIndicator will remain. 
Partially reverts: https://github.com/zkSNACKs/WalletWasabi/pull/2479
Related: 
https://github.com/zkSNACKs/WalletWasabi/issues/1298
https://github.com/zkSNACKs/WalletWasabi/pull/2076#issuecomment-518807315
https://github.com/zkSNACKs/WalletWasabi/issues/597

Put BusyIndicator back to CoinLists

---

WalletWasabi.Tests/IntegrationTests/RegTests.cs
WalletWasabi.Tests/UnitTests/Transactions/TransactionProcessorTests.cs
WalletWasabi/Blockchain/TransactionOutputs/CoinsRegistry.cs

When a transaction replace another one that is the root of a long chain of other transactions, all the coins created by those transactions that will be replaced must be removed from the spent coins list too. I've found this today during a walk-through with @yahiheb

Remove coins spent by replaced txs

---

WalletWasabi.Backend/Global.cs
WalletWasabi.Tests/UnitTests/BlockNotifierTests.cs
WalletWasabi/BitcoinCore/CoreNode.cs
WalletWasabi/BitcoinCore/IRPCClient.cs
WalletWasabi/BitcoinCore/RpcWrappedClient.cs
WalletWasabi/Blockchain/Blocks/BlockNotifier.cs

This PR contains unit tests for the `BlockNotifier` class in order to be able to validate its correctness as part of the continuous integration process. These are no a replace for the existing integration tests.
In order to be able to unittest it, it was necessary to isolate the component from external dependencies like the RPC client and the P2pNode.

Unit tests for BlockNotifier

---

WalletWasabi.Backend/Startup.cs
WalletWasabi.Gui/Global.cs
WalletWasabi/BitcoinCore/P2pNode.cs

Please verify if this is correct.
In `Startup.cs` in `CleanupAsync` method we have:
```
global.Coordinator?.Dispose();
Logger.LogInfo($"{nameof(global.Coordinator)} is disposed.");
```
if `global.Coordinator` is null should we log?

Remove null-conditional operator

---

WalletWasabi.Tests/UnitTests/Transactions/TransactionProcessorTests.cs
WalletWasabi/Blockchain/Transactions/TransactionProcessor.cs

This PR add asserts to the current tests in order to verify the `TransactionStore` state is always correct.

Test TransactionStore states

---

.editorconfig

Sometimes it is much better to have a body for lambdas. Let the coder decide.

Use expression body for lambdas => Suggestion

---

WalletWasabi.Gui/Controls/GroupBox.cs
WalletWasabi.Gui/Controls/GroupBox.xaml

Simplifying GroupBox by just using grid col/rows instead of hacking around the arrange methods. Grid alignment is derived from WPF's PresentationFramework.Aero style xaml.
cc: @nopara73 @molnard

Simplify GroupBox

---

WalletWasabi.Tests/UnitTests/Transactions/AllTransactionStoreTests.cs
WalletWasabi/Blockchain/Transactions/AllTransactionStore.cs
WalletWasabi/Services/WalletService.cs

One more test for reorgs. There is case that I don't know if it is possible, it is when we call `TryReorg` with a block hash that is not the tip.

Test block reorgs

---

WalletWasabi.Gui/Converters/ErrorDescriptorToBorderColorConverter.cs

Iv stopped the border converter printing exceptions because:
1) It shouldnt be the responsibility of a converter to intercept and log exceptions.
2) These exceptions are not uncaught exceptions.
3) Avalonia handles these internally. Its an allowed state when you have changed your datacontext, but not updated your UI.
This now has the same behavior as previous version of Wasabi.
Closes https://github.com/zkSNACKs/WalletWasabi/issues/2513
Closes https://github.com/zkSNACKs/WalletWasabi/issues/2552

Fix Missing Member exceptions in Logs from Wallet Manager tab

---

WalletWasabi/CoinJoin/Coordinator/Rounds/CoordinatorRound.cs

We receive `Alice not found` reports from users (it is in the client log). It means that the backend removed Alice for some reason from the CoinJoin round without notifying the client about this at that point. In many cases, the notification is impossible as the Backend doesn't know who to notify and also only clients can initialize communication.
`Alice not found` is not an issue it is an intended behavior when the server removes invalid Alices to maintain successful CoinJoins. 
With this PR we will have a server-side log record when Alice removed by mempool dis-acceptance. The log will contain the reason for this.

Log Mempool dis-acceptance reason on Backend

---

WalletWasabi.Gui/ManagedDialogs/ManagedFileChooserViewModel.cs
WalletWasabi.Tests/IntegrationTests/RegTests.cs
WalletWasabi/WebClients/Wasabi/WasabiClient.cs

Make sure to use to convert `IEnumerable` into object (`First`) or array (`ToArray()`) when using `Select(x => new MyClasse(x))`. 
To avoid accidental multiple creations of the objects. 
I did not find anything suspicious so just nitpicking.

Avoid multiple enumeration on Select(x => new...)

---

WalletWasabi.Gui/Tabs/WalletManager/LoadWalletViewModel.cs

new users might come across this as they start with no wallets, probably why non of us have noticed this before.

Fix: When you have no wallets and Click Load Wallet it says Wallet already loaded

---

WalletWasabi.Gui/Controls/WalletExplorer/CoinListViewModel.cs
WalletWasabi.Gui/Controls/WalletExplorer/HistoryTabViewModel.cs
WalletWasabi.Gui/Controls/WalletExplorer/ReceiveTabViewModel.cs
WalletWasabi.Gui/Controls/WalletExplorer/WalletViewModel.cs
WalletWasabi.Gui/Global.cs
WalletWasabi.Tests/IntegrationTests/RegTests.cs
WalletWasabi.Tests/UnitTests/Transactions/TransactionProcessorTests.cs
WalletWasabi/Blockchain/TransactionProcessing/TransactionProcessor.cs
WalletWasabi/Blockchain/TransactionProcessing/TxCoinsEventArgs.cs
WalletWasabi/CoinJoin/Client/Clients/CoinJoinClient.cs
WalletWasabi/CoinJoin/Client/Rounds/ClientState.cs
WalletWasabi/Services/WalletService.cs

So events raised from txprocessing are merged together. Eg, if we receive 50 coins in one tx, then we only raise 1 event that contains all 50 coins instead of 50 separate events.
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/2641

Use merged events

---

WalletWasabi.Gui/Converters/ErrorDescriptorToBorderColorConverter.cs

Fixes #2610 by handling the exception that is thrown by avalonia bindings system when the textbox string value doesnt match the target property's type.

Fix missing error border color

---

WalletWasabi.Gui/Helpers/NotificationHelpers.cs
WalletWasabi.Gui/Helpers/NullNotificationManager.cs

Use local NullNotificationManager

---

WalletWasabi.Gui/Controls/WalletExplorer/ReceiveTabViewModel.cs
WalletWasabi.Gui/ViewModels/AddressViewModel.cs
WalletWasabi.Tests/IntegrationTests/RegTests.cs
WalletWasabi/Blockchain/Keys/KeyManager.cs
WalletWasabi/Services/WalletService.cs

Based on and closes https://github.com/zkSNACKs/WalletWasabi/pull/2659
Closes https://github.com/zkSNACKs/WalletWasabi/issues/2624
Closes https://github.com/zkSNACKs/WalletWasabi/issues/2340
As @btcpirate described in https://github.com/zkSNACKs/WalletWasabi/issues/2340, we were recycling receive addresses when the user created too much. In this PR, I decided to stop recycling and instead give notifications to the user if the gap limit is exceeded for new address generation:
I realized the restore issue should practically never happen because we are restoring wallets with 100 gap limit by default unlike the wallet generation that's only using 21, so we have a nice 79 addresses leeway there.

Adjust gap limit for too many receive instead of recycling.

---

WalletWasabi.Gui/Controls/WalletExplorer/SendTabView.xaml
WalletWasabi.Gui/Controls/WalletExplorer/SendTabViewModel.cs

Fixes: https://github.com/zkSNACKs/WalletWasabi/issues/2237
If you subscribe with `WhenAnyValue` to a property and want to modify that inside the subscription it causes deadlock randomly on OSX. It is the same with `AmountText` property. So instead of Subscribing the change, I subscribe to the `KeyUp` event. 
The same walkaround already used elsewhere in Wasabi. 
Hide whitespace changes!

Use KeyUp instead of Text property

---

WalletWasabi.Gui/WalletWasabi.Gui.csproj

Fixes:
#2549 OSX menu not working on Catalina
#2644 Warning / Exception when closing Wasabi.

Update Avalonia 0.9 with a couple of fixes

---

WalletWasabi.Gui/Controls/WalletExplorer/SendTabViewModel.cs

Fixes #2623 but I'm not sure if this is the correct fix...
For some reason, the `ObservableAsPropertyHelper` version of `IsCustomFee` is not sending any change notifications to the binding so i changed it into a regular rx property and it works.
I need some guidance here @molnard @nopara73

Fix Manual Fee box not showing up on first instance.

---

WalletWasabi.Gui/Global.cs
WalletWasabi/Blockchain/TransactionProcessing/TransactionProcessor.cs

Closes https://github.com/zkSNACKs/WalletWasabi/issues/2699
On the one hand, we weren't checking CJ confirmed, on the other hand we had a bug in our "IsLikelyCoinJoin" calculation at the transaction processor. It was only going through unspent coins, where it must go through all the coins instead, because when we're only processing the tx for confirmation, we must look for spent coins, too.

Fix CoinJoin confirmed notification

---

WalletWasabi/CoinJoin/Coordinator/Rounds/CoordinatorRound.cs

The last remained event invoked from a lock.
Fixes: https://github.com/zkSNACKs/WalletWasabi/issues/2653

Fix CoinJoinBroadcastedEvent

---

WalletWasabi.Gui/Global.cs
WalletWasabi.Gui/Helpers/FileHelpers.cs
WalletWasabi.Gui/Shell/Commands/DiskCommands.cs
WalletWasabi.Gui/Tabs/SettingsViewModel.cs
WalletWasabi/Helpers/IoHelpers.cs

Closes #2733
Note: I moved the `OpenFileInTextEditor` from the WalletWasabi project to the WalletWasabi.Gui because it is only used in the GUI.

Display a notification when file is not found

---

WalletWasabi.Gui/Controls/WalletExplorer/TransactionBroadcasterViewModel.cs

Closes #2746 by disabling the `Broadcast transaction` button when the textbox is empty

Disable Broadcast button

---

WalletWasabi.Backend/wwwroot/index.html

The macOS guide link changed after https://github.com/zkSNACKs/WasabiDoc/pull/373
There is this file `/WalletWasabi.Backend/wwwroot/onion-index.html` that is ignored in `.gitignore`, should that file not be updated?
Fixes: https://github.com/zkSNACKs/WalletWasabi/issues/2729

Update masOS guide link

---

WalletWasabi.Gui/Controls/LockScreen/SlideLockScreen.xaml

Fixes #2763 by removing the tacky chevrons animation and adding a helper text below the Slide lockscreen. Also add our logo in the center to break negative space.

Replace visual design of SlideLockScreen.

---

WalletWasabi.Gui/Tabs/WalletManager/GenerateWalletSuccessViewModel.cs
WalletWasabi.Gui/Tabs/WalletManager/GenerateWalletView.xaml
WalletWasabi.Gui/Tabs/WalletManager/GenerateWalletViewModel.cs

Fixes #2777
This makes sure to generate the wallet file only after the user confirms that he has written the recovery words.
Please verify that there is nothing changed in the wallet generation process.
Note:
Should we rename `GenerateWalletViewModel.cs` to `StartWalletGenerationViewModel.cs` & `GenerateWalletSuccessViewModel.cs` to `GenerateWalletViewModel.cs`?
Should we change `base("Generate Wallet")` to `base("Start Wallet Generation")` & `base("Wallet Generated Successfully!")` to `base("Generate Wallet")`?

Edit generation wallet workflow

---

WalletWasabi.Gui/Controls/ExtendedTextBox.cs

Fixes #2771 
Context menu opening causes the textbox to loose focus, as the context menu gets focused.
Textbox detects when context menu closes, and refocuses itself.

refocus the textbox when context menu closes.

---

README.md
WalletWasabi.Backend/WalletWasabi.Backend.csproj
WalletWasabi.Documentation/BackendDeployment.md
WalletWasabi.Gui/WalletWasabi.Gui.csproj
WalletWasabi.Packager/WalletWasabi.Packager.csproj
WalletWasabi.Tests/WalletWasabi.Tests.csproj
WalletWasabi/WalletWasabi.csproj
azure-pipelines-linux.yml
azure-pipelines-osx.yml
azure-pipelines-windows.yml

Note, this needs to be deployed to the backend in the same way as the .NET Core 3.0 had to, due to it changing the release directory structure.
resolves https://github.com/zkSNACKs/WalletWasabi/issues/2821
Also note if this is not merged before the release, then the deterministic guide won't work, since there our instruction is "In order to reproduce Wasabi's builds you need Git, Windows 10 and the version of .NET Core SDK that was the most recent in the time of building the release."
https://docs.wasabiwallet.io/using-wasabi/DeterministicBuild.html

Update to .NET Core 3.1

---

README.md

Maybe this is not necessary but there is `azure-pipelines-osx.yml`, should we rename it as well?

Replace OSX by macOS

---

WalletWasabi.Gui/Program.cs

There is no need to sync back to anywhere on exit.
For me, on windows, this solved the issue.

Solve hang on filter crash

---

WalletWasabi.Gui/Tabs/SettingsViewModel.cs

Fixes: https://github.com/zkSNACKs/WalletWasabi/issues/2722
While the Tab is opening we are setting properties with loading and also LostFocus command called by Avalonia, those would trigger the Save function before we load the config.
Easy solution - optimized to easy review. 
Review: Hide whitespace changes!

Prevent Save before load

---

WalletWasabi.Packager/Program.cs

When I released I got Wasabi-1.1.10.0.dmg and so on. It looks awkward so I remove revision number if it is zero. 
Installed on macOS and on windows and looks fine. Old versions upgraded to new ones.

Adjust release filename 1.1.10.0 => 1.1.10

---

WalletWasabi.Gui/Program.cs

This is no longer needed, because Avalonia release has this fix in...
https://github.com/AvaloniaUI/Avalonia/blob/master/src/Windows/Avalonia.Win32/Win32Platform.cs#L89

remove avalonia hack

---

WalletWasabi/Nito/AsyncEx/AsyncMutex.cs

Reduce log rate in AsyncMutex class.
@MaxHillebrand reported:
However, it does take forever to close the wallet now, with this showing up hundreds of times in the logs.
DEBUG	AsyncMutex (413)	Waiting for: MatureIndex-76A7981.

Reduce log rate in AsyncMutex class.

---

WalletWasabi.Gui/Controls/WalletExplorer/CoinViewModel.cs
WalletWasabi.Tests/UnitTests/Transactions/TransactionProcessorTests.cs
WalletWasabi/Blockchain/TransactionOutputs/CoinsRegistry.cs

Fixes a problem tracking the clusters of same-scriptPubKey coins. This is necessary to fix #2903 but it is not enough because we are not refreshing the UI when a cluster changes. This means that internally the data structures are okay but the UI remains inconsistent. We can see the changes after closing and reopening the Send tab (or the CoinJoin tab).

Fix same scriptpubkey tracking

---

WalletWasabi/TorSocks5/TorProcessManager.cs

I found this while investigating #2289
```c#
var a = "ello";
var b = a.Insert(0, "H");
b
"Hello"
a
"ello"
```

Correct path correction

---

WalletWasabi.Backend/Controllers/ChaumianCoinJoinController.cs
WalletWasabi.Documentation/ClientDeployment.md
WalletWasabi.Gui/Global.cs
WalletWasabi.Tests/IntegrationTests/RegTests.cs
WalletWasabi.Tests/UnitTests/BitcoinCore/ConfigTests.cs
WalletWasabi.Tests/UnitTests/BitcoinCore/ConfigTranslatorTests.cs
WalletWasabi/BitcoinCore/Configuration/CoreConfig.cs
WalletWasabi/BitcoinCore/Configuration/CoreConfigTranslator.cs
WalletWasabi/BitcoinCore/Configuration/NetworkTranslator.cs
WalletWasabi/BitcoinCore/Configuration/Whitening/WhiteBind.cs
WalletWasabi/BitcoinCore/Configuration/Whitening/WhiteEntry.cs
WalletWasabi/BitcoinCore/Configuration/Whitening/WhiteList.cs
WalletWasabi/BitcoinCore/CoreNode.cs
WalletWasabi/BitcoinCore/IRPCClient.cs
WalletWasabi/BitcoinCore/Monitoring/RpcFeeProvider.cs
WalletWasabi/BitcoinCore/Processes/BitcoindRpcProcessBridge.cs
WalletWasabi/CoinJoin/Coordinator/Coordinator.cs
WalletWasabi/CoinJoin/Coordinator/Rounds/CoordinatorRound.cs
WalletWasabi/Extensions/RPCClientExtensions.cs
WalletWasabi/Helpers/Constants.cs
WalletWasabi/Microservices/Binaries/README.md
WalletWasabi/WalletWasabi.csproj

Closes https://github.com/zkSNACKs/WalletWasabi/pull/2885
Closes https://github.com/zkSNACKs/WalletWasabi/pull/2612
In this PR I want to add some small improvements for Bitcoin Core and I'm hoping to add these to the next backport release to reduce the Bitcoin Core related support requests.
- Make sure we don't ruin the config of Bitcoin Core 19 users who are using advanced whitebinded options, added here: https://github.com/bitcoin/bitcoin/pull/16248 - commit: https://github.com/zkSNACKs/WalletWasabi/pull/2899/commits/e92f75de3ffb747095fe67c2c34165a23d4947e3
- Improve start and stop mechanism. Wasabi gets stuck when we are quickly opening and closing it. This PR fixes that (in expense of throwing an exception.) https://github.com/zkSNACKs/WalletWasabi/pull/2899/commits/58f4b6512dcaf7c6caf …

Upgrade to Bitcoin Core 19 + Small Improvements

---

WalletWasabi/Blockchain/Keys/KeyManager.cs

This PR uses a faster mechanism for counting the largest sequence of consecutive key indexes. The new algorithm is just as performant as the previous one when there is no holes (or few holes) in the sequence and the MinGapLimit is small (for example 21). However, when the MinGapLimit is bigger, let say 100 or greater, and there are holes in the sequence the new algorithm is much faster.

Faster keys gap counting algorithm

---

WalletWasabi.Tests/IntegrationTests/RegTests.cs

This regtest failed, as the assertion expects a single coin to be spent, but it was two coin, since @lontivero implemented to spend all when coins are on the same address.

Fix BuildTransactionValidationsTestAsync

---

WalletWasabi.Gui/Tabs/WalletManager/LoadWalletViewModel.cs

Throws a better exception when hardware wallet has no fingerprint. 
Related: #2928

Throw exception when wallet has no fingerprint

---

WalletWasabi.Gui/Helpers/AvalonStudioShellExtensions.cs
WalletWasabi.Gui/Shell/Commands/ToolCommands.cs
WalletWasabi.Gui/Shell/Commands/WalletCommands.cs

This reverts commit 75c3b81dd65a3190f50889e059dd9b401d24b21b.
@nopara73 unfortunately this code is required. I move most of the code to the Shell, but allowed passing a lamda to control how the item is retreived.
We need to keep this code as is for now.
Part of my plan for future refactoring should eliminate this need in future, however I believe we need to keep this for now, otherwise might break stuff in subtle ways.

Revert "Remove unneeded code"

---

WalletWasabi.Gui/Controls/SortingArrow.cs

Current version has the arrow icons when sorting table columns the wrong way around.
When the list would go from big to small (descending) it would show the triangle with the small end at top and large end at bottom. This is the opposite to the presented data with big at top and small at bottom.

Correct sort order arrow icons

---

WalletWasabi/Helpers/EndPointParser.cs

There were a couple of checks for:
```c#
ushort.TryParse(portString, out ushort p) && p >= IPEndPoint.MinPort && p <= IPEndPoint.MaxPort
```
Refactored into its own method to hopefully improve readability/remove duplication. I also refactored an if/else into a switch statement which should be a bit more efficient.
Prior to merge, I did have a question why we essentially perform the same checks twice. `ushort.TryParse(portString, out ushort p)` would be the same as `p >= IPEndPoint.MinPort && p <= IPEndPoint.MaxPort` in regards to min/max values.
The `ushort` min/max is 0/65535 and `IPEndPoint.MinPort` is 0 and `IPEndPoint.MaxPort` is 65535. Is there a reason behind this?

Refactor EndPointParser to remove some code duplication

---

WalletWasabi/Services/WalletService.cs

The use of `walletName` seems to have been removed in https://github.com/zkSNACKs/WalletWasabi/commit/edf47d67425643b2ff422e627f52fbc50366f4e7.

Removed unused variable/block of code in WalletService

---

WalletWasabi/BitcoinCore/Configuration/CoreConfigTranslator.cs
WalletWasabi/BitcoinCore/CoreNode.cs

Since it's an invalid Bitcoin Core configuration option. It will always default to localhost, even if it's specified, so picking up the specified "rpchost" in Wasabi doesn't make sense, rather we should default to localhost, too.
Closes https://github.com/zkSNACKs/WalletWasabi/issues/2955
Possibly it was removed here? https://github.com/bitcoin/bitcoin/pull/9929
But searching Core's repo I'm not sure it ever existed.

Remove "rpchost"

---

WalletWasabi.Gui/Controls/WalletExplorer/WalletViewModel.cs
WalletWasabi.Gui/MainWindow.xaml.cs
WalletWasabi.Gui/Tabs/WalletManager/LoadWalletViewModel.cs
WalletWasabi.Gui/UiConfig.cs

Closes #1490
If the user closes Wasabi with either `Send` or `Receive` or `History` or `CoinJoin` or `Build Transaction` as the last active tab, Wasabi will display that tab in the next run.
If the user closes Wasabi with any other tab, Wasabi will display the `CoinJoin` tab in the next run.

Open last active tab

---

.editorconfig

This is extremely annoying. I start typing `var foo = 3;` and it shows up as an error until I use foo.

Remove rule to discard unnecessary assignment

---

WalletWasabi.Tests/IntegrationTests/ExternalApiTests.cs
WalletWasabi/WebClients/BlockchainInfo/BlockchainInfoExchangeRateProvider.cs
WalletWasabi/WebClients/Coinbase/CoinbaseExchangeRateProvider.cs
WalletWasabi/WebClients/ExchangeRateProviders.cs
WalletWasabi/WebClients/Gemini/GeminiExchangeRateProvider.cs
WalletWasabi/WebClients/ItBit/ItBitExchangeRateProvider.cs
WalletWasabi/WebClients/SmartBit/SmartBitClient.cs

Related https://github.com/zkSNACKs/WalletWasabi/issues/3017
I was researching the problem with "IOException: too many open files" and nothing seems to point to swagger. Most of the people that suffered this problem point out to this article: https://medium.com/@mshanak/soved-dotnet-core-too-many-open-files-in-system-when-using-postgress-with-entity-framework-c6e30eeff6d1 which in its point 2.2 talks about `HttpClient`.
I've found this forum where the problem was solved by disposing the `HttpWebResponse` instances:
https://forums.servicestack.net/t/servicestack-on-kestrel-holds-open-files/5615 so, I am disposing all the `IDisposable` instances returned by the `HttpClient`.
Here is the controversial part. The documentation says that the `HttpClient` class was designed with the idea that an …

Use using statement for IDisposable http objects

---

WalletWasabi.Documentation/BackendDeployment.md

Looks like @osagga was experimenting with values of 1000 so doubling 64 should be fine: https://github.com/bitpay/bitcore-node/issues/463#issuecomment-413379440
Reason: 
```
2020-02-07T11:37:53Z WARNING: request rejected because http work queue depth exceeded, it can be increased with the -rpcworkqueue= setting
2020-02-07T11:37:53Z WARNING: request rejected because http work queue depth exceeded, it can be increased with the -rpcworkqueue= setting
```

Double rpcworkqueue

---

WalletWasabi.Gui/Rpc/WasabiJsonRpcService.cs

This PR allows to build signed transactions using rpc but without sending. The built transaction can be broadcasted using the Wasabi transaction broadcaster or any other service. 
Closes https://github.com/zkSNACKs/WalletWasabi/issues/2991
```sh
curl -s --data-binary '{"jsonrpc":"2.0","id":"1","method":"buildtransaction", "p
arams": { "payments":[ {"sendto": "tb1qgvnht40a08gumw32kp05hs8mny954hp2snhxcz", "amount": 5000, "label": "Davi
d2 } ], "coins":[{"transactionid":"d279916a9ea2679e6672839862e269c271fe4eed96f00e08aae3b82f20d469bd", "index"
:0}], "feeTarget":2, password:null }}' http://127.0.0.1:37128/ | jq                                           
{                                                                                                             
"jsonrpc": "2.0", …
```

Add build rpc call

---

WalletWasabi.Backend/Controllers/ChaumianCoinJoinController.cs
WalletWasabi.Gui/Helpers/FileHelpers.cs
WalletWasabi.Gui/Models/StatusBarStatuses/StatusType.cs
WalletWasabi.Gui/Tabs/WalletManager/LoadWalletViewModel.cs
WalletWasabi.Tests/IntegrationTests/RegTests.cs
WalletWasabi.Tests/UnitTests/Transactions/TransactionFactoryTests.cs
WalletWasabi.Tests/UnitTests/Transactions/TransactionProcessorTests.cs
WalletWasabi/Blockchain/TransactionProcessing/TransactionProcessor.cs
WalletWasabi/Blockchain/Transactions/SmartTransaction.cs
WalletWasabi/CoinJoin/Client/Clients/CoinJoinClient.cs
WalletWasabi/CoinJoin/Coordinator/Rounds/CoordinatorRound.cs
WalletWasabi/Gma/QrCodeNet/Encoding/EncodingRegion/FormatInformation.cs
WalletWasabi/WebClients/Wasabi/WasabiClient.cs

This is the final round of Typo fixes in these Series.
Some background : i used a little bit of bash code
and ispell to find potential typos , and then manually
reviewed the Output and fixed where needed .
For instance:
( find -iname "*.md" -exec cat {} \; ) | ispell -a | grep ^\& | cut -d " " -f 1-2 | sort -u -f
It was the first time I tried something like this and
I'm pretty happy with the results . I was able to find
and fix around 40 typos in the complete Series :)
I think a big Thanks to ispell is appropriate here !

Final round of Typo fixes

---

WalletWasabi.Backend/Controllers/BlockchainController.cs
WalletWasabi.Tests/IntegrationTests/RegTests.cs
WalletWasabi/Backend/Models/Responses/StatusResponse.cs
WalletWasabi/Blockchain/BlockFilters/IndexBuilderService.cs

Recreating this: https://github.com/zkSNACKs/WalletWasabi/pull/2425
The status of filter generation on the Backend server is fundamental for clients without a full node. If the filter creation stops for some reason, the wallet will not refresh the statuses related to blockchain. 
This PR created an API request which can be monitored with our monitoring system UptimeRobot which can detect the existence of some keywords in responses. 
1. Merge this PR into the master.
2. Deploy it on Testnet/Mainnet backend.
3. Add the monitor to UptimeRobot. 
As a result, we will get notifications on our maintenance channels, so actions can be made.

Add status request API - for filters 

---

WalletWasabi.Tests/UnitTests/Transactions/TransactionProcessorTests.cs
WalletWasabi/Blockchain/TransactionProcessing/TransactionProcessor.cs

In the `TransactionProcessorTests` only the `Process` function with one transaction is being tested. However if multiple transactions are feeded into the `Process`, it is not tested. This is a test that brings out an issue with PR https://github.com/zkSNACKs/WalletWasabi/pull/3074.

Add IgnoreDoubleSpendMultiTxAsync

---

WalletWasabi.Gui/Controls/WalletExplorer/CoinListView.xaml

Enable item virtualization on `CoinListView`'s `ListBox` to have a smoother scroll and less memory usage.
fixes #2614

Enable CoinListView Item Virtualization

---

WalletWasabi.Backend/Controllers/BlockchainController.cs

Alternative to https://github.com/zkSNACKs/WalletWasabi/pull/3081
closes https://github.com/zkSNACKs/WalletWasabi/pull/3081
probably fixes https://github.com/zkSNACKs/WalletWasabi/issues/3039
Based on my tests whenall will wait until all the tasks finished and throws the first exception. While our current foreach will throw the first exception and abandon the remaining tasks.  
Task waitall would block and throw an aggregate exception.
I also tried to catch unobserved exceptions but my small console app doesn't catch any, not even for the first foreach solution. So I'm not 100% sure this fixes the issue, but if it does it does it elegantly.

Use Task.WhenAll

---

WalletWasabi.Backend/wwwroot/index.html

The `free and open source` block on the website linked to the 10 commandments on verifying the PGP signatures. This is not really important in the context of why wasabi is free software. Further, since we changed the 10 commandments, this sub link is broken.
Thus this changes the hyperlink to the FAQ where it is beautifully written [why Wasabi is open source](https://docs.wasabiwallet.io/FAQ/FAQ-Introduction.html#why-is-wasabi-libre-and-open-source-software) - in my opinion a much better fit for this block.
It should be a trivial merge.

[WEBSITE] change broken link

---

azure-pipelines-osx.yml

Do not merge!
CI on macOS was failed so I did https://github.com/zkSNACKs/WalletWasabi/commit/005f5f516f441d517e66a9654e9d9958463fa4ab. There are already reports on that it looks like a bug in Azure.
https://developercommunity.visualstudio.com/content/problem/922217/pipeline-task-usedotnet.html
If it is fixed by MS this should be merged to let Azure use the newest version.

Revert buggy Azure CI fix

---

WalletWasabi.Gui/CommandLine/Daemon.cs
WalletWasabi.Gui/Controls/WalletExplorer/CoinJoinTabViewModel.cs
WalletWasabi.Gui/Controls/WalletExplorer/CoinListViewModel.cs
WalletWasabi.Gui/Controls/WalletExplorer/CoinViewModel.cs
WalletWasabi.Gui/Controls/WalletExplorer/SendControlViewModel.cs
WalletWasabi.Gui/Converters/PhaseColorConverter.cs
WalletWasabi.Gui/Dialogs/CannotCloseDialogViewModel.cs
WalletWasabi.Gui/Global.cs
WalletWasabi.Gui/MainWindow.xaml.cs
WalletWasabi.Gui/Rpc/WasabiJsonRpcService.cs
WalletWasabi.Tests/IntegrationTests/P2pTests.cs
WalletWasabi.Tests/IntegrationTests/RegTests.cs
WalletWasabi/Blockchain/TransactionBroadcasting/TransactionBroadcaster.cs
WalletWasabi/CoinJoin/Client/Clients/CoinJoinClient.cs
WalletWasabi/CoinJoin/Client/CoinJoinProcessor.cs
WalletWasabi/Services/WalletService.cs

In this PR the coinjoin client become implicitly wallet dependent. A better approach than creating "DefaultChaumianClient" and such so it won't need to be managed explicitly: https://github.com/zkSNACKs/WalletWasabi/pull/3104
Closes https://github.com/zkSNACKs/WalletWasabi/pull/3104

Place CoinJoin client to WalletService

---

WalletWasabi.Tests/IntegrationTests/RegTests.cs
WalletWasabi.Tests/UnitTests/SmartCoinTests.cs
WalletWasabi.Tests/UnitTests/Transactions/TransactionFactoryTests.cs
WalletWasabi/Blockchain/TransactionOutputs/SmartCoin.cs
WalletWasabi/Blockchain/TransactionProcessing/TransactionProcessor.cs
WalletWasabi/Blockchain/Transactions/TransactionFactory.cs
WalletWasabi/CoinJoin/Client/Rounds/ClientState.cs
WalletWasabi/Services/WalletService.cs

This is a break down of PR #3105 
- master: 1:04
- this branch: 0:53
By flipping the cycles it is possible to do less search in our coins.
After merging PR https://github.com/zkSNACKs/WalletWasabi/pull/3107 to master and adding the second improvement to this branch, it ended up being 23s, wich is 2.7x faster than what it was after https://github.com/zkSNACKs/WalletWasabi/pull/3084 and 7.56 times faster than what it was when @NicolasDorier created https://github.com/zkSNACKs/WalletWasabi/issues/3073 as the previous PR resulted in 2.8x speed increase: https://github.com/zkSNACKs/WalletWasabi/pull/3084#issuecomment-586710870
This closes https://github.com/zkSNACKs/WalletWasabi/issues/3073 and closes https://github.com/zkSNACKs/WalletWasabi/pull/3105

Improve Load Speed: Input Iteration

---

WalletWasabi.Gui/Global.cs

Fix misspelling of the word "replaceable" (was "replacable")

Trivial: Fix misspelling

---

.editorconfig
WalletWasabi.Tests/UnitTests/Hwi/HwiProcessBridgeMock.cs
WalletWasabi.Tests/UnitTests/IoTests.cs
WalletWasabi.Tests/UnitTests/Transactions/AllTransactionStoreTests.cs
WalletWasabi/Helpers/IoHelpers.cs
WalletWasabi/Mono/StringCoda.cs

To be aligned with StyleCop's rule `ConstFieldNamesMustBeginWithUpperCaseLetter`
https://github.com/zkSNACKs/WalletWasabi/blob/master/Settings.StyleCop#L37-L39

Add naming rule for local const (PascalCase)

---

WalletWasabi.Gui/Controls/WalletExplorer/CoinJoinTabViewModel.cs
WalletWasabi.Gui/Controls/WalletExplorer/HistoryTabViewModel.cs
WalletWasabi.Gui/Controls/WalletExplorer/PinPadViewModel.cs
WalletWasabi.Gui/Controls/WalletExplorer/ReceiveTabViewModel.cs
WalletWasabi.Gui/Controls/WalletExplorer/SendControlViewModel.cs
WalletWasabi.Gui/Controls/WalletExplorer/TransactionBroadcasterViewModel.cs
WalletWasabi.Gui/Controls/WalletExplorer/TransactionViewerViewModel.cs
WalletWasabi.Gui/Controls/WalletExplorer/WalletInfoViewModel.cs
WalletWasabi.Gui/Tabs/SettingsViewModel.cs
WalletWasabi.Gui/ViewModels/TextResourceViewModelBase.cs
WalletWasabi.Gui/ViewModels/WasabiDocumentTabViewModel.cs

Currently we have almost every viewmodel implementing its own Disposables property, this just moves that to the base class.
The advantages are:
- less repeated code
- developer cant make a mistake by repeating code in incorrect way.
- no longer implemented on classes that were not using this.
- cleaner code, simpler interface (onopen onclose)
Follow up PR that solves the 7 CodeFactor issues here: 
https://github.com/zkSNACKs/WalletWasabi/pull/3169
will make it too hard to review otherwise.

Wasabi document tab vm implements disposables for us

---

WalletWasabi.Gui/Controls/WalletExplorer/CoinJoinTabViewModel.cs
WalletWasabi.Gui/Controls/WalletExplorer/ReceiveTabViewModel.cs
WalletWasabi.Gui/Controls/WalletExplorer/SendControlViewModel.cs
WalletWasabi.Gui/Controls/WalletExplorer/WalletInfoViewModel.cs

https://github.com/zkSNACKs/WalletWasabi/pull/3165 ruined UI at where IsWatchOnly and/or IsHardwareWallet were used.

Fix IsWatchOnly / IsHardwareWallet xamls

---

WalletWasabi.Tests/UnitTests/KeyManagementTests.cs
WalletWasabi/Blockchain/Keys/KeyManager.cs

Rational: If we will add a feature to hide (lock) addresses, then we need to also count the locked external keys to get the consecutive unused key.
Fixes #3131
Should the `CountConsecutiveCleanKeys` method be renamed to `CountConsecutiveUnusedKeys`?
Please check if this has any side effects, like when there should always be 21 change addresses or something like that.

Count locked external keys to get consecutive unused keys

---

WalletWasabi.Tests/IntegrationTests/LiveServerTests.cs
WalletWasabi.Tests/UnitTests/LegalTests.cs
WalletWasabi/Legal/LegalDocuments.cs

This is a breakdown to https://github.com/zkSNACKs/WalletWasabi/pull/3145
With the exception of `FetchLatestAsync` method all the code is added to the `LegalDocuments` class with many unit tests.

Add LegalDocuments class code with unit tests

---

WalletWasabi.Gui/ViewModels/StatusBarViewModel.cs

In some cases the default value is being checked, which is 0. Since we're never downgrading legal docs remotely, a `<` is a better check than a `!=` and also solves this race condition.

Fix race condition on legal version check

---

WalletWasabi.Gui/CommandLine/Daemon.cs

If the user specifies `--mixall` to the daemon, then it should go through all the coins exactly once and not keep re-enqueueing them forever, which is the case when both `--mixall` AND `--keepalive` is specified.

Fix bug: mixall + keepalive

---

WalletWasabi.Gui/Dialogs/CannotCloseDialogView.xaml
WalletWasabi.Gui/Global.cs
WalletWasabi.Gui/Tabs/WalletManager/LoadWalletViewModel.cs
WalletWasabi/CoinJoin/Client/Clients/CoinJoinClient.cs
WalletWasabi/Wallets/WalletManager.cs

I somehow get in the unfortunate situation on RegTest that I could not exit from Wasabi. 
1. I was continuously getting the notification that Coin cannot be dequeued
2. The backend was disconnected so there was no way successful dequeue. 
The cancel button was hidden behind the notifications so I moved it one the left. 
I added the checking of backend status before trying to dequeue. 
Something to consider: after 1 minute of trying to add a button force exit which will exit Wasabi anyway without dequeuing. 
UPDATE!
A force quit button is not required. If the backend is not connected the user doesn't have to wait 6 minutes it will quit immediately.

Improve the dequeuing of coins on exit

---

WalletWasabi.Backend/Controllers/BlockchainController.cs
WalletWasabi/Backend/Models/Responses/StatusResponse.cs
WalletWasabi/CoinJoin/Coordinator/Coordinator.cs

This PR is for adding new data into our existing status request query. 
I tried to do some RPC magic but getting the time/height of the last CoinJoin tx is not so easy. 
Concept review.

Add CoinJoin status monitor

---

WalletWasabi.Gui/Controls/WalletExplorer/SendControlViewModel.cs

When the user inserts the same address and custom-change-address, then he changes on of them to another address, only the one which was changed updates the validation around the control. Now with this PR both validation will be updated. 
Related: https://github.com/zkSNACKs/WalletWasabi/issues/3223

Trigger both validation on Address or CustomChangeAddress

---

WalletWasabi.Gui/Controls/WalletExplorer/SendControlViewModel.cs
WalletWasabi.Gui/Converters/UsdExchangeRateAmountToolTipConverter.cs

On two occations, the USD price of bitcoin is shown as `BTC/USD`, when the unit should be `USD/BTC`. This pull request replaces these two instances in the code with `USD/BTC`.
I am aware that there are others working on making fee display more flexible, but this seems to be a simple enough change to be included without bigger repercussions.

fix exchange rate unit: USD/BTC

---

WalletWasabi/Wallets/WalletManager.cs

It is easier for the UI to subscribe to only one event in WalletManager and follow the status changes of the wallets there.

Add WalletStateChanged event to WalletManager

---

WalletWasabi.Gui/Config.cs

The last `return TargetPrivacy.None;` can never be reached, and the
`if (MixUntilAnonymitySet > PrivacyLevelFine)` should have been
`if (MixUntilAnonymitySet > PrivacyLevelStrong)` but anyway.

Remove unreachable case

---

WalletWasabi.Tests/RegressionTests/SendTests.cs

For some reason we start the wallet twice which makes no sense and throws an exception. We were able to get away with this bug before but now with @molnard we're throwing exceptions if the things aren't called in the right time.

Fix regtest

---

WalletWasabi/TorSocks5/TorProcessManager.cs

@MaxHillebrand noted that "30 users have reported issues with Tor from the last release, when we updated Tor." He also reported that deleting the tor data dir fixes this issue.
This PR asks Tor to use the `tordata` directory under Wasabi's datadir, so it fixes the issue.

Specify Tor data dir arg to be our own directory

---

WalletWasabi.Gui/Controls/WalletExplorer/WalletExplorerView.xaml

Builds upon #3345 and #3387; This PR aligns the elements of `TreeViewItem`s in the sidebar. It also adjusts the height to be uniform to all the sidebar's items.
cc: @molnard @danwalmsley

Align WalletExplorer's Header text & Icons

---

WalletWasabi.Gui/Tabs/WalletManager/LoadWallets/LoadWalletView.xaml

I don't know if this is the best way to do this, but this would allow the user to double click an item in the Load Wallet tab outside the text.

Fix double click outside text (Load Wallet tab)

---

WalletWasabi.Gui/Tabs/WalletManager/HardwareWallets/ConnectHardwareWalletViewModel.cs
WalletWasabi.Gui/Tabs/WalletManager/LoadWallets/LoadWalletViewModel.cs
WalletWasabi.Gui/Tabs/WalletManager/RecoverWallets/RecoverWalletViewModel.cs
WalletWasabi.Gui/Tabs/WalletManager/WalletManagerViewModel.cs

I had a small bug when trying to load my second hardware wallet. The load button was disabled. 
So I refactored it according to https://github.com/zkSNACKs/WalletWasabi/pull/3400
Now it is working fine. 
I was trying to reduce the code duplication among `ConnectHardwareWalletViewModel` and `LoadWalletViewModel` but it ended up changing our current user workflow - so I did not do that. My idea was that instead of loading the wallet you can just add at ConnectHardwareWalletViewModel and then it will change to LoadWalletViewModel and the selection. We can talk about this on dev call. 
Another idea was, which I do not prefer is to call LoadWalletViewModel.LoadWalletAsync() from ConnectHardwareWalletViewModel but it is a hacky solution. ViewModels should not call each others methods directly.

Fix Hardware wallet loading

---

WalletWasabi.Gui/Controls/WalletExplorer/ClosedWalletViewModel.cs
WalletWasabi.Gui/Tabs/WalletManager/HardwareWallets/ConnectHardwareWalletViewModel.cs
WalletWasabi.Gui/Tabs/WalletManager/LoadWallets/LoadWalletViewModel.cs
WalletWasabi/Stores/IndexStore.cs
WalletWasabi/Wallets/Wallet.cs

Fixes https://github.com/zkSNACKs/WalletWasabi/issues/3403
The problem was caused by this line:
https://github.com/molnard/WalletWasabi/blob/3e83310a20f513877b6b34a2b359b158a1e40313/WalletWasabi/Wallets/Wallet.cs#L654
Added CancellationToken to more places and handle the logs correctly.

Fix enless loop when exiting during filter processing

---

WalletWasabi.Gui/Controls/WalletExplorer/WalletExplorerViewModel.cs
WalletWasabi.Gui/WalletWasabi.Gui.csproj

originally reported by @MaxHillebrand 
I was able to code a reliable repro and caught the same bug Max had.
Its caused because we are binding SelectedItem on the Shell and calling AddOrSelectDocument in the handler for that.
Calling AddOrSelectDocument can trigger SelectedItem to change before its finished. Meaning we were calling AddOrSelectDocument before the item was added.
It can only happen when the main window is closing.
This fixes in 2 ways:
1) protect against recursion in the viewmodel with a flag.
2) add fixes to the shell to make account for this scenario. (https://github.com/VitalElement/AvalonStudio.Shell/commit/66d4f5e6c1ac06c5d9b79d5f6f448466f3bfa778)
Updates: Avalonia and AvalonStudio.Shell to 0.9.6 (only fixes this)

Fixes duplicate key exception

---

WalletWasabi/Wallets/Wallet.cs

Fixes https://github.com/zkSNACKs/WalletWasabi/issues/3415
I moved the code to a new method in order to do not create additional complexity in the already complex method.
The pattern is:
* If the block file is already there then there is nothing to do (some other wallet downloaded the block first and saved it)
* If the block file does not exist then we lock the block folder to save the file.
* It can be possible that immediately after checking the existence of the file and before the lock, other task creates the file so, we have to check for the file again inside the lock. If the file is not there then we can save the block safely.

Do not overwrite existing block

---

WalletWasabi.Tests/UnitTests/Transactions/TransactionProcessorTests.cs
WalletWasabi/Blockchain/TransactionProcessing/TransactionProcessor.cs

During the transaction processing those keys that received dust were not marked as `Used` (they remained as `Clean`), for this reason the address is not removed from the `Receive` tab what make it possible to reuse.

Mark keys with dust as used

---

WalletWasabi.Gui/Controls/WalletExplorer/WalletExplorerViewModel.cs

Fixes #3405
This would allow the user to enable LWM before loading the wallet. https://github.com/zkSNACKs/WalletWasabi/issues/3405#issuecomment-608413045

Enable LWM button (Wallet Explorer)

---

WalletWasabi/CoinJoin/Coordinator/Rounds/CoordinatorRound.cs

As a test we are lowering the fees. As discussed in the management meeting. This avoids overpaying. It's a bit worse for privacy, but prevents edge cases when user would overpay.  
For the record we officially advertise 1%.

Lower max coord fee from 0.7% to 0.3%

---

WalletWasabi.Tests/RegressionTests/BackendTests.cs
WalletWasabi.Tests/RegressionTests/WalletTests.cs
WalletWasabi/WalletWasabi.csproj

NBitcoin doesn't have the Schnorr Blinding Signature algorithms we use in Wasabi. Those algorithms were move to Wasabi and it was removed from NBitcoin.
Note this version allows us to create transactions with smaller amounts (greater than dust) than before and the dust protection mechanism is aware of the fact that the transaction input is segwit.

Update NBitcoin to 5.0.28

---

WalletWasabi.Gui/Global.cs

Fixes https://github.com/zkSNACKs/WalletWasabi/issues/3479
It log the reason why the rpc server cannot start (most of the times is `port already in use` or `permission denied`). Also, it sets the `RpcServer` variable to `null`, in that way wasabi does not try to dispose it.

Log failing attempts to start rpc server

---

WalletWasabi.Gui/Global.cs
WalletWasabi/Wallets/P2pBlockProvider.cs

Sometimes when a user has an ugly internet connection or has to synchronize with the network by downloading tens of blocks the process fails and the nodes are disconnected until we reach zero peers. 
This PR is to prevent peers going back to 0 by do not disconnect nodes when there are less than 2 connected peers. We only disconnect peers when there are more than two or when the node misbehaves by providing invalid blocks
Additionally the maximum number of peers connected is increase from 8 to 12.
NBitcoin makes its best to prevent sybil attacks at a network level, that can be change if needed for TestNet.

Prevent 0 peers and increase max connections

---

WalletWasabi.Gui/Controls/WalletExplorer/SendControlViewModel.cs
WalletWasabi.Gui/Controls/WalletExplorer/SendTabViewModel.cs
WalletWasabi.Gui/Helpers/NotificationHelpers.cs

- I removed one extra catch clause.
- I fixed the notification title, sometimes it displayed: "Error - " Now it will be only "Error"
- Added WalletName to the error notification when sending. Sometimes it takes several seconds to get the error and the user can navigate elsewhere meanwhile. Better to clarify which send was erroneous.

Better exception handling on SendTab

---

WalletWasabi.Gui/Rpc/WasabiJsonRpcService.cs
WalletWasabi/Wallets/WalletManager.cs

Fixes an ugly warning that happens when you select a wallet using the rpc method. It also deletes a unused method.

Fix exception warning while using rpc

---

Settings.StyleCop
WalletWasabi.Gui/Rpc/JsonRpcRequest.cs
WalletWasabi/Blockchain/Analysis/FeesEstimation/AllFeeEstimate.cs
WalletWasabi/Blockchain/TransactionProcessing/ProcessedResult.cs
WalletWasabi/CoinJoin/Client/Rounds/ClientRoundRegistration.cs
WalletWasabi/CoinJoin/Common/Models/RoundStateResponse.cs
WalletWasabi/Interfaces/IConfig.cs
WalletWasabi/Io/DigestableSafeMutexIoManager.cs
WalletWasabi/Logging/Logger.cs
WalletWasabi/Nito/AsyncEx/AsyncMutex.cs
WalletWasabi/Nito/AsyncEx/IAsyncWaitQueue.cs
WalletWasabi/Services/WasabiSynchronizer.cs

https://documentation.help/StyleCop/SA1623.html
> The property’s summary text must begin with wording describing the types of accessors exposed within the property. If the property contains only a get accessor, the summary must begin with the word “Gets”. If the property contains only a set accessor, the summary must begin with the word “Sets”. If the property exposes both a get and set accessor, the summary text must begin with “Gets or sets”.

Enable PropertySummaryDocumentationMustMatchAccessors

---

WalletWasabi.Tests/UnitTests/JsonConvertersTest/UnblindedSignatureTests.cs
WalletWasabi/Crypto/UnblindedSignature.cs

Applied our coding conventions.
Run the `UnblindedSignatureTests` and they both pass.
Also I corrected `UnblindedSignatureTests` name space.

Refactor UnblindedSignature class

---

Settings.StyleCop

https://documentation.help/StyleCop/SA1627.html
> A violation of this rule occurs when the documentation header for an element contains an empty tag.

Enable DocumentationTextMustNotBeEmpty

---

.coverage.sh

https://www.codefactor.io/repository/github/zksnacks/walletwasabi/issues?category=Maintainability&groupId=2412
It is the first time I see that, maybe adding `#!/bin/bash` will fix that.
https://github.com/koalaman/shellcheck/wiki/SC2148

Add a shebang line to the top of .coverage.sh file

---

WalletWasabi.Gui/Controls/WalletExplorer/SendTabViewModel.cs

The new Payjoin spec is not guaranteed to work with BIP79 so I would remove its BIP21 key as a signal for payjoin.

Remove BIP21 "bpu" payjoin detection

---

WalletWasabi.Gui/CommandLine/PasswordFinderCommand.cs

Currently if you run `wassabeed.exe findpassword --wallet:walletname` on Windows the `numbers` argument is false, it should be true by default.
Same for `symbols` argument.

Password finder

---

WalletWasabi.Backend/Controllers/ChaumianCoinJoinController.cs

- There is less coinbase utxos than utxos with confirmations <= 100, and more importantly there is very few coinbase utxos that are coinjoined, so it makes sense to check if IsCoinBase first when checking if utxo is immature.
This is to slightly optimize the code.

Check if IsCoinBase first when checking if utxo is immature

---

WalletWasabi.Gui/Controls/WalletExplorer/CoinJoinTabView.xaml
WalletWasabi.Gui/Controls/WalletExplorer/WalletViewModel.cs

Partially addresses #3653
> 1. It is not hidden because, at that time when we integrated the HWWs, we believed that at some point it will be supported. Now I am more on the site it will be never supported. So your suggestion makes sense.

Hide CoinJoin tab if watch only wallet

---

WalletWasabi.Backend/Controllers/BlockchainController.cs
WalletWasabi/Blockchain/BlockFilters/IndexBuilderService.cs

Currently, we are getting false alarms in our monitoring system, about filter generation. Now the monitor checks if the last filter is created for one of the last two blocks on the blockchain. This is not always true especially on TestNet where the backend is slower and there are mining bursts. 
Adding a time frame for the filter creation would solve this. 
So basically the monitor will fail only if both conditions fail:
- The last filter was generated more than 20 minutes ago.
- The last filter was not generated either of the last two blocks on the blockchain.
This will also slightly optimize the RPC usage. 
I checked on slack and the longest false filter downtime was 15 minutes.

Dismiss false alarms on Backend about filter generation

---

WalletWasabi.Gui/Tabs/WalletManager/LoadWallets/LoadWalletViewModel.cs
WalletWasabi.Gui/Tabs/WalletManager/WalletManagerViewModel.cs

This PR should not change anything from the UI side. I moved the auto close logic into Wallet Manager, so now it is closing itself instead of closed by an external object.

Auto close wallet manager in a better place.

---

azure-pipelines-linux.yml
azure-pipelines-osx.yml
azure-pipelines-windows.yml

This improves logging for CI tests in Azure Pipelines by adding two options to the 'Test Debug' task. 
1. `--logger "console;verbosity=detailed"` Currently, our logs only show failed tests. Adding this option shows successful tests, how long they took to complete, and at what time they completed:
2. `--blame` 
> Runs the tests in blame mode. This option is helpful in isolating problematic tests that cause the test host to crash. When a crash is detected, it creates an sequence file in TestResults/<Guid>/<Guid>_Sequence.xml that captures the order of tests that were run before the crash.
These two options may be helpful in providing clues for solving some of the more difficult CI issues like #3660, without adding much complexity or causing the tests to run much slower.

Add verbose console logging for CI tests

---

WalletWasabi.Gui/CommandLine/Daemon.cs
WalletWasabi.Gui/CommandLine/MixerCommand.cs
WalletWasabi.Gui/Global.cs
WalletWasabi.Gui/Program.cs

This PR is moving the "dirty" `Environment.Exit` to the topmost position where it is required. 
The `Environment.Exit` is a walkaround fix because the AppMainAsync method cannot throw exceptions as it is crashing Avalonia. With this, I could clean out the daemon code too - so the goal to call `Environment.Exit` only if required is reached.

Call Environment.Exit at a better place

---

WalletWasabi.Backend/wwwroot/index.html

This makes the link of `press kit` the direct download link. when this is clicked, the download starts immediately. 
https://github.com/zkSNACKs/Meta/raw/master/WasabiPressKit.zip

[WEBSITE] Make presskit link the direct download

---

CodeMaid.config

If you use Visual Studio whenever you build the solution you get an extra build window which is annoying, this disables that.

Disable CodeMaid's Build Progress Tool Window

---

WalletWasabi/CoinJoin/Coordinator/Rounds/CoordinatorRound.cs

Recently we added the functionality that in case of mempool-too-long dis-acceptance backend accepts only confirmed inputs. 
https://github.com/zkSNACKs/WalletWasabi/pull/3670
In the case of coinjoin mempool dis-acceptance, many clients get banned and @lontivero figured out that the reason was that the Unsigned CoinJoin was missing some outputs so the clients did not sign the tx. 
After some hours of investigation, I figured out that:
**The removed clients could still post their outputs into the round as they have a valid signature to do so. So the valid clients could not post their outputs in time. The unsigned tx constructed but some inputs were missing.** 
To dismiss this DoS attack possibility, I added the following feature. If the backend needs to remove some Alices after the phase of …

Fix bug of banning clients in case of mempool dis-acceptance

---

Settings.StyleCop

https://documentation.help/StyleCop/SA1206.html
IMO this rule is good to add.

Enable DeclarationKeywordsMustFollowOrder

---

WalletWasabi.Gui/Rpc/WasabiJsonRpcService.cs
WalletWasabi/Blockchain/Transactions/TransactionHistoryBuilder.cs
WalletWasabi/Blockchain/Transactions/TransactionSummary.cs

This PR adds a new boolean fields `islikelycoinjoin` to the result of RPC `gethistory` method.
```
$ curl -s --data-binary '{"jsonrpc":"2.0","id":"1","method":"gethistory"}' http:/127.0.0.1:37128 | jq '.result[0]'
{
"datetime": "2019-01-15T21:27:36+00:00",
"height": 102,
"amount": 5000000000,
"label": "Walter",
"tx": "bb51003b65642a31337b28ad1bb118ebd923c6f8a972209805d10bcfd0b9210a",
"islikelycoinjoin": false
}
```

Return IsLikelyCoinJoin as part of gethistory

---

WalletWasabi.Gui/Rpc/JsonRpcMethodMetadata.cs
WalletWasabi.Gui/Rpc/JsonRpcRequest.cs
WalletWasabi.Gui/Rpc/JsonRpcRequestHandler.cs
WalletWasabi.Gui/Rpc/JsonRpcService.cs
WalletWasabi.Tests/RpcTests.cs

Current rpc methods' optional parameters are settled to `null` ignoring the default value assigned by the developer, for that reason optional parameters only work for reference values.
This PR sets the optional parameters correctly. Additionally it supports batching requests. This is good in many situations, for example: You can select the wallet to use and perform the desired operation in an atomic operation. You can also simplify repetitive request.
This PR should be review commit by commit.

RPC optional parameters and batching capability

---

WalletWasabi.Gui/Global.cs
WalletWasabi.Tests/IntegrationTests/P2pTests.cs
WalletWasabi.Tests/RegressionTests/Common.cs
WalletWasabi.Tests/UnitTests/BitcoinCore/P2pBasedTests.cs
WalletWasabi/Stores/BitcoinStore.cs

This PR moves dependencies of `BitcoinStore` class to its constructor. It paves the path for #3372, for example.
Review is very easy when reviewing commits separately. It's only moving of code basically.
You may not like how many parameters the new `BitcoinStore` has. I don't like it either. The point of this refactoring is actually to show that the class depends on *too much* dependencies. Over time it will go down again with more refactoring PRs. Unfortunately, it's not possible to solve this in one go..

BitcoinStore: Improve DI

---

WalletWasabi.Packager/Program.cs

Only the package for the "other" Linux distributions has the prefix `WasabiLinux` while for Windows, macOS, Debian/Ubuntu packages they have the prefix `Wasabi`:
I tired to check if there is a reason for that in the [code](https://github.com/zkSNACKs/WalletWasabi/blob/master/WalletWasabi.Packager/Program.cs) but I don't see any, but please check if I am correct or not.
This is a low priority but it is to avoid things like https://github.com/zkSNACKs/WasabiDoc/pull/886

Unify package prefix

---

WalletWasabi/Blockchain/Transactions/TransactionFactory.cs

This feature has being broken for a while now. Setting locktime was put after the transaction was already built.

Make locktime take effect in all cases

---

WalletWasabi.Documentation/Guides/DeterministicBuildGuide.md

De docs has been modified in a way that ruins the deterministic build process by relaxing the .NET version requirement. This PR restores the old deterministic guide here as we discussed many times in the past that it should not be in the docs, because this is developer specific thing and things like this can be very dangerous to ruin.

Add Deterministic guide back

---

WalletWasabi/WalletWasabi.csproj

Update NBitcoin that has the sanity check for NonWitnessUTXO removed.
This PR contributes for #3734

Update to NBitcoin 5.0.43

---

WalletWasabi/Bases/PeriodicRunner.cs

When I run WasabiWallet in my Visual Studio 2019 in debug mode and then close it, often I can see an NPE as a result. This PR fixes that.
**Notes:**
1. https://github.com/zkSNACKs/WalletWasabi/compare/master...kiminuo:feature/2020-06-periodic-runner?expand=1#diff-289b5b3f1a6c7a552e98f4cc7e6cd666L107 - This line is superfluous. I don't see any value for a reader to set `TriggeringCts` explicitly to null and garbage collector is fine with just `TriggeringCts = new CancellationTokenSource();`
2. https://github.com/zkSNACKs/WalletWasabi/compare/master...kiminuo:feature/2020-06-periodic-runner?expand=1#diff-289b5b3f1a6c7a552e98f4cc7e6cd666R104 - This line can throw the mentioned NullPointerException
3. `IDisposable` in .NET has its rules one should follow, so my understanding is that the issue …

PeriodicRunner: Fix possible NullPointerException

---

WalletWasabi/Services/WasabiSynchronizer.cs

The first sync request goes to V3 API then the client detects V4. This PR is removing the exception message in that case.

Do not throw exception when switching to V4 backend

---

WalletWasabi.Documentation/WasabiCompatibility.md

This document lists all the officially supported software and devices by Wasabi Wallet. This means that Wasabi makes tests on those systems and put all the efforts to make it work and maintain compatibility. One of our main goals is to not break the user space so we have to set up boundaries that we can responsibly maintain. This does not necessarily mean that systems that are not listed will not work - they might work but we not give support for them. There are a lot of systems out there and more to come we have to focus our priorities.

Create officially supported OSs and devices document

---

WalletWasabi/CoinJoin/Coordinator/Rounds/CoordinatorRound.cs
WalletWasabi/CoinJoin/Coordinator/Rounds/CoordinatorRoundConfig.cs

fixes https://github.com/zkSNACKs/WalletWasabi/issues/3815
If someone does not register a Bob, we couldn't just send out the incomplete transaction with the large mining fee for signing, because the attacker could just sign, knowing well that that he won't lose money as the tx would be invalid. For this we were adding the coordinator output to fill up the gap of the missing Bob.
However as @onvej-sl pointed out, it is not enough to make sure that the tx will be valid in a naive way. We also have to make sure that the Wasabi tx structure is valid otherwise the tx can still be invalid due to tx building logic later on.
There are 2 changes I made here:
- First I made sure the coordinator fills up the gap with new addresses, because filling up the gap with the coordinator address would result …

Fix Possible DoS Attack Vector

---

WalletWasabi.Gui/WalletWasabi.Gui.csproj

- Fixes OSX crash
OSX you can crash by putting in fullscreen mode then closing the program.
https://github.com/AvaloniaUI/Avalonia/releases/tag/0.9.11
should be tested on linux, windows and osx

update avalonia to 0.9.11

---

WalletWasabi.Tests/UnitTests/BlockNotifierTests.cs

Hi,
this PR tackles several things:
1) `Assert.Equal(b.GetHash(), chain.GetBlock(height++).HashBlock);` - this assert does actually nothing because any exception thrown by `Assert.Equal` is caught by `PeriodicRunner` and it is not propagated. The solution, I have chosen, is to make the delay long (10s) and add a CTS that is canceled when the work is done, so in ideal case the test will be fast and when it fails, it may take up to 10 seconds (which is fine imo).
2) `await Task.Delay(TimeSpan.FromMilliseconds(100)); // give it time to process the blocks` makes the test (potentially) unstable and prone to failing when a machine is under heavier load.
Cheers

BlockNotifierTests: Make `NotifyBlocksAsync` test more robust

---

.editorconfig

Hi,
this PR sets two .editorconfig properties:
* `trim_trailing_whitespace=true` 
* `end_of_line=lf`.
I'm not sure whether these changes are somewhat radical or not but the truth is that at the moment I can see that newlines are mixed in the source code. For example, Visual Studio takes incremental approach. Meaning: when you save a file, line endings won't change in the whole file, only for touched lines so git diffs won't be excessive.
Cheers!
fixes #3794

Modify .editorconfig

---

WalletWasabi.Gui/Controls/WalletExplorer/SendControlViewModel.cs

- Go to Send tab
- Change fee display format to %
- Edit the fee manually to something like 10000
- Change the amount to 1 (the expected percentage should change)
- Change the amount back to 0
The expected percentage didn't change but it should.

Fix FeePercentage when amount is 0

---

WalletWasabi.Tests/UnitTests/Crypto/BlindingTests.cs
WalletWasabi.Tests/UnitTests/Crypto/RandomTests.cs
WalletWasabi.Tests/UnitTests/Crypto/StringCipherTests.cs
WalletWasabi/Crypto/Randomness/IWasabiRandom.cs
WalletWasabi/Crypto/Randomness/IWasabiRandomExtensions.cs
WalletWasabi/Crypto/Randomness/MockRandom.cs
WalletWasabi/Crypto/Randomness/PseudoRandom.cs
WalletWasabi/Crypto/Randomness/SecureRandom.cs
WalletWasabi/Crypto/Randomness/UnsecureRandom.cs
WalletWasabi/Crypto/StringCipher.cs
WalletWasabi/Helpers/ByteArrayEqualityComparer.cs
WalletWasabi/Helpers/HashHelpers.cs

This is a preparation PR for WabiSabi: https://github.com/zkSNACKs/WalletWasabi/pull/3851
I refactored the randomness implementation based on @lontivero's suggestion (https://github.com/zkSNACKs/WalletWasabi/pull/3851#discussion_r449032189) and some private conversation with @lontivero and @molnard. So now we will be able to have an own custom `MockRandom` for making it easy for us to test things. The design is as follows:
`IRandom` (from NBitcoin) -> `IWasabiRandom` -> `SecureRandom`, `PseudoRandom`, `MockRandom`
It does not touch the code, except in one place. It swaps the `StringCypher`'s old school randomness implementation with our `SecureRandom` implementation.

Refactor Randomness

---

WalletWasabi.Gui/Controls/WalletExplorer/TransactionInfoTabView.xaml

Fixes #3878
https://github.com/zkSNACKs/WalletWasabi/blob/master/WalletWasabi.Gui/Controls/WalletExplorer/HistoryTabViewModel.cs#L145
Should we also change that to
`BlockHeight = txr.Height.Type == HeightType.Chain ? txr.Height.Value : int.MaxValue,`
or
`BlockHeight = txr.Height.Type == HeightType.Chain ? txr.Height.Value : int.MinValue,`

Hide block height if the transaction is not confirmed

---

WalletWasabi.Gui/Controls/TransactionDetails/ViewModels/TransactionDetailsViewModel.cs

#3880 didn't really fix the block height issue because https://github.com/zkSNACKs/WalletWasabi/commit/0e62cf81c7d12643abb85933a8be26ae64b38840#diff-995774607e811ee67f9687572ce5b3c9 removed the `Confirmed` property which is necessary [here](https://github.com/zkSNACKs/WalletWasabi/blob/master/WalletWasabi.Gui/Controls/WalletExplorer/TransactionInfoTabView.xaml#L28)

Add back Confirmed property

---

WalletWasabi/TorSocks5/TorProcessManager.cs

`IsTorRunningAsync` is not used. Do not confuse with the static variant that is in use!

TorProcessManager: Remove unused method.

---

WalletWasabi.Gui/Controls/WalletExplorer/HistoryTabViewModel.cs

Fixes https://github.com/zkSNACKs/WalletWasabi/issues/3877
NewBlockProcessed was only called when there was at least one relevant tx in the block
https://github.com/molnard/WalletWasabi/blob/f7397ece96fe448ab908659122056f1fb238dfeb/WalletWasabi/Wallets/Wallet.cs#L523
The confirmations need to be updated every time if there is a new block. So change this to be triggered by NewFilterProcessed
https://github.com/molnard/WalletWasabi/blob/f7397ece96fe448ab908659122056f1fb238dfeb/WalletWasabi/Wallets/Wallet.cs#L411 
It gets called every time and after the wallet processed a new filter/block.

Fix the update of confirmations on History Tab

---

WalletWasabi.Gui/packages.lock.json
WalletWasabi.Tests/packages.lock.json

After a running dotnet restore I get this
Deleted the lock file so it was regenerated and there was a difference in the hash of SkiSharp.

Update hash of SkiaSharp in nuget lock file

---

WalletWasabi.Backend/WalletWasabi.Backend.csproj
WalletWasabi.Backend/packages.lock.json
WalletWasabi.Gui/WalletWasabi.Gui.csproj
WalletWasabi.Gui/packages.lock.json
WalletWasabi.Packager/Program.cs
WalletWasabi.Packager/WalletWasabi.Packager.csproj
WalletWasabi.Packager/packages.lock.json
WalletWasabi.Tests/WalletWasabi.Tests.csproj
WalletWasabi.Tests/packages.lock.json
WalletWasabi/WalletWasabi.csproj
WalletWasabi/packages.lock.json

This PR attempts to fix an issue mentioned in #4077, namely:
> Seemingly if you run publish on different platforms, more and more dependency hashes added [to package.lock.json files].
> [and]
> I saw that the package.lock files were modified meanwhile the build and only at the end were the same like in the current master. 
This PR is based on #4083 so that one must be reviewed first.
Please test, if it works for you.

Improve Packager wrt deterministic builds.

---

WalletWasabi.Backend/WalletWasabi.Backend.csproj
WalletWasabi.Gui/WalletWasabi.Gui.csproj
WalletWasabi.Packager/WalletWasabi.Packager.csproj
WalletWasabi.Tests/WalletWasabi.Tests.csproj
WalletWasabi/WalletWasabi.csproj

Fixes: https://github.com/zkSNACKs/WalletWasabi/issues/4090
Some places we use the `[CallerFilePath]` that will hardcode the file path into the binaries in compile time. This ruining deterministic build, if the user tries to build Wasabi from a different repository path that I used on my own machine when creating the release. 
`[CallerFilePath] string callerFilePath = ""`
We are using it in the logger, here:
https://github.com/molnard/WalletWasabi/blob/87275a988334b16baf8fca536d807ac15972c782/WalletWasabi/Logging/Logger.cs#L126
Without PathMap
By adding this to csproj file
`<PathMap>$(MSBuildProjectDirectory)\=WalletWasabi.Gui</PathMap>`
Refs:
https://blog.paranoidcoding.com/2016/04/05/deterministic-builds-in-roslyn.html
https://gist.github.com/aelij/b20271f4bd0ab1298e49068b388b54ae …

Add PathMap to solve deterministic build on  CallerFilePath

---

WalletWasabi.Backend/Controllers/BlockchainController.cs
WalletWasabi.Tests/UnitTests/MemoryTests.cs
WalletWasabi/BitcoinCore/CachedRpcClient.cs
WalletWasabi/Extensions/MemoryExtensions.cs
WalletWasabi/Wallets/SmartBlockProvider.cs

This is emergency fix and must be deployed as soon as properly reviewed. Thus CodeScene's failure can be dismissed exceptionally.  
The server's caching is failing and RPC calls were freezing it yesterday, so a temporary solution was deployed: https://github.com/zkSNACKs/WalletWasabi/pull/4136
TLDR:
1. Added failing test.
2. Fixed newly added failing test.
3. Removed temporary hotfix hack.
4. Since the fix changed the parameter list of the function, adjusted the code accordingly.
In this PR, the issue is successfully reproduced with a new failing unit test: `CacheTaskTestAsync` (https://github.com/zkSNACKs/WalletWasabi/pull/4137/files#diff-604389d9afed9a111915d66afb00e6f3R203-R236) for the recently introduced `AtomicGetOrCreateAsync` function. It was failing, because .NET's built in …

Fix Failing Atomic Cache

---

WalletWasabi.Gui/Controls/WalletExplorer/SendTabViewModel.cs

For a couple of years, Tor documentation has made the term `hidden service` obsolete, in favor of `onion service`: [Tor Project | Onion Services](https://community.torproject.org/onion-services/)
This PR updates references for Payjoin alerts.

Replace `hidden service` with `onion service`

---

WalletWasabi.Gui/Tabs/WalletManager/RecoverWallets/RecoverWalletViewModel.cs

Allow suggesting same words multiple times when typing recovery words

---

WalletWasabi.Gui/Suggestions/SuggestLabelViewModel.cs
WalletWasabi/Wallets/WalletManager.cs

This moves code that is specific from `WalletManager` to `SuggestLabelViewModel` class.
Also, it improves dependency passing. In the long run, it may decrease the number of dependencies `WalletManager` requires.

Move complexity from WalletManager to SuggestLabelViewModel.

---

WalletWasabi.Gui/Helpers/FileHelpers.cs

Noticed this while [testing v1.1.12](https://github.com/zkSNACKs/WalletWasabi/issues/3782).
Without this change on a Linux systems without gedit installed (like mine), each time you try to open some log file, confusing `/bin/sh: gedit: command not found` error is printed to stdout. This fixes that.
Of course, this is fairly minor and likely should not be merged before next release.

Check for existence of gedit before trying to launch it

---

WalletWasabi/TorSocks5/TorProcessManager.cs
WalletWasabi/TorSocks5/TorSocks5Client.cs

This is part of my attempt to clean Tor-related classes a bit.

TorSocks5Client: Remove unused constructor.

---

.editorconfig

Currently, the rules apply to `*.cs` files. `*.csproj` should follow similar rules.

Update .editorconfig for *.csproj files.

---

WalletWasabi.Gui/Tabs/WalletManager/RecoverWallets/RecoverWalletViewModel.cs

In the Recovery Wallet page Wasabi allows users to specify the `Account Key Path` but it never validates that the entered keypath is really an account key path compatible with Wasabi.
Closes https://github.com/zkSNACKs/WalletWasabi/issues/3916

Validate Account keypath

---

WalletWasabi/Logging/Logger.cs
WalletWasabi/TorSocks5/TorSocks5Client.cs

This PR adds more logs to `TorSocks5Client` class as Tor issues are important to diagnose correctly.
Notes:
* Review should be done with whitespace changes disabled (https://github.com/zkSNACKs/WalletWasabi/pull/4131/files/?w=1).
* The PR just wraps code in try-catch and adds logging statements. There should be no change in behavior.
* I have used `Logger.LogDebug($"> {nameof(host)}={host}, {nameof(port)}={port}, {nameof(isRecursiveCall)}={isRecursiveCall}");` where `>` is a convention for saying "we are entering `ConnectToDestinationAsync` method. It can be any character/string. If you like something better, it can be changed. However, by itself it's very useful to know "that code went into the method and that it left the method (denoted by `>` sign)". 
* I would add more log statements …

Add more logging to TorSocks5Client.

---

WalletWasabi.Tests/UnitTests/Crypto/GroupElements/GeneralTests.cs
WalletWasabi.Tests/UnitTests/Crypto/GroupElements/OperationTests.cs

In https://github.com/zkSNACKs/WalletWasabi/pull/4149 CodeScene complained about the code health of Group Element tests, but it did not provide any information why. After https://github.com/zkSNACKs/WalletWasabi/pull/4149 got merged I did an X-Ray on the tests and found the `MultiplyByScalar` test to have the largest "Complexity/Size" metric.
This PR does two things:
- Created a test directory `GroupElements` and moved the `GroupElementTests` file under it. Renamed the file to `GeneralTests` and added a new file `OperationTests`, to which I copypasted operation related tests, like addition, subtraction, multiply by scalar, negation.
- I decoupled the `MultiplyByScalar` test into two tests, where the first part stayed the same, but the second part is called `OverflownScalar` as that's …

Organize Group Element Tests

---

WalletWasabi.Gui/Controls/WalletExplorer/CoinJoinTabView.xaml
WalletWasabi.Gui/Controls/WalletExplorer/CoinListView.xaml
WalletWasabi.Gui/Controls/WalletExplorer/PinPadView.xaml
WalletWasabi.Gui/Dialogs/CannotCloseDialogView.xaml
WalletWasabi.Gui/Dialogs/TextInputDialogView.xaml

Closes #4104
Finish the work that i started on #4104 by simplifying some of the old row/col defs. Also added wrappers for non trivial columndefinitions in case https://github.com/AvaloniaUI/Avalonia/pull/4397 is merged into 0.10 final
cc: @lontivero @molnard

[3/3] Simplify Grid col/row definitions declarations

---

WalletWasabi.Documentation/Guides/HowToDebug.md

This PR simplifies the steps needed to debug code with vscode after the addition of `<PathMap>`. It also includes steps needed to be able to debug unit tests.

Improve documentation for debugging

---

WalletWasabi.Tests/RegressionTests/CoinJoinTests.cs
WalletWasabi.Tests/RpcTests.cs
WalletWasabi.Tests/TestableRpcService.cs
WalletWasabi.Tests/UnitTests/BlockNotifierTests.cs
WalletWasabi.Tests/UnitTests/Clients/WasabiClientTests.cs

See #4147 issue and comment https://github.com/zkSNACKs/WalletWasabi/issues/4147#issuecomment-671798346 for details why xunit tests should not contain DIRECTLY ConfigureAwait(false) method calls.
This is a part of work on #4152 too.

Remove ConfigureAwait(false) from tests.

---

WalletWasabi.Documentation/WasabikaCodex.md

After pulling the project I got an error that says `WalletWasabi.WindowsInstaller` is not supported in Visual Studio 2019.
How to fix:
- `Extension -> Manage Extensions` Install `WiX Toolset Visual Studio 2019 Extension`
- After the installation reload the `WalletWasabi.WindowsInstaller` project by right click on it and `Reload Project`

Update WasabikaCodex.md add missing setup elements to Visual Studio guide

---

WalletWasabi.Tests/UnitTests/GUI/CommandInterpreterTest.cs

This PR attempts to unify use of `StringNoWhiteSpaceEqualityComparer` in `CommandInterpreterTest` test.
This PR is an attempt to make #3863 smaller to make review easier.

CommandInterpreterTest: Add missing StringNoWhiteSpaceEqualityComparer.

---

WalletWasabi.Tests/UnitTests/SerialBlockNotifierTests.cs

`BlockNotifier` tests are flaky. Make them run in serial order.
This is part of #4152 project.

Make BlockNotifierTests run in serial mode in xunit.

---

WalletWasabi/Blockchain/Transactions/TransactionFactory.cs

Fixes #4172
Currently when you make a transaction that generates change, the change goes to a random address from the list of clean change addresses. The standard behavior is to receive the change in the first clean change address.
Used `FirstOrDefault()` because `RandomElement()` returns `default` if there is no element. https://github.com/zkSNACKs/WalletWasabi/blob/master/WalletWasabi/Extensions/LinqExtensions.cs#L44-L61

Receive change in the first clean change address

---

WalletWasabi.Backend/wwwroot/index.html

- Move `faq` at the first place (it's the only internal link)
- Add `blog`
- Edit `download` button (make it simpler)
Preview:

Update website menu

---

WalletWasabi.Tests/UnitTests/MemoryTests.cs

There is an issue on the server and with @lontivero we were suspecting this (https://github.com/alastairtree/LazyCache/issues/84) but this test seem to work correctly.

Add a basic test for AbsoluteExpirationRelativeToNow

---

WalletWasabi/Helpers/Constants.cs

As pointed out twice https://github.com/zkSNACKs/WalletWasabi/pull/4036#issuecomment-663082174 & https://github.com/zkSNACKs/WalletWasabi/pull/4036#pullrequestreview-464687067 `MaxSatoshisSupply` is no longer used.
There are other constants that are not used, should those also get removed?
https://github.com/zkSNACKs/WalletWasabi/blob/master/WalletWasabi/Helpers/Constants.cs#L39-L41
https://github.com/zkSNACKs/WalletWasabi/blob/master/WalletWasabi/Helpers/Constants.cs#L81-L94

Remove unused const

---

WalletWasabi.Gui/Tabs/WalletManager/GenerateWallets/GenerateWalletSuccessView.xaml

The reason why we salt the recovery words with the password is for those two to not be in the same place physically, thus both has to be hacked in order to gain access to the user's wallet. Or more specifically an attacker would have to break into
- the user's mind (to get the password/passphrase)
AND to one of the following places:
- the user's house (to get the mnemonics)
- the user's computer (to get the wallet file)

Do NOT advise to write down the password

---

WalletWasabi.Tests/UnitTests/Hwi/SerialDefaultResponseTests.cs

This is part of #3863 project.
* Fixes `HwiProcessBridgeTestAsync` as it uses:
```csharp
var res = await pb.SendCommandAsync("version", false, cts.Token);
```
which is incorrect because `--version` should be passed instead of `version`. Previous behavior was that an error message (string) in JSON was returned (on my Windows 10 machine). `Constants.HwiVersion` is used to verify the actual version.
* New test `HwiHelpTestAsync` asserts JSON response format.

Improve HWI tests.

---

WalletWasabi.Gui/Tabs/WalletManager/GenerateWallets/GenerateWalletSuccessView.xaml

FWIW, I agree with @yahiheb [comment](https://github.com/zkSNACKs/WalletWasabi/pull/4257#pullrequestreview-478069277).
If the goal is to encourage users to keep mnemonic and password separate, then why not to tell them exactly that? Telling them to memorize the password does not tell them to keep them separate; e.g., I can imagine users that memorize the password because so the wallet says, but they also write it down next to the mnemonic for good measure (since no one is telling them to keep them separate).

Nit - Fix typo

---

WalletWasabi.Tests/UnitTests/BitcoinCore/SerialP2pBasedTests.cs

This PR is part of #4152 project. It converts `P2pBasedTests` to `SerialP2pBasedTests` as the tests are time-sensitive and prone to be flaky.
I'm aware of the Lucas' suggestion which I have added as an issue here: https://github.com/zkSNACKs/WalletWasabi/issues/4260 but I find it better to make tests as stable as possible as soon as possible.

Make P2pBasedTests serial.

---

WalletWasabi.Tests/UnitTests/HashChainTests.cs

`The parameter must begin on the line after the previous parameter.`
I just moved the comments.

Fix CodeFactor issues

---

.github/stale.yml

IMO we should let stale bot act on priority issues/PRs, so I think we should remove it from `exemptLabels`.
If we have an issue or a PR with the label priority but it is inactive for 60 days, this means either we should fix it or it is not really a priority.

Allow stalebot to act on priority issues and PRs

---

WalletWasabi.Gui/UiConfig.cs

We have way too much space in the general wallet already and the distracting legal window looks much better in normal size, too.

Open Wasabi in normal size by default.

---

WalletWasabi/Hwi/Models/HardwareWalletModels.cs

With HWI 1.2, the BitBox02 hardware wallets are supported. This commit
adds those to the list of enabled wallets for Wasabi.
See also https://github.com/bitcoin-core/HWI/milestone/4?closed=1
HWI 1.2 can be vendored once it is released. Until then, this commit is a no-op, but once HWI 1.2 is vendored, it will automatically work with the BitBox02.

Hwi/Models: add BitBox02 support

---

WalletWasabi.Tests/IntegrationTests/LiveServerTests.cs

I have noticed this when researching `TorProcessManager` & #4299.
Notes:
* The PR fixes a single nullable warning. Alternatively, one can use `Network.GetNetwork(networkType.ToString())!` (i.e. with the `!` operator).

Remove nullable warning.

---

WalletWasabi.Tests/IntegrationTests/TorTests.cs

- smartbit -> postman, because smartbit is unreliable
- slack -> postman, because the response is strange, this could be investigated further though
- whonix onion now needs www

Fix Tor tests

---

WalletWasabi/Legal/Assets/LegalDocuments.txt

There was an extra space. Now the 9.5 chapter follows the design of the rest of the document.

Remove extra space in LegalDocuments.txt

---

WalletWasabi/Tor/TorInstallator.cs
WalletWasabi/Tor/TorProcessManager.cs

This PR is "move-only" PR that adds new `TorInstallator` class.
The future plans are:
* Research whether we can test Tor installation.
* Verify that the installation is actually correct - Tor program is where it is supposed to be.
* Probably attempt to handle exceptions from `IoHelpers.BetterExtractZipToDirectoryAsync` in `InstallAsync` right away to return nice report what actually failed.

Add TorInstallator class.

---

README.md

Users can click on the badge and download the latest binaries from here.

Add status badge for continuous delivery

---

WalletWasabi.Gui/Controls/WalletExplorer/SendControlView.xaml
WalletWasabi.Gui/Controls/WalletExplorer/SendControlViewModel.cs
WalletWasabi.Gui/Converters/FeeDisplayFormatStringConverter.cs
WalletWasabi.Gui/Tabs/SettingsView.xaml
WalletWasabi.Gui/Tabs/SettingsViewModel.cs
WalletWasabi.Gui/UiConfig.cs

A simple version of #2038.
Closes #2038
- Option added in `Settings` to select the display format of the fee.
- Everything is synchronized (Send tab detects if the selected display format is changed in Settings and Settings detects if it changed in the Send tab)

Add fee display format option in settings

---

WalletWasabi.Gui/Config.cs
WalletWasabi/Helpers/EnvironmentHelpers.cs

Notes:
* This PR should be reviewed with disabled whitespace changes.
* It fixes nullable warning for `string directory`.
* It removes exception throwing for the sake of cathing it later. I'm not sure what the intent behind this was but I kind of think that you wanted stacktrace. If you don't like this part, I can revert it.
* EnvironmentHelpers.cs is now without a nullable warning.

Adjust GetDefaultBitcoinCoreDataDirOrEmptyString.

---

WalletWasabi/Helpers/EnvironmentHelpers.cs
WalletWasabi/Tor/TorProcessManager.cs
WalletWasabi/Tor/TorSettings.cs

This is part of #4244 project where I would actually like to get rid of those `await Task.Delay(3000);` delays in `TorTests` and enforce that when you start Tor and you ask for `ensureRunning` it will be started or an exception will be thrown. This PR paves the path to that goal.
**Notes:**
* This PR adds a convenience `TorBinaryDir` property to `TorSettings`. I will remove those `Tor` prefixes later on. But now it's for consistency reasons.
* Main change of this PR is to use `ProcessAsync` API for Linux & macOS to start Tor process.
**Testing:** I have tested on the following platforms
* Windows 10 
* Ubuntu 20.04
* Ubuntu 18.04
* Ubuntu 16.04
* Fedora 32
Can anyone help with testing this on not covered OSes?
PS: I don't have mac. Does anyone know how to install mac in a virtual machine …

TorProcessManager & ProcessAsync API.

---

WalletWasabi.Tests/UnitTests/Crypto/ZeroKnowledge/KnowledgeOfDlogTests.cs
WalletWasabi.Tests/UnitTests/Crypto/ZeroKnowledge/KnowledgeOfRepTests.cs
WalletWasabi/Crypto/ZeroKnowledge/NonInteractive/Verifier.cs
WalletWasabi/Crypto/ZeroKnowledge/ProofSystem.cs
WalletWasabi/Crypto/ZeroKnowledge/Transcript.cs

Trivial PR that simplifies the code simply by removing the FQs from everywhere. These identifiers were there in order to be able to have a previous version and a new version separated by namespaces.

[WabiSabi] Remove Fully Qualified identifiers

---

WalletWasabi.Gui/Global.cs
WalletWasabi/CoinJoin/Client/Clients/Queuing/DequeueReason.cs

Similar to here #4388.
Since now we have an `EnumExtension` to get a `FriendlyName()` I think it is better to use it here too.

Use EnumExtension's FriendlyName on DequeueReason enum

---

WalletWasabi/Tor/TorInstallator.cs
WalletWasabi/Tor/TorProcessManager.cs

This is part of #4244 project where I would actually like to get rid of those await `Task.Delay(3000);` delays in `TorTests` and enforce that when you start Tor and you ask for `ensureRunning` it will be started or an exception will be thrown. This PR paves the path to that goal.
**Notes:**
* Only moves a few conditions from `TorProcessManager` to `TorInstallator`. 
* The change is important because `TorInstallator` is supposed to do everything related to installation of Tor and `TorProcessManager` is supposed to manage Tor process: to run it and to monitor it.

Move the rest of installation stuff from TorProcessManager to TorInstallator.

---

.gitignore
WalletWasabi.Gui/packages.lock.json
WalletWasabi.Packager/packages.lock.json
WalletWasabi/WalletWasabi.csproj
WalletWasabi/packages.lock.json

NBitcoin.Secp256k1 contains a new ctor for Scalar that we need to use. I took the opportunity to update NBitcoin too (this is not absolutely necessary but we use to work with the latest version).

Update NBitcoin and NBitcoin.Secp256k1

---

WalletWasabi.Gui/Controls/WalletExplorer/WalletInfoView.xaml

Similar to https://github.com/zkSNACKs/WalletWasabi/pull/4321#issuecomment-693298309
> If password box has any text in it, the height of the button next to it grows to the same as the password box height.
There is still one place in the Receive tab where this can be changed but I don't know how to do that (@jmacato can you take a look at that):
https://github.com/zkSNACKs/WalletWasabi/blob/master/WalletWasabi.Gui/Controls/WalletExplorer/ReceiveTabView.xaml#L30

Make button height same as textbox height

---

WalletWasabi.Backend/Controllers/BatchController.cs
WalletWasabi.Backend/Controllers/BlockchainController.cs
WalletWasabi.Backend/Global.cs
WalletWasabi.Tests/IntegrationTests/LiveServerTests.cs
WalletWasabi.Tests/RegressionTests/CoinJoinTests.cs
WalletWasabi.Tests/UnitTests/BitcoinCore/RpcBasedTests.cs
WalletWasabi/BitcoinCore/Monitoring/RpcFeeProvider.cs
WalletWasabi/CoinJoin/Coordinator/Rounds/CoordinatorRound.cs
WalletWasabi/Extensions/RPCClientExtensions.cs
WalletWasabi/WebClients/Wasabi/WasabiClient.cs

- Remove a bunch of dead code.
- Handle fee estimation fail gracefully on the backend.
- Don't prevent running of the backend if fee estimation isn't available.
- This was freezing the UI with Core when estimation wasn't available.

Improve fee estimation

---

WalletWasabi.Gui/Validation/ValidationExtensions.cs
WalletWasabi.Gui/Validation/Validations.cs
WalletWasabi/Models/ErrorDescriptor.cs

* https://github.com/zkSNACKs/WalletWasabi/pull/4422/files#diff-06b262b748fb1ad8b11ec35df1894ec7L7 - removes unused ErrorDescriptor
* https://github.com/zkSNACKs/WalletWasabi/pull/4422/files#diff-9a89bbc7e8c23807e8faf2f04fd12d35L49 - replaces `ContainsKey` + `[]` with `TryGetValue`.
* https://github.com/zkSNACKs/WalletWasabi/pull/4422/files#diff-2d7dc384b466265d05cbc5d55d408d3bL13 - no change, just to make it easier to understand.

GUI validation: trivial improvements.

---

WalletWasabi.Gui/Global.cs
WalletWasabi.Tests/IntegrationTests/LiveServerTests.cs
WalletWasabi.Tests/IntegrationTests/TorTests.cs
WalletWasabi/Logging/BenchmarkLogger.cs
WalletWasabi/Tor/TorProcessManager.cs

This is part of #4244 project where I would actually like to get rid of those await `Task.Delay(3000);` delays in `TorTests` and enforce that when you start Tor and you ask for `ensureRunning` it will be started or an exception will be thrown. This PR paves the path to that goal.
<s>**Depends on #4403.**</s>
**Notes;**
* Review with whitespace changes [disabled](https://github.com/zkSNACKs/WalletWasabi/pull/4405/files?diff=split&w=1).
* Major change (up to discussion here) is [waiting until Wasabi Wallet can connect to Tor process](https://github.com/zkSNACKs/WalletWasabi/pull/4405/files?diff=split&w=1#diff-4d4ddd30769b96fecd018a04b266a850R181) (note that this is not the same as to prove that Tor really works because to prove that you need to access some URL via Tor).
* On my machine with …

TorProcessManager.Start - async version

---

WalletWasabi/Tor/Http/TorHttpClient.cs

I have noticed this TODO in code when looking at #4421.
Depends on #4405. (For correct path where to install Tor when running tests with: `~/work/WalletWasabi$ dotnet test --configuration Debug --filter "IntegrationTests" --logger "console;verbosity=detailed"`).
Relevant resources:
* https://github.com/dotnet/corefx/issues/21761
* https://github.com/dotnet/runtime/issues/17677
* https://github.com/dotnet/corefx/pull/28278 - PR fixing the issue
* https://devblogs.microsoft.com/dotnet/announcing-net-core-2-1-preview-1/#sockets-performance-and-http-managed-handler - relevant release notes for .NET Core 2.1
@nopara73 Do you agree with the concept here? Do you possibly remember how to test this?

TorHttpClient: SslStream is supposed to support SNI since .NET Core 2.1.

---

WalletWasabi.Tests/IntegrationTests/TorTests.cs
WalletWasabi/Tor/TorProcessManager.cs

This is part of work on #4421 where I try to simplify the code first.
My plan is to continue with cleaning up of `TorSocks5Client`. I have some plan for that.

TorProcessManager.IsTorRunningAsync no longer accepts NULL.

---

WalletWasabi/Services/WasabiSynchronizer.cs

This fixes the issue when the wasabi process never ends when running the Fluent project.

[Fluent] Fix Wasabi process never ends

---

WalletWasabi/Tor/Http/Extensions/HttpResponseMessageExtensions.cs

This PR only removes unused method.

trivial: Remove unused `HttpResponseMessageExtensions.*` methods.

---

WalletWasabi/Tor/Http/Extensions/HttpResponseMessageExtensions.cs
WalletWasabi/Wallets/Wallet.cs

This PR removes `DataDir` property from `Wallet` class + fixes nullability issue in `ThrowRequestExceptionFromContentAsync`.

trivial: Remove unused `DataDir` property from Wallet.

---

WalletWasabi/Services/WasabiSynchronizer.cs

This PR only removes unused constructor and makes easier to review my next PR which removes `CreateNew` method.

trivial: Remove unused constructor from WasabiSynchronizer.

---

WalletWasabi/Services/WasabiSynchronizer.cs

Removes unused constructor:
```csharp
public WasabiSynchronizer(Network network, BitcoinStore bitcoinStore, WasabiClient client)
{
CreateNew(network, bitcoinStore, client);
}
```
and inlines `CreateNew()` method (which removes a bunch of nullability issues) but it also helps me with the refactoring of Tor classes.

WasabiSynchronizer: Constructors

---

WalletWasabi.Tests/UnitTests/MemoryTests.cs

`MemoryTests.ExpirationTestsAsync` recently failed for me:
I'm not sure why that happened. The idea of the PR here is to have more information next time the test fails.

Attempt to make `ExpirationTestsAsync` more robust wrt CI.

---

WalletWasabi.Backend/Program.cs
WalletWasabi.Gui/Program.cs

It's defined in the `launchsettings.json`, too. And since that needs to be there so VS knows where to open the file, this duplication should be removed.

Remove duplicated port setting

---

WalletWasabi.Backend/Program.cs

No behavior change here. However some ASP.NET boilerplate apps rely on this function being in the `Program.cs`. For example the MVC test framework only works if it's here, which we should start using for testing eventually instead of the large dirty code of RegTests.

Create CreateHostBuilder method

---

WalletWasabi.Backend/WalletWasabi.Backend.csproj

It's pointless and it was forgotten to be updated after v4.

Remove version from backend package

---

WalletWasabi.Community/Dojo.md

This folder contained the Dojo a long time ago. We left it here and redirected to the docs as it was moved, but we didn't want to break links. I think sufficient amount of time passed by now so we can remove this root level directory.

Remove WalletWasabi.Community

---

WalletWasabi.Gui/Controls/WalletExplorer/SendTabViewModel.cs
WalletWasabi/Blockchain/Transactions/TransactionFactory.cs
WalletWasabi/WebClients/PayJoin/PayjoinClient.cs

Fixes #4426
Encode the PSBT with base64 in the PayJoin client in order to make it work with JM. BTCPayServer uses base16 but the bip says base64 only so.
@MaxHillebrand would you like to try this?

Encode PSBT using base64 instead of base16

---

WalletWasabi.Backend/Program.cs

Reverts https://github.com/zkSNACKs/WalletWasabi/pull/4473
It seems like launchsettings is only used by VS.

Add back endpoint

---

WalletWasabi/Services/SingleInstanceChecker.cs

This PR attempts to fix `SingleInstanceCheckerTest` as it appears the test is flaky:
@molnard Could you say why `TimeSpan.Zero` was used in the first place?

Increase timeout for SingleInstanceChecker.

---

WalletWasabi.Tests/UnitTests/Crypto/ProofSystemTests.cs
WalletWasabi.Tests/UnitTests/Crypto/ZeroKnowledge/LinearRelationTests.cs
WalletWasabi/Crypto/ZeroKnowledge/LinearRelation/Statement.cs
WalletWasabi/Crypto/ZeroKnowledge/ProofSystem.cs
WalletWasabi/Crypto/ZeroKnowledge/Transcript.cs

I think it's good enough for now, but this could still use some work:
- better tests
- improve coverage of inter-equation aspects of LinearRelation, in particular range proofs rely on the fact that witness components are shared between equations, there should be tests with more maliciously constructed proofs to ensure the verifier rejects
- tests are pretty slow, not sure what to do about this
- cleaner API
- it's not clear whether the `Knowledge` returning variant of `RangeProof` should generate bit commitments itself or that should be done separately (e.g. in some convenience routine used before calling that, in which case the arguments would be a vector of bits, a vector of randomness, and the randomness of the amount commitment... i tried this and didn't like it)
The range proofs are …

[WabiSabi] Range proof

---

WalletWasabi/Tor/Http/TorHttpClient.cs

`ITorHttpClient` already implements `IDisposable`. So this is redundant here.

trivial: Remove redundant IDisposable.

---

WalletWasabi/Tor/Socks5/TorSocks5Client.cs

* `TorSocks5EndPoint` can no longer be `null`.
* `TorSocks5EndPoint` can be private field. 
Review with whitespace turned off: https://github.com/zkSNACKs/WalletWasabi/pull/4518/files?diff=split&w=1

TorSocks5Client: Remove unused code.

---

WalletWasabi/Tor/Socks5/Models/Bases/OctetSerializableBase.cs
WalletWasabi/Tor/Socks5/Models/Fields/OctetFields/VerField.cs
WalletWasabi/Tor/Socks5/Models/Messages/MethodSelectionResponse.cs
WalletWasabi/Tor/Socks5/Models/Messages/TorSocks5Request.cs
WalletWasabi/Tor/Socks5/Models/Messages/TorSocks5Response.cs
WalletWasabi/Tor/Socks5/Models/Messages/VersionMethodRequest.cs

Do not allow to create `VerField` without getting some byte - make it harder to make a mistake.

Refactor VerField.

---

WalletWasabi/CoinJoin/Client/Clients/CoinJoinClient.cs

I've got a report by @lukechilds on input and output side address reuse in a coinjoin. I investigated it and came to the conclusion that it can only happen if the `ExposedKeys` contain non-`Locked` `HdPubKey`s.
Considering that there's no privacy issue here, only efficiency issue, since address reuse is handled with anonset calculations and that wabisabi will obsolate this code, I think this simple sanity check is more reasonable to do instead of a more intrusive refactoring.

Ensure `ExposedKeys` are properly cleaned up before usage

---

WalletWasabi/Hwi/HwiClient.cs

`commandArguments` from argument should be just passed through to recursive call but instead local variable `arguments` has been mistakenly used (it already included options and command)
(cherry picked from commit 5aae4e5a7ada2a00d6077df54e2cfbf8737b0e84)

bugfix HwiClient.SendCommandAsync() recursive call

---

WalletWasabi/WebClients/PayJoin/PayjoinReceiverException.cs

This is no longer used since https://github.com/zkSNACKs/WalletWasabi/commit/25ccfeb1d19857fe1f42fa16776b756cddcb5a68#diff-f51d4fca9024c80f00b1b7feec1fd0e5

[Trivial] Remove unused member

---

WalletWasabi.Gui/Config.cs
WalletWasabi.Gui/Global.cs
WalletWasabi.Gui/Tabs/SettingsView.xaml
WalletWasabi.Gui/Tabs/SettingsViewModel.cs
WalletWasabi/Tor/TorProcessManager.cs

If the Tor process was started by Wasabi then it will kill it on quit. The default value for this option is false - by default Wasabi is not closing the Tor process after quit - this is intentional and for privacy reasons.

Add config option to close Tor instance on quit

---

WalletWasabi.Tests/UnitTests/Clients/SingleInstanceCheckerTests.cs
WalletWasabi/Services/SingleInstanceChecker.cs

This should fix the flakiness of SingleInstanceCheckerTest.

Randomize lock names in SingleInstanceChecker test.

---

CONTRIBUTING.md
WalletWasabi.Backend/InitConfigStartupTask.cs
WalletWasabi.Gui/Controls/LockScreen/SlideLock.cs
WalletWasabi.Gui/Controls/SortingArrow.cs
WalletWasabi.Gui/Controls/WalletExplorer/CoinListViewModel.cs
WalletWasabi.Gui/MainWindow.xaml.cs
WalletWasabi.Gui/Program.cs
WalletWasabi.Gui/ViewModels/ViewModelBase.cs
WalletWasabi.Tests/RegressionTests/Common.cs
WalletWasabi/Bases/NotifyPropertyChangedBase.cs
WalletWasabi/BitcoinCore/Monitoring/RpcFeeProvider.cs
WalletWasabi/BitcoinCore/Monitoring/RpcMonitor.cs
WalletWasabi/BitcoinCore/P2pNode.cs
WalletWasabi/Blockchain/Analysis/FeesEstimation/FeeProviders.cs
WalletWasabi/Blockchain/Analysis/FeesEstimation/IFeeProvider.cs
WalletWasabi/Blockchain/BlockFilters/IndexBuilderService.cs
WalletWasabi/Blockchain/Blocks/BlockNotifier.cs
WalletWasabi/Blockchain/P2p/TrustedP2pBehavior.cs
WalletWasabi/Blockchain/TransactionProcessing/TransactionProcessor.cs
WalletWasabi/CoinJoin/Client/Clients/CoinJoinClient.cs
WalletWasabi/CoinJoin/Client/CoinJoinProcessor.cs
WalletWasabi/CoinJoin/Coordinator/Coordinator.cs
WalletWasabi/CoinJoin/Coordinator/Rounds/CoordinatorRound.cs
WalletWasabi/Services/UpdateChecker.cs
WalletWasabi/Services/WasabiSynchronizer.cs
WalletWasabi/Stores/IndexStore.cs
WalletWasabi/Wallets/P2pBlockProvider.cs
WalletWasabi/Wallets/Wallet.cs
WalletWasabi/Wallets/WalletManager.cs

This PR changes 
```csharp
public event EventHandler Name; // ditto for its generic variant: public event EventHandler<T> Name; 
```
to
```csharp
public event EventHandler? Name; // ditto for its generic variant: public event EventHandler<T>? Name; 
```
because
> You should make the event nullable, because it is indeed nullable. It may look a bit strange but that's the correct way of expressing your intent. 
(see https://stackoverflow.com/a/62536248)
Resources:
* https://stackoverflow.com/questions/58376972/guidelines-for-events-since-non-nullable-references
* https://source.dot.net/#System.Private.CoreLib/EventHandler.cs,3b79d2b06c15f250
* https://source.dot.net/#System.ObjectModel/System/ComponentModel/PropertyChangedEventHandler.cs,670754815f6804ff
PS: This PR removes about 130 …

Fix nullability for events and its `object sender` parameter.

---

WalletWasabi.Gui/Global.cs

@yahiheb sent me the following log when he tested #4507:
```
2020-10-14 22:19:35 WARNING     Global (643)    Process is exiting.
2020-10-14 22:19:35 DEBUG       Global (654)    Step #1: Wait for initialization to complete.
2020-10-14 22:19:35 DEBUG       Global (666)    Step #2: WalletManager.
2020-10-14 22:19:35 INFO        WalletManager (331)     KeyManager backup saved to `C:\Users\RESEAU\AppData\Roaming\WalletWasabi\Client\WalletBackups\Testnet Wallet.json`.
2020-10-14 22:19:35 INFO        Wallet (258)    ChaumianClient is stopped.
2020-10-14 22:19:35 INFO        WalletManager (333)     Wallet is stopped.
2020-10-14 22:19:35 DEBUG       Global (678)    Step #2: Application's MainWindow.
2020-10-14 22:19:35 DEBUG       Global (689)    Step #3: RpcServer.
2020-10-14 22:19:35 DEBUG …
```

`Synchronizer` must be stopped after `HostedServices`.

---

WalletWasabi/Tor/TorProcessManager.cs

Remove condition that is no longer useful since `TorSocks5EndPoint` is never null.

trivial: Remove superfluous condition.

---

WalletWasabi/Tor/Http/Bases/TorDisposableBase.cs
WalletWasabi/WebClients/Wasabi/WasabiClient.cs

`WasabiClient` inherits `TorDisposableBase`. This makes it difficult for me to continue with refactoring of Tor related classes. So I have removed the inheritance here.

`WasabiClient` no longer inherits `TorDisposableBase`.

---

WalletWasabi/Services/WasabiSynchronizer.cs
WalletWasabi/Tor/Socks5/TorSocks5Client.cs

This PR adds a few logging statements and simplifies exception catching which is correct thank to the fact that `TaskCanceledException` inherits `OperationCanceledException`.

WasabiSynchronizer: Cancelling + logging.

---

WalletWasabi/Tor/Socks5/Models/Fields/ByteArrayFields/MethodsField.cs
WalletWasabi/Tor/Socks5/Models/Fields/OctetFields/MethodField.cs
WalletWasabi/Tor/Socks5/Models/Fields/OctetFields/VerField.cs
WalletWasabi/Tor/Socks5/Models/Messages/MethodSelectionResponse.cs

This PR disallows to create `MethodField` without passing a byte.
Notes:
* `MethodField.NoAuthenticationRequired` no longer allocates when accessing needlessly.
* `MethodSelectionResponse` constructor was not in use.

Pass byte via constructor to MethodField.

---

WalletWasabi/Services/UpdateChecker.cs

Library code should use events to indicate change, according to our code conventions. 
Also another solution to https://github.com/zkSNACKs/WalletWasabi/pull/4568

Fix UpdateChecker Nullable

---

WalletWasabi/Blockchain/Transactions/TransactionFactory.cs

Fixes: https://github.com/zkSNACKs/WalletWasabi/issues/4460
Another solution to this closes https://github.com/zkSNACKs/WalletWasabi/pull/4600
After adding KeyPath to the PSBT here: 
https://github.com/molnard/WalletWasabi/blob/2acf63c420ad24b78b89b5cd44c8c48da2e623b1/WalletWasabi/Blockchain/Transactions/TransactionFactory.cs#L361
It is added to both Inputs and Outputs and CC cannot sign the tx.
This code will remove it from the outputs.

Remove PSBT output if KeyPath added to both inputs and outputs

---

WalletWasabi.Gui/packages.lock.json
WalletWasabi.Packager/packages.lock.json
WalletWasabi/Blockchain/Transactions/TransactionFactory.cs
WalletWasabi/Extensions/NBitcoinExtensions.cs
WalletWasabi/WalletWasabi.csproj
WalletWasabi/packages.lock.json

Fixes https://github.com/zkSNACKs/WalletWasabi/issues/4460 with a clean concept. Also fixes other bugs. Need to be tested with
- coldcard usb hardware wallet
- coldcard PSBT workflow
- payjoins

Concept for cleaner PSBT update

---

WalletWasabi/Tor/Socks5/Models/Fields/OctetFields/AuthVerField.cs
WalletWasabi/Tor/Socks5/Models/Messages/UsernamePasswordRequest.cs
WalletWasabi/Tor/Socks5/Models/Messages/UsernamePasswordResponse.cs

This PR disallows to create `AuthVerField` without passing a byte.

Pass parameter via constructor to AuthVerField

---

WalletWasabi/Tor/Socks5/Models/Fields/OctetFields/AuthStatusField.cs
WalletWasabi/Tor/Socks5/Models/Messages/UsernamePasswordResponse.cs

This PR disallows to create `AuthStatusField` without passing a byte.

Pass parameter via constructor to AuthStatusField

---

WalletWasabi/Tor/Socks5/Models/Fields/ByteArrayFields/AddrField.cs
WalletWasabi/Tor/Socks5/Models/Fields/OctetFields/AtypField.cs
WalletWasabi/Tor/Socks5/Models/Messages/TorSocks5Request.cs
WalletWasabi/Tor/Socks5/Models/Messages/TorSocks5Response.cs

This PR disallows to create `AtypField` without passing a parameter (byte/string).

Pass parameters via constructor to AtypField

---

WalletWasabi/Tor/Socks5/TorSocks5Client.cs

IsTorRunningAsync() called rarely, usually, at the start of Wasabi. This is true until something happens with Tor and it needs to be restarted. In this case, using a new circuit can exhaust the available streams in Tor - it makes no sense to open new streams for detection.

Do not isolate Tor stream when checking connection status

---

WalletWasabi.Tests/RegressionTests/Common.cs
WalletWasabi/WebClients/Wasabi/WasabiClient.cs

`TorClient.SendAndRetryAsync` can return `null` when all attempts fails. This was not handled in `WasabiClient` code.

Possible NREs in WasabiClient 

---

WalletWasabi.Tests/RegressionTests/CoinJoinTests.cs
WalletWasabi.Tests/UnitTests/BitcoinCore/RpcBasedTests.cs
WalletWasabi.Tests/UnitTests/CoordinatorRoundTests.cs
WalletWasabi.Tests/UnitTests/MockRpcClient.cs
WalletWasabi/BitcoinCore/Rpc/CachedRpcClient.cs
WalletWasabi/BitcoinCore/Rpc/IRPCClient.cs
WalletWasabi/BitcoinCore/Rpc/RpcClientBase.cs
WalletWasabi/CoinJoin/Coordinator/Rounds/CoordinatorRound.cs
WalletWasabi/Extensions/NBitcoinExtensions.cs
WalletWasabi/Extensions/RPCClientExtensions.cs

Bitcoin Core/Knots smart fee estimations get smaller as we increase the confirmation target at the point that we can see always a 1 sat/vbyte at the extreme. However, even when 1 sat/byte is valid and the estimation could be correct, in circumstances when there is a big pressure on the mempool (full mempools) transaction paying 1 sat/vbyte are not relayed.   
For a transaction to be relayed it has to pay at least the `MinRelayTxFee` but this doesn't guarantee the tx will be accepted in the mempool, the minimum fee to pay is provided by the node (rpc interface) asn it is called `MinMemPoolFee` that is the maximum of `MinRelayTxFee` and `MinMemPoolFee`.
This is important because Wsabi coinjoin transactions are built using the estimated fee for targets far in the time that can be under the …

Prevent building CJ with fee lower than minMemPoolFee

---

WalletWasabi.Gui/Models/Sorting/SortingPreference.cs
WalletWasabi.Gui/Models/StatusBarStatuses/Status.cs
WalletWasabi/BitcoinCore/Monitoring/RpcStatus.cs
WalletWasabi/Blockchain/Analysis/Clustering/Cluster.cs
WalletWasabi/Blockchain/Analysis/Clustering/SmartLabel.cs
WalletWasabi/Blockchain/Analysis/FeesEstimation/AllFeeEstimate.cs
WalletWasabi/Blockchain/Keys/HdPubKey.cs
WalletWasabi/Blockchain/TransactionOutputs/SmartCoin.cs
WalletWasabi/Blockchain/Transactions/SmartTransaction.cs
WalletWasabi/CoinJoin/Common/Crypto/SchnorrKey.cs
WalletWasabi/CoinJoin/Common/Crypto/SchnorrPubKey.cs
WalletWasabi/CoinJoin/Coordinator/MixingLevels/MixingLevel.cs
WalletWasabi/Crypto/Mac.cs
WalletWasabi/Helpers/ByteHelpers.cs
WalletWasabi/Hwi/Models/HwiOption.cs
WalletWasabi/Models/UpdateStatus.cs
WalletWasabi/Tor/Http/Models/HttpProtocol.cs
WalletWasabi/Tor/Socks5/Models/Bases/ByteArraySerializableBase.cs
WalletWasabi/Tor/Socks5/Models/Bases/OctetSerializableBase.cs

`==` and `!=` and so must be prepared for accept nulls.
Also added C# 7 syntax in some places and fixed some minor bugs.

Allow nullability for equality

---

WalletWasabi/Tor/Socks5/Models/Bases/ByteArraySerializableBase.cs
WalletWasabi/Tor/Socks5/Models/Fields/ByteArrayFields/AddrField.cs
WalletWasabi/Tor/Socks5/Models/Fields/ByteArrayFields/MethodsField.cs
WalletWasabi/Tor/Socks5/Models/Fields/ByteArrayFields/PasswdField.cs
WalletWasabi/Tor/Socks5/Models/Fields/ByteArrayFields/PortField.cs
WalletWasabi/Tor/Socks5/Models/Fields/ByteArrayFields/UNameField.cs
WalletWasabi/Tor/Socks5/Models/Interfaces/IByteArraySerializable.cs
WalletWasabi/Tor/Socks5/Models/Messages/MethodSelectionResponse.cs
WalletWasabi/Tor/Socks5/Models/Messages/TorSocks5Request.cs
WalletWasabi/Tor/Socks5/Models/Messages/TorSocks5Response.cs
WalletWasabi/Tor/Socks5/Models/Messages/UsernamePasswordRequest.cs
WalletWasabi/Tor/Socks5/Models/Messages/UsernamePasswordResponse.cs
WalletWasabi/Tor/Socks5/Models/Messages/VersionMethodRequest.cs
WalletWasabi/Tor/Socks5/TorSocks5Client.cs

Notes:
* No change in behavior.
* Pass bytes via constructors in `UsernamePasswordResponse` and `MethodSelectionResponse`.
* Merge two `HandshakeAsync` methods in TorSocks5Client.

[Tor] Deserialize Byte Arrays from Constructors

---

WalletWasabi.Tests/IntegrationTests/LiveServerTests.cs

This PR is paves the way to remove the following two constructors:
```csharp
public WasabiClient(Func<Uri> baseUriAction, EndPoint? torSocks5EndPoint)
{
TorClient = new TorHttpClient(baseUriAction, torSocks5EndPoint, isolateStream: true);
}
public WasabiClient(Uri baseUri, EndPoint? torSocks5EndPoint) : this(() => baseUri, torSocks5EndPoint)
{
}
```
from `WasabiClient` class. 
Notes:
* `isolateStream: true` was set in the original code too, I have not changed it.

LiveServerTests: Use factory method to instantiate TorHttpClient.

---

WalletWasabi/Tor/Http/TorHttpClient.cs
WalletWasabi/Tor/Socks5/TorSocks5Client.cs

This PR is quite simple. 
I attempt to use `TorSocks5Client.Stream` property to be implementation detail of `TorSocks5Client` and not to be exposed publicly. This helps with decoupling of `TorHttpClient` and `TorSocks5Client` classes.

Move SSL authentication from TorHttpClient to TorSocks5Client.

---

WalletWasabi/Blockchain/Keys/HdPubKey.cs
WalletWasabi/Blockchain/TransactionBuilding/BuildTransactionResult.cs
WalletWasabi/Blockchain/TransactionOutputs/CoinsRegistry.cs
WalletWasabi/Blockchain/TransactionOutputs/SmartCoin.cs
WalletWasabi/Blockchain/Transactions/SmartTransaction.cs
WalletWasabi/Blockchain/Transactions/TransactionFactory.cs

- this cannot be used in tx processor, nor in tx factory because that's where it's set.  
- these are set for all loaded wallets -> question arises if it enables cross-wallet anonset calculation?
- there are sadly some circular references here (smartcoin knows its smarttransactions and smarttransaction knows its smartcoins)

SmartTransaction and HdPubKey to know all the SmartCoins it is connected to

---

WalletWasabi/BitcoinCore/Processes/BitcoindRpcProcessBridge.cs
WalletWasabi/Microservices/ProcessAsync.cs

This is part of #4152 project.
This PR increases `ReasonableCoreShutdownTimeout` as on my laptop (2-3 years old) the number seems more fitting. The number is only experimentally verified but given that even @molnard seems to observe the ill consequences of the original timeout when he runs `BackendTests`, I think the original number is not good enough.
Feedback is welcome.
PS: I have just noticed that `TimeSpan.FromSeconds(21)` is used throughout the codebase. Any other place to apply the same change?

BitcoindRpcProcessBridge: ReasonableCoreShutdownTimeout increased.

---

WalletWasabi.Fluent/ViewModels/AddWalletPageViewModel.cs
WalletWasabi/Extensions/StringExtensions.cs
WalletWasabi/Userfacing/PasswordHelper.cs

This PR about that to increase readability in a way to not use `PasswordHelper` class in a wallet name validation.
- `IsTrimable()` added to `StringExtenstion.cs`
- Use this extension methdon in `PasswordHelper`
cc @molnard

Add IsTrimable() to string extension

---

.editorconfig
WalletWasabi.Backend/Controllers/SoftwareController.cs
WalletWasabi.Backend/Middlewares/HeadMethodMiddleware.cs
WalletWasabi.Gui/Controls/LockScreen/SlideLockScreenViewModel.cs
WalletWasabi.Packager/NSubsys/PeUtility.cs
WalletWasabi/BitcoinCore/Processes/BitcoindRpcProcessBridge.cs
WalletWasabi/Crypto/StrobeProtocol/Strobe.cs
WalletWasabi/Crypto/ZeroKnowledge/SyntheticSecretNonceProvider.cs
WalletWasabi/Mono/OptionSet.cs
WalletWasabi/Nito/AsyncEx/AsyncLock.cs
WalletWasabi/Nito/AsyncEx/AwaitableDisposable.cs
WalletWasabi/Nito/AsyncEx/DefaultAsyncWaitQueue.cs
WalletWasabi/Nito/Collections/CollectionHelpers.cs
WalletWasabi/Nito/Collections/Deque.cs
WalletWasabi/Nito/Disposables/Internals/BoundAction.cs
WalletWasabi/Nito/Disposables/SingleDisposable.cs
WalletWasabi/Services/SingleInstanceChecker.cs
WalletWasabi/Services/Terminate/TerminateService.cs
WalletWasabi/WebClients/ExchangeRateProviders.cs

This PR:
- Removes an editorconfig naming rule (as suggested in https://github.com/zkSNACKs/WalletWasabi/pull/4655#issuecomment-721127344)
- Fixes naming violations.
- Removes unused variable.

Remove readonly field naming rule

---

WalletWasabi/Tor/Socks5/Models/Bases/OctetSerializableBase.cs
WalletWasabi/Tor/Socks5/Models/Fields/OctetFields/CmdField.cs
WalletWasabi/Tor/Socks5/Models/Fields/OctetFields/PLenField.cs
WalletWasabi/Tor/Socks5/Models/Fields/OctetFields/RepField.cs
WalletWasabi/Tor/Socks5/Models/Fields/OctetFields/RsvField.cs
WalletWasabi/Tor/Socks5/Models/Fields/OctetFields/ULenField.cs
WalletWasabi/Tor/Socks5/Models/Interfaces/IByteSerializable.cs
WalletWasabi/Tor/Socks5/Models/Messages/TorSocks5Request.cs
WalletWasabi/Tor/Socks5/Models/Messages/TorSocks5Response.cs
WalletWasabi/Tor/Socks5/Models/Messages/UsernamePasswordRequest.cs

This PR only removes `OctetSerializableBase.FromByte` so that all classes are properly constructed using their respective constructors.

Remove FromByte from OctetSerializableBase.

---

.shellcheckrc

This file was not working for some reason and after https://github.com/zkSNACKs/WalletWasabi/issues/4531#issuecomment-723940490 it is not needed.

Remove .shellcheckrc file

---

WalletWasabi/Tor/Http/ClearnetHttpClient.cs
WalletWasabi/Tor/Http/IRelativeHttpClient.cs
WalletWasabi/Tor/Http/Interfaces/ITorHttpClient.cs
WalletWasabi/Tor/Http/TorHttpClient.cs

This PR adds `IRelativeHttpClient` interface on top of `IHttpClient` to allow me to continue with my refactorings.
`ClearnetHttpClient` newly implements `IRelativeHttpClient`.

Add IRelativeHttpClient.

---

WalletWasabi.Gui/Controls/WalletExplorer/CoinViewModel.cs
WalletWasabi.Tests/Common.cs
WalletWasabi.Tests/UnitTests/Transactions/TransactionFactoryTests.cs
WalletWasabi.Tests/UnitTests/Transactions/TransactionProcessorTests.cs
WalletWasabi/Blockchain/Analysis/Clustering/Cluster.cs
WalletWasabi/Blockchain/Keys/HdPubKey.cs
WalletWasabi/Blockchain/TransactionBuilding/SmartCoinSelector.cs
WalletWasabi/Blockchain/TransactionOutputs/CoinsRegistry.cs
WalletWasabi/Blockchain/TransactionOutputs/SmartCoin.cs

Recently we removed the `Label` from `SmartCoin` because it was coming from the `SmartCoin`'s `HdPubKey` anyway.  
This PR moves Cluster to `HdPubKey` from `SmartCoin`.
This is a preparation of the next PR, which will move anonymity set to `HdPubKey` from `SmartCoin` which is a preparation for https://github.com/zkSNACKs/WalletWasabi/pull/4678
This PR accidentally also results in a 30% performance gain in transaction processing.

Make HdPubKey have Cluster and not SmartCoin

---

WalletWasabi.Gui/CommandLine/Daemon.cs
WalletWasabi.Gui/Controls/WalletExplorer/CoinJoinTabViewModel.cs
WalletWasabi.Gui/Controls/WalletExplorer/CoinViewModel.cs
WalletWasabi.Gui/Rpc/WasabiJsonRpcService.cs
WalletWasabi.Tests/Common.cs
WalletWasabi.Tests/RegressionTests/CoinJoinTests.cs
WalletWasabi.Tests/UnitTests/SmartCoinTests.cs
WalletWasabi.Tests/UnitTests/Transactions/TransactionFactoryTests.cs
WalletWasabi.Tests/UnitTests/Transactions/TransactionProcessorTests.cs
WalletWasabi/Blockchain/Analysis/BlockchainAnalyzer.cs
WalletWasabi/Blockchain/Analysis/Clustering/Cluster.cs
WalletWasabi/Blockchain/Keys/HdPubKey.cs
WalletWasabi/Blockchain/TransactionBuilding/SmartCoinSelector.cs
WalletWasabi/Blockchain/TransactionOutputs/CoinsRegistry.cs
WalletWasabi/Blockchain/TransactionOutputs/CoinsView.cs
WalletWasabi/Blockchain/TransactionOutputs/ICoinsView.cs
WalletWasabi/Blockchain/TransactionOutputs/SmartCoin.cs
WalletWasabi/Blockchain/TransactionProcessing/ProcessedResult.cs
WalletWasabi/Blockchain/TransactionProcessing/TransactionProcessor.cs
WalletWasabi/Blockchain/Transactions/TransactionFactory.cs
WalletWasabi/CoinJoin/Client/Rounds/ClientState.cs
WalletWasabi/Wallets/Wallet.cs

Recently we removed the `Label` from `SmartCoin` because it was coming from the `SmartCoin`'s `HdPubKey` anyway.  
Previous PR moved Cluster to `HdPubKey` from `SmartCoin`: https://github.com/zkSNACKs/WalletWasabi/pull/4717
This PR moves anonymity set to `HdPubKey` from `SmartCoin`.
This PR is the final preparation for https://github.com/zkSNACKs/WalletWasabi/pull/4678
This PR accidentally also results in a 50% performance gain in transaction processing on top of the 30% increase in https://github.com/zkSNACKs/WalletWasabi/pull/4717.

Make HdPubKey have Anonset and not SmartCoin

---

.editorconfig

This PR sets `indent_size` to 4 for this repository by updating the `.editorconfig` file. Currently, there is no preconfigured default for this, and a tab character on GitHub is equivalent to 8 spaces. That hurts the readability of the source code when one decides to browse the code online. Currently, the source files look like this:
With the updated `indent_size` setting, the source files should look like this:
This way we get shorter lines of code when browsing source files online. Also, we get better formatting for `WhenAny` chains. Probably worth noting that WasabiWallet uses `indent_size = 2` for XAML files.
The solution is taken from https://stackoverflow.com/a/33831598/11351183

Set indent_size to 4 for C# Files

---

WalletWasabi.Fluent/Controls/Dialog.xaml.cs
WalletWasabi.Fluent/ViewModels/Dialogs/DialogScreenViewModel.cs

Fixes:
> bottom left click Settings -  click Add Wallet - click outside the dialog screen - notice the focus is still on Add Wallet, but the Settings content is shown in tab - now click Add Wallet again, notice it does not open the dialog screen again - click Settings, notice tab content refreshes - now click Add Wallet and see it opens the dialog screen again.

[Fluent] Reset navigation when Dialog is using IScreen

---

WalletWasabi.Backend/WalletWasabi.Backend.csproj
WalletWasabi.Fluent.Desktop/WalletWasabi.Fluent.Desktop.csproj
WalletWasabi.Fluent/WalletWasabi.Fluent.csproj
WalletWasabi.Gui/WalletWasabi.Gui.csproj
WalletWasabi.Packager/WalletWasabi.Packager.csproj
WalletWasabi.Tests/WalletWasabi.Tests.csproj
WalletWasabi/WalletWasabi.csproj

https://devblogs.microsoft.com/dotnet/automatically-find-latent-bugs-in-your-code-with-net-5/
> Starting with .NET 5, we’re introducing what we’re calling AnalysisLevel in the C# compiler to introduce warnings for these patterns in a safe way. The default Analysis Level for all projects targeting .NET 5 will be set to 5, meaning that more warnings (and suggestions to fix them) will be introduced.
> If you always want to be on the highest supported analysis level you can specify latest in your project file:
> ```
> <Project Sdk="Microsoft.NET.Sdk">
> 
>   <PropertyGroup>
>     <TargetFramework>net5.0</TargetFramework>
>     
>     <AnalysisLevel>latest</AnalysisLevel>
>   </PropertyGroup>
> 
> </Project>
> ```

Specify analysis level in project files

---

WalletWasabi.Gui/ViewModels/StatusBarViewModel.cs
WalletWasabi.Tests/IntegrationTests/LiveServerTests.cs
WalletWasabi.Tests/RegressionTests/BackendTests.cs
WalletWasabi.Tests/RegressionTests/CoinJoinTests.cs
WalletWasabi.Tests/RegressionTests/Common.cs
WalletWasabi/Blockchain/Mempool/MempoolService.cs
WalletWasabi/Blockchain/TransactionBroadcasting/TransactionBroadcaster.cs
WalletWasabi/CoinJoin/Client/CoinJoinProcessor.cs
WalletWasabi/Services/UpdateChecker.cs
WalletWasabi/Services/WasabiSynchronizer.cs
WalletWasabi/Wallets/Wallet.cs
WalletWasabi/WebClients/Wasabi/WasabiClient.cs
WalletWasabi/WebClients/Wasabi/WasabiClientFactory.cs

<s>Depends on #4735.</s>
This PR makes:
* `WasabiClient` class to no longer implement `IDisposable` interface.
* The reasoning behind this is that `WasabiClient` actually only sends requests to Wasabi Backend API. The means how to send it can be simply taken from constructor (clearnet HTTP client / tor HTTP client). `WasabiClient` should not create new instances of HTTP clients as it only complicate things (like where will I get tor endpoint etc.?)
* Adds `SharedWasabiClient` to `WasabiClientFactory` [[link](https://github.com/zkSNACKs/WalletWasabi/pull/4736/files#diff-2c1a13f131b977dd93bb3eb18f801b092a533d9fc216e8891b33f8647ded4619R44)] with default stream identity. So that you can just access that property and send an HTTP request using that `WasabiClient` and you don' need to …

WasabiClient is no longer disposable

---

WalletWasabi/CoinJoin/Client/Rounds/ClientState.cs

I have noticed that `ClientState::AddOrReplaceRound` method is currently unused. Maybe it can be removed? It would actually help me with Tor refactorings too, if the method is not needed anymore.

Remove unused AddOrReplaceRound method.

---

WalletWasabi.Tests/RegressionTests/CoinJoinTests.cs
WalletWasabi/CoinJoin/Client/Clients/BobClient.cs
WalletWasabi/CoinJoin/Client/Clients/CoinJoinClient.cs

Please review with hidden whitespace changes: https://github.com/zkSNACKs/WalletWasabi/pull/4757/files?diff=split&w=1
The goal here is to remove dependency on `TorDisposable` as was done for `SatoshiClient` already.
I'm not sure how to correctly run `CoinJoinTests`. Does anyone know? Hm, looks like one by one.

BobClient without being disposable.

---

WalletWasabi.Documentation/WasabiCompatibility.md

After upgrading to .NET 5.0 we need to update the supported operating systems: https://github.com/dotnet/core/blob/master/release-notes/5.0/5.0-supported-os.md

Update supported operating systems

---

WalletWasabi/Crypto/Groups/GroupElement.cs

https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1833
> Using a range-indexer on array and assigning to a memory or span type: The range indexer on a Span<T> is a non-copying Slice operation, but for the range indexer on array the method GetSubArray will be used instead of Slice, which produces a copy of requested portion of the array. This copy is usually unnecessary when it is implicitly used as a Span<T> or Memory<T> value. If a copy isn't intended, use the AsSpan or AsMemory method to avoid the unnecessary copy.

Use 'AsSpan' instead of the 'System.Range'-based indexer on 'byte[]' to avoid creating unnecessary data copies

---

WalletWasabi.Gui/.editorconfig

This is wrong, because UI thread sync back is preferable. https://github.com/zkSNACKs/WalletWasabi/pull/4771

Remove confawait check from the GUI project.

---

WalletWasabi.Tests/IntegrationTests/TorTests.cs

`TorHttpClient` is not supposed to be used for clearnet requests - `CanRequestClearnetAsync` was removed.

Minor refactoring in TorTests.

---

WalletWasabi.Gui/Controls/WalletExplorer/SendTabViewModel.cs
WalletWasabi.Gui/Global.cs
WalletWasabi/Blockchain/TransactionBroadcasting/TransactionBroadcaster.cs
WalletWasabi/WebClients/PayJoin/PayjoinClient.cs
WalletWasabi/WebClients/Wasabi/WasabiClientFactory.cs

PR notes:
* Removes one property from `Global` - namely `TorSocks5EndPoint`.
* `PayjoinClient` accepts an HttpClient only through `IRelativeHttpClient` now.
* `NewBackendTorHttpClient` and `NewTorHttpClient` did basically the same. That was a mistake.
* New method was added `WasabiClientFactory.NewHttpClient` to get `IRelativeHttpClient` that is correctly created.

PayjoinClient accepts HttpClient only through IRelativeHttpClient now.

---

WalletWasabi/Blockchain/Transactions/TransactionFactory.cs
WalletWasabi/Extensions/NBitcoinExtensions.cs

Fixes: https://github.com/zkSNACKs/WalletWasabi/issues/4689
The feature was broken by https://github.com/zkSNACKs/WalletWasabi/pull/4608 when the order of adding more information to PSBT was changed.

Add KeyPaths first to PSBT

---

WalletWasabi/Tor/Http/ClearnetHttpClient.cs

This PR solves one issue that is far from being clear from [HttpClient ](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient?view=net-5.0) documentation. The documentation mentions
> HttpClient is intended to be instantiated once and re-used throughout the life of an application. Instantiating an HttpClient class for every request will exhaust the number of sockets available under heavy loads. This will result in SocketException errors. Below is an example using HttpClient correctly.
However, one [gotcha](https://github.com/dotnet/extensions/issues/1345#issuecomment-480548175) of that is that DNS records won't get refreshed *at all*. This PR fixes that by setting [SocketsHttpHandler.PooledConnectionLifetime](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.soc …

Avoid using the same DNS records for good in ClearnetHttpClient

---

.editorconfig

> If a disposable object is not explicitly disposed before all references to it are out of scope, the object will be disposed at some indeterminate time when the garbage collector runs the finalizer of the object. Because an exceptional event might occur that will prevent the finalizer of the object from running, the object should be explicitly disposed instead.
https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca2000

Add code quality rule (CA2000: Dispose objects before losing scope)

---

WalletWasabi.Gui/Converters/PascalToPhraseConverter.cs
WalletWasabi/Backend/Models/FilterModel.cs
WalletWasabi/Mono/OptionSet.cs

> When calling `StringBuilder.Append` with a unit length string, consider using a `const char` rather than a unit length `const string` to improve performance.
https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1834

[Trivial] Use StringBuilder.Append(char) for single character strings

---

.editorconfig
WalletWasabi.Gui/Rpc/JsonRpcRequestHandler.cs
WalletWasabi.Tests/UnitTests/Clients/WasabiClientTests.cs
WalletWasabi.Tests/UnitTests/Crypto/TranscriptTests.cs
WalletWasabi.Tests/UnitTests/NBitcoinTests.cs
WalletWasabi.Tests/UnitTests/Transactions/TransactionFactoryTests.cs
WalletWasabi.Tests/UnitTests/Transactions/TransactionProcessorTests.cs
WalletWasabi.Tests/UnitTests/Wabisabi/CredentialTests.cs
WalletWasabi/Crypto/ZeroKnowledge/LinearRelation/Knowledge.cs
WalletWasabi/Crypto/ZeroKnowledge/LinearRelation/Statement.cs
WalletWasabi/Extensions/NBitcoinExtensions.cs

> This rule flags the `Count` LINQ method calls on collections of types that have equivalent, but more efficient `Length` or `Count` property to fetch the same data. `Length` or `Count` property does not enumerate the collection, hence is more efficient.
https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1829

Add code quality rule (CA1829: Use Length/Count property instead of Enumerable.Count method)

---

WalletWasabi/Backend/Models/FilterModel.cs

`ArgumentException(string message, string paramName)`
The param name should be second.
https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca2208

Swap arguments order

---

azure-pipelines-windows.yml

Trying to find out why windows CI is the weakest point now. We are using an older vmImage.

Upgrade Windows CI vmImage

---

WalletWasabi.Tests/UnitTests/BitcoinCore/NodeBuildingTests.cs

`GetNodeVersionTestsAsync` appears to be flaky. I would give it more time. 
Part of #4880.

Tests: Set higher timeout for GetNodeVersionTestsAsync.

---

WalletWasabi.Documentation/BackendDeployment.md

With every dotnet major release, the publish directory changes. In this case, the old published directory remains there and can cause problems, recently I bumped into a problem where the backend was using old code because I forget to update the service file and because the files were still there I did not notice anything about this. 
Unfortunately `dotnet clean` does not delete the bin directory so I used `rm`. `;` denotes to run both commands sequentially independent of the failure or success of running of the first command.

Clean bin directory before publish on backend

---

WalletWasabi.Fluent.Desktop/Program.cs
WalletWasabi.Gui/Global.cs

`Global.InitializeNoWalletAsync` running in parallel with the creation of the window. We can detect multiple instances earlier and in case we can prevent the further execution of the software. I moved the check before `Global.InitializeNoWalletAsync` into program.cs.
Note that this will prevent running some CLI command as well like --version. To fix that further refactoring has to be done - not the goal of this PR.
Based on https://github.com/zkSNACKs/WalletWasabi/pull/4896

Move SingleInstanceChecker to program.cs from global

---

WalletWasabi.Fluent/Controls/ContentArea.axaml
WalletWasabi.Fluent/Controls/Dialog.xaml.cs
WalletWasabi.Fluent/ViewModels/AboutViewModel.cs
WalletWasabi.Fluent/Views/AboutView.axaml
WalletWasabi.Fluent/Views/MainView.axaml

[Fluent] Disable dismiss dialogs by clicking outside

---

.editorconfig
WalletWasabi.Backend/Controllers/BlockchainController.cs
WalletWasabi.Tests/RegressionTests/BuildTests.cs
WalletWasabi/Services/WasabiSynchronizer.cs

https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca2200
> Once an exception is thrown, part of the information it carries is the stack trace. The stack trace is a list of the method call hierarchy that starts with the method that throws the exception and ends with the method that catches the exception. If an exception is re-thrown by specifying the exception in the throw statement, the stack trace is restarted at the current method and the list of method calls between the original method that threw the exception and the current method is lost. To keep the original stack trace information with the exception, use the throw statement without specifying the exception.

CA2200: Rethrow to preserve stack details

---

WalletWasabi.Tests/UnitTests/BlockchainAnalysis/CoinJoinAnonscoreTests.cs
WalletWasabi/Blockchain/Analysis/BlockchainAnalyzer.cs

The idea is that if we participate in a coinjoin in the same level, then the probability of picking a random UTXO can be directly translated to the anonymity set. (Instead of like previously we just naively said our coins have the normal anonset minus our redundant coin count.)
If we see these outputs and the last 2 are ours, then the anonymity sets are what in parenthesis:
```
1(5), 1(5), 1(5), 1(5-1), 1(5-1)
```
```
1(5), 1(5), 1(5), 1(5/2), 1(5/2)
```

Translate Probabilities to Anonymity Sets

---

WalletWasabi/Helpers/Guard.cs
WalletWasabi/Tor/Socks5/Models/Bases/OctetSerializableBase.cs
WalletWasabi/Tor/Socks5/Models/Fields/ByteArrayFields/MethodsField.cs
WalletWasabi/Tor/Socks5/Models/Fields/ByteArrayFields/PasswdField.cs
WalletWasabi/Tor/Socks5/Models/Fields/ByteArrayFields/PortField.cs
WalletWasabi/Tor/Socks5/Models/Fields/ByteArrayFields/UNameField.cs
WalletWasabi/Tor/Socks5/Models/Fields/OctetFields/AtypField.cs
WalletWasabi/Tor/Socks5/Models/Fields/OctetFields/CmdField.cs
WalletWasabi/Tor/Socks5/Models/Fields/OctetFields/NMethodsField.cs
WalletWasabi/Tor/Socks5/Models/Fields/OctetFields/RepField.cs
WalletWasabi/Tor/Socks5/Models/Fields/OctetFields/RsvField.cs
WalletWasabi/Tor/Socks5/Models/Interfaces/IByteSerializable.cs
WalletWasabi/Tor/Socks5/Models/Messages/TorSocks5Response.cs
WalletWasabi/Tor/Socks5/TorSocks5Client.cs

This PR contains some changes from #4738 that can be reviewed. 
This work mostly finishes the job of converting Tor SOCKS5 classes to be immutable and as such they can be used as "constants" so that many allocations are not needed. It won't have any significant perf outcome but the code is more clear after the change and I guess it's more in line with the rest of the source code.
The PR can be reviewed commit by commit too.

Tor parallel bits - part 1

---

WalletWasabi/Logging/Logger.cs

This PR is a proposal to add thread IDs to logging messages. The result would be: 
```
2021-01-04 08:49:58 [1] INFO    FileSystemBlockRepository (24)  .ctor finished in 12 milliseconds.
2021-01-04 08:49:58 [1] INFO    Global (81)     .ctor finished in 58 milliseconds.
2021-01-04 08:50:00 [1] INFO    Program (53)    Wasabi GUI started (4944e1ef-38f6-4b12-a805-a91ed32f0ac5).
2021-01-04 08:50:59 [5] INFO    TransactionStore (34)   MempoolStore.InitializeAsync finished in 57 milliseconds.
2021-01-04 08:50:59 [8] INFO    TransactionStore (34)   ConfirmedStore.InitializeAsync finished in 44 milliseconds.
2021-01-04 08:50:59 [8] INFO    AllTransactionStore (40)        InitializeAsync finished in 84 milliseconds.
```
The reasons why that may be a good thing are:
* I find it useful in general for …

Add thread ID to logging messages.

---

WalletWasabi/Tor/Http/ClearnetHttpClient.cs
WalletWasabi/Tor/Http/IHttpClient.cs
WalletWasabi/Tor/Socks5/TorSocks5Client.cs

This PR extracts @lontivero commit from #4738. 
Explanation from the commit:
> According to the documentation (https://docs.microsoft.com/en-us/dotnet/api/system.security.authentication.sslprotocols?view=net-5.0) by default (None) is the recommended one because let the OS to negotiate the most secure connection.
>
> Side note: TLS is only for backward compatibility and TLS1.1 is being deprecated and it is disabled in most recent browsers and servers.
Cherry-picked from: https://github.com/zkSNACKs/WalletWasabi/pull/4738/commits/e54ea8922b63c2861dec62d366686c7e4618dd33

Tor parallel bits - part 5: Remove IHttpClient.SupportedSslProtocols.

---

WalletWasabi.Tests/RegressionTests/BackendTests.cs

`StringContent` is non-controversial.
I'm not sure whether you guys are ok with this change: https://github.com/zkSNACKs/WalletWasabi/compare/master...kiminuo:feature/2021-mising-usings?expand=1#diff-e988bb08724158f8009106903466a8b24156ae86036ea939337f7b84199b9770R223 It seems reasonable to me. I would prefer `BlockchainController service = Assert.NotNull(RegTestFixture.BackendHost.Services.GetService(typeof(BlockchainController)))` but `Assert.NotNull` does not return any object.

[easy] Add missing "using"s and fix nullability issue.

---

WalletWasabi.Tests/UnitTests/Tor/Http/Extensions/HttpRequestMessageExtensionsTests.cs
WalletWasabi/Tor/Http/Extensions/HttpRequestMessageExtensions.cs
WalletWasabi/Tor/Http/TorHttpClient.cs

This PR is best to be reviewed commit by commit.
Question: Is `ConnectHttpMethod` actually used? My wild guess is that this HTTP connect method was added before Tor SOCK5 "connect" command was used.

Tor parallel bits - part 6: HttpRequestMessageExtensions modifications.

---

WalletWasabi.Fluent/Controls/ConcatenatingWrapPanel.cs

Regarding the 3rd commit (to fix CodeFactor):
> Calls to members from a base class should not begin with base., unless a local override is implemented, and the developer wants to specifically call the base class member. When there is no local override of the base class member, the call should be prefixed with `this.` rather than `base.`.
https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1100.md

[Fluent] Use expression body for accessors

---

WalletWasabi.Fluent.Desktop/Program.cs
WalletWasabi.Fluent/ViewModels/MainViewModel.cs
WalletWasabi.Gui/Global.cs

This PR is about improving fluent project disposing logic by clearing the navigation stacks on close. When a ViewModel is cleared from navigation stack, its `DoNavigateFrom()` is called which calls `_currentDisposable?.Dispose();`

[Fluent] Clear navigation stacks on close

---

WalletWasabi.Gui/ViewModels/StatusBarViewModel.cs
WalletWasabi.Tests/IntegrationTests/TorTests.cs
WalletWasabi/Blockchain/Transactions/TransactionFactory.cs
WalletWasabi/CoinJoin/Client/Clients/AliceClientBase.cs
WalletWasabi/Services/WasabiSynchronizer.cs
WalletWasabi/Tor/Http/TorHttpClient.cs
WalletWasabi/Tor/Socks5/Exceptions/TorConnectCommandFailedException.cs
WalletWasabi/Tor/Socks5/Exceptions/TorConnectionException.cs
WalletWasabi/Tor/Socks5/Exceptions/TorException.cs

* This PR adds `TorException` class so that it will be possible to catch any Tor-related exception in Tor Parallel PR.
* This PR also unifies behavior of HTTP clients (TorHttpClient & ClearnetHttpClient) so that both throws `HttpRequestException`. For `TorHttpClient`, this `HttpRequestException` contains proper `TorException` as an inner exception of `HttpRequestException`.
This PR is based on feedback: https://github.com/zkSNACKs/WalletWasabi/pull/4986#issuecomment-761099455 and it is an alternative to #4986 which is generally not considered to be good.

Tor parallel bits - part 7 [second attempt]: Add TorException base class and add a few comments. 

---

WalletWasabi.Fluent/ViewModels/AddWallet/AddWalletPageViewModel.cs
WalletWasabi.Fluent/ViewModels/MainViewModel.cs

We decided to check and show legal agreement on wallet load. Reason - the client will have more time to download the file and loading the wallet is unavoidable for both newly generated or already existing wallets. 
Break down of https://github.com/zkSNACKs/WalletWasabi/pull/4995

Legal bits - part 1: Remove legal check at Add Wallet

---

WalletWasabi.Fluent/Views/AddWallet/LegalDocumentsView.axaml

The continue button seems like we are agreeing with the document but it but we are just viewing it. I removed the button so the user can just go back. 
Break down of #4995

Legal bits - part 2: Remove continue button

---

WalletWasabi/Helpers/ByteHelpers.cs

This PR proposes to change behavior of `ByteHelpers.FromHex(string hex)` which currently can return `null` value. 
I couldn't find any caller who would actually pass `null` and all the callers I have found does not handle null-case.

ByteHelpers: Do not allow "null" value.

---

WalletWasabi.Tests/UnitTests/Wabisabi/Backend/ConfigTests.cs

According to @danwalmsley it fails randomly.

Wait longer

---

WalletWasabi.Documentation/BackendDeployment.md

Documents the change in the number of threads used to process the rpc requests queue (from 4 to 8)

Document rpcthread setting

---

WalletWasabi.Fluent/Views/AddWallet/HardwareWallet/ConnectHardwareWalletView.axaml

[Nit-fix] Adjust the spacing to be equal in ConnectHardwareWalletView.

---

WalletWasabi/Blockchain/Transactions/TransactionFactory.cs
WalletWasabi/Helpers/Constants.cs

Closes https://github.com/zkSNACKs/WalletWasabi/issues/1543
RBF may have some privacy issues with it, but as transaction fees are raising it's getting inevitable to have it.
In the future we can have a "Speed Up" context menu item in the Transaction History, which would work as follows:
1. If normal TX, then RBF it.
2. If receiving TX, then CPFP it.
3. If coinjoin, then CPFP it - but MAKE SURE THE USER KNOWS THE COSTS.

Turn on RBF by default for every transaction

---

WalletWasabi.Fluent/ViewModels/AddWallet/HardwareWallet/ConnectHardwareWalletViewModel.cs
WalletWasabi.Fluent/Views/AddWallet/HardwareWallet/ConnectHardwareWalletView.axaml

This PR:
- fixes the issue when we automatically navigated to the next page without the `Continue` button click, after the user entered the passphrase on the device.
- Simplifies the cancel token handling by making the `CancelCts` non-nullable.

[Fluent] Hardware wallet (round 3)

---

WalletWasabi.Fluent.Desktop/packages.lock.json
WalletWasabi.Fluent/packages.lock.json
WalletWasabi.Gui/packages.lock.json
WalletWasabi.Packager/packages.lock.json
WalletWasabi.Tests/UnitTests/BitcoinCore/BitcoindBinaryHashesTests.cs
WalletWasabi.Tests/UnitTests/BitcoinCore/P2pBasedTests.cs
WalletWasabi.Tests/UnitTests/BitcoinCore/RpcBasedTests.cs
WalletWasabi.Tests/UnitTests/MockRpcClient.cs
WalletWasabi.Tests/XunitConfiguration/RegTestFixture.cs
WalletWasabi/BitcoinCore/Rpc/IRPCClient.cs
WalletWasabi/BitcoinCore/Rpc/RpcClientBase.cs
WalletWasabi/Helpers/Constants.cs
WalletWasabi/WalletWasabi.csproj
WalletWasabi/packages.lock.json

The release had just been announced on the Bitcoin dev mailing list - and also here https://github.com/zkSNACKs/WalletWasabi/pull/5074#issuecomment-770537615: https://bitcoinknots.org/files/0.21.x/0.21.0.knots20210130/
The website doesn't link these binaries yet.

Update to Bitcoin Knots 0.21.0

---

WalletWasabi.Tests/RegressionTests/CoinJoinTests.cs
WalletWasabi.Tests/RegressionTests/DosTests.cs
WalletWasabi/CoinJoin/Client/Clients/AliceClient4.cs
WalletWasabi/CoinJoin/Client/Clients/AliceClientBase.cs
WalletWasabi/CoinJoin/Client/Clients/CoinJoinClient.cs
WalletWasabi/Tor/TorMonitor.cs
WalletWasabi/WebClients/Wasabi/WasabiClientFactory.cs

Goal of this PR is to make sure that all `IHttpClient` instances are obtained via `WasabiClientFactory` (would be great to find a better name for this).
With this change, it should be possible in a next PR to actually make `TorHttpClient` non-disposable which would simplify more code and this would open path to make it easy to add the TCP pool for `TorHttpClient`.
Please review commit by commit.

Use IHttpClient in CoinJoinClient.

---

WalletWasabi.Tests/UnitTests/WabiSabi/Backend/UtxoPrisonWardenTests.cs
WalletWasabi.Tests/UnitTests/Wabisabi/Backend/ConfigTests.cs

One of these tests were randomly failing as pointed out by @kiminuo so I'll default them to 7 sec instead of 3, even though 3 should be more than sufficient, it's an xunit synchronization issue and the tests aren't testing these times anyway.

Increase test timeouts

---

WalletWasabi.Documentation/Guides/UpgradeTorDaemons.md
WalletWasabi/Helpers/IoHelpers.cs

This PR removes unused code.
This section https://github.com/zkSNACKs/WalletWasabi/blob/master/WalletWasabi.Documentation/Guides/UpgradeTorDaemons.md#digest-creation seems obsolete thanks to f6ccd89a. Should we delete it too?

IoHelpers: Remove unused "CheckExpectedHash" method.

---

WalletWasabi.Fluent/ViewModels/WalletManagerViewModel.cs

When user clicks wallet login and after that clicks on navbar item of other type than selectable (e.g. Add Wallet) selection can get lost as tracking of selected item is wrong. This fixes that scenario.

[Fluent] Track only selectable NavBarItemViewModel in wallet manager

---

WalletWasabi/Tor/Http/TorHttpClient.cs
WalletWasabi/Tor/Socks5/TorSocks5Client.cs

[Documentation](https://docs.microsoft.com/en-us/dotnet/api/system.net.sockets.tcpclient.connected?view=net-5.0) specifies that `TcpClient.Connected` behaves as follows:
> true if the Client socket was connected to a remote resource as of the most recent operation; otherwise, false.
Code led me to think that the original code relies on `TcpClient.Connected` meaning "Is connection up or not?" That would be a bug. But that's not what the code does. It checks whether the TCP connection was successfully connected. However, I find the new code is easier to follow, to understand and to argue about its behavior.
Review is easier with whitespace off: https://github.com/zkSNACKs/WalletWasabi/pull/5178/files?diff=split&w=1
Note: I have been chopping off bits of #4738 and we have been merging these …

Remove TorSocks5Client.Connected property

---

WalletWasabi.Tests/Helpers/WabiSabiFactory.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Backend/RegisterInputTests.cs
WalletWasabi/WabiSabi/Backend/Models/WabiSabiProtocolErrorCode.cs
WalletWasabi/WabiSabi/Backend/PostRequests/InputRegistrationHandler.cs
WalletWasabi/WabiSabi/Backend/PostRequests/PostRequestHandler.cs
WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
WalletWasabi/WabiSabi/Backend/Rounds/Round.cs

If Alice was already registered
- to the same round and the phase is input registration: update Alice
- to the same round and the phase isn't input registration: throw wrong round exception
- to another round and the phase is input registration: update Alice
- to another round and the phase isn't input registration: throw Alice already registered exception
I'm not too happy with the implementation as the logic is in two different places, it should be improved somehow.
Even the behavior was wrong, because of the locking all over the place. I won't be optimizing for performance now. Arena locks everything.

[WabiSabi] Handle Alice if already registered

---

WalletWasabi.Fluent/Views/NavBar/NavBar.axaml

When the login indicator appeared the button's height increased a bit. This fixes it.
Before:
After:

[Fluent] Keep NavBarItem height when login inicator is visible

---

WalletWasabi.Backend/Controllers/ChaumianCoinJoinController.cs

I think `RemoveAlicesIfAnInputRefusedByMempoolAsync` is called twice, but please check me. I think `ExecuteNextPhaseAsync` will call `MoveToConnectionConfirmationAsync` and that also calls `RemoveAlicesIfAnInputRefusedByMempoolAsync`. @yahiheb @kiminuo you guys are good at spotting off by ones. May I ask one of you to make sure I'm right or wrong?

Reduce RPC calls in coinjoins

---

WalletWasabi/Extensions/LinqExtensions.cs
WalletWasabi/Extensions/RPCClientExtensions.cs

My local full node is returning the same target for more estimation requests. I think if it does not have enough data it will return the closest one. For example, if the node has only one estimation then it will return the exact same one on each request not matter what was the request target.

Fix duplicate item exception in GetFeeEstimations

---

WalletWasabi/Wallets/WalletManager.cs

Please review commit by commit.
I have also noticed how `IsInitialized` property is used:
```csharp
while (!IsInitialized)
{
await Task.Delay(100, CancelAllInitialization.Token).ConfigureAwait(false);
}
```
where `IsInitialized` not synchronized and it is used in multiple threads (at least it seems so). `Task.Delay` is a workaround here, it would be nicer to use Cleary's [AsyncManualResetEvent](https://github.com/StephenCleary/AsyncEx/blob/master/src/Nito.AsyncEx.Coordination/AsyncManualResetEvent.cs) or `SemaphoreSlim`

WalletManager: Nits

---

WalletWasabi.Fluent/Helpers/CoinPocketHelper.cs
WalletWasabi.Tests/UnitTests/Transactions/TransactionProcessorTests.cs

This PR contains a method with tests that can be used when the Wallet coins are shown in clusters according to their label. 
- If the label is the same, the coins belong to the same cluster. 
- If the label is empty, we don't know anything about the coin, so it will be listed separately.

Add GetPockets method

---

WalletWasabi.Backend/wwwroot/index.html

Removed underlines from social media links in the footer (website). There was a small graphical issue when pointing with the cursor.

Remove text-decoration and color from social hyperlinks

---

WalletWasabi.Documentation/BackendDeployment.md

The last time we restarted the server Knots [lost mempool with an error message about serialization](https://github.com/zkSNACKs/WalletWasabi/pull/5118). The goal of this PR is to add status check commands to make us able to verify the status of the services before we move forward, for example with a shutdown. 
Based on this https://github.com/zkSNACKs/WalletWasabi/pull/4644
P.S. this command might seem to be scary but this is how it works. The goals were the following one-liner and easy to check.

Add status checks to BackendDeployment.md

---

WalletWasabi.Tests/Helpers/BitcoinFactory.cs
WalletWasabi.Tests/RegressionTests/CoinJoinTests.cs
WalletWasabi.Tests/UnitTests/BlockchainAnalysis/CoinJoinAnonscoreTests.cs
WalletWasabi.Tests/UnitTests/BlockchainAnalysis/NormalSpendAnonScoreTests.cs
WalletWasabi.Tests/UnitTests/BlockchainAnalysis/PubKeyReuseAnonScoreTests.cs
WalletWasabi.Tests/UnitTests/BlockchainAnalysis/SelfSpendAnonScoreTests.cs
WalletWasabi/Blockchain/Analysis/BlockchainAnalyzer.cs
WalletWasabi/Blockchain/Keys/HdPubKey.cs

The anonymity set calculation whenever we processed a transaction twice thought it's an address reuse.
fixes #5287
fixes https://github.com/zkSNACKs/WalletWasabi/issues/4916

Fix anonymity set bug

---

WalletWasabi/CoinJoin/Client/Clients/Queuing/DequeueReason.cs
WalletWasabi/Extensions/EnumExtension.cs
WalletWasabi/Hwi/Models/HardwareWalletModels.cs
WalletWasabi/Models/FriendlyNameAttribute.cs
WalletWasabi/Wallets/PasswordFinder/PasswordFinderCharset.cs

This PR creates a custom attribute called `FriendlyName` and uses this instead of the `Description` attribute.
This improves readability. FriendlyName attribute is more meaningful, if someone looks at it, will know immediately what does it mean.

Use FriendlyName attribute instead of Description attribute

---

WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
WalletWasabi/WabiSabi/LoggerTools.cs

Basically, the PR is as the title. I also simplified the logic to have only one failure path, better for logging and error handling. 
Oh and one more thing, I tried to create something to not forget the round Id every time we have to log something related to the round like `$"Round ({round.Id}):`. So I ended up having `LoggerTools.cs`. This can be done in a various way but IMO the less SPAM in the code the better. I can even move that huge logging part about the CoinJoin transaction details into `LoggerTools.cs `.
I know this is a new concept, so we can N/ACK it. 
- Create an extension method into `Round` like `string ToLog(string message)` and call `Logger.Log(round.ToLog("tx broadcast"))`

Add Logging in Signing and Broadcasting phase

---

WalletWasabi.Tests/Helpers/WabiSabiFactory.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepOutputRegistrationTests.cs
WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepTransactionSigningTests.cs

Basically as the title. The cleanest way to do this was to dismiss the foreach and duplicate the code.

Remove ugliSolution var from tests

---

WalletWasabi.Tests/UnitTests/AllFeeEstimateTests.cs

```
##[error]WalletWasabi.Tests/UnitTests/AllFeeEstimateTests.cs(216,16): Error CS0266: Cannot implicitly convert type 'long' to 'ulong'. An explicit conversion exists (are you missing a cast?)
```
Error during build debug, trying to see if this occurs again.

Replace L with UL in AllFeeEstimateTests.cs

---

WalletWasabi.Tests/UnitTests/Transactions/TransactionProcessorTests.cs
WalletWasabi/Bases/NotifyPropertyChangedBase.cs
WalletWasabi/Blockchain/TransactionOutputs/SmartCoin.cs
WalletWasabi/Blockchain/TransactionProcessing/TransactionProcessor.cs

After CoinJoin, your new coin's anonimity set would decrease back to 1 until confirmation, altough it should have a new, increased anonimitySet value.
Also, after opening your wallet, all unconfirmed coin's anonimity set would decrease back to 1 after several seconds of opening.
This PR should fix both.

Potentially fix anonySet decrease bug

---

WalletWasabi.Tests/UnitTests/Transactions/TransactionProcessorTests.cs
WalletWasabi/Bases/NotifyPropertyChangedBase.cs
WalletWasabi/Blockchain/TransactionOutputs/SmartCoin.cs

When an already procceded transaction comes in, we add the **SmartCoin** to the _walletInput_ regardless of the equality check.
There is no loss or harm, but still gives us the right anon set.
- RaiseAndSetIfRefChanged
(it was unnecessary)

Alternative solution for AnonSet bug

---

WalletWasabi.Tests/UnitTests/BitcoinCore/P2pBasedTests.cs

Contributes to #4244.
This test fails very often and this should help to mitigate the issue. 
@molnard expressed once a concern that bumping the timeouts is not that great. The thing here is that if you have more and more tests, in the current design it is somewhat unavoidable unless there some bigger change how tests are being executed.
Just for the sake of making myself clear, there are several things we can consider to limit these timeout bumps in the long term:
* Split one test project (kind of non-standard really) to "one C# project ~ one test C# project" and run one test project after another.
* fun fact: https://github.com/zkSNACKs/WalletWasabi/pull/5051 cannot be merged because we have only one test project. 
* Split tests in the current test project to some smaller …

MempoolNotifiesAsync times out often.

---

WalletWasabi.Tests/UnitTests/Transactions/TransactionProcessorTests.cs
WalletWasabi/Blockchain/Transactions/TransactionStore.cs

When reviewing #5314, I have noticed that https://github.com/zkSNACKs/WalletWasabi/blob/90484f2f27bba5bc688a6bdeec175e5d5b93c39c/WalletWasabi.Tests/UnitTests/Transactions/TransactionStoreTests.cs#L90 is not disposed correctly.
This PR attempts to fix that.

TransactionProcessorTests: Fix missing disposal of TransactionStore

---

WalletWasabi.Tests/UnitTests/InvalidTxExceptionTests.cs
WalletWasabi/Exceptions/InvalidTxException.cs

This PR overrides the default `InvalidTxException.Message` to provide better information about invalid transactions created by Wasabi as in #5259
The exception message, contains the serialized invalid transaction and all the collected reason why it is invalid:
```
Invalid transaction:
010000000aabe301115d20f1061b9f60fdd8bc3e8d8861cb98d317b2655ccee982356bda285000000000ffffffff5b8cfe1b2e169f6cedf366ace365ab007aadd5314f13fefa4c29a402379605466000000000ffffffff6a32b604e93bdf81975d4ad09f
04a2a40aeba2fb4b5aad72e14c911c81fa49b04c00000000ffffffff21e8c966e190c11332a83fbb43773c5be528551b4dd829e9283ca2510e107c584600000000ffffffff323f400b4f038bc6f36c1243c31856999cfe6962732bbe0eb4fc50452931b6
0b4000000000ffffffff3cb3b5f132909a6add1406285527e34951e90f57e584364204531078119177b66300000000ffffffff74e08d6ada …
```

Provide useful info about invalid transactions

---

WalletWasabi.Tests/UnitTests/Transactions/TransactionProcessorTests.cs
WalletWasabi/Blockchain/TransactionOutputs/SmartCoin.cs
WalletWasabi/Blockchain/TransactionProcessing/TransactionProcessor.cs
WalletWasabi/Blockchain/Transactions/SmartTransaction.cs

I was reviewing the RBF logic because I suspected (still) that the transaction stores are inconsistent after RBF (true) is the default value and I found two problems:
1. In a long chain of transactions where only the first one signals RBF, that one and the next one are recognized as replaceable while the rest are not.
2. In some (rare) cases when the user broadcast a replacement transaction but the original is mined first the wallet state is broken.
These are not the final solutions, I am uploading them here for discussion and because the tests are okay (the code is not).

Fix spent rbf

---

WalletWasabi.Fluent/ViewModels/NavBar/NavBarItemViewModel.cs
WalletWasabi.Fluent/ViewModels/NavBar/NavBarViewModel.cs
WalletWasabi.Fluent/ViewModels/Navigation/NavigationStack.cs
WalletWasabi.Fluent/ViewModels/Wallets/Actions/AdvancedWalletActionViewModel.cs
WalletWasabi.Fluent/ViewModels/Wallets/Actions/CoinJoinWalletActionViewModel.cs
WalletWasabi.Fluent/ViewModels/Wallets/ClosedWalletViewModel.cs
WalletWasabi.Fluent/ViewModels/Wallets/Receive/ReceiveViewModel.cs
WalletWasabi.Fluent/ViewModels/Wallets/Send/SendViewModel.cs
WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModelBase.cs

- Removes the unused NavBarItem.Parent Property
- Fixes Clear implementation which was keeping the page you navigated away from on the stack.
- Root navbar items, clear the stack when navigated to, children dont.

Navigation fixes

---

WalletWasabi.Fluent/ViewModels/Wallets/Send/PrivacyControlViewModel.cs

In this case this screen can only inform the user, save them a step by pre-selecting the item.

privacy control - pre-select if there is only 1 item.

---

WalletWasabi/Hwi/HwiClient.cs

The missing parentheses broke the HW Katas, it's fixed and should work just fine now.

Fixed logic in BuildOptions in HwiClient.cs

---

WalletWasabi/Blockchain/Keys/KeyManager.cs
WalletWasabi/Helpers/ImportWalletHelper.cs

When a wallet gets imported the `BlockchainState.Height` should be 0, thus the wallet will be rescanned.

Force wallet rescan after import

---

WalletWasabi.Fluent/Views/MainView.axaml

The normal dialog was not visible when the fullscreen dialog is visible. This because the fullscreen dialog covered the normal one.
How to test:
1. Click on Add Wallet.
2. Import a wallet that is already added.
3. See error dialog.
(Before this fix, the dialog was not visible until the fullscreen dialog was not closed)

[Fluent] Fix normal dialog visibility when fullscreen dialog is visible

---

WalletWasabi.Gui/Tabs/WalletManager/RecoverWallets/RecoverWalletViewModel.cs

Fix mnemonic phrase length (fixes https://github.com/zkSNACKs/WalletWasabi/issues/5212)
Valid lengths are 12, 15, 18, 21 and 24.
@danwalmsley this have to be fixed on Fluent too. I tag @jmacato because it seems he was involved in the implementation of this in Fluent.

Fix mnemonic phrase length (GUI only)

---

WalletWasabi/Blockchain/TransactionProcessing/TransactionProcessor.cs
WalletWasabi/Wallets/Wallet.cs
WalletWasabi/Wallets/WalletManager.cs

Background: https://github.com/zkSNACKs/WalletWasabi/pull/5376#issuecomment-801425896
What does it improve?
- There was a dirty dictionary in the wallet manager that paired wallets to hashsets for the coinjoin processor. It was moved to the transaction processor so now we can be sure that all the transactions those were processed are there.
- We don't reprocess transactions when they come from mempool now. (Be much more careful with other places though.)
This PR has an effect on many things probably, but one reproducible issue is at processing unconfirmed coinjoins when Bitcoin Core is running. In that case after we received the coinjoins from the mempool we sent it to the Bitcoin Core RPC, which propagated us the transaction back and we processed it again. Now we don't do that.

Prevent some duplicated tx processing

---

WalletWasabi.Tests/Helpers/TestNodeBuilder.cs
WalletWasabi/BitcoinCore/CoreNode.cs
WalletWasabi/BitcoinCore/CoreNodeParams.cs

Try to increase the regression test performance by reducing the number of thread used by the bitcoin node and its workload. In this case we make sure to not create/publish a new onion service and listen on it, we do not try to discover new peers and do not try to open/save mempool file during initialization and shutdown.

More node parameters

---

azure-pipelines-cd.yml

We only want to have a CD if something merged into the master - not when creating a PR.

Disable CD build for PR-s

---

WalletWasabi.Fluent/Views/Wallets/Send/OptimisePrivacyView.axaml
WalletWasabi.Fluent/Views/Wallets/Send/PrivacySuggestionControl.axaml

This PR fixes the layout issue and also handles when the dialog is on the smallest size.
before:
after:

[Fleunt] Fix Optimise Privacy layout

---

WalletWasabi.Fluent/Controls/CurrencyEntryBox.axaml.cs

Fixes:
cc @danwalmsley @soosr 
@MaxHillebrand please test this thoroughly

[Fluent] Fix up CurrencyEntryBox

---

WalletWasabi.Fluent/Controls/Dialog.axaml
WalletWasabi.Fluent/Views/Dialogs/Authorization/HardwareWalletAuthDialogView.axaml
WalletWasabi.Fluent/Views/Dialogs/Authorization/PasswordAuthDialogView.axaml

This PR adds minimum height and width to the dialog content, thus the CompactDialog will not look weird when only a progress ring is visible.
This PR also fixes the layout issue described here https://github.com/zkSNACKs/WalletWasabi/pull/5369.

[Fluent] Dialog min size

---

WalletWasabi.Tests/UnitTests/BitcoinCore/IndexBuilderServiceTests.cs
WalletWasabi.Tests/UnitTests/Data/VerboseBlock.json
WalletWasabi.Tests/WalletWasabi.Tests.csproj
WalletWasabi/BitcoinCore/Rpc/Models/RpcPubkeyType.cs
WalletWasabi/BitcoinCore/Rpc/RpcParser.cs
WalletWasabi/Blockchain/BlockFilters/IndexBuilderService.cs

This PR includes taproot scripts in the compact filters. This is necessary for Wasabi to detect taproot payments.
**UNTESTED**

Support taproot script in filters

---

WalletWasabi/Wallets/Wallet.cs

As far as I can understand the code, it looks to me that `filterModel.Filter` cannot be `null` thanks to:
https://github.com/zkSNACKs/WalletWasabi/blob/5a6d80f14b63b6dbb247489293c9f80de3361d0d/WalletWasabi/Backend/Models/FilterModel.cs#L15
(I have found this when trying to understand #5418 better.)

Wallet: Remove always-true if statement

---

WalletWasabi.Gui/Global.cs
WalletWasabi.Tests/IntegrationTests/P2pTests.cs
WalletWasabi.Tests/RegressionTests/BuildTests.cs
WalletWasabi.Tests/RegressionTests/CoinJoinTests.cs
WalletWasabi.Tests/RegressionTests/SendTests.cs
WalletWasabi.Tests/RegressionTests/WalletTests.cs
WalletWasabi/Wallets/Wallet.cs
WalletWasabi/Wallets/WalletManager.cs

Related to #5418.
Removal of `Nodes` from `Wallet` looks like a small win to me.

Wallet & superfluous Nodes

---

WalletWasabi.Tests/UnitTests/Crypto/ProofSystemTests.cs
WalletWasabi/Crypto/Groups/Generators.cs
WalletWasabi/Crypto/ZeroKnowledge/ProofSystem.cs

This PR refactors the powers of two generators so there is no mutable state, and makes the specification of range proof widths more constrained and consistent between the client and issuer.

Static -2^i * Gh generators

---

WalletWasabi/Stores/IndexStore.cs

The exactly same `IoHelpers.EnsureDirectoryExists(workFolderPath)` call is in constructor. I believe this is just an oversight.

IndexStore: Remove extra "IoHelpers.EnsureDirectoryExists(WorkFolderPath);".

---

WalletWasabi/Io/SafeIoManager.cs

This PR does not change behavior, it not removes "new" keywords that emits warnings because `IoManager` does not contain those methods.

SafeIoManager: Remove extra "new"

---

WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterOutputTests.cs
WalletWasabi/WabiSabi/Backend/Models/WabiSabiProtocolErrorCode.cs
WalletWasabi/WabiSabi/Backend/PostRequests/ArenaRequestHandler.cs
WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs

This is redundant with the allowed script check because that allows
a strict subset of standard outputs (only p2wpkh), but that check can be
parameterized in the round metadata later in order to allow payment from
CoinJoins to other address types.

[WabiSabi] Only allow standard outputs
