WalletWasabi/WalletWasabi

WalletWasabi/BitcoinCore/Rpc/CachedRpcClient.cs
Draft, because the value(s) should be checked by others, too.
If you have an idea, which other cache expiration time should be increased, feel free to suggest!
=> [Backend] Increase Fee cache expiration time

WalletWasabi.Documentation/ServiceStatus.md
Let me know if you know more or feel free to add.
=> Add a link collection about useful status pages

WalletWasabi.Tests/Helpers/WabiSabiFactory.cs, WalletWasabi/WabiSabi/Client/CoinJoinClient.cs, WalletWasabi/WabiSabi/Client/CoinJoinTrackerFactory.cs, WalletWasabi/WabiSabi/Client/LiquidityClueHelper.cs
~~Please, do not review yet. I need to have your ci tests run before that, since I'm not able to run them all locally.~~ Ready for review!
This PR allows for implementation of Wabisabi client library which will be used by Trezor.
=> Liquidity clue abstraction

WalletWasabi.Fluent/Views/Wallets/CoinJoinSettingsView.axaml, WalletWasabi/Blockchain/Keys/KeyManager.cs
https://github.com/zkSNACKs/WalletWasabi/issues/7122#issuecomment-1272601134
=> [Trivial] Fix tooltip about auto-coinjoin start if the balance is less than PlebStopThreshold

WalletWasabi.Fluent/Helpers/TransactionHelpers.cs, WalletWasabi.Fluent/ViewModels/Dialogs/AddressEntryDialogViewModel.cs, WalletWasabi.Fluent/ViewModels/Dialogs/LabelEntryDialogViewModel.cs, WalletWasabi.Fluent/ViewModels/Wallets/Advanced/WalletCoins/WalletCoinsViewModel.cs, WalletWasabi.Fluent/ViewModels/Wallets/Send/ChangeAvoidanceSuggestionViewModel.cs, WalletWasabi.Fluent/ViewModels/Wallets/Send/PrivacySuggestionsFlyoutViewModel.cs, WalletWasabi.Fluent/ViewModels/Wallets/Send/SendViewModel.cs, WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionInfo.cs, WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionPreviewViewModel.cs, WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionSummaryViewModel.cs
- Destination address is moved into the class
- IsFixedAmount is moved into the class
- Easier to read as everything is in the same class
- fewer params
- Fixed the bug when pasted address contained a label and it hasn't been taken into account
=> [VDG] move things to `TransactionInfo.cs`

WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/PrivacyControlTileViewModel.cs, WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/PrivacyRing/PrivacyBarViewModel.cs, WalletWasabi.Fluent/Views/Wallets/Home/Tiles/PrivacyBar/PrivacyBar.axaml, WalletWasabi.Fluent/Views/Wallets/Home/Tiles/PrivacyControlTileView.axaml
cc @ichthus1604 @zkSNACKs/visual-design-group 
Before: 
After:
=>  [VDG] Fix privacy bar showing as empty space if there's no privacy data. 

WalletWasabi.Fluent/ViewModels/Wallets/LoadingViewModel.cs, WalletWasabi.Fluent/Views/Wallets/LoadingControl.axaml
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/9291
cc @soosr @zkSNACKs/visual-design-group
=> Remove unused StringFormat in LoadingControl StatusText binding.

WalletWasabi.Fluent.Desktop/packages.lock.json, WalletWasabi.Fluent/WalletWasabi.Fluent.csproj, WalletWasabi.Fluent/packages.lock.json
Required for https://github.com/zkSNACKs/WalletWasabi/pull/9283 @molnard
=> [VDG] Update TreeDataGrid to NuGet version 0.10.18

WalletWasabi.Backend/wwwroot/about.html, WalletWasabi.Backend/wwwroot/contribution.html, WalletWasabi.Backend/wwwroot/faq.html
This fixes some broken legal documents and the supported hardware wallets links.
=> [Trivial] Fix some links on the website

WalletWasabi.Backend/wwwroot/contribution.html
Sorry about the formatting changes, it was `CodeMaid`.
=> Fix broken link on website

WalletWasabi/Blockchain/Transactions/TransactionFactory.cs
Related https://github.com/zkSNACKs/WalletWasabi/pull/9289
=> Log less in tx build - it is called a many times

WalletWasabi.Backend/wwwroot/index.html
Reverts zkSNACKs/WalletWasabi#9288
=> Revert "Updated docs links"

WalletWasabi/Blockchain/Transactions/TransactionFactory.cs
This was edited in #9304 but IMO it is more clear to use say `Sending`
=> [Trivial] Clarify tx build log message

WalletWasabi/WabiSabi/Client/CoinJoinManager.cs, WalletWasabi/WabiSabi/Client/RoundStateAwaiters/RoundStateUpdater.cs
Closes https://github.com/zkSNACKs/WalletWasabi/pull/9311
Closes https://github.com/zkSNACKs/WalletWasabi/pull/9300
=> Slow down requests when not CoinJoining

WalletWasabi/BitcoinCore/Rpc/CachedRpcClient.cs
Partially fixes: https://github.com/zkSNACKs/WalletWasabi/issues/9299
=> Adjust MemoryCache expire dates

WalletWasabi.Fluent/Global.cs
This PR is for testing purpose only. The idea is to use it to test by coinjoining in testnet.
=> Use fallback mechanism by default

WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModel.cs
Fixes #9331
FWIW this issue would have been avoided if we made MusicBox visible only on hover (if we merged #9181).
=> [VDG] Hide MusicBox always if the wallet is watch-only

WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModel.cs
fixes https://github.com/zkSNACKs/WalletWasabi/issues/9337
fixes https://github.com/zkSNACKs/WalletWasabi/issues/9346
=> [VDG] fix visibility of musicbox on hover

WalletWasabi.Packager/Program.cs
Follow-up to #8383
If you have a linux machine, you can test this by:
```
cd WalletWasabi.Packager
dotnet build && dotnet run -- --publish
```
=> Packager: Make packaging work on linux

WalletWasabi.Fluent/ViewModels/Dialogs/ManualCoinJoinProfileDialogViewModel.cs
for consistency with the wording
to prevent confusion
=> [VDG] improve Coinjoin Strategy Settings title

WalletWasabi.Fluent/Helpers/TransactionHelpers.cs, WalletWasabi.Fluent/ViewModels/Wallets/Advanced/WalletCoins/WalletCoinsViewModel.cs, WalletWasabi.Fluent/ViewModels/Wallets/Send/ChangeAvoidanceSuggestionViewModel.cs, WalletWasabi.Fluent/ViewModels/Wallets/Send/LabelSelectionViewModel.cs, WalletWasabi.Fluent/ViewModels/Wallets/Send/SendViewModel.cs, WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionInfo.cs, WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionPreviewViewModel.cs, WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionSummaryViewModel.cs, WalletWasabi.Tests/UnitTests/UserInterfaceTest/PocketSelectionTests.cs
It just simply makes more sense.
=> [Trivial] Rename `UserLabels` to `Recipient`

WalletWasabi.Documentation/WasabiCompatibility.md
It is possible to install Wasabi on Tails according to some some user.
https://www.reddit.com/r/WasabiWallet/comments/ybojg6/comment/ithh7gz/?utm_source=share&utm_medium=web2x&context=3
=> [Trivial] Clarify using Wasabi on Tails

WalletWasabi.Fluent/Models/UiTriggers.cs, WalletWasabi.Fluent/ViewModels/Wallets/CoinJoinSettingsViewModel.cs
They will trigger instantly and only once on a subscription.
=> [VDG] Remove `Throttle` from `UiTriggers`

WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/PrivacyControlTileViewModel.cs
=> [VDG] Prevent privacy ring dialog from opening for an empty wallet

WalletWasabi.Fluent/Models/UiTriggers.cs
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/9386
=> [VDG] Fix transaction doesn't appear (only notification)

WalletWasabi.Fluent/Models/UiTriggers.cs
follow up for https://github.com/zkSNACKs/WalletWasabi/pull/9388.
=> [VDG] fix possible called from invalid thread

WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionSummaryViewModel.cs
=> [VDG] Transaction Preview: Hide fiat amounts when exchange rate is zero

WalletWasabi.Fluent/Behaviors/ShowAttachedFlyoutWhenFocusedBehavior.cs
=> [VDG] Fix SearchBar flyout issue on theme change

WalletWasabi.Fluent/ViewModels/AddWallet/WalletNamePageViewModel.cs
Alternative https://github.com/zkSNACKs/WalletWasabi/pull/6796
Closes https://github.com/zkSNACKs/WalletWasabi/pull/6796
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/6294
=> [VDG] Only recreate mnemonics if the user start everything over

WalletWasabi.Fluent/Views/Wallets/Home/History/HistoryTable.axaml
https://github.com/zkSNACKs/WalletWasabi/pull/9391 got merged before it was finalized.
=> fix empty history style

WalletWasabi.Fluent/Views/AddWallet/Create/ConfirmRecoveryWordsView.axaml
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/9438
=> [VDG] Add Wallet - fix delay after password

WalletWasabi.Fluent/ViewModels/TransactionBroadcasting/BroadcasterViewModel.cs
nit
broadcasting 1 tx at a time
& rest of dialog also uses singular
=> [VDG] [trivial] broadast TX caption typo

WalletWasabi.Fluent/Controls/PrivacyContentControl.axaml, WalletWasabi.Fluent/Views/Wallets/Advanced/WalletCoins/Columns/LabelsColumnView.axaml
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/9433
=> [VDG] Discreet Mode - fix hover on empty labels in Wallet Coins

WalletWasabi.Fluent/Controls/PrivacyContentControl.axaml, WalletWasabi.Fluent/Views/Wallets/Advanced/WalletCoins/Columns/LabelsColumnView.axaml, WalletWasabi.Fluent/Views/Wallets/Home/History/Columns/LabelsColumnView.axaml
- Builds upon @soosr's PR #9460 
- Fixes #9473 for both history table and Ctrl+C+D Coinlist
- @SuperJMN: It might be worth checking your Coin Selection PR once this one is merged
=> [VDG] Discreet control alignment

WalletWasabi.Tests/Helpers/WabiSabiFactory.cs, WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepOutputRegistrationTests.cs
Testing this PR https://github.com/zkSNACKs/WalletWasabi/pull/9172
=> Add test for preventing double output registration 

WalletWasabi.Fluent/ViewModels/Wallets/CoinJoinStateViewModel.cs
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/9451
=> [VDG] fix calculation of `AreAllCoinsPrivate`

WalletWasabi.Fluent/ViewModels/Wallets/Send/LabelSelectionViewModel.cs, WalletWasabi.Fluent/ViewModels/Wallets/Send/PrivacyControlViewModel.cs, WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionPreviewViewModel.cs, WalletWasabi.Tests/UnitTests/UserInterfaceTest/PocketSelectionTests.cs
It reduces the number of prebuilds from 5 to 1.
In my test a sending generated 8 log messages, with this PR it is only 4 which is ok as 1 is the prebuilt one, 1 is the actual transaction, and there are 2 changeless transactions.
=> [VDG] Decrease prebuilds

WalletWasabi.Fluent/Views/Wallets/WalletView.axaml
=> Order settings

.github/workflows/auto-add-to-projcet.yml
Reverts zkSNACKs/WalletWasabi#9497
=> Revert "Enable auto add action for PRs"

WalletWasabi.Fluent/ViewModels/AddWallet/Create/ConfirmRecoveryWordsViewModel.cs, WalletWasabi.Fluent/Views/AddWallet/Create/RecoveryWordsView.axaml
This adds a suggestion to store recovery words in various places, while making the text shorter to declutter the UI.
=> [Trivial] simplify backup message 

WalletWasabi.Packager/ArgsProcessor.cs, WalletWasabi.Packager/Program.cs, WalletWasabi.Packager/Properties/launchSettings.json, WalletWasabi/Helpers/Constants.cs, WalletWasabi/Helpers/WasabiSignerHelpers.cs
Part of https://github.com/zkSNACKs/WalletWasabi/pull/9259
Add files of:
- SHA256SUMS - contains SHA256 hashes and filenames
- SHA256SUMS.asc - contains SHA256 hashes and filenames + zkSNACKs official pgp signature 
- SHA256SUMS.wasabisig - contains signature generated with ECDSA from SHA256SUMS.asc file.
SHA256SUMS and SHA256SUMS.asc were generated with standard command line tools.
=> Packager SHA256SUMS.asc 

.github/workflows/auto-add-to-projcet.yml
Reverts zkSNACKs/WalletWasabi#9524, it did not work.
=> Revert "Auto-add discussions to project board"

WalletWasabi/WabiSabi/Models/MultipartyTransaction/ConstructionState.cs
Closes https://github.com/zkSNACKs/WalletWasabi/issues/9323
This is **not** THE solution but is one that we can use while we find the real solution. The magic number was extracted from the logs (see #9323)
=> Tolerate some missing fee rate

WalletWasabi/WabiSabi/Models/MultipartyTransaction/ConstructionState.cs
Fixup https://github.com/zkSNACKs/WalletWasabi/pull/9530 because t was not enough margin according to the logs.
=> Increase fee rate tolerance

WalletWasabi.Fluent/ViewModels/AddWallet/HardwareWallet/ConnectHardwareWalletViewModel.cs
=> [VDG] improve connect hww & enter pin message

WalletWasabi.Fluent/TreeDataGrid/PlainTextCell.cs, WalletWasabi.Fluent/TreeDataGrid/PlainTextColumn.cs, WalletWasabi.Fluent/TreeDataGrid/PlainTextElementFactory.cs, WalletWasabi.Fluent/TreeDataGrid/PrivacyElementFactory.cs, WalletWasabi.Fluent/TreeDataGrid/TreeDataGridPlainTextCell.cs, WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryViewModel.cs, WalletWasabi.Fluent/Views/Wallets/Home/History/HistoryTable.axaml
To be used for text column in TDG where we don't need privacy content.
Tested it on history table, seems to work fine.
Usage: https://github.com/zkSNACKs/WalletWasabi/pull/9514/commits/3cee916983ec779d567f4dc18c81a13b0c5463df
=> [VDG] Add PlainTextColumn for TreeDataGrid

WalletWasabi.Fluent/ViewModels/SearchBar/SettingsSearchSource.cs
Found while working on something.
Just to be consistent, doesn't change functionality, it just bothered my eye.
=> [Trivial] Fix lambda consistency

WalletWasabi/WabiSabi/Models/MultipartyTransaction/ConstructionState.cs
Further relaxation of mining fee rates to prevent aborting rounds for miscalculations.
=> Relax mining fee rate diff.

WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
https://github.com/zkSNACKs/WalletWasabi/pull/9555#discussion_r1025005674
=> Clarify break condition

WalletWasabi.Fluent/ViewModels/SearchBar/SearchBarViewModel.cs
=> [VDG] [Trivial] Fix different sort ordering in items between searches

WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
PR that addresses: https://github.com/zkSNACKs/WalletWasabi/pull/9569/files#r1026607948
=> [minor] `CoinJoinClient`: Simplify a line

WalletWasabi.Fluent/Config.cs, WalletWasabi.Fluent/Global.cs, WalletWasabi/Tor/TorMonitor.cs
This PR removes the fallback mechanism which allows to switch from accessing the onion service to the clearnet URI. We use only the clearnet URI at the moment.
David asked me to do this.
=> Remove fallback mechanism

WalletWasabi.Fluent/Controls/LabelsItemsPresenter.axaml
Fixes: https://github.com/zkSNACKs/WalletWasabi/issues/9600
=> [VDG] Fix LabelsItemsPresenter HorizontalAlignment

WalletWasabi.Fluent/Views/AddWallet/Create/RecoveryWordsView.axaml
As suggested here: https://github.com/zkSNACKs/WalletWasabi/pull/9575#issuecomment-1321757571 
and here https://github.com/zkSNACKs/WalletWasabi/pull/9575#issuecomment-1323414320
=> [Trivial] Improve recovery words warning text

WalletWasabi.Fluent/Models/UiTriggers.cs
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/9602
=> [VDG] Update history on new filter

WalletWasabi.Tests/Helpers/ArenaBuilder.cs, WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs, WalletWasabi/WabiSabi/WabiSabiCoordinator.cs
=> `Arena`: Remove unused `Network` parameter

WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItems/CoinJoinHistoryItemViewModel.cs, WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItems/CoinJoinsHistoryItemViewModel.cs, WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItems/HistoryItemViewModelBase.cs, WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItems/TransactionHistoryItemViewModel.cs
Addresses: https://github.com/zkSNACKs/WalletWasabi/issues/8582#issuecomment-1194026998
Master:
PR:
=> Fix negative OutgoingAmount in History

WalletWasabi/Backend/Models/FilterModel.cs
This is an idea how to make mature index loading a bit faster.
**Before:** MatureIndexFileManager loading finished in 6.6 seconds.
**After:** MatureIndexFileManager loading finished in 5.9 seconds.
Using debug configuration.
=> `FilterModel`: Faster implementation

WalletWasabi.Fluent/Views/Wallets/Home/Tiles/PrivacyRing/PrivacyRingDetailsView.axaml, WalletWasabi.Fluent/Views/Wallets/Home/Tiles/PrivacyRing/PrivacyRingView.axaml
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/9624
=> [VDG] fix discreet mode in privacy ring

WalletWasabi.Fluent/Views/Wallets/Send/TransactionPreviewView.axaml
=> [VDG] [trivial] remove handcursor for MaxPrivacy flyout at TX Preview

WalletWasabi.Fluent/ViewModels/AddWallet/LegalDocumentsViewModel.cs, WalletWasabi.Fluent/ViewModels/HelpAndSupport/AboutViewModel.cs, WalletWasabi.Fluent/ViewModels/HelpAndSupport/BugReportLinkViewModel.cs, WalletWasabi.Fluent/ViewModels/HelpAndSupport/DocsLinkViewModel.cs, WalletWasabi.Fluent/ViewModels/HelpAndSupport/UserSupportViewModel.cs
I've observed that some items in Help & Support offer captions that aren't useful and all and feel unprofessional.
This PR fixes them.
Current: 
This PR:
Feel free to suggest better texts :)
=> [VDG] [Trivial] Improve captions for SearchBar elements

WalletWasabi.Fluent/Views/Wallets/Home/Tiles/PrivacyRing/PrivacyRingItemDetailsView.axaml
=> [VDG] [Trivial] Fix Privacy center margins

WalletWasabi.Fluent/Controls/TagsBox.axaml
- Fixes #9552 
- Also fixes the issue when there is more than 1 line:
- Closes #9571
=> [VDG] [Trivial] TagsBox height fix

WalletWasabi.Fluent/ViewModels/CoinJoinProfiles/CoinJoinProfilesViewModel.cs
=> Fix Coinjoin default set upon not changing anything

WalletWasabi.Fluent/Views/Wallets/Home/Tiles/PrivacyRing/PrivacyRingView.axaml
=> [VDG] [Trivial] Increase PrivacyRing adaptive threshold

WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
Just moving the code into the right place. It should not change behavior.
=> Move input reg code into ProceedWithInputRegAndConfirmAsync

WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepOutputRegistrationTests.cs, WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/SignTransactionTests.cs, WalletWasabi.Tests/UnitTests/WabiSabi/Models/MultipartyTransactionTests.cs, WalletWasabi.Tests/UnitTests/WabiSabi/Models/SerializationTests.cs, WalletWasabi/WabiSabi/Backend/Rounds/Arena.Partial.cs, WalletWasabi/WabiSabi/Client/CoinJoinManager.cs, WalletWasabi/WabiSabi/Models/MultipartyTransaction/ConstructionState.cs
This PR just extracts some whitespace changes from #9683 and fixes a few typos. Thus makes #9683 a bit smaller.
=> [trivial] A few typos & code style

WalletWasabi.Fluent/Controls/TileButton.axaml, WalletWasabi.Fluent/Views/AddWallet/AddWalletPageView.axaml
=> [VDG] Add Wallet - adjust buttons for narrow window size

WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
fixes https://github.com/zkSNACKs/WalletWasabi/issues/9685
=> move CJ started notification to where client actually started

WalletWasabi.Fluent/Controls/NavBarItem.axaml
Fixes: https://github.com/zkSNACKs/WalletWasabi/issues/9715
=> [VDG] Disable style for NavBarItem as we do not have dragging enabled

WalletWasabi/Blockchain/Keys/HdPubKeyCache.cs
Revert https://github.com/zkSNACKs/WalletWasabi/pull/9070/commits/30b89a29f989d8f8b7b94d7b1d1ecbcf3a1c50e2
Fixes #9731 
@lontivero
=> AddOrReplace to fix ArgumentException

WalletWasabi.Fluent/Rpc/WasabiJsonRpcService.cs, WalletWasabi.Fluent/ViewModels/Wallets/Receive/ReceiveViewModel.cs, WalletWasabi.Tests/RegressionTests/BuildTests.cs, WalletWasabi.Tests/RegressionTests/SendTests.cs, WalletWasabi.Tests/RegressionTests/WalletTests.cs, WalletWasabi.Tests/UnitTests/Transactions/TransactionProcessorTests.cs, WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepOutputRegistrationTests.cs, WalletWasabi/Blockchain/Keys/KeyManager.cs
- Notification was never really implemented in the UI
- There was leftover code in `KeyManager` that was supposed to deal with this but didn't.
- Such code was removed from `KeyManager` and usages updated accordingly.
- Fixes #9738
=> [VDG] [Taproot UI support] #6 - Remove minimum gap limit reached notification

WalletWasabi.Fluent/ViewModels/Wallets/Home/History/Details/CoinJoinDetailsViewModel.cs, WalletWasabi.Fluent/Views/Wallets/Home/History/Details/CoinJoinDetailsView.axaml
Fixes: #9713
Sorry, low hanging fruit 😅
=> [VDG] Add confirmation count to CJ details view

WalletWasabi/BitcoinCore/CoreNode.cs, WalletWasabi/Rpc/JsonRpcServer.cs, WalletWasabi/Services/SingleInstanceChecker.cs
Removes a few warnings which appeared after .NET 7 support was merged.
=> [Housekeeping][Easy] Forward cancellation tokens

WalletWasabi.Fluent/ViewModels/AddWallet/RecoverWalletViewModel.cs, WalletWasabi.Fluent/ViewModels/Dialogs/AdvancedRecoveryOptionsViewModel.cs, WalletWasabi.Fluent/Views/Dialogs/AdvancedRecoveryOptionsView.axaml
- Title is self-explanatory
- Fixes #9737
=> [VDG] [Taproot UI support] #5 - Remove Custom Derivation Path from Wallet Recovery flow

WalletWasabi.Documentation/WasabiCompatibility.md
According to: https://github.com/dotnet/core/blob/main/release-notes/7.0/supported-os.md
- Add windows 11 version to the supported OS
- Updated  Ubuntu version
=> [Trivial] Update supported OS

WalletWasabi.Fluent/Extensions/TransactionSummaryExtensions.cs, WalletWasabi.Fluent/ViewModels/TransactionBroadcasting/BroadcastTransactionViewModel.cs, WalletWasabi.Fluent/ViewModels/Wallets/Home/History/Details/CoinJoinDetailsViewModel.cs, WalletWasabi.Fluent/ViewModels/Wallets/Home/History/Details/CoinJoinsDetailsViewModel.cs, WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionSummaryViewModel.cs, WalletWasabi.Fluent/Views/Wallets/Home/History/Details/CoinJoinDetailsView.axaml, WalletWasabi.Fluent/Views/Wallets/Home/History/Details/CoinJoinsDetailsView.axaml
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/9447
=> [VDG] Fix copy content of fees

WalletWasabi/Blockchain/Keys/KeyManager.cs, WalletWasabi/WabiSabi/Client/CoinJoinClient.cs, WalletWasabi/WabiSabi/Client/KeyChain.cs, WalletWasabi/Wallets/Wallet.cs
Alternative solution https://github.com/zkSNACKs/WalletWasabi/pull/9778
=> Store the MasterKey in KeyManager

WalletWasabi.Fluent/ViewModels/Wallets/CoinJoinStateViewModel.cs
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/9809
=> [VDG] add missing permit in auto start state

WalletWasabi.Backend/wwwroot/about.html, WalletWasabi.Backend/wwwroot/css/style.css, WalletWasabi.Backend/wwwroot/faq.html, WalletWasabi.Backend/wwwroot/index.html
Padding and font size fixes on mobile view.
=> [website] Mobile fixes

WalletWasabi.Documentation/WasabiSetupRegtest.md
Just an update of what to change in the round config file, from WW1 with CCJ to WW2 with WabiSabi
=> [Trivial] WasabiSetupRegtest.md: Update CcjRoundsConfig by WabiSabiConfig

WalletWasabi/Helpers/RuntimeParams.cs, WalletWasabi/Wallets/P2pBlockProvider.cs
Review with whitespace [off](https://github.com/zkSNACKs/WalletWasabi/pull/9851/files?diff=split&w=1).
=> `P2pBlockProvider`: Minor changes

WalletWasabi.Fluent/ViewModels/Wallets/CoinJoinStateViewModel.cs
=> [trivial] minor musicbox message improvement

WalletWasabi.Fluent/ViewModels/MainViewModel.cs, WalletWasabi.Fluent/ViewModels/WalletManagerViewModel.cs
Not sure we need or want to add `SelectedWallet` property and sync it with wallet list maybe this method will be enough @soosr
=> [VDG] Add TryGetSelectedWalletViewModel to WalletManagerViewModel

WalletWasabi.Backend/Controllers/ChaumianCoinJoinController.cs, WalletWasabi.Fluent/Extensions/DynamicDataExtensions.cs, WalletWasabi/CoinJoin/Coordinator/Rounds/CoordinatorRound.cs, WalletWasabi/WabiSabi/Backend/Rounds/Arena.Partial.cs
To unify the code those curly brackets can be removed as discussed here:
https://github.com/zkSNACKs/WalletWasabi/pull/9850#discussion_r1060087385
https://github.com/zkSNACKs/WalletWasabi/pull/9849#discussion_r1059155339
To easily review this turn off whitespace changes https://github.com/zkSNACKs/WalletWasabi/pull/9934/files?diff=unified&w=1
=> [Trivial] Remove unnecessary curly brackets

WalletWasabi/BitcoinCore/CoreNode.cs
=> `CoreNode`: Remove a few more warnings

WalletWasabi/WabiSabi/Client/InternalDestinationProvider.cs
Close #9964
The code in place was the one needed for scriptPubKey randomization, what it is not implemented yet.
=> Fix randomization of output types

WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiHttpApiIntegrationTests.cs, WalletWasabi/WabiSabi/Client/CoinJoinClient.cs, WalletWasabi/WabiSabi/Client/CoinJoinManager.cs, WalletWasabi/WabiSabi/Client/CoinJoinResult.cs
This is a small refactoring that doesn't change the behavior.
=> Small preparation for payments in coinjoins

WalletWasabi.Fluent/Controls/NavBarItem.axaml, WalletWasabi.Fluent/Views/NavBar/NavBar.axaml
Before: 
After:
cc @soosr @zkSNACKs/visual-design-group
=> [VDG] Realign NavBarItem element margins and heights.

WalletWasabi/WabiSabi/Backend/Banning/Whitelist.cs
=> Fix Whitelist LastSavedChangeId property

WalletWasabi.Fluent/ViewModels/MainViewModel.cs
Fixes: https://github.com/zkSNACKs/WalletWasabi/issues/9908
=> [VDG] Authorize wallet info when navigated from search bar

WalletWasabi.Fluent/ViewModels/Wallets/Receive/ReceiveAddressViewModel.cs
Addresses #9783
Supposedly fix `System.InvalidOperationException: Call from invalid thread`
Hide whitespaces when reviewing
=> Remove unecessary Task.Run

WalletWasabi/WabiSabi/Backend/Banning/CoinVerifierLogger.cs
We don't want to negate there.
=> Fix my mistake

WalletWasabi.Fluent/ViewModels/CoinControl/Core/CoinCoinControlItemViewModel.cs, WalletWasabi.Fluent/ViewModels/CoinControl/Core/CoinControlItemViewModelBase.cs, WalletWasabi.Fluent/ViewModels/Wallets/Advanced/WalletCoins/WalletCoinViewModel.cs, WalletWasabi.Fluent/Views/Wallets/Advanced/WalletCoins/Columns/SelectionColumnView.axaml
fixes https://github.com/zkSNACKs/WalletWasabi/issues/9992
=> [VDG] enable selection of CJing coins

WalletWasabi.Fluent/Controls/FadeOutTextBlock.cs
cc @wieslawsoltes @soosr 
Fixes FadeOutTextBlock not updating on text change. We never noticed this because we never bound any dynamic text on this control before i did what im doing on #10033 right now.
=> [VDG] Fix FadeOutTextBlock not updating on text change.

WalletWasabi.Fluent/Converters/MoneyConverters.cs
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/10034
=> [VDG] fix balance format

.github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature-request.md
Removed link for the obsoleted section of Discussions.
Added a new template for feature requests.
=> Fix feature request workflow

WalletWasabi.Fluent/Config.cs
Fixes #10043.
Please note that it might not be a fix but a workaround as it seems #10043 issue was introduced lately
=> Non default ServiceConfiguration at client init

WalletWasabi.Fluent/Behaviors/HoldKeyBehavior.cs, WalletWasabi.Fluent/Helpers/ApplicationHelper.cs
The "Review coins" link should no longer get stuck when the Main Window is deactivated.
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/10002
=> [VDG] Fix HoldKeyBehavior stuck when MainWindow deactivated

WalletWasabi/Extensions/NBitcoinExtensions.cs
=> remove local from InvalidOperationException

WalletWasabi.Fluent/ViewModels/Wallets/Advanced/WalletCoins/WalletCoinViewModel.cs, WalletWasabi.Fluent/ViewModels/Wallets/Advanced/WalletCoins/WalletCoinsViewModel.cs, WalletWasabi.Fluent/Views/Wallets/Advanced/WalletCoins/WalletCoinsView.axaml
It won't be implemented in the wallet coins dialog.
=> [VDG] Coin freeze - remove leftover

WalletWasabi.Fluent/ViewModels/CoinControl/Core/CoinCoinControlItemViewModel.cs
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/10061
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/10068
=> [VDG] Send - fix labels for coin list

WalletWasabi/Blockchain/BlockFilters/IndexBuilderService.cs, WalletWasabi/Blockchain/BlockFilters/StartingFilters.cs, WalletWasabi/Stores/BitcoinStore.cs
I have noticed this while researching something else
=> [trivial] `IndexBuilderService`: nits

WalletWasabi.Fluent/ApplicationStateManager.cs
Fixes CF issues as pointed out here https://github.com/zkSNACKs/WalletWasabi/pull/10120#issuecomment-1432773926
=> [Trivial] Fix CodeFactor issues in ApplicationStateManager.cs

WalletWasabi.Tests/UnitTests/KeyManagementTests.cs
Closes https://github.com/zkSNACKs/WalletWasabi/issues/10122
This contains a unit tests that creates a `KeyManager` and ask for 10 keys for change and then verifies half of them are segwit and there rest are taproot.
=> Creates UT to verify script type of change outputs

WalletWasabi.Fluent/Behaviors/ItemsPresenterAnimationBehavior.cs, WalletWasabi.Fluent/Views/Wallets/Home/Tiles/PrivacyRing/PrivacyRingView.axaml
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/9338
=> [VDG] Privacy Ring - attempt to fix double animation

WalletWasabi/BitcoinCore/CoreNode.cs
cherry picked commit 6f56a772262036f571eb259e21d4c82fdf518fbd for silent release
=> [silent release] Add softwareexpiry=0 to knots parameters

WalletWasabi.Fluent.Desktop/packages.lock.json, WalletWasabi.Fluent/packages.lock.json, WalletWasabi.Packager/packages.lock.json, WalletWasabi.Tests/UnitTests/Transactions/TransactionFactoryTests.cs, WalletWasabi/WalletWasabi.csproj, WalletWasabi/packages.lock.json
cherry picked for silent release from https://github.com/zkSNACKs/WalletWasabi/pull/10042
=> [silent release] Upgrade NBitcoin version from 7.0.14 to 7.0.24

WalletWasabi.Fluent/Views/Dialogs/Authorization/HardwareWalletAuthDialogView.axaml
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/9885
=> [VDG] Ask user to check the hardware wallet when confirming

WalletWasabi.Backend/wwwroot/index.html, WalletWasabi/Helpers/Constants.cs
=> Bump version to v2.0.3

WalletWasabi.Fluent/ViewModels/CoinControl/SelectCoinsDialogViewModel.cs
Requested by the Marketing team.
=> [VDG] Rename cc title

WalletWasabi.Fluent/Models/UiTriggers.cs
Fixes #10244 
Please @soosr review, and if it's not the right way to go just disregard this PR and make a new one, I will not be able to address change requests before 2pm Budapest.
=> Add sample for tx history update event on new filter

WalletWasabi.Fluent/ViewModels/CoinControl/CoinSelectorDataGridSource.cs, WalletWasabi.Fluent/Views/CoinControl/SelectCoinsDialogView.axaml
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/10215
=> [VDG] Coin Control - fix column width

WalletWasabi.Fluent/ViewModels/CoinControl/CoinSelectorViewModel.cs, WalletWasabi.Fluent/ViewModels/CoinControl/Core/CoinControlItemViewModelBase.cs, WalletWasabi.Fluent/ViewModels/CoinControl/Core/PocketCoinControlItemViewModel.cs, WalletWasabi.Fluent/ViewModels/Wallets/Advanced/WalletCoins/WalletCoinsViewModel.cs
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/10048
=> [VDG] Fix address reuse coin selection

WalletWasabi.Fluent/ViewModels/CoinControl/CoinSelectorDataGridSource.cs, WalletWasabi.Fluent/ViewModels/CoinControl/CoinSelectorViewModel.cs, WalletWasabi.Fluent/ViewModels/CoinControl/Core/CoinControlItemViewModelBase.cs, WalletWasabi.Fluent/ViewModels/CoinControl/Core/PocketCoinControlItemViewModel.cs
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/10222
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/10217
=> [VDG] Coin Control - fix sorting #2

WalletWasabi.Fluent/ViewModels/CoinControl/CoinSelectorViewModel.cs, WalletWasabi.Fluent/ViewModels/CoinControl/Core/CoinControlItemViewModelBase.cs, WalletWasabi.Fluent/ViewModels/CoinControl/Core/PocketCoinControlItemViewModel.cs, WalletWasabi.Fluent/ViewModels/Wallets/Advanced/WalletCoins/WalletCoinsViewModel.cs
https://github.com/zkSNACKs/WalletWasabi/pull/10141
cc @molnard
=> [Release] CC fix 1

WalletWasabi.Fluent/ViewModels/CoinControl/CoinSelectorDataGridSource.cs, WalletWasabi.Fluent/Views/CoinControl/SelectCoinsDialogView.axaml
https://github.com/zkSNACKs/WalletWasabi/pull/10253
cc @molnard
=> [Release] cc fix 2

WalletWasabi.Fluent/ViewModels/CoinControl/CoinSelectorDataGridSource.cs, WalletWasabi.Fluent/ViewModels/CoinControl/CoinSelectorViewModel.cs, WalletWasabi.Fluent/ViewModels/CoinControl/Core/CoinControlItemViewModelBase.cs, WalletWasabi.Fluent/ViewModels/CoinControl/Core/PocketCoinControlItemViewModel.cs
https://github.com/zkSNACKs/WalletWasabi/pull/10255
cc @molnard
=> [Release] fix cc 3

WalletWasabi.Fluent/ViewModels/CoinControl/CoinSelectorViewModel.cs, WalletWasabi.Fluent/ViewModels/CoinControl/Core/CoinControlItemViewModelBase.cs
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/10256
=> [VDG] Coin Control - fix non relevant cluster gets expanded

WalletWasabi.Fluent/ViewModels/CoinControl/CoinSelectorDataGridSource.cs, WalletWasabi.Fluent/ViewModels/CoinControl/CoinSelectorViewModel.cs, WalletWasabi.Fluent/ViewModels/CoinControl/Core/CoinCoinControlItemViewModel.cs, WalletWasabi.Fluent/ViewModels/CoinControl/Core/PocketCoinControlItemViewModel.cs
https://github.com/zkSNACKs/WalletWasabi/pull/10264
cc @molnard
=> [Release] cc fix 4

WalletWasabi.Tests/Helpers/ServiceFactory.cs, WalletWasabi.Tests/UnitTests/WabiSabi/Client/CoinJoinClientTests.cs, WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/10274
=> Fix output address generation and add test

WalletWasabi.Tests/Helpers/ServiceFactory.cs, WalletWasabi.Tests/UnitTests/WabiSabi/Client/CoinJoinClientTests.cs, WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
merging https://github.com/zkSNACKs/WalletWasabi/pull/10289 into the release branch
=> [release] Fix output address generation and add test

WalletWasabi.Fluent/ViewModels/CoinControl/CoinSelectorViewModel.cs, WalletWasabi.Fluent/ViewModels/CoinControl/Core/CoinControlItemViewModelBase.cs
https://github.com/zkSNACKs/WalletWasabi/pull/10285
=> [Release] cc fix 5

WalletWasabi.Fluent/Controls/Dialog.axaml.cs
https://github.com/zkSNACKs/WalletWasabi/pull/10283
=> [Release] dialog close prevention

WalletWasabi.Fluent/Behaviors/FlyoutSuggestionBehavior.cs, WalletWasabi.Fluent/Extensions/FunctionalExtensions.cs, WalletWasabi.Fluent/Global.cs, WalletWasabi.Fluent/ViewModels/CoinControl/CoinSelectorViewModel.cs, WalletWasabi.Fluent/ViewModels/Dialogs/AdvancedRecoveryOptionsViewModel.cs, WalletWasabi.Fluent/ViewModels/MainViewModel.cs, WalletWasabi.Fluent/ViewModels/Wallets/Send/SendViewModel.cs, WalletWasabi.Tests/Helpers/WabiSabiFactory.cs, WalletWasabi.Tests/UnitTests/Affiliation/AffiliateDataUpdaterTests.cs, WalletWasabi.Tests/UnitTests/Affiliation/ReadyToSingRequestRequestCompatibilityTests.cs, WalletWasabi/Affiliation/AffiliateDataCollector.cs, WalletWasabi/Affiliation/AffiliateDataUpdater.cs, WalletWasabi/Affiliation/AffiliateServerStatusUpdater.cs, WalletWasabi/Affiliation/Extensions/NBitcoinExtensions.cs, WalletWasabi/Affiliation/RoundData.cs, WalletWasabi/Bases/ConfigBase.cs, WalletWasabi/Blockchain/TransactionProcessing/TransactionProcessor.cs, WalletWasabi/Helpers/CoinHelpers.cs, WalletWasabi/Logging/Logger.cs, WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs, WalletWasabi/WabiSabi/Client/CoinJoinManager.cs, WalletWasabi/WabiSabi/Client/CoinJoinResult.cs, WalletWasabi/WabiSabi/Client/SmartRequestNode.cs, WalletWasabi/WabiSabi/Models/ReadyToSignRequestRequest.cs, WalletWasabi/Wallets/P2PBlockProvider.cs, WalletWasabi/Wallets/P2PNodesManager.cs, WalletWasabi/Wallets/RpcBlockProvider.cs, WalletWasabi/Wallets/SmartBlockProvider.cs
This can be easily reviewed with whitespace changes off:
https://github.com/zkSNACKs/WalletWasabi/pull/10294/files?diff=unified&w=1
=> [Trivial] Fix formatting

WalletWasabi.Fluent/Models/NavBarSelectedIndicatorState.cs, WalletWasabi.Fluent/ViewModels/NavBar/NavBarViewModel.cs
- Fixes https://github.com/zkSNACKs/WalletWasabi/issues/10301
- Fixes the selection indicator when the very first wallet has been just added.
=> [VDG] Fix many selected wallet at the same time

WalletWasabi.Fluent/ViewModels/Wallets/Advanced/WalletCoins/WalletCoinsViewModel.cs, WalletWasabi.Fluent/ViewModels/Wallets/Advanced/WalletInfoViewModel.cs, WalletWasabi.Fluent/ViewModels/Wallets/Advanced/WalletStatsViewModel.cs, WalletWasabi.Fluent/ViewModels/Wallets/CoinJoinSettingsViewModel.cs, WalletWasabi.Fluent/ViewModels/Wallets/Receive/ReceiveViewModel.cs, WalletWasabi.Fluent/ViewModels/Wallets/Send/SendViewModel.cs, WalletWasabi.Fluent/ViewModels/Wallets/WalletSettingsViewModel.cs
nit
to match _Legal Document_ & _About Wasabi_
=> [VDG] [TRIVIAL] SearchBar: minor wording improvement

.deepsource.toml
This could improve our code quality and reduce review time. 
https://deepsource.io/platform/static-analysis/
https://deepsource.io/docs/concepts
- Free For open-source projects, individuals, and small teams.
- Highly configurable - what and how to analyze and what to report.
=> Add Deepsource analyzer to the repo

WalletWasabi.Fluent/Views/AddWallet/Create/ConfirmRecoveryWordsView.axaml
https://github.com/zkSNACKs/WalletWasabi/pull/10331#issuecomment-1480740916
=> [VDG] Confirm recovery words - adjust layout

WalletWasabi.Fluent/Infrastructure/ClipboardObserver.cs, WalletWasabi.Fluent/ViewModels/AddWallet/WalletNamePageViewModel.cs, WalletWasabi/Extensions/TextReaderExtensions.cs
This PR just addresses small recommendations by deepsource to test it.
=> [Trivial] Fix small issues/recommendations according to deepsource

WalletWasabi.Backend/Global.cs
I looked over the `Global.cs` file and a question popped up in my head:
Why do we have these unnecessary local variables?! 
Just to assign them to their properties on the next line?
=> [Clean up] Remove unnecessary local variables

WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
Fixes [CA2208](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca2208) according to my IDE.
=> [Trivial] Instantiate argument exception with parameter name

WalletWasabi/WabiSabi/Client/AliceClient.cs
The client even tries to unregister when it is clear it will fail. This PR tries to evaluate better is we should try it.
=> Make sure to try unregister when we can.

WalletWasabi.Fluent/ViewModels/NavBar/NavBarViewModel.cs
fixes https://github.com/zkSNACKs/WalletWasabi/pull/10342#issuecomment-1481416696
=> [VDG] navbar - fix weird case

WalletWasabi/WabiSabi/Client/AliceClient.cs
We are unregistering inputs in case of error - having a minor privacy leak against the backend. The inputs were removed at the same time thus giving an opportunity to cluster the user's inputs by using time correlation. 
We only need to unregister if Alice would not be timed out by the backend. The backend timeout for Alices is `round.ConnectionConfirmationTimeFrame.Duration`.
```mermaid
gantt
title Input registration phase
dateFormat mm:ss
axisFormat %M:%S
Start of Input registration : milestone, m1, 00:00,0min
After this we need to unregister : milestone, m1, 08:00,0min
End of Input registration : milestone, m1, 10:00,0min
```
=> Let Alice timeout instead of remove.

WalletWasabi.Fluent/Styles/ScrollViewer.axaml
Fixes: https://github.com/zkSNACKs/WalletWasabi/issues/10131
=> [VDG] Make ScrollBar thumb more prominent

WalletWasabi.Backend/wwwroot/about.html, WalletWasabi.Backend/wwwroot/contribution.html, WalletWasabi.Backend/wwwroot/css/style.css, WalletWasabi.Backend/wwwroot/faq.html, WalletWasabi.Backend/wwwroot/index.html, WalletWasabi.Backend/wwwroot/onion-index.html
=> Mobile navgitation fix

WalletWasabi.Fluent/Controls/QrCode.cs, WalletWasabi.Fluent/Views/Wallets/Receive/ReceiveAddressView.axaml
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/10341
=> [VDG] Fix QR-core is cropped wrong

WalletWasabi.Fluent/ViewModels/Wallets/Send/LabelSelectionViewModel.cs, WalletWasabi.Fluent/ViewModels/Wallets/Send/LabelViewModel.cs, WalletWasabi.Fluent/ViewModels/Wallets/Send/PrivacyControlViewModel.cs, WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionPreviewViewModel.cs, WalletWasabi.Tests/UnitTests/UserInterfaceTest/PocketSelectionTests.cs
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/10345
=> [VDG] Fix ChangePocketCommand runs in the UI thread and has noticeable delay

WalletWasabi/BitcoinP2p/P2pNetwork.cs
Part of work on #10010
This PR just makes it clean what are public and what are private properties.
Easy to review commit by commit.
=> [easy] `P2pNetwork`: Cleanup

WalletWasabi.Fluent/Styles/TextBox.axaml
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/8789
=> [VDG] Fix Send - ´To´ field cuts off some letters at bottom

WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/9956
=> PlebStop preventing log message to Trace

WalletWasabi.Fluent/Behaviors/FlyoutSuggestionBehavior.cs
- Fixes https://github.com/zkSNACKs/WalletWasabi/issues/10290
- Improves code readability
=> [VDG] Fix suggestions out of sync

WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
=> [Trivial] Use TryGetValue

WalletWasabi.Fluent/Extensions/DateTimeExtensions.cs, WalletWasabi.Fluent/Extensions/DateTimeOffsetExtensions.cs, WalletWasabi.Fluent/ViewModels/Wallets/Home/History/Details/TransactionDetailsViewModel.cs, WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItems/CoinJoinHistoryItemViewModel.cs, WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItems/CoinJoinsHistoryItemViewModel.cs, WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItems/TransactionHistoryItemViewModel.cs, WalletWasabi.Fluent/Views/Wallets/Home/History/Details/TransactionDetailsView.axaml
=> Changed user facing date time formats to ISO like

Contrib/WalletDiagnostic/README.md
`coinsgraph.fsx` was renamed `txgraph.fsx`
=> [Trivial] Update file name in Contrib.WalletDiagnostic.README

WalletWasabi.Fluent/Views/Wallets/Send/TransactionPreviewView.axaml
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/10375
=> [VDG] fix Preview TX: shield_regular & shield_good displayed simultaniously 

WalletWasabi.Fluent/ViewModels/AddWallet/Create/RecoveryWordsViewModel.cs, WalletWasabi.Fluent/Views/AddWallet/Create/RecoveryWordsView.axaml
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/9018
=> Make recovery words copyable

WalletWasabi.Fluent/Extensions/FriendlyExceptionMessageExtensions.cs, WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionPreviewViewModel.cs
Fixes: https://github.com/zkSNACKs/WalletWasabi/issues/10509
With this Wasabi shows an error dialog, instead of crashing.
=> User friendly exception on PSBT saving

WalletWasabi.Daemon/README.md, WalletWasabi.Daemon/WasabiAppBuilder.cs, WalletWasabi.Fluent.Desktop/Program.cs, WalletWasabi.Fluent/Services.cs
This PR is for displaying the software version using command line.
=> Display software version

WalletWasabi.Daemon/ArgumentHelpers.cs
=> Fix comparison

WalletWasabi.Backend/README.md
closes https://github.com/zkSNACKs/WalletWasabi/issues/10477
- minor improvements
- update Blockchain controller table
- update POST filters
- remove coinjoin table (as suggested https://github.com/zkSNACKs/WalletWasabi/issues/10477#issuecomment-1511118641)
=> update Backend README

WalletWasabi.Fluent.Desktop/Program.cs
=> [trivial] improve wording crash report title

WalletWasabi.Fluent/ViewModels/Wallets/Receive/ReceiveAddressesViewModel.cs, WalletWasabi.Fluent/Views/Wallets/Receive/ReceiveAddressesView.axaml, WalletWasabi.Fluent/Views/Wallets/Receive/ReceiveView.axaml
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/10541
=> [VDG] Improve Unused Receive Addresses wording

WalletWasabi.Fluent/Helpers/Sort.cs, WalletWasabi.Fluent/ViewModels/CoinControl/CoinSelectorDataGridSource.cs, WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItems/HistoryItemViewModelBase.cs, WalletWasabi.Fluent/ViewModels/Wallets/Receive/AddressViewModel.cs, WalletWasabi.Fluent/ViewModels/Wallets/Receive/ReceiveAddressesViewModel.cs
It's better to have a single method responsible for sorting instead of two having differences just in 3 lines.
=> Removed logic duplication in sort methods

WalletWasabi/Models/Height.cs
Noticed while reviewing #10617
=> Height: Fix typos

WalletWasabi.Daemon/Global.cs, WalletWasabi/Blockchain/Keys/BlockchainState.cs, WalletWasabi/Blockchain/Keys/HdPubKey.cs, WalletWasabi/Blockchain/Keys/KeyManager.cs, WalletWasabi/Blockchain/Keys/WalletGenerator.cs, WalletWasabi/Blockchain/TransactionProcessing/TransactionProcessor.cs, WalletWasabi/Helpers/ImportWalletHelper.cs, WalletWasabi/JsonConverters/HeightJsonConverter.cs, WalletWasabi/JsonConverters/WalletHeightJsonConverter.cs, WalletWasabi/Wallets/WalletManager.cs
Changes extracted from #10260 to address https://github.com/zkSNACKs/WalletWasabi/pull/10260#pullrequestreview-1401533271
It's basically TurboSync without the Sync.
=> [TurboSync] TurboSyncHeight: Set and Save

WalletWasabi/Rpc/JsonRpcServer.cs
This PR fixes a bug that made the RPC server to ignore errors
=> Fix parsing error reporting

WalletWasabi.Fluent/Extensions/FriendlyExceptionMessageExtensions.cs
closes https://github.com/zkSNACKs/WalletWasabi/issues/10511
closes https://github.com/zkSNACKs/WalletWasabi/pull/10536
=> http request better message

WalletWasabi.Fluent/ViewModels/Dialogs/ShuttingDownViewModel.cs
Fixes this comment https://github.com/zkSNACKs/WalletWasabi/issues/10657#issuecomment-1543928168
=> Dont check `MainViewCanShutdown` in `ShuttingDownViewModel`

WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModel.cs
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/10683
=> [VDG] Fix wallet navigation via Notification Click

WalletWasabi.Fluent/Helpers/ApplicationHelper.cs, WalletWasabi.Fluent/Infrastructure/ClipboardObserver.cs, WalletWasabi.Fluent/ViewModels/Wallets/Send/SendViewModel.cs
The paste suggestion (hint) in Send It didn'd show randomly.
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/10422
=> [VDG] Fix Amount Suggestion not showing

WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryViewModel.cs
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/10687
=> [VDG] Fix CJ group child item selection from SearchBar result

WalletWasabi.Fluent/ViewModels/Navigation/RoutableViewModel.cs
Disables going back when the dialog is Busy.
Fixes #10685
=> [VDG] Disable Back in Dialogs when Escape is pressed

WalletWasabi.Fluent.Desktop/WalletWasabi.Fluent.Desktop.csproj, WalletWasabi.Fluent.Desktop/packages.lock.json, WalletWasabi.Fluent/WalletWasabi.Fluent.csproj, WalletWasabi.Fluent/packages.lock.json
The updated Avalonia contains critical bug fix for macOS regarding input: https://github.com/AvaloniaUI/Avalonia/pull/11096
This is last update in 0.10.x line, next releases will be only in 11.x.x
=> [VDG] Update to Avalonia 0.10.20

WalletWasabi/Stores/IndexStore.cs
This PR addresses https://github.com/zkSNACKs/WalletWasabi/pull/10551#issuecomment-1532802797
=> [Index][Migration] Remove old index data

WalletWasabi.Fluent/ViewModels/Wallets/Receive/ReceiveAddressViewModel.cs, WalletWasabi.Tests/UnitTests/ViewModels/ReceiveAddressViewModelTests.cs
The susbcription wasn't being disposed after navigating away from the ViewModel.
Fixes #10762
=> [VDG] Dispose ReceiveAddressViewModel subscription properly

WalletWasabi.Fluent/ViewModels/Wallets/CoinJoinStateViewModel.cs
nit
at other message _Play_ also has uppercase
=> [VDG] [trivial] uppercase letter musicbox

WalletWasabi/WabiSabi/Client/AmountDecomposer.cs
There were a couple of problems with the creation of the naive set. This PR fixes it. Equivalent in Sake: https://github.com/nopara73/Sake/commit/26f0dbf765eb52714adca7e2038066e5d41f989f
=> Make Naive Set truly naive

WalletWasabi.Fluent/CrashReport/ViewModels/CrashReportWindowViewModel.cs, WalletWasabi.Fluent/CrashReport/Views/CrashReportWindow.axaml, WalletWasabi.Fluent/ViewModels/HelpAndSupport/AboutViewModel.cs
- nice to know where you're going
-  _Copy Log_ also has tooltip 
Usually you run with `dotnet run`.
To trigger a crash report, run with this:
```
dotnet run crashreport -attempt="1" -exception="eyJFeGNlcHRpb25UeXBlIjoiU3lzdGVtLkV4Y2VwdGlvbiIsIk1lc3NhZ2UiOiJNeSBkdW1teSBleGNlcHRpb25NeSBkdW1teSBleGNlcHRpb25NeSBkdW1teSBleGNlcHRpb25NeSBkdW1teSBleGNlcHRpb25NeSBkdW1teSBleGNlcHRpb25NeSBkdW1teSBleGNlcHRpb25NeSBkdW1teSBleGNlcHRpb25NeSBkdW1teSBleGNlcHRpb25NeSBkdW1teSBleGNlcHRpb25NeSBkdW1teSBleGNlcHRpb25NeSBkdW1teSBleGNlcHRpb25NeSBkdW1teSBleGNlcHRpb25NeSBkdW1teSBleGNlcHRpb25NeSBkdW1teSBleGNlcHRpb25NeSBkdW1teSBleGNlcHRpb25NeSBkdW1teSBleGNlcHRpb25NeSBkdW1teSBleGNlcHRpb25NeSBkdW1teSBleGNlcHRpb25NeSBkdW1teSBleGNlcHRpb25NeSBkdW1teSBleGNlcHRpb25NeSBkdW1teSBleGNlcHRpb25NeSBkdW1teSBleGNlcHRpb25NeSBkdW1teSBle …
```
=> crash report: add tooltip to open GH report hyperlink

WalletWasabi.Fluent/Controls/TagsBox.axaml.cs
Fixes: https://github.com/zkSNACKs/WalletWasabi/issues/10591
=> [VDG] Do not use RequestAdd property in TagsBox to proxy adding new labels

WalletWasabi/WabiSabi/Client/AmountDecomposer.cs
Equivalent in Sake: https://github.com/nopara73/Sake/pull/29
=> Extract naive decomposition out into its own method

WalletWasabi.Documentation/HowToDeploy.md
This is a  step by step summary of what was agreed here: https://github.com/zkSNACKs/WalletWasabi/discussions/10538
=> how to deploy

WalletWasabi/WabiSabi/Client/AmountDecomposer.cs
Equivalent in Sake: https://github.com/nopara73/Sake/pull/30
=> Extract changeless decomposition out into its own method

CONTRIBUTING.md, WalletWasabi/Blockchain/Analysis/FeesEstimation/HybridFeeProvider.cs, WalletWasabi/Blockchain/Analysis/FeesEstimation/ThirdPartyFeeProvider.cs, WalletWasabi/CoinJoin/Coordinator/Rounds/CoordinatorRound.cs, WalletWasabi/Helpers/RuntimeParams.cs, WalletWasabi/Services/HostedServices.cs, WalletWasabi/Wallets/Kitchen.cs, WalletWasabi/WebClients/Wasabi/WasabiClient.cs
Let's recommend the new syntax. Not many people use the old syntax anymore.
=> [trivial] Use new new

WalletWasabi/CoinJoin/Coordinator/Rounds/CoordinatorRound.cs, WalletWasabi/Services/HostedServices.cs
=> [Trivial] Use new new keyword

WalletWasabi/WabiSabi/Client/AmountDecomposer.cs
Mainly the work of @turbolay and @adamPetho 
History, description, discussion, etc.. can be found by following the trails of the Sake equivalence: https://github.com/nopara73/Sake/pull/32
=> Introduce the concept of change tolerance

Contrib/CLI/README.md, Contrib/CLI/wcli.sh, WalletWasabi.Daemon/Rpc/WasabiJsonRpcService.cs
This PR adds support for taproot in the rpc methods and adds the `wcli.sh` to interact with the rpc easier.
=> wcli+taproot

WalletWasabi/WabiSabi/Client/AmountDecomposer.cs
Sake: https://github.com/nopara73/Sake/pull/35, https://github.com/nopara73/Sake/pull/37, https://github.com/nopara73/Sake/commit/081c333cf134575ff58d20d87f318e43d3e3e7f5
Closes https://github.com/nopara73/Sake/pull/25
Closes https://github.com/zkSNACKs/WalletWasabi/pull/10755
It mostly, but I not fully addresses https://github.com/zkSNACKs/WalletWasabi/issues/10675, because I'm a chicken: https://github.com/zkSNACKs/WalletWasabi/pull/10824#discussion_r1212755083
So.. what's happening here? I'm explaining in code comments.
=> Ensure min output amount is economical in coinjoins

WalletWasabi.Tests/UnitTests/LinqExtensionsTests.cs, WalletWasabi/Extensions/LinqExtensions.cs
Possible memory leak 
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/10808
=> Alternative implementation for Combinations

WalletWasabi.Fluent/Controls/TagsBox.axaml.cs, WalletWasabi.Fluent/ViewModels/Dialogs/LabelEntryDialogViewModel.cs, WalletWasabi.Fluent/ViewModels/Wallets/Labels/SuggestionLabelsViewModel.cs, WalletWasabi.Fluent/ViewModels/Wallets/Receive/ReceiveViewModel.cs, WalletWasabi.Fluent/Views/Dialogs/LabelEntryDialogView.axaml, WalletWasabi.Fluent/Views/Wallets/Receive/ReceiveView.axaml
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/10806
=> [VDG] Fix TagsBox

WalletWasabi.Tests/UnitTests/AllFeeEstimateTests.cs, WalletWasabi/Extensions/RPCClientExtensions.cs
Do not pay too much more than what is necessary for confirming in 2 blocks.
Closes #10665
Closes #10804
=> Do not pay too much

WalletWasabi.Fluent/Models/UI/QrCodeReader.cs, WalletWasabi.Fluent/ViewModels/Dialogs/ShowQrCameraDialogViewModel.cs
=> [VDG] Excluded VideoForWindows from web cam devices

WalletWasabi.Fluent/ViewModels/Wallets/Labels/SuggestionLabelsViewModel.cs, WalletWasabi.Tests/UnitTests/ViewModels/SuggestionLabelsViewModelTests.cs
=> [VDG] Deduplication of suggested labels based on score

WalletWasabi.Fluent/ViewModels/Wallets/Home/History/Details/TransactionDetailsViewModel.cs, WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItems/CoinJoinHistoryItemViewModel.cs, WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItems/CoinJoinsHistoryItemViewModel.cs, WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItems/HistoryItemViewModelBase.cs, WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItems/TransactionHistoryItemViewModel.cs
=> [VDG] Excluded fee from amount for outgoing transactions

WalletWasabi.Fluent/Controls/TagsBox.axaml.cs
fixes https://github.com/zkSNACKs/WalletWasabi/issues/10864
=> [VDG] close suggestions when input field is empty

WalletWasabi.Fluent/ViewModels/Settings/PrivacyModeViewModel.cs
The title of the button was faded for no reason.
=> [VDG] fix discreet mode cut off

WalletWasabi.Fluent/Models/UI/NullWalletList.cs, WalletWasabi.Fluent/Models/Wallets/IWalletListModel.cs, WalletWasabi.Fluent/Models/Wallets/WalletListModel.cs, WalletWasabi.Fluent/ViewModels/NavBar/NavBarViewModel.cs
- Restores persistence of last selected wallet, which was broken by #10576
- Closes #10871
=> [VDG] Fix LastSelectedWallet

WalletWasabi.Fluent/Views/Wallets/Home/Tiles/PrivacyRing/PrivacyRingDetailsView.axaml
Addresses https://github.com/zkSNACKs/WalletWasabi/pull/10863#issuecomment-1584300927
Master:
PR:
=> [VDG] Fix format for private amount of the privacy ring

WalletWasabi.Fluent/Behaviors/NavBarSelectedIndicatorChildBehavior.cs, WalletWasabi.Fluent/Controls/NavBarItem.axaml, WalletWasabi.Fluent/Controls/NavBarItem.axaml.cs, WalletWasabi.Fluent/Views/NavBar/NavBar.axaml
fixes https://github.com/zkSNACKs/WalletWasabi/issues/10865
=> [VDG] Fix NavBarItem stlye

WalletWasabi.Fluent/ViewModels/CoinControl/CoinSelectorDataGridSource.cs, WalletWasabi.Fluent/ViewModels/CoinControl/Core/CoinCoinControlItemViewModel.cs, WalletWasabi.Fluent/ViewModels/CoinControl/Core/CoinControlItemViewModelBase.cs, WalletWasabi.Fluent/ViewModels/CoinControl/Core/PocketCoinControlItemViewModel.cs
=> [VDG] [Trivial] Show anonscore for all items

WalletWasabi.Fluent/ViewModels/ApplicationViewModel.cs
Fixes: https://github.com/zkSNACKs/WalletWasabi/issues/10657
=> [VDG] Allow shutdown main view when no wallets are present

WalletWasabi.Tests/RegressionTests/Common.cs
This is a minimum <s>fix</s> workardound to make the `FilterDownloaderTestAsync` test work. I filed #10934 to improve it further, it should be a mechanical change but likely many changed lines of code (see #10935)
cc @nopara73
=> Fix `FilterDownloaderTestAsync`

WalletWasabi.Fluent/ViewModels/Wallets/Home/History/Details/TransactionDetailsViewModel.cs, WalletWasabi.Fluent/Views/Wallets/Home/History/Details/TransactionDetailsView.axaml
Let users copy each individual address instead of the whole list.
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/10899
=> [VDG] Copy individual address

WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterInputFailureTests.cs, WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiHttpApiIntegrationTests.cs
This PR only fixes 2 CF issues that for some reason where not included in my latest PR even when it was there.
=> Fix inconsistency in Github

WalletWasabi.Fluent.Desktop/Program.cs
=> Fixed a crash on Ctrl+C termination

WalletWasabi/WabiSabi/Backend/Rounds/Arena.Partial.cs, WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
Close #10259
Makes sure to do not remove Alices that confirmed.
=> Do not remove alices.

WalletWasabi/Blockchain/Analysis/CoinjoinAnalyzer.cs
```
Initial Transaction Processing finished in 14.61 seconds
```
```
Wallet.Dispose (509)    Initial Transaction Processing finished in 7.92 seconds.
```
=> Speed Up Wallet Load

WalletWasabi/Wallets/Wallet.cs
https://github.com/zkSNACKs/WalletWasabi/pull/10950#issuecomment-1610984506
=> Add comments for HandleFiltersLock usage

WalletWasabi.Fluent/ViewModels/Wallets/Receive/ReceiveViewModel.cs
was done in https://github.com/zkSNACKs/WalletWasabi/pull/10352
got reversed by https://github.com/zkSNACKs/WalletWasabi/pull/10386/
=> [trivial] typo searchbar

WalletWasabi.Fluent/ViewModels/SearchBar/Sources/ActionsSearchSource.cs
fixes https://github.com/zkSNACKs/WalletWasabi/issues/10984
=> [VDG] fix OOBE background on add wallet from searchbar

WalletWasabi.Fluent/ViewModels/AddWallet/WelcomePageViewModel.cs, WalletWasabi.Fluent/Views/AddWallet/AddWalletPageView.axaml, WalletWasabi.Fluent/Views/AddWallet/WelcomePageView.axaml
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/10698
=> [VDG] new onboarding

WalletWasabi.Fluent/Views/AddWallet/WelcomePageView.axaml
Closes https://github.com/zkSNACKs/WalletWasabi/pull/10991
=> Welcome Page: tweak wording coinjoin fees page

.deepsource.toml
=> Disable C# Analyzer

WalletWasabi.Fluent/Extensions/CurrencyExtensions.cs, WalletWasabi.Fluent/Models/Transactions/PrivacySuggestion.cs, WalletWasabi.Fluent/Models/Transactions/PrivacySuggestionsModel.cs, WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionSummaryViewModel.cs
Fixes: https://github.com/zkSNACKs/WalletWasabi/issues/11021
=> Fix internal address re-use destination amount calculation

WalletWasabi.Tests/Helpers/BitcoinFactory.cs, WalletWasabi.Tests/UnitTests/CoordinatorRoundTests.cs, WalletWasabi.Tests/UnitTests/MockRpcClient.cs, WalletWasabi.Tests/UnitTests/WabiSabi/Backend/RoundCreationTests.cs, WalletWasabi/Extensions/RPCClientExtensions.cs
Estimations for coinjoins were not using information from the mempool.
=> Use corrected estimations for coinjoins

WalletWasabi.Fluent/ViewModels/CoinControl/CoinSelectorDataGridSource.cs, WalletWasabi.Fluent/ViewModels/CoinControl/CoinSelectorViewModel.cs
@MarnixCroes Can you see if this corrects this issue with the sorting?
Might fix #10985
=> [VDG] Fix coin selection sort order

WalletWasabi.Fluent/Views/Wallets/Home/History/Details/CoinJoinDetailsView.axaml, WalletWasabi.Fluent/Views/Wallets/Home/History/Details/TransactionDetailsView.axaml
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/11016
cc @Kruwed
=> [VDG] Increase hover zones for copy buttons

WalletWasabi/Backend/Models/FilterModel.cs
This is just something I forgot to do when I re-implemented `IndexStore` to use SQLite.
=> `FilterModel`: Nits

WalletWasabi.Tests/UnitTests/Stores/BlockFilterSqliteStorageTests.cs, WalletWasabi/Stores/BlockFilterSqliteStorage.cs
Extracted from https://github.com/zkSNACKs/WalletWasabi/pull/11046/files#diff-d4618b25aa450f9d38709252fbc76ac6e299803ff55c3d72d0559e794097b19b where @turbolay & me did some improvements.
Related discussion: https://github.com/zkSNACKs/WalletWasabi/pull/11046#discussion_r1266681095
=> Minor improvement & bugfix for `BlockFilterSqliteStorage`

WalletWasabi.Tests/UnitTests/Transactions/TransactionProcessorTests.cs
This was forgotten to be removed in #8668.
=> [Trivial] Remove unused parameter

WalletWasabi/BitcoinP2p/P2pBehavior.cs, WalletWasabi/BitcoinP2p/TrustedP2pBehavior.cs, WalletWasabi/BitcoinP2p/UntrustedP2pBehavior.cs, WalletWasabi/Extensions/NBitcoinExtensions.cs
Builds on top of https://github.com/zkSNACKs/WalletWasabi/pull/11121
Also implements:
> Check how we are requesting the blocks (we should use MSG_WITNESS_BLOCK).
=> Have The Witness

WalletWasabi/Blockchain/Transactions/SmartTransaction.cs
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/11133
=> Fix "CPFP grouping doesn't always work properly"

WalletWasabi.Fluent/Views/Wallets/Home/WalletTiles.axaml
Fixes: https://github.com/zkSNACKs/WalletWasabi/issues/11084
=> [VDG] Fix missing wallet tile on small screen

WalletWasabi.Tests/UnitTests/Stores/IndexStoreTests.cs
This is just a minor cleanup. I got here while reviewing #11065.
=> `IndexStoreTests`: Clean up the test

WalletWasabi.Fluent/Controls/PrivacyBar.axaml.cs
Fixes: https://github.com/zkSNACKs/WalletWasabi/issues/11112
=> [VDG] Fix PrivacyBarSegment width calculation

WalletWasabi.Tests/IntegrationTests/TorTests.cs, WalletWasabi/Tor/Http/TorHttpClient.cs
=> Fix Tor tests

WalletWasabi.Daemon/PersistentConfig.cs, WalletWasabi.Tests/IntegrationTests/LiveServerTests.cs, WalletWasabi.Tests/XunitConfiguration/LiveServerTestsFixture.cs, WalletWasabi/Helpers/Constants.cs
Fixes #11144
I'm not sure if I got everything right. Hopefully, I did.
=> Fix LiveServer tests

WalletWasabi.Daemon/Rpc/WasabiJsonRpcService.cs
=> Remove `selectwallet` rpc call

WalletWasabi.Tests/RegressionTests/BuildTransactionValidationsTest.cs
Fixing regression test mentioned in the title. 
Related: https://github.com/zkSNACKs/WalletWasabi/pull/11065
=> Fix BuildTransactionValidationsTestAsync

WalletWasabi.Fluent/ViewModels/Wallets/Home/History/Features/CancelTransactionDialogViewModel.cs, WalletWasabi.Fluent/ViewModels/Wallets/Home/History/Features/SpeedUpTransactionDialogViewModel.cs, WalletWasabi.Fluent/Views/Wallets/Home/History/Features/CancelTransactionDialogView.axaml, WalletWasabi.Fluent/Views/Wallets/Home/History/Features/SpeedUpTransactionDialogView.axaml, WalletWasabi.Fluent/Views/Wallets/Send/SendSuccessView.axaml
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/11192
https://github.com/zkSNACKs/WalletWasabi/pull/11155#issuecomment-1665216812
https://github.com/zkSNACKs/WalletWasabi/pull/11155#issuecomment-1665263467
=> [VDG] SpeedUp&Cancel - use compact dialogs and `ContentArea`

WalletWasabi.Fluent/ViewModels/Wallets/Send/FeeChartViewModel.cs
It allows the update method to change the slider only the first time the values arrive.
Fixes #11103
=> [VDG] Set the slider value only once

WalletWasabi/Blockchain/Analysis/FeesEstimation/AllFeeEstimate.cs
Addresses https://github.com/zkSNACKs/WalletWasabi/pull/10988/files#r1257537757
=> `AllFeeEstimate`: Fix parameter name

WalletWasabi.Fluent/ViewModels/Wallets/Home/History/Features/CancelTransactionDialogViewModel.cs, WalletWasabi.Fluent/ViewModels/Wallets/Home/History/Features/SpeedUpTransactionDialogViewModel.cs, WalletWasabi.Fluent/ViewModels/Wallets/Send/SendSuccessViewModel.cs, WalletWasabi.Fluent/Views/Wallets/Send/SendSuccessView.axaml
=> [VDG] Change success dialog wording for cancel and speedup

Contrib/CLI/wcli.sh
=> Fix authentication in wcli.sh

WalletWasabi/Blockchain/Transactions/TransactionHistoryBuilder.cs
This problem was encountered by @SuperJMN
@MarnixCroes can you please try to repro #11079 on this branch?
I'm not 100% sure that it fixes the issue, but it def looks like a mistake.
EDIT:
Fixes #11079
=> Change wrong usage of containingTx by spendingTx

Directory.Packages.props, WalletWasabi.Daemon/packages.lock.json, WalletWasabi.Fluent.Desktop/packages.lock.json, WalletWasabi.Fluent.Generators/packages.lock.json, WalletWasabi.Fluent/packages.lock.json, WalletWasabi.Packager/packages.lock.json, WalletWasabi/packages.lock.json
Contributes to #11042.
This PR upgrades only some dependencies that cannot break something important. #11064 is a follow-up to this PR.
=> Update low-risk dependencies

WalletWasabi.Backend/Startup.cs, WalletWasabi.Tests/UnitTests/WabiSabi/Integration/Startup.cs, WalletWasabi/Tor/Http/Extensions/HttpResponseMessageExtensions.cs
Reverts zkSNACKs/WalletWasabi#11080
=> Revert "Use same json serialization settings on client and server"

WalletWasabi.Fluent/Helpers/CoinPocketHelper.cs, WalletWasabi.Fluent/Helpers/LabelsComparer.cs, WalletWasabi.Tests/UnitTests/Transactions/TransactionProcessorTests.cs
https://github.com/zkSNACKs/WalletWasabi/pull/11242
=> [2.0.4] Fix pocket generation

WalletWasabi/Stores/BlockFilterSqliteStorage.cs, WalletWasabi/Stores/IndexStore.cs
Cherry pick of https://github.com/zkSNACKs/WalletWasabi/pull/11274
=> [v2.0.4] Make filter migration cancellable

WalletWasabi.Documentation/WasabiCompatibility.md
https://github.com/dotnet/core/blob/main/release-notes/7.0/supported-os.md#linux
the others are up-to-date
=> [trivial] bump Fedora minimal version requirement

WalletWasabi.Fluent/Views/Wallets/Home/History/Details/TransactionDetailsView.axaml
cherry-picked commits from https://github.com/zkSNACKs/WalletWasabi/pull/11286
=> [v2.0.4] tx details: clarify expected confirmation time

WalletWasabi.Fluent/Models/Wallets/IWalletCoinjoinModel.cs, WalletWasabi.Fluent/Models/Wallets/IWalletModel.cs, WalletWasabi.Fluent/Models/Wallets/IWalletPrivacyModel.cs, WalletWasabi.Fluent/Models/Wallets/WalletCoinjoinModel.cs, WalletWasabi.Fluent/Models/Wallets/WalletModel.cs, WalletWasabi.Fluent/Models/Wallets/WalletPrivacyModel.cs, WalletWasabi.Fluent/ViewModels/CoinJoinProfiles/CoinJoinProfilesViewModel.cs, WalletWasabi.Fluent/ViewModels/Wallets/CoinJoinStateViewModel.cs, WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModel.cs, WalletWasabi.Tests/UnitTests/ViewModels/ReceiveAddressViewModelTests.cs, WalletWasabi.Tests/UnitTests/ViewModels/ReceiveViewModelTests.cs, WalletWasabi.Tests/UnitTests/ViewModels/SuggestionLabelsViewModelTests.cs
- Introduces `IWalletPrivacyModel`
- Introduces `IWalletCoinjoinModel`
- Decouples `CoinjoinStateViewModel`
=> [VDG] UI Decoupling #35

WalletWasabi.Fluent/Views/Wallets/Send/TransactionSummary.axaml
cherry-picked commits from https://github.com/zkSNACKs/WalletWasabi/pull/11288
=> [v2.0.4] Preview Transaction: update confirmation time label text

WalletWasabi.Fluent/Models/Wallets/WalletLoadWorkflow.cs, WalletWasabi/Wallets/Wallet.cs
Almost the same as #11306
Cherry-picked from #11306
I didn't bring the `merge master` (last) commit because it introduces around +173 commit and makes the review impossible.
Credits goes to: @turbolay
=> [v2.0.4] Process filters while downloading them from turbolay

WalletWasabi.Backend/Controllers/ChaumianCoinJoinController.cs, WalletWasabi.Backend/Filters/DeprecatedAttibute.cs
This is for disabling WW1 controller before removing all the code.
=> Disable WW1 gracefully

WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/PrivacyRing/PrivacyBarViewModel.cs
- Removes per-coin segments in the Privacy Bar.
- Will show at most 3 segments: Non-private, semi-private and private funds.
- Fixes #11355 
- Fixes #11353
=> [VDG] Remove PrivacyBar Segments

WalletWasabi.Backend/Global.cs, WalletWasabi.Tests/UnitTests/WabiSabi/Backend/OffenderSerializationTests.cs, WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PrisonTests.cs, WalletWasabi/WabiSabi/Backend/DoSPrevention/Offender.cs, WalletWasabi/WabiSabi/Backend/DoSPrevention/Prison.cs, WalletWasabi/WabiSabi/Backend/DoSPrevention/Warden.cs, WalletWasabi/WabiSabi/WabiSabiCoordinator.cs
This PR is for banning coins that tries to escape from prison by spending.
Descendants inherit the punishment from the most punished of theirs ancestors.
=> Punish descendants

WalletWasabi/WabiSabi/Backend/DoSPrevention/Prison.cs
I found this while looking into #11408
=> `Prison`: fix lock

Contrib/deploy.sh, flake.nix
This PR adds a simple bash script for deploying the backend with systemd.
=> Add deploy script and version

WalletWasabi.Fluent.Generators/Abstractions/GeneratorStep.cs
Fixes a sporadic build error "inconsistent syntax tree features"
=> [VDG] Combined SourceGenerator: Fix sporadic build error in Visual Studio

WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepOutputRegistrationTests.cs, WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepTransactionSigningTests.cs, WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs, WalletWasabi/WabiSabi/Backend/Rounds/Round.cs, WalletWasabi/WabiSabi/Backend/WabiSabiConfig.cs
Addresses feedback for https://github.com/zkSNACKs/WalletWasabi/pull/11115
=> Fast signing banning

WalletWasabi.Fluent/ViewModels/AddWallet/HardwareWallet/DetectedHardwareWalletViewModel.cs
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/11020
Check my https://github.com/zkSNACKs/WalletWasabi/issues/11020#issuecomment-1706345208 for explanation.
=> Fix crash during HW import

WalletWasabi.Documentation/HowToDeploy.md, flake.nix
Simplify the deployment steps.
Note: I took the opportunity to change the package version as agreed during a meeting.
=> New scripts for deploying

WalletWasabi.Fluent/Views/Wallets/Send/CustomFeeRateDialogView.axaml
=> [VDG] Allow only 2 decimals instead of 3 in custom fee rate view

WalletWasabi.Tests/UnitTests/SmartCoinTests.cs, WalletWasabi/Blockchain/TransactionOutputs/SmartCoin.cs
=> Fix Smartcoin.IsImmature

WalletWasabi.Fluent/Models/Wallets/WalletLoadWorkflow.cs, WalletWasabi/Blockchain/Blocks/SmartHeaderChain.cs, WalletWasabi/Stores/IndexStore.cs
Review with [whitespace off](https://github.com/zkSNACKs/WalletWasabi/pull/11377/files?diff=split&w=1).
=> `WalletLoadWorkflow`: Remove active waiting

WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
Fixes: https://github.com/zkSNACKs/WalletWasabi/issues/11175
=> Change log level from Warning to Error in case of RPCException

WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs, WalletWasabi/WabiSabi/Backend/Rounds/Round.cs, WalletWasabi/WabiSabi/Client/CoinJoinClient.cs, WalletWasabi/WabiSabi/WabiSabiCoordinator.cs
Close #11454
This PR doesn't manipulate `Round` state from outside `Arena`
=> Abort round by `Arena`

WalletWasabi.Fluent/Models/Wallets/CoinModel.cs, WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/PrivacyControlTileViewModel.cs, WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/PrivacyRing/PrivacyRingItemViewModel.cs, WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/PrivacyRing/PrivacyRingViewModel.cs, WalletWasabi.Fluent/Views/Wallets/Home/Tiles/PrivacyRing/PrivacyRingItemDetailsView.axaml
Cherry-picked the relevant commit from https://github.com/zkSNACKs/WalletWasabi/pull/11487
- Decouples `PrivacyRingViewModel`
- Decouples `PrivacyRingItemViewModel`
=> [VDG] UI Decoupling #39

WalletWasabi/Rpc/PaymentInfo.cs
=> [rpc] `PaymentInfo`: Fix warnings

WalletWasabi/Blockchain/TransactionOutputs/CoinsRegistry.cs, WalletWasabi/Blockchain/TransactionProcessing/TransactionProcessor.cs
Improves https://github.com/zkSNACKs/WalletWasabi/issues/11287
Closes https://github.com/zkSNACKs/WalletWasabi/pull/11513
Closes https://github.com/zkSNACKs/WalletWasabi/pull/11298
=> Speed up transaction processing by 44%

exclusion.dic
As suggested by Kimi here https://github.com/zkSNACKs/WalletWasabi/pull/11329#discussion_r1334251011
=> [Trivial] Add non-words to their group in the spell checker file exclusion.dic

WalletWasabi.Backend/Controllers/OffchainController.cs
Noticed while reviewing #11551
=> `OffchainController`: Fix warnings

WalletWasabi.Backend/Startup.cs, WalletWasabi.Backend/WalletWasabi.Backend.csproj
Close https://github.com/zkSNACKs/WalletWasabi/issues/11582
The web app was looking for static content but wasabi doesn't have static content anymore.
=> Remove web static content

WalletWasabi.Daemon/Rpc/WasabiJsonRpcService.cs
Close https://github.com/zkSNACKs/WalletWasabi/issues/11521
=> Add `loadwallet` RPC method

WalletWasabi.Fluent/ViewModels/Wallets/VerifyRecoveryWordsViewModel.cs
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/11518
=> [VDG] Verify seed words - add `canExecute` to verify button

WalletWasabi/Tor/Http/Models/StatusLine.cs
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/11599
=> Remove http status reason part as required

WalletWasabi.Fluent/ViewModels/Wallets/VerifyRecoveryWordsViewModel.cs, WalletWasabi.Fluent/Views/Wallets/VerifyRecoveryWordsView.axaml
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/11614
=> [VDG] Remove checkmark for verify recovery words dialog

WalletWasabi.Fluent/ViewModels/SearchBar/SearchBarViewModel.cs, WalletWasabi.Fluent/Views/SearchBar/SearchBarDropdown.axaml
Fixes conditions where the SearchBar results dropdown didn't show up correctly when no results are found.
Fixed by redefining of the `HasResults` observable, that wasn't working correctly.
Fixes #9453
Fixes #11632
=> [VDG] Fix empty searchbar dropdown

WalletWasabi/Blockchain/TransactionOutputs/CoinsRegistry.cs
A part of #11516 which is trivial.
=> `CoinsRegistry`: Extract `UpdateSnapshotsNoLock`

WalletWasabi.Fluent/Helpers/TransactionHelpers.cs
Left out of #11662
The least we can do is log the exception IMO.
=> [Trivial] Add missing Exception logging on tx import

WalletWasabi.Daemon/Rpc/WasabiJsonRpcService.cs
Close #11700 
```
$ ./wcli.sh listwallets
name
.hidden
~hidden
Wallet_5
yahia-2.0.2.1
yahia
password-is-pindurs2
taproot
TestNet_Special2
TestNet_Special1
recovered-wallet2
Unknownx
TestNet-bak
segwit-only
taproot2
TestNet_1
wieslav2
Julian
Dan
TestNet2
=> Add `listwallets` rpc call

Contrib/CLI/README.md
anonscoretarget was [added](https://github.com/zkSNACKs/WalletWasabi/pull/11622), coinjoinstatus was [added](https://github.com/zkSNACKs/WalletWasabi/pull/11559), and the rest [as well ](https://github.com/zkSNACKs/WalletWasabi/pull/11701)
=> [Contrib/CLI] update getwalletinfo example

WalletWasabi/WabiSabi/Client/AmountDecomposer.cs
Reverts zkSNACKs/WalletWasabi#11671
=> Revert "Improve amount decomposer fail condition for Trezor integration tests"

WalletWasabi/WabiSabi/Client/AmountDecomposer.cs
Note: This change was already merged to Sake.
=> Add Condition For Non Existent Denominations

WalletWasabi.Fluent/Styles/TextBox.axaml
Fixes: https://github.com/zkSNACKs/WalletWasabi/issues/8789
=> [VDG] Restore padding fix for TextBox.monoSpaced style

WalletWasabi/Blockchain/TransactionOutputs/CoinsRegistry.cs
I extracted the first commit from #11740 as it feels done and a nice contribution on its own.
Credits to @turbolay
=> `CoinsRegistry`: Remove `KnownTransactions`

WalletWasabi.Fluent/Controls/LabelsItemsPresenter.axaml, WalletWasabi.Fluent/Controls/LabelsPanel.cs, WalletWasabi.Fluent/Views/Wallets/Receive/ReceiveAddressView.axaml
Fixes: https://github.com/zkSNACKs/WalletWasabi/issues/11724
Fixes: https://github.com/zkSNACKs/WalletWasabi/issues/11742
=> [VDG] Fix LabelsItemsPresenter layout algorithm after update to Avalonia 11

WalletWasabi.Fluent/ViewModels/Wallets/CoinJoinStateViewModel.cs
Fix https://github.com/zkSNACKs/WalletWasabi/issues/11755
=> Fix countdown when error

WalletWasabi.Fluent/CrashReport/CrashReportApp.axaml
Fixes: https://github.com/zkSNACKs/WalletWasabi/issues/11763
=> [VDG] Add missing themes to CrashReportApp

WalletWasabi.Fluent/Styles/ContextMenu.axaml, WalletWasabi.Fluent/Styles/MenuFlyoutPresenter.axaml
Fixes: https://github.com/zkSNACKs/WalletWasabi/issues/11731
=> [VDG] Fix MenuItem spacing in flyouts and context menus

WalletWasabi.Fluent/Controls/CaptionButtons.axaml, WalletWasabi.Fluent/Styles/Themes/Fluent.axaml
Fixes: https://github.com/zkSNACKs/WalletWasabi/issues/11725
=> [VDG] Workaround for invalid caption buttons theme

WalletWasabi.Fluent/App.axaml, WalletWasabi.Fluent/Controls/AmountControl.axaml, WalletWasabi.Fluent/Styles/Themes/Fluent.axaml
Continuation of work from https://github.com/zkSNACKs/WalletWasabi/pull/10423 for AmountControl control
=> [VFG] Migrate AmountControl to control themes

WalletWasabi.Fluent/Controls/LineChart.cs
To easily review turn off whitespace change: https://github.com/zkSNACKs/WalletWasabi/pull/11793/files?diff=unified&w=1
=> `LineChart` Remove unused parameter

WalletWasabi.Fluent/Controls/NavBarItem.axaml
Fixes: https://github.com/zkSNACKs/WalletWasabi/issues/11726
=> [VDG] Fix NavBar item font and icon color is different when it is disabled

WalletWasabi.Tests/UnitTests/Blockchain/TransactionOutputs/CoinsRegistryTests.cs, WalletWasabi/Blockchain/TransactionOutputs/CoinsRegistry.cs
@kiminuo Looks like an error in a recent PR?
=> Only update amount if coin is added

WalletWasabi.Fluent/Views/Login/PasswordFinder/PasswordFoundView.axaml
Fixes: https://github.com/zkSNACKs/WalletWasabi/issues/11749
https://github.com/AvaloniaUI/Avalonia/blob/77e1abcc68cd7d2433e4eef4edb7c4f27b551447/src/Avalonia.Themes.Fluent/Controls/TextBox.xaml#L233
=> [VDG] Fix PasswordFoundView reveal password button

WalletWasabi.Fluent/Controls/LineChart.cs, WalletWasabi.Tests/UnitTests/Helpers/PowerSaving/BaseInhibitorTaskTests.cs, WalletWasabi.Tests/UnitTests/Helpers/PowerSaving/MockProcessAsync.cs, WalletWasabi.Tests/UnitTests/MockHttpClient.cs, WalletWasabi.Tests/UnitTests/MockHttpClientExtensions.cs, WalletWasabi.Tests/UnitTests/MockIHttpClient.cs, WalletWasabi.Tests/UnitTests/WabiSabi/Integration/MockWasabiHttpClientFactory.cs, WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiHttpApiIntegrationTests.cs, WalletWasabi.Tests/UnitTests/Wallet/MockBlockRepository.cs, WalletWasabi.Tests/UnitTests/Wallet/WalletBuilder.cs
This simply moves some classes to separate files.
=> Fix Codefactor

WalletWasabi/WabiSabi/Client/CoinJoinClient.cs, WalletWasabi/WabiSabi/LoggerTools.cs, WalletWasabi/WabiSabi/Models/RoundState.cs
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/11779
=> Don't skip blame rounds

WalletWasabi.Fluent/Models/Wallets/WalletCoinsModel.cs, WalletWasabi.Fluent/Models/Wallets/WalletModel.cs, WalletWasabi.Fluent/Models/Wallets/WalletModelExtensions.cs, WalletWasabi.Fluent/ViewModels/Wallets/Receive/ReceiveAddressViewModel.cs, WalletWasabi.Tests/UnitTests/ViewModels/ReceiveAddressViewModelTests.cs, WalletWasabi.Tests/UnitTests/ViewModels/ReceiveViewModelTests.cs, WalletWasabi.Tests/UnitTests/ViewModels/SuggestionLabelsViewModelTests.cs
Correctly fetch changes when signal arrives.
This is for Addresses only.
=> [VDG] Use fetcher for addresses

WalletWasabi.Tests/Helpers/WabiSabiFactory.cs, WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepConnectionConfirmationTests.cs, WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepTransactionSigningTests.cs, WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterInputFailureTests.cs, WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterInputToBlameRoundTests.cs, WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PrisonTests.cs, WalletWasabi.Tests/UnitTests/WabiSabi/Backend/UtxoPrisonWardenTests.cs, WalletWasabi/WabiSabi/Backend/DoSPrevention/Prison.cs, WalletWasabi/WabiSabi/Backend/DoSPrevention/Warden.cs, WalletWasabi/WabiSabi/Backend/Rounds/Arena.Partial.cs, WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs, WalletWasabi/WabiSabi/Backend/WabiSabiConfig.cs, WalletWasabi/WabiSabi/WabiSabiCoordinator.cs
This PR avoids to recalculate the punishment for each outpoint again and again, which is problematic for those that inherit the punishment from their ancestors.
=> Prison inheritance performance improvement

WalletWasabi.Fluent/Converters/MoneyConverters.cs, WalletWasabi.Fluent/Extensions/CurrencyExtensions.cs, WalletWasabi.Fluent/Views/Wallets/Home/Tiles/BtcPriceTileView.axaml
Fixes: https://github.com/zkSNACKs/WalletWasabi/issues/11776
=> [VDG] Fix usd formatting in tiles

WalletWasabi.Fluent/Behaviors/HistoryItemTypeClassBehavior.cs, WalletWasabi.Fluent/Views/Wallets/Home/History/HistoryTable.axaml
Fixes: https://github.com/zkSNACKs/WalletWasabi/issues/9920
=> [VDG] Fix setting classes for history items

WalletWasabi.Tests/IntegrationTests/ExternalApiTests.cs, WalletWasabi/WebClients/Coingate/CoingateExchangeRateProvider.cs, WalletWasabi/WebClients/ExchangeRateProviders.cs
close #11143 
Not the main exchange rate provider. This is just alternative if main one doesn't work
=> Added 1 more Exchange rate provider

WalletWasabi.Fluent/Models/Wallets/WalletModel.cs
Reduces the complexity of the `Balances` observable.
=> [VDG] [Trivial] Simplify balances

WalletWasabi.Fluent/Helpers/ApplicationHelper.cs
Part of: https://github.com/zkSNACKs/WalletWasabi/issues/11625
There is no Window in mobile, we need to use TopLevel class.
=> [VDG] [Mobile] Add single lifetime clipboard support

WalletWasabi.Fluent/Controls/PrivacyContentControl.axaml, WalletWasabi.Fluent/Controls/PrivacyContentControl.axaml.cs, WalletWasabi.Fluent/Controls/PrivacyTextPresenter.cs, WalletWasabi.Fluent/Views/Wallets/Advanced/WalletCoins/Columns/LabelsColumnView.axaml, WalletWasabi.Fluent/Views/Wallets/Home/History/Columns/LabelsColumnView.axaml, WalletWasabi.Fluent/Views/Wallets/Receive/Columns/LabelsColumnView.axaml
Fixes: https://github.com/zkSNACKs/WalletWasabi/issues/11730
=> [VDG] Introduce MaxPrivacyChars for PrivacyContentControl

WalletWasabi.Fluent/Models/Wallets/AddressesModel.cs, WalletWasabi.Fluent/Models/Wallets/WalletModel.cs
This refreshes the addresses when new addresses are created.
=> Fix 'addresses awaiting payment' link not displayed when creating new addresses

WalletWasabi.Fluent/ViewModels/Wallets/WalletPageViewModel.cs
This PR make it impossible to bypass Wallet Info password entry from the SearchBar.
Fixes #11804
=> [VDG] Fix wallet info bypass

WalletWasabi.Fluent/Models/Wallets/WalletModel.cs
fix the issue that was introduced by my commit.
NewTransactionArrived still makes more sense, but a sample is missing so it caused UI lag.
=> [UI] fix lag

WalletWasabi.Fluent/Extensions/CommandExtension.cs, WalletWasabi.Fluent/ViewModels/SearchBar/SearchItems/NestedItemConfiguration.cs, WalletWasabi.Fluent/ViewModels/SearchBar/SearchItems/SearchItemNode.cs, WalletWasabi.Fluent/ViewModels/SearchBar/SettingsSearchSource.cs, WalletWasabi.Fluent/ViewModels/SearchBar/Sources/EditableSearchSourceExtensions.cs, WalletWasabi.Fluent/ViewModels/Wallets/WalletPageViewModel.cs, WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModel.cs
This PR makes the Send dialog unavailable when balance is zero.
Fixes #11806
=> [VDG] Fix "Send" is available even when no balance in Search Bar.

WalletWasabi.Fluent/Views/Shell/Shell.axaml
For testing purposes - do not review.
https://github.com/zkSNACKs/WalletWasabi/assets/2297442/48960421-1a8f-4785-9196-12e485cff076
=> [VDG] Add blur effect to background when dialog is shown

WalletWasabi.Fluent/Views/Shell/Shell.axaml
Followup on https://github.com/zkSNACKs/WalletWasabi/pull/11853 introduces better solution.
=> [VDG] Use EffectTransition instead of Animations for dialog background blur

WalletWasabi.Fluent/ViewModels/NavBar/NavBarViewModel.cs, WalletWasabi.Fluent/Views/NavBar/NavBar.axaml
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/11916
Fixes #11729
=> [VDG] Fix NavBar issues

Directory.Packages.props, WalletWasabi.Fluent.Desktop/packages.lock.json, WalletWasabi.Fluent.Generators/packages.lock.json, WalletWasabi.Fluent/packages.lock.json
Downgrade `Microsoft.CodeAnalysis.Common` and ` Microsoft.CodeAnalysis.CSharp`
=> Fix Analyzer version

WalletWasabi.Fluent/Models/Wallets/TransactionModel.cs, WalletWasabi.Fluent/Models/Wallets/TransactionTreeBuilder.cs, WalletWasabi.Fluent/ViewModels/Wallets/Home/History/Details/TransactionDetailsViewModel.cs, WalletWasabi.Fluent/Views/Wallets/Home/History/Details/TransactionDetailsView.axaml, WalletWasabi/Blockchain/Transactions/TransactionSummary.cs
Adds Fee Rate to Transaction Details.
=> [VDG] Add Fee Rate to Transaction Details

WalletWasabi.Fluent/Views/Wallets/Home/History/Details/TransactionDetailsView.axaml
Fixes display unit for fee rate.
Master:
This PR:
Fixes: https://github.com/zkSNACKs/WalletWasabi/pull/11968
=> [VDG] Correct units for Fee Rate

WalletWasabi.Daemon/Global.cs, WalletWasabi/WabiSabi/Client/Banning/CoinPrison.cs
Cherry-picked from https://github.com/zkSNACKs/WalletWasabi/pull/11958
=> [v2.0.4.1 Silent Release] Local Prison invalidation

WalletWasabi.Tests/IntegrationTests/ShopWareApiClientTests.cs, WalletWasabi/BuyAnything/BuyAnythingManager.cs, WalletWasabi/WebClients/BuyAnything/BuyAnythingClient.cs, WalletWasabi/WebClients/ShopWare/Models/Customer.cs, WalletWasabi/WebClients/ShopWare/ShopWareApiClient.cs
Credits to @Szpoti
This is easier than cherry-picking.
=> Add Login logic and test

WalletWasabi.Daemon/Global.cs, WalletWasabi.Fluent/ViewModels/Wallets/Buy/BuyViewModel.cs, WalletWasabi.Tests/IntegrationTests/ShopWareApiClientTests.cs, WalletWasabi/BuyAnything/BuyAnythingManager.cs, WalletWasabi/BuyAnything/ConversationExtensions.cs, WalletWasabi/BuyAnything/ConversationUpdateTrack.cs, WalletWasabi/WebClients/ShopWare/ShopWareApiClient.cs
=> Use IHttpClient + Misc

WalletWasabi.Fluent/ViewModels/Wallets/Buy/Workflows/ShopinBit/Initial/Validators/ProductInputValidator.cs, WalletWasabi.Fluent/Views/Wallets/Buy/OrderMessagesView.axaml
=> Adapt to Figma designs

WalletWasabi.Fluent/ViewModels/Wallets/Buy/BuyViewModel.cs, WalletWasabi.Fluent/ViewModels/Wallets/Buy/Workflows/ShopinBit/ShopinBitWorkflowManager.cs, WalletWasabi/BuyAnything/BuyAnythingManager.cs
=> Trigger event upon new conversation

WalletWasabi/BuyAnything/BuyAnythingManager.cs
=> Better offer display

WalletWasabi.Fluent/ViewModels/Wallets/Buy/Messages/PayNowAssistantMessageViewModel.cs, WalletWasabi.Fluent/ViewModels/Wallets/Buy/OrderViewModel.cs, WalletWasabi/BuyAnything/BuyAnythingManager.cs, WalletWasabi/BuyAnything/ChatMessage.cs, WalletWasabi/BuyAnything/Conversation.cs
=> store IsPaid in Invoice

WalletWasabi.Fluent/ViewModels/Wallets/Buy/OrderViewModel.cs, WalletWasabi.Fluent/ViewModels/Wallets/Buy/Workflows/ShopinBit/1 - Initial/StartConversationStep.cs, WalletWasabi.Fluent/ViewModels/Wallets/Buy/Workflows/ShopinBit/2 - Delivery/AcceptOfferStep.cs, WalletWasabi.Fluent/ViewModels/Wallets/Buy/Workflows/ShopinBit/2 - Delivery/SaveConversationStep.cs, WalletWasabi.Fluent/ViewModels/Wallets/Buy/Workflows/ShopinBit/3 - Support/SupportChatStep.cs, WalletWasabi.Fluent/ViewModels/Wallets/Buy/Workflows/Workflow.cs, WalletWasabi.Fluent/ViewModels/Wallets/Buy/Workflows/WorkflowStep.cs, WalletWasabi/BuyAnything/BuyAnythingManager.cs
- Resilient workflow execution (graceful Step error handling)
- Fix ChatSupportStep not working
- remove unused method and leftover code
=> Buy anything cordoba edition

WalletWasabi.Packager/Program.cs, WalletWasabi.WindowsInstaller/WalletWasabi.WindowsInstaller.wixproj, azure-pipelines-detbuild.yml
Follow-up to #11897
Continuous delivery is [red](https://github.com/zkSNACKs/WalletWasabi/runs/19745274141). Hopefully, this PR fixes that.
=> Attempt to use new Windows RID

WalletWasabi.Fluent/ViewModels/Wallets/Buy/Messages/PayNowAssistantMessageViewModel.cs
=> Rename pay now to pay

WalletWasabi.Fluent/ViewModels/Wallets/Buy/Workflows/ShopinBit/1 - Initial/CountryStep.cs, WalletWasabi.Fluent/ViewModels/Wallets/Buy/Workflows/ShopinBit/1 - Initial/RequestedItemStep.cs, WalletWasabi.Fluent/ViewModels/Wallets/Buy/Workflows/ShopinBit/1 - Initial/StartConversationStep.cs, WalletWasabi.Fluent/ViewModels/Wallets/Buy/Workflows/ShopinBit/1 - Initial/WelcomeStep.cs, WalletWasabi.Fluent/Views/Wallets/Buy/BuyView.axaml, WalletWasabi.Fluent/Views/Wallets/WalletView.axaml
Replaces #12039
This mainly simplifies the text.
PR:
Curent BuyAnythingButton-v2.0.4.1:
=> [Trivial] Simplify the wording and remove unnecessary text

WalletWasabi.Documentation/ClientRelease/ReleaseNotesTemplate.md, WalletWasabi.Documentation/WasabiCompatibility.md
since we're using .NET 8
https://github.com/dotnet/core/blob/main/release-notes/8.0/supported-os.md
=> bump supported OS versions with .NET 8

WalletWasabi.Fluent/Converters/MoneyConverters.cs
Closes https://github.com/zkSNACKs/WalletWasabi/pull/11944/files
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/11747
=> [UI] Fix usd balance copy button is not clickable

WalletWasabi.Tests/UnitTests/KeyManagementTests.cs, WalletWasabi/Blockchain/Keys/KeyManager.cs
This PR allows the generation of external taproot scripts.
Related: https://github.com/zkSNACKs/WalletWasabi/issues/12088
=> Generate Taproot external keys

WalletWasabi.Fluent/Views/AddWallet/Create/ConfirmRecoveryWordsView.axaml, WalletWasabi.Fluent/Views/AddWallet/Create/RecoveryWordsView.axaml
Fixes: https://github.com/zkSNACKs/WalletWasabi/issues/12091
=> [VDG] Fix recovery words dialog lines visibility

WalletWasabi.Documentation/ClientRelease/ClientDeployment.md, WalletWasabi.Documentation/Guides/HowToDebug.md, WalletWasabi.Documentation/Guides/MacOsSigning.md, WalletWasabi.Documentation/WasabikaCodex.md, WalletWasabi/Gma/QrCodeNet/Encoding/QRCodeConstantVariable.cs, WalletWasabi/Nito/Disposables/Internals/BoundAction.cs, WalletWasabi/Nito/Disposables/SingleDisposable.cs, WalletWasabi/WabiSabi/Client/CredentialDependencies/CredentialEdgeSet.cs
Fix typos in Documentation
Fix typos in WalletWasabi/
=> Fix typos in Documentation

WalletWasabi/Blockchain/Transactions/TransactionStore.cs
Fixes https://github.com/zkSNACKs/WalletWasabi/pull/12202#issuecomment-1892547705
If someone wants to change code style I agree with that but please push to the PR directly
=> Fix oldPath for transactions migration

WalletWasabi.Fluent/ViewModels/Wallets/WalletRenameViewModel.cs, WalletWasabi.Fluent/ViewModels/Wallets/WalletSettingsViewModel.cs
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/12253
=> [UI] Update the last selected wallet after rename

Directory.Packages.props, WalletWasabi.Fluent.Desktop/packages.lock.json, WalletWasabi.Fluent/packages.lock.json
macos docking apis and some memory leak fixes.
This will allow us to merge #12230 and #12210
=> update to Avalonia 11.0.7

WalletWasabi/Wallets/WalletFilterProcessor.cs
After https://github.com/zkSNACKs/WalletWasabi/pull/12273 it is not necessary to materialize the sync info.
=> Avoid unnecessary materialization

WalletWasabi.Fluent/Behaviors/ListBoxPreviewBehavior.cs, WalletWasabi.Fluent/Views/Wallets/Send/PrivacyWarningsView.axaml
With this PR the preview won't be stuck.
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/11758
=> [UI] Fix broken Send Privacy Suggestion preview on ALT+TAB

WalletWasabi.Fluent/App.axaml, WalletWasabi.Fluent/App.axaml.cs, WalletWasabi.Fluent/ApplicationStateManager.cs, WalletWasabi.Fluent/ViewModels/SearchBar/SettingsSearchSource.cs, WalletWasabi.Fluent/Views/Settings/GeneralSettingsTabView.axaml
closes https://github.com/zkSNACKs/WalletWasabi/issues/8151 
closes https://github.com/zkSNACKs/WalletWasabi/issues/8665
=> Fix osx dock icon issues

WalletWasabi/Bases/PeriodicRunner.cs
=> Add `HttpRequestException` handling in `PeriodicRunner`

WalletWasabi/Rpc/JsonRpcRequestHandler.cs, WalletWasabi/Rpc/JsonRpcResponse.cs
This is a refactoring that is required to implement changes in the http status codes
=> Split `JsonRpcResponse` is success and error

WalletWasabi/WabiSabi/Client/OutputProvider.cs
Fix https://github.com/zkSNACKs/WalletWasabi/issues/12317
=> Ensure only valid decompositions

WalletWasabi.Fluent/Models/Wallets/TransactionTreeBuilder.cs
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/12345
=> [UI] fix cancel icon

WalletWasabi.Fluent/Helpers/FlyoutHelpers.cs
This also fixed the null warning
=> Fix crash when opening send

WalletWasabi.Fluent/ViewModels/SearchBar/Sources/TransactionsSearchSource.cs
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/12372
=> [VDG] Do not call NavigateAndHighlight if selected wallet is the same as found one

WalletWasabi.Fluent/Converters/MoneyConverters.cs, WalletWasabi.Fluent/Views/Wallets/Home/Tiles/WalletBalanceTileView.axaml
https://github.com/zkSNACKs/WalletWasabi/pull/12374
=> [Release] fix USD amount copy

WalletWasabi.Fluent/Behaviors/FlyoutSuggestionBehavior.cs, WalletWasabi.Fluent/Controls/CurrencyEntryBox.axaml.cs, WalletWasabi.Fluent/Controls/DualCurrencyEntryBox.axaml.cs, WalletWasabi.Fluent/Views/Wallets/Send/SendView.axaml
https://github.com/zkSNACKs/WalletWasabi/pull/12380
=> [Release] Fix CurrencyEntryBox

WalletWasabi.Fluent/ViewModels/SearchBar/Sources/TransactionsSearchSource.cs
https://github.com/zkSNACKs/WalletWasabi/pull/12383
=> [Release] Fix history after txn search

WalletWasabi.Fluent/ViewModels/Wallets/CoinJoinStateViewModel.cs
https://github.com/zkSNACKs/WalletWasabi/pull/12252
=> [2.0.6 release] musicbox: update RandomlySkippedRoundMessage

WalletWasabi.Fluent/Behaviors/FocusControlActionCustom.cs, WalletWasabi.Fluent/ViewModels/Wallets/Buy/BuyViewModel.cs, WalletWasabi.Fluent/ViewModels/Wallets/Buy/OrderViewModel.cs, WalletWasabi.Fluent/ViewModels/Wallets/Buy/Workflows/WorkflowStep.cs, WalletWasabi.Tests/IntegrationTests/ShopWareApiClientTests.cs, WalletWasabi.Tests/UnitTests/BuyAnything/BuyAnythingSerializationTests.cs, WalletWasabi.Tests/UnitTests/ViewModels/UiContext/NullApplicationSettings.cs, WalletWasabi/BuyAnything/BuyAnythingManager.cs, WalletWasabi/BuyAnything/ConversationExtensions.cs, WalletWasabi/BuyAnything/ConversationUpdateTrack.cs, WalletWasabi/WebClients/BuyAnything/BuyAnythingClient.cs
Some code clean ups after #12181 was merged.
This simply removes unused fields, parameters, and fixes small typos.
There is other code where some fields or parameter are not used but removing those would lead to a cascade of changes, so maybe some dev should check that:
https://github.com/zkSNACKs/WalletWasabi/blob/85165479e6baedc140ae6cca89d111776de5642f/WalletWasabi/WebClients/BuyAnything/BuyAnythingClient.cs#L113-L114
https://github.com/zkSNACKs/WalletWasabi/blob/85165479e6baedc140ae6cca89d111776de5642f/WalletWasabi.Fluent/ViewModels/Wallets/Buy/BuyViewModel.cs#L130
=> Code cleanup

WalletWasabi.Fluent/ViewModels/Wallets/Buy/BuyViewModel.cs, WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModel.cs
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/12401
=> [UI] Fix duplicate orders

WalletWasabi.Fluent/ViewModels/Wallets/Buy/BuyViewModel.cs, WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModel.cs
https://github.com/zkSNACKs/WalletWasabi/pull/12409
=> [Release] Fix duplicate orders

WalletWasabi.Tests/UnitTests/Wallet/WalletFilterProcessorTests.cs, WalletWasabi/Wallets/Wallet.cs
Justification: https://github.com/zkSNACKs/WalletWasabi/pull/12411#issuecomment-1935979248
@molnard @soosr Can you try to reproduce with this branch merged? I still haven't been able to repro the issue.
If it doesn't fix the problem, I suggest to go with #12411 for the release
=> Move NewFiltersEvent registration after Initial Tx Process

WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/PrivacyRing/PrivacyRingItemViewModel.cs, WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/PrivacyRing/PrivacyRingViewModel.cs, WalletWasabi.Fluent/Views/Wallets/Home/Tiles/PrivacyRing/PrivacyRingItemDetailsView.axaml
https://github.com/zkSNACKs/WalletWasabi/pull/12421
=> [Release] PrivacyRing - Fix anonscore when display pockets

WalletWasabi.Fluent/CrashReport/CrashReporter.cs, WalletWasabi/Microservices/ProcessStartInfoFactory.cs
Fixes #12407 
Based on @soosr's idea in #12415
This was tested on Mac, Windows and Linux (thanks @kristapsk for Linux's test) and this solution works.
I'm not sure about the underlying cause of the problem, but this works and doesn't change behaviour of other components calling `Make`.
=> Fix CrashReporter window - Continuation

WalletWasabi.Fluent/ViewModels/Wallets/Buy/OrderViewModel.cs, WalletWasabi.Fluent/ViewModels/Wallets/Buy/Workflows/ShopinBit/1_Initial/StartConversationStep.cs, WalletWasabi.Fluent/ViewModels/Wallets/Buy/Workflows/ShopinBit/2_Delivery/AcceptOfferStep.cs, WalletWasabi.Fluent/ViewModels/Wallets/Buy/Workflows/ShopinBit/2_Delivery/SaveConversationStep.cs, WalletWasabi.Fluent/ViewModels/Wallets/Buy/Workflows/ShopinBit/4_Finished/OrderFinishedMessage.cs, WalletWasabi.Fluent/ViewModels/Wallets/Buy/Workflows/ShopinBit/ShopinBitWorkflow.cs, WalletWasabi.Fluent/ViewModels/Wallets/Buy/Workflows/Workflow.cs, WalletWasabi.Fluent/ViewModels/Wallets/Buy/Workflows/WorkflowStep.cs
https://github.com/zkSNACKs/WalletWasabi/pull/12406
=> [Release] BAB - Fix error handling

WalletWasabi.Tests/UnitTests/Wallet/WalletFilterProcessorTests.cs, WalletWasabi/Wallets/Wallet.cs
https://github.com/zkSNACKs/WalletWasabi/pull/12413
=> [Release] Move NewFiltersEvent registration after Initial Tx Process

WalletWasabi.Fluent/CrashReport/CrashReporter.cs, WalletWasabi/Microservices/ProcessStartInfoFactory.cs
=> [Release] Fix CrashReporter window - Continuation

WalletWasabi.Daemon/Global.cs, WalletWasabi.Daemon/WasabiAppBuilder.cs, WalletWasabi.Fluent.Desktop/Program.cs
Fixes #12360
Alternative to #12366
Idea suggested by Lucas here https://github.com/zkSNACKs/WalletWasabi/pull/12366#issuecomment-1936296496.
=> Disable SleepInhibitor in Daemon

WalletWasabi.Fluent/Controls/Rendering/DrawCompositionCustomVisualHandler.cs, WalletWasabi.Fluent/Controls/Spectrum/SpectrumControl.cs
=> [UI] Update spectrum control bounds

WalletWasabi.Fluent/Controls/Rendering/DrawCompositionCustomVisualHandler.cs, WalletWasabi.Fluent/Controls/Spectrum/SpectrumControl.cs
https://github.com/zkSNACKs/WalletWasabi/pull/12436
=> [Release] Fix CJ aura

WalletWasabi.Fluent/ViewModels/Wallets/Buy/BuyViewModel.cs, WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModel.cs
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/12399
=> [UI] fix BuyAnything button visibility

WalletWasabi.Fluent/ViewModels/Wallets/Buy/BuyViewModel.cs, WalletWasabi.Fluent/ViewModels/Wallets/Buy/IOrderManager.cs, WalletWasabi.Fluent/ViewModels/Wallets/Buy/OrderViewModel.cs, WalletWasabi.Fluent/ViewModels/Wallets/Buy/Workflows/Workflow.cs
https://github.com/zkSNACKs/WalletWasabi/pull/12433
=> [Release] BuyAnything - error dialog adjustment

WalletWasabi.Fluent/Views/Settings/BitcoinTabSettingsView.axaml
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/12300
=> [VDG] Fix discreet mode hover not working for Bitcoin P2P endpoint

WalletWasabi.Fluent/ViewModels/Wallets/Buy/BuyViewModel.cs, WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModel.cs
https://github.com/zkSNACKs/WalletWasabi/pull/12410
=> [Release] Fix BuyAnything button visibility

WalletWasabi.Fluent/Views/Settings/BitcoinTabSettingsView.axaml
https://github.com/zkSNACKs/WalletWasabi/pull/12440
=> [Release] discreet mode fix

WalletWasabi.Fluent/ViewModels/Wallets/Buy/BuyViewModel.cs, WalletWasabi.Fluent/ViewModels/Wallets/Buy/OrderViewModel.cs, WalletWasabi.Fluent/ViewModels/Wallets/Buy/Workflows/Workflow.cs
https://github.com/zkSNACKs/WalletWasabi/pull/12439
=> [Release] fix unread badge

WalletWasabi.Fluent/ViewModels/Wallets/Buy/Workflows/ShopinBit/1_Initial/CountryStep.cs
Fixes: https://github.com/zkSNACKs/WalletWasabi/issues/12447
=> [BAB] Adjust minimum amount wording

WalletWasabi.Fluent/ViewModels/Wallets/Buy/Workflows/ShopinBit/1_Initial/RequestedItemStep.cs, WalletWasabi.Fluent/ViewModels/Wallets/Buy/Workflows/WorkflowStep.cs, WalletWasabi.Fluent/Views/Wallets/Buy/UserInputValidatorView.axaml
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/12445
This PR adds a char counter where it makes sense. Plus also sets the minimum limit where needed.
=> [UI] Add char limit

WalletWasabi.Fluent/ViewModels/Wallets/Buy/Messages/AssistantMessageViewModel.cs
Removes `@timestamp@` from the beginning of messages, only on the UI side.
=> [BaB] Remove timestamp from UI message

WalletWasabi.Fluent/ViewModels/Wallets/Buy/Workflows/ShopinBit/1_Initial/RequestedItemStep.cs, WalletWasabi.Fluent/ViewModels/Wallets/Buy/Workflows/WorkflowStep.cs, WalletWasabi.Fluent/Views/Wallets/Buy/UserInputValidatorView.axaml
https://github.com/zkSNACKs/WalletWasabi/pull/12453/
=> [Release] BAB - char limit

WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModel.cs
Commits from the release branch.
=> Adjust bab visibility

WalletWasabi.Fluent/ViewModels/Wallets/Buy/Messages/AssistantMessageViewModel.cs
=> [Release] Remove timestamp from UI message

WalletWasabi.Fluent/ViewModels/Wallets/Buy/Workflows/ShopinBit/1_Initial/CountryStep.cs
nit
master
```
Hello, I am your chosen Fast Travel Assistant.
For now, the MINIMUM ORDER VALUE is $1,000 USD and we only accept requests for LEGAL goods or services.
```
PR
```
Hello, I am your Fast Travel Assistant.
For now, the MINIMUM ORDER VALUE is $1,000 USD and we only accept requests for LEGAL goods or services.
```
the word "chosen" reads weird and doesn't add anything
=> [BAB] [trivial] update assistant greeting, remove "chosen"

WalletWasabi.Fluent/ViewModels/Wallets/Buy/Workflows/ShopinBit/1_Initial/CountryStep.cs
https://github.com/zkSNACKs/WalletWasabi/pull/12462
=> [2.0.6 release] BAB: update assistant greeting text

WalletWasabi.Fluent/ViewModels/Login/PasswordFinder/PasswordFinderIntroduceViewModel.cs
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/12461#issuecomment-1943309167
=> [UI] PasswordFinder - add missing navtaget

WalletWasabi.Fluent/ViewModels/Login/PasswordFinder/PasswordFinderIntroduceViewModel.cs
https://github.com/zkSNACKs/WalletWasabi/pull/12469/commits
=> [Release] add missing navtaget

WalletWasabi.Fluent/Controls/Dialog.axaml.cs
https://github.com/zkSNACKs/WalletWasabi/pull/12468/commits
=> [Release] fix pointer event

WalletWasabi.Fluent/ViewModels/Wallets/Buy/Workflows/ShopinBit/1_Initial/RequestedItemStep.cs, WalletWasabi.Fluent/Views/Wallets/Buy/UserInputValidatorView.axaml
=> [UI] BAB - improve UX of min char limit

WalletWasabi.Fluent/ViewModels/Wallets/Buy/Workflows/ShopinBit/1_Initial/RequestedItemStep.cs, WalletWasabi.Fluent/Views/Wallets/Buy/UserInputValidatorView.axaml
https://github.com/zkSNACKs/WalletWasabi/pull/12472/commits
=> [Release] bab min char ux

WalletWasabi/Helpers/HardwareWalletOperationHelpers.cs
This PR cherry picks the commit from #12437.
I guess the change should have first been added to `master` then to `release_v2.0.6`.
=> Disable Taproot KeyPath under HW first connection

WalletWasabi.Fluent/ViewModels/Wallets/Send/SendViewModel.cs, WalletWasabi/Userfacing/Bip21/Bip21UriParser.cs
=> [Release] Fix PayJoin

WalletWasabi.Tests/UnitTests/Userfacing/Bip21/Bip21UriParserTests.cs
Follow-up to #12417
Addresses https://github.com/zkSNACKs/WalletWasabi/pull/12417#discussion_r1486196738
=> [BIP21 parser] Add tests for unknown parameters

WalletWasabi/BuyAnything/BuyAnythingManager.cs, WalletWasabi/WebClients/ShopWare/Models/Order.cs
=> [Release] Fix shipping cost not showing

WalletWasabi.Tests/UnitTests/WabiSabi/Client/IsRoundEconomicTests.cs, WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
=> [Release] Time preference lower time frames

WalletWasabi.Fluent/Views/AddWallet/WelcomePageView.axaml
re-attempt at https://github.com/zkSNACKs/WalletWasabi/pull/10991
several people are confused about the inaccurate wording
=> [VDG] fix welcome page inaccuracies

WalletWasabi.Fluent/Views/AddWallet/WelcomePageView.axaml
https://github.com/zkSNACKs/WalletWasabi/pull/12483, cherry-picked the commit
=> [release_v2.0.6] fix welcome page inaccuracies

WalletWasabi/Helpers/IoHelpers.cs
https://github.com/zkSNACKs/WalletWasabi/pull/12485
=> [Release] fix opening browser on macos

WalletWasabi.Fluent/Converters/TextToInlineCollectionConverter.cs, WalletWasabi.Fluent/ViewModels/Wallets/Buy/Workflows/ShopinBit/1_Initial/CountryStep.cs, WalletWasabi.Fluent/ViewModels/Wallets/Buy/Workflows/ShopinBit/1_Initial/WelcomeStep.cs, WalletWasabi.Fluent/Views/Wallets/Buy/OrderMessagesView.axaml
Adds a new message with hyperlink to the required URL.
Pending, the message doesn't render the link even thoug it's there.
Can you please help @ichthus1604 @wieslawsoltes?
Fixes #12446
=> [UI][BAB] Remove assistant's explanation

WalletWasabi.Fluent/Converters/TextToInlineCollectionConverter.cs, WalletWasabi.Fluent/ViewModels/Wallets/Buy/Workflows/ShopinBit/1_Initial/WelcomeStep.cs, WalletWasabi.Fluent/Views/Wallets/Buy/OrderMessagesView.axaml
https://github.com/zkSNACKs/WalletWasabi/pull/12458
=> [Release] BAB explanation link

WalletWasabi.Fluent/Views/Wallets/MusicControlsView.axaml
It crashes sometimes depending on the system.
=> do not use inlines, its buggy.

WalletWasabi.Fluent/Views/Wallets/MusicControlsView.axaml
https://github.com/zkSNACKs/WalletWasabi/pull/12507
=> [Release] Remove usuage of inlines completely

Directory.Build.props, Directory.Packages.props, NuGet.Config, WalletWasabi.Fluent.Desktop/packages.lock.json, WalletWasabi.Fluent/ApplicationStateManager.cs, WalletWasabi.Fluent/packages.lock.json
https://github.com/zkSNACKs/WalletWasabi/pull/12505
=> [Release] Fix Linux popup and flyout issues 2

WalletWasabi.Fluent/Controls/ContentArea.axaml, WalletWasabi.Fluent/Controls/ContentArea.axaml.cs, WalletWasabi.Fluent/Views/Wallets/LoadingView.axaml, WalletWasabi.Fluent/Views/Wallets/Send/SendView.axaml, WalletWasabi.Fluent/Views/Wallets/Send/TransactionPreviewView.axaml, WalletWasabi.Fluent/Views/Wallets/WalletView.axaml
- Introduces `TopContent` and `BottomContent` properties for `ContentArea` control.
- Replaces usages of `Title` property to include additional UI elements in: `LoadingView`, `SendView`, `TransactionPreviewView` and `WalletView`.
- Fixes #12362
=> [VDG] ContentArea Improvements

WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
Equivalent of https://github.com/zkSNACKs/WalletWasabi/pull/12502
=> [Release] Fix StopWhenAllMixed = false

WalletWasabi.Fluent/TreeDataGrid/TreeDataGridPrivacyTextCell.cs
https://github.com/zkSNACKs/WalletWasabi/pull/12510
=> [Release] fix privacy cell discreet mode

WalletWasabi/BuyAnything/BuyAnythingManager.cs
https://github.com/zkSNACKs/WalletWasabi/pull/12522
=> [Release] Fix crash when countries cannot be retrieved.

WalletWasabi.Fluent/Models/Wallets/HealthMonitor.cs, WalletWasabi/Services/WasabiSynchronizer.cs
https://github.com/zkSNACKs/WalletWasabi/pull/12504
=> [Release] Simplify synchronizer gensock event reporting

WalletWasabi.Fluent/Controls/DualCurrencyEntryBox.axaml.cs, WalletWasabi.Fluent/ViewModels/Wallets/Send/SendViewModel.cs
=> [Release] SendViewModel: Make AmountBtc nullable

WalletWasabi.Fluent/Controls/CurrencyEntryBox.axaml.cs
https://github.com/zkSNACKs/WalletWasabi/pull/12542
=> [Release] paste amount selection fix

WalletWasabi.Fluent/Models/Wallets/WalletCoinjoinModel.cs
https://github.com/zkSNACKs/WalletWasabi/pull/12538
=> [Release] fix aura on CJ completed

WalletWasabi.Fluent/Controls/PreviewMessageItem.axaml.cs, WalletWasabi.Fluent/Views/Wallets/Buy/UserInputValidatorView.axaml
=> [VDG] Fix errors in ide

WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
Clone of https://github.com/zkSNACKs/WalletWasabi/pull/12554
=> [Release] Revert "Fix "StopWhenAllMixed = false doesn't work""

WalletWasabi.Fluent/ViewModels/Wallets/CoinJoinStateViewModel.cs, WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
Clone of https://github.com/zkSNACKs/WalletWasabi/pull/12553
=> [Release] Add missing state machine transition when wallet reached 100% - take 2

WalletWasabi.Fluent/Controls/TextBox.axaml, WalletWasabi.Fluent/Views/Wallets/Send/SendView.axaml
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/12449
=> [VDG] Fix send To address field scrolling

WalletWasabi/Helpers/Constants.cs
Placeholder PR for bumping the version number.
This PR should be the last PR merged to the branch, if everything goes well.
=> [Release] Bump version to v2.0.6

WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModel.cs
https://github.com/zkSNACKs/WalletWasabi/pull/12566
=> fix visibility on testnet

WalletWasabi.Fluent/Models/Wallets/CoinModel.cs, WalletWasabi.Fluent/ViewModels/Dialogs/LabelEntryDialogViewModel.cs, WalletWasabi.Fluent/ViewModels/Wallets/Advanced/WalletCoins/WalletCoinsViewModel.cs, WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/PrivacyControlTileViewModel.cs, WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/PrivacyRing/PrivacyBarViewModel.cs, WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/PrivacyRing/PrivacyRingViewModel.cs
https://github.com/zkSNACKs/WalletWasabi/pull/12573
=> [Release] Fix coin model leak

WalletWasabi.Fluent/CrashReport/CrashReporter.cs, WalletWasabi/Microservices/ProcessStartInfoFactory.cs, WalletWasabi/Stores/IndexStore.cs
Fixes #12581 
Sorry, I didn't catch that there were other cases while making the fix.
EDIT: 
> It was a breaking change in .NET8 that caused the issue. So there is no "when it will work again".
=> Fix for Restart not working

WalletWasabi.Fluent/Helpers/TransactionFeeHelper.cs, WalletWasabi.Fluent/ViewModels/Wallets/Send/FeeChartViewModel.cs, WalletWasabi.Fluent/ViewModels/Wallets/Send/SendFeeViewModel.cs
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/11122
=> [UI] FeeChart - Integrate WildEstimations

WalletWasabi.Fluent/Controls/TextBox.axaml
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/12587
=> [VDG] Fix TextBox cursor

WalletWasabi.Tests/UnitTests/Hwi/HwiBinaryHashesTests.cs, WalletWasabi/Helpers/Constants.cs
Fixes: #12285 
Changelog:
- Support for Trezor Safe 3
- Improved error handling for invalid descriptors and Ledger device errors
Tested with RC4
=> Hwi update to 2.4.0

WalletWasabi.Tests/UnitTests/Tor/Socks5/Pool/TorHttpPoolTests.cs
=> Change RedirectSupportAsync for CodeMaid

WalletWasabi/Services/UpdateManager.cs
https://github.com/zkSNACKs/WalletWasabi/issues/12633#issuecomment-1983414318
=> Use Warning in case of wrong json in UpdateManager

WalletWasabi.Fluent/ViewModels/AddWallet/WalletNamePageViewModel.cs
fixes https://github.com/zkSNACKs/WalletWasabi/issues/12171
credits to @adamPetho for the debugging and @soosr for the fix
=> [UI] fix `Add Wallet`: sometimes wallet name page is displayed at first wallet creation

WalletWasabi.Fluent/App.axaml, WalletWasabi.Fluent/Controls/TagsBox.axaml, WalletWasabi.Fluent/Controls/TagsBoxAutoCompleteBox.axaml, WalletWasabi.Fluent/Styles/TagsBox.axaml, WalletWasabi.Fluent/Styles/Themes/Fluent.axaml, WalletWasabi.Tests/UnitTests/Fluent/App.axaml
Related: https://github.com/zkSNACKs/WalletWasabi/issues/12673
=> [UI] Migrate TagsBox to ControlTheme

WalletWasabi.Fluent/Controls/PreviewMessageItem.axaml, WalletWasabi.Fluent/Controls/PreviewMessageItem.axaml.cs, WalletWasabi.Fluent/Styles/Styles.axaml, WalletWasabi.Fluent/Styles/Themes/Fluent.axaml
Related [#12673](https://github.com/zkSNACKs/WalletWasabi/issues/12673)
=> [UI] Migrate PreviewMessageItem to ControlTheme

CONTRIBUTING.md
A question arose on the code team meeting, this change aims to answer and clarify the way. 
Many parts copy pasted from https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md
=> Add commit, merge related conventions

Contrib/Containers/docker-compose.yml, WalletWasabi.Daemon/Global.cs, WalletWasabi/BitcoinCore/Configuration/CoreConfig.cs, WalletWasabi/BitcoinCore/CoreNode.cs, WalletWasabi/BitcoinCore/CoreNodeParams.cs
This PR changes the `mempoolreplacement` policy for local nodes. 
Completely untested.
Note: I think it is a bad idea to manipulate users node configuration.
=> Change mempool policy on local node

WalletWasabi.Fluent.Desktop/Program.cs
=> Fix NRE SingleInstanceChecker

WalletWasabi/WabiSabi/Client/Banning/CoinPrison.cs
Requested here https://github.com/zkSNACKs/WalletWasabi/issues/11910#issuecomment-2042500010 and during meetings
=> Change MaxDaysToTrustLocalPrison to 15 days and remove randomness

WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModel.cs
=> [UI] Set CoinJoinSettingsCommand

WalletWasabi.Fluent/Helpers/MacOsStartupHelper.cs, WalletWasabi.Fluent/Helpers/StartupHelper.cs, WalletWasabi.Fluent/UiConfig.cs, WalletWasabi.Packager/Program.cs, WalletWasabi.Tests/UnitTests/StartWasabiOnSystemStartupTests.cs, WalletWasabi/Helpers/Constants.cs
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/10317
Contains commits of #10190 squashed.
<details>
<summary>Commits squashed</summary>
commit e95d4df1fb85b50b8a321ae63d6b41ddde113e2e
Merge: a2158a2403 13aaf6552e
Author: Balázs Faragó <54551879+Szpoti@users.noreply.github.com>
Date:   Sat Apr 6 08:55:48 2024 +0200
Merge branch 'walletStartHiddenOnMac' of github.com:Szpoti/WalletWasabi into walletStartHiddenOnMac
commit a2158a240352473df68dfde51e856e4a8fcf3184
Author: Turbolay <clement.ogame@gmail.com>
Date:   Thu Apr 4 10:26:47 2024 -0600
Improve readability and make it work when built from source
commit 13aaf6552e14f74d9392c5c32b9ebf35dc36458b
Author: Turbolay <clement.ogame@gmail.com>
Date:   Thu Apr 4 10:38:13 2024 -0600
Fix test
commit ab33cad37ca41accc065ba3cc86d2cf746696f6b …
=> OSX: Start Wasabi in the background during startup

WalletWasabi.Tests/AcceptanceTests/HwiKatas.cs
Reverts zkSNACKs/WalletWasabi#12713
=> Revert "[Trivial] Use ValidatePathString for other HW models"

WalletWasabi.Tests/UnitTests/ViewModels/SuggestionLabelsViewModelTests.cs
It wasn't a bug, but a design problem I mentioned [here](https://github.com/zkSNACKs/WalletWasabi/discussions/12666).
Anyways, this fixes CI ;)
=> Fix CI due to broken tests

WalletWasabi.Fluent/Behaviors/FocusControlActionCustom.cs, WalletWasabi.Fluent/Views/Login/LoginView.axaml
=> [UI] Login: Fix focus after Incorrect Password message

WalletWasabi.Fluent/ViewModels/Dialogs/LabelEntryDialogViewModel.cs, WalletWasabi.Fluent/ViewModels/Wallets/Receive/AddressLabelEditViewModel.cs, WalletWasabi.Fluent/ViewModels/Wallets/Send/SendViewModel.cs
- Fixes #12799 
- Also adds logic to Activate `SuggestionLabelsViewModel` in:
- `LabelEntryDialogViewModel`
- `AddressLabelEditViewModel`
=> [UI] Send: Activate SuggestionLabelsViewModel

WalletWasabi/WabiSabi/Client/Banning/CoinPrison.cs
Revert #12782
We discovered that we have Prison problems.
Feels much more safe to revert this change for the release.
=> Revert 12782

WalletWasabi.Fluent/ApplicationStateManager.cs
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/12774
=> [UI] Always call ApplyUiConfigWindowState() before showing the window

WalletWasabi.Fluent/Controls/TagControl.axaml
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/12809
=> [UI] Label - adjust margins to prevent shifting

WalletWasabi.Fluent/ApplicationStateManager.cs
Fixes: https://github.com/zkSNACKs/WalletWasabi/issues/12815
Maybe https://github.com/zkSNACKs/WalletWasabi/issues/12817
=> [UI] [macOS] Do not call Hide when the MainWindow from lifetime is not present

WalletWasabi.Fluent/ApplicationStateManager.cs
https://github.com/zkSNACKs/WalletWasabi/pull/12819
=> [Release] Fix hide on Mac

WalletWasabi.Tests/UnitTests/Hwi/HwiBinaryHashesTests.cs, WalletWasabi/Helpers/Constants.cs
fixes : #12757 
Tested with master
=> Update HWI to 3.0.0

WalletWasabi.Tests/UnitTests/Hwi/HwiBinaryHashesTests.cs, WalletWasabi/Helpers/Constants.cs
=> [Release] Update HWI to 3.0.0

WalletWasabi/BuyAnything/BuyAnythingManager.cs, WalletWasabi/BuyAnything/ConversationTracking.cs, WalletWasabi/WebClients/BuyAnything/BuyAnythingClient.cs
Small BAB clean up.
Replacement of https://github.com/zkSNACKs/WalletWasabi/pull/12741
Please test it, this can easily break.
=> [Trivial] Small BAB cleanup

WalletWasabi.Fluent/Models/Wallets/TransactionTreeBuilder.cs
https://github.com/zkSNACKs/WalletWasabi/pull/12842
=> [Release] fix child date format

WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItems/SpeedUpHistoryItemViewModel.cs, WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryViewModel.cs
=> [Release] Fix SpeedUpGroup children transactions details

WalletWasabi.Fluent/Helpers/CoinPocketHelper.cs, WalletWasabi.Tests/UnitTests/Transactions/TransactionProcessorTests.cs
#12853
If I did it incorrectly can someone else please do it? Thanks
=> [Release] Use helper privacy functions in `GetPockets`

WalletWasabi/BitcoinCore/Rpc/RpcClientBase.cs
This PR add RPC response times. The approach is very intrusive but it is also the simplest one.
=> Add response times

WalletWasabi/Helpers/Constants.cs
Equivalent of https://github.com/zkSNACKs/WalletWasabi/pull/12858
=> Bump version to 2.0.7 on master as well

WalletWasabi/Helpers/Constants.cs
Including https://github.com/zkSNACKs/WalletWasabi/pull/12874
=> Bump v2.0.7.1

WalletWasabi/Helpers/Constants.cs
https://github.com/zkSNACKs/WalletWasabi/pull/12869
=> Bump version to v2.0.7.1

WalletWasabi/Microservices/MicroserviceHelpers.cs, WalletWasabi/Tor/TorProcessManager.cs
Extracted from #12749 to decrease its diff.
=> [trivial] `MicroserviceHelpers`: extract `GetFilenameWithExtension`

WalletWasabi/Crypto/Extensions.cs, WalletWasabi/Extensions/LinqExtensions.cs, WalletWasabi/WabiSabi/Backend/Statistics/RequestTimeStatista.cs
Close https://github.com/zkSNACKs/WalletWasabi/issues/12883
=> Add `stddev` to statista

flake.lock, flake.nix
Updates the `dotnet trace` and `dotnet dump` tools in order to diagnose the application.
=> Update tooling versions

flake.nix
=> Add `dotnet counters` to the available tool box

WalletWasabi.Fluent/Views/AddWallet/WelcomePageView.axaml
=> Removed rule1 from initialization screen

WalletWasabi/WabiSabi/Backend/Statistics/RequestTimeStatista.cs
Removes the exhausting list of data elements, instead aggregates internally during the Add method.
Hopefully fixes https://github.com/zkSNACKs/MaintenanceVault/issues/366
=> Statista performance update

WalletWasabi.Backend/Startup.cs
=> `SatoshiWebSocketHandler` is a required service

WalletWasabi.Fluent/CrashReport/Views/CrashReportWindow.axaml
Fixes #10172
Program arguments for testing:
```
crashreport -attempt="1" -exception="eyJFeGNlcHRpb25UeXBlIjoiU3lzdGVtLkV4Y2VwdGlvbiIsIk1lc3NhZ2UiOiJNeSBkdW1teSBleGNlcHRpb25NeSBkdW1teSBleGNlcHRpb25NeSBkdW1teSBleGNlcHRpb25NeSBkdW1teSBleGNlcHRpb25NeSBkdW1teSBleGNlcHRpb25NeSBkdW1teSBleGNlcHRpb25NeSBkdW1teSBleGNlcHRpb25NeSBkdW1teSBleGNlcHRpb25NeSBkdW1teSBleGNlcHRpb25NeSBkdW1teSBleGNlcHRpb25NeSBkdW1teSBleGNlcHRpb25NeSBkdW1teSBleGNlcHRpb25NeSBkdW1teSBleGNlcHRpb25NeSBkdW1teSBleGNlcHRpb25NeSBkdW1teSBleGNlcHRpb25NeSBkdW1teSBleGNlcHRpb25NeSBkdW1teSBleGNlcHRpb25NeSBkdW1teSBleGNlcHRpb25NeSBkdW1teSBleGNlcHRpb25NeSBkdW1teSBleGNlcHRpb25NeSBkdW1teSBleGNlcHRpb25NeSBkdW1teSBleGNlcHRpb25NeSBkdW1teSBleGNlcHRpb25NeSBkdW1teSBleGNlcHRpb25NeSBkdW1teSBleGNlcHRpb25NeSBkdW1teSBleGNlcHRpb25NeSBkdW1teSBleGNlcHRpb25NeSB …
```
=> [UI] CrashReporter - remove logo from bg 

WalletWasabi.Fluent/ViewModels/Login/PasswordFinder/SearchPasswordViewModel.cs
Fixes: https://github.com/zkSNACKs/WalletWasabi/issues/12963
Fixes #12933
=> Fix Password Finder's CTS dispose

WalletWasabi.Fluent/Controls/DualCurrencyEntryBox.axaml.cs, WalletWasabi.Fluent/Views/Wallets/Send/SendView.axaml
Closes https://github.com/zkSNACKs/WalletWasabi/issues/12932
Explanation: https://github.com/zkSNACKs/WalletWasabi/issues/12932#issuecomment-2097815998
=> [UI] Send - keep focus when clicking on amount hyperlink

WalletWasabi.Fluent/Controls/TagsBox.axaml
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/12960
=> [UI] TagsBox - fix style

WalletWasabi.Fluent/ViewModels/Wallets/Send/FeeChartViewModel.cs
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/12492
=> [UI] Fee Slider - fix Y axis labels

WalletWasabi.Documentation/ClientRelease/ClientDeployment.md
We did a release with Roland and clarified the steps + verified IRL.
=> Final Update of ClientDeployment

WalletWasabi.Fluent/ViewModels/AddWallet/WelcomePageViewModel.cs, WalletWasabi.Fluent/Views/AddWallet/WelcomePageView.axaml, WalletWasabi.Fluent/Views/CoinJoinProfiles/CoinJoinProfilesView.axaml
It depends on the coordinator's configuration.
=> [FOSS] Remove CJ fee related contents

WalletWasabi.Fluent/Models/Wallets/WalletCoinjoinModel.cs, WalletWasabi.Fluent/ViewModels/Wallets/Settings/WalletCoinJoinSettingsViewModel.cs, WalletWasabi.Fluent/Views/Wallets/Settings/WalletCoinJoinSettingsView.axaml
fix typo thing and change  the output wallet selection to real coin join start not the input registered
=> fix coin join real start

WalletWasabi/Helpers/Constants.cs, WalletWasabi/Legal/Assets/LegalDocumentsWw2.txt
to let users know that on June 1, 2024, zkSNACKs is going to stop the coinjoin service
=> Update Terms and Conditions

WalletWasabi.Tests/UnitTests/Bases/ConfigManagerTests.cs, WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepOutputRegistrationTests.cs, WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterInputSuccessTests.cs, WalletWasabi.Tests/UnitTests/WabiSabi/Client/ArenaClientTests.cs, WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiHttpApiIntegrationTests.cs, WalletWasabi.Tests/UnitTests/WabiSabi/Models/MultipartyTransactionTests.cs, WalletWasabi.Tests/UnitTests/WabiSabi/Models/SerializationTests.cs, WalletWasabi/Crypto/StrobeProtocol/StrobeHasherExtensions.cs, WalletWasabi/JsonConverters/DefaultValueCoordinationFeeRateAttribute.cs, WalletWasabi/WabiSabi/Backend/Models/Alice.cs, WalletWasabi/WabiSabi/Backend/Rounds/Arena.Partial.cs, WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs, WalletWasabi/WabiSabi/Backend/WabiSabiConfig.cs, WalletWasabi/WabiSabi/Client/CoinJoin/Client/AliceClient.cs, WalletWasabi/WabiSabi/Client/CoinJoin/Client/ArenaClient.cs, WalletWasabi/WabiSabi/Client/CoinJoin/Client/CoinJoinClient.cs, WalletWasabi/WabiSabi/Models/CoordinationFeeRate.cs, WalletWasabi/WabiSabi/Models/InputRegistrationResponse.cs
Wasabi coordinator doesn't charge any coordination fee by default. `Plebs don't pay threshold` is removed because it makes zero sense.
=> Make Wasabi FREE by default

WalletWasabi.Backend/Controllers/WabiSabiController.cs, WalletWasabi/WabiSabi/Models/HumanMonitorResponse.cs, WalletWasabi/WabiSabi/Models/HumanMonitorRoundResponse.cs
This info will be provided by the Satoshi Notifications system
=> Remove Human Monitor API

WalletWasabi.Backend/Controllers/BatchController.cs, WalletWasabi.Fluent.Desktop/Extensions/AppBuilderExtension.cs, WalletWasabi.Fluent.Generators/AnalyzerExtensions.cs, WalletWasabi.Tests/Helpers/BitcoinFactory.cs, WalletWasabi/Crypto/OwnershipIdentifier.cs, WalletWasabi/Tor/Http/Models/HeaderSection.cs
Simplified expressions/conditions
=> Removing "can be simplified" warnings

WalletWasabi/Helpers/Constants.cs
https://github.com/zkSNACKs/WalletWasabi/pull/12999
=> Bump client version to 2.0.7.2

WalletWasabi.Daemon/WasabiAppBuilder.cs, WalletWasabi.Fluent/ApplicationStateManager.cs, WalletWasabi.Fluent/Behaviors/HorizontalScrollViewerBehavior.cs, WalletWasabi.Fluent/Controls/LineChart.cs, WalletWasabi.Fluent/Helpers/EnumerableExtensions.cs, WalletWasabi.Fluent/MathNet/CubicSpline.cs, WalletWasabi.Fluent/ViewModels/Wallets/Buy/OrderViewModel.cs, WalletWasabi/Services/UpdateManager.cs, WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs, WalletWasabi/WabiSabi/Models/MultipartyTransaction/MultipartyTransactionState.cs, WalletWasabi/WabiSabi/Models/MultipartyTransaction/SigningState.cs
CodeFactor cleanup from the Maintainability page
Implied arithmetic operator precedence resolved only at the two most affected files
=> CodeFactor cleanup

WalletWasabi/WabiSabi/Client/CoinJoin/Client/CoinJoinClient.cs, WalletWasabi/WabiSabi/Client/CoinJoin/Client/DependencyGraphTaskScheduler.cs, WalletWasabi/WabiSabi/Client/CoinJoin/Manager/CoinJoinManager.cs, WalletWasabi/WabiSabi/Client/IDestinationProvider.cs, WalletWasabi/WabiSabi/Client/IKeyChain.cs, WalletWasabi/WabiSabi/Client/InternalDestinationProvider.cs, WalletWasabi/WabiSabi/Client/KeyChain.cs
Fixes at least one small part of #12856
=> Pass KeyChain of the output wallet to DependencyGraphTaskScheduler

WalletWasabi.Backend/Controllers/BatchController.cs, WalletWasabi.Backend/Controllers/WalletController.cs, WalletWasabi/WebClients/Wasabi/WasabiClient.cs
There are two independent APIs:
* `WabiSabi` for coinjoining and,
* `Wallet` required for providing services to the wallet client to operate.
=> Organize the API

WalletWasabi.Backend/Controllers/BatchController.cs, WalletWasabi.Backend/Controllers/BlockchainController.cs, WalletWasabi/WebClients/Wasabi/WasabiClient.cs
Reverts zkSNACKs/WalletWasabi#13040
=> Revert "Organize the API"

WalletWasabi.Tests/UnitTests/Wallet/FilterProcessor/BlockDownloadServiceTests.cs
=> Mark BDS Tests as a collection + pass CT to Delay

WalletWasabi.Fluent/Views/Settings/BitcoinTabSettingsView.axaml, WalletWasabi.Fluent/Views/Wallets/Settings/WalletCoinJoinSettingsView.axaml
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/13020
=> [UI] CurrencyEntryBox - add missing style class

WalletWasabi.Fluent/Helpers/NotificationHelpers.cs
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/12969
=> [UI] Notification - adjust text when CPFP

WalletWasabi.Daemon/Config.cs, WalletWasabi.Daemon/PersistentConfig.cs, WalletWasabi.Fluent/Models/UI/ApplicationSettings.cs
This PR addresses https://github.com/zkSNACKs/WalletWasabi/pull/12991#discussion_r1609662023.
Context:
* https://github.com/zkSNACKs/WalletWasabi/pull/12991#discussion_r1609371057
* https://github.com/zkSNACKs/WalletWasabi/pull/12991#discussion_r1610070901
=> [Tor] Fix changing Tor modes in the UI settings

WalletWasabi.Backend/Controllers/BlockchainController.cs
=> Fix infinite await in `FetchTransactionsAsync` in case of missing txs (take 2)

WalletWasabi.Fluent/Models/UI/ApplicationSettings.cs, WalletWasabi.Fluent/ViewModels/Settings/BitcoinTabSettingsViewModel.cs
This PR fixes the P2P Bitcoin endpoint string value to make it change based on the selected network. Also fixes the saving logic.
=> [Config] Fix behavior

WalletWasabi/Wallets/WalletFilterProcessor.cs
Fixes #13099
Note that it's not a complete fix, the underlying problem will still exist, but it's a complex problem linked to skip synchronization. I will open an issue soon with more explanation
Thanks a lot to @yahiheb
=> Fix crash in WFP on weird interaction

WalletWasabi.Fluent/ViewModels/HelpAndSupport/AboutViewModel.cs
just a simple fix to have the visible links in the GUI updated
there are many other such links in the codebase
did these as a "quick fix", as they are the only ones visible to the user
=> [ui] update visible links in About

WalletWasabi.Fluent/ViewModels/AddWallet/WelcomePageViewModel.cs, WalletWasabi.Fluent/Views/AddWallet/WelcomePageView.axaml, WalletWasabi.Fluent/Views/CoinJoinProfiles/CoinJoinProfilesView.axaml
https://github.com/WalletWasabi/WalletWasabi/pull/13112#issuecomment-2141327249
=> Remove CJ fee related contents

WalletWasabi.Fluent/Controls/CurrencyEntryBox.axaml.cs
Fixes https://github.com/WalletWasabi/WalletWasabi/issues/13148
=> Fix double paste issue in the CurrencyEntryBox

WalletWasabi.Tests/UnitTests/ViewModels/UiContext/NullApplicationSettings.cs
#13153  broke a test but for some reasons I wasn't able to push on @soosr's branch so I preferred do this rather than spend time figuring out why
=> Fixed tests broken in #13153

WalletWasabi/WabiSabi/Client/CoinJoin/Client/CoinJoinClient.cs
I don't see how it can cause harm, this was requested by @lontivero 
I used 10% as a tolerance but it feels too much. 5%? I don't know
=> Assert that effective fee rate is at least what was agreed on

WalletWasabi.Fluent/Behaviors/CheckMarkVisibilityBehavior.cs, WalletWasabi.Fluent/Controls/TextBox.axaml, WalletWasabi.Fluent/Styles/Checkmark.axaml, WalletWasabi.Fluent/Styles/TextBox.axaml
Before:
After:
Fixes [#12891](https://github.com/WalletWasabi/WalletWasabi/issues/12891)
=> [UI] Moved validation checkmark inside PasswordBox

WalletWasabi.Fluent/Extensions/ObservableExtensions.cs, WalletWasabi.Fluent/Models/Wallets/CoinListModel.cs, WalletWasabi.Fluent/Models/Wallets/WalletRepository.cs, WalletWasabi.Fluent/Models/Wallets/WalletTransactionsModel.cs
Closes https://github.com/WalletWasabi/WalletWasabi/issues/13197
=> Partially revert https://github.com/WalletWasabi/WalletWasabi/pull/13175

WalletWasabi.Fluent/Controls/Button.axaml, WalletWasabi.Fluent/ViewModels/Wallets/Send/ManualControlDialogViewModel.cs
Fixes https://github.com/WalletWasabi/WalletWasabi/issues/13198
=> [UI] Manual Control - minor adjustments

WalletWasabi.Fluent/Models/Transactions/PrivacySuggestionsModel.cs
=> [UI] Do not trim zeros for suggested btc amounts to avoid change

WalletWasabi.Tests/Helpers/WabiSabiFactory.cs, WalletWasabi.Tests/XunitConfiguration/RegTestFixture.cs
Tests are terrible right now because:
- Those tests fail locally since we changed the repo
- I thought they were also failing on the CI all the time
I think that this change will fix the issue that I just introduced
=> Fix coinjoin tests 

WalletWasabi.Fluent/Models/Wallets/CoinListModel.cs, WalletWasabi.Fluent/Models/Wallets/CoinModel.cs, WalletWasabi.Fluent/Models/Wallets/WalletCoinsModel.cs
Fixes https://github.com/WalletWasabi/WalletWasabi/issues/12985
=> [UI] fix CoinModel design issue

WalletWasabi.Backend/Controllers/BatchController.cs, WalletWasabi.Backend/Controllers/BlockchainController.cs, WalletWasabi.Backend/Controllers/WabiSabiController.cs, WalletWasabi.Backend/Startup.cs
Implement request timeout for WabiSabi API using standard .NET capabilities.
=> Gobal request timeout for WabiSabi

WalletWasabi/Helpers/Constants.cs
Reverts WalletWasabi/WalletWasabi#13245
=> Revert "bump version to 2.9.0.0"

WalletWasabi.Fluent/ViewModels/Settings/CoordinatorTabSettingsViewModel.cs
follow up to https://github.com/WalletWasabi/WalletWasabi/pull/13239/
also removes % from the fee rate
=> settings: fix values in coordinator tab

WalletWasabi/Services/UpdateManager.cs
=> Fix `UpdateManager` version number

WalletWasabi.Tests/UnitTests/WabiSabi/Client/AmountDecomposerTests.cs
Unit tests for Decomposer.Decompose.
Fails on the current master, see: https://github.com/WalletWasabi/WalletWasabi/pull/13260
=> Decompose tests

WalletWasabi.Backend/Global.cs, WalletWasabi.Daemon/Global.cs, WalletWasabi.Tests/Helpers/ArenaBuilder.cs, WalletWasabi.Tests/RegressionTests/BackendTests.cs, WalletWasabi.Tests/UnitTests/BitcoinCore/IndexBuilderServiceTests.cs, WalletWasabi.Tests/UnitTests/BitcoinCore/MempoolMirrorTests.cs, WalletWasabi.Tests/UnitTests/BitcoinCore/P2pBasedTests.cs, WalletWasabi.Tests/UnitTests/BlockNotifierTests.cs, WalletWasabi.Tests/UnitTests/WabiSabi/Backend/UtxoPrisonWardenTests.cs, WalletWasabi.Tests/UnitTests/WabiSabi/Client/ArenaClientTests.cs, WalletWasabi.Tests/UnitTests/WabiSabi/Client/BobClientTests.cs, WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiApiApplicationFactory.cs, WalletWasabi/BitcoinCore/CoreNode.cs, WalletWasabi/BitcoinCore/Mempool/MempoolMirror.cs, WalletWasabi/BitcoinCore/P2pNode.cs, WalletWasabi/Blockchain/BlockFilters/IndexBuilderService.cs, WalletWasabi/Blockchain/Blocks/BlockNotifier.cs, WalletWasabi/WabiSabi/Backend/DoSPrevention/Warden.cs, WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs, WalletWasabi/WabiSabi/CoordinatorParameters.cs, WalletWasabi/WabiSabi/WabiSabiCoordinator.cs
This is required to wire the services using a DI container.
=> Simplify background service construction

WalletWasabi.Fluent/Views/Wallets/Advanced/WalletCoinsView.axaml
remove send mention, sending from this dialog was removed with the introduction of the manual control
=> fix wallet coins dialog caption

WalletWasabi.Fluent/Extensions/ObservableExtensions.cs, WalletWasabi.Fluent/Models/Wallets/CoinListModel.cs, WalletWasabi.Fluent/Models/Wallets/UserSelectionCoinListModel.cs, WalletWasabi.Fluent/Models/Wallets/WalletCoinsModel.cs, WalletWasabi.Fluent/ViewModels/CoinControl/SelectCoinsDialogViewModel.cs, WalletWasabi.Fluent/ViewModels/Wallets/Advanced/WalletCoinsViewModel.cs, WalletWasabi.Fluent/ViewModels/Wallets/Coins/CoinListViewModel.cs, WalletWasabi.Fluent/ViewModels/Wallets/Coins/PocketViewModel.cs, WalletWasabi.Fluent/ViewModels/Wallets/Send/ManualControlDialogViewModel.cs, WalletWasabi.Fluent/ViewModels/Wallets/Settings/ExcludedCoinsViewModel.cs
From https://github.com/GingerPrivacy/GingerWallet/pull/70
=> Improve fix to CoinList crash

WalletWasabi.Fluent.Desktop/Program.cs
=> Fix crash when using --version on GUI

WalletWasabi.Daemon/Global.cs, WalletWasabi/WabiSabi/Client/Banning/CoinPrison.cs, WalletWasabi/WabiSabi/Client/CoinJoin/Manager/CoinJoinManager.cs
This PR has two parts:
* Refactoring: to simplify the code and the logic.
* Isolate prisons for different coordinators.
Closes #https://github.com/WalletWasabi/WalletWasabi/issues/13308
=> Local prison per coordinator

WalletWasabi.Fluent/Extensions/DateTimeExtensions.cs
Follow up to #13237 to make the datetime more comprehensive.
Master:
`Today at 08:31`
PR:
`Today at 20:31`
=> [UI] Display the hour using a 24-hour clock from 00 to 23

WalletWasabi/WabiSabi/Client/CoinJoin/Client/Decomposer/DenominationBuilder.cs
Make clear that the denominations are: $`2^n | 3^n | 2*3^n | 10^n | 2*10^n | 5*10^n`$
=> Simplify denominations building

WalletWasabi.Fluent/Models/Wallets/WalletStatsModel.cs, WalletWasabi.Fluent/Views/Wallets/Advanced/WalletStatsView.axaml
=> Do not display 'locked addresses' in wallet stats

WalletWasabi.Fluent/Controls/SubActionButton.axaml
With this PR the SubActions also have a handcursor, where previously only the main button had a handcursor.
Giving the SubActionButtons also a handcursor looks better.
=> add handcursor to SubActionButton

WalletWasabi/WabiSabi/Client/CoinJoin/Manager/CoinJoinManager.cs
This PR fixes an issue introduced by me in #13353
=> Fix assignment order

WalletWasabi.Fluent/Models/UI/ApplicationSettings.cs
=> Fix BackendURI setting save

WalletWasabi.Fluent/UiConfig.cs
It is time, this default was already weird before but now it's just bad
=> Don't run in the background by default

WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiHttpApiIntegrationTests.cs
The test use to fail because there is only one client and then it is somehow difficult to bread the amount in a way that there is at least one denomination that repeats.
=> Silince test in rare case

WalletWasabi/BitcoinP2p/P2pBehavior.cs, WalletWasabi/BitcoinP2p/TrustedP2pBehavior.cs, WalletWasabi/BitcoinP2p/UntrustedP2pBehavior.cs, WalletWasabi/Blockchain/Mempool/MempoolService.cs, WalletWasabi/Blockchain/TransactionBroadcasting/TransactionBroadcaster.cs, WalletWasabi/Blockchain/TransactionProcessing/TransactionProcessor.cs, WalletWasabi/Blockchain/Transactions/TransactionBroadcastEntry.cs
Requires at least two nodes to accept the transactions and two nodes to echo the tx.
=> More resilient broadcasting mechanism

WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionSummaryViewModel.cs, WalletWasabi.Fluent/Views/Wallets/Send/TransactionSummary.axaml
=> [UI] Show fee rate at preview transaction when sending

WalletWasabi.Fluent/Views/Wallets/MusicControlsView.axaml
fixes https://github.com/WalletWasabi/WalletWasabi/issues/13361
=> fix duplicate musicbox menuitem

Contrib/Migration/migrateBackendFilters.fsx
=> Fix from string by using correct endians

WalletWasabi/Stores/BlockFilterSqliteStorage.cs, WalletWasabi/Stores/IndexStore.cs
=> Smart resync when index has inverted endians

WalletWasabi.Fluent/ViewModels/Wallets/Home/History/Details/TransactionDetailsViewModel.cs
fixes https://github.com/WalletWasabi/WalletWasabi/issues/13427
=> [BugFix] Transaction Details Fee rate displayed while null 

WalletWasabi.Daemon/Rpc/WasabiJsonRpcService.cs, WalletWasabi.Fluent/Models/Transactions/PrivacySuggestionsModel.cs, WalletWasabi.Fluent/ViewModels/Wallets/Send/PrivacyControlViewModel.cs, WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionPreviewViewModel.cs
The send workflow was disrupted when there was not a coinjoin manager configured.
Close #13426
=> [BugFix] Send workflow disruption

WalletWasabi.Fluent/Helpers/ApplicationHelper.cs
Closes https://github.com/WalletWasabi/WalletWasabi/issues/13446
=> [BugFix] Incorrect clipboard content casting

WalletWasabi.Documentation/WasabiCompatibility.md, WalletWasabi.Tests/AcceptanceTests/HwiKatas.cs, WalletWasabi.Tests/UnitTests/Hwi/HwiProcessBridgeMock.cs, WalletWasabi.Tests/UnitTests/Hwi/MockedDeviceTests.cs, WalletWasabi/Hwi/Models/HardwareWalletModels.cs, WalletWasabi/Hwi/Models/HwiEnumerateEntry.cs
Update HWI to 3.1.0.
Currently untested
=> [Feature] Trezor Safe 5 & Coldcard Q support

WalletWasabi/WabiSabi/Client/Batching/PaymentAwareOutputProvider.cs, WalletWasabi/WabiSabi/Client/CoinJoin/Manager/CoinJoinTracker.cs
This PR includes the final change for allowing payments in coinjoins, fixing the bug that prevented the official release of this feature
=> [Feature] Functional Payment in Coinjoin 

.github/workflows/onReleasePublished.yml
Follow up to the doc one, it's working in exactly the same way, except that the token must be a different one
=> Auto update version number on Website

WalletWasabi.Tests/UnitTests/BitcoinCore/IndexBuilderServiceTests.cs, WalletWasabi.Tests/UnitTests/BitcoinCore/RpcBasedTests.cs, WalletWasabi/BitcoinCore/Rpc/Models/VerboseInputInfo.cs, WalletWasabi/BitcoinCore/Rpc/Models/VerboseTransactionInfo.cs, WalletWasabi/BitcoinCore/Rpc/RpcParser.cs, WalletWasabi/Blockchain/BlockFilters/IndexBuilderService.cs
Handle the scenario where while building the filters, the txs' prevout are pruned.
=> Improve code logic and add log for index service

WalletWasabi/WebClients/Wasabi/WasabiHttpClientFactory.cs
A connection can take several seconds and in case it fails then there is a waiting time before retrying (using the same circuit).
=> Increase bob's disposal from 10 to 40 seconds

WalletWasabi.Fluent/Views/Wallets/Advanced/WalletStatsView.axaml, WalletWasabi.Fluent/Views/Wallets/Home/Tiles/PrivacyControlTileView.axaml
=> [Trivial] Fix some copyable content

WalletWasabi.Fluent/Helpers/PrivacyModeHelper.cs
closes https://github.com/WalletWasabi/WalletWasabi/issues/13490
=> decrease RevealDelay for PrivacyChars on hover

Contrib/ReleaseHighlight.md
Full changelog (excluding Trivial, maybe I will add a category "Miscellaneaous" with some of this changes):
Still missing PR that will need to be merged tomorrow
```
* Trezor Safe 5 & Coldcard Q support by @turbolay in https://github.com/WalletWasabi/WalletWasabi/pull/13438
* Modernize Tor usage technology by @lontivero in https://github.com/WalletWasabi/WalletWasabi/pull/13339
* Functional Payment in Coinjoin  by @lontivero in https://github.com/WalletWasabi/WalletWasabi/pull/13458
* Add coinjoin inputs/outputs summary by @turbolay in https://github.com/WalletWasabi/WalletWasabi/pull/13469
* New format for BTC Amounts by @turbolay in https://github.com/WalletWasabi/WalletWasabi/pull/13491
* Decrease RevealDelay for PrivacyChars on hover by @MarnixCroes in …
```
=> [Trivial] Release highlights for v2.3.0.0

WalletWasabi.Fluent/Models/Wallets/CoinListModel.cs, WalletWasabi.Fluent/Models/Wallets/CoinModel.cs, WalletWasabi.Fluent/ViewModels/Wallets/Coins/CoinListItem.cs, WalletWasabi.Fluent/ViewModels/Wallets/Coins/CoinViewModel.cs, WalletWasabi.Fluent/Views/Wallets/Coins/CoinListView.axaml
=> [Feature] Extend context menu to copy address to CoinList

WalletWasabi.Fluent/ViewModels/Wallets/Coinjoins/CoinjoinCoinListDataGridSource.cs, WalletWasabi.Fluent/ViewModels/Wallets/Coins/CoinListDataGridSource.cs, WalletWasabi.Fluent/ViewModels/Wallets/Transactions/Inputs/InputsCoinListDataGridSource.cs, WalletWasabi.Fluent/ViewModels/Wallets/Transactions/Outputs/OutputsCoinListDataGridSource.cs
=> [BugFix] Fix amount sorting regression

WalletWasabi/JsonConverters/EndPointJsonConverterNg.cs
=> [BugFix] Fix address EndPoint not working correctly after relaunch

WalletWasabi/Extensions/NBitcoinExtensions.cs
fixes https://github.com/WalletWasabi/WalletWasabi/issues/13529
=> Payment in coinjoin to P2WSH

WalletWasabi/WabiSabi/Client/Banning/CoinPrison.cs
Close: https://github.com/WalletWasabi/WalletWasabi/issues/13551
=> [Trivial] Trust the coordinator about the banning time

WalletWasabi/Blockchain/TransactionBroadcasting/TransactionBroadcaster.cs
Fixes #13541 
This bug is major
=> [BugFix] Fix broadcastError out of range

NOTICE.md, WalletWasabi.Fluent/Controls/CurrencyEntryBox.axaml, WalletWasabi.Fluent/Controls/DualCurrencyEntryBox.axaml, WalletWasabi.Fluent/Controls/TextBox.axaml, WalletWasabi.Fluent/Styles/ComboBoxItem.axaml, WalletWasabi.Fluent/Styles/SettingsLayout.axaml, WalletWasabi.Fluent/Views/Settings/AdvancedSettingsTabView.axaml, WalletWasabi.Fluent/Views/Settings/BitcoinTabSettingsView.axaml, WalletWasabi.Fluent/Views/Settings/CoordinatorTabSettingsView.axaml, WalletWasabi.Fluent/Views/Settings/GeneralSettingsTabView.axaml, WalletWasabi.Fluent/Views/Wallets/Settings/WalletCoinJoinSettingsView.axaml, WalletWasabi/Models/TorMode.cs
Requires #13604 
Based on https://github.com/GingerPrivacy/GingerWallet/commit/d561723236887a92d35405d3d648bfed5a3768c6
Slightly improved
https://github.com/user-attachments/assets/b7e7a129-5301-4ffe-8546-b416e2257672
=> [Feature] Improve settings layout

WalletWasabi.Fluent/ViewModels/AddWallet/Create/RecoveryWordsViewModel.cs, WalletWasabi.Fluent/Views/AddWallet/Create/RecoveryWordsView.axaml
=> Remove 'Copy recovery words'

Contrib/ReleaseHighlight.md
This release is small, this is why I call it a "Stability release"
=> [Trivial] Highlights v2.3.1

WalletWasabi.Fluent/ViewModels/Dialogs/ManualCoinJoinSettingsViewModel.cs, WalletWasabi.Fluent/ViewModels/Dialogs/NewWalletAdvancedOptionsDialogViewModel.cs, WalletWasabi.Fluent/Views/Dialogs/AdvancedCoinjoinOptionsView.axaml, WalletWasabi.Fluent/Views/Dialogs/NewWalletAdvancedOptionsDialogView.axaml, WalletWasabi.Fluent/Views/Login/LoginView.axaml, WalletWasabi.Fluent/Views/Wallets/Settings/WalletCoinJoinSettingsView.axaml
Thanks @remcoros and @Kruwed for the report
=> [BugFix] Fix some layout regressions

WalletWasabi/Blockchain/Keys/KeyManager.cs, WalletWasabi/Blockchain/Transactions/TransactionFactory.cs, WalletWasabi/Extensions/NBitcoinExtensions.cs, WalletWasabi/WabiSabi/Client/KeyChain.cs
This is the first of a many small PR needed to implement Silent Payments.
=> Use `Key` instead of `ExtKey`

WalletWasabi/Wallets/Wallet.cs
Closes https://github.com/WalletWasabi/WalletWasabi/issues/13584
=> Fix Wallet has no key chain

WalletWasabi/Extensions/NBitcoinExtensions.cs
Closes https://github.com/WalletWasabi/WalletWasabi/issues/13529
=> Add P2SH as unknown script types

WalletWasabi/Helpers/ImportWalletHelper.cs
=> [BugFix] Fix import json from ColdCard Q

WalletWasabi.Fluent/ViewModels/HelpAndSupport/AboutViewModel.cs, WalletWasabi.Fluent/Views/HelpAndSupport/AboutView.axaml
Not sure how to have better aesthetics because it doesn't look that nice, I think it's ok
https://github.com/user-attachments/assets/87f88f55-2e7c-475c-8a82-67c7c74e2c84
=> Button to Release Highlights in AboutViewModel

WalletWasabi.Fluent/ViewModels/Wallets/CoinJoinStateViewModel.cs, WalletWasabi/Extensions/LinqExtensions.cs, WalletWasabi/WabiSabi/Client/CoinJoin/Client/CoinJoinClient.cs, WalletWasabi/WabiSabi/Client/CoinJoin/Manager/CoinJoinManager.cs, WalletWasabi/WabiSabi/Client/CoinJoin/Manager/StatusChangedEvents/StatusChangedEventArgs.cs
=> Verify that our own inputs are in the list of CJ inputs before Amount Decomposition

WalletWasabi.Fluent/Models/UI/ApplicationSettings.cs, WalletWasabi.Fluent/UiConfig.cs, WalletWasabi.Fluent/ViewModels/SearchBar/SettingsSearchSource.cs, WalletWasabi.Fluent/ViewModels/Settings/AdvancedSettingsTabViewModel.cs, WalletWasabi.Fluent/ViewModels/Settings/BitcoinTabSettingsViewModel.cs, WalletWasabi.Fluent/ViewModels/Settings/CoordinatorTabSettingsViewModel.cs, WalletWasabi.Fluent/ViewModels/Settings/GeneralSettingsTabViewModel.cs, WalletWasabi.Fluent/Views/Settings/AdvancedSettingsTabView.axaml, WalletWasabi.Fluent/Views/Settings/GeneralSettingsTabView.axaml, WalletWasabi.Tests/UnitTests/ViewModels/UiContext/NullApplicationSettings.cs
Fixes #8195
Not sure how to make it prettier
It doesnt reset CoordinatorURI.
In the future, it shouldn't reset BackendURI as well (because defaults are empty)
This PR is far from easy. It uses reflection but there are special cases.
Please test and notify me if there is a setting that is not reset or that the new value is not correctly displayed in the UI
=> Reset all settings to default button

WalletWasabi.Fluent/Models/UI/ApplicationSettings.cs, WalletWasabi.Fluent/ViewModels/Settings/BitcoinTabSettingsViewModel.cs, WalletWasabi.Fluent/Views/Settings/BitcoinTabSettingsView.axaml, WalletWasabi.Tests/UnitTests/ViewModels/UiContext/NullApplicationSettings.cs, WalletWasabi/Wallets/Exchange/ExchangeRateProvider.cs
I added that in Bitcoin Settings, felt was the best
@lontivero Please check if case change in ExchangeRateProvider.Provider is OK
=> Exchange Rate Provider UI Picker

WalletWasabi.Fluent/ViewModels/SearchBar/SettingsSearchSource.cs
=> [UI] Remove Tor setting from the searchbar

WalletWasabi.Fluent/ViewModels/Settings/SettingsPageViewModel.cs, WalletWasabi.Fluent/Views/Settings/SettingsPageView.axaml
=> Fix oversight in settings

WalletWasabi.Tests/IntegrationTests/ExternalApiTests.cs, WalletWasabi/WebClients/UserAgent.cs
Fixes: #13704
@yahiheb could you please test this?
For me, this fixed the issue.
=> Fix Blockstream.info fee fetching on Windows on Clearnet

WalletWasabi.Fluent/Converters/PreferredScriptPubKeyTypeConverter.cs, WalletWasabi.Fluent/Models/Wallets/WalletSettingsModel.cs, WalletWasabi.Fluent/Styles/SettingsLayout.axaml, WalletWasabi.Fluent/ViewModels/Wallets/Settings/WalletSettingsViewModel.cs, WalletWasabi.Fluent/Views/Wallets/Settings/WalletGeneralSettingsView.axaml, WalletWasabi/Blockchain/Keys/KeyManager.cs, WalletWasabi/JsonConverters/PreferredScriptPubKeyTypeJsonConverter.cs, WalletWasabi/Models/PreferredScriptPubKeyType.cs
Fixes #13717
Goes well into quality of life release + I made the same code a few PR ago so fast.
@lontivero please check the changes in the KM, tell me if better way.
=> Set change script type

WalletWasabi.Fluent/Models/ClientConfig/ClientConfig.cs, WalletWasabi.Fluent/Models/ClientConfig/IClientConfig.cs, WalletWasabi.Fluent/Models/Wallets/WalletRepository.cs, WalletWasabi.Tests/UnitTests/WalletDirTests.cs, WalletWasabi/Helpers/ImportWalletHelper.cs, WalletWasabi/Wallets/WalletDirectories.cs, WalletWasabi/Wallets/WalletManager.cs
As mentioned here https://github.com/orgs/WalletWasabi/discussions/13661, this is not needed.
This PR removes the wallet backup related codes from the project.
@yahiheb could you please test adding and recovering a wallet? It should work just as before.
=> [Unwanted] Remove wallet backups

WalletWasabi.Fluent/ViewModels/Wallets/LoadingViewModel.cs, WalletWasabi.Fluent/Views/Wallets/LoadingView.axaml
=> Slightly improve loading screen visual

WalletWasabi.Fluent/Controls/Button.axaml, WalletWasabi.Fluent/ViewModels/Wallets/Settings/WalletCoinJoinSettingsViewModel.cs, WalletWasabi.Fluent/Views/Wallets/Settings/WalletCoinJoinSettingsView.axaml, WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiHttpApiIntegrationTests.cs, WalletWasabi/CoinJoinProfiles/PrivacyProfiles.cs
=> Follow up Rework Cj Profile

WalletWasabi.Fluent/ViewModels/Wallets/Settings/WalletCoinJoinSettingsViewModel.cs, WalletWasabi.Fluent/Views/Wallets/Settings/WalletCoinJoinSettingsView.axaml
=> Fix validation AS error + order coinjoin settings

WalletWasabi.Fluent/Converters/StatusConverters.cs, WalletWasabi.Fluent/Models/Wallets/HealthMonitor.cs, WalletWasabi.Fluent/Views/StatusIcon/StatusIcon.axaml, WalletWasabi/Blockchain/Blocks/SmartHeaderChain.cs, WalletWasabi/FeeRateEstimation/FeeRateEstimationUpdater.cs
It was decided to keep the `Exchange Rate` as a `Tile` for now, so only this info for now.
Not yet any tooltip nor errors
=> Fee Rate & Blockchain Tip in HealthMonitor

WalletWasabi.Fluent/Views/Wallets/LoadingView.axaml, WalletWasabi.Fluent/Views/Wallets/Settings/ResyncWalletView.axaml, WalletWasabi.Fluent/Views/Wallets/Settings/WalletCoinJoinSettingsView.axaml
=> [UI] Less text

WalletWasabi.Fluent/ViewModels/HelpAndSupport/AboutViewModel.cs
=> Remove Backend Status Page

WalletWasabi/Blockchain/Keys/KeyManager.cs
=> Fix autocoinjoin reset

WalletWasabi.Fluent/ViewModels/Settings/BitcoinTabSettingsViewModel.cs
=> Update search keywords for dust attack limit

WalletWasabi.Fluent/Controls/AmountControl.axaml.cs, WalletWasabi/Blockchain/TransactionBuilding/MoneyRequest.cs, WalletWasabi/WabiSabi/Client/Batching/PaymentAwareOutputProvider.cs
This fixes warning [CS0618](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs0618)
=> Use Money.Zero instead of obsolete member

WalletWasabi.Daemon/Config/Config.cs, WalletWasabi.Daemon/Config/PersistentConfig.cs, WalletWasabi.Tests/IntegrationTests/LiveServerTests.cs, WalletWasabi.Tests/UnitTests/Transactions/TransactionProcessorTests.cs, WalletWasabi/Blockchain/Mempool/MempoolService.cs, WalletWasabi/Cache/MemoryCache.cs, WalletWasabi/Helpers/Constants.cs, WalletWasabi/Models/ServiceConfiguration.cs, WalletWasabi/Wallets/Wallet.cs, WalletWasabi/WebClients/Wasabi/WasabiClient.cs
Solves https://github.com/WalletWasabi/WalletWasabi/issues/13094 but in a backward-compatible way (without touching the backend code)
=> Removes mempool-hashes synchronization

WalletWasabi/Services/WasabiSynchronizer.cs
This PR contains a small refactoring to clean the WasabiSynchronizer.
=> Clean synchronizer

WalletWasabi.Tests/UnitTests/BitcoinCore/P2pBasedTests.cs, WalletWasabi.Tests/UnitTests/BitcoinCore/RpcBasedTests.cs, WalletWasabi.Tests/UnitTests/Cache/IdempotencyRequestCacheTests.cs, WalletWasabi.Tests/UnitTests/Transactions/TransactionFactoryTests.cs, WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepOutputRegistrationTests.cs, WalletWasabi.Tests/UnitTests/WabiSabi/Client/ArenaClientTests.cs, WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiHttpApiIntegrationTests.cs
Reduce build time in one minute. It is better than nothing.
=> Improve CI times

WalletWasabi/Blockchain/Keys/KeyManager.cs
An HD signer (`KeyManager`) consists basically of a `seed`. `Bip39` and `Slip39` are just different ways to encode/decode that seed. This PR allows to create and recover the seed from bip39 mnemonic as before while add support for doing the same with slip39 ones.
=> Create and Recover from Slip39 shares

WalletWasabi.Fluent/Views/Settings/BitcoinTabSettingsView.axaml
for people to know what is expected to be entered
=> settings: add watermark to RPCcredentialString textbox

WalletWasabi.Backend/Config/Config.cs, WalletWasabi.Backend/Config/Serializarion.cs, WalletWasabi.Backend/Startup.cs, WalletWasabi.Tests/RegressionTests/FilterDownloaderTest.cs, WalletWasabi.Tests/RegressionTests/ReorgTest.cs, WalletWasabi.Tests/UnitTests/BitcoinCore/IndexBuilderServiceTests.cs, WalletWasabi.Tests/UnitTests/Filters/IndexBuilderTests.cs, WalletWasabi.Tests/UnitTests/Wallet/MockNode.cs, WalletWasabi.Tests/XunitConfiguration/RegTestFixture.cs, WalletWasabi/Blockchain/BlockFilters/IndexBuilderService.cs, WalletWasabi/Blockchain/BlockFilters/StartingFilters.cs, WalletWasabi/Helpers/Constants.cs
This PR the Wasabi indexer to generate the legacy filters as well as the bip158 filters from the bitcoin node.
=> Index builder service bip158

WalletWasabi/Serialization/External.cs
Fixes https://github.com/WalletWasabi/WalletWasabi/issues/13777
=> Fix wrong serialization casing

WalletWasabi.Fluent/Views/Settings/ConnectionsSettingsTabView.axaml
Fixes https://github.com/WalletWasabi/WalletWasabi/issues/13825
=> Fix Indexer URI

WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryViewModel.cs
Fixes: #13812
On each `OnActivated` call it seems like we appended the `IObservableCollection<HistoryItemViewModelBase> Transactions` (source of the History table) with the Wallet's transaction list. 
There might be unintended consequences to this change. Sending and receiving looked fine, but please test it.
=> Fix duplicate history items

NOTICE.md, WalletWasabi.Fluent/Controls/ProgressRing.axaml, WalletWasabi.Fluent/Controls/ProgressRing.axaml.cs, WalletWasabi.Fluent/Controls/ProgressRingArc.axaml, WalletWasabi.Fluent/Controls/ProgressRingArc.axaml.cs
Fixes: #13806
Based on: https://github.com/GingerPrivacy/GingerWallet/pull/139/commits/eb9c022f394a15e8ad6048e0fc9b78cef9dcb1e6
=> Fix loading ring

.github/workflows/release.yml, Contrib/release.sh
**UNTESTED**
This should be really close to the code required to sign using Azure Trusted Signing
=> Sign Windows Binary using Azure Trusted Signing

.github/workflows/release.yml, Contrib/release.sh
Hopefully the last one,
Probably not
=> Fix AZ Signing

.github/workflows/release.yml, Contrib/release.sh
(hopefully, maybe PATHS are wrong tho)
=> Final Azure fixes

WalletWasabi.Fluent/Views/Wallets/Receive/Columns/LabelsColumnView.axaml
First half of: https://github.com/WalletWasabi/WalletWasabi/issues/13807
=> Fix Receive view horizontal scrollbar visibility

Directory.Packages.props, WalletWasabi.Fluent/Views/Wallets/Receive/Columns/LabelsColumnView.axaml, deps.nix
=> Downgrade Avalonia.Controls.TreeDataGrid to v11.1.0

WalletWasabi.Fluent/Views/Settings/ConnectionsSettingsTabView.axaml, WalletWasabi.Fluent/Views/StatusIcon/StatusIcon.axaml
Until #13833 is implemented, I would prefer to avoid discrepancies between config file and UI
=> TMP: Indexer -> Backend in StatusIcon

WalletWasabi/Announcements/ReleaseHighlights.cs, WalletWasabi/Announcements/ReleaseHighlights.md, WalletWasabi/Helpers/Constants.cs
I can remove `🔮 A Glimpse on Tomorrow` section if preferred
=> Release Highlights + VersionName + Bump to 2.6.0

WalletWasabi.Daemon/Global.cs, WalletWasabi.Fluent/Services.cs
The update mechanism should never connect to relays or any other third party on clearnet.
=> Do not upgrade without Tor

WalletWasabi.Daemon/Config/PersistentConfig.cs
close #13895 
close https://github.com/WalletWasabi/WalletWasabi/issues/13886
=> Check if the bitcoin.conf file exists

WalletWasabi.Daemon/Config/Config.cs, WalletWasabi.Daemon/README.md
Fix https://github.com/WalletWasabi/WalletWasabi/issues/13893
=> Fix variable environment names

Contrib/release.sh, WalletWasabi.sln
The idea is that a build should run without a privileged user.
=> Remove sudo from Release script 

WalletWasabi.Tests/RegressionTests/BackendTests.cs, WalletWasabi.Tests/RegressionTests/BuildTransactionReorgsTest.cs, WalletWasabi.Tests/RegressionTests/BuildTransactionValidationsTest.cs, WalletWasabi.Tests/RegressionTests/CancelTests.cs, WalletWasabi.Tests/RegressionTests/FilterDownloaderTest.cs, WalletWasabi.Tests/RegressionTests/MaxFeeTests.cs, WalletWasabi.Tests/RegressionTests/ReceiveSpeedupTests.cs, WalletWasabi.Tests/RegressionTests/RegTestSetup.cs, WalletWasabi.Tests/RegressionTests/ReorgTest.cs, WalletWasabi.Tests/RegressionTests/ReplaceByFeeTxTest.cs, WalletWasabi.Tests/RegressionTests/SelfSpendSpeedupTests.cs, WalletWasabi.Tests/RegressionTests/SendSpeedupTests.cs, WalletWasabi.Tests/RegressionTests/SendTests.cs, WalletWasabi.Tests/RegressionTests/SpendUnconfirmedTxTests.cs, WalletWasabi.Tests/RegressionTests/WalletTests.cs, WalletWasabi.Tests/WalletWasabi.Tests.csproj, WalletWasabi/WalletWasabi.csproj, flake.nix
Wasabi doesn't depend on any particular Bitcoin fork and it doesn't start/stop a bitcoin node anymore.
=> Remove Bitcoin Node dependency

WalletWasabi.Fluent/Controls/TagsBox.axaml.cs, WalletWasabi/Serialization/ReflectionUtils.cs
=> Fix Recovery words typing 

WalletWasabi.Daemon/WasabiApplication.cs
Close https://github.com/WalletWasabi/WalletWasabi/issues/13981
=> [Fix] First time config is created, use mainnet

WalletWasabi.Daemon/Global.cs
close https://github.com/WalletWasabi/WalletWasabi/issues/13930
=> Fix error with malformed rpc credential string

WalletWasabi.Fluent/Models/Wallets/CoinModel.cs, WalletWasabi/Blockchain/TransactionOutputs/SmartCoin.cs, WalletWasabi/WabiSabi/Client/Banning/CoinPrison.cs
Close: https://github.com/WalletWasabi/WalletWasabi/issues/14065
It need testing
=> Fix banning icon

WalletWasabi.Daemon/Global.cs, WalletWasabi.Fluent/Views/Settings/ConnectionsSettingsTabView.axaml
found in https://github.com/WalletWasabi/WalletWasabi/pull/14071
=> two small writing fixes
