WalletWasabi/WalletWasabi

- WalletWasabi.Fluent/ViewModels/AddWallet/Create/ConfirmRecoveryWordsViewModel.cs
The original message is confusing a bit, it implies that a password is needed to open a wallet which is not correct.
> [Trivial] Edit message when adding password

- WalletWasabi.Fluent/Views/Wallets/Home/Tiles/PrivacyRing/PrivacyRingView.axaml
which causes an unnecessary re-rendering of the privacy ring.
fixes #9338
> [VDG] Fix Privacy Ring References layout problem

- WalletWasabi.Fluent/Views/Wallets/Home/Tiles/PrivacyRing/PrivacyRingView.axaml
- Workaround for #9340 
- Reduces coin details preview delay, making it much harder (but not impossible if you try really hard) to reproduce the bug.
> [VDG] Reduce Privacy Ring Preview Delay

- WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModel.cs
- WalletWasabi.Fluent/Views/Wallets/WalletView.axaml
The name of the variable is misleading, which leads to confusions like: https://github.com/zkSNACKs/WalletWasabi/pull/9381#discussion_r1004692279
> [Trivial] Rename variable

- WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
During the input and conn-conf phase, UnexpectedRoundPhaseException can happen because of not enough inputs or LoadBalancing. Neither is a warning message. 
The PR will dismiss these messages from the logs
```
2022-10-25 08:14:03.239 [55] WARNING	CoinJoinClient.CreateRegisterAndConfirmCoinsAsync (396)	WalletWasabi.WabiSabi.Client.RoundStateAwaiters.UnexpectedRoundPhaseException: Round 2bb1275b9d62fbfbdea1815eb786535ef0c5186409e96c6ebb6ff7fec3e80180 unexpected phase change. Waiting for 'ConnectionConfirmation' but the round is in 'Ended' - ErrorCode:'AbortedLoadBalancing'.
at WalletWasabi.WabiSabi.Client.AliceClient.ConfirmConnectionAsync(RoundStateUpdater roundStatusUpdater, CancellationToken cancellationToken) in WalletWasabi\WabiSabi\Client\AliceClient.cs:line 165
at …
```
> UnexpectedRoundPhaseException shouldn't be a warning

- WalletWasabi.Fluent/Helpers/CoinHelpers.cs
- WalletWasabi.Fluent/Helpers/CoinPocketHelper.cs
- WalletWasabi/Blockchain/Analysis/BlockchainAnalyzer.cs
- WalletWasabi/Helpers/Constants.cs
- WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
Add a constant to avoid making mistakes.
The value of this const (2) was first introduced in #8255 to hide/forget clusters/lables when no unique outputs created in coinjoins.
> Add SemiPrivateThreshold constant

- WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryViewModel.cs
- WalletWasabi.Fluent/Views/Wallets/Home/History/HistoryTable.axaml
This PR fixes #9106 with just few changes:
- It removes the text message when a wallet is empty (has no transactions)
- It makes the dummy lines a bit more transparent.
https://github.com/zkSNACKs/WalletWasabi/pull/9348#issuecomment-1291613042
Master:
This PR:
> [Trivial][VDG] Remove empty wallet message

- WalletWasabi.Tests/UnitTests/MempoolMirrorTests/MempoolMirrorTests.cs
- WalletWasabi/BitcoinCore/Mempool/MempoolMirror.cs
@lontivero found this bug
```
Oct 19 12:54:16 WalletWasabi walletwasabi-backend[3342266]:       System.ArgumentException: An item with the same key has already been added. Key: d33ac9c36fe99540b46a02c991aaed16a06a1681b6c1518760979687>
Oct 19 12:54:16 WalletWasabi walletwasabi-backend[3342266]:          at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
Oct 19 12:54:16 WalletWasabi walletwasabi-backend[3342266]:          at WalletWasabi.BitcoinCore.Mempool.MempoolMirror.GetSpenderTransactions(IEnumerable`1 txOuts)
Oct 19 12:54:16 WalletWasabi walletwasabi-backend[3342266]:          at WalletWasabi.Backend.Controllers.BlockchainController.BroadcastAsync(String hex)
```
> Fix MempoolMirror's ArgumentException

- WalletWasabi.Backend/Controllers/BatchController.cs
- WalletWasabi.Backend/Controllers/BlockchainController.cs
- WalletWasabi.Backend/Controllers/LegacyController.cs
- WalletWasabi.Backend/Controllers/OffchainController.cs
- WalletWasabi.Backend/Controllers/WasabiController.cs
- WalletWasabi.Tests/IntegrationTests/ExternalApiTests.cs
- WalletWasabi/Interfaces/IExchangeRateProvider.cs
- WalletWasabi/WebClients/Bitstamp/BitstampExchangeRateProvider.cs
- WalletWasabi/WebClients/BlockchainInfo/BlockchainInfoExchangeRateProvider.cs
- WalletWasabi/WebClients/CoinGecko/CoinGeckoExchangeRateProvider.cs
- WalletWasabi/WebClients/Coinbase/CoinbaseExchangeRateProvider.cs
- WalletWasabi/WebClients/ExchangeRateProviders.cs
- WalletWasabi/WebClients/Gemini/GeminiExchangeRateProvider.cs
- WalletWasabi/WebClients/ItBit/ItBitExchangeRateProvider.cs
Part of #9351
~~I didn't touch the exchange rate related methods because they don't (yet) support a cancellation token.~~
~~I will do that in a following PR.~~ Done.
I didn't touch `ChaumianController` because those methods modify states, and we don't want to halt that mid-way through IMO.
https://stackoverflow.com/a/58534523
It's easier to review commit by commit IMO.
> Add cancellation token to Controllers #1

- WalletWasabi.Fluent/ViewModels/Wallets/Advanced/WalletStatsViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModel.cs
- WalletWasabi.Fluent/Views/Wallets/WalletView.axaml
closes https://github.com/zkSNACKs/WalletWasabi/issues/9441
-rename Wallet Statistics to Wallet Stats
-change order of items
> rename and change order WalletView menu items

- WalletWasabi.Fluent/Controls/LabelsItemsPresenter.axaml
- WalletWasabi.Fluent/Converters/StringConverters.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/PrivacyRing/PrivacyRingItemViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/PrivacyRing/PrivacyRingViewModel.cs
- WalletWasabi.Fluent/Views/Wallets/Home/Tiles/PrivacyRing/PrivacyRingDetailsView.axaml
- WalletWasabi.Fluent/Views/Wallets/Home/Tiles/PrivacyRing/PrivacyRingDetailsView.axaml.cs
- WalletWasabi.Fluent/Views/Wallets/Home/Tiles/PrivacyRing/PrivacyRingItemDetailsView.axaml
- WalletWasabi.Fluent/Views/Wallets/Home/Tiles/PrivacyRing/PrivacyRingItemDetailsView.axaml.cs
- WalletWasabi.Fluent/Views/Wallets/Home/Tiles/PrivacyRing/PrivacyRingView.axaml
- Fixes bad layout problem in the privacy ring for minimal resolution where the center info is overlapping the ring segments
- Fixes #9365
- Closes #9032 
on Master:
This PR:
> [VDG] Privacy Ring Details Layout

- WalletWasabi.Fluent/Views/Wallets/Send/TransactionSummary.axaml
When you hover over a privacy suggestion (and its preview is being displayed), the edit pockets button shouldn't be visible.
> [VDG] Hide edit pockets button on Preview transactions

- WalletWasabi/BitcoinCore/Mempool/MempoolMirror.cs
Fixes #9446 (hopefully)
https://github.com/zkSNACKs/WalletWasabi/issues/9446#issue-1431471722 proposes to modify `EvictSpendersNoLock` like this:
```cs
var txos = Mempool.Values
.SelectMany(x => x.Inputs.Select(y => (PrevOut: y.PrevOut, TxId: x.GetHash())))
.ToDictionary(x => x.PrevOut, x => x.TxId);
foreach (var input in txOuts)
{
if (txos.TryGetValue(input, out var txid))
{
Mempool.Remove(txid);
}
}
```
but this PR does not implement that idea because I don't see too much value in recomputing prevouts for the mempool transactions *with every received new mempool transaction* because we can do it once and then just update the data. So this PR removes `EvictSpendersNoLock` and adds an index (`PrevOutsIndex`) that allows to detect double spends easily.
> `MempollMirror`: Improve effectiveness of `EvictSpendersNoLock`

- WalletWasabi.Tests/Helpers/WabiSabiFactory.cs
- WalletWasabi/Tor/Http/Extensions/HttpRequestMessageExtensions.cs
- WalletWasabi/Tor/Http/Helpers/HttpMessageHelper.cs
- WalletWasabi/Tor/TorProcessManager.cs
Follow-up to https://github.com/zkSNACKs/WalletWasabi/pull/8979#discussion_r951224641 so that it's hard to not propagate a cancellation token all the way down.
> Remove `default` CTs from Tor code (2)

- WalletWasabi/Services/UpdateManager.cs
Fixes #9492
Don't do unnecessary work on Linux.
This PR logs only in Info level.
> Use LogInfo in UpdateManager if it's called from Linux distro

- .github/workflows/auto-add-to-projcet.yml
This is not tested, similar to https://github.com/zkSNACKs/WalletWasabi/pull/9497/, but for discussions.
> Auto-add discussions to project board

- WalletWasabi.Packager/Program.cs
In case of an interruption in the packager progress flow - inconsistent states can occur regarding files. With this PR packager will be more tolerant.
> [Packager] Skip MSI creation if already exists 

- WalletWasabi/Helpers/ByteHelpers.cs
This PR aligns us with .NET and uses [`Convert.FromHexString`](https://learn.microsoft.com/en-us/dotnet/api/system.convert.fromhexstring?view=net-5.0) which is vectorized in .NET, so we should observe significant speedup (see https://github.com/MetacoSA/NBitcoin/pull/1149 for some numbers). 
Current master implementation
```
|  Method |      Mean |    Error |   StdDev |
|-------- |----------:|---------:|---------:|
|   ToHex |  25.19 ns | 0.501 ns | 1.355 ns |
| FromHex | 563.06 ns | 4.742 ns | 3.702 ns |
```
This PR: Only first commit:
```
|  Method |     Mean |    Error |   StdDev |
|-------- |---------:|---------:|---------:|
|   ToHex | 35.58 ns | 0.171 ns | 0.152 ns |
| FromHex | 71.38 ns | 0.650 ns | 0.576 ns |
```
This PR: All commits
```
|  Method |     Mean |    Error |   StdDev …
```
> Use .NET 5's HEX function

- WalletWasabi.Documentation/WasabiSetupRegtest.md
Updates the doc:
- Reflect that **bitcoin.conf** won't exist after setup. It needs to be created first.
- Can't start more than 1 instance of Wasabi Wallet.
- Minor corrections.
> [Documentation] [Trivial] Update manual steps for RegTest setup

- WalletWasabi.Fluent/Behaviors/ExecuteCommandOnDoubleTapped.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Advanced/WalletCoins/WalletCoinViewModel.cs
- WalletWasabi.Fluent/Views/Wallets/Advanced/WalletCoins/WalletCoinsView.axaml
- WalletWasabi.Fluent/Views/Wallets/Home/History/HistoryTable.axaml
- WalletWasabi.Fluent/Views/Wallets/Receive/ReceiveAddressesView.axaml
Fixes: #9532
- HistoryTable - Show transaction details
- ReceiveAddressesView - Navigate to address QR code
- WalletCoinsView - Selected/deselect coin
> [VDG] Add support for double-click to show details

- WalletWasabi.Documentation/WasabiCompatibility.md
Windows 10 version 1703 is supported by .NET 6 according to: https://github.com/dotnet/core/blob/main/release-notes/6.0/supported-os.md
> [Trivial] Update supported OS

- WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/PrivacyRing/PrivacyRingViewModel.cs
It will immediately clear the ring as the window is resized. Throttle time shouldn't affect it.
> [VDG] Privacy Ring - fix glitch during resize

- WalletWasabi.Backend/Controllers/WabiSabiController.cs
- WalletWasabi/Cache/IdempotencyRequestCache.cs
- WalletWasabi/Wallets/P2pBlockProvider.cs
> [trivial] `IdempotencyRequestCache`: Preparation work

- WalletWasabi.Fluent/ViewModels/CoinJoinProfiles/PrivateCoinJoinProfileViewModel.cs
Fixes: #9587
Max Privacy + 50 anon score target gives back `Custom` coinjoin profile falsely.
This PR fixes this.
> Fix Max Privacy profile equality

- WalletWasabi.Fluent/Views/AddWallet/Create/RecoveryWordsView.axaml
- Sets the basic 3-column layout that will be used in #9575 to fix the problems described in #9576
- This is a separate PR because it affects a different screen than #9575
> [VDG] Recovery words - 3 column layout

- WalletWasabi.Tests/UnitTests/WabiSabi/Client/CoinJoinCoinSelectionTests.cs
- WalletWasabi/Blockchain/TransactionOutputs/ISmartCoin.cs
- WalletWasabi/Blockchain/TransactionOutputs/SmartCoin.cs
- WalletWasabi/Crypto/Bip322Signature.cs
- WalletWasabi/Crypto/OwnershipProof.cs
- WalletWasabi/Extensions/NBitcoinExtensions.cs
- WalletWasabi/WabiSabi/Backend/Rounds/RoundParameters.cs
- WalletWasabi/WabiSabi/Backend/Rounds/UtxoSelectionParameters.cs
- WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
This PR allows for implementation of Wabisabi client library which will be used by Trezor.
> Select coins for round abstraction

- WalletWasabi.Tests/Helpers/ArenaBuilder.cs
- WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepConnectionConfirmationTests.cs
- WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepTransactionSigningTests.cs
- WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterInputFailureTests.cs
- WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterInputToBlameRoundTests.cs
- WalletWasabi.Tests/UnitTests/WabiSabi/Backend/UtxoPrisonTests.cs
- WalletWasabi.Tests/UnitTests/WabiSabi/Backend/UtxoPrisonWardenTests.cs
- WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiApiApplicationFactory.cs
- WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiHttpApiIntegrationTests.cs
- WalletWasabi/WabiSabi/Backend/DoSPrevention/Inmate.cs
- WalletWasabi/WabiSabi/Backend/DoSPrevention/Prison.cs
- WalletWasabi/WabiSabi/Backend/DoSPrevention/Punishment.cs
- WalletWasabi/WabiSabi/Backend/DoSPrevention/Warden.cs
- WalletWasabi/WabiSabi/Backend/Rounds/Arena.Partial.cs
- WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
- WalletWasabi/WabiSabi/WabiSabiCoordinator.cs
This is a preparation PR before start working on the DoS prevention improvements.
```
├── WabiSabi
│   ├── Backend
│   │   ├── Banning
│   │   │   ├── ApiResponseItem.cs
│   │   │   ├── CoinVerifierApiClient.cs
│   │   │   ├── CoinVerifier.cs
│   │   │   ├── Innocent.cs
│   │   │   ├── Inmate.cs
│   │   │   ├── Prison.cs
│   │   │   ├── Punishment.cs
│   │   │   ├── Warden.cs
│   │   │   └── Whitelist.cs
```
```
├── WabiSabi
│   ├── Backend
│   │   ├── Banning
│   │   │   ├── ApiResponseItem.cs
│   │   │   ├── CoinVerifierApiClient.cs
│   │   │   ├── CoinVerifier.cs
│   │   │   ├── Innocent.cs
│   │   │   └── Whitelist.cs
│   │   ├── DoSPrevention
│   │   │   ├── Inmate.cs
│   │   │   ├── Prison.cs
│   │   │   ├── Punishment.cs
│   │   │   └── Warden.cs
```
> [Trivial] Separate DoS classes from utxo whitelisting

- WalletWasabi.Fluent/TreeDataGrid/TreeDataGridPrivacyTextCell.cs
- WalletWasabi.Fluent/Views/Wallets/Home/History/HistoryTable.axaml
- Adds `Background` support in the rendering of `TreeDataGridPrivacyTextCell`
- Sets the `Background` to `Transparent` for such cells in the `HistoryTable`
- Fixes #9595
> [VDG] TreeDataGrid PrivacyTextCell - Add Transparent background

- WalletWasabi.Fluent/Config.cs
- WalletWasabi.Fluent/Global.cs
Follow-up to https://github.com/zkSNACKs/WalletWasabi/pull/9528#issuecomment-1323901667
I like the new names better as it's certainly more correct.
WDYT?
> Change setting properties's names after the fallback mechanism removal

- WalletWasabi/Helpers/WasabiSignerHelpers.cs
- WalletWasabi/Services/UpdateManager.cs
Instead of #9259 
This PR adds different file verifying methods to the UpdateManager with the help of WasabiSignerHelpers, introduced in #9515 .
Once, upon a new release, it verifies the provided `SHA256SUMS.asc` file, with the _(also provided)_ `SHA256SUMS.wasabisig`.
Then, after the correct installer is downloaded, it verifies the hash of the downloaded file with the expected hash to be found in  `SHA256SUMS.asc`.
> Add file verifying to UpdateManager

- WalletWasabi.Tests/UnitTests/Clients/SingleInstanceCheckerTests.cs
I have noticed that the test has been failing recently. I'm not sure if this fixes the issue but it might be the reason why it fails.
> `SingleInstanceCheckerTests.OtherInstanceStartedTestsAsync`: Add missing test multiplier

- WalletWasabi.Fluent/ViewModels/CoinControl/Core/PocketCoinControlItemViewModel.cs
Calculation was wrong. This showed pockets as being unconfirmed. Not it's fixed.
> [VDG] [Trivial] Coin control. Fix bad confirmation count

- WalletWasabi.Fluent/ViewModels/Wallets/Advanced/WalletCoins/WalletCoinViewModel.cs
- WalletWasabi.Fluent/Views/Wallets/Advanced/WalletCoins/Columns/SelectionColumnView.axaml
- WalletWasabi.Fluent/Views/Wallets/Advanced/WalletCoins/WalletCoinsView.axaml
First part of https://github.com/zkSNACKs/WalletWasabi/issues/9541
This PR only works on the `CTRL+C+D` dialog.
Next PR will tinker on the default send workflow.
> Don't allow to select coins if they are registered to a CJ round

- WalletWasabi.Tests/UnitTests/Transactions/TransactionStoreTests.cs
- WalletWasabi/Blockchain/Transactions/AllTransactionStore.cs
- WalletWasabi/Blockchain/Transactions/TransactionStore.cs
- WalletWasabi/Stores/IndexStore.cs
This fixes a few warnings and passes data via ctor which is a good thing.
> `TransactionStore`: Cleanup

- .github/ISSUE_TEMPLATE/bug-report.md
For more readable logs reported from the users, as some don't know you can use triple '`'s to format logs.
> Update Logs part of Issue creation

- WalletWasabi.Fluent/Helpers/NotificationHelpers.cs
current is wrong
the user doesn't receive anything
as long as it's unconfirmed there is 0 certainty that you will receive the bitcoin
`X BTC incoming` is the best correct (newbie friendly) message, I think
> correct incoming notification

- WalletWasabi.Packager/Program.cs
- WalletWasabi/Helpers/WasabiSignerHelpers.cs
Simple addition to #9535, requested by @molnard :
At the very end, check back if the created installer file's match the ones in `SHA256SUMS.asc`.
> Verify back Installer's hashes in Packager

- WalletWasabi/Blockchain/Keys/KeyManager.cs
- WalletWasabi/Blockchain/Transactions/TransactionFactory.cs
This PR makes sure to use segwit scripts for change outputs.
> Make sure we never use other than segwit script for change outputs

- WalletWasabi.Fluent/Global.cs
- WalletWasabi.Tests/Helpers/TestNodeBuilder.cs
- WalletWasabi/BitcoinCore/CoreNode.cs
- WalletWasabi/BitcoinCore/CoreNodeParams.cs
This PR disables wallet for Bitcoin Knots when starting it. The reasons are the following:
1. We don't need it.
2. It probably makes startup faster.
3. It makes Knots work on my machine.
Let me elaborate on point (3):
I recently changed computers and noticed Wasabi Wallet cannot start Bitcoin Knots. It fails with the following message:
```
2022-12-08 11:14:49.945 [22] ERROR	Global.StartLocalBitcoinNodeAsync (272)	WalletWasabi.BitcoinCore.Processes.BitcoindException: Failed to start daemon, location: 'C:\Users\user\Desktop\WalletWasabi\WalletWasabi.Fluent.Desktop\bin\Debug\net7.0\Microservices\Binaries\win64\bitcoind.exe -regtest=0 -testnet=0 -datadir="C:\Users\user\AppData\Roaming\Bitcoin" -printtoconsole=0'
---> System.Net.Http.HttpRequestException: No connection could be made because …
```
> Fix "Bitcoin Knots doesn't work" issue

- WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
- WalletWasabi/WabiSabi/Client/CoinJoinResult.cs
Preparation for this https://github.com/zkSNACKs/WalletWasabi/pull/9681
Just moving the code and a small restructure.
> Extract round related actions to method

- WalletWasabi.Fluent/Helpers/KeyManagerExtensions.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Advanced/WalletStatsViewModel.cs
- WalletWasabi.Fluent/Views/Wallets/Advanced/WalletStatsView.axaml
- WalletWasabi.Tests/UnitTests/KeyManagementTests.cs
- Removes `Largest receive key gap` and `Largest change key gap` from the `Wallet Stats` UI.
- Removes the `KeyManagerExtensions.CountConsecutiveUnusedKeys()` extension method.
- Removes Unit Tests for the method above.
- Fixes #9733
> [VDG] Remove key gap fields from Wallet Stats

- WalletWasabi.Tests/UnitTests/Transactions/AllTransactionStoreTests.cs
- WalletWasabi/Blockchain/Transactions/AllTransactionStore.cs
- WalletWasabi/Stores/IndexStore.cs
- WalletWasabi/Wallets/FileSystemBlockRepository.cs
This PR removes code that ensures backward compatibility. I'm aware that the policy is not to break BC but there are some considerations that might make it reasonably in this case.
* The [code](https://github.com/zkSNACKs/WalletWasabi/commit/29ca098abb58ad98aec9b330c2330e43b1713ccb) was added 2 years ago.
* https://github.com/zkSNACKs/WalletWasabi/pull/9528#issuecomment-1328857058 - David plans to write a note about backward compatibility anyway
So 2 years is a long time and there were many new WW1 versions after that. So the removed code is only useful for people who are on a very old WW1 versions and did not upgrade to the latest WW1 also did not install WW2 and also did not need [Trezor T hotfix](https://github.com/zkSNACKs/WalletWasabi/releases/tag/v1.1.12.7), probably use an oldish …
> Remove backward compatibility code

- WalletWasabi.WindowsInstaller/Components.wxs
- WalletWasabi.WindowsInstaller/Product.wxs
Fixes #4325
* It would be good to actually tick the checkbox by default. Not sure how to do it at the moment.
* The first commit shows how to run WW without any interaction whatsoever after the installation is done. This is slightly uncommon behavior though.
* The second commit adds the checkbox and fixes #4325. However, the checkbox is located in a gray rectangle. That's a known [WIX issue](https://github.com/wixtoolset/issues/issues/1687) and I have not found any workaround.
* https://github.com/wixtoolset/issues/issues/1687 - text on exitdialog needs to be separate from checkbox 
* https://github.com/wixtoolset/issues/issues/5430 - example 1
* https://github.com/xenserver/xenadmin/pull/3018 - example 2
* https://wixtoolset.org/docs/v3/wixui/wixui_customizations/
> Run Wasabi Wallet After Install 

- WalletWasabi/Tor/Http/Extensions/HttpRequestMessageExtensions.cs
- WalletWasabi/Tor/Http/Models/HeaderSection.cs
`ToString(bool endWithTwoCRLF)` is always called with `false` as the parameter of the calls
> [Tor] `HeaderSection`: Remove unused `ToString(bool endWithTwoCRLF)`

- WalletWasabi.Fluent/ViewModels/Wallets/Send/SendViewModel.cs
- WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/9165
> Handle wallets separately when are in send workflow

- WalletWasabi.Fluent/ViewModels/Wallets/Advanced/WalletInfoViewModel.cs
- WalletWasabi.Fluent/Views/Wallets/Advanced/WalletInfoView.axaml
- Title is self-explanatory
- Fixes #9736
> [VDG] Taproot UI support] #4 - Remove Remove zprv and zpub from Wallet Info

- .github/workflows/auto-add-to-projcet.yml
This PR adds explicit [permissions section](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) to workflows. This is a security best practice because by default workflows run with [extended set of permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) (except from `on: pull_request` [from external forks](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)). By specifying any permission explicitly all others are set to none. By using the principle of least privilege the damage a compromised workflow can do (because of an [injection](https://securitylab.github.com/research/github-actions-untrusted-input/) or compromised third party tool or …
> GitHub Workflows security hardening

- WalletWasabi.Fluent/ViewModels/Settings/BitcoinTabSettingsViewModel.cs
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/8735
The thing is empty string is allowed in case it doesn't find the directory. This solution still allows the string to be empty, but when the user turns the feature off/on it will try to find again the default path.
> [VDG] reset empty local BTC core path when enabled

- WalletWasabi.Tests/UnitTests/TestWallet.cs
- WalletWasabi.Tests/UnitTests/WabiSabi/Client/ArenaClientTests.cs
- WalletWasabi.Tests/UnitTests/WabiSabi/Client/KeyChainTests.cs
- WalletWasabi/WabiSabi/Client/AliceClient.cs
- WalletWasabi/WabiSabi/Client/ArenaClient.cs
- WalletWasabi/WabiSabi/Client/BaseKeyChain.cs
- WalletWasabi/WabiSabi/Client/IKeyChain.cs
Follow-up to the slack discussion:
> Is there a reason why `IKeyChain.Sign` has ownershipProof [parameter](https://github.com/zkSNACKs/WalletWasabi/blob/97f07b778b886b43207519bbc34ed348062a11e6/WalletWasabi/WabiSabi/Client/IKeyChain.cs#L12)? Both implementations of IKeyChain:
>
> *  https://github.com/zkSNACKs/WalletWasabi/blob/97f07b778b886b43207519bbc34ed348062a11e6/WalletWasabi.Tests/UnitTests/TestWallet.cs#L127-L136
>  * https://github.com/zkSNACKs/WalletWasabi/blob/97f07b778b886b43207519bbc34ed348062a11e6/WalletWasabi/WabiSabi/Client/BaseKeyChain.cs#L41-L65
>
> do not seem to use the parameter.
Lucas's response:
> Yes. The idea is to abstract the signer. IKeyChain tries to be that abstraction, it should be good enough to abstract smart devices that know their UTXO set as well as dumb …
> Remove unused `OwnershipProof` from `IKeyChain`

- WalletWasabi/Helpers/Guard.cs
This PR makes it so that the following snippet does not show a warning on the marked place:
```cs
Guard.NotNull(nameof(value), value);
writer.WriteValue(Convert.ToHexString(value /* no warning here */));
```
Inspired by https://github.com/xunit/assert.xunit/pull/36/files#diff-404187c76aea8c97952a33aade25a6e3a47480961b7d507e49d3c925a0919ba0R23
> `Guard.NotNull`: Make sure analyzers will know that T was not `null`

- SECURITY.md
This feature is now enabled, this PR explains it here.
https://docs.github.com/en/code-security/security-advisories/guidance-on-reporting-and-writing/privately-reporting-a-security-vulnerability
> Add Github vulnerability reporting

- WalletWasabi/BitcoinCore/CoreNode.cs
Fixes the CI and Knots for users who are using the full node integration.
> Add softwareexpiry=0 to knots parameters

- WalletWasabi/Blockchain/TransactionOutputs/ISmartCoin.cs
- WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
Fixes #9770
There are several ways of doing this concept, I implemented 2:
1) Commits [ea17538-46aa327](https://github.com/zkSNACKs/WalletWasabi/pull/9782/files/46aa327e7916b9cb11e8b4bc9f03ad13da4ec5cc): At the beginning of the coin selection, if some coins are on the same `HdPubKey`, group and select `MaxInputsRegistrableByWallet` of them.
If not that much are available, does not complete the selection with other coins.
2) [83473d3](https://github.com/zkSNACKs/WalletWasabi/pull/9782/files/83473d3a505adb57f15de1e44a1d372a10d44d3d): At the end of the selection, check if the winners coins have other coins on their `HdPubKey` and if so select them but respecting the number of `MaxInputsRegistrableByWallet`.
> Select coins from reused address

- WalletWasabi.Fluent/ViewModels/Wallets/Receive/ReceiveAddressViewModel.cs
- WalletWasabi/Extensions/ExceptionExtensions.cs
- WalletWasabi/Hwi/HwiClient.cs
Closes https://github.com/zkSNACKs/WalletWasabi/issues/9781
This is how I would imagine a more user friendly but talkitive error message, pls suggest something if you find that better.
But to be perfectly honest, this isn't really an error, I can imagine this be usefull as somekind of a software-freeze prevention. Is there a main reason to happen like this?
What if we just handle this timeout in the background, but don't show it on the UI? Or increase the timespan to 120 sec?
One problem I can think of is that the user might click on some command (send, show address etc.) again, but if one didn't respond to the previous command on the HW, we throw an error anyway that the HW is busy. ⬅️ Maybe that error message needs a lil user-friendly tweak?
> More friendly HWI error message on timeout

- WalletWasabi.Fluent/Controls/NavBarItem.axaml
- WalletWasabi.Fluent/Controls/NavBarItem.axaml.cs
- WalletWasabi.Fluent/ViewModels/AddWallet/AddWalletPageViewModel.cs
- WalletWasabi.Fluent/ViewModels/AddWallet/AddedWalletPageViewModel.cs
- WalletWasabi.Fluent/ViewModels/AddWallet/HardwareWallet/ConnectHardwareWalletViewModel.cs
- WalletWasabi.Fluent/ViewModels/MainViewModel.cs
- WalletWasabi.Fluent/ViewModels/NavBar/NavBarItemViewModel.cs
- WalletWasabi.Fluent/ViewModels/NavBar/NavBarViewModel.cs
- WalletWasabi.Fluent/ViewModels/WalletManagerViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/ClosedWalletViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModelBase.cs
- WalletWasabi.Fluent/Views/NavBar/NavBar.axaml
Based on https://github.com/zkSNACKs/WalletWasabi/pull/9724, draft until that one gets merged.
Fixes: https://github.com/zkSNACKs/WalletWasabi/issues/8249
The main problem with the NavBar was that it was a `ListBox` and we relied on its `SelectedItem` property. That property was the trigger of the navigation.
This logic got problematic at a point as there are items in the NavBar that cannot be selected, so the idea is to have `Button`s instead of the `ListBoxItem` in the NavBar, and the trigger of the navigation is the click that executes a command.
This PR:
- Removes many negative margins and unnecessary code from the AXAML.
- Removes the workarounds
- Simplifies a lot
Known issue:
- Navigation to another wallet B as soon as wallet A started to load breaks the navigation, the following …
> [VDG] Refactor navbar

- WalletWasabi.Fluent/Styles/ToggleSwitch.axaml
Fixes: https://github.com/zkSNACKs/WalletWasabi/issues/9436
The ToggleSwitch has Transitions set for knonbs when IsChecked property value changes (true/false). When initial value of IsChecked=true and view is first time showed the transition is activated so it may be perceived as delay.
https://github.com/AvaloniaUI/Avalonia/blob/401bc521d2947bf7699a530f3d6e43e7a32c6baf/src/Avalonia.Themes.Fluent/Controls/ToggleSwitch.xaml#L116-L125
https://github.com/AvaloniaUI/Avalonia/blob/401bc521d2947bf7699a530f3d6e43e7a32c6baf/src/Avalonia.Themes.Fluent/Controls/ToggleSwitch.xaml#L162-L168
https://github.com/AvaloniaUI/Avalonia/blob/401bc521d2947bf7699a530f3d6e43e7a32c6baf/src/Avalonia.Controls/ToggleSwitch.cs#L242-L255
In this PR I just disabled the transition, another option would be enable …
> [VDG] Disable ToggleSwitch knobs transitions to fix delay of switch toggle as settings

- WalletWasabi/Tor/TorProcessManager.cs
Fixes #9518
Fixes #9878
Rename `WalletWasabi/Microservices/Binaries/win64/Tor/tor.exe` to `WalletWasabi/Microservices/Binaries/win64/Tor/tor2.exe` so that the file is not found by WW. You should see a crash report.
I have tested it on Windows.
> `TorProcessManager`: Re-throw exception

- WalletWasabi.Fluent/ViewModels/Wallets/CoinJoinStateViewModel.cs
Same as #9393 
Related https://github.com/zkSNACKs/WasabiDoc/pull/1413
I don't know the reasonning that led to label it "fallback round" in the UI, but we are referring to this concept as blame round, we are adding an entry in the doc about blame round, everywhere it's called blame round except here.
Imo it can bring confusion and make user think it's a different concept.
If there is a strong reason why it's bad to name it "blame" in the eyes of the users let's NACK and close this PR again but I think it's worth considering the change again now that we are adding a "blame round" entry in the doc.
Searching for "fallback" in the doc will only show an unrelated article: https://docs.wasabiwallet.io/using-wasabi/PayJoin.html#fallback-transaction
> Rename fallback to blame in music box

- WalletWasabi/Blockchain/Keys/KeyManager.cs
Reverts the change introduced before release to limit the output scripts for change outputs to segwit only.
> Remove segwit limitation for change outputs

- WalletWasabi/Stores/IndexStore.cs
- WalletWasabi/Wallets/Wallet.cs
This PR fixes a few warning regarding not propagating cancellation tokens. 
Also it simplifies the algorithm used in `ForeachFiltersAsync` and it's actually slightly faster on my machine because instead of using `ReadLineAsync` that returns `Task`, we use the overload that returns `ValueTask` so we don't need to allocate that much.
Additionaly, about 12 warnings is shaved off.
> `IndexStore`: Simplify `ForeachFiltersAsync`

- WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Receive/ReceiveAddressesViewModel.cs
This is same refactoring done as in https://github.com/zkSNACKs/WalletWasabi/pull/9946 and makes it consistent with other usages of TreeDataGrid column initialization in codebase.
> [VDG] Refactor TreeDataGrid column creation into methods

- WalletWasabi.Tests/UnitTests/Helpers/PowerSaving/BaseInhibitorTaskTests.cs
- WalletWasabi.Tests/UnitTests/Tor/TorProcessManagerTests.cs
- WalletWasabi/Microservices/ProcessAsync.cs
Remove unused code. At this point, we need `ProcessAsync` only for mocking purposes. Originally, `ProcessAsync` was implemented because `Process.WaitForExitAsync` was not implemented in .NET. 
Imho our encapsulation of `Process` should be as thin as possible.
> `ProcessAsync`: Cleanup

- WalletWasabi.Backend/Global.cs
- WalletWasabi.Tests/UnitTests/WabiSabi/Backend/UtxoWhitelistTests.cs
- WalletWasabi.Tests/UnitTests/WabiSabi/Backend/WhitelistTests.cs
- WalletWasabi/WabiSabi/Backend/Banning/CoinVerifier.cs
- WalletWasabi/WabiSabi/Backend/Banning/Whitelist.cs
`WhiteList` will be able to check and release coins one by one - right at the time when requested. This is required for further work with CoinVerifier.
> Refactor WhiteList

- WalletWasabi.Fluent/App.axaml
- WalletWasabi.Fluent/Controls/ClipboardCopyButton.axaml.cs
- WalletWasabi.Fluent/Controls/CopyableItem.axaml
- WalletWasabi.Fluent/Controls/CopyableItem.axaml.cs
- WalletWasabi.Fluent/Converters/BooleanConverters.cs
- WalletWasabi.Fluent/Converters/MoneyConverters.cs
- WalletWasabi.Fluent/Extensions/CurrencyExtensions.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/WalletBalanceTileViewModel.cs
- WalletWasabi.Fluent/Views/Wallets/Home/Tiles/PrivacyControlTileView.axaml
- WalletWasabi.Fluent/Views/Wallets/Home/Tiles/WalletBalanceTileView.axaml
- WalletWasabi.Fluent/Views/Wallets/Send/SendView.axaml
Improves UX by allowing users to copy their balance (in a given wallet) using a copy button that appears on hover.
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/9678
> [VDG] Copy balance from tile

- WalletWasabi.Fluent/Controls/LineChart.cs
- WalletWasabi.Fluent/Models/Windows/DirectShow.cs
- WalletWasabi.Fluent/State/StateMachine.cs
- WalletWasabi.Fluent/Validation/Validations.cs
- WalletWasabi.Fluent/ViewModels/Navigation/NavigationManager.cs
- WalletWasabi/Blockchain/Analysis/CoinjoinAnalyzer.cs
- WalletWasabi/WabiSabi/Backend/Statistics/RequestTimeStatista.cs
To fix some VS warnings.
> CA1854: Prefer the IDictionary.TryGetValue(TKey, out TValue) method
> Rule description
> When an element of an IDictionary is accessed, the indexer implementation checks for a null value by calling the IDictionary.ContainsKey method. If you also call IDictionary.ContainsKey in an if clause to guard a value lookup, two lookups are performed when only one is needed.
https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1854
> Use IDictionary.TryGetValue(TKey, out TValue) method

- WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
Closes #9936 (see https://github.com/zkSNACKs/WalletWasabi/issues/9936#issuecomment-1405969523)
I don't think it makes any difference in the behavior as wallet will wait for the coins to confirm anyway.
Not sure if we want to do that, please NACK if no.
Please also note that this doesn't help for #9957, even if the issues are similar
To fix both issues we could remove these lines: 
https://github.com/zkSNACKs/WalletWasabi/blob/919c88e21d4a33f9d339afdf2649e7b8f5444d32/WalletWasabi/WabiSabi/Client/CoinJoinManager.cs#L199-L206
> Start CJ with only pending coins

- WalletWasabi/Helpers/CoinHelpers.cs
- WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
- WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
- WalletWasabi/Wallets/Wallet.cs
Result of a meeting with @molnard 
This PR does 3 things:
1) 7d0398b41a22aedc49283ffef7a5bd46269ba656: Create `WalletWasabi.Helpers.CoinHelpers` which is inspired from [WalletWasabi.Fluent.Helpers.CoinHelpers](https://github.com/zkSNACKs/WalletWasabi/blob/master/WalletWasabi.Fluent/Helpers/CoinHelpers.cs) and implements privacy status checks for `TCoin`. I chose to use `TCoin` as it's the same type used in `SelectCoinsForRounds`. It would probably be cleaner to create a file for this class.
2) 32aa212291ef2632f595f69adaae6245d7e5dc27: Reverts #10008
3) 4b68c87c0120677bdda238207f061cfb315a6adc: Throw `StartError NoCoinsToMix` when the wallet is 100% private but has pending incoming coins.
-> So the behavior is always consistent: When no coins are available to mix in auto mode, don't start …
> CoinHelpers and starting CJ with empty coins consistency

- WalletWasabi.Fluent/Config.cs
- WalletWasabi.Fluent/Global.cs
- WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
This PR attempts to separate the coordinator http client from the wasabi http client. The idea is that not all coordinators would provide block filters, currency rates, etc so wasabi wallet should be able to connect to two endpoints: a backend and a coordinator
> Separate wasabi and wabisabi clients

- WalletWasabi.Fluent.Desktop/packages.lock.json
- WalletWasabi.Fluent/packages.lock.json
- WalletWasabi.Packager/packages.lock.json
- WalletWasabi.Tests/UnitTests/Transactions/TransactionFactoryTests.cs
- WalletWasabi/WalletWasabi.csproj
- WalletWasabi/packages.lock.json
NBitcoin 7.0.14 doesn't allow elements larger than 1MiB what prevents us to deal with transactions containing NFTs or other large witness data.
See: https://github.com/MetacoSA/NBitcoin/issues/1162
> Upgrade NBitcoin version from 7.0.14 to 7.0.24

- WalletWasabi.Fluent/ViewModels/Wallets/Advanced/WalletCoins/WalletCoinsViewModel.cs
If you address reuse the coins dialog is missing utxos.
Master:
This PR:
> Fix coins dialog on address reuse

- WalletWasabi.Tests/UnitTests/Transactions/TransactionProcessorTests.cs
- WalletWasabi/Blockchain/TransactionProcessing/TransactionProcessor.cs
Closes #10044
A small coin is not an attack on the user if it was not sent by someone to an already used address. A coins should be filtered when:
1. it is smaller than the _dust attack prevention threshold_,
2. the sender and the receiver are not the same person and,
3. the coin is sent to an already used address.
> Fix dust attack prevention logic

- WalletWasabi.Tests/XunitConfiguration/RegTestFixture.cs
- WalletWasabi/WebClients/Bitstamp/BitstampExchangeRateProvider.cs
- WalletWasabi/WebClients/CoinGecko/CoinGeckoExchangeRateProvider.cs
- WalletWasabi/WebClients/Wasabi/WasabiClient.cs
When the base url has a subpath, and the relative url has a leading "/", the subpath of the base url is ignored. Initially ran into this in #9904, and @kiminuo showed me the correct usage. Since I was only testing with the wabisabi client, it all worked fine. Now, I was testing with the full wasabi client ans the api calls in `WasabiClient` all have a leading "/", causing the same issue. This PR removes all leading "/" in HttpClient Send requests.
> Fix relative path in uri

- WalletWasabi.Fluent/ViewModels/Wallets/CoinJoinStateViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/MusicStatusMessageViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/WalletSettingsViewModel.cs
- WalletWasabi.Fluent/Views/Wallets/MusicControlsView.axaml
- Removes `MusicStatusMessageViewModel` as we thought that would be needed, but since then it is clear `string` is enough.
- Fixes `PlebStopThreshold`. For some reason, it was duplicated on the wallet settings and the coinjoin settings too. It checked the wrong place.
- Cleanup (removes obsolete comment, reordering, unifying)
- Renames `ElapsedTime` and `RemainingTime` to `LeftText` and `RightText` as they don't only display time, but also messages.
> [VDG] `CoinJoinStateViewModel` - Cleanup

- WalletWasabi.Fluent/ViewModels/Wallets/CoinJoinStateViewModel.cs
- WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
Fixes CF issues in `CoinJoinManager.cs` & `CoinJoinStateViewModel.cs` to address https://github.com/zkSNACKs/WalletWasabi/pull/10059#issuecomment-1419216052
> Fix some CodeFactor issues

- WalletWasabi.Backend/InitConfigStartupTask.cs
- WalletWasabi.Backend/Startup.cs
- WalletWasabi.Fluent.Desktop/Program.cs
- WalletWasabi.Fluent/Config.cs
- WalletWasabi.Tests/UnitTests/StartWasabiOnSystemStartupTests.cs
- WalletWasabi.Tests/UnitTests/WabiSabi/Backend/ConfigTests.cs
- WalletWasabi/Bases/ConfigBase.cs
- WalletWasabi/Interfaces/IConfig.cs
- WalletWasabi/Services/ConfigWatcher.cs
- WalletWasabi/WabiSabi/CoordinatorParameters.cs
Follow-up to: https://github.com/zkSNACKs/WalletWasabi/pull/10045#issuecomment-1419194364
Review with whitespace off: https://github.com/zkSNACKs/WalletWasabi/pull/10077/files?diff=split&w=1
> `Config`: Merge load methods

- WalletWasabi.Fluent/MathNet/.editorconfig
- WalletWasabi.Fluent/Models/Windows/.editorconfig
- WalletWasabi/Gma/.editorconfig
- WalletWasabi/Nito/.editorconfig
Because these .editorconfig files have `root = true` the search for .editorconfig files will stop and therefore not use the .editoconfig file at the root of the repository.
This change prevents the use of spaces when editing any file in the directory of the .editorconfig file or in any child directory.
> [Trivial] Add indentation preference in .editorconfig files

- WalletWasabi.Backend/Global.cs
- WalletWasabi.Tests/UnitTests/WabiSabi/Backend/CoinVerifierTests.cs
- WalletWasabi/WabiSabi/Backend/Banning/CoinVerifierApiClient.cs
I'm seeing a lot of these in the Logs
```
2023-02-07 09:37:19.048 [518] ERROR	xxx.TryScheduleVerification (265)	xxx was failed with 'System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
---> System.TimeoutException: The operation was canceled.
---> System.Threading.Tasks.TaskCanceledException: The operation was canceled.
---> System.IO.IOException: Unable to read data from the transport connection: Operation canceled.
---> System.Net.Sockets.SocketException (125): Operation canceled
--- End of inner exception stack trace ---
```
~~With this PR, the `cancellation token` and the `HttpClient.Timeout` is the same time interval.~~
_I know this is only mitigating the issue._
> Retry in case of exception/timeout of HttpClient

- WalletWasabi/WabiSabi/Models/MultipartyTransaction/ConstructionState.cs
Adds a safety margin of tolerance for mining fee paid by coinjoins and add log the offending transaction to see what elements are the one disrupting the round
> Quick fix for incorrect fee issue

- WalletWasabi/BestEffortEndpointConnector.cs
Attempts to do: *There was a Tor meeting 2 months ago where we decided not to enforce identity change between P2P Bitcoin nodes so we avoid using many circuits.*
This PR shows just the most strict approach. We would have only one Tor identity. 
I think it would be better to add a little bit of randomness to it. Lucas mentioned:
_you can also "reduce" the number of identities by deciding which one to use based on the endpoint.  Lets say you want to use only 3 circuits the you can do:_
```cs
var aThirdOfInt32 = Int32.MaxValue / 3;
var hash = Hash(endpoint);
Convert.ToInt32(hash[0..4]) switch {
n when n < aThirdOfInt32 => "identity 1",
n when n < 2 * aThirdOfInt32 => "identity 2"
_ => "identity 3" }
```
another approach might be to have just one circuit but to change it after N minutes (10 / …
> Do not enforce identity change when connecting to p2p nodes

- WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
Missing from #10088
Found this in the Logs
```
Exception: System.Collections.Generic.KeyNotFoundException: The given key 'NBitcoin.Coin' was not present in the dictionary.
at WalletWasabi.WabiSabi.Backend.Rounds.Arena.StepInputRegistrationPhaseAsync(CancellationToken cancel)
```
> Add missing equality comparer

- WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
Throw the exception to the outer try-catch block otherwise we can resurrect ended rounds.
Exmaple:
```
Round.SetPhase (90)	Round (34c600b6a1d8b3135ad7ef527c462c8d657951f37a3e7f6bacfcfc0ccde6d200): Phase changed: InputRegistration -> Ended
Round.SetPhase (90)	Round (34c600b6a1d8b3135ad7ef527c462c8d657951f37a3e7f6bacfcfc0ccde6d200): Phase changed: Ended -> ConnectionConfirmation
Arena.StepConnectionConfirmationPhaseAsync (194)	Round (34c600b6a1d8b3135ad7ef527c462c8d657951f37a3e7f6bacfcfc0ccde6d200): 2 alices removed because they didn't confirm.
Round.SetPhase (90)	Round (34c600b6a1d8b3135ad7ef527c462c8d657951f37a3e7f6bacfcfc0ccde6d200): Phase changed: ConnectionConfirmation -> OutputRegistration
```
> Fix the impossible :)

- WalletWasabi.Fluent/ViewModels/Wallets/Receive/ReceiveAddressViewModel.cs
fixes https://github.com/zkSNACKs/WalletWasabi/issues/9911
The previous solution (navigate back) was less intrusive, but honestly, it is better the close the dialog as that would be the first thing that the user does after noticing the new transaction.
> [VDG] Close address displaying dialog when received funds

- WalletWasabi.Fluent/Controls/Spectrum/AuraSpectrumDataSource.cs
- WalletWasabi.Fluent/Controls/Spectrum/SpectrumControl.cs
- WalletWasabi.Fluent/Controls/Spectrum/SpectrumDataSource.cs
- WalletWasabi.Fluent/Controls/Spectrum/SplashEffectDataSource.cs
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/9189
The animation was broken on the master. This PR fixes while trying to simplify the rendering logic.
It will keep calling `Render` until there is something to draw.
Expected behavior:
- The greeting "splash" animation should appear when a wallet's home screen gets opened.
- it should not appear when CJing animation is visible.
- The MainWindow should be refreshed when there is no animation.
- Press F12 to pop Avalonia debugger. enable FPS counter from the Options. It should be 0 when there is no animation (and of course if there is nothing on the screen that is moving)
- Whenever the animation is finished the FPS counter should go back to 0.
- Splash animation and CJing animation should not happen at the same time.
> [VDG] Fix splash animation

- WalletWasabi/WabiSabi/Backend/Banning/CoinVerifier.cs
Right now, I can see a bunch of these in the Logs.
```
WARNING	CoinVerifier.TryScheduleVerification (177)	Coin was already scheduled for verification.
WARNING	CoinVerifier.TryScheduleVerification (177)	Coin was already scheduled for verification.
WARNING	CoinVerifier.TryScheduleVerification (177)	Coin was already scheduled for verification.
```
Which means the coin was already scheduled for verification and most probably finished already, but we failed to remove it from the dictionary. (Not sure why we failed yet)
If the task is completed, the coin is either on the `Whitelist` or in the `Prison`, so we should remove completed tasks on `CleanUp()` calls.
> Fix removal of items when task is completed

- WalletWasabi.Fluent/ViewModels/Wallets/CoinJoinStateViewModel.cs
In auto coinjoin mode!
When you have unconfirmed coins only and you press the play button to override the initial coinjoin delay, it won't change the display to that the coinjoin is running and checking coins every 30 seconds. Another consequence is that the user cannot press pause, because only the play button is visible.
> State machine will follow the business logic

- WalletWasabi.Fluent/Views/Shell/MainScreen.axaml
Because it is annoying if it runs whenever the musicbox got visible.
> [VDG] Disable splash animation on full private wallets

- WalletWasabi.Tests/UnitTests/Affiliation/ServerStatusUpdaterTests.cs
This is an idea how to fix the flaky test.
> [Affiliate server] Fix flaky `AffiliateServerStatusUpdaterTests.GetStatusTestAsync` test

- Contrib/AffiliationServer/README.md
- Contrib/AffiliationServer/signerkeygen.fsx
We will need to generate a key pair for wasabi coordinator to sign the coinjoin notifications that will be sent to the affiliate servers. This tool is for generating that secret/public key pair.
Before going to production the public key must be shared with all the affiliate server's operatros.
> Key generator for affiliation server

- WalletWasabi.Fluent/Controls/PreviewItem.axaml.cs
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/10003
This PR fixes the issue, but IMHO it should be refactored because it relies (and even the previous solution) on `ReactiveCommand` which shouldn't happen.
> [VDG] Fix copy button

- WalletWasabi.Fluent/ViewModels/AddWallet/HardwareWallet/ConnectHardwareWalletViewModel.cs
- WalletWasabi.Fluent/Views/AddWallet/HardwareWallet/ConnectHardwareWalletView.axaml
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/9238
It is not possible to know during detection if it lasts too long or just a device requests a password... The previous solution assumed that if the detection lasts longer than 7 seconds then it is probably a password request. This is bad as it really depends on the computer...
Remove the hack and display a restrained message about the possible password.
> [VDG] fix confusing wrong message about passphrase

- WalletWasabi.Fluent.Desktop/Program.cs
- WalletWasabi.Fluent/Config.cs
New special hostnames are created for API requests. Part of longer term plan to separate backend from website. Old URLs are still working and will work for foreseeable future, but we want clients to start using new ones ASAP.
> Change default backend URIs to new API hostnames

- WalletWasabi/Blockchain/Analysis/BlockchainAnalyzer.cs
This pull request slightly modifies the anonymity computation algorithm.
The anonymity score of a transaction output [is computed](https://github.com/zkSNACKs/WalletWasabi/blob/a695f7db82ba928ef994050defc8977d63fdb909/WalletWasabi/Blockchain/Analysis/BlockchainAnalyzer.cs#L163) as an anonymity inherited from the inputs of the transaction belonging to the same person as the output plus an anonymity gained from the transaction itself. The inherited anonymity is either
* [the average anonymity score of the inputs weighted by their values](https://github.com/zkSNACKs/WalletWasabi/blob/a695f7db82ba928ef994050defc8977d63fdb909/WalletWasabi/Blockchain/Analysis/BlockchainAnalyzer.cs#L72) or
* [the minimum anonymity score of the inputs](https://github.com/zkSNACKs/WalletWasabi/blob/a695f7db82ba928e …
> Use less strict condition in anonymity computation

- WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
- WalletWasabi/WabiSabi/Client/SmartRequestNode.cs
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/9370
I've tested many ways to mitigate the problem as best as possible; this solution is the most efficient. I tested it extensively to the limits of the wallet (20 wallets coinjoining at the same time), I had no problem and could make coinjoins with 70+ TXs easily.
It has no effect if someone is conjoining with only one wallet.
Otherwise, requests are just waiting for others to finish before starting, keeping the load constant on Tor, increasing the number of requests that can be sent in the phase time window.
Using `15` as the max number of parallel requests is also possible and better on my machine, but I chose `10` for safety reasons because I can't test on old hardware.
> Limit parallels reissuance requests to 10

- WalletWasabi.Backend/wwwroot/index.html
- WalletWasabi/Helpers/Constants.cs
This will be released https://github.com/zkSNACKs/WalletWasabi/tree/v2030 
I wanted to have a commit to stick with. This might be the final version for the release. https://github.com/zkSNACKs/WalletWasabi/commit/dcac6090ffb83aa131674f5d3a785f60c21c13b9
With this PR, I am ensuring that the new version won't be deployed accidentally to the backend - because that would signal the latest version to everyone. 
Reverts zkSNACKs/WalletWasabi#10241
> Revert "Bump version to v2.0.3"

- WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
> [Trivial] Use Count property instead of Enumerable.Count method

- WalletWasabi.Backend/Controllers/ChaumianCoinJoinController.cs
- WalletWasabi.Tests/UnitTests/WabiSabi/Backend/CoinVerifierTests.cs
- WalletWasabi/WabiSabi/Backend/Banning/CoinVerifier.cs
- WalletWasabi/WabiSabi/Backend/Rounds/Arena.Partial.cs
Extracted from #10208 and improved a bit.
- removed nullability from parameters
- `[NotNullWhen(true)] out CoinVerifyItem? coinVerifyItem` was removed since no one used it.
- Removed "fast-scheduling", see my [reasons](https://github.com/zkSNACKs/WalletWasabi/pull/10266#issuecomment-1461693272)
> Refactor Schedule method

- WalletWasabi.Fluent/ViewModels/Wallets/Send/ChangeAvoidanceSuggestionViewModel.cs
- WalletWasabi.Tests/UnitTests/Blockchain/TransactionBuilding/ChangelessTransactionCoinSelectorTests.cs
- WalletWasabi/Blockchain/TransactionBuilding/ChangelessTransactionCoinSelector.cs
Co-pilot @Szpoti 
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/10060
Test taken from https://github.com/zkSNACKs/WalletWasabi/pull/10233
BnB should choose coins with same `ScriptPubKey` together and calculates with them as ONE coin. BnB doesn't prioritize them over non-address-reused coins.
All this PR does is making sure to spend the address reused coins together.
Also, improves the tests by a lot.
> [BnB] Spend address re-used coins together

- WalletWasabi.Backend/Controllers/ChaumianCoinJoinController.cs
- WalletWasabi.Tests/Helpers/BitcoinFactory.cs
- WalletWasabi.Tests/UnitTests/MockRpcClient.cs
- WalletWasabi.Tests/UnitTests/WabiSabi/Backend/CoinVerifierTests.cs
- WalletWasabi/WabiSabi/Backend/Banning/CoinVerifier.cs
- WalletWasabi/WabiSabi/Backend/Banning/CoinVerifierLogger.cs
- WalletWasabi/WabiSabi/Backend/Rounds/Arena.Partial.cs
Explanation of this `blockchainHeight - (confirmations - 1)` with an example:
For simplicity let's say at the time of the input registration request
blockchainHeight = 1000;
confirmations = 4
Report_block_height = 995 (Report_block_height indicates which is the last block the API provider analyzed.)
confirmations = 4 means the coin is in the 997 block.
Since being in the latest block means we are in the 1000 block, but the confirmations would be 1, we need to extract 1 out of the confirmations variable.
So in this example, we would remove the coin, because the coin is in the 997. block, which is bigger than the Report_block_height.
> Use block height from response (take 2)

- WalletWasabi.Fluent/ViewModels/Wallets/Home/History/Details/TransactionDetailsViewModel.cs
- WalletWasabi.Fluent/Views/Wallets/Home/History/Details/TransactionDetailsView.axaml
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/10154
> [VDG] Dont copy negative values on Transaction Details's amount.

- WalletWasabi.Fluent/ViewModels/AddWallet/Create/ConfirmRecoveryWordsViewModel.cs
Small addition for https://github.com/zkSNACKs/WalletWasabi/pull/9816, that I was not sure about. So this PR is for discussing it too.
IMO it is better to show the words that the user can choose from, in alphabetical order instead of random. With this, the users can find the needed words much quicker.
> [VDG] Confirm recovery words - alphabetical instead of random

- WalletWasabi/WabiSabi/Client/AliceClient.cs
Fixes message in the log.
```
2023-03-18 23:17:29.991 [36] WARNING	AliceClient.TryToUnregisterAlicesAsync (234)	709c87bb14ef0cd40626b687ff01778decb7ecc9dddf8b1541aff67c5fa55a54-264 unregistration failed with WalletWasabi.WabiSabi.Backend.Models.WabiSabiProtocolException: Round (9aef62f13ed28e462c12a42c96ddc9609ec60dfc32a91c94962e5863533f682c): Wrong phase (Ended).
at WalletWasabi.Tor.Http.Extensions.HttpResponseMessageExtensions.ThrowUnwrapExceptionFromContentAsync(HttpResponseMessage me, CancellationToken cancellationToken)
at WalletWasabi.WabiSabi.Client.WabiSabiHttpApiClient.SendWithRetriesAsync[TRequest](RemoteAction action, TRequest request, CancellationToken cancellationToken, Nullable`1 retryTimeout)
at WalletWasabi.WabiSabi.Client.WabiSabiHttpApiClient.SendAndReceiveAsync[TRequest] …
```
> Downgrade warning message to debug

- WalletWasabi.Tests/UnitTests/NBitcoinTests.cs
- WalletWasabi/Extensions/NBitcoinExtensions.cs
I noticed this while working on #10010.
> `NBitcoinExtensions`: Remove unused methods

- WalletWasabi.Fluent/Helpers/NotificationHelpers.cs
- WalletWasabi.Fluent/ViewModels/WalletManagerViewModel.cs
Closes https://github.com/zkSNACKs/WalletWasabi/issues/9824
This "fixes" #9824 ; As it was said in the meeting, we will only partially address it by adding fiat conversion in the notification cards.
> [VDG] Add fiat conversion in notification cards

- WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
`unsignedCoinJoinTransaction` wasn't used in `LogCoinJoinSummary(...)`.
> [Trivial] Remove unused parameter

- WalletWasabi.Tests/UnitTests/Tor/Http/Extensions/HttpContentExtensionsTests.cs
- WalletWasabi/Tor/Http/Extensions/HttpContentExtensions.cs
- WalletWasabi/WabiSabi/Backend/Banning/CoinVerifierApiClient.cs
This PR is an alternative to #10310 and pulls the good parts from that PR.
If the PR is merged, the next step should be to move `HttpContentExtensions` out of `WalletWasabi.Tor.Http.Extensions` namespace to a better one (e.g. `WalletWasabi.Http.Extensions`)
> `HttpContentExtensions`: Cleanup + `CoinVerifierApiClient` cleanup

- WalletWasabi.Tests/UnitTests/Affiliation/AffiliateDataUpdaterTests.cs
In this PR we removed the mocked HttpClient by one a simpler version of it that allows us to assert the content and even set breakpoints.
> Make the test easier to understand and play with

- WalletWasabi.Fluent.Desktop/WalletWasabi.Fluent.Desktop.csproj
- WalletWasabi.Fluent.Desktop/packages.lock.json
- WalletWasabi.Fluent/WalletWasabi.Fluent.csproj
- WalletWasabi.Fluent/packages.lock.json
Looks like Avalonia 0.10.19 has several bug fixes for windowing system, might be worth updating as v11 is still not ready.
https://github.com/AvaloniaUI/Avalonia/compare/release/0.10.18...release/0.10.19
I think it fixes: https://github.com/zkSNACKs/WalletWasabi/issues/9193
> [VDG] Update to Avalonia 0.10.19

- WalletWasabi.Fluent/Helpers/ApplicationHelper.cs
- WalletWasabi.Fluent/Infrastructure/ClipboardObserver.cs
As @soosr pointed out in https://github.com/zkSNACKs/WalletWasabi/pull/10318#issuecomment-1484651352 `null` values are expected here.
> Clipboard text observables produce nullable values

- WalletWasabi.Packager/ArgsProcessor.cs
- WalletWasabi/Blockchain/Analysis/CoinjoinAnalyzer.cs
- WalletWasabi/Services/UpdateManager.cs
`First()` and `Count()` accept predicates, so we can drop the `Where()` part and move the predicates right into those calls.
> Simplify LINQ calls

- WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
This is useless as coin is already a `TCoin`, 2 lines after there's the same code where `TCoin` is not specified.
> [Trivial] Remove type specification

- WalletWasabi.Fluent/ViewModels/Wallets/Send/ChangeAvoidanceSuggestionViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Send/PrivacySuggestionsFlyoutViewModel.cs
- WalletWasabi.Fluent/Views/Wallets/Send/ChangeAvoidanceSuggestionControl.axaml
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/7861
https://github.com/zkSNACKs/WalletWasabi/issues/7861#issuecomment-1447999168:
> We discussed this with @molnard. If the BnB found a solution with the same amount, only that one will be suggested. And also the text should be something more proper.
In [this commit](https://github.com/zkSNACKs/WalletWasabi/commit/baed8d6875440e9e6a2c65c2e9a75dc30c2262a6) I moved a similar check to have everything in the same place.
I don't know how to test it, review it carefully.
> [VDG] Fix less option sends the same amount

- WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionPreviewViewModel.cs
- WalletWasabi.Tests/UnitTests/Transactions/TransactionFactoryTests.cs
- WalletWasabi/Blockchain/TransactionBuilding/BuildTransactionResult.cs
- WalletWasabi/Blockchain/Transactions/TransactionFactory.cs
- WalletWasabi/Wallets/Wallet.cs
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/9377
On **master**:
0. Create an address labeled "First". Send 50 USD to wallet (from other client).
1. Ctrl+C+D.
2. Select 1 coin, click Send selected coins.
3. Enter "First" address.
4. Enter label "Random".
5. Cancel transaction.
6. Ctrl+C+D.
See that the coin now has "First" and "Random" labels. Restarting the Wallet solves this issue as it's all in memory.
**Additional problem**: If you create a new address labeled "Second", and want to self spend, if you give a recepient label, e.g: "Test", but cancel the transaction, "Test" will appear next to "Second" as a label in the Unused Receive Addresses tab.
If you do this a more than once, you can stack up unused Labels. If you eventually send the transaction, all the unused labels will …
> Change HdPubKey Labels after Transaction is sent

- WalletWasabi/WabiSabi/Client/Output.cs
The `Output` class implements `IEqualityComparer<Output>`. It seems to me that the author of the class wanted to implement `IEquatable<Output>` instead. 
This pull request makes `Output` a record which is a natural way to implement the `IEquatable` interface.
> Make Output a record

- WalletWasabi.Tests/UnitTests/WabiSabi/Integration/Participant.cs
- WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiHttpApiIntegrationTests.cs
- WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
- WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
- WalletWasabi/WabiSabi/Client/CoinJoinTracker.cs
- WalletWasabi/WabiSabi/Client/CoinJoinTrackerFactory.cs
- WalletWasabi/Wallets/IWallet.cs
- WalletWasabi/Wallets/Wallet.cs
Fixes: #10391
Built on top of https://github.com/zkSNACKs/WalletWasabi/pull/10403
The idea here is to only select coins in `CoinJoinClient` after we found a round.
So we are selecting from a more up-to-date list of coins.
> Use Func<> to get up-to-date coin candidates in CoinJoinClient

- WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
Discovered while looking into #10155.
Issue introduced in #10400 so this PR does not help with #10155.
This line https://github.com/zkSNACKs/WalletWasabi/blob/e12945e8c70b9b8ce85c1a9c5e9245adf7d265ef/WalletWasabi/WabiSabi/Client/CoinJoinManager.cs#L53 throws the `InvalidOperationException` exception when `CoinJoinClientStates` is empty.
Log:
```
Exception type: System.InvalidOperationException
Message: Sequence contains no elements
Stack Trace:    at System.Linq.ThrowHelper.ThrowNoElementsException()
at System.Linq.Enumerable.MaxBy[TSource,TKey](IEnumerable`1 source, Func`2 keySelector, IComparer`1 comparer)
at System.Linq.Enumerable.MaxBy[TSource,TKey](IEnumerable`1 source, Func`2 keySelector)
at WalletWasabi.WabiSabi.Client.CoinJoinManager.get_HighestCoinJoinClientState() in …
```
> Exception when closing the wallet fast

- WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
Edit:
~The idea here is to break the `WaitForRoundAsync` call, which can wait for a long time as described in the issue.~
> The economy profile could wait for a coinjoin hours/days or even a week according to the user's selection. During this period, coins could confirm, got unbanned, or generally change state.
~By breaking out of the `WaitForRoundAsync` with an `OperationCancelledException`, we force the `CoinJoinManager` to re-build the `CoinJoinTracker` class,
and more importantly to update the coin candidates.~
Just don't wait indefinitely.
This can be still useful IMO.
> Don't wait indefinitely for a Round

- WalletWasabi/Exceptions/CoinJoinClientException.cs
- WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
- WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
- WalletWasabi/WabiSabi/Client/RoundStateAwaiters/NoCoinsToMixException.cs
- WalletWasabi/Wallets/IWallet.cs
- WalletWasabi/Wallets/Wallet.cs
Idea come from @molnard 
What this PR tries to achieve:
Since waiting for a round can take some time, this PR runs a couple of sanity checks before AND after we find a round.
Sanity checks:
- Wallet got into the Send workflow while waiting
- Wallet balance fall below the `PlebStop` while waiting
- Backend become unresponsive
- Wallet become fully private meanwhile (not sure how could this happen)
This PR also adds a new exception called `CoinJoinClientException`, which is thrown by the sanity checks.
This exception can be used to make `NoCoinsToMixException` useless. So that's got removed.
> Sanity checks before and after we found a round

- WalletWasabi.Backend/README.md
dead link
it was removed 4c95e03e75fe0736f52f58089ce237201253216a
> remove backend deployment instructions link from backend README

- Contrib/WalletDiagnostic/common.fsx
The model on master gives an `int`, but big amount need a `double` (or at least a `long` but IDK ho to do that).
> Fix Common.fsx script for big amount values

- WalletWasabi.Fluent/ViewModels/CoinJoinProfiles/PrivateCoinJoinProfileViewModel.cs
This PR reduces the `MaxAnonScore` of `PrivateCoinJoinProfile` from 100 to 60.  
It covers both ideas mentioned in #10462:
> - lower the privacy scores of Maximize Privacy profile, it's a terrible overkill
> - Reduce the impact of randomness
Old wallets with `PrivacyProfile` selected would now see that they have a `Custom` profile if their AS is between 61 and 100, but nothing would change for them.
I didn't implement retro-compatibility (set `AnonScoreTarget` (AST) lower for old wallets with `PrivacyProfile` selected) in case of a NACK because there are several things to add. Still, if it's preferred to have retro-compatibility, I will add the following behavior, so please give your opinion in the comments:
- Add the name of the `CoinJoinProfile` selected to the wallet json file
- While …
> Reduce MaxAnonScore of PrivateCoinJoinProfile for new wallets

- WalletWasabi.Tests/UnitTests/WabiSabi/Integration/Participant.cs
- WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiHttpApiIntegrationTests.cs
- WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
- WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
- WalletWasabi/WabiSabi/Client/CoinJoinTracker.cs
- WalletWasabi/WabiSabi/Client/CoinJoinTrackerFactory.cs
- WalletWasabi/Wallets/IWallet.cs
- WalletWasabi/Wallets/Wallet.cs
Changing the `IWallet` breaks the implementation of others.
`GetCoinsCandidate` changed here: #10406 c3e05c420548273e1ada1b34f11411cb297829c9
`IsWalletPrivate` changed here: #10441 631a0c79826b2cf5626fd8ae8bf2968b30b0ea7f
> Revert breaking changes in IWallet interface

- WalletWasabi.Fluent/ViewModels/CoinControl/CoinSelectorDataGridSource.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Advanced/WalletCoins/WalletCoinsViewModel.cs
- WalletWasabi.Fluent/Views/CoinControl/Core/Headers/AnonymityScoreHeaderView.axaml
- WalletWasabi.Fluent/Views/Wallets/Advanced/WalletCoins/Columns/AnonymitySetHeaderView.axaml
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/9560
Simply use initials instead. ToolTip says the full title.
> [VDG] do not use same icon for coinjoin indicator and anonymity score indicator

- WalletWasabi.Fluent/Helpers/TransactionHelpers.cs
Fixes: https://github.com/zkSNACKs/WalletWasabi/issues/10513
~From the top of my head I went with the first 5 character of the txid as the initial name for the PSBT file.~
~Feel free to suggest otherwise.~
> Use the TXID as the initial file name for PSBT

- WalletWasabi.Daemon/ArgumentHelpers.cs
- WalletWasabi.Daemon/Config.cs
- WalletWasabi.Daemon/README.md
- WalletWasabi.Daemon/WasabiAppBuilder.cs
This PR allows to specify one or more wallets to be opened automatically by the daemon after starting. For example:
```
$ ./wasabi.daemon --wallet:LucasWallet
```
Or many wallets separated by comma
```
$ ./wasabi.daemon --wallet:LucasWallet,DavidWallet,BalazzWallet
```
This is required to do things like:
* Start wallet automatically when computer starts,
* Specify wallet in the request path #10522 or,
* Implement `--coinjointo=`
> Start wallets automatically after daemon starts

- WalletWasabi.Daemon/Rpc/WasabiJsonRpcService.cs
- WalletWasabi.Tests/RpcTests.cs
- WalletWasabi/Rpc/JsonRpcInitializationAttribute.cs
- WalletWasabi/Rpc/JsonRpcMethodAttribute.cs
- WalletWasabi/Rpc/JsonRpcMethodMetadata.cs
- WalletWasabi/Rpc/JsonRpcRequestHandler.cs
- WalletWasabi/Rpc/JsonRpcServer.cs
- WalletWasabi/Rpc/JsonRpcService.cs
This PR allows to specify the wallet to use in the url path. 
```bash
curl -s
\ --data-binary '{"jsonrpc":"2.0", "id":"curltext", "method":"listcoins", "params":[]}' 
\ -H 'content-type: text/plain;'
\ 'http://127.0.0.1:37128/MyWallet'
```
Before it was required to use two calls: `SelectWallet` first and then the wanted method.
> Specify wallet in the request path

- WalletWasabi.Fluent/ViewModels/AddWallet/Create/RecoveryWordsViewModel.cs
Having a comma is non-standard; see #10523 
I also agree with the other point of #10523:
> The recovery words remain in the clipboard, which is risky.
And could make it in a following PR, but I believe that removing the commas shouldn't be controversial at all; hence I prefer to do it in 2 PRs.
> Remove comma copy recovery words

- README.md
I guess it was mistake to link to the docs about the technical overview of wasabi which will be removed maybe. https://github.com/zkSNACKs/WasabiDoc/pull/1417
> [Trivial] Correct link for API

- WalletWasabi.Tests/UnitTests/WabiSabi/Client/CoinJoinCoinSelectionTests.cs
- WalletWasabi/WabiSabi/Client/CoinJoinCoinSelector.cs
- WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
Fixes: #10521
It got messed up in https://github.com/zkSNACKs/WalletWasabi/pull/10441
Previously:
We notified the `MusicBox` about the `PlebStop`, but right after that, we overwrote the `MusicBox` status and the user couldn't override the `PlebStop`.
With this:
User get to decide if he wants to override the PlebStop or not. Just as before my mistake.
Please test this PR and look out for edge cases.
> Fix CjManager Notification flow

- WalletWasabi.Fluent/ViewModels/Dialogs/AddressEntryDialogViewModel.cs
- WalletWasabi.Fluent/ViewModels/Dialogs/ShowQrCameraDialogViewModel.cs
- WalletWasabi.Fluent/ViewModels/MainViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Advanced/WalletCoins/WalletCoinsViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Send/SendViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModel.cs
No idea why no constructor for `ShowQrCameraDialogViewModel` is generated automatically while making it private, but keeping it public there's an error, so I ended up with a public constructor taking `UiContext`.
Required to fix #10479.
> Fixed view model constructors according guidelines

- WalletWasabi.Tests/Helpers/WabiSabiFactory.cs
- WalletWasabi.Tests/UnitTests/WabiSabi/Client/CoinJoinClientTests.cs
- WalletWasabi.Tests/UnitTests/WabiSabi/Client/CoinJoinCoinSelectionTests.cs
- WalletWasabi.Tests/UnitTests/WabiSabi/Integration/Participant.cs
- WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
- WalletWasabi/WabiSabi/Client/CoinJoinCoinSelector.cs
- WalletWasabi/WabiSabi/Client/CoinJoinTrackerFactory.cs
- WalletWasabi/WabiSabi/Client/OutputProvider.cs
This PR contain two commits that simplify the `CoinJoinClient` interface and improve the code many ways. Extracting the logic for outputs generation allows us to implement a much cleaner solution for payments in coinjoins because a PIC is not  other thing that providing and registering the right output in a coinjoin round.
The PR should be reviewed commit by commit. Each commit contains the explanation of what and why the changes are for.
> [Payment in Coinjoin] Output provider

- WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryViewModel.cs
Fixes the issue when the selection doesn't work from the history search result due to the item is already selected.
https://github.com/zkSNACKs/WalletWasabi/pull/10721#issuecomment-1551244708
> [VDG] Improve history selection from SearchBar

- WalletWasabi/WabiSabi/Client/AmountDecomposer.cs
- Credit goes to @turbolay for the idea here: https://github.com/zkSNACKs/WalletWasabi/issues/10708#issuecomment-1553033121
- Equivalent commit in Sake: https://github.com/nopara73/Sake/commit/a6cc7c3a65f69623bbfbfcfdb48589f4f0780c7a
- This improves upon (probably a lot) on https://github.com/zkSNACKs/WalletWasabi/issues/10708#issuecomment-1553033121
- This also solves a user's issue I've been hunting for 3 weeks at this point: his anonymity score went down after creating a non-standard (not the largest one, mind you!) output. Although I've been hunting it for 3 weeks, this information came to light today. (Thanks for @SuperJMN's PRs: https://github.com/zkSNACKs/WalletWasabi/pull/10680, https://github.com/zkSNACKs/WalletWasabi/pull/10679)
**So what does this PR do?** It changes preference …
> Reduce Non-Standard Changes

- .github/workflows/codeql.yml
Fixes: https://github.com/zkSNACKs/WalletWasabi/issues/10514
This is GitHub's own code and security analyzer utility - that's why I think we should add this. It is collecting data and vulns from all the projects on GitHub worldwide - so it is not a typical analyzer but more. It is available under the security tab of the repository.
> Add Code scanning

- WalletWasabi.Tests/Helpers/MempoolInfoGenerator.cs
- WalletWasabi.Tests/UnitTests/AllFeeEstimateTests.cs
- WalletWasabi/Extensions/RPCClientExtensions.cs
Here we calculate the minimum fee rate needed to be in the top 200Mb of the mempool.
It is tested with real world data extracted from mempool.space (May 8th) and the result (30s/b) seems reasonable.
> Calculate the min feerate

- WalletWasabi/WabiSabi/Client/AmountDecomposer.cs
Nobrainer. Although we do sort orderedCandidates by change first, later on `costTolerance` logic would still prefer them. 
https://github.com/nopara73/Sake/commit/639295b6b44f4904843c1b1311090bf13f75f3a0
> If there are changeless candidates, don't even consider ones with change

- .editorconfig
This rule has wasted time for contributors like Yoh, Onvej, and myself, on many PRs: #10684, #10727, #10715, and did the same for reviewers and maintainers.
> [Trivial] Remove sort System using directives rule

- WalletWasabi/Blockchain/Transactions/TransactionHistoryBuilder.cs
A leftover of #10504. The `address` is not used.
> [Trivial] Remove unused variable

- WalletWasabi/WabiSabi/Client/AmountDecomposer.cs
This PR builds on top of https://github.com/zkSNACKs/WalletWasabi/pull/10787 and I'll keep this as a draft until that is merged, so you don't get confused by the diff.
Sake equivalence: https://github.com/nopara73/Sake/pull/31
In extreme cases: when one cannot avoid creating a change output, there's only one decomposition to choose from. The solution proposed here involves introducing more decompositions via an intermediary pre-decomposition algorithm.
To put things into perspective, we currently use two decomposition algorithms which we'll refer to as: Naive decomp and Lucas decomp. While the Naive decomp is capable of generating only one decomp, the Lucas decomp generates decomps only when it can avoid creating change outputs.
However, there are scenarios (like when a user introduces …
> Introducing Pre-Decompositions to Enhance Decomposition Algorithms

- WalletWasabi/WabiSabi/Client/AmountDecomposer.cs
Sake equivalence: https://github.com/nopara73/Sake/pull/33
ToDo: @turbolay @adamPetho can you do quick testing? (regtest, testnet, unit test, whatever you find the quickest)  
It needs to be tested if it works, namely what we're interested in is if there's any conditions outside of the decomposer that would limit our outputs to 8. There shouldn't be, but better to be safe than sorry. So if you succeeded to generate a regtest/testnet/unit test coinjoin with 9 or 10 outputs, then you're good. Note: you have to be big whale for that. If you're looking to test on testnet you may need @MaxHillebrand's whale coins for that. In Sake it does work, but I need slightly more guarantees.
> Increase max out from 8 to 10

- WalletWasabi.Tests/UnitTests/WabiSabi/Client/AmountDecomposerTests.cs
- WalletWasabi/WabiSabi/Backend/Rounds/RoundParameters.cs
- WalletWasabi/WabiSabi/Client/AmountDecomposer.cs
- WalletWasabi/WabiSabi/Client/DenominationBuilder.cs
- WalletWasabi/WabiSabi/Client/OutputProvider.cs
This is a preparation PR for https://github.com/zkSNACKs/WalletWasabi/pull/10830 to eventually resolve https://github.com/zkSNACKs/WalletWasabi/issues/10759
This does not change the behavior at all and is safe.
- The main thing is I took `CreateDenominations` out of `AmountDecomposer` to `DenominationBuilder`.
- I pushed `IsTaprootAllowed` calculation to the `RoundParameters`
- I pushed the min economic output amount reasonability calculation into `RoundParameters`: `CalculateMinReasonableOutputAmount`
> Decouple stuff from Amount Decomposer

- WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/PrivacyControlTileViewModel.cs
- WalletWasabi.Fluent/Views/Wallets/Home/Tiles/PrivacyControlTileView.axaml
- WalletWasabi.Fluent/Views/Wallets/Home/Tiles/PrivacyRing/PrivacyRingDetailsView.axaml
> [VDG] Changed format of copied privacy balance

- WalletWasabi.Fluent/Controls/CurrencyEntryBox.axaml.cs
- WalletWasabi.Fluent/Helpers/TextHelpers.cs
fixes https://github.com/zkSNACKs/WalletWasabi/issues/10855
> [VDG] CurrencyEntryBox - do not allow space

- WalletWasabi.Daemon/WalletWasabi.Daemon.csproj
- WalletWasabi.Packager/Program.cs
- WalletWasabi/Helpers/Constants.cs
Addresses
> Lucas Ontivero 3 days ago I think the next release is not shipping the daemon. It will be there but the packager doesn't remaned it as wassabeed as i think it should
from https://github.com/orgs/zkSNACKs/projects/27/views/1
```bash
cd C:\WasabiWallet\WalletWasabi\WalletWasabi.Packager
dotnet restore && dotnet build && dotnet run # or: dotnet restore && dotnet build && dotnet run -- --onlybinaries
cd C:\WalletWasabi\WalletWasabi.Fluent.Desktop\bin\dist\win7-x64
wassabeed.exe
```
<s>I'm not exactly why this leads to starting the Daemon process but not waiting for user input (pressing CTRL+C). I tried to add `Console.Read()` command but it did not help. Investigating. Maybe I'm doing something trivially wrong.</s> Fixed by bc2a139f643d9b3610ab6b31709fcc78f9ae433d.
Help is …
> Packager: Rename Daemon + Fix for `Release` mode

- WalletWasabi.Fluent/Icons/Icons.axaml
- WalletWasabi.Fluent/ViewModels/Wallets/Home/History/Details/TransactionDetailsViewModel.cs
- WalletWasabi.Fluent/Views/Wallets/Home/History/Details/TransactionDetailsView.axaml
- WalletWasabi/Blockchain/Transactions/Summary/ForeignOutput.cs
- WalletWasabi/Blockchain/Transactions/Summary/Output.cs
- WalletWasabi/Blockchain/Transactions/Summary/OwnOutput.cs
- WalletWasabi/Blockchain/Transactions/TransactionHistoryBuilder.cs
- WalletWasabi/Blockchain/Transactions/TransactionSummary.cs
This adds the destination address to the transaction summary.
I have calculated the destionation address by sorting by amount and taking the address of the first output. 
If this algorithm is incorrect, please tell me the correct way to do so :)
Also, I took the freedom to choose the icon 
Related: #8662, [#9014](https://github.com/zkSNACKs/WalletWasabi/issues/9014)
> [VDG] Add destination address to transaction summary

- WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionSummaryViewModel.cs
- WalletWasabi.Fluent/Views/Wallets/Send/TransactionSummary.axaml
The Transaction Preview dialog (when sending) is full of text and not user friendly imo.
This is a small PR with minimal effort to simplify the text and make the dialog less cluttered.
Master:
PR:
> [VDG][Trivial] Simplify text of Preview Transaction dialog

- WalletWasabi/Wallets/Wallet.cs
See https://github.com/zkSNACKs/WalletWasabi/issues/10948#issuecomment-1610243376
> TurboSync: Remove an extra `while`

- WalletWasabi/WabiSabi/Backend/Models/WabiSabiProtocolErrorCode.cs
This PR removes `WrongOwnershipProof` from the list of cheating reason.
> [WabiSabi] Do not ban inputs without valid ownership proof

- WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterInputFailureTests.cs
- WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterInputToBlameRoundTests.cs
- WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiHttpApiIntegrationTests.cs
- WalletWasabi/WabiSabi/Backend/Rounds/Arena.Partial.cs
- WalletWasabi/WabiSabi/Models/MultipartyTransaction/ConstructionState.cs
This PR is for checking ownership proofs before other acceptance criteria in order to act as an authentication mechanism for input registration.
> [WabiSabi] Verify ownership proof before any other policies

- WalletWasabi/Affiliation/AffiliateServerStatusUpdater.cs
- WalletWasabi/Extensions/EventHandlerExtensions.cs
- WalletWasabi/WabiSabi/Backend/Banning/CoinVerifier.cs
Fixes: [#10849](https://github.com/zkSNACKs/WalletWasabi/issues/10849)
This PR reduces the log levels of several common errors in the backend log.
> Whatever is not an error that prevents the coordinator to work properly should be a warning. Errors are suppose to be events that need our immediate attention and then the team should be notified on slack or in any other channel to take actions.
Reducing the severity from Error to Warning in the logs mean that we will still log them but they won't be sent to maintainers (if that will be introduced).
> Reduce log levels of common errors in the Log

- WalletWasabi/Blockchain/Transactions/TransactionHistoryBuilder.cs
Fixes #10916
The comments are self-explanatory.
I can remove them from the code before merging, even if I think they help.
I believe this algo covers the standard cases correctly.
Sometimes if users make weird transactions, it might be incorrect, but I believe we don't care, as there is no way to know the user's intention anyway.
> Improve destination addresses algorithm

- WalletWasabi.Tests/UnitTests/AllFeeEstimateTests.cs
- WalletWasabi/Extensions/RPCClientExtensions.cs
In case we lose the mempool the fee estimation algorithm will not use the fee rate histogram.
> Prevent using the mempool info too early

- WalletWasabi.Backend/Controllers/BatchController.cs
- WalletWasabi.Backend/Controllers/WabiSabiController.cs
- WalletWasabi.Backend/Global.cs
- WalletWasabi.Backend/Startup.cs
- WalletWasabi.Tests/UnitTests/WabiSabi/Backend/CoinJoinMempoolManagerTests.cs
- WalletWasabi.Tests/UnitTests/WabiSabi/Client/ArenaClientTests.cs
- WalletWasabi.Tests/UnitTests/WabiSabi/Client/BobClientTests.cs
- WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiApiApplicationFactory.cs
- WalletWasabi/BitcoinCore/Mempool/IMempoolMirror.cs
- WalletWasabi/BitcoinCore/Mempool/MempoolMirror.cs
- WalletWasabi/CoinJoin/Client/CoinJoinProcessor.cs
- WalletWasabi/WabiSabi/Backend/CoinJoinMempoolManager.cs
Alternative to https://github.com/zkSNACKs/WalletWasabi/pull/10924
This solution uses the same feature what we had and still have for WW1. From time to time (30 secs) there is a sync request that contains all the unconfirmed CJ hashes. The list was not containing WW2 coinjoins, with this PR I added them. 
No change on the client side.
The concept is to make the clients know about the coinjoins in the coordinator's mempool. 
There is a difference to https://github.com/zkSNACKs/WalletWasabi/pull/10924 - this PR does not force the transactionprocessor to make the CJ replace double spend tx. In that case, the CJ will be rejected. 
Fixes: https://github.com/zkSNACKs/WalletWasabi/issues/10629
> Get unconfirmed CoinJoins from the coordinator

- WalletWasabi.Fluent/ViewModels/Wallets/Receive/AddressViewModel.cs
Fixes label sorting in **Addresses awaiting payment** (Receive) by using the correct (IComparable) data type.
Fixes #11010
> [VDG] [Trivial] Fix label sorting

- WalletWasabi.Fluent/ViewModels/WalletManagerViewModel.cs
This PR:
Selects the correct wallet when a notification is clicked.
Without this PR: 
The NavBar doesn't update its selection to reflect the correct wallet when a notification of a transaction is clicked.
> [VDG] Select correct wallet when clicking notification

- WalletWasabi/Wallets/Wallet.cs
the wallet name is part of the starting wallet log message
`INFO	WalletManager.StartWalletAsync (167)	Starting wallet 'WalletName'...`
with this PR the wallet name is also in the wallet fully synced message 
`INFO	Wallet.PerformFinalSynchronizationAsync (281)	Wallet 'WalletName' is fully synchronized.`
currently, it's annoying/hard to tell when loading multiple wallets
> add walletname to fully synced log message

- WalletWasabi.Fluent/Views/Wallets/Send/TransactionSummary.axaml
As discussed in UX meeting, we use capitals everywhere so for consistency we should do the same here.
> [VDG] Transaction preview - use capital initials

- WalletWasabi/Blockchain/BlockFilters/FilterProcessor.cs
I found this during review of #11046. Given how complex that block filter processing is, I find it useful to remove unnecessary complexities.
> `FilterProcessor`: Remove lock

- .github/workflows/auto-add-to-projcet.yml
When an issue gets reopened we need to deal with it again, so should be added to the RR board again.
> add issues to project board on reopening too

- WalletWasabi.Fluent.Generators/WalletWasabi.Fluent.Generators.csproj
Should fix warnings like https://dev.azure.com/zkSNACKs/Wasabi/_build/results?buildId=102319&view=logs&j=0da5d1d9-276d-5173-c4c4-9d4d4ed14fdb&t=fa4a47f7-906d-5276-1b56-2e609eec1e77&l=20
> Add `EnforceExtendedAnalyzerRules` to `WalletWasabi.Fluent.Generators` project

- WalletWasabi.Fluent/Models/Transactions/PrivacySuggestionsModel.cs
- WalletWasabi.Fluent/Models/Transactions/PrivacyWarning.cs
- WalletWasabi.Fluent/Views/Wallets/Send/PrivacyWarningsView.axaml
- WalletWasabi/Blockchain/TransactionBuilding/BuildTransactionResult.cs
As spending coinjoining coins causes issues for both client and backend, I think this warning makes a lot of sense.
Issue: similar to https://github.com/zkSNACKs/WalletWasabi/issues/11013, the suggestion doesn't get updated. So user can see the warning while coinjoin stopped in the meantime.
> [VDG] PrivacySuggestions: add warning for spending coinjoining coins

- WalletWasabi/Wallets/Wallet.cs
I found this during review of #11046. Given how complex that block filter processing is, I find it useful to remove unnecessary complexities.
> `Wallet`: Remove `NewBlockProcessed` event

- WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
Currently start of CoinJoinClient is only logged in debug while stop is always logged.
With this PR: always log start and stop of CoinJoinClient.
```
2023-07-21 11:23:42.061 [30] INFO	CoinJoinManager.HandleCoinJoinCommandsAsync (230)	Wallet (Testint): CoinJoinClient started.
2023-07-21 11:23:42.061 [30] DEBUG	CoinJoinManager.HandleCoinJoinCommandsAsync (231)	Wallet (Testint): StopWhenAllMixed:'False' OverridePlebStop:'False'.
2023-07-21 11:23:56.636 [25] INFO	CoinJoinManager.HandleCoinJoinFinalizationAsync (460)	Wallet (Testint): CoinJoinClient stopped.
```
> Always log that CoinJoinClient starts

- WalletWasabi.Daemon/Global.cs
- WalletWasabi/WabiSabi/Client/Banning/CoinPrison.cs
- WalletWasabi/WabiSabi/Client/Banning/PrisonedCoinRecord.cs
- WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
- WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
- WalletWasabi/WabiSabi/Client/CoinJoinProgressEvents/CoinBanned.cs
- WalletWasabi/WabiSabi/Client/CoinJoinTracker.cs
Similar to #10957
This approach adds `CoinPrison` to `CoinJoinManager`, so we can get and call `CoinPrison` directly in `CoinJoinManager` for banning.
Also introduces an even subscription in `Global` to `WalletManager` which loads in banned state of coins. This function can later on be deleted when we get rid of `SmartCoin.IsBanned`.
> Store banned coins in file

- WalletWasabi/Blockchain/TransactionProcessing/TransactionProcessor.cs
This makes it easier to mock `TransactionProcessor` for `WalletWasabi/Wallets/WalletFilterProcessor.cs` in #11065.
> `TransactionProcessor`: Remove guards

- WalletWasabi.Fluent/Views/Wallets/Send/PrivacyWarningsView.axaml
They are less emphasized so won't take the user's attention, rather they will focus immediately on the suggestion's description.
> [VDG] Privacy Warning - decerase the opacity of icons of the suggestions

- WalletWasabi.Fluent/ViewModels/CoinControl/CoinControlLabelComparer.cs
- WalletWasabi.Fluent/ViewModels/CoinControl/CoinSelectorDataGridSource.cs
Implements the correct sorting algorithm for Pockets in Coin Control screen.
Fixes #11085
> [VDG] Fix sorting for non-private pockets

- WalletWasabi.Fluent/Helpers/CoinPocketHelper.cs
For consistency in wording.
Coins is used everywhere else. Like at suggestions.
This is the text here, which user sees at coin control
I can rename `Private**Funds**Text` and all related as well if desired.
> [VDG] [trivial] rename Funds to Coins for Pocket

- WalletWasabi.Fluent/Views/Wallets/Send/PrivacyWarningsView.axaml
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/11068
There's multiple ways how to approach this, I went with first describing the consequence (as mentioned in the issue) and, if applicable, also mention what the user should do.
See changes for full text of tooltips
Ideally, the tooltips could be different for certain scenario's for example user has "interlinks labels" but is not able to do label management and another tooltip text for scenario where user "interlinks labels" but is able to do label management. I'm not sure if it's possible, if so maybe a follow up improvement.
Anyway, I've made them general enough for all scenarios
[Screencast](https://github.com/zkSNACKs/WalletWasabi/assets/93143998/0ff4a508-420e-4caf-aeb0-ce6ab2d1b0e1)
> [VDG] PrivacySuggestions: ToolTip with consequences and explanation

- WalletWasabi.Fluent/Models/Transactions/PrivacyWarning.cs
- WalletWasabi.Fluent/Views/Wallets/Send/PrivacyWarningsView.axaml
- Change `UnconfirmedFundsWarning.Severity` to `Info`
- Change corresponding icon
- Fixes #11087
> [VDG] Fix unconfirmed coins warning

- WalletWasabi.Fluent/ViewModels/Wallets/Home/History/Details/TransactionDetailsViewModel.cs
Fixes visibility not being updated in Transaction Summary for Confirmation Time and Labels.
https://github.com/zkSNACKs/WalletWasabi/pull/11092#issuecomment-1653077734
> [VDG] Notify property updates for Confirmation Time and Labels

- WalletWasabi/BitcoinP2p/P2pBehavior.cs
Related: #11119 
In our `TransactionStore` we have witness-stripped segwit transactions (txs in pre-segwit-compatible serialization format) what means we really don't know the real size of them. Given the weight discount only applies to witness data, calling `GetVirtualSize` against these transactions make no sense and will return the real size in bytes compatible to the pre-segwit size calculation (where no virtual byte/virtual size existed).
Peers were sending us the stripped transactions because that's how we were requesting them (bug). This PR changes that and starts requesting the full transactions (MSG_WTX). Additionally we do not process txs received via p2p without witness data (i didn't see them coming after this change so, it should never happen but just in case)
What to do with …
> Request tx with witness data and ignore txs without it.

- WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionPreviewViewModel.cs
Cleaner version of https://github.com/zkSNACKs/WalletWasabi/pull/11082
The privacy suggestion calculation was not cancelled when a new one had to be made after changin the transaction in preview.
> Cancel previous task before running new privacy calculation

- WalletWasabi.Fluent/Views/Wallets/Home/History/Details/TransactionDetailsView.axaml
Fixes this double separator issue noticed by @turbolay.
> [Trivial] Hide TXID separator if tx is not confirmed

- WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
Fixes #11072 
As always, with this part of the codebase, not sure if this breaks something else.
The idea is that if we're L206, we passed L191. Hence, the `NoCoinsEligibleToMix` message is factually correct at this point (we have some non-private coins, but they are not eligible for coinjoin), but not `AllCoinsPrivate` (because we have some non-private coins).
> Use NoCoinsEligibleToMix instead of AllCoinsPrivate if all candidates are private

- WalletWasabi.Tests/UnitTests/Tor/TorSettingsTests.cs
- WalletWasabi/Tor/TorSettings.cs
Fixes #11117
Adds `TruncateLogFile` as suggested here https://github.com/zkSNACKs/WalletWasabi/issues/11117#issuecomment-1659145141. 
The proposed behavior seems reasonable as it *truncates `TorLogs.txt` when we start Tor.* That does not necessarily mean that we delete `TorLogs.txt` every time that WW is started. 
The actual behavior depends on user setting *Terminate Tor when Wasabi shuts down*. If is is off, then we truncate `TorLogs.txt` with every WW start. If the setting is off, then we effectively truncate `TorLogs.txt` with every machine reboot[^1] because Tor process is not stopped.
Given contributed `TorLogs.txt` sizes reported by various users, it seems this solution is actually good. 
[^1]: I would find it risky to delete `TorLogs.txt` while Tor process is running.
> Truncate `TorLogs.txt` when Tor starts

- WalletWasabi.Fluent/ViewModels/Wallets/Home/History/Features/CancelTransactionDialogViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Home/History/Features/SpeedUpTransactionDialogViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItems/TransactionHistoryItemViewModel.cs
This improves UX when the transaction is confirmed while the dialog is open and the broadcast fails due to a confirmed transaction.
Fixes #11146.
Fixes #11152.
> [VDG] Go back when transaction is confirmed

- WalletWasabi/BitcoinP2p/P2pBehavior.cs
Cherry picked first commit from https://github.com/zkSNACKs/WalletWasabi/pull/11205 because the second and the third commit there were accidental.
> Get txs with witness data

- WalletWasabi.Fluent/ViewModels/Wallets/Home/History/Features/SpeedUpTransactionDialogViewModel.cs
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/11154
Notes:
1. This is a super minor issue that will never happen in production, so it isn't necessary for the release, although I see no reason why not to merge it.
2. There's also another super minor, albeit larger issue than this, which is what we show when both the sender and the receiver are paying some amount for the speedup; I'll leave that bug in there up for grabs.
> Refine detection of who's paying

- WalletWasabi.Tests/IntegrationTests/ExternalApiTests.cs
- WalletWasabi/WebClients/CoinGecko/CoinGeckoExchangeRate.cs
- WalletWasabi/WebClients/CoinGecko/CoinGeckoExchangeRateProvider.cs
- WalletWasabi/WebClients/ExchangeRateProviders.cs
This provider was removed under the assumption that i was not working but the real problem was our requests were blocked by cloudflare. Adding a `User-Agent` fixed the problem.
> Reintroduce CoinGecko rate provider

- WalletWasabi.Fluent/Controls/QuestionControl.axaml
- WalletWasabi.Fluent/Controls/QuestionControl.axaml.cs
- WalletWasabi.Fluent/Views/Wallets/Home/History/Features/CancelTransactionDialogView.axaml
- WalletWasabi.Fluent/Views/Wallets/Home/History/Features/SpeedUpTransactionDialogView.axaml
- WalletWasabi/Blockchain/TransactionBuilding/TransactionModifierWalletExtensions.cs
- WalletWasabi/Services/SingleInstanceChecker.cs
This PR unifies the warning messages and makes them shorter, and also removes the awkward looking `Are you sure?` message under the amount.
I guess if we want we can make these dialogs smaller since there is a lot of empty space.
PR:
Master:
> [Trivial] Unify warning messages for the Cancel/Speed up dialogs

- WalletWasabi.Fluent/ViewModels/Wallets/Home/History/Features/CancelTransactionDialogViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Home/History/Features/SpeedUpTransactionDialogViewModel.cs
This makes the transaction lookup fail-safe. This lookup is needed to auto-close the dialog when the given transaction has been confirmed.
Fixes #11195
> [VDG] Speed-up / Cancel: Make transaction lookup fail-safe

- WalletWasabi.Fluent/Views/Wallets/Home/History/Details/TransactionDetailsView.axaml
it copies this format `2.00:00:00` and similar to the _Status_, it's not useful to copy it anyway
> [VDG] [trivial] remove CopyableContent from confirmation time

- WalletWasabi/Blockchain/TransactionOutputs/CoinsRegistry.cs
- WalletWasabi/Blockchain/TransactionProcessing/TransactionProcessor.cs
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/11134
Closes https://github.com/zkSNACKs/WalletWasabi/pull/11176
Closes https://github.com/zkSNACKs/WalletWasabi/pull/11214
If you guys have time to do more, then here are my recommendations:
> Fix SpentCoinsByOutPoint is not updated

- WalletWasabi.Backend/Controllers/BatchController.cs
This PR keeps the response for `synchronize` in the caches for 60 seconds. 
The response can be cached in all the intermediary http servers (cloudflare included).
The change also requires the following changes in the nginx configuration:
```
worker_processes  1;
pid	nginx.pid;
events {
worker_connections  1024;
}
http
{
proxy_cache_path cache-for-filters levels=1:2 keys_zone=filters_cache:10m max_size=10g inactive=2m use_temp_path=off;
server {
server_name 127.0.0.1;
listen 8888;
server_tokens off;
access_log nginx-access.log combined;
error_log  nginx-error.log warn;
location ~* /api/v4/btc/batch/synchronize {
proxy_cache filters_cache;
proxy_cache_use_stale error timeout http_500 http_502 http_503 http_504;
proxy_cache_lock on;
proxy_pass http://localhost:37127;
}
location ~* /api/ { …
```
> Cache slow `synchronize` response

- WalletWasabi.Fluent/Extensions/EnumerableExtension.cs
- WalletWasabi.Fluent/Models/Transactions/PrivacyItem.cs
- WalletWasabi.Fluent/Models/Transactions/PrivacySuggestion.cs
- WalletWasabi.Fluent/Models/Transactions/PrivacySuggestionsModel.cs
- WalletWasabi.Fluent/Models/Transactions/PrivacySuggestionsResult.cs
- WalletWasabi.Fluent/Models/Transactions/PrivacyWarning.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Send/PrivacySuggestionsFlyoutViewModel.cs
- Fixes #11031 
- Marked as draft because there is a hard to debug race deadlock that I haven't been able to fix yet, which stops the change avoidance suggestions from yielding, thus the flyout stays busy forever.
> [VDG] Change PrivacyWarnings to IAsyncEnumerable

- WalletWasabi.Fluent/ViewModels/Wallets/Send/FeeChartViewModel.cs
Potentially fixes https://github.com/zkSNACKs/WalletWasabi/issues/11206
> [VDG] Fee Chart - fix mid value

- WalletWasabi.Fluent/Behaviors/ContextFlyoutWorkaroundBehavior.cs
Fixes NullReferenceException exception in ContextFlyoutWorkaroundBehavior:
```
Exception type: System.NullReferenceException
Message: Object reference not set to an instance of an object.
Stack Trace:    at WalletWasabi.Fluent.Behaviors.ContextFlyoutWorkaroundBehavior.<OnAttached>b__1_7(EventHandler`1 handler) in WalletWasabi.Fluent\Behaviors\ContextFlyoutWorkaroundBehavior.cs:line 39
at System.Reactive.Disposables.AnonymousDisposable`1.Dispose() in /_/Rx.NET/Source/src/System.Reactive/Disposables/AnonymousDisposable.cs:line 74
at System.Reactive.Concurrency.Scheduler.<>c__75`1.<ScheduleAction>b__75_0(IScheduler _, ValueTuple`2 tuple) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/Scheduler.Simple.cs:line 66
at System.Reactive.Concurrency.SynchronizationContextScheduler.<>c__DisplayCl …
```
> [VDG] Fixes NullReferenceException exception in ContextFlyoutWorkaroundBehavior

- WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
see https://github.com/zkSNACKs/WalletWasabi/issues/11109
too many issues where `CoinJoinClient started` is incorrectly being logged. Those should be fixed first, then we can change this back to `LogInfo`.
I kept `CoinJoinClient stopped` purposely on `LogInfo`, as it is useful (for example when using daemon) when you stop it on purpose (and want to confirm it did) where as when starting CoinJoinClient you can notice that the CoinJoinClient started when you see related coinjoin logs coming in.
> temp fix: make `CoinJoinClient started` debug log level

- WalletWasabi.Backend/Startup.cs
- WalletWasabi.Tests/UnitTests/WabiSabi/Integration/Startup.cs
- WalletWasabi/Tor/Http/Extensions/HttpResponseMessageExtensions.cs
Client and server shared the same set of converters but not the exact set of json serialization settings. For that reason clients use PascalCase while server uses camelCase (except for the WabiSabi converters that are strict).
This change makes both sides to use the same ContractResolver so they both serialize using the same casing. This is effectively a breaking change that shouldn't affect us but can potentially affect others using our api.
> Use same json serialization settings on client and server

- WalletWasabi.Backend/wwwroot/index.html
- WalletWasabi/Helpers/Constants.cs
zkSNACKs high council postponed the release to the 21st of Aug.
I am reverting this to accidentally not deploying this to backends.
Reverts zkSNACKs/WalletWasabi#11237
> Revert "Bump version to v2.0.4"

- WalletWasabi.Packager/Program.cs
Close https://github.com/zkSNACKs/WalletWasabi/issues/11233
The debian package didn't include a started script for the deamon, what make it impossible to launch.
> Starter script for `wassabeed`

- WalletWasabi/Blockchain/BlockFilters/IndexBuilderService.cs
An alternative to #11239 and #11240 which replaces 
* AsyncLock with a simple lock
* Removes an RPC call from the critical section.
Closes https://github.com/zkSNACKs/MaintenanceVault/issues/295
Closes https://github.com/zkSNACKs/WalletWasabi/pull/11240
> `IndexBuilderService`: Remove `RpcClient.GetBlockHashAsync` from the critical section

- WalletWasabi.Tests/RegressionTests/CancelTests.cs
- WalletWasabi/Blockchain/Analysis/BlockchainAnalyzer.cs
If the blockchain analyzer encounters a cancellation transaction with foreign inputs - a technical impossibility but a logical possibility - or foreign outputs, then set its input anonsets to 0.
It may not comprehensively fix all the problems noted in https://github.com/zkSNACKs/WalletWasabi/issues/11226. However, it improves and closes https://github.com/zkSNACKs/WalletWasabi/issues/11226
After this PR, a new issue may be opened if there are still any problems.
> Cancellation TX to reset input AS

- WalletWasabi.Fluent/Models/Wallets/IWalletSettingsModel.cs
- WalletWasabi.Fluent/Models/Wallets/WalletRepository.cs
- WalletWasabi.Fluent/Models/Wallets/WalletSettingsModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/CoinJoinStateViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModel.cs
Fixes: https://github.com/zkSNACKs/WalletWasabi/issues/10944
> Option 2 is the best. Pause the auto cj right after the recovery is finished. In this way, the default will be kept true and the user can quickly start by pressing the play button.
https://github.com/zkSNACKs/WalletWasabi/issues/10944#issuecomment-1617770975
> Pause CJ after recovery

- WalletWasabi/Stores/BlockFilterSqliteStorage.cs
- WalletWasabi/Stores/IndexStore.cs
Fixes #11273 
This PR:
- Passes `CancellationToken` to `MigrateToSqliteNoLock` (even if it's not an `async` method) and checks at every iteration if it should `throw`
- Change conditions of `RunMigration` so migration will be relaunched in case of cancellation.
- Change `INSERT INTO` to `INSERT OR IGNORE INTO` to just ignore duplicate in DB and avoid inserting them again.
- Reduces the size of batches to make the process less error-prone.
> Make filter migration cancellable

- WalletWasabi.Backend/Controllers/BlockchainController.cs
- WalletWasabi.Backend/Controllers/OffchainController.cs
Caching these responses can relax the pressure against the coordinator
```
/api/v4/btc/blockchain/mempool-hashes min 0.000
/api/v4/btc/blockchain/mempool-hashes max 95.276
/api/v4/btc/blockchain/mempool-hashes avg 18.391639591808591325932565676
/api/v4/btc/Blockchain/filters min 0.000
/api/v4/btc/Blockchain/filters max 38.917
/api/v4/btc/Blockchain/filters avg 0.4782768565643298856235976577
```
> Cache big responses

- WalletWasabi.Fluent/Views/Wallets/Send/TransactionSummary.axaml
https://github.com/zkSNACKs/WalletWasabi/pull/11286#pullrequestreview-1578319580
The phrasing used to be "correct" but got removed https://github.com/zkSNACKs/WalletWasabi/commit/09f9eef3d0de3b68aa63902eb9721091bf0559d7
This is just a wording fix, to keep it trivial (and included into release?)
If OK, I can add tooltip with small explanation for this as well.
> [VDG] Preview Transaction: update confirmation time label text

- WalletWasabi.Tests/Helpers/WabiSabiFactory.cs
- WalletWasabi/Extensions/TimeSpanExtensions.cs
- WalletWasabi/WabiSabi/Backend/Rounds/RoundParameters.cs
- WalletWasabi/WabiSabi/Backend/WabiSabiConfig.cs
- WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
This PR is an alternative to https://github.com/zkSNACKs/WalletWasabi/pull/11141 consisting on 2 hardcoded delay values (0 seconds and 50 seconds).
> Hardcode delay before signing

- WalletWasabi/Blockchain/Keys/KeyManager.cs
I realized I forgot it while implementing `TurboSync`.
This is a clear bug because if I don't have the filters or there is a reorg but `TurboSyncHeight` is higher than `BestHeight`, it will cause the synchronization process to stop.
This PR also contains a small refactor of the function `SetMaxBestHeight`, as it's much more readable that way and doesn't change behavior.
> Fix: Add TurboSyncHeight reset to SetMaxBestHeight

- WalletWasabi.Backend/Global.cs
- WalletWasabi.Daemon/Global.cs
- WalletWasabi.Fluent/Services.cs
- WalletWasabi.Tests/IntegrationTests/BlockstreamInfoClientTests.cs
- WalletWasabi.Tests/IntegrationTests/P2pTests.cs
- WalletWasabi.Tests/RegressionTests/BuildTransactionReorgsTest.cs
- WalletWasabi.Tests/RegressionTests/BuildTransactionValidationsTest.cs
- WalletWasabi.Tests/RegressionTests/CancelTests.cs
- WalletWasabi.Tests/RegressionTests/FilterDownloaderTest.cs
- WalletWasabi.Tests/RegressionTests/ReceiveSpeedupTests.cs
- WalletWasabi.Tests/RegressionTests/ReorgTest.cs
- WalletWasabi.Tests/RegressionTests/ReplaceByFeeTxTest.cs
- WalletWasabi.Tests/RegressionTests/SelfSpendSpeedupTests.cs
- WalletWasabi.Tests/RegressionTests/SendSpeedupTests.cs
- WalletWasabi.Tests/RegressionTests/SendTests.cs
- WalletWasabi.Tests/RegressionTests/SpendUnconfirmedTxTests.cs
- WalletWasabi.Tests/RegressionTests/WalletTests.cs
- WalletWasabi.Tests/UnitTests/Wallet/WalletBuilder.cs
- WalletWasabi/Blockchain/Mempool/MempoolService.cs
- WalletWasabi/Blockchain/TransactionBroadcasting/TransactionBroadcaster.cs
- WalletWasabi/Services/WasabiSynchronizer.cs
- WalletWasabi/Tor/Http/IHttpClient.cs
- WalletWasabi/Tor/TorMonitor.cs
- WalletWasabi/WebClients/BlockstreamInfo/BlockstreamInfoClient.cs
- WalletWasabi/WebClients/Wasabi/WasabiHttpClientFactory.cs
- exclusion.dic
Alternative to #10569
Notes:
* `HttpClientFactory` is renamed to `WasabiHttpClientFactory` to avoid confusion with `IHttpClientFactory` in .NET.
* `WasabiHttpClientFactory.CreateLongLivedHttpClient` allows to create `HttpClient` instances that can live for long-time (as DNS is properly updated).
* A modification in `Global` was done to use the new `WasabiHttpClientFactory.CreateLongLivedHttpClient` helper method.
Review is easy commit by commit. Each commit can be a standalone PR basically if needed.
> Rename `HttpClientFactory` to `WasabiHttpClientFactory` and introduce `CreateLongLivedHttpClient` helper

- WalletWasabi.Daemon/Rpc/WasabiJsonRpcService.cs
Closes https://github.com/zkSNACKs/WalletWasabi/issues/11347.
```
$ ~/wcli.sh getfeerates
{
"2": 8
"36":4
"1008":2
}
```
> Add RPC fee rates

- global.json
We know that this repo cannot be built on `7.0.102`[^1]. So let's bump it a bit so users having `7.0.102` are not surprised when trying to compile.
This is not a proper fix but it's something we can do in reasonable time.
[^1]: I have hit this issue during working on [this](https://github.com/zkSNACKs/WalletWasabi/issues/10915#issuecomment-1685778961) and installing .NET on Ubuntu 22.04.
> Bump required .NET SDK version to 7.0.200

- WalletWasabi.Fluent/Models/Wallets/WalletCoinjoinModel.cs
Fixes: https://github.com/zkSNACKs/WalletWasabi/issues/11339
Wrong `StopAsync` was called before, so we didn't write the `StopCommand` to the `Channel`.
> Fix broken music box

- WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionPreviewViewModel.cs
Addresses #11191
Addresses #10171
and probably more in the future.
Already suggested this fix in the past for different problems, not sure why it was not accepted.
At this point, if an exception does occur somehow even before trying to finalize and send, just when we build the tx, we should raise the exception and throw out a message because something is deffinetly not ok, and we can prevent the wallet **crash** as well.
This PR just widens the try/catch.
> Fix Wasabi crash if exception happens after PreviewTx screen

- WalletWasabi.Backend/Global.cs
- WalletWasabi/BitcoinCore/P2pNode.cs
- WalletWasabi/BitcoinP2p/P2pBehavior.cs
- WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
- WalletWasabi/WabiSabi/Backend/Rounds/Round.cs
- WalletWasabi/WabiSabi/WabiSabiCoordinator.cs
This PR is for banning coins that were spent after being registered for participation in a coinjoin.
> Ban doublespenders

- WalletWasabi.Fluent/Views/Wallets/MusicControlsView.axaml
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/11265
Tested, all the message fits the space.
> [VDG] MusicBox - remove fade out on messages

- WalletWasabi/WabiSabi/Backend/Rounds/RoundParameters.cs
- WalletWasabi/WabiSabi/Backend/WabiSabiConfig.cs
- WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
This reverts commit 197eccea110d992cb82d0dfdeb7d6377358e8966. And only take the suggestion to have `DelayTransactionSigning` to false by default.
> Revert `RoundParameter` that made clients to trust

- WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItems/HistoryItemViewModelBase.cs
Fixes `ArgumentNullException` constantly occurring in `HistoryViewModelBase` due to UI bindings reading values of properties `IsIncomingTransactionDisplayed` and `IsOutgoingTransactionDisplayed` that error out:
> [VDG] Fix HistoryViewModelBase error

- WalletWasabi.Fluent/Models/Transactions/PrivacyWarning.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Send/PrivacySuggestionsFlyoutViewModel.cs
- WalletWasabi.Fluent/Views/Wallets/Send/PrivacyWarningsView.axaml
- WalletWasabi.Fluent/Views/Wallets/Send/TransactionPreviewView.axaml
- Based on [this definition](https://github.com/zkSNACKs/WalletWasabi/issues/11269#issuecomment-1700531642)
- The following Warnings now have `Critical` severity:
- `InterlinksLabelsWarning`
- `TransactionKnownAsYoursByWarning`
- `NonPrivateFundsWarning`
- The icon in the Transaction Preview screen turns orange if there is at least one Critical warning, otherwise it will either be a white warning icon, or the green shield as before
- The icons in the warning list are orange for Critical warnings, otherwise white.
- Fixes #11269
> [VDG] Critical privacy warnings

- WalletWasabi.Fluent/Models/Wallets/Address.cs
This effectively re-enables address hiding in the GUI.
It was disabled due to this https://github.com/zkSNACKs/WalletWasabi/issues/10177
Fixes #11442
> [VDG] Re-enable mark as locked

- flake.nix
This PR is a solution for https://github.com/zkSNACKs/MaintenanceVault/discussions/139. It installs dotnet diagnostic tools `dotnet-trace` and `dotnet-dump` dependent on dotnet sdk 7. 
To get a shell with these tools available simply enter:
```bash
$ nix develop github:zksnacks/WalletWasabi
```
> Install diagnostic tools

- WalletWasabi/WalletWasabi.csproj
- flake.nix
Close https://github.com/zkSNACKs/WalletWasabi/issues/11483
Before this PR you had to have git installed and the Wasabi repository cloned in your filesystem in order to build Wasabi backend in a way that it displays the `CommitHash` correctly as part of the `Versions` API. This is because at building time the building system executed `git rev-parse HEAD` and used the console output to fill the `CommitHash` assembly metadata.
After this PR the building system receives the `CommitHash` as a parameter. In this way the build doesn't requires having git or the wasabi repository cloned locally and can create a deterministic build independent of the build environment.
With nix installed, just type `nix build` and press enter.
Then, check the `WalletWasabi.dll` metadata. You can do it with f# as …
> Use build parameters instead of running `git`

- WalletWasabi/Blockchain/Transactions/SmartTransactionExtensions.cs
- WalletWasabi/Blockchain/Transactions/TransactionHistoryBuilder.cs
This PR is meant to simplify #11458 and ease reviews. It should be easy to review the PR commit by commit.
Credits to @turbolay.
> [refactoring] Move methods out of `TransactionHistoryBuilder`

- WalletWasabi.Daemon/Rpc/WasabiJsonRpcService.cs
- WalletWasabi.Fluent/Extensions/TransactionSummaryExtensions.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Home/History/Details/TransactionDetailsViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItems/CoinJoinHistoryItemViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItems/CoinJoinsHistoryItemViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItems/TransactionHistoryItemViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryViewModel.cs
- WalletWasabi/Blockchain/Transactions/SmartTransactionExtensions.cs
- WalletWasabi/Blockchain/Transactions/TransactionHistoryBuilder.cs
- WalletWasabi/Blockchain/Transactions/TransactionSummary.cs
- WalletWasabi/Extensions/LinqExtensions.cs
This is another PR to simplify #11458.
Easy to review commit by commit.
> Step forward to Remove `TransactionSummary` (1/n)

- WalletWasabi.Fluent/ViewModels/Wallets/Home/History/Details/TransactionDetailsViewModel.cs
- WalletWasabi/Blockchain/Transactions/SmartTransactionExtensions.cs
- WalletWasabi/Blockchain/Transactions/TransactionHistoryBuilder.cs
- WalletWasabi/Blockchain/Transactions/TransactionSummary.cs
Follow-up to #11520
Computation of destination addresses can be IMO done later when it's actually needed. This should get us some benefit from #11458 without a big bang change.
> `TransactionSummary` refactoring (2/n): Remove computations of destination addresses.

- WalletWasabi.Tests/UnitTests/Transactions/TransactionFactoryTests.cs
- WalletWasabi/Blockchain/Transactions/TransactionFactory.cs
During https://github.com/zkSNACKs/WalletWasabi/pull/11120 I found that the calculation is wrong in the case of self spend.
I added a test for it.
Issue: https://github.com/zkSNACKs/WalletWasabi/pull/11120#pullrequestreview-1551330343
Explanation: https://github.com/zkSNACKs/WalletWasabi/pull/11120#issuecomment-1656127155
ping for review @zkSNACKs/code-team
> TransactionFactory - Fix fee percentage calculation for self spend

- WalletWasabi.Daemon/Rpc/WasabiJsonRpcService.cs
This PR adds a new method to recover wallets from mnemonics. Close: https://github.com/zkSNACKs/WalletWasabi/issues/11362
```
$ curl -s \
--user <rpcuser:rpcpassword> \
--data-binary '{"jsonrpc":"2.0", "id":"curltext", "method":"recoverwallet", "params":["recovered-wallet", "emerge title hero sauce pilot mail breeze jelly fatal speak shock ladder"]}' \
-H \
-- 'content-type: text/plain;' \
http://127.0.0.1:37128/
```
```
$ ./wcli.sh \
recoverwallet recovered-wallet \
"emerge\ title\ hero\ sauce\ pilot\ mail\ breeze\ jelly\ fatal\ speak\ shock\ ladder\"
```
> Add `recoverwallet` RPC call

- WalletWasabi/Blockchain/TransactionOutputs/CoinsRegistry.cs
- WalletWasabi/Blockchain/TransactionProcessing/TransactionProcessor.cs
This PR optimizes out section B bottleneck (described here: https://github.com/zkSNACKs/WalletWasabi/issues/11287) of transaction processing with no noticeable memory growth.
This PR is a part of https://github.com/zkSNACKs/WalletWasabi/pull/11298 and https://github.com/zkSNACKs/WalletWasabi/pull/11513/
```
1.6GB memory
2023-09-23 10:51:43.331 [17] INFO	Wallet.Dispose (421)	Initial Transaction Processing finished in 9.2 seconds.
Time spent in sections: A: 0.42%, B: 24.02%, C: 1.40%, D: 28.57%, E: 7.25%, F: 1.05%, G: 37.28%
```
```
1.6 GB memory
2023-09-23 10:57:18.962 [20] INFO	Wallet.Dispose (421)	Initial Transaction Processing finished in 8.32 seconds.
2023-09-23 10:58:58.438 [17] INFO	Wallet.Dispose (421)	Initial Transaction Processing finished in 8.71 seconds.
2023-09-23 11:01:29.075 …
```
> Speed up transaction processing by 20%

- WalletWasabi/Blockchain/TransactionProcessing/TransactionProcessor.cs
Found while reviewing #11572
Removed these two properties in `TransactionProcessor`
```cs
private int QueuedTxCount { get; set; }
private int QueuedProcessedTxCount { get; set; }
```
because seemingly we write to these properties but never ever did anything with them. 
We just stored some information, then never read them.
Also removed their try-finally block because in case of error, the exception bubbled up to the caller. 
I didn't change this behavior, but the try-finally become obsolete.
> Clean up useless properties in TransactionProcessor

- WalletWasabi.Tests/UnitTests/Transactions/TransactionProcessorTests.cs
- WalletWasabi/Blockchain/TransactionOutputs/CoinsRegistry.cs
Extracted change from #11516 
See my explanation here: https://github.com/zkSNACKs/WalletWasabi/pull/11516#discussion_r1330772917
> Set `SpenderTransaction` to null in Undo

- WalletWasabi.Daemon/Rpc/WasabiJsonRpcService.cs
This PR adds the `speeduptransaction` RPC method which received the hash of the transaction to be speed up and returns the raw transaction that does it (using RBF or CPFP) the previous tx.
```
$ curl -s --user rpcuser:rpcpassword \
--data-binary '{"jsonrpc":"2.0", "id":"curltext", "method":"speeduptransaction", "params":["0f5cdf64a4138d7bbf95bdaf7b73619aae9137085edf69c057b18ff6dda1935f"]}' -H \
-- 'content-type: text/plain;' \
http://127.0.0.1:37128/TestNet%20Small/
```
This one and https://github.com/zkSNACKs/WalletWasabi/pull/11536 close: https://github.com/zkSNACKs/WalletWasabi/issues/11500
> Add `speeduptransaction` RPC method

- WalletWasabi.Daemon/Rpc/WasabiJsonRpcService.cs
This PR adds the `canceltransaction` RPC method which received the hash of the transaction to be cancelled and returns the raw transaction that cancels the previous tx.  
```
$ curl -s --user rpcuser:rpcpassword \
--data-binary '{"jsonrpc":"2.0", "id":"curltext", "method":"canceltransaction", "params":["0f5cdf64a4138d7bbf95bdaf7b73619aae9137085edf69c057b18ff6dda1935f"]}' -H \
-- 'content-type: text/plain;' \
http://127.0.0.1:37128/TestNet%20Small/
010000000001015620b45c9625563e7fe9899407ce905c0b34d4b1edb373eca920e6ece172f06a0000000000fdffffff011b3e100000000000225120f2e947f2bbbad6a738fe6dcc96886291fc75d483e428dcd0fd7dc25fb7ebe4e00140f074f6f3e53ace8f4e60c25186661ba5a31159feb668d6a78e864815c398a8b317cc759971144cfbecc6ab122e3e3d9f91362b793bb9b48297894a1c2c26927200000000
```
This one and …
> Add `canceltransaction` RPC method

- WalletWasabi/Blockchain/TransactionOutputs/CoinsRegistry.cs
- WalletWasabi/Blockchain/TransactionProcessing/TransactionProcessor.cs
Found while looking at https://github.com/zkSNACKs/WalletWasabi/pull/11577#issuecomment-1734277566
This PR has 2 goals:
- On master, `CanBeConsideredDustAttack` enumerates all the time the `Coins` of the wallet. This PR uses the `TryGetValue` of `CoinsByPubKeys`, a cache that was introduced in #11571. So it's cleaner and potentially more performant in some cases.
- On master, `CanBeConsideredDustAttack` has a bug; it doesn't consider the keys with no unspent coin left to unlock as used. This PR fixes this.
Note: Maybe it would make more sense to do this using the `KeyManager`, but `CanBeConsideredDustAttack` was already using the `CoinsRegistry`.
> Introduce IsUsed in the CoinsRegistry

- WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PrisonTests.cs
- WalletWasabi.Tests/UnitTests/WabiSabi/Backend/UtxoPrisonWardenTests.cs
- WalletWasabi/WabiSabi/Backend/DoSPrevention/Prison.cs
Close https://github.com/zkSNACKs/WalletWasabi/issues/11482
Utxos created by Wasabi coinjoins are punished linearly instead of exponentially.
> Punish remixers linearly

- WalletWasabi.Tests/RegressionTests/CancelTests.cs
- WalletWasabi.Tests/RegressionTests/ReceiveSpeedupTests.cs
- WalletWasabi.Tests/RegressionTests/SelfSpendSpeedupTests.cs
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/11557
> Fix CPFP + Cancel Regression Tests

- WalletWasabi/WebClients/Wasabi/WasabiHttpClientFactory.cs
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/11600
> Allow decompress Brotli responses automatically

- WalletWasabi.Fluent/Converters/EnumToBoolConverter.cs
- WalletWasabi.Fluent/Converters/TransactionHistoryItemToolTipConverter.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItems/CoinJoinHistoryItemViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItems/CoinJoinsHistoryItemViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItems/HistoryItemViewModelBase.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItems/SpeedUpHistoryItemViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Home/History/HistoryItems/TransactionHistoryItemViewModel.cs
- WalletWasabi.Fluent/Views/Wallets/Home/History/Columns/IndicatorsColumnView.axaml
While doing https://github.com/zkSNACKs/WalletWasabi/pull/10423 it was reported that while scrolling items in TDG history table have glitches in icons. To make icon updates we use classes binding, to do so we have created many properties and bind them to icon classes. This PR is first step to make view model code cleaner, next step would be (if needed - glitches still occur) to refactor how PathIcon data is set (using enum to path data converter) - should be done in another PR is still needed.
> [VDG] Use enum for history item status and type

- WalletWasabi.Daemon/Rpc/WasabiJsonRpcService.cs
NBitcoin was returning "Unknown" as a message when it was not able to guess the words list language used in the mnemonic. We improve this in our side.
Close https://github.com/zkSNACKs/WalletWasabi/issues/11564
Note: HTTP status code has to be 200 OK in this case.
> More descriptive error message when recovering wallet rpc

- WalletWasabi.Fluent/Views/Wallets/Send/TransactionPreviewView.axaml
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/11296
> [VDG] Privacy Warning - change final message

- WalletWasabi.Fluent/App.axaml.cs
- WalletWasabi.Fluent/Helpers/AuthorizationHelpers.cs
- WalletWasabi.Fluent/Models/UI/UiContext.cs
- WalletWasabi.Fluent/Models/Wallets/HardwareWalletModel.cs
- WalletWasabi.Fluent/Models/Wallets/WalletModel.cs
- WalletWasabi.Fluent/Models/Wallets/WalletRepository.cs
- WalletWasabi.Fluent/ViewModels/MainViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Home/History/Features/CancelTransactionDialogViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Home/History/Features/SpeedUpTransactionDialogViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Send/SendViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionPreviewViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModel.cs
- WalletWasabi.Tests/UnitTests/ViewModels/Mocks.cs
- WalletWasabi.Tests/UnitTests/ViewModels/ReceiveAddressViewModelTests.cs
- WalletWasabi.Tests/UnitTests/ViewModels/ReceiveViewModelTests.cs
- WalletWasabi.Tests/UnitTests/ViewModels/SuggestionLabelsViewModelTests.cs
- WalletWasabi.Tests/UnitTests/ViewModels/UiContextBuilder.cs
This PR Adds `IAmountProvider` to `IWalletModel`. This is to avoid having a direct dependency on `UiContext` for several ViewModels where an `IWalletModel` will suffice. 
There are many cases of ViewModels which require `IAmountProvider` in their constructor, and we know that `UiContext` can't be accessed directly from ViewModel's constructors. 
We still need need the service to be available "globally" in the `UiContext` because there are cases of ViewModels that don't work with a particular Wallet, therefore `IWalletModel` isn't available for them, but they still need to work with amounts.
> [VDG] UI Decoupling #48

- WalletWasabi.Fluent/Controls/AmountControl.axaml.cs
- WalletWasabi.Fluent/Infrastructure/ClipboardObserver.cs
- WalletWasabi.Fluent/Models/Wallets/Amount.cs
- WalletWasabi.Fluent/Models/Wallets/WalletModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/CoinJoinStateViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Home/History/Details/CoinJoinDetailsViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Home/History/Details/CoinJoinsDetailsViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/WalletBalanceTileViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Send/SendViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionSummaryViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModel.cs
- WalletWasabi.Tests/UnitTests/ViewModels/ReceiveAddressViewModelTests.cs
- WalletWasabi.Tests/UnitTests/ViewModels/ReceiveViewModelTests.cs
- WalletWasabi.Tests/UnitTests/ViewModels/SuggestionLabelsViewModelTests.cs
This PR moves the `Amount` class to the Model layer (and corresponding namespace).
This class really belongs there, as it's just a wrapper over `Money` plus an observable for fiat equivalent based on exchange rate.
Also, since both `UiContext` and `WalletModel` have a reference to this type, and these classes are Models, it follows that the `Amount` is also a model, because Models can't really depend on ViewModel otherwise we'd be mixing layers in an incorrect way.
> [VDG] UI Decoupling #49

- WalletWasabi.Fluent/Views/TransactionBroadcasting/LoadTransactionView.axaml
current
over time, several people reached out that they were not able to paste their tx.
It turned out that they were pasting the TxID instead of the hex.
so just a small clarification.
shouldn't be controversial that _hex_ is technical as this is for advanced usage anyway.
> [vdg] clarify Transaction Broadcaster dialog caption

- WalletWasabi/WabiSabi/Backend/DoSPrevention/Warden.cs
Whenever I stop the server on RegTest, this is how the log looks like:
```
2023-10-03 12:43:04.902 [28] INFO	HostedServices.StopAllAsync (88)	Stopped Block Notifier.
2023-10-03 12:43:04.902 [29] INFO	HostedServices.StopAllAsync (88)	Stopped Full Node Mempool Mirror.
2023-10-03 12:43:04.905 [28] ERROR	Warden.ExecuteAsync (83)	System.OperationCanceledException: The operation was canceled.
at System.Threading.Channels.AsyncOperation`1.GetResult(Int16 token)
at System.Threading.Channels.ChannelReader`1.ReadAllAsync(CancellationToken cancellationToken)+MoveNext()
at WalletWasabi.WabiSabi.Backend.DoSPrevention.Warden.ExecuteAsync(CancellationToken cancel) in WalletWasabi\WabiSabi\Backend\DoSPrevention\Warden.cs:line 74
at WalletWasabi.WabiSabi.Backend.DoSPrevention.Warden.ExecuteAsync(Cancellati …
```
> [Trivial] Reduce log level when Warden stops

- WalletWasabi.Tests/UnitTests/Blockchain/TransactionOutputs/CoinsRegistryTests.cs
- WalletWasabi/Blockchain/TransactionOutputs/CoinsRegistry.cs
- WalletWasabi/Blockchain/TransactionProcessing/TransactionProcessor.cs
A part of #11516 which is trivial.
> [trivial] `CoinsRegistry`: Rename methods

- WalletWasabi.Daemon/Rpc/WasabiJsonRpcService.cs
- WalletWasabi/Wallets/Wallet.cs
I thought of adding an RPC endpoint to access #9925 feature, as the UI was never made.
The function can be used to both exclude some coins or "unexclude" them, depending on the bool passed.
I can change the naming and signature if anyone has a better idea. I can also move the business logic.
I also took the liberty to implement 2 ways to exclude coins: By Outpoint or by Label of a transaction linked to the coin.
I can remove the "By Label" feature if it's preferred to don't have it.
> Add `excludefromcoinjoin` from RPC

- WalletWasabi.Fluent/Helpers/TransactionHelpers.cs
- WalletWasabi.Fluent/ViewModels/TransactionBroadcasting/LoadTransactionViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/HardwareWalletViewModel.cs
Addresses: https://github.com/zkSNACKs/WalletWasabi/issues/9856#issuecomment-1753125713
Might fix completely: https://github.com/zkSNACKs/WalletWasabi/issues/9856
When the user sets this settings on ColdCard (`settings>delete psbts>normal/delete)` to `delete`,
ColdCard deletes the PSBT files from the SD card.
What's left is a signed `.txn` file.
Wasabi almost supported this, but because we throw this ex:
`throw new FormatException("An error occurred while loading the PSBT file.", ex);`
the fallback mechanism didn't have a chance to run.
With this PR I was able to broadcast the .txn file properly.
> Fix .txn file import for ColdCards

- WalletWasabi.Daemon/Rpc/WasabiJsonRpcService.cs
- WalletWasabi.Tests/RpcTests.cs
- WalletWasabi.Tests/UnitTests/RpcTests.cs
- WalletWasabi/Helpers/Constants.cs
- WalletWasabi/Rpc/JsonRpcRequestHandler.cs
This is based on @NabiSabi PR #3696 which was okay but the [JsonRpcRequestHandler.cs](https://github.com/zkSNACKs/WalletWasabi/compare/master...lontivero:WalletWasabi:rpc-feerate-build?expand=1#diff-15a4dc01afb2e9b1dba8a1ff94b3fafdb4a81cb2bcaa831c2f5c3cec66befa6b) didn't know how to handle the optional values.
Here we add support for optional values and take the code from #3696 almost as it was. 
You can use the example from the original PR to test it:
```
$ curl -s \
--user wasabiuser:wasabiuserpassword \
-H -- 'content-type: text/plain;' \
--binary-data  '{"jsonrpc":"2.0","id":"1","method":"send", "params": { "payments":[ {"sendto": "tb1qgvnht40a08gumw32kp05hs8mny954hp2snhxcz", "amount": 15000, "label": "David" }, {"sendto":"tb1qpyhfrpys6skr2mmnc35p3dp7zlv9ew4k0gn7qm", "amount": 86200, …
```
> Add `feeRate` to `build` and `send` rpc interface

- WalletWasabi.Fluent/Views/Settings/BitcoinTabSettingsView.axaml
Moved up `Stop Bitcoin Knots on shutdown` and `Local Bitcoin Core/Knots version` settings, and made the node version setting visible only if `StartLocalBitcoinCoreOnStartup` is on.
Master:
PR:
> [VDG][Trivial] Order bitcoin node settings

- WalletWasabi/Helpers/VirtualSizeHelpers.cs
- WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
- WalletWasabi/WabiSabi/Models/MultipartyTransaction/MultipartyTransactionParameters.cs
- WalletWasabi/WabiSabi/Models/MultipartyTransaction/SigningState.cs
On testnet, when the size of the coinjoin transaction is small, the weight of the transaction shared overhead is greater and can fall below the minimum transaction relay, failing to broadcast it.
The current shared overhead assumes the number of inputs and outputs is greater than 254, what is false in testnet in most of the cases. This is why this problem is important for `TestNet` only.
> Fix coinjoins shared overhead calculation

- WalletWasabi.Fluent/Views/Wallets/Send/TransactionSummary.axaml
Amount and address are the most important pieces of information here.
Put them at the top.
I found myself confused/extra thinking several times before, easier to see amount and address just in one look.
Which is what the user usually will double-check.
I could not find any reasoning on why the `Recipient` label should be the second item, when it was added https://github.com/zkSNACKs/WalletWasabi/pull/8563
> [vdg] Preview TX screen: put address as second item

- WalletWasabi.Fluent/Extensions/ObservableExtensions.cs
- WalletWasabi.Fluent/Models/Wallets/WalletCoinsModel.cs
- WalletWasabi.Fluent/ViewModels/CoinControl/CoinSelectorViewModel.cs
- WalletWasabi.Fluent/ViewModels/Dialogs/LabelEntryDialogViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Advanced/WalletCoins/WalletCoinsViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/PrivacyControlTileViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/PrivacyRing/PrivacyBarViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/PrivacyRing/PrivacyRingViewModel.cs
I've included some performance tuning here and remove what looked like a memory leak. 
It should be noticeable in anything that uses coins/pockets, and most importantly, when switching wallets and on initial wallet log in.
I've tested myself, but not extensively. The code is quite robust, but I'd feel better if you try to hunt for any regression.
These are the features that come to mind that could be affected:
- Coin List
- Coin Control
- Wallet History
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/11681
> [VDG] Performance tuning

- WalletWasabi.Daemon/Config.cs
- WalletWasabi.Daemon/Global.cs
- WalletWasabi/Tor/Control/TorControlClient.cs
- WalletWasabi/Tor/TorProcessManager.cs
- WalletWasabi/Tor/TorSettings.cs
This PR exposes the RPC server as an onion service.
```
$ dotnet run -- \
--usetor=true \
--network=testnet \
--jsonrpcserverenabled=true \
--jsonrpcuser=myuser \
--jsonrpcpassword=mypassword \
--onionenabled=true
```
It is important to know that:
* `UseTor` is necessary because that switch controls whether the Tor process must be launched or not. We need the Tor process running in order to create the ephemeral onion service.
* `JsonRpcServerEnabled` must be true because otherwise the rpc server is not started.
* Anonymous access is not allowed when exposing the server as an onion service. This means that you have to specify both `JsonRpcUser` and `JsonRpcPassword`.
* `OnionEnabled` indicates whether or not to create the ephemeral onion service. This switch is only available as a command …
> Expose the RPC Server as an onion service

- WalletWasabi.Fluent/Models/Wallets/WalletCoinsModel.cs
@MarnixCroes discovered:
> Everytime after launching Wasabi and opening a wallet I get 3 of these in the logs?
[1] INFO    WalletCoinsModel..ctor (51)    Refresh signal emitted in WalletName
> [UI] Wallet Coins - fix unnecessary refreshes

- WalletWasabi.Fluent/ViewModels/Wallets/Send/TransactionSummaryViewModel.cs
- WalletWasabi.Fluent/Views/Wallets/Send/TransactionSummary.axaml
Fixes #11785
When you copy the `Amount` in the Tx Preview dialog, the class type of the amount got saved to the clipboard.
this: `WalletWasabi.Fluent.Models.Wallets.Amount`
The actual BTC amount is copied to the clipboard.
> [VDG] Fix amount copy on Transaction Preview dialog

- WalletWasabi.Fluent/Models/Transactions/PrivacySuggestion.cs
- WalletWasabi.Fluent/Models/Transactions/PrivacySuggestionsModel.cs
> Fix change avoidance giving back two Less/More suggestion

- WalletWasabi/Helpers/ImportWalletHelper.cs
Fixes #11796
It only set's `PreferPsbtWorkflow` to `true` when the wallet is imported with ColdCard's json file. In that case it is safe to assume that the user prefers PSBT.
> Set PreferPsbtWorkflow true when importing ColdCard HW

- WalletWasabi.Fluent/ViewModels/AddWallet/RecoverWalletViewModel.cs
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/11668
- Error message changed to be more accurate
- Error message only appears when the number of words reaches 12,15,18,21 or 24 and the checksum is not valid.
> [UI] Recovery words - fix message and improve UX

- WalletWasabi/WabiSabi/WabiSabiCoordinator.cs
Coinjoin outputs should not inherit punishments because otherwise everybody pays for the sins of a few.
> Do not ban coinjoin outputs

- WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
- WalletWasabi/WabiSabi/WabiSabiCoordinator.cs
In many cases the coordinator receives a coinjoin transaction even before the round that created it switches to `Ended` state. Because of that the coordinator believes that it has received a transaction that spent coins that are registered in an **active** round.
> Fix ban double spenders

- WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModel.cs
Fixes Wallet Coins and Wallet Settings dialogs appearing on full screen due to missing parameter in the Navigation method call
fixes https://github.com/zkSNACKs/WalletWasabi/issues/11819
> [VDG] Fix Wallet Dialogs

- WalletWasabi.Fluent/Behaviors/ItemsPresenterAnimationBehavior.cs
Fixes: https://github.com/zkSNACKs/WalletWasabi/issues/9338
This actually reverts previous fix for Avalonia 0.10.x from https://github.com/zkSNACKs/WalletWasabi/pull/10161
I think initial delay in animations was fixed in Avalonia v11.
> [VDG] Fix PrivacyRing loading animation showing twice when opened

- WalletWasabi.Fluent/Models/Wallets/TransactionModel.cs
- WalletWasabi.Fluent/Models/Wallets/TransactionTreeBuilder.cs
fixes https://github.com/zkSNACKs/WalletWasabi/issues/11818
closes https://github.com/zkSNACKs/WalletWasabi/pull/11838
> [UI] History - fix CJ group amounts (alternative)

- WalletWasabi/WabiSabi/Backend/DoSPrevention/Prison.cs
- WalletWasabi/WabiSabi/Backend/Models/WabiSabiProtocolErrorCode.cs
- WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
Access to the banning times cache was not correctly synchronized and that resulted in exceptions like the following:
```
2023-10-30 02:37:10.382 [264] ERROR     PeriodicRunner.ExecuteAsync (107)       System.IndexOutOfRangeException: Index was outside the bounds of the array.
at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
at WalletWasabi.WabiSabi.Backend.DoSPrevention.Prison.GetBanTimePeriod(OutPoint outpoint, DoSConfiguration configuration)
at WalletWasabi.WabiSabi.WabiSabiCoordinator.<>c__DisplayClass35_0.<BanDescendant>g__IsInputBanned|0(TxIn input)
at System.Linq.Enumerable.WhereSelectListIterator`2.ToArray()
at WalletWasabi.WabiSabi.WabiSabiCoordinator.<>c__DisplayClass35_0.<BanDescendant>b__3(Transaction tx)
at …
```
> Fix synchronization issue

- WalletWasabi.Daemon/Rpc/WasabiJsonRpcService.cs
This PR uses a type `JsonRpcResult` instead of `object` what give us more flexibility to create the response in the shape that we want.
> RPC service refactoring

- WalletWasabi.Daemon/Config.cs
- WalletWasabi.Daemon/WasabiAppBuilder.cs
- WalletWasabi/Extensions/StringExtensions.cs
This PR add some help (not yet really) using the config metadata
```
$ wassabeed --help
Wasabi Daemon 2.0.4.0
Usage: Wasabi Daemon [OPTION]...
Available options are:
--blockonlymode                  Indicate Wasabi should only listen for 
blocks and not for transactions
--coordinatoridentifier          -
--downloadnewversion             Indicate new version of Wasabi should 
be downloaded automatically
--dustthreshold                  Threshold amount under which coin 
received from others to reused 
addresses are considered a dust attack
--enablegpu                      Indicate Wasabi should use the GPU
--jsonrpcpassword                The user password that is authorized to 
make requests to the Json RPC server
--jsonrpcserverenabled           Indicate the Json RPC Server should be …
```
> Add some help to the command line

- WalletWasabi.Daemon/Rpc/WasabiJsonRpcService.cs
- WalletWasabi.Tests/UnitTests/Transactions/SmartTransactionTests.cs
- WalletWasabi/Blockchain/Keys/HdPubKey.cs
- WalletWasabi/Blockchain/Transactions/SmartTransaction.cs
- WalletWasabi/WabiSabi/Models/Serialization/JsonSerializationOptions.cs
EDIT: Implemented @lontivero's suggestion: https://github.com/zkSNACKs/WalletWasabi/pull/11851#pullrequestreview-1710426768
I`Pubkey.Hash.Get()` is a time-consuming operation, and avoiding computing these values (what this PR is doing) improves startup by more or less 20% with wallets containing a lot of keys (8s -> 6s on my setup).
> Don't use PubKey.Hash in HdPubKey equality comparer

- WalletWasabi/Extensions/DateTimeOffsetExtensions.cs
- WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
It's just refactoring, as #11679 wants to access poisson scheduling outside the `CoinJoinClient`.
In this PR, I moved `CoinJoinClient.GetScheduleDates` methods in `DateTimeOffsetExtensions`.
The virtual method must stay in `CJC` because a test is using it.
I could have created a non-extension method class but I believe it makes sense to be based on the `endTime`
> Expose poisson scheduling in DateTimeOffset extension method

- WalletWasabi/WabiSabi/Backend/DoSPrevention/Prison.cs
This is an optimization because otherwise calculating the banning period requires a full scan or the Offenders list, what is really expensive.
> Keep offenders grouped by txid.

- WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PrisonTests.cs
- WalletWasabi/WabiSabi/Backend/DoSPrevention/Prison.cs
The reasoning is that by spending the banned coin the attacker has incurred in a penalty (cost of spending + time confirmation time).
Close https://github.com/zkSNACKs/WalletWasabi/issues/11933
> Reduce the punishment by half for offenders who spent.

- WalletWasabi/Backend/Models/Responses/StatusResponse.cs
I found out that we still have this redundant status about WW1 coinjoins.
and it will always be false.
> [Trivial] Remove redundant WW1 status property

- WalletWasabi.Fluent/Converters/FeeRateConverters.cs
- WalletWasabi.Fluent/Views/Wallets/Home/History/Details/TransactionDetailsView.axaml
NBitcoin returns `sat/B` which doesn't seem to be correct: https://github.com/zkSNACKs/WalletWasabi/pull/11953#issuecomment-1818799270, https://github.com/zkSNACKs/WalletWasabi/issues/11128#issuecomment-1818802514
> [UI] correct FeeRate unit

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/feature-request.md
Over time, several people who opened an issue didn't remove the help/example text.
So it was shown when reading the issue.
Commenting it out makes the issue look better and easier to read, when the issue opener doesn't remove it.
> ISSUE_TEMPLATE: comment out example/help text

- WalletWasabi.Tests/UnitTests/WabiSabi/Backend/CoordinatorTests.cs
- WalletWasabi.Tests/UnitTests/WabiSabi/Backend/OffenderSerializationTests.cs
- WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PrisonTests.cs
- WalletWasabi.Tests/UnitTests/WabiSabi/Backend/UtxoPrisonWardenTests.cs
- WalletWasabi/Extensions/LinqExtensions.cs
- WalletWasabi/WabiSabi/Backend/DoSPrevention/Offender.cs
- WalletWasabi/WabiSabi/Backend/DoSPrevention/Prison.cs
- WalletWasabi/WabiSabi/Backend/Rounds/Arena.Partial.cs
- WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
- WalletWasabi/WabiSabi/WabiSabiCoordinator.cs
This PR fixes a few very important things in the process of detecting and banning round disruptions by spending coins participating in coinjoin rounds.
1. Given a transaction can have multiple inputs and those can be participating in multiple rounds, a single transaction can be used to disrupt more than one round. This fact was not part of the original design and for that reason the RoundDisruption offense only considered one round instead of multiple rounds.
2. Wasabi was banning the inputs of the attacking transaction but those coins are spent and it makes no sense to ban them, instead it should have banned the coins that the attacking transaction creates.
3. There was a small time frame where a received wasabi coinjoin transaction was not in the CoinJoinIdStore or in the RoundStates …
> Detecting and (avoid) Banning Wasabi coinjoins

- WalletWasabi.Fluent/Views/Wallets/Home/History/Details/TransactionDetailsView.axaml
Close #11972 
Found sat/vByte Fee rate only in Transaction Details page.
Before:
After:
Anything under .05 will round down, and .05 and above will round up.
> Changed string format to 1 number after dot.

- WalletWasabi.Daemon/Global.cs
- WalletWasabi/WabiSabi/Client/Banning/CoinPrison.cs
Part of #11910
If, by mistake, the coordinator bans a coin for couple of years, the client won't ever try to register that coin while it is banned according to the client's LOCAL prison. 
Even if we clean the Prison on the backend, nothing invalidates the banned state in the local prison.
This is the naive way to invalidate the local prison.
If the client detects that the banning period is way too long (more than 4 days atm), then the local prison will pick a random value between 2 day and 4 day and save that.
Randomized hours-minutes-seconds so common input ownership is not revealed once the reduced banning time is over.
With this, the client will try to CJ its banned coins from time to time. So we are "checking" the true Prison in the backend more frequently.
> Reduce and randomize local banning time if the banning time is absurdly long

- WalletWasabi.Fluent/ApplicationStateManager.cs
- WalletWasabi.Fluent/Providers/ICanShutdownProvider.cs
- WalletWasabi.Fluent/ViewModels/ApplicationViewModel.cs
Instead of https://github.com/zkSNACKs/WalletWasabi/pull/11984
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/11544
Found a much easier idea. We can reach `TerminateService` from `ApplicationStateManager`.
As I said [here](https://github.com/zkSNACKs/WalletWasabi/pull/11984#issuecomment-1824603969), if "Run in background" is turned ON, `Services.UiConfig.HideOnClose` will be true, so we just return and won't shutdown Wasabi, so the check in `CanShutdown()` was redundant.
Instead in this PR, if we know Wasabi was forcefully terminated, we don't check this option, just shutdown.
> Shutdown Wasabi with Ctrl-C even when "Run in background" is enabled | Take 2

- WalletWasabi.Tests/Helpers/ServiceFactory.cs
- WalletWasabi.Tests/Helpers/TransactionParametersBuilder.cs
- WalletWasabi.Tests/UnitTests/Transactions/PayjoinTests.cs
- WalletWasabi.Tests/UnitTests/Transactions/TransactionFactoryTests.cs
- WalletWasabi/Blockchain/TransactionBuilding/TransactionBuilderWalletExtensions.cs
- WalletWasabi/Blockchain/Transactions/TransactionFactory.cs
Follow-up to #11738
Easier to review commit by commit.
> Use `TransactionFactoryParameters` in tests

- WalletWasabi.Backend/WalletWasabi.Backend.csproj
- WalletWasabi.Daemon/WalletWasabi.Daemon.csproj
- WalletWasabi.Fluent.Desktop/WalletWasabi.Fluent.Desktop.csproj
- WalletWasabi.Fluent.Generators/WalletWasabi.Fluent.Generators.csproj
- WalletWasabi.Fluent/WalletWasabi.Fluent.csproj
- WalletWasabi.Packager/WalletWasabi.Packager.csproj
- WalletWasabi.Tests/WalletWasabi.Tests.csproj
- WalletWasabi/WalletWasabi.csproj
Recently my VS auto-updated and I got the new C# - especially the new C# lang version => 12. After this VS started to offer new expressions that are only available in 12. I thought it was OK because we specified versions in config files precisely. Unfortunately, this was not the case with the lang version - other devs were not able to compile the project. 
I propose to set the version of the lang from `latest` to `11` to make this deterministic. In this case, automatic updates cannot mess up our code integrity. We have a similar concept with the .NET version as well - it is specified precisely.
> Make sure we all use the same C# lang version

- WalletWasabi.Documentation/WasabiCompatibility.md
- WalletWasabi.Tests/AcceptanceTests/HwiKatas.cs
- WalletWasabi.Tests/Helpers/HwiValidationHelper.cs
- WalletWasabi.Tests/UnitTests/Hwi/HwiProcessBridgeMock.cs
- WalletWasabi.Tests/UnitTests/Hwi/MockedDeviceTests.cs
- WalletWasabi.Tests/UnitTests/WalletDirTests.cs
- WalletWasabi/Hwi/Models/HardwareWalletModels.cs
- WalletWasabi/Hwi/Models/HwiEnumerateEntry.cs
- WalletWasabi/Hwi/Parsers/HwiParser.cs
- WalletWasabi/Wallets/WalletType.cs
Fixes: [zkSNACKs/WalletWasabi#11908](https://github.com/zkSNACKs/WalletWasabi/issues/11908)
The HWI already supports the Blockstream Jade hardware wallet, but until now, Wasabi wallet did not. Therefore, we decided to implement this in the current codebase.
We acquired a Blockstream Jade hardware wallet and initialized it with the appropriate parameters. After this, I implemented the new Enums, HardwareWalletModel and WalletType, in the code.
I started the Wasabi wallet and was able to add it as a wallet.
> Jade wallet implement

- WalletWasabi/BuyAnything/BuyAnythingManager.cs
Tracking codes and attachment links now will be sent seperately.
> Separate links into their own bubbles

- WalletWasabi/Helpers/ByteHelpers.cs
Simple https://benchmarkdotnet.org benchmark confirms that we no longer need the custom code:
```cs
[MemoryDiagnoser]
public class Benchmarks
{
private byte[] _bytes;
[Params(4, 16, 128)]
public int Length { get; set; }
[GlobalSetup]
public void Setup() => _bytes = RandomNumberGenerator.GetBytes(Length);
[Benchmark]
public string Master()
{
return WalletWasabi.Helpers.ByteHelpers.ToHex(_bytes);
}
[Benchmark]
public string Pr()
{
return Convert.ToHexString(_bytes);
}
}
```
Results:
| Method | Length |      Mean |    Error |   StdDev |    Median |  Gen 0 |  Gen 1 | Allocated |
|------- |------- |----------:|---------:|---------:|----------:|-------:|-------:|----------:|
| Master |      4 |  11.18 ns | 0.314 ns | 0.911 ns |  10.91 ns | 0.0063 |      - |      40 B |
|     Pr |      4 | …
> `ByteHelpers.ToHex`: Use .NET implementation

- WalletWasabi/Blockchain/Transactions/AllTransactionStore.cs
This shows what the API actually is. `internal` methods are needed only for tests.
> `AllTransactionStore`: Fix accessibility modifiers

- Directory.Packages.props
- WalletWasabi.Fluent.Desktop/packages.lock.json
- WalletWasabi.Fluent/WalletWasabi.Fluent.csproj
- WalletWasabi.Fluent/packages.lock.json
- Update to  Avalonia.Controls.TreeDataGrid v11.0.2 - has many bug fixes https://github.com/AvaloniaUI/Avalonia.Controls.TreeDataGrid/releases/tag/11.0.2
- Update to Avalonia  v11.0.6 https://github.com/AvaloniaUI/Avalonia/releases/tag/11.0.6 - has many bug fixes 
- Remove hack fix "HarfBuzzSharp can be removed when Avalonia.Skia gets updated version"
> [VDG] Update to latest Avalonia 11 NuGet packages

- WalletWasabi/Helpers/Constants.cs
We didn't release from `master` branch, but `master` should also know about the release.
> Bump version to 2.0.5 on master

- WalletWasabi.Fluent/Views/MainWindow.axaml
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/12167
We really need SubpixelAntialias for smooth text rendering without artifacts.
> [VDG] Fix text rendering after Avalonia v11 update

- WalletWasabi.Documentation/WasabiSetupRegtest.md
With the "new" version of Knots you do not have a wallet by default. It is required for testing.
> RegTest - enable wallet

- WalletWasabi.Tests/UnitTests/Bases/ConfigManagerTests.cs
- WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterOutputTests.cs
- WalletWasabi/WabiSabi/Backend/WabiSabiConfig.cs
Allow to register more scriptpubkyes to  enable more use cases for coinjoins
> Allow `P2PKH` and `P2SH` scripts in coinjoin outputs

- WalletWasabi.Tests/UnitTests/Bases/ConfigManagerTests.cs
- WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterOutputTests.cs
- WalletWasabi/WabiSabi/Backend/WabiSabiConfig.cs
Reverts zkSNACKs/WalletWasabi#12190 
This was not tested enough. I will continue working on this concept in another PR.
> Revert "Allow `P2PKH` and `P2SH` scripts in coinjoin outputs"

- WalletWasabi.Fluent/Models/Wallets/HealthMonitor.cs
> Fix RpcMonitor init in HealthMonitor

- WalletWasabi/Wallets/Wallet.cs
Fixes a bug revealed by #12185.
> Ensure Height is at least SegWit activation

- WalletWasabi.Fluent/Controls/ContentArea.axaml
- WalletWasabi.Fluent/Controls/SuggestionItem.axaml
- ContentArea is a ContentControl.
ContentControl expects a ContentPresenter, because it was using a ContentControl instead of presenter, content control was unable to manage the lifetime of the content.
> fix memory leak caused by content area.

- WalletWasabi/Wallets/P2PBlockProvider.cs
- WalletWasabi/Wallets/SmartBlockProvider.cs
The PR moves the looping behavior from `P2PBlockProvider` to `SmartBlockProvider`. This change makes `P2PBlockProvider` more useful as a "building block".
The PR is meant as a helper PR for #12184.
To understand the PR, it's good to check one commit at a time and then review whole PR with whitespace [off](https://github.com/zkSNACKs/WalletWasabi/pull/12250/files?diff=split&w=1).
> Move repeating behavior of `P2PBlockProvider` to `SmartBlockProvider`

- WalletWasabi.Tests/UnitTests/TestWallet.cs
- WalletWasabi.Tests/UnitTests/WabiSabi/Client/CoinJoinCoinSelectionTests.cs
- WalletWasabi/WabiSabi/Backend/Rounds/RoundParameters.cs
- WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
- WalletWasabi/WabiSabi/Client/CoinJoinCoinSelector.cs
- WalletWasabi/WabiSabi/Client/IDestinationProvider.cs
- WalletWasabi/WabiSabi/Client/InternalDestinationProvider.cs
- WalletWasabi/WabiSabi/Client/OutputProvider.cs
- WalletWasabi/WabiSabi/Client/UtxoSelectionParameters.cs
`RoundParameter` , a class designed to concentrate/centralize the parameters required by the coordinator to create rounds, was containing client-side code. That code was moved to a better place.
The amount decomposition was using the scripts types allowed in the coinjoin outputs to split the amount without taking into account the script types supported by the client. This means that if we enable other script types in the coinjoins the client would try to send money to itself using scripts that the wallet doesn't support (this would result in money being sent to scripts that wasabi cannot spend). This is why https://github.com/zkSNACKs/WalletWasabi/pull/12190 was reverted.
> Fix round parameters

- WalletWasabi/Services/WasabiSynchronizer.cs
Alternative and working solution to https://github.com/zkSNACKs/WalletWasabi/pull/12261
> Use INotifyPropertyChanged instead of base in WasabiSynchronizer

- WalletWasabi.Tests/UnitTests/Bases/ConfigManagerTests.cs
- WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterOutputTests.cs
- WalletWasabi/Extensions/NBitcoinExtensions.cs
- WalletWasabi/Helpers/Constants.cs
- WalletWasabi/WabiSabi/Backend/WabiSabiConfig.cs
This PR allows to register `P2PKH`, `P2SH` and `P2WSH` scriptpubkeys to enable more use cases for coinjoins.
> `P2PKH`, `P2SH` and `P2WSH` in coinjoin outputs

- WalletWasabi.Daemon/Global.cs
- WalletWasabi/Wallets/Wallet.cs
- WalletWasabi/Wallets/WalletManager.cs
Fixes #12278 by ensuring that heights used in the `KeyManager` are at least `SegWit` activation before starting the wallet and therefore registering the event to process new filters.
This can stay in Wallet.cs if required, I felt it was more clean that way.
> Move EnsureHeightsAreAtLeastSegWitActivation to WalletManager

- WalletWasabi.Daemon/Global.cs
- WalletWasabi.Daemon/Rpc/WasabiJsonRpcService.cs
- WalletWasabi.Fluent/App.axaml.cs
- WalletWasabi.Fluent/Models/Wallets/HealthMonitor.cs
- WalletWasabi.Fluent/Models/Wallets/WalletLoadWorkflow.cs
- WalletWasabi.Fluent/Services.cs
- WalletWasabi.Tests/IntegrationTests/P2pTests.cs
- WalletWasabi.Tests/RegressionTests/BuildTransactionReorgsTest.cs
- WalletWasabi.Tests/RegressionTests/BuildTransactionValidationsTest.cs
- WalletWasabi.Tests/RegressionTests/CancelTests.cs
- WalletWasabi.Tests/RegressionTests/FilterDownloaderTest.cs
- WalletWasabi.Tests/RegressionTests/MaxFeeTests.cs
- WalletWasabi.Tests/RegressionTests/ReceiveSpeedupTests.cs
- WalletWasabi.Tests/RegressionTests/ReorgTest.cs
- WalletWasabi.Tests/RegressionTests/ReplaceByFeeTxTest.cs
- WalletWasabi.Tests/RegressionTests/SelfSpendSpeedupTests.cs
- WalletWasabi.Tests/RegressionTests/SendSpeedupTests.cs
- WalletWasabi.Tests/RegressionTests/SendTests.cs
- WalletWasabi.Tests/RegressionTests/SpendUnconfirmedTxTests.cs
- WalletWasabi.Tests/RegressionTests/WalletTests.cs
- WalletWasabi.Tests/UnitTests/Wallet/WalletBuilder.cs
- WalletWasabi/Services/WasabiSynchronizer.cs
- WalletWasabi/Wallets/Wallet.cs
Built upon #12262, this PR introduces `PeriodicRunner` in `WasabiSynchronizer` as a base class.
With this change we can rework the running logic of `WasabiSynchronizer` which before was basically a "`PeriodicRunner` by hand".
Now that the old base class was changed, we can use `PeriodicRunner` instead to run `WasabiSynchronizer` regularly.
With these changes,  `WasabiSynchronizer` was registered as a `HostedService`.
The action logic is the same, a few logical details was tweaked so it fits and behaves the same as before.
> Introduce `PeriodicRunner` in `WasabiSynchronizer`

- WalletWasabi.Fluent/TreeDataGrid/TreeDataGridPrivacyTextCell.cs
In the ui refresh branch, hovering over a cell and showing a tooltip, causes the text to be lost when the tooltip closes.
Its because the formatted text isn't cached, and was designed to only ever have a single render call for every measure.
That's not always the case.
This fixes it.
> Fix rendering issues in privacy text cell

- WalletWasabi/Hwi/Models/HwiEnumerateEntry.cs
Not all Hardware Wallets support offline PSBT via SD card. That is why this PR was created to be able to regulate this in the future.
#Solution
To be able to prepare for this task, I had to go through the datasheet on every device. It is also possible to sign the transaction with PSBT on the other HardwareWallets, but for that, you have to use another external application, which makes PSBT meaningless, because the Hardware Wallet must not be connected to the computer. In this case, it is enough to accept the transaction directly on HarwareWallet while it is connected to the computer.
#Results
- Not supported
- Supported
- Supported the Air gapped PSBT but recently has not implemented in WW
- Trezors
- Not supported 
- Supported
> Offline Psbt Workflow compatible

- WalletWasabi/Wallets/WalletManager.cs
This PR improves the performance if the user has more wallets. It will reduce the time between starting and window popup. 
**Current master:**
`WalletManager.RefreshWalletList (126)   '8' wallets loaded in 1595 ms with 18050 number of keys`
**This PR:**
`WalletManager.RefreshWalletList (137)   '8' wallets loaded in 818 ms with 18050 number of keys`
Addressing https://github.com/zkSNACKs/WalletWasabi/issues/11748#issuecomment-1892485862 
Contributes to https://github.com/zkSNACKs/WalletWasabi/issues/11748
> Open the wallet files in parallel at startup

- WalletWasabi.Fluent/Helpers/EnumerableExtensions.cs
- WalletWasabi.Fluent/Helpers/KeyManagerExtensions.cs
- WalletWasabi.Fluent/Helpers/LabelHelpers.cs
- WalletWasabi.Fluent/Helpers/WalletHelpers.cs
This PR improves by a factor ~2.5, from 2.2s to 0.8s (on the big wallet I use for tests), the computation of  `GetMostUsedLabels`.
This function is used a lot, and introduces delays at really annoying moments such as when you click on `Receive` or during the `Send` workflow.
This PR works by avoiding enumerating several times over the same structures, it has 2 commits:
2944241b41189df7b63c3a1b070403bc37e57ea7: Stores the `WalletId` with the Labels while fetching them for all wallets, therefore there is no need to fetch them again for the current wallet.
58d18e6ac9d584a2df38ae2e6d60edcbff62f325: Returns two `List` instead of `IEnumerable` while fetching the labels from the `KeyManager` so we avoid enumerating multiple times.
> Improve most used labels

- WalletWasabi.Daemon/Rpc/WasabiJsonRpcService.cs
- WalletWasabi.Fluent/Helpers/TransactionHelpers.cs
- WalletWasabi.Tests/Helpers/TransactionParametersBuilder.cs
- WalletWasabi/Blockchain/TransactionBuilding/TransactionBuilderWalletExtensions.cs
- WalletWasabi/Blockchain/Transactions/TransactionFactory.cs
- WalletWasabi/Blockchain/Transactions/TransactionParameters.cs
Fixes: https://github.com/zkSNACKs/WalletWasabi/issues/12118
I went with this comment https://github.com/zkSNACKs/WalletWasabi/issues/12118#issuecomment-1866578858, so this overriding "mechanism" only works via RPC for now.
How to test:
1. Call the `build` RPC endpoint with a small outgoing amount and huge fees.
2. See `TransactionFeeOverpaymentException` exception.
3. Call `buildunsafetransaction` endpoint with a small outgoing amount and huge fees.
4. See no exceptions and a successfully built transaction.
@turbolay @MarnixCroes Could you guys test this please? Much appreciated!!
> Override Fee Overpayment Protection via RPC

- WalletWasabi.Backend/Controllers/BatchController.cs
- WalletWasabi.Backend/Controllers/BlockchainController.cs
- WalletWasabi.Backend/Global.cs
- WalletWasabi.Tests/RegressionTests/BackendTests.cs
Taproot-only compact filters were created to help Trezor suite development/testing but they are not using them, however the generation of these blocks has a cost that we are paying.
> Remove Taproot-only compact filters

- WalletWasabi.Tests/UnitTests/WabiSabi/Models/MultipartyTransactionTests.cs
- WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
Wasabi only takes the exact coordination fee rate and in some situations when there are small amounts that are uneconomical it gives those amounts to miners. This PR changes that to pay the exact committed mining feerate to the miners and no more.
> Pay to miners the exact committed fee rate

- WalletWasabi.Fluent/Models/Transactions/PrivacySuggestionsModel.cs
Fixes: https://github.com/zkSNACKs/WalletWasabi/issues/11951
I used the same logic as used for coins in the critical cj phase which is the following currently:
- The pocket selector and coin-selector create an initial tx. 
- That is the tx, which is shown to the user on the tx preview dialog. 
- BnB checks if the initial tx includes critical coins, if yes then it is allowed to use them in BnB. If the initial tx is not using critical coins, then BnB won't use them either.
This PR adds the same behavior regarding unconfirmed coins.
> Try not to use unconfirmed coins when BnB.

- WalletWasabi/Services/WasabiSynchronizer.cs
Based on https://github.com/zkSNACKs/WalletWasabi/pull/12307
The try/catch in `WasabiSynchronizer` was written in a way to never stop the while loop. Now it's a `HostedService`, so exception handling is the `PeriodicRunner`'s task.
> Refactor exception catches in `WasabiSynchronizer`

- WalletWasabi.Documentation/WasabiSetupRegtest.md
https://github.com/zkSNACKs/WalletWasabi/blob/master/WalletWasabi.Documentation/WasabiSetupRegtest.md was outdated
> Knots version fixing and document update

- WalletWasabi.Fluent/Models/Wallets/HardwareWalletModel.cs
fixes: #12090
When we send transactions with many inputs to HW, sending the transaction to the device takes longer than usual, so I changed the timeout to dynamic.
Opinion:
A transaction with 1 input takes about 7-10 seconds
For 2 inputs, this number is 14-19 seconds
The current default timeout was 3 minutes. So if, say, in the case of 10 inputs, the number is about 100 seconds, given a safety margin, this should be good.
> Fixing large transaction inputs timeout

- CONTRIBUTING.md
I see lines like:
`_ = Directory.CreateDirectory()` in the codebase. 
This rule is to dismiss them - it is unnecessary and causes inconsistency.
> Update CONTRIBUTING.md - add rule for unused return values

- WalletWasabi.Fluent/Behaviors/HistoryItemTypeClassBehavior.cs
- WalletWasabi.Tests/RegressionTests/CoinVerifierApiClientStressTests.cs
- WalletWasabi.Tests/RegressionTests/IdempotencyRequestCacheStressTests.cs
- WalletWasabi.Tests/UnitTests/Blockchain/TransactionBuilding/BranchAndBoundTests.cs
- WalletWasabi.Tests/UnitTests/Blockchain/TransactionOutputs/CoinsRegistryTests.cs
- WalletWasabi.Tests/UnitTests/JsonConverters/ByteArrayJsonConverterTests.cs
- WalletWasabi.Tests/UnitTests/Tor/Control/TorControlClientTests.cs
- WalletWasabi.Tests/UnitTests/Tor/Control/Utils/AsyncEventParserTests.cs
- WalletWasabi.Tests/UnitTests/Tor/Socks5/Pool/TorHttpPoolTests.cs
- WalletWasabi.Tests/UnitTests/WabiSabi/Client/CoinJoinCoinSelectionTests.cs
- WalletWasabi.Tests/UnitTests/Wallet/FilterProcessor/BlockFilterIteratorTests.cs
- WalletWasabi.Tests/UnitTests/WalletDirTests.cs
- WalletWasabi.Tests/UnitTests/Wallets/SpecificNodeBlockProviderTests.cs
- WalletWasabi/BitcoinCore/Mempool/Mempool.cs
- WalletWasabi/Blockchain/Transactions/AllTransactionStore.cs
- WalletWasabi/Blockchain/Transactions/TransactionStore.cs
- WalletWasabi/Helpers/IoHelpers.cs
- WalletWasabi/Stores/BlockFilterSqliteStorage.cs
- WalletWasabi/Tor/Control/Messages/Events/StatusEvents/BootstrapStatusEvent.cs
- WalletWasabi/Tor/Control/TorControlClient.cs
- WalletWasabi/Tor/TorMonitor.cs
- WalletWasabi/Userfacing/CurrencyInput.cs
- WalletWasabi/WabiSabi/Backend/Banning/CoinVerifier.cs
- WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
- WalletWasabi/Wallets/SpecificNodeBlockProvider.cs
- WalletWasabi/Wallets/WalletFilterProcessor.cs
Consequence of https://github.com/zkSNACKs/WalletWasabi/pull/12335.
> Remove unnecessary _ = from the code

- WalletWasabi.Tests/UnitTests/WabiSabi/Client/IsRoundEconomicTests.cs
- WalletWasabi/WabiSabi/Client/CoinJoinClient.cs
Problem found by @Kruwed 
tl;dr: When you are willing to wait for several days for the best moment of the month, you are also willing to wait few extra hours for the best moment of the day
Currently, `IsRoundEconomic` only takes into consideration the `MedianFeeRate` related to the exact `TimeFrame` selected in user's Coinjoin settings,
But in cases where a `FeeRateMedian` for a short `TimeFrame` is lower than the `FeeRateMedian` for a longer `TimeFrame` , and the user has the longer `TimeFrame` in its settings, `IsRoundEconomic` will allow coinjoin.
---
Example:
Median past day, 24 sat/vbyte
Median past week, 27 sat/vbyte
Median past month, 35 sat/vbyte
The user has `Weekly` selected, the current coinjoin round's fee rate is 26 sat/vb
Currently, `IsRoundEconomic` will return `true`, …
> Apply time preference check for all lower TimeFrames

- WalletWasabi.Fluent/Converters/MoneyConverters.cs
- WalletWasabi.Fluent/Views/Wallets/Home/Tiles/WalletBalanceTileView.axaml
Fixes #12371 
It copies the same number as displayed but without the `~()` (so it also copies `USD`)
_Thanks @soosr for the quick help_
> Copy USD Balance to ToUsdFriendlyDecimals

- WalletWasabi.Fluent/Behaviors/FlyoutSuggestionBehavior.cs
- WalletWasabi.Fluent/Controls/CurrencyEntryBox.axaml.cs
- WalletWasabi.Fluent/Controls/DualCurrencyEntryBox.axaml.cs
- WalletWasabi.Fluent/Views/Wallets/Send/SendView.axaml
This PR makes the CurrencyEntryBox release-ready on master. If https://github.com/zkSNACKs/WalletWasabi/pull/11966 fails to be ready, we will go with this solution, and finish that PR after the release (as that PR is better in terms of functionality).
**Tests are very much welcomed.**
> [UI] CurrencyEntryBox - hotfix for release 

- WalletWasabi.Fluent/ViewModels/Wallets/CoinJoinStateViewModel.cs
related https://github.com/zkSNACKs/WalletWasabi/issues/12195
I think `Skipping this round` is the best option.
Suggestions welcome
`Randomly skipping this round`, random could be confusing
`Skipping this round for better privacy`, getting better privacy by not participating in a coinjoin seems backwards
> musicbox: update RandomlySkippedRoundMessage

- Directory.Packages.props
- WalletWasabi.Fluent.Desktop/packages.lock.json
- WalletWasabi.Fluent/App.axaml
- WalletWasabi.Fluent/ViewModels/ApplicationViewModel.cs
- WalletWasabi.Fluent/packages.lock.json
https://github.com/zkSNACKs/WalletWasabi/pull/12392
> [Release] Avalonia update

- WalletWasabi.Fluent/Views/Wallets/WalletView.axaml
This simply moves the Buy Anything Button to the right position compared to Send and Receive buttons.
The main functions of the wallet are to send and receive bitcoin so I guess it makes sense to put those first (left).
PR:
Master:
> [UI][Trivial] Change BAB's position

- WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/PrivacyRing/PrivacyRingItemViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/PrivacyRing/PrivacyRingViewModel.cs
- WalletWasabi.Fluent/Views/Wallets/Home/Tiles/PrivacyRing/PrivacyRingItemDetailsView.axaml
Shows `min-max` range AnonScore in the Privacy Ring segments whenever they represent a group of coins grouped together by PrivacyLevel.
Fixes #12373
> Privacy Ring - AnonScore Range for PrivacyLevel Segments

- WalletWasabi.Fluent/ViewModels/Wallets/Buy/OrderViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Buy/Workflows/ShopinBit/1_Initial/StartConversationStep.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Buy/Workflows/ShopinBit/2_Delivery/AcceptOfferStep.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Buy/Workflows/ShopinBit/2_Delivery/SaveConversationStep.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Buy/Workflows/ShopinBit/4_Finished/OrderFinishedMessage.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Buy/Workflows/ShopinBit/ShopinBitWorkflow.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Buy/Workflows/Workflow.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Buy/Workflows/WorkflowStep.cs
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/12403
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/12156
Relevant commit from https://github.com/zkSNACKs/WalletWasabi/pull/12391. It got merged when the original PR was merged.
> Improves error handling on #12181
> 
> This will show the error dialog only the first time an error comes out for a non-interactive step (such as `StartConversationStep`). For interactive steps (which require user input), these are reset whenever an error occurs within their execution, which means the user will have to re-enter their input in order to retry the action, which is the expected UX:
> 
> Interactive: user input -> try action -> error message -> user input -> retry action -> error message -> user input....
> 
> Non interactive: try action …
> [UI] Chat workflow better error handling

- WalletWasabi.Fluent/ViewModels/Wallets/Buy/BuyViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Buy/IOrderManager.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Buy/OrderViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Buy/Workflows/Workflow.cs
This PR:
- Shows an error dialog to the user when an error happens in a noninteractive step.
- Only if the Buy Anything dialog is opened.
- An error can only be displayed once.
- Provides an actual error message to the user instead of a meaningless message.
> [UI] BAB - Error dialog improvement

- WalletWasabi.Fluent/ViewModels/Wallets/Buy/BuyViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Buy/OrderViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Buy/Workflows/Workflow.cs
Whenever the Conversation changes in the active Order, the messages should be marked as read.
It includes a check to avoid stack overflow when marking all messages as read modifies the Conversation.
Fixes #12404
> [UI] Fix wrong unread badge

- WalletWasabi/Helpers/HardwareWalletOperationHelpers.cs
Hardware wallets can provide ANY "key at path", while it is not certain that there is an implementation behind it.
Most of HW doesn't support the Taproot Account yet but can provide us with the KeyPath.
So, this is a hotfix until we don't find a good solution for it.
Transaction sign tested with these models:
> Disable Taproot KeyPath under HW first connection

- WalletWasabi.Fluent/Controls/Dialog.axaml.cs
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/12430
> [VDG] Use RoutingStrategies.Bubble for pointer event for closing dialog

- WalletWasabi.Fluent/Helpers/TransactionHelpers.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Send/SendViewModel.cs
- WalletWasabi/Userfacing/Bip21/Bip21UriParser.cs
Fixes #12365
There are 3 problems that this PR fixes:
- Parsing of the PJ part of BIP21 is not working anymore
- `GetPayjoinClient` is relying on the `PersistentConfig` which was not taking into account `--usetor` CLI overriding
I didn't test a full PJ but the request is correctly initiated with this PR
> Fix PayJoin

- WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
@MarnixCroes found this.
The issue:
```
ERROR	CoinJoinManager.HandleCoinJoinFinalizationAsync (549)	Wallet (Wallet): CoinJoinClient failed with exception: 'WalletWasabi.WabiSabi.Backend.Models.WabiSabiProtocolException: Round (492ec6c2351785e3fe8e66b58328af7bf82244653aec6ef44b496d94b8f8e249): Wrong phase (Ended).
at WalletWasabi.Tor.Http.Extensions.HttpResponseMessageExtensions.ThrowUnwrapExceptionFromContentAsync(HttpResponseMessage me, CancellationToken cancellationToken) in WalletWasabi/Tor/Http/Extensions/HttpResponseMessageExtensions.cs:line 77
at WalletWasabi.WabiSabi.Client.WabiSabiHttpApiClient.SendWithRetriesAsync[TRequest](RemoteAction action, TRequest request, CancellationToken cancellationToken, Nullable`1 retryTimeout) in …
```
> Catch wrong phase exception in CJManager in case of detected double spend

- WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
Same as https://github.com/zkSNACKs/WalletWasabi/pull/12450
> [Release] Catch wrong phase exception in CJManager in case of detected double spend

- WalletWasabi/BuyAnything/BuyAnythingManager.cs
- WalletWasabi/WebClients/ShopWare/Models/Order.cs
There must've been a change in their protocol but now the shipping cost is not under `"shippingCosts"`, but under `"deliveries": [{...,"shippingCosts",...}]"`. I'll ask about this change, but for the time being this solves our issue.
EDIT:
Updated the PR, now it should get the total shipping cost from either under `shippingCosts` or `deliveries`, whichever is available. Also makes sure to send the correct data towards the UI.
> [BaB] Fix shipping cost not showing

- WalletWasabi.Daemon/Global.cs
- WalletWasabi/Blockchain/Transactions/TransactionStore.cs
- WalletWasabi/Wallets/WalletManager.cs
Remove the temporary code made for #12202.
Please @molnard decide if you want to remove it for 2.0.6 or let it and remove in 2.0.7
If we do not remove it, we will release some temporary code, this might be OK but I wanted to make the PR to give you the option to not.
If we remove it, there might be some people who updated to the faulty master and didn't update to master again for the forced resync.
> Remove temporary resync code

- WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
Possibly fixes: https://github.com/zkSNACKs/WalletWasabi/issues/12408
Unfortunately, I was unable to recreate the environment of the original issue, so I tried to fix it in theory.
My theory:
- After the successful CJ, we check if the wallet became private or not. According to the original issue, the wallet did become private, but `StopWhenAllMixed = false` so we schedule the next CJ.
https://github.com/zkSNACKs/WalletWasabi/blob/master/WalletWasabi/WabiSabi/Client/CoinJoinManager.cs#L581-L589
- On the next CJ, when we do the sanity checks and the selection of candidate coins, we find out that the wallet is private and we throw `CoinJoinClientException(CoinjoinError.AllCoinsPrivate)`
https://github.com/zkSNACKs/WalletWasabi/blob/master/WalletWasabi/WabiSabi/Client/CoinJoinManager.cs#L207-L …
> Fix "StopWhenAllMixed = false doesn't work"

- WalletWasabi.Fluent/TreeDataGrid/TreeDataGridPrivacyTextCell.cs
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/12509
> [VDG] Fix TreeDataGridPrivacyTextCell rendering

- WalletWasabi/WabiSabi/Client/CoinJoinCoinSelector.cs
`largestAllowedCoin` must have been a concept we used in the past but we are not anymore, because it's the only place we use it and it's nothing more than a fancy empty check.
I also removed the `else` which was useless as well.
> [Trivial] Remove useless check in CoinJoinCoinSelector

- WalletWasabi/Wallets/Wallet.cs
Fixes #12514 
It's not really important, but still, this looks safe and makes more sense, as the check `AssertNetworkOrClearBlockState` is clearly something that should happen pre-initialisation.
We can backport it as it looks pretty safe but it's not super important either as the problem only occurs when messing with wallet files.
> Fix WFP crash when network changes

- WalletWasabi/BuyAnything/BuyAnythingManager.cs
Wasabi crashes without the internet on TestNet because BaB tries to get the countries and the error is not handled. On MainNet this is not happening as the countries are constant and stored in a file, so Wasabi just loads them. 
Source: https://github.com/zkSNACKs/WalletWasabi/pull/12504#issuecomment-1956476539
> Fix crash when countries cannot be retrieved.

- WalletWasabi.Documentation/WasabiCompatibility.md
- WalletWasabi.Tests/AcceptanceTests/HwiKatas.cs
- WalletWasabi.Tests/Helpers/HwiValidationHelper.cs
- WalletWasabi.Tests/UnitTests/Hwi/HwiProcessBridgeMock.cs
- WalletWasabi.Tests/UnitTests/Hwi/MockedDeviceTests.cs
- WalletWasabi/Hwi/Models/HwiEnumerateEntry.cs
Equivalent of https://github.com/zkSNACKs/WalletWasabi/pull/12341
Files changes are a bit different, because https://github.com/zkSNACKs/WalletWasabi/pull/12390 already added the `WalletType.BitBox` to the codebase.
Guys, any reason why we left out the BitBox implementation from the release??
- If there is, close this PR.
- If not, then I'm glad Thib reached out to me and asked questions.
> [Release] Add missing BitBox implementation?

- WalletWasabi.Fluent/Models/Wallets/HealthMonitor.cs
- WalletWasabi/Services/WasabiSynchronizer.cs
The UI relies on the `WasabiSynchronizer` request and `BackendStatus` property to determine the status to be displayed for the user - that is working fine.
But it also effect the wallet load. If the backend is available the wallet will sync before displaying the wallet page. If the backend is not it will just show the wallet page with the warning of the balance might not be accurate. 
We have a bug there. In some cases, the loading never finishes when the backend is down. I emulated it by turning off my network. 
The reason is sometimes we got different exception (Tor SOCKS5 proxy responded with TtlExpired) that we assume and after some cumbersome logic we arrive [to the point of waiting to the backend](https://github.com/molnard/WalletWasabi/blob/master/WalletWasabi.Fluent/Models/Wallets/ …
> Simplify synchronizer gensock event reporting

- WalletWasabi.Fluent/Models/Wallets/WalletCoinjoinModel.cs
Fixes: https://github.com/zkSNACKs/WalletWasabi/issues/12525
Spectrum control visibility binds to:
https://github.com/molnard/WalletWasabi/blob/master/WalletWasabi.Fluent/Views/Shell/MainScreen.axaml#L25
This is where the path ends, the IsRunning property:
https://github.com/molnard/WalletWasabi/blob/master/WalletWasabi.Fluent/Models/Wallets/WalletCoinjoinModel.cs#L60
That observable is merged from 3 other observables. One of them was not working, see the fix.
> CompletedEventArgs was not forwarded in the the observable chain

- WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/PrivacyRing/PrivacyRingViewModel.cs
- WalletWasabi.Fluent/Views/Wallets/Home/Tiles/PrivacyRing/PrivacyRingView.axaml
- Removes Carousel UI element from Privacy Ring view
- Fade in animation has been temporarily disabled to prevent the glitches. Will restore it in a future PR.
- Fixes #12537
- Attempt to fix #12495. I could not reproduce this issue so I'm not sure 100% that it's fixed in this PR. @yahiheb can you confirm?
> [VDG] Privacy Ring - Remove Carousel

- WalletWasabi.Documentation/ClientRelease/ReleaseNotesTemplate.md
After we updated from .Net 7.0 to .Net 8.0 #11897, the macOS minimum version requirement was changed also.
Same as: #12534
> [Trivial] Update ReleaseNotesTemplate.md

- WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
Reverts zkSNACKs/WalletWasabi#12502
Unfortunately, this mix will never stop in autocj mode. To fix the original issue we will need a larger refactor. 
This line shows that if autocj is turned on StopWhenAllMixed is always false - rendering the business to never stop mixing. 
https://github.com/molnard/WalletWasabi/blob/master/WalletWasabi.Fluent/ViewModels/Wallets/CoinJoinStateViewModel.cs#L109
> Revert "Fix "StopWhenAllMixed = false doesn't work""

- WalletWasabi.Fluent/ViewModels/Wallets/CoinJoinStateViewModel.cs
- WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
Fixes: https://github.com/zkSNACKs/WalletWasabi/issues/11380
With this PR the music box will display hurray! and stop there without any buttons. If the balance or the anonscore target changes the button can appear and the user presses it to start mixing. 
There is no way for the user to forcefully continue mixing if all coins are private. 
With autocoin everything is the same, like before except the hurray message will be displayed but it will continue CJ in case of new coins or anonscore change. 
Ancestor https://github.com/zkSNACKs/WalletWasabi/pull/12540
> Add missing state machine transition when wallet reached 100% - take 2

- .gitignore
I am using Visual Studio and when I added `--loglevel=debug` as the default project-level command line argument it created a file: `launchSettings.json`. This file will never be required for version control it contains custom launch rules.
> Ignore visual studio launchSettings.json

- WalletWasabi/WabiSabi/Client/CoinJoinManager.cs
Fixes an issue reported here: https://github.com/zkSNACKs/WalletWasabi/issues/12536#issuecomment-1962363029 where if your wallet is fully private and then some coins are coming the CoinJoinManager will start coinjoin when it would be better to wait for confirmation
It is the way to fix it with the less probability of breaking things, but maybe it still breaks 1000 other things. IMO this issue is an important one because it is highly inefficient in a standard case.
> Don't mix if all non-private coins are unconfirmed.

- WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModel.cs
In Debug mode it is always visible.
In Release mode it is only visible when balance > 0 or there is already an order.
> BAB - fix visibility on testnet

- WalletWasabi.Tests/Helpers/WabiSabiFactory.cs
- WalletWasabi.Tests/UnitTests/Bases/ConfigManagerTests.cs
- WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepInputRegistrationTests.cs
- WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepTransactionSigningTests.cs
- WalletWasabi.Tests/UnitTests/WabiSabi/Backend/Rounds/MultipartyTransactionStateTests.cs
- WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
- WalletWasabi/WabiSabi/Backend/WabiSabiConfig.cs
An alternative solution to https://github.com/zkSNACKs/WalletWasabi/pull/12444 according to https://github.com/zkSNACKs/WalletWasabi/pull/12444#pullrequestreview-1885764516.
According to [Lucas's comment](https://github.com/zkSNACKs/WalletWasabi/pull/12444#issuecomment-1955283328) this will be OK. 
We only use the config when we destroy and create the blame round. 
This is a simpler solution than https://github.com/zkSNACKs/WalletWasabi/pull/12444. It does not add anything to the round. 
Check diff [HERE](https://github.com/zkSNACKs/WalletWasabi/pull/12524/files?diff=split&w=1).
The main idea is to move the round-ending logic into the CreateBlameRound method:
- Remove code duplication
- Easier to see that the config is only used to determine if we create the blame round or not.
> Introduce MinInputCountByBlameRound - simple

- WalletWasabi.Fluent/Models/Wallets/CoinModel.cs
- WalletWasabi.Fluent/ViewModels/Dialogs/LabelEntryDialogViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Advanced/WalletCoins/WalletCoinsViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/PrivacyControlTileViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/PrivacyRing/PrivacyBarViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/PrivacyRing/PrivacyRingViewModel.cs
- Removes change notification subscriptions from `SmartCoin` inside `CoinModel` constructor.
- Moves these to a dedicated method `SubscribeToCoinChanges()`
- Uses this method only in
- `WalletCoinsViewModel`
- `PrivacyRingViewModel`
- This leaves the following ViewModels subscription-free:
- `PrivacyControlTileViewModel`
- `PrivacyBarViewModel`
- These two do not use coin information other than PrivacyLevel, which isn't affected by the subscriptions.
- Startup time will no longer be affected by this; however, noticeable delay will occur when opening Wallet Coins and Privacy Ring for wallets with large number of UTXOs.
- Fixes #12547
> [VDG] WalletCoinsModel - Deferred Subscription

- WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
Round destroyer is broken since deployment of #12524 because `roundDestroyerInputCount = 440`, which is higher than `MaxInputCountByRound` (400). However, it must always be lower.
This clearly shows how unintuitive is this code, those multipliers etc etc... We should remove all that and refactor more simply.
Something else, we had extremely good rounds while having this bug. Maybe we should reconsider how this round destroyer is working.
> Add sanity check for round destroyer threshold

- WalletWasabi.Daemon/Global.cs
- WalletWasabi.Tests/IntegrationTests/P2pTests.cs
- WalletWasabi.Tests/RegressionTests/BuildTransactionReorgsTest.cs
- WalletWasabi.Tests/RegressionTests/BuildTransactionValidationsTest.cs
- WalletWasabi.Tests/RegressionTests/CancelTests.cs
- WalletWasabi.Tests/RegressionTests/MaxFeeTests.cs
- WalletWasabi.Tests/RegressionTests/ReceiveSpeedupTests.cs
- WalletWasabi.Tests/RegressionTests/ReplaceByFeeTxTest.cs
- WalletWasabi.Tests/RegressionTests/SelfSpendSpeedupTests.cs
- WalletWasabi.Tests/RegressionTests/SendSpeedupTests.cs
- WalletWasabi.Tests/RegressionTests/SendTests.cs
- WalletWasabi.Tests/RegressionTests/SpendUnconfirmedTxTests.cs
- WalletWasabi.Tests/RegressionTests/WalletTests.cs
- WalletWasabi.Tests/UnitTests/Wallet/WalletBuilder.cs
- WalletWasabi/Wallets/Wallet.cs
- WalletWasabi/Wallets/WalletFactory.cs
- WalletWasabi/Wallets/WalletManager.cs
This PR
* Adds a `WalletFactory` type 
* Removes the static `Wallet.CreateAndRegisterServices` method
* Removes the `Wallet.CreateWalletInstance` method
* Removes the `Wallet.BlockProvider` property because it was only used to create `WalletFilterProcessor` in the `Wallet.ctor`.
* ... is just refactoring, no functional change is intended here
This PR is meant to be a precursor to #12562
> Add `WalletFactory` type

- WalletWasabi.Fluent/Helpers/TransactionFeeHelper.cs
- WalletWasabi.Tests/UnitTests/AllFeeEstimateTests.cs
- WalletWasabi.Tests/UnitTests/BitcoinCore/RpcBasedTests.cs
- WalletWasabi/BitcoinCore/Monitoring/RpcFeeProvider.cs
- WalletWasabi/Blockchain/Analysis/FeesEstimation/AllFeeEstimate.cs
- WalletWasabi/Blockchain/Analysis/FeesEstimation/HybridFeeProvider.cs
- WalletWasabi/Blockchain/Analysis/FeesEstimation/ThirdPartyFeeProvider.cs
- WalletWasabi/Extensions/RPCClientExtensions.cs
- WalletWasabi/WebClients/BlockstreamInfo/BlockstreamInfoClient.cs
This PR removes the `EstimationMode` property because it is and always was `Conservative`. It also removes the `IsAccurate` because it assumes bitcoin nodes can give us back erroneous estimations under some specific conditions but that's not the case, bitcoin nodes return error if they cannot give us good enough estimations.
This is something required to simplify the synchronization mechanism based on websockets.
> Simplify estimation code

- WalletWasabi.Fluent/Extensions/ObservableExtensions.cs
- WalletWasabi.Fluent/Models/Wallets/CoinModel.cs
- WalletWasabi.Fluent/Models/Wallets/WalletCoinsModel.cs
OK, after some testing I've come to the conclusion that instances of CoinModel **were not being disposed**.
I still need to investigate the reason why this happened, because CoinModel's subscriptions **shared the same lifespan of their parent CoinModel**, so, as soon as the CoinModel is not longer used, the subscriptions should have been GC'd as well.
It's interesting to notice that we called `WhenAnyValue` correctly (calling it right after the `this` keyword). This, in theory, makes it unnecessary to explicitly implement IDisposable. 
For some reason, this didn't happen. The instances survived.
This PR ensures that CoinModels are disposed as well as their subscriptions, if any.
> [UI] Fix potential memory leaks

- WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
Addresses: https://github.com/zkSNACKs/WalletWasabi/pull/12585#discussion_r1508832348
Why is this so important for me?
Because in case there is an issue in the backend and we need to investigate it, more or less the logs are our only weapon.
If we cannot trust the logs or the logs are inaccurate, the investigation becomes much harder.
`master` produces logs like this:
```
2024-03-01 11:51:57.989 [71] INFO	Arena.CreateRoundsAsync (540)	Destroyed round with 360 inputs. Threshold: 450
```
This is NOT urgent to deploy.
> Fix logging when we destroy a round (LoadBalancer)

- WalletWasabi/Blockchain/TransactionOutputs/CoinsRegistry.cs
All coinbase transactions have the exact same dummy input and for that reason the coinregistry fails to handle coins generated by miners.
> Avoid caching non-existing inputs

- WalletWasabi/Blockchain/Transactions/TransactionStore.cs
Fixes #12520 
@MarnixCroes look if you prefer this, but we won't do another fix and logging only once for both files as it would be annoying to do because of the design.
> Log end of transaction file migration to SQL

- WalletWasabi.Backend/Controllers/BlockchainController.cs
It was probably left out when we removed the Taproot only filters.
Ultra trivial PR.
> [Trivial] Fix warning in Blockchain Controller

- WalletWasabi/WabiSabi/WabiSabiCoordinator.cs
We might have banned some inputs without any reason since the delta PR.
> IsWasabiCoinJoinLookingTx need to account for delta

- .github/notify-users-config.json
- .github/workflows/mention_users_on_filechange.yml
Fixes: https://github.com/zkSNACKs/WalletWasabi/issues/10516
This is adding a simple script that will mention specific users on specific file changes. 
If one user mentioned once at a PR the script will never mention him again.  
P.S. Why JavaScript? 
> The use of JavaScript in the GitHub Actions script, particularly within the github-script action, is because the github-script action itself is designed to run JavaScript (JS) code directly within your workflow. This allows you to interact with the GitHub API and perform a wide range of operations based on the context of your GitHub repository, pull requests, issues, and more, without needing to set up a separate environment or external dependencies.
> Add mention_users_on_filechange.yml script

- WalletWasabi.Fluent/Controls/CurrencyEntryBox.axaml.cs
- WalletWasabi.Fluent/Controls/DualCurrencyEntryBox.axaml.cs
- WalletWasabi.Fluent/Extensions/CurrencyExtensions.cs
- Formats BTC values using exactly 8 fractional digits `"0000 0000"` when entering fiat values in the Dual Currency Entry Box.
- Formats BTC values using the exact number of fractional digits (up to 8) when pasting values from clipboard. This way, pasting `0.00100` will result in `0.0010 0` instead of just `0.001`
- Fixes #12649
> [VDG] Format BTC with Fixed Fractional

- WalletWasabi/BitcoinCore/Processes/BitcoindRpcProcessBridge.cs
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/12580
> Fix wrong `DataDir` error on Windows for Knots

- WalletWasabi/Wallets/WalletManager.cs
The PR removes an event that had no handlers
> Delete unused event

- WalletWasabi/Hwi/Parsers/HwiParser.cs
This error came with Trezor Safe 3 because when I used the HWI enumerate command, the type in the response was "trezor_safe 3". When I tried to use it in the parser, it returned with an error because of the "space" character.
So the solution is that I need to replace the "space" character in HardwareWalletModels parsing part.
> Fix typestring before HardwareWalletModels parsing

- WalletWasabi.Tests/UnitTests/WabiSabi/Backend/CoordinatorTests.cs
- WalletWasabi/WabiSabi/Backend/Rounds/Arena.Partial.cs
- WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
- WalletWasabi/WabiSabi/WabiSabiCoordinator.cs
Close https://github.com/zkSNACKs/WalletWasabi/issues/12643
This PR introduces a new criterion to abort a round after a participating input is spent. Now, only those affected rounds paying a lower fee rate than the attacking transaction will be aborted, this means that a round paying a higher fee rate is expected to replace the attacking transaction.
> Do not abort rounds paying more than attacker

- WalletWasabi.Fluent.Generators/Generators/AutoInterfaceGenerator.cs
There is, eg, `HealthMonitor` and we generate an `IHealthMonitor` interface for it. However, `IHealthMonitor` adds `Dispose` method even though it hides an existing one for `HealthMonitor`.
This PR is PoC what we can posssibly do about it. It's certainly not perfect (performance-wise).
The generated `IHealthMonitor` looks like this:
```cs
public partial interface IHealthMonitor
{
ICollection<Issue> TorIssues { get; }
bool UseTor { get; }
bool UseBitcoinCore { get; }
TorStatus TorStatus { get; set; }
BackendStatus BackendStatus { get; set; }
bool IsConnectionIssueDetected { get; set; }
RpcStatus? BitcoinCoreStatus { get; set; }
int Peers { get; set; }
bool IsP2pConnected { get; set; }
HealthMonitorState State { get; set; }
bool CriticalUpdateAvailable { get; set; }
bool UpdateAvailable { …
```
> `AutoInterfaceGenerator`: Skip interface method implementations

- WalletWasabi.Fluent/ViewModels/Wallets/CoinJoinStateViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModel.cs
- WalletWasabi.Fluent/Views/Wallets/MusicControlsView.axaml
Makes CJ settings easier to discover by a "..." menu in the Music Box.
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/9432
> [UI] Make CJ settings more discoverable via MusicBox

- WalletWasabi.Daemon/Global.cs
I don't think this behavior is OK even temporarily.
> `UpdateChecker`: Increase interval to 1 hour

- WalletWasabi.Packager/MacSignTools.cs
Fixes: https://github.com/zkSNACKs/WalletWasabi/issues/12722
Looks like `altool` is obsolete and that caused the issue.
Very useful Apple documentation I used on how to migrate from `altool` to `notarytool`
https://developer.apple.com/documentation/technotes/tn3147-migrating-to-the-latest-notarization-tool
According to the apple documentation:
> Apple has deprecated altool for the purposes of notarization and [announced that it will stop working for notarization on 2023-11-01](https://developer.apple.com/news/?id=y5mjxqmn).
New process:
`notarytool submit --wait --apple-id \"{appleId}\" -p \"WasabiNotarize\" \"{filePath}\"`
- submit: upload the file for notarization
- wait: wait for the notazition to finish. With this we don't need to check the status of the notarization periodically.
- …
> Fix macOS notarization (signing), migrate to `notarytool`

- WalletWasabi.Documentation/WasabiCompatibility.md
- WalletWasabi.Tests/AcceptanceTests/HwiKatas.cs
- WalletWasabi.Tests/UnitTests/Hwi/HwiProcessBridgeMock.cs
- WalletWasabi.Tests/UnitTests/Hwi/MockedDeviceTests.cs
- WalletWasabi.Tests/UnitTests/WalletDirTests.cs
- WalletWasabi/Hwi/Models/HardwareWalletModels.cs
- WalletWasabi/Hwi/Models/HwiEnumerateEntry.cs
- WalletWasabi/Hwi/Parsers/HwiParser.cs
Fixes: #12143
The HWI already supports the Trezor Safe 3 hardware wallet, but until now, Wasabi wallet did not. Therefore, we decided to implement this in the current codebase.
We acquired a Trezor Safe 3 hardware wallet and initialized it with the appropriate parameters. After this, I implemented the new Enums, HardwareWalletModel and WalletType, in the code.
I started the Wasabi wallet and was able to add it as a wallet.
> Trezor Safe 3 implementation

- WalletWasabi/Wallets/WalletFilterProcessor.cs
Fixes partially #12703 
When P2P network is not available (such as on RegTest) but you have a full node, if for some reason a download fails from the node, the software will then enter an infinite loop trying to download from the non-existent P2P network.
This PR fixes this by retrying to get from the node.
I also converted the many ifs to switch statements because it's more readable that way.
> Fix infinite loop when getting blocks from unavailable P2P

- WalletWasabi.Tests/UnitTests/WabiSabi/Client/CoinJoinCoinSelectionTests.cs
- WalletWasabi/WabiSabi/Client/CoinJoin/Client/CoinJoinClient.cs
- WalletWasabi/WabiSabi/Client/CoinJoin/Client/CoinJoinCoinSelector.cs
- WalletWasabi/WabiSabi/Client/CoinJoin/Manager/CoinJoinManager.cs
Related to: https://github.com/zkSNACKs/WalletWasabi/issues/12602
This PR disables the `StopWhenAllMixed` feature. The change is not affecting the Manual CoinJoin mode. 
However in AutoCoin mode:
- Before this PR if the wallet is not entirely private (unconfirmed coins for example), we will keep going even if ALL the selected coins are private. 
- With this PR if the wallet is not entirely private (unconfirmed coins for example), we won't continue if ALL the selected coins are private, otherwise, we will continue. 
What happens after that? Are we restarting the client? The behavior was not changed by this PR - it is the same as before:
- In `AutoCoinJoin` mode we will keep trying no matter what, the wallet might receive new coins. 
- In ManualMode we will only stop if all coins are …
> Disable StopWhenAllMixed feature

- WalletWasabi.Fluent/Models/Wallets/BuyAnythingModel.cs
- WalletWasabi.Fluent/Models/Wallets/WalletModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Buy/BuyViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Buy/OrderViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Buy/Workflows/ShopinBit/ShopinBitWorkflow.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Buy/Workflows/Workflow.cs
- WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModel.cs
- WalletWasabi.Tests/UnitTests/ViewModels/ReceiveAddressViewModelTests.cs
- WalletWasabi.Tests/UnitTests/ViewModels/SuggestionLabelsViewModelTests.cs
- Introduces `IWalletModel.IBuyAnythingModel`
- Removes `Workflow.Create()` factory method.
- Removes responsibility of instantiation of `Workflow` class from `BuyViewModel` and moves it to `OrderViewModel`
- Makes `Workflow` implement `IDisposable`
- This PR is required by #12625 in order to properly dispose of RX subscriptions inside `Workflow` class, while maintaining ownership and lifecycle of `Workflow` instances tied to `OrderViewModel`.
> [UI] BAB Workflow Lifecycle refactor

- WalletWasabi.Tests/AcceptanceTests/HwiKatas.cs
This PR addresses https://github.com/zkSNACKs/WalletWasabi/pull/12041#discussion_r1421565482
I didn't add this for the `LedgerNanoSPlusKataAsync` test because `Ledger_Nano_S_Plus`'s regex is not in `ValidatePathString`.
Is that intentional?
I have tested this only with `Trezor T`.
> [Trivial] Use ValidatePathString for other HW models

- WalletWasabi.Fluent/Controls/DualCurrencyEntryBox.axaml.cs
- WalletWasabi.Fluent/Views/Wallets/Send/SendView.axaml
- Adds <kbd>Enter</kbd> Key functionality in Send screen:
- Hitting <kbd>Enter</kbd> while focusing the Address field moves focus to Amount.
- Hitting <kbd>Enter</kbd> while focusing on Amount field (BTC or fiat) moves focus to Labels
- Hitting <kbd>Enter</kbd> while focusing Labels field (when not typing a new label) is equivalent to clicking Next button.
- Fixes #12732
> [UI] Send: Move Focus On Enter Key

- WalletWasabi.Tests/UnitTests/Stores/IndexStoreTests.cs
- WalletWasabi/Stores/IndexStore.cs
`Try` implies that the function doesn't `throw`
`RemoveAllNewerThanAsync` uses it as if it was not throwing (otherwise, how can it return `null`???)
It's the problem here: https://github.com/zkSNACKs/WalletWasabi/pull/12400#discussion_r1532283415
> `TryRemoveLastFilterIfNewerThanAsync` should not throw

- WalletWasabi.Backend/Controllers/BlockchainController.cs
- WalletWasabi/WabiSabi/Backend/Rounds/Arena.Partial.cs
- WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
- WalletWasabi/WabiSabi/Backend/Statistics/RequestTimeStatista.cs
Backend "hiccups" are happening multiple times per day. Response times can go up 60-70 seconds for minutes. After that, everything goes back to normal. 
We are investigating and need more information. We are sniffing around the lock first. 
I want to deploy it as soon as possible because the hiccups are happening. 
Commit by commit review is easier.
> Add more statistics to backend

- .editorconfig
- BannedSymbols.txt
- Directory.Build.props
- Directory.Packages.props
- WalletWasabi.Daemon/packages.lock.json
- WalletWasabi.Fluent.Desktop/packages.lock.json
- WalletWasabi.Fluent.Generators/packages.lock.json
- WalletWasabi.Fluent/packages.lock.json
- WalletWasabi.Packager/packages.lock.json
- WalletWasabi.Tests/.editorconfig
- WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiHttpApiIntegrationTests.cs
- WalletWasabi/WebClients/Bitstamp/BitstampExchangeRateProvider.cs
- WalletWasabi/WebClients/BlockchainInfo/BlockchainInfoExchangeRateProvider.cs
- WalletWasabi/WebClients/CoinGecko/CoinGeckoExchangeRateProvider.cs
- WalletWasabi/WebClients/Coinbase/CoinbaseExchangeRateProvider.cs
- WalletWasabi/WebClients/Coingate/CoingateExchangeRateProvider.cs
- WalletWasabi/WebClients/Gemini/GeminiExchangeRateProvider.cs
- WalletWasabi/packages.lock.json
`Microsoft.CodeAnalysis.BannedApiAnalyzers` is a tool developed by Microsoft that allows to specify which .NET types, methods, etc. are forbidden to use by specifying those in a `BannedSymbols.txt` file. 
There are various use cases in general[^1] but here are a few examples:
* Some people ban `DateTime.UtcNow` because code testing with unit tests is then harder.
* Roslyn itself [uses](https://github.com/dotnet/roslyn/blob/efdb56597abbe7dff8f5df311f60375877f0b17d/eng/config/BannedSymbols.txt#L64) the analyzer to avoid performance issues.
* Dotnet runtime uses it to [nudge](https://github.com/dotnet/runtime/blob/main/src/tools/illink/src/linker/BannedSymbols.txt) devs to use correct API methods
* etc.
In Visual Studio, you should see an analyzer warning (an error actually) with an …
> Introduce support for banning API

- WalletWasabi.sln
- deps.nix
Because https://github.com/zkSNACKs/WalletWasabi/pull/12797 didn't updated the deps.nix file with the new dependency, nix cannot build (we cannot deploy) because it is deterministic. The problem is showed here: https://github.com/zkSNACKs/WalletWasabi/pull/12797#issuecomment-2057045070
This PR updates the dependencies and add the nix files ad solution items just for convenience.
> Update dependencies for deterministic build

- WalletWasabi.Fluent/Helpers/CoinPocketHelper.cs
- WalletWasabi.Tests/UnitTests/Transactions/TransactionProcessorTests.cs
> Use helper privacy functions in `GetPockets`

- WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepConnectionConfirmationTests.cs
- WalletWasabi/WabiSabi/Backend/DoSPrevention/Offender.cs
- WalletWasabi/WabiSabi/Backend/DoSPrevention/Prison.cs
- WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
This PR doesn't necessarily have to be merged as it is, but it's more of an ice-breaker let's say.
The point is simple: When there are MANY (arbitrarily many) inputs misbehaving, the coordinator should take the blame on himself, and not blame the clients.
It's really unlikely that more than 30% of the clients misbehave, the problem must have been the coordinator having an issue during the phase and be unable to process the requests during that time.
I believe that merging of such concept would make the problem to almost disappear, as the vast majority of coins banned incorrectly are banned in huge batches like this.
If we want to merge this, maybe 25%, 20% or 15% would be better than 30%, I wrote the number for sake of illustration
> Mitigate bans because of coordinator lag

- azure-pipelines-linux.yml
fixes: #12855 
##Description
Hwi broke the CI for some reason in the Mock Tests place. But in the local machines, the tests are passed. 
##Solution
I needed to increase the Ubuntu version number in linux.yml to 22.04.
> Fix CI failing with ubuntu version increase

- WalletWasabi.Tests/UnitTests/WabiSabi/Backend/CoordinatorTests.cs
- WalletWasabi/WabiSabi/Backend/Rounds/Arena.Partial.cs
The DoS prevention was aborting round in input-registration phase when Arena already can detect that and remove offending Alices without needing to disrupt the round.
Update: this reduces the need to call GetTxOutAsync method so often and reduce the workload for the bitcoin node.
> Do not abort round in input registration

- WalletWasabi.Fluent/Helpers/MacOsStartupHelper.cs
- WalletWasabi.Fluent/Helpers/StartupHelper.cs
Fixes a bug introduced in this release that can cause a crash to users in cases where they have installed Wasabi on macOs since a really long time, enabled `RunOnSystemStartUp`, but don't have anything else on their session that runs on startup.
`LaunchAgents` doesn't exist by default, `Library` does but I check it as well in case user deleted it.
I tested and it fixes the problem, sorry for that, didn't realize while reviewing that those folders didn't exist by default!!
> Create Library and LaunchAgents folder if they don't exist

- WalletWasabi.Fluent/Helpers/MacOsStartupHelper.cs
- WalletWasabi.Fluent/Helpers/StartupHelper.cs
Taken from https://github.com/zkSNACKs/WalletWasabi/pull/12869
> [Release] Create Library and LaunchAgents folder if they don't exist

- WalletWasabi/Helpers/Constants.cs
It seems that the constants is not used anymore. It looks like we can remove it. 
If somebody is depending on it, it's easy to do it in a 3rd party library.
> Remove unused `Constants.OutputSizeInBytes` constant

- WalletWasabi.Fluent/Styles/MenuItem.axaml
Forgot to do it in UI Refreshment. It will make the text more noticeable.
Before:
After:
> [UI] MenuItem - make icons less emphazied

- WalletWasabi.Packager/Program.cs
fixes: [#12610](https://github.com/zkSNACKs/WalletWasabi/issues/12610)
The best solution was that under the Ubuntu system, during or somehow after the WW installation, the "installudevrules" command of HWI should be executed to further facilitate usability for the users.
To achieve this, it was necessary to implement the "postinst" script which runs after the installation and performs the necessary steps.
> Install udevrules with Ubuntu distribution

- WalletWasabi/BitcoinP2p/P2pNetwork.cs
- WalletWasabi/Blockchain/TransactionBroadcasting/TransactionBroadcaster.cs
- WalletWasabi/Blockchain/TransactionBuilding/TransactionModifierWalletExtensions.cs
- WalletWasabi/BuyAnything/BuyAnythingManager.cs
- WalletWasabi/Tor/Socks5/Pool/Circuits/DefaultCircuit.cs
- WalletWasabi/Tor/Socks5/Pool/Circuits/OneOffCircuit.cs
- WalletWasabi/Tor/Socks5/Pool/Circuits/PersonCircuit.cs
- WalletWasabi/WabiSabi/Client/CoinJoin/Client/UtxoSelectionParameters.cs
- WalletWasabi/Wallets/P2PNodesManager.cs
Removing the remaining InsecureRandom usage.
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/10857
> Removing the remaining InsecureRandom usages

- WalletWasabi.Documentation/ClientRelease/ReleaseNotesTemplate.md
- WalletWasabi.Documentation/WasabiCompatibility.md
As long as HWI doesn't come out with a new version, we need to increase the minimum Ubuntu version number, because currently, it can't run on the older 20.04 version.
Main issue:
https://github.com/bitcoin-core/HWI/issues/732
> Update WasabiCompatibility.md because of HWI

- WalletWasabi/Services/SatoshiSynchronizer.cs
At the time of opening this PR several blocks were mined per second and there were many reorgs. We were logging this as errors instead of debug or info. 
Also, if there is a problem closing the websocket and exception was not caught (to ignore). 
----
Client log
```
2024-04-23 22:05:00.531 [9] ERROR       SatoshiSynchronizer.ExecuteAsync (132)  Inconsistent index state detected.
Local chain: 2642442/2642442 (0 left- best known block hash: 00000000010bddcb3516bb780c1a7657f551bea4fb331c32dcff5efaffbfbef5
Received filter: 0000000000006f85d79e128b81441b184b8af322644cefc6c8c5e1a8473bbcdb height: 2642442
```
Server log
```
2024-04-24 01:04:56.198 [25] WARNING    IndexBuilderService.Synchronize (199)   Reorg observed on the network.
2024-04-24 01:04:56.198 [25] INFO …
```
> Fix reorg error log

- WalletWasabi.Fluent/Views/Wallets/Home/WalletTiles.axaml
The drop shadow for the Light theme made it narrow on each theme. The privacy control tile is crowed, so this PR mitigates the issue.
(The long-term goal is to have better-designed tiles)
Before:
After:
> [UI] Increase height of tiles

- WalletWasabi.Tests/UnitTests/LinqExtensionsTests.cs
- WalletWasabi/Extensions/LinqExtensions.cs
AFAIK median is not defined for an empty collection. We return `0` right now.
> Median of an empty set

- .editorconfig
Lately there are a lot of these suggestions on VS, and most of them are just annoying.
Similar to #12707, this PR disables some code style rules because applying those style suggestions would require a big refactoring.
> [Trivial] Disable IDE0028 & IDE0290 & IDE0300 & IDE0305 code style rules in `.editorconfig`

- WalletWasabi.Daemon/Config.cs
- WalletWasabi.Daemon/Global.cs
- WalletWasabi.Daemon/WasabiAppBuilder.cs
- WalletWasabi/Logging/Logger.cs
- WalletWasabi/Tor/TorSettings.cs
Contributes to #9805
This PR adds `--LogModes` command line option to specify that one wants to log to only specific logging targets[^1]. Specifically one can omit `file` to avoid storing logging data.
See also https://github.com/zkSNACKs/WalletWasabi/issues/9805#issuecomment-2071845610.
```powershell
dotnet build && dotnet run --framework net8.0 -- --LogModes="" # Do not log at all
dotnet build && dotnet run --framework net8.0 -- --LogModes="file" # Log only to file
dotnet build && dotnet run --framework net8.0 -- --LogModes="console" # Log only to console
dotnet build && dotnet run --framework net8.0 -- --LogModes="file,console" # Log to console & file
dotnet build && dotnet run --framework net8.0 -- --LogModes="console,file" # Log to file & console (equivalent to the above line)
dotnet …
```
> Add command line option `--LogModes`

- WalletWasabi.Fluent/ViewModels/Login/PasswordFinder/SearchPasswordViewModel.cs
No idea why this works.
To repro simply try to open a wallet without password by writing "f" in passphrase field then click "forgot passphrase" then write f, f, press no, no, and wait for crash.
The only change of this PR is to change
`var cts = new CancellationTokenSource().DisposeWith(disposables);`
to
```
var cts = new CancellationTokenSource()
[...]
disposables.Add(cts);
```
> Reverts #12964 + Fix PF's CTS dispose

- WalletWasabi.Tests/UnitTests/Bases/ConfigManagerTests.cs
- WalletWasabi/WabiSabi/Backend/Rounds/Arena.Partial.cs
- WalletWasabi/WabiSabi/Backend/WabiSabiConfig.cs
This PR allows us to disable the coinjoin service. What it does it to return no rounds to the clients, making the coinjoins impossible.
This is not the best way to do it because all the machinery is still there working and consuming resources but it is the simplest thing to do. 
The clients will see "Awaiting for coinjoin" forever.
> Disable coinjoins

- WalletWasabi/Services/Terminate/TerminateService.cs
This PR is a sort of ultimate solution for CTRL+C issues. 
Right now, I suspect that that `CoinJoinManager` does not respond to CTRL+C requests correctly because I can see in my logs
```log
2024-05-04 12:52:16.102 [15] WARNING	TerminateService.Console_CancelKeyPress (103)	Process termination was requested using 'ControlC' keyboard shortcut.
2024-05-04 12:52:45.155 [41] INFO	CoinJoinClient.StartRoundAsync (299)	Round (XY): Aborted. Not enough participants.
2024-05-04 12:52:46.133 [56] INFO	CoinJoinManager.HandleCoinJoinFinalizationAsync (511)	Wallet (2022-10): CoinJoinClient finished. Coinjoin transaction was not broadcast.
2024-05-04 12:52:46.134 [56] INFO	CoinJoinManager.HandleCoinJoinFinalizationAsync (605)	Wallet (2022-10): CoinJoinClient restart automatically.
2024-05-04 12:53:43.604 …
```
> `TerminateService`: Allow forceful termination on second CTLR+C

- WalletWasabi.Daemon/Rpc/WasabiJsonRpcService.cs
- WalletWasabi.Fluent/Models/Wallets/WalletCoinjoinModel.cs
- WalletWasabi.Fluent/Models/Wallets/WalletModel.cs
- WalletWasabi.Fluent/Models/Wallets/WalletSettingsModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Settings/WalletCoinJoinSettingsViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Settings/WalletSettingsViewModel.cs
- WalletWasabi.Fluent/Views/Wallets/Settings/WalletCoinJoinSettingsView.axaml
- WalletWasabi.Tests/UnitTests/ViewModels/ReceiveAddressViewModelTests.cs
- WalletWasabi.Tests/UnitTests/ViewModels/SuggestionLabelsViewModelTests.cs
- WalletWasabi/WabiSabi/Client/CoinJoin/Manager/CoinJoinTrackerFactory.cs
- WalletWasabi/Wallets/IWallet.cs
> [v2.0.7.2] Mix to another wallet clean

- WalletWasabi.Fluent/ViewModels/CoinControl/SelectCoinsDialogViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Advanced/WalletCoinsViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Coins/CoinListViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Coins/CoinViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Coins/PocketViewModel.cs
It's now possible to decide if coins that are coinjoining can be selected or not.
Addresses comment https://github.com/zkSNACKs/WalletWasabi/pull/12893#issuecomment-2069284026
> [UI] Add option to configure selectability of CJing coins

- WalletWasabi/Stores/BlockFilterSqliteStorage.cs
- WalletWasabi/Stores/IndexStore.cs
The idea here is that we don't really use SQLite connection pooling for anything. 
The pooling feature is useful when one creates and tears down connections. We have just one connection though that lives as long as the application lives.
> SQLite: Disable connection pooling for block filter SQLite database

- WalletWasabi.Fluent/Models/Wallets/WalletRepository.cs
- WalletWasabi.Fluent/ViewModels/Dialogs/AboutAdvancedInfoViewModel.cs
- WalletWasabi.Tests/UnitTests/Helpers/ResultTests.cs
- WalletWasabi/Helpers/Result.cs
- WalletWasabi/WabiSabi/Client/CoinJoin/Client/CoinJoinClient.cs
- WalletWasabi/WabiSabi/Client/CoinJoin/Client/DependencyGraphTaskScheduler.cs
This PR is an attempt to improve situations that lead to bad designs. For example, the `StartOutputRegistrationsAsync` receives the list of outputs that it has to register, the schedule that has to use for the registration and the bob client to perform the operation. However, it also received a `DestinationProvider`! WFT!? The destination provider provides destinations, it already provided those destinations which were passed to the `StartOutputRegistrationsAsync` method. Or well you want a meal or a well you want a chef but for the sake of gosh don't bring me the food AND the chef who cooked that meal!
This happens because we create functions that return nothing to the caller and for that reason the callee has to do it all and needs to receive dependencies from the caller to do things …
> Improve output registration error handling

- WalletWasabi.Daemon/Global.cs
- WalletWasabi/CoinJoin/Client/CoinJoinProcessor.cs
This is just a PR that allows a bigger refactoring towards using .NET `HttpClient`'s `WebProxy` for Tor purposes. 
In any case, accessing "internals" of WasabiSynchronizer is not cool.
> [refactoring] `CoinJoinProcessor`: pass correctly `WasabiHttpClientFactory`

- WalletWasabi.Tests/IntegrationTests/BlockDownloadTests.cs
I wanted to test #13032, but because @csiki2 wrote the wrong file name as a title, I tried the wrong test..... just to realize that it didn't work on macOs :D
This PR uses `Config.DataDir` for the `AddressManagerMain.dat` file instead of a random file
> Use correct path for `addressManagerFilePath` in `BlockDownloadTests`

- WalletWasabi.Tests/XunitConfiguration/RegTestFixture.cs
`DataDir` already contains `EnvironmentHelpers.GetDataDir` so it was repeated twice.
Before:
After:
> Fix path in RegTestFixture

- WalletWasabi.Tests/IntegrationTests/LiveServerTests.cs
- WalletWasabi/WebClients/Wasabi/WasabiClient.cs
`WasabiClient` had a `GetMempoolHashesAsync` method overloaded for testing purpose only. This is not okay and it is removed in this PR
> Remove test-only API Client `mempool-hashes`

- WalletWasabi.Backend/Controllers/WabiSabiController.cs
- WalletWasabi.Backend/Controllers/WalletController.cs
- WalletWasabi.Backend/Program.cs
- WalletWasabi.Backend/Properties/launchSettings.json
- WalletWasabi/Helpers/Constants.cs
- WalletWasabi/WabiSabi/Client/WabiSabiHttpApiClient.cs
- WalletWasabi/WebClients/Wasabi/WasabiClient.cs
This PR allows us to run multiple instances by doing something like: 
```
$ dotnet run --urls="http://localhost:38888/" --datadir="/home/userx/backend-datadir-1"
$ dotnet run --urls="http://localhost:39999/" --datadir="/home/userx/backend-datadir-2"
``````
`Wallet` API and `WabiSabi` API are now versioned, what allows us also to configure an http proxy easier.
> Allow to run multiple backend instances

- WalletWasabi.Daemon/Config.cs
- WalletWasabi.Daemon/PersistentConfig.cs
- WalletWasabi.Fluent/Models/UI/ApplicationSettings.cs
Ports #13074 to the FOSS version + adds a bugfix 59f22c9513d8c7204bced09a46bbcda38897aafd for the Lucas issue (`--UseTor=False` used to throw, similarly `--UseTor=disabled` instead of `--UseTor=Disable` used to throw an exception)
Test using:
```
dotnet build && dotnet run --framework net8.0 -- --UseTor=false
dotnet build && dotnet run --framework net8.0 -- --UseTor=disabled
dotnet build && dotnet run --framework net8.0 -- --UseTor=enabled
```
> [Tor] Fix changing Tor modes in the UI settings (FOSS port)

- WalletWasabi/Services/UpdateManager.cs
This PR is useless because it doesn't change anything except avoiding a redirection.
Yet it's better to point to the correct place I guess.
There is a much bigger PR to make to replace links everywhere, but this PR is part of an effort to finalize UpdateManager on the `Downsize+FOSS` branch so we can port it to `master` for the release.
I'm super power merging
> Point to the correct repository in UpdateManager

- WalletWasabi/Services/UpdateManager.cs
Tested and found no way where it can cause any problem, in fact it seems to me that it correctly 
Using super power merging again because I really want to make the PR to master today, but @Szpoti or @molnard please scream if it is incorrect.
> Use `<` instead of `<=` for versions check in `UpdateManager`

- WalletWasabi.Backend/Config.cs
- WalletWasabi.Daemon/PersistentConfig.cs
- WalletWasabi/Helpers/Constants.cs
- WalletWasabi/Wallets/SpecificNodeBlockProvider.cs
Fixed a problem that I introduced recently where it `LogWarning` at every launch because there is no `SpecificNode` to connect to.
This PR doesn't log if the endpoint specified is default, so that it avoids logging for nothing in the standard case, but still logs if user specified a custom endpoint.
The downside is that there will not be any log if a node is expected by user on default endpoint but is not available. However, there is no perfect solution here and I believe this PR is the best tradeoff
@kiminuo If you can think of a better place for `IsDefaultP2pEndpoint` please move it!
> Don't log that we couldn't connect to a node if endpoint is default

- WalletWasabi.Fluent/Models/Wallets/WalletLoadWorkflow.cs
- WalletWasabi.Fluent/Views/Wallets/LoadingView.axaml
- WalletWasabi.Tests/Helpers/ServiceFactory.cs
- WalletWasabi.Tests/UnitTests/KeyManagementTests.cs
- WalletWasabi/Blockchain/Keys/KeyManager.cs
Fixes #13111 
It also includes a slight change of the text during sync to emphasize that it will be longer on first launch.
This loading screen really doesn't make the job but well... out of scope.
Note that this PR is not aimed at `master` but at `Downsize+FOSS`, it is seeking for cACK or cNACK, I would accept either but take in mind that this feature creates maintenance burden
Ps: I noticed that the filters are longer to download than in the past
> [FOSS Port] Remove `SkipSynchronization`

- WalletWasabi/Services/UpdateManager.cs
> Fix UpdateManager on Linux

- WalletWasabi.Daemon/Config.cs
- WalletWasabi.Daemon/Global.cs
- WalletWasabi.Daemon/PersistentConfig.cs
- WalletWasabi.Fluent/Models/UI/ApplicationSettings.cs
- WalletWasabi.Fluent/ViewModels/Settings/BitcoinTabSettingsViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/CoinJoinStateViewModel.cs
- WalletWasabi.Fluent/Views/Settings/BitcoinTabSettingsView.axaml
- WalletWasabi.Tests/Helpers/WabiSabiFactory.cs
- WalletWasabi.Tests/UnitTests/ViewModels/UiContext/NullApplicationSettings.cs
- WalletWasabi/Helpers/Constants.cs
- WalletWasabi/WabiSabi/Client/CoinJoin/Client/CoinJoinClient.cs
- WalletWasabi/WabiSabi/Client/CoinJoin/Manager/CoinJoinManager.cs
- WalletWasabi/WabiSabi/Client/CoinJoin/Manager/CoinJoinTrackerFactory.cs
- WalletWasabi/WabiSabi/Client/CoinJoin/Manager/StatusChangedEvents/StatusChangedEventArgs.cs
Fixes #13106
I used 0 as a default, not to enforce free coordinators but to protect clients. The reason is that we don't have any mechanism to enforce free remixing or to ensure that coordination fee doesn't change over time. Therefore, the coordinator as it is can be characterized as trust-minimized, because as I explained we didn't achieve real trustlessness yet. However, connecting to a coordinator that can charge a coordination fee requires some amount of trust, which is why 0 as a default is what makes the most sense.
Nevertheless, changing this setting is super easy when changing `CoordinatorURI`, as both are at the same place. As a result, a for-profit coordinator could instruct users that have a minimum amount of trust towards it to change both settings at the same time.
Finally, …
> Introduce `MaxAllowedCoordinationFeeRate` setting

- WalletWasabi.Fluent/Styles/SettingsLayout.axaml
A new style selector for TextBox in StackPanel.settingsLayout has been added. This sets the width of the TextBox to a value of 360 to ensure TextBox doesn't grow indefintely.
Fixes #13163
> [UI] Set fixed width for TextBoxes in SettingsLayout

- WalletWasabi.Fluent/Models/UI/ApplicationSettings.cs
The configuration source for the Tor setting has been changed. Instead of deriving the Tor setting from '_startupConfig.UseTor', it is now set via '_config.UseTor'. This change ensures the consistency in the UI as well.
Fixes #13093
> [UI] Use the correct setting for Tor when --UseTor parameter is used

- WalletWasabi.Fluent/Extensions/ObservableExtensions.cs
- WalletWasabi.Fluent/Helpers/LambdaComparer.cs
- WalletWasabi.Fluent/Models/Wallets/WalletCoinsModel.cs
- WalletWasabi.Fluent/Models/Wallets/WalletRepository.cs
- WalletWasabi.Fluent/Models/Wallets/WalletTransactionsModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Coins/CoinListItem.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Coins/CoinListViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Coins/CoinViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Coins/PocketViewModel.cs
- I've investigated this issue https://github.com/WalletWasabi/WalletWasabi/issues/12985 and discovered.
- I've researched about the usage of EditDiff.
- Made some isolated tests to verify its behavior. https://reactivex.slack.com/archives/C4LF8S19N/p1718182734512799
And discovered that we are using the `EditDiff` method without a comparer where we SHOULD use it. 
EditDiff is given a key selector, but it won't magically compare instances for equality, so there are instances that we consider equal, that `EditDiff` won't.
This is incorrect.
It doesn't cause major issues, but it can be the source of many of our issues with lists, that are refreshed when they don't need to, thus decreasing the performance of the application.
This change improves this situation a lot. Now, the items that are …
> [UI] Review EditDiff usages

- WalletWasabi.Fluent/ViewModels/Wallets/Settings/ExcludedCoinsViewModel.cs
all other references in the GUI call it _Exclude Coins_, instead of the _Exclude**d** Coins_ dialog title.
-> update the title
(exclude, makes more sense anyway)
> [vdg] rename excluded coins dialog

- WalletWasabi.Daemon/Config.cs
- WalletWasabi.Daemon/Global.cs
- WalletWasabi.Daemon/PersistentConfig.cs
- WalletWasabi.Fluent/Models/UI/ApplicationSettings.cs
- WalletWasabi.Fluent/ViewModels/Settings/CoordinatorTabSettingsViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/CoinJoinStateViewModel.cs
- WalletWasabi.Fluent/Views/Settings/CoordinatorTabSettingsView.axaml
- WalletWasabi.Tests/Helpers/WabiSabiFactory.cs
- WalletWasabi.Tests/UnitTests/Bases/ConfigManagerNgTests.cs
- WalletWasabi.Tests/UnitTests/ViewModels/UiContext/NullApplicationSettings.cs
- WalletWasabi/Helpers/Constants.cs
- WalletWasabi/WabiSabi/Client/CoinJoin/Client/CoinJoinClient.cs
- WalletWasabi/WabiSabi/Client/CoinJoin/Manager/CoinJoinManager.cs
- WalletWasabi/WabiSabi/Client/CoinJoin/Manager/StatusChangedEvents/StatusChangedEventArgs.cs
I believe that this should be the last coordinator config.
We need to also have `Name` and `ReadMoreURI` but..... Those are not configs, there are coordinators properties, that we should probably store somewhere else.
These coordinator configs are also slightly annoying because most are network-agnostic, except the endpoint. I think it is ok, but it would probably be better to completely separate
> Introduce AbsoluteMininputCount coordinator config

- WalletWasabi/WabiSabi/Client/CoinJoin/Client/CoinJoinCoinSelector.cs
Same Tx Allowance degrades performances and increase cost of coinjoin significantly for small wallets remixing a lot.
In fact, this comment:
> // The smaller our balance is the more privacy we gain and the more the user cares about the costs, so more interconnectedness allowance makes sense.
is incorrect because a small value for same tx allowance will result in less consolidation, which means higher costs, especially for small wallets.
It's a negative spiral because the coins get more decomposed, which would over time, further decrease the same tx allowance (as the registered amount will be reduced). Consolidation will also become harder and harder, same for payments into coinjoin etc etc etc
Even worse, we sort private coins by amount. Therefore, even if we try to avoid selecting coins …
> Increase same tx allowance to 2 on average

- WalletWasabi.Tests/UnitTests/Bases/ConfigManagerTests.cs
- WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PhaseStepping/StepOutputRegistrationTests.cs
- WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterInputSuccessTests.cs
- WalletWasabi.Tests/UnitTests/WabiSabi/Client/ArenaClientTests.cs
- WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiHttpApiIntegrationTests.cs
- WalletWasabi.Tests/UnitTests/WabiSabi/Models/MultipartyTransactionTests.cs
- WalletWasabi.Tests/UnitTests/WabiSabi/Models/SerializationTests.cs
- WalletWasabi/Crypto/StrobeProtocol/StrobeHasherExtensions.cs
- WalletWasabi/JsonConverters/DefaultValueCoordinationFeeRateAttribute.cs
- WalletWasabi/WabiSabi/Backend/Models/Alice.cs
- WalletWasabi/WabiSabi/Backend/Rounds/Arena.Partial.cs
- WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
- WalletWasabi/WabiSabi/Backend/WabiSabiConfig.cs
- WalletWasabi/WabiSabi/Client/CoinJoin/Client/AliceClient.cs
- WalletWasabi/WabiSabi/Client/CoinJoin/Client/ArenaClient.cs
- WalletWasabi/WabiSabi/Client/CoinJoin/Client/CoinJoinClient.cs
- WalletWasabi/WabiSabi/Models/CoordinationFeeRate.cs
- WalletWasabi/WabiSabi/Models/InputRegistrationResponse.cs
This is the same that https://github.com/WalletWasabi/WalletWasabi/pull/13005 but it doesn't break backward compatibility. The thing is that the coordinator continue sending the `plebsDontPayThreshold` to the client, and committing to it as part of the round id, but the value is hardcoded to 0 (zero).
> Make Wasabi FREE by default (compatible)

- WalletWasabi/WabiSabi/Client/CoinJoin/Client/CoinJoinClient.cs
Thanks @Kruwed 
Both codes that `throw` if client refuse to participate (for new and blame rounds) should be combined, this duplication is the reason why I made the mistake.
Because this PR is important, I suggest to merge it ASAP then if you want we can think about combining both codes.
> Also check blame round max fees

- WalletWasabi.Fluent/Models/Wallets/CoinListModel.cs
- WalletWasabi.Fluent/Models/Wallets/WalletModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/WalletPageViewModel.cs
- WalletWasabi.Tests/UnitTests/ViewModels/ReceiveAddressViewModelTests.cs
- WalletWasabi.Tests/UnitTests/ViewModels/SuggestionLabelsViewModelTests.cs
Closes https://github.com/WalletWasabi/WalletWasabi/issues/12927
The current design doesn't allow only load values when a wallet is selected, and I am not even sure how much refactoring is needed to achieve it.
(The first sign of it is the usage of Lazy)
This is the minimum change to fix the issue.
> make sure coins are updated when selecting a wallet

- WalletWasabi.Daemon/PersistentConfig.cs
- WalletWasabi.Daemon/WasabiApplication.cs
- WalletWasabi.Fluent/Views/Settings/CoordinatorTabSettingsView.axaml
- WalletWasabi.Tests/UnitTests/Bases/ConfigManagerNgTests.cs
- WalletWasabi/WabiSabi/Client/CoinJoin/Client/CoinJoinClient.cs
This PR changes the `MaxCoordinationFeeRate`  semantic from percentage to rate value to make it content consistent with its name and the rest of the code base.
It adds a version number to the config file in order to know which migrations needs to be done. Ideally we should move to something like what I did for Wasabito: https://github.com/lontivero/Wasabito/commit/1e18aa0e2332a14c69761edb43bb9d5eefe0f9a4 (see config files there)
> Migrate MaxCoordinationFeeRate to rate

- WalletWasabi.Fluent/Models/Wallets/CoinListModel.cs
Fixes https://github.com/WalletWasabi/WalletWasabi/issues/13127
The previous code kept the old coin in the list even if it left the wallet which resulted in the issue mentioned above.
_(This is another example that we do not understand Reactive and things don't work as we expect, we should decrease the usage of it)_
> Fix Privacy progress tile is incorrect

- WalletWasabi/Discoverability/CoordinatorConnectionString.cs
- negative coordination fee rate is not accepted
- ToString method is fixed so it will pop a new dialog in the case of a new magic string while and old one is being opened.
> Quick patch for Coordinator string

- WalletWasabi.Daemon/Config.cs
- WalletWasabi.Daemon/Global.cs
- WalletWasabi.Tests/Helpers/WabiSabiFactory.cs
- WalletWasabi.Tests/UnitTests/Bases/ConfigManagerTests.cs
- WalletWasabi/Helpers/Constants.cs
- WalletWasabi/WabiSabi/Client/CoinJoin/Client/CoinJoinClient.cs
- WalletWasabi/WabiSabi/Client/CoinJoin/Manager/CoinJoinManager.cs
This PR reduce the absolute max coordination fee to 0.005 and the absolute min input count to 5 while prevents solo coinjoining.
> More strict coinjoin parameters

- WalletWasabi/WalletWasabi.csproj
Ignore vulnerability warning until the dotnet sdk is available and installed by the team.
> Ignore compilation warning 

- WalletWasabi.Fluent/Views/Settings/CoordinatorTabSettingsView.axaml
to match behavior of all other settings items
i.e. when you click it, it gets automatically selected
> Settings: add auto select behavior to MinInputCount textbox

- WalletWasabi.Tests/UnitTests/WabiSabi/Client/AmountDecomposerTests.cs
- WalletWasabi/WabiSabi/Client/CoinJoin/Client/Decomposer/AmountDecomposer.cs
- WalletWasabi/WabiSabi/Client/CoinJoin/Client/Decomposer/Decomposer.cs
The original decomposer encoded each decomposition as a `ulong` , a (precompted) `Sum`  and a `Count` property.  The idea was to prevent allocations while allowing filtering by `Sum` and `Count`. However that was never user, instead all the decompositions were decoded, always. 
Encoding increased the complexity of the algorithm. This PR removes the encoding/decoding feature and replaces it by a linked list `Decomposition` which reuses all common elements of decompositions calculated from the same root. The `InternalCombinations` function which was hard to understand now it is smallers and cleaner.
> Simplify Decomposer

- WalletWasabi/BitcoinCore/P2pNode.cs
In the context of our downsize efforts, the backend server should be able to work with pruned nodes. The `IndexBuilderService`  doesn't really needs a full blockchain but it can work with a manually prune one from the segwit activation height to generate the filters. However, once the filters have been generated, the blockchain can be pruned even further or automatically pruned.
Other features that prevent pruning  are those that use the transaction index, basically the `GetRawTransaction`  which we are removing in next prs.
> Allow connection to puned local node

- WalletWasabi.Tests/UnitTests/AllFeeEstimateTests.cs
- WalletWasabi/Extensions/RPCClientExtensions.cs
This PR, as it titles implies, uses the cumulative Count instead of the Count to skip fee groups
This piece of code as several conceptual flaws that lead to poor results.
I want to take them one at a time, and this is the biggest and easiest to solve one:
`FeeRateGroup.Count` is not cumulative ([source](https://github.com/bitcoinknots/bitcoin/blob/01ac32f90b6de7510c35a7fa2f35ca1ff6c0a5c2/src/rpc/mempool.cpp#L946)), so currently the concept is `Skip groups until we find one that has more txs in it than 0.001 * total number of txs in the mempool`
I believe it's a clear mistake, first because the logic sounds fishy but also because it's not in accordance with the comment right above `(less than 0.1%).`, which implies that only 0.1% of the transactions can be skipped, which is not true (much …
> Improve Fee estimation based on mempool histogram

- WalletWasabi/WabiSabi/Models/Serialization/GenericInterfaceJsonConverter.cs
Instead of using static flags to prevent reentering into an infinite recursion, it is cleaner to remove the current converter from the list of converters.
> Simplify generic serializer

- WalletWasabi.Fluent/Extensions/ObservableExtensions.cs
- WalletWasabi.Fluent/Models/Wallets/CoinListModel.cs
- WalletWasabi.Fluent/Models/Wallets/UserSelectionCoinListModel.cs
- WalletWasabi.Fluent/Models/Wallets/WalletCoinsModel.cs
Superseedes #13269 
It doesn't fix the underlying issue and I'm sure there are 23423 better ways to do it, but still it works perfectly.
The problem with the crash is that `GetPockets` is called before `CreateCoinsModel`.
This PR creates an overload of `Fetch` to make 2 cache updates atomic and then swaps the calls of `GetPockets` and `CreateCoinsModel`
Then I also included #13269 because why not?
@Kruwed @MarnixCroes @yahiheb , could you test please?
> Fix crash when CoinList is Rebuilt

- WalletWasabi.Tests/Helpers/ArenaBuilder.cs
- WalletWasabi.Tests/Helpers/WabiSabiFactory.cs
- WalletWasabi.Tests/UnitTests/WabiSabi/Backend/PostRequests/RegisterOutputTests.cs
- WalletWasabi/Helpers/VirtualSizeHelpers.cs
- WalletWasabi/WabiSabi/Models/MultipartyTransaction/MultipartyTransactionParameters.cs
`SharedOverhead` (a weight measure) was used in vsize calculations (apples + oranges).
> Fix shared transaction overhead calculation

- WalletWasabi.Backend/Controllers/BlockchainController.cs
- WalletWasabi.Tests/UnitTests/BitcoinCore/MempoolTests.cs
- WalletWasabi/BitcoinCore/Mempool/Mempool.cs
- WalletWasabi/BitcoinCore/Mempool/MempoolMirror.cs
- WalletWasabi/CoinJoin/Client/CoinJoinProcessor.cs
This PR removes all usages of `getrawtransaction` in the backend in a really straight-forward way, and creates only 2 small issues:
- In case of double spends, the state of the in-memory mempool will be incorrect for maximum 21s as the double-spent transaction won't be removed until node's mempool is re-cloned.
- This PR disables `unconfirmed-transactions-chain`, but old clients (i.e. clients prior merge of #13193) will still try to access it. This will cause the old clients to have no details about the confirmation ETA for transactions such as coinjoins (like before @adamPetho's work), and these clients will re-try the request 3 times in a row, leading of 3 log warning asking to update. This behavior can be changed if we want by either:
- Returning a `Ok(dummy value)` instead of …
> Remove usages of getrawtransaction

- WalletWasabi.Tests/UnitTests/WabiSabi/Integration/WabiSabiHttpApiIntegrationTests.cs
The test was failing from time to time because randomly preferred tr over wpkh but only wpkh scripts were marked as used by the coordinator.
> Test with both P2TR and P2WPKH

- WalletWasabi.Fluent/Views/Wallets/MusicControlsView.axaml
bit of a nit, but it's easier on the eye
now the order of the items is descending, the same as the menuitems at the right top at a wallet
> change order of musicbox menuitems

- WalletWasabi.Daemon/Global.cs
- WalletWasabi.Tests/RegressionTests/BackendTests.cs
- WalletWasabi.Tests/RegressionTests/BuildTransactionReorgsTest.cs
- WalletWasabi.Tests/RegressionTests/CancelTests.cs
- WalletWasabi.Tests/RegressionTests/MaxFeeTests.cs
- WalletWasabi.Tests/RegressionTests/ReceiveSpeedupTests.cs
- WalletWasabi.Tests/RegressionTests/SelfSpendSpeedupTests.cs
- WalletWasabi.Tests/RegressionTests/SendSpeedupTests.cs
- WalletWasabi.Tests/RegressionTests/SendTests.cs
- WalletWasabi.Tests/RegressionTests/SpendUnconfirmedTxTests.cs
- WalletWasabi/BitcoinP2p/P2pBehavior.cs
- WalletWasabi/BitcoinP2p/TrustedP2pBehavior.cs
- WalletWasabi/BitcoinP2p/UntrustedP2pBehavior.cs
- WalletWasabi/Blockchain/Mempool/MempoolService.cs
- WalletWasabi/Blockchain/TransactionBroadcasting/TransactionBroadcaster.cs
- WalletWasabi/Blockchain/TransactionProcessing/TransactionProcessor.cs
- WalletWasabi/Blockchain/Transactions/TransactionBroadcastEntry.cs
- WalletWasabi/Extensions/LinqExtensions.cs
- WalletWasabi/Helpers/Result.cs
Instead of trying to broadcast a transaction with nodes one by one, this version tries with one or more in parallel. It doesn't iterate in a loop but uses a `TaskCompletion` task to get a notification when the tx is propagated.
The number of selected nodes is one thrid of the connected nodes plus one, what makes sure to have always connected nodes (it doesn't disconnect them all). Also, this allows users to broadcast transaction immediately after the wallet starts because at that moment there use to be a very few connected nodes. Before, this was almost always impossible and the backend had to be used in most of the cases.
> Make transaction broadcasting faster.

- .github/workflows/release.yml
- Contrib/ReleaseHighlight.md
- Contrib/ReleaseTemplate.md
- Contrib/release.sh
- WalletWasabi.WindowsInstaller/Product.wxs
This PR is for automating the release process. The idea is that once we push a version tag (ex: v2.15.3) the GitHub CI action creates the release automatically with all the packages, release notes, etc without requiring any human intervention.
The bash script that performs almost all the actions required to create the Wasabi Wallet packages. Given it is a bash script, it can run in linux, windows and macos and it is much more convenient than the current `WalletWasabi.Packager` project in the sense that we don't need to build a project to build the projects and, because it is much simpler, shorter and easier to understand and maintain.
This script does:
* Compile WasabiWallet Desktop for all supported platforms (`win-x64`, `linux-x64`, `osx-x64` and `osx-arm64`). 
* Create the `.zip` and …
> Automated build

- WalletWasabi.Tests/UnitTests/WabiSabi/Client/PaymentAwareOutputProviderTests.cs
- WalletWasabi/WabiSabi/Client/CoinJoin/Client/CoinJoinClient.cs
- WalletWasabi/WabiSabi/Client/CredentialDependencies/DependencyGraph.cs
Fixes https://github.com/zkSNACKs/WalletWasabi/issues/12584
`DependencyGraph` class was subtracting the inputs' size from the available vsize but that's incorrect because the size of the inputs is already discounted and vsize is then only for outputs. That's why in some cases it believed there was not enough space available for the outputs and failed.
> Fix `DependencyGraph` vsize calculation

- Contrib/release.sh
The Microsoft documentation doesn't apply to Linux and instead of failing with a decent error, it fails with `No certificates were found that met all the given criteria` .
> Do not trust Microsoft help page

- WalletWasabi.Backend/Global.cs
- WalletWasabi.Tests/UnitTests/BitcoinCore/IndexBuilderServiceTests.cs
- WalletWasabi/Blockchain/BlockFilters/IndexBuilderService.cs
- WalletWasabi/Stores/BlockFilterSqliteStorage.cs
Master on main:
This PR on main:
It is also far more efficient CPU for search operations.
This PR is simply missing the migration
A good follow up that I won't do as part of this PR is to unify both filter files for backend and client, but it adds a bunch of complexity
> Use sqlite for backend filters

- Contrib/migrateBackendFilters.fsx
The script is more complex than required but it is fast and avoids using too much memory.
It has been used on both Main and TestNet.
> Add script to migrate backend filters

- WalletWasabi.Tests/UnitTests/WabiSabi/Backend/Rounds/MultipartyTransactionStateTests.cs
- WalletWasabi/WabiSabi/ProtocolConstants.cs
The goal is to reduce CPU requirement in cryptographic operations, specially during credential reissuance phase.
> Reduce max input amount to 1343 btc

- WalletWasabi.Tests/UnitTests/WabiSabi/Backend/Rounds/MultipartyTransactionStateTests.cs
- WalletWasabi/WabiSabi/ProtocolConstants.cs
Reverts WalletWasabi/WalletWasabi#13403
It is necessary to implement it in a more elegant way because there are two values being used for the same thing, this one and MaxRegistrableAmount.
> Revert "Reduce max input amount to 1343 btc"

- Contrib/Migration/README.md
- Contrib/Migration/migrateBackendFilters.fsx
- flake.nix
The idea is to allow operator who already deploy using Nix and that don't have dotnet sdk installed in their servers to migrate filters by just doing:
```bash
$ nix run github:WalletWasabi/WalletWasabi#migrateFilters
Database already exists. Skipping creation.
.....................................
Completed. Total processed: 371888, Total inserted: 371888
Max Block Height in DB: 853711
```
> Make it easier to migrate filters for non-devs operators

- WalletWasabi/Discoverability/AnnouncerConfig.cs
This makes sense currently because the separation coordinator/backend is still not complete
> [Trivial] Change coordinator's default to false

- .github/workflows/release.yml
This is because v4 has a bug that makes the jobs to fail while uploading artifact for mac: https://github.com/actions/upload-artifact/issues/527
Closes https://github.com/WalletWasabi/WalletWasabi/issues/13432
> Downgrade upload-artifact action from v4 to v3

- Contrib/release.sh
Close https://github.com/WalletWasabi/WalletWasabi/issues/13459
> [Package] Debian: Use `xz` instead of `zst` for compression

- WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
- WalletWasabi/WabiSabi/Models/MultipartyTransaction/ConstructionState.cs
Fixes #13448
Note that in some cases where we coordinator would be collecting the output, now it won't collect it anymore (if fees are expansive)
An alternative concept would be to check the cost of creating an output at current mining fee rate, but the cost of spending it at 1s/vb, as the coordinator can wait.
> [Coordinator] Collect coordinator output if and only if economical

- WalletWasabi/Stores/IndexStore.cs
Some users are reporting this issue, not worth it to investigate, this change in code would work around it.
> Work around IOException in SmartResyncIfCorrupted

- .github/workflows/onReleasePublished.yml
This PR triggers https://github.com/WalletWasabi/WasabiDoc/pull/1836 after a release is published.
The reason it is not included in the release workflow is because we absolutely want this one after it is PUBLISHED, not still in draft.
It has a slight limitation: We do not use this GitHub feature, but on GitHub we can publish pre-releases (RC). This action ignores them, but then is not triggered if a pre-release is edited so it becomes the latest release. If we decide to use pre-releases in the future, we would need to delete them then create a new latest release (instead of editing)
Because it performs cross repo operations, it unfortunately needs a personal access token that is stored as a secret that I named `WASABI_DOC_PAT`. It must be from someone that has write access in the target …
> Update version in doc after a release

- WalletWasabi.Fluent/UiConfig.cs
This default is not good for several reasons:
- It requires some special handling in custom `Deserialize` function
- It is disabled on Linux but enabled on others because who knows
- It is definitely not common for a software handling MONEY to launch itself at startup like this
- On MacOs, this require to provide scary permissions on installation about system events
- Wasabi is pretty heavy and it has a high impact on startup performances
- If the wallet could load itself on launch then it would be useful to avoid sync, but it's not even the case
For all those reaosns, I believe that it is better to switch the default to false.
> [Trivial] Switch default run on system startup to false

- Contrib/release.sh
The issue is that in the specific bash version bundled in MacOs 14.6.1, the string substitution raises an error:
`./Contrib/release.sh: line 30: -2: substring expression < 0`
Interestingly, on MacOs v15.1 it works without particular issue.
To avoid further problems we might want to use a specific version instead of latest in the yml
> [BugFix] Fix version number in MacOs plist

- WalletWasabi.Daemon/Config.cs
- WalletWasabi.Daemon/Global.cs
- WalletWasabi/Services/WasabiSynchronizer.cs
- WalletWasabi/WebClients/Wasabi/WasabiHttpClientFactory.cs
There are 3 http handlers that shouldn't be disposed because they have to live forever.
> [BugFix] Do not dispose long-live connection

- WalletWasabi.Fluent/Helpers/TransactionHelpers.cs
- WalletWasabi.Fluent/Screenshot/Capture.cs
- WalletWasabi.Fluent/ViewModels/AddWallet/AddWalletPageViewModel.cs
- WalletWasabi.Fluent/ViewModels/TransactionBroadcasting/LoadTransactionViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/HardwareWalletViewModel.cs
fixes #13475
All these usages come from either FileDialogHelper.OpenFileAsync or FileDialogHelper.SaveFileAsync.
tested importing a wallet with spaces on windows only.
> replace usages of Uri.AbsolutePath with LocalPath for file system paths

- WalletWasabi.Fluent/Controls/TreeDataGrid.axaml
- WalletWasabi.Fluent/Converters/ThicknessConverters.cs
- WalletWasabi.Fluent/Models/Wallets/TransactionModel.cs
- WalletWasabi.Fluent/Models/Wallets/TransactionTreeBuilder.cs
- WalletWasabi.Fluent/ViewModels/CoinControl/CoinControlLabelComparer.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Coinjoins/CoinjoinCoinListDataGridSource.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Coinjoins/CoinjoinCoinListItem.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Coinjoins/CoinjoinCoinListViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Coinjoins/CoinjoinCoinViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Coins/CoinListDataGridSource.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Coins/CoinListItem.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Coins/CoinListViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Coins/CoinViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Coins/PocketViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Home/History/Details/CoinJoinDetailsViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Home/History/Details/CoinJoinsDetailsViewModel.cs
- WalletWasabi.Fluent/Views/CoinControl/Core/Cells/IndicatorsCellView.axaml
- WalletWasabi.Fluent/Views/CoinControl/Core/Cells/LabelsCellView.axaml
- WalletWasabi.Fluent/Views/CoinControl/Core/Cells/SelectionCellView.axaml
- WalletWasabi.Fluent/Views/Wallets/Coinjoins/CoinjoinCoinListView.axaml
- WalletWasabi.Fluent/Views/Wallets/Coinjoins/CoinjoinCoinListView.axaml.cs
- WalletWasabi.Fluent/Views/Wallets/Coinjoins/Columns/AnonymityScoreColumnView.axaml
- WalletWasabi.Fluent/Views/Wallets/Coinjoins/Columns/AnonymityScoreColumnView.axaml.cs
- WalletWasabi.Fluent/Views/Wallets/Coins/CoinListView.axaml
- WalletWasabi.Fluent/Views/Wallets/Home/History/Details/CoinJoinDetailsView.axaml
- WalletWasabi.Fluent/Views/Wallets/Home/History/Details/CoinJoinsDetailsView.axaml
- WalletWasabi/Blockchain/Analysis/BlockchainAnalyzer.cs
- WalletWasabi/Blockchain/Keys/HdPubKey.cs
- WalletWasabi/Blockchain/Transactions/TransactionSummary.cs
Built on top of #13468
After what felt like an infinite amount of pain, I am glad to present this feature that has been requested since forever.
For CoinJoinsDetails, it only shows the inputs that don't come from a coinjoin of this group. For the outputs it's the same, it only shows outputs that are not remixed in this group. Same goes for the total: it doesn't account for the foreign coins that were remixed in one of the transaction of this group. This is the best way to do it because that way it really gives insightful info, but maybe I can add a tooltip to explain it.
It is final. As always my Avalonia code is pitiful, sorry for that, but I believe that the feature is really slick.
I additionally thoght about showing the total amount but it provided really little value as this info is …
> [Feature] Add coinjoin inputs/outputs summary

- WalletWasabi.Tests/Helpers/WabiSabiFactory.cs
- WalletWasabi.Tests/UnitTests/WabiSabi/Client/CredentialDependencyTests.cs
- WalletWasabi.Tests/UnitTests/WabiSabi/Client/PaymentAwareOutputProviderTests.cs
- WalletWasabi.Tests/UnitTests/WabiSabi/ProtocolConstants.cs
- WalletWasabi/WabiSabi/Backend/Rounds/Arena.cs
- WalletWasabi/WabiSabi/Backend/Rounds/MaxSuggestedAmountProvider.cs
- WalletWasabi/WabiSabi/Client/CoinJoin/Client/CoinJoinClient.cs
- WalletWasabi/WabiSabi/Client/CredentialDependencies/CredentialEdgeSet.cs
- WalletWasabi/WabiSabi/Client/CredentialDependencies/DependencyGraph.cs
- WalletWasabi/WabiSabi/ProtocolConstants.cs
The amount credential size was always configurable, however, later in time hardcoded values were added to the `MuxSuggestedMountProvider`   and `DependencyGraph` classes. This PR makes sure hardcoded values are not used anymore.
> Amount credential size configurable

- WalletWasabi.Tests/UnitTests/WabiSabi/Backend/Rounds/MultipartyTransactionStateTests.cs
- WalletWasabi.Tests/UnitTests/WabiSabi/Models/RoundStateUpdaterTests.cs
- WalletWasabi/WabiSabi/Client/RoundStateAwaiters/RoundStateUpdater.cs
- WalletWasabi/WabiSabi/Models/MultipartyTransaction/MultipartyTransactionState.cs
- WalletWasabi/WabiSabi/Models/RoundState.cs
Client was trusting on the coordinator round id instead of computing it by itself. This PR is for fixing that and also to verify that all inputs registered in a round were created for that round only, this is done by verifying their ownership proofs.
> [BugFix] Make client to compute `RoundId`

- WalletWasabi/BitcoinP2p/P2pNetwork.cs
All peer-to-peer messages `inv` and `getdata` where sent twice because the `Untrustedp2pBehavior` was registered twice.
> [BugFix] Duplicated p2p network messages

- WalletWasabi/BitcoinP2p/P2pBehavior.cs
- WalletWasabi/BitcoinP2p/UntrustedP2pBehavior.cs
- WalletWasabi/Blockchain/Mempool/MempoolService.cs
- WalletWasabi/Blockchain/TransactionBroadcasting/TransactionBroadcaster.cs
- WalletWasabi/Blockchain/Transactions/TransactionBroadcastEntry.cs
- WalletWasabi/Helpers/Result.cs
- WalletWasabi/WebClients/Wasabi/WasabiClient.cs
> In previous versions the propagation was confirmed only when the transactions were broadcast to the peer-to-peer network. However, it is important to verify the propagation also when it is sent directly to the trusted node using the RPC interface or when the transaction is sent to the backend.
Better detection of broadcast and propagation confirmation and less nodes to broadcast to.
> Improve propagation confirmation

- WalletWasabi/Helpers/Constants.cs
Merge after release highlights and last bug fix.
Then create tag `v2.3.0.0`
> [Trivial] Bump version to 2.3.0.0

- WalletWasabi.Fluent/Views/CoinControl/Core/Cells/AmountCellView.axaml
- WalletWasabi.Fluent/Views/Wallets/Coinjoins/Cells/AmountCellView.axaml
- WalletWasabi.Fluent/Views/Wallets/Transactions/Inputs/Cells/AmountCellView.axaml
- WalletWasabi.Fluent/Views/Wallets/Transactions/Outputs/Cells/AmountCellView.axaml
as follow up to https://github.com/WalletWasabi/WalletWasabi/pull/13534/
If you'd want to know the related address, the user can now see it with a tooltip after right clicking.
Otherwise the user would need to copy the address, and then paste it somewhere (so either close the dialog, or copy outside of Wasabi) to see the address.
> [Feature] Coinlist: add address as tooltip when hover over amount

- WalletWasabi.Daemon/Global.cs
- WalletWasabi.Fluent/Models/Wallets/BuyAnythingModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Buy/BuyViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Buy/OrderViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModel.cs
- WalletWasabi.Fluent/Views/Wallets/Buy/BuyView.axaml
- WalletWasabi.Fluent/Views/Wallets/Buy/OrdersListView.axaml
- WalletWasabi/BuyAnything/BuyAnythingManager.cs
- WalletWasabi/BuyAnything/ConversationExtensions.cs
- WalletWasabi/WebClients/BuyAnything/BuyAnythingClient.cs
This PR disables the `BuyAnythingButton` in a way that it doesn't let users to create new conversations anymore + it hides the button except if they have a conversation ongoing or done (so users can still access the result or terminate ongoing conversations)
In the next version, we can completely remove all code related.
This PR also removes the Test Shop because it doesn't exist anymore and the endpoints return errors.
It would be great if someone with a completed order could test
> [Misc] Disable BuyAnythingButton

- WalletWasabi.Tests/UnitTests/WabiSabi/Client/AmountDecomposerTests.cs
- WalletWasabi/WabiSabi/Client/Batching/PaymentAwareOutputProvider.cs
- WalletWasabi/WabiSabi/Client/CoinJoin/Client/Decomposer/AmountDecomposer.cs
- WalletWasabi/WabiSabi/Client/OutputProvider.cs
When payment in CoinJoin is used, the remaining amount that is decomposed to standard denominations can be decomposed into denominations not used by the other participants. Therefore, such a user doesn't get the expected level of anonymity, and the fact that the outputs are owned by someone who paid in the CoinJoin can be leaked. This issue is caused by the paying participant not considering some of his input coins when filtering the denominations while others consider all the input values.
This PR fixes that issue by considering all inputs when filtering denominations. I also removed one exception in `AmountDecomposer.cs` as it would be triggered any time when the amount remaining for mixing is too low (this issue existed even before my changes).
> Fix amount decomposition when payment in CoinJoin is used

- WalletWasabi.Fluent/Views/Wallets/Home/History/Details/CoinJoinDetailsView.axaml
- WalletWasabi.Fluent/Views/Wallets/Home/History/Details/TransactionDetailsView.axaml
- WalletWasabi.Fluent/Views/Wallets/Send/SendFeeView.axaml
- WalletWasabi.Fluent/Views/Wallets/Send/TransactionSummary.axaml
Current behavior makes no sense and is confusing.
As it is rounding the number, but for a Fee Rate the exact amount matters.
It should just display the full 2 digit decimal.
Now it will only trim the last digit if it is a 0, which makes sense.
**master**
[master.webm](https://github.com/user-attachments/assets/014ada63-c55d-42d2-8561-783d9d43cc9c)
**PR**
[PR.webm](https://github.com/user-attachments/assets/6627409b-a7ed-40de-a48b-811c2bfc0105)
> Preview TX: remove fee rate formatting/rounding to 1 decimal

- WalletWasabi.Daemon/README.md
- WalletWasabi.Documentation/Ports.md
- WalletWasabi.Documentation/WasabiSetupRegtest.md
- WalletWasabi.Tests/UnitTests/Bases/ConfigManagerNgTests.cs
- WalletWasabi.Tests/UnitTests/BitcoinCore/RpcBasedTests.cs
- WalletWasabi.Tests/UnitTests/JsonConverters/EndPointJsonConverterTests.cs
- WalletWasabi.Tests/UnitTests/JsonConverters/NetworkJsonConverterTests.cs
- WalletWasabi.Tests/UnitTests/SmartHeaderTests.cs
- WalletWasabi.Tests/UnitTests/Userfacing/AddressStringParserTests.cs
- WalletWasabi.Tests/UnitTests/WalletDirTests.cs
- WalletWasabi/BitcoinCore/Configuration/NetworkTranslator.cs
- WalletWasabi/Blockchain/Blocks/SmartHeader.cs
- WalletWasabi/Blockchain/Keys/KeyManager.cs
- WalletWasabi/Helpers/Constants.cs
- WalletWasabi/ModuleInitializer.cs
This PR replaces `TestNet3` by `TestNet4`. Given that NBitcoin's `Network.TestNet` reference the already dead TestNet3 and that the `TestNet4` network is available only through `Bitcoin.Instance`, or well we change that everywhere (rather risky imo) or we hack it as I do here (ugly).
> [Feature] Use TestNet4 as testnet

- WalletWasabi.Backend/StartupTask.cs
Use `GenerateToAddress` RPC call instead of `Generate` because the latter requires to have a wallet loaded.
> Avoid rpc method that assume a wallet is loaded

- WalletWasabi/Announcements/ReleaseHighlights.md
- WalletWasabi/Helpers/Constants.cs
Now version bump + Highlights will be in the same PR to make it easier to test the highlights.
Maybe I could summarize more
> [Trivial] v2.4.0 Highlights + Version bump

- Contrib/release.sh
- WalletWasabi.Backend/Config.cs
- WalletWasabi.Backend/Startup.cs
- WalletWasabi.Coordinator/Controllers/WabiSabiController.cs
- WalletWasabi.Coordinator/Extensions.cs
- WalletWasabi.Coordinator/Filters/ExceptionTranslateFilter.cs
- WalletWasabi.Coordinator/Filters/LateResponseLoggerFilter.cs
- WalletWasabi.Coordinator/GlobalUsings.cs
- WalletWasabi.Coordinator/Program.cs
- WalletWasabi.Coordinator/Startup.cs
- WalletWasabi.Coordinator/StartupTask.cs
- WalletWasabi.Coordinator/WalletWasabi.Coordinator.csproj
- WalletWasabi.Tests/UnitTests/Bases/ConfigManagerTests.cs
- WalletWasabi.Tests/UnitTests/WabiSabi/Client/ArenaClientTests.cs
- WalletWasabi.Tests/UnitTests/WabiSabi/Client/BobClientTests.cs
- WalletWasabi.Tests/UnitTests/WabiSabi/Integration/Startup.cs
- WalletWasabi.Tests/WalletWasabi.Tests.csproj
- WalletWasabi.sln
- WalletWasabi/WabiSabi/Backend/Rounds/Arena.Partial.cs
- WalletWasabi/WabiSabi/Backend/WabiSabiConfig.cs
- flake.nix
Creates a new project called `WalletWasabi.Coordinator` which contains the wabisabi api alone. The `WalletWasabi.Backend` project doesn't contain anything related to multiparty transaction coordination.
Separating Wallet API and Multiparty Transaction Coordination (WabiSabi) API physically simplifies the maintenance, reduce the usage of resources and makes it easier to host these APIs independently. Wasabi infrastructure operators could host these APIs in different servers and scale them accordingly, what is not so easy in a monolithic architecture.  This is because the nature of the APIs is different, while Wallet API is stateless and trivial to scale horizontally, WabiSabi is stateful and can only scale vertically.
Additionally, this PR makes contains the changes in the release system …
> Separate coordinator from backend

- WalletWasabi.Fluent/Views/Settings/AdvancedSettingsTabView.axaml
Adds a tooltip to the backend URI box with explanation.
> The backend provides the block filters to synchronize the wallet.
the backend provides more than just the filters, but I'd go with this to keep it simple
---
> [UI] settings: add tooltip to backend URI box

- WalletWasabi.Daemon/Config.cs
- WalletWasabi.Daemon/Global.cs
- WalletWasabi.Daemon/PersistentConfig.cs
- WalletWasabi.Daemon/Rpc/WasabiJsonRpcService.cs
- WalletWasabi.Fluent/App.axaml.cs
- WalletWasabi.Fluent/Models/Transactions/PrivacySuggestionsModel.cs
- WalletWasabi.Fluent/Models/Wallets/AmountProvider.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Send/SendViewModel.cs
- WalletWasabi.Tests/UnitTests/Bases/ConfigManagerNgTests.cs
- WalletWasabi/Services/WasabiSynchronizer.cs
- WalletWasabi/Wallets/Exchange/ExchangeRate.cs
- WalletWasabi/Wallets/Exchange/ExchangeRateProvider.cs
- WalletWasabi/Wallets/Exchange/ExchangeRateUpdater.cs
- WalletWasabi/WebClients/UserAgent.cs
Allow users to select the USD/BTC exchange rate providers instead of using the one provided by the Wasabi backend. This is an step forward in our goal to remove the need for a central server.
> Use exchange rate provider selected by user

- WalletWasabi.Fluent/Converters/ScriptTypeConverters.cs
- WalletWasabi.Fluent/Models/Wallets/ScriptType.cs
- WalletWasabi.Fluent/Models/Wallets/WalletModel.cs
- WalletWasabi.Fluent/Models/Wallets/WalletSettingsModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Settings/WalletSettingsViewModel.cs
- WalletWasabi.Fluent/ViewModels/Wallets/WalletViewModel.cs
- WalletWasabi.Fluent/Views/Wallets/Settings/WalletGeneralSettingsView.axaml
- WalletWasabi.Fluent/Views/Wallets/WalletView.axaml
- WalletWasabi.Tests/UnitTests/ViewModels/ReceiveAddressViewModelTests.cs
- WalletWasabi.Tests/UnitTests/ViewModels/SuggestionLabelsViewModelTests.cs
- WalletWasabi/Blockchain/Keys/KeyManager.cs
- WalletWasabi/JsonConverters/ScriptPubKeyTypeJsonConverter.cs
- WalletWasabi/JsonConverters/SendWorkflowJsonConverter.cs
- WalletWasabi/Models/SendWorkflow.cs
- WalletWasabi/WabiSabi/Models/Serialization/JsonSerializationOptions.cs
Fixes #13462 
This PR goes into the continuation of my goal for this week: Quality of life features
In the end, the Default Receive Script Type has to be wallet specific because some wallets don't have Taproot.
Default Send Workflow would be better as a global setting but I prefer for both settings to be at the same spot.
A wallet without Taproot won't see the Default Receive Script Type setting
A wallet that will never be able to send (Hardware or WatchOnly) cannot see Default Send Workflow
A wallet that cannot send now but might in the future (Balance = 0) can see Default Send Workflow
> Settings for Default Receive Script Type / Send Workflow

- WalletWasabi.Fluent/Models/Wallets/WalletRepository.cs
- WalletWasabi.Fluent/ViewModels/Wallets/CoinJoinStateViewModel.cs
- WalletWasabi/Blockchain/Keys/WalletGenerator.cs
Fixes #13328
I set new delay to 1-3 min.
I think it's good to keep it to give some time to disable. 
I kept the randomization because... IDK.
Auto-Cj to false by default is obvious to me now.
This PR also changes the text "Coinjoin has stopped" to "Coinjoin is stopped" because it fits better with usage.
> Reduce auto-start delay + disable it by default

- WalletWasabi.Fluent/Models/Wallets/WalletLoadWorkflow.cs
- WalletWasabi.Fluent/ViewModels/Wallets/LoadingViewModel.cs
- WalletWasabi.Fluent/Views/Wallets/LoadingView.axaml
https://github.com/user-attachments/assets/68da90be-9039-48e7-b003-ffd7bb7fde72
First I display how many filters are yet to be downloaded, no progress needed, it's clear that the number goes down
Then I display `current synchronized height / current tip`, along with an estimate of how much bitcoin history remains to dl Value can be:` Less than 1h`, `X hours` if less than 1 day, `X days` if less than 1 month, `X years` if more than 1 year. It's always the Ceiling so if 1 year and 10 minutes then it will show 2 years
The progress bar still shows the current progress, it didn't change
The only problem with this is that is shows that Wasabi download blocks really slowly :D
> Bitcoin-friendly progress in loading screen

- WalletWasabi.Daemon/Config.cs
- WalletWasabi.Daemon/PersistentConfig.cs
- WalletWasabi.Tests/UnitTests/Bases/ConfigManagerNgTests.cs
It is better for both providers (Exchange Rate and Fee Rate) to be on the same provider to avoid breaking more often. Estimations were the same when I checked.
> Change default FeeRateProvider to mempool.space

- WalletWasabi.Fluent/Views/Settings/BitcoinTabSettingsView.axaml
closes https://github.com/WalletWasabi/WalletWasabi/issues/13760
> update Dust Threshold text and tooltip

- WalletWasabi/Wallets/Wallet.cs
Fixes: #13754
> When an incoming transaction is detected in the mempool that causes the threshold to be met, input registration begins immediately before the tx is confirmed. This effectively bypasses the efficiency safeguard since only confirmed coins are eligible to register to the round.
> Plebstop include only confirmed coins amount

- WalletWasabi.Fluent/ViewModels/Wallets/CoinJoinStateViewModel.cs
- WalletWasabi.Fluent/Views/Wallets/Settings/WalletCoinJoinSettingsView.axaml
- WalletWasabi/Blockchain/Keys/KeyManager.cs
- WalletWasabi/WabiSabi/Client/CoinJoin/Manager/CoinJoinManager.cs
- WalletWasabi/WabiSabi/Client/CoinJoin/Manager/StatusChangedEvents/StatusChangedEventArgs.cs
- WalletWasabi/Wallets/IWallet.cs
- WalletWasabi/Wallets/Wallet.cs
Supersedes #13768
This PR makes 3 important changes:
- It unifies `IsUnderPlebStop` with the actual `coinCandidates` computation. That way, both are always strictly the same. To do so, `IsUnderPlebStop` is moved in `CoinjoinManager`. Also improves the code.
- It removes the requirement for backend synchronization to coinjoin. This change has a negative consequence: If some coins are immatures (Coinbase < 101 confirmations) and we are not connected to the backend then we will try to coinjoin those funds. I think this alignement of stars is so rare that it never happened to an actual user, and will never happen. So I believe it's better to let users coinjoin when backend is not connected. @lontivero are you ok with that?
- It displays a new message on the bottom line of the MusicBox if the …
> PlebStop rework

- WalletWasabi.Backend/StartupTask.cs
- WalletWasabi.Tests/UnitTests/BitcoinCore/IndexBuilderServiceTests.cs
- WalletWasabi.Tests/UnitTests/Blockchain/Blocks/SmartHeaderChainTests.cs
- WalletWasabi.Tests/UnitTests/MockRpcClient.cs
- WalletWasabi.Tests/UnitTests/SmartHeaderTests.cs
- WalletWasabi.Tests/UnitTests/Stores/BlockFilterSqliteStorageTests.cs
- WalletWasabi.Tests/UnitTests/Wallet/MockNode.cs
- WalletWasabi/Backend/Models/FilterModel.cs
- WalletWasabi/BitcoinRpc/IRPCClient.cs
- WalletWasabi/BitcoinRpc/RpcClientBase.cs
- WalletWasabi/Blockchain/BlockFilters/IndexBuilderService.cs
- WalletWasabi/Blockchain/BlockFilters/StartingFilters.cs
- WalletWasabi/Blockchain/Blocks/SmartHeader.cs
- WalletWasabi/Blockchain/Blocks/SmartHeaderChain.cs
- WalletWasabi/Blockchain/Keys/HdPubKeyInfo.cs
- WalletWasabi/Blockchain/Keys/KeyManager.cs
- WalletWasabi/Stores/BlockFilterSqliteStorage.cs
- WalletWasabi/Stores/IndexStore.cs
- WalletWasabi/Wallets/WalletFilterProcessor.cs
This is a subset of the changes in https://github.com/WalletWasabi/WalletWasabi/pull/13625 that doesn't change the index building service. This means that the filters are still being generated as before. However, the client can distinguish the legacy wasabi filters from the standard bip158 filters and used them to synchronize the wallet.
The idea is to allow the `WasabiSynchronizer` to fetch filters from the backend (legacy for the moment) or from a Bitcoin Node RPC (standard) because with this Wasabi could finally synchronize without a backend server. After that we can merge the missing parts from #13625 which allow the backend to also serve standard filters instead of building them.
> Allow client to use bip158-compatible filters

- WalletWasabi.Fluent/Models/Wallets/Amount.cs
- WalletWasabi.Fluent/Models/Wallets/AmountProvider.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Home/Tiles/BtcPriceTileViewModel.cs
- WalletWasabi.Fluent/Views/Wallets/Home/Tiles/BtcPriceTileView.axaml
- WalletWasabi.Tests/UnitTests/ViewModels/AmountTests.cs
Fix a bug introduced in https://github.com/WalletWasabi/WalletWasabi/pull/13793
> The exchange rate tile does not update after the logs say a new price has been fetched.
Ping @Kruwed could you confirm the fix works?
> Fix exchange rate tile update

- WalletWasabi.Tests/UnitTests/Data/Slip39TestVectors.json
- WalletWasabi.Tests/UnitTests/Wallets/ShamirMnemonicTests.cs
- WalletWasabi.Tests/WalletWasabi.Tests.csproj
- WalletWasabi/Serialization/Primitives.cs
- WalletWasabi/Wallets/ShamirSecretSharing/BitStream.cs
- WalletWasabi/Wallets/ShamirSecretSharing/Slip39.cs
- WalletWasabi/Wallets/ShamirSecretSharing/WordList.cs
This PR adds the cryptography library to support the SLIP39 (Shamir Secret Sharing).
There are tow main functions:
* `Generate` which takes the `seed`, and optional `passphrase` and the `n-of-m` group definition and creates `m` shares and,
* `Combine` which takes `n` shares and an option `passphrase` and "combine" them to recover the original seed.
```c#
var shares = Slip39.Generate(
group:  (2, 3),     // 2 of 3 shares are required to reconstruct the secret
seed: "ABCDEFGHIJKLMNOP"u8.ToArray(),
passphrase: "TREZOR");
var recoveredSecret = Slip39.Combine(shares, passphrase);
Assert.Equal(masterSecret, recoveredSecret);
```
> SLIP39 crypto

- WalletWasabi.Daemon/Global.cs
- WalletWasabi.Fluent/Converters/StatusConverters.cs
- WalletWasabi.Fluent/Models/Wallets/HealthMonitor.cs
- WalletWasabi.Fluent/Models/Wallets/WalletLoadWorkflow.cs
- WalletWasabi.Tests/IntegrationTests/P2pTests.cs
- WalletWasabi.Tests/RegressionTests/BuildTransactionReorgsTest.cs
- WalletWasabi.Tests/RegressionTests/BuildTransactionValidationsTest.cs
- WalletWasabi.Tests/RegressionTests/CancelTests.cs
- WalletWasabi.Tests/RegressionTests/FilterDownloaderTest.cs
- WalletWasabi.Tests/RegressionTests/MaxFeeTests.cs
- WalletWasabi.Tests/RegressionTests/ReceiveSpeedupTests.cs
- WalletWasabi.Tests/RegressionTests/ReorgTest.cs
- WalletWasabi.Tests/RegressionTests/ReplaceByFeeTxTest.cs
- WalletWasabi.Tests/RegressionTests/SelfSpendSpeedupTests.cs
- WalletWasabi.Tests/RegressionTests/SendSpeedupTests.cs
- WalletWasabi.Tests/RegressionTests/SendTests.cs
- WalletWasabi.Tests/RegressionTests/SpendUnconfirmedTxTests.cs
- WalletWasabi.Tests/RegressionTests/WalletTests.cs
- WalletWasabi.Tests/UnitTests/Mocks/MockRpcClient.cs
- WalletWasabi.Tests/UnitTests/Stores/BlockFilterSqliteStorageTests.cs
- WalletWasabi.Tests/UnitTests/Wallet/FilterProcessor/BlockFilterIteratorTests.cs
- WalletWasabi.Tests/UnitTests/Wallet/MockNode.cs
- WalletWasabi/Backend/Models/FilterModel.cs
- WalletWasabi/BitcoinRpc/RpcClientBase.cs
- WalletWasabi/BitcoinRpc/RpcMonitor.cs
- WalletWasabi/BitcoinRpc/RpcStatus.cs
- WalletWasabi/Extensions/RPCClientExtensions.cs
- WalletWasabi/Services/EventBus.cs
- WalletWasabi/Services/WasabiSynchronizer.cs
- WalletWasabi/Stores/IndexStore.cs
This PR creates a more modular architecture for `WasabiSynchronizer` by introducing a `CompactFilterProvider` abstraction, allowing different sources to supply compact filters to the client.
- Created a `ICompactFilterProvider` interface to decouple filter retrieval logic
- Implemented two concrete providers:
- `WebApiFilterProvider`: Fetches filters from the Wasabi backend (existing functionality)
- `BitcoinRpcFilterProvider`: Fetches filters directly from a Bitcoin Core node
- The client can now continue functioning without connecting to the Wasabi backend if a local Bitcoin node is available and properly configured
- Improved separation of concerns and testability
- Lays groundwork for future sources of filters like bitcoin p2p (bip 157) and standard compact filters from external …
> Synchronize using Bitcoin RPC

- WalletWasabi.Tests/UnitTests/WabiSabi/SerializationTests.cs
- WalletWasabi/Serialization/Primitives.cs
BtcPayServer coordinators serialize json fields in pascal case while Wasabi coordinators do it in camel.
Close https://github.com/WalletWasabi/WalletWasabi/issues/13854
> Ensure compatibility with BtcPayServer coordinators

- WalletWasabi/Blockchain/Keys/WalletGenerator.cs
BIP39 Wasabi wallets are created with 128bits entropy. SLIP39 Wasabi wallet must be 128 too.
> SLIP-39 Seed entropy reduced to 128 bits (20 words)

- WalletWasabi.Fluent/ViewModels/StatusIcon/StatusIconViewModel.cs
- WalletWasabi.Fluent/Views/StatusIcon/StatusIcon.axaml
As discussed with @turbolay, we should mention the fact that Wasabi won't receive new release notifications while Tor is disabled.
> Update Checker warning if Tor is disabled

- WalletWasabi.Daemon/Config/Config.cs
- WalletWasabi.Daemon/Config/PersistentConfig.cs
- WalletWasabi.Daemon/Config/PersistentConfigManager.cs
- WalletWasabi.Daemon/Config/Serialization.cs
- WalletWasabi.Daemon/Global.cs
- WalletWasabi.Daemon/WasabiApplication.cs
- WalletWasabi.Fluent/App.axaml.cs
- WalletWasabi.Fluent/Models/UI/ApplicationSettings.cs
- WalletWasabi.Fluent/Services.cs
- WalletWasabi.Fluent/UiConfig/UiConfig.cs
- WalletWasabi.Fluent/ViewModels/Settings/CoordinatorTabSettingsViewModel.cs
- WalletWasabi.Fluent/Views/Settings/BitcoinTabSettingsView.axaml
- WalletWasabi.Tests/UnitTests/Bases/PersistentConfigManagerTests.cs
- WalletWasabi.Tests/UnitTests/ViewModels/UiContext/NullApplicationSettings.cs
- WalletWasabi/Helpers/Constants.cs
- WalletWasabi/Helpers/ValueList.cs
The current config file has some properties that are network dependent and others that are not. Why? Because otherwise all the properties should triplicado `MainNetSomething`, `TestNetSomething` and `RegTestSomething`.
In other to make it easier to configure Wasabi with different settings for different networks, each network has its own configuration file.
> One config file per bitcoin network

- WalletWasabi.Daemon/Global.cs
using a hostname for the Bitcoin RPC connection currently does not work because 'DnsEndpoint.ToString()' returns a string in this format: 'AddressFamily/hostname:port' (result is: `Unspecified/bitcoind.startos:8332`), which is not a valid hostname+port.
NBitcoin has an extension method to get the correct string: ToEndpointString()
> fix: replace EndPoint.ToString() with 'ToEndpointString()'.

- WalletWasabi/Blockchain/Keys/KeyManager.cs
Make `ExcludedCoinsFromCoinJoin` field in wallets optional because it can be missed in older wallets.
> Make `ExcludedCoinsFromCoinJoin` field in wallets optional

- WalletWasabi.Fluent/Views/StatusIcon/StatusIcon.axaml
Fixes: https://github.com/WalletWasabi/WalletWasabi/issues/13929
This PR hides the backend status in the StatusIcon if we are connected to a full node. (backend is not used in this case)
> Hide backend status when connected to Node

- WalletWasabi.Tests/UnitTests/Tor/TorSettingsTests.cs
- WalletWasabi/Tor/TorSettings.cs
I have found that a huge problem of Wasabi with Tor is that at some point in time Wasabi makes too many circuit creation requests to the same entry guard which leads to be timed out for DoS protection by the entry guard.
This PR increases the pool of Entry Guards being Primarily used, from 1 to 3.
This leads to a huge stability increase of Wasabi, especially at start up.
Note that the max for this settings is 10 but it is advised not to use a huge pool of entry guards because it increases attack surface. However in our case this conservative is worth it.
> Increase Primary Guards used + Conflux throughput

- WalletWasabi/Wallets/P2PNodesManager.cs
This removes an unnecessary check and prevent disconnecting nodes when there are less than 5.
> Node disconnect

- WalletWasabi.Fluent/Converters/StatusConverters.cs
- WalletWasabi.Fluent/Helpers/TransactionFeeHelper.cs
- WalletWasabi.Fluent/Models/Wallets/HealthMonitor.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Send/CustomFeeRateDialogViewModel.cs
- WalletWasabi.Tests/UnitTests/AllFeeEstimateTests.cs
- WalletWasabi/Blockchain/Analysis/FeesEstimation/AllFeeEstimate.cs
- WalletWasabi/Blockchain/TransactionBuilding/FeeStrategy.cs
- WalletWasabi/Extensions/RPCClientExtensions.cs
- WalletWasabi/FeeRateEstimation/FeeRateEstimations.cs
- WalletWasabi/FeeRateEstimation/FeeRateProviders.cs
- WalletWasabi/Serialization/Backend.cs
- WalletWasabi/WebClients/BlockstreamInfo/BlockstreamInfoClient.cs
Before this PR Wasabi only supported integer values for fee rate estimations, this means that fee rates received from fee rate providers were rounded **up** to be converted from decimal to integer. For example, if Wasabi received 1.3s/vb it transformed to 2s/vb.
After this PR Wasabi supports more accurate estimations and do not rounds them.
> Support fee rates with decimal values

- WalletWasabi.Coordinator/Program.cs
- WalletWasabi.Coordinator/Startup.cs
- WalletWasabi.Coordinator/TorProcessManagerService.cs
- WalletWasabi.Daemon/Global.cs
- WalletWasabi/Discoverability/AnnouncerConfig.cs
- WalletWasabi/Serialization/Config.cs
- WalletWasabi/Tor/Control/TorControlClient.cs
- WalletWasabi/Tor/TorSettings.cs
- WalletWasabi/WabiSabi/Coordinator/WabiSabiConfig.cs
After this PR coordinators will be exposed as onion services by default. 
New coordinators' operators need to do nothing at all, the coordinator will generate a new private key and store it in the `Config.json`  file:
```json
"PublishAsOnionService": true,
"OnionServicePrivateKey": "ED25519-V3:U8bTYDyXRqL6kwFG7ErGnKQ8vrpyPMrRnGmW49oRdyC033rBqmX8DIm8JRP7q468SLFrbUExi5XhFuquEsspcg=="
```
Next it will display the onion service url in the log file, something like this:
```
TorProcessManagerService.StartAsync (39)        Coordinator server listening on http://i44n7q2hhps7lowgd3jcw2eagirbu4hivbm7472alhuxsogd7x3rp7vd.onion
```
The coordinator will also automatically change the nostr announcement data in the `Config.json` file to reflect the change in the coordinator's uri.
It is also important …
> Publish Coordinator as Onion Service

- WalletWasabi.Fluent/ViewModels/Wallets/Coins/CoinListItem.cs
- WalletWasabi.Fluent/ViewModels/Wallets/Settings/ExcludedCoinsViewModel.cs
- WalletWasabi.Fluent/Views/Wallets/Settings/ExcludedCoinsView.axaml
This shows the warning:
- When a coinjoin round is found
- When selection has changed
I didn't add a feature to catch if the selection was reverted to initial state
> Show warning to restart Coinjoin after ExcludedCoins change

- WalletWasabi.Fluent/Views/Wallets/Settings/WalletCoinJoinSettingsView.axaml
This fixes the description for the "Reduce Costs" coinjoin strategy, which was made obsolete by the removal of the coinjoin time preference setting.
I also improved the wording of other settings on this menu. "Enhance Privacy" is hard to describe (especially without using the word 'remix'), but the "at all costs" warning is too extreme since the anonymity score target of this setting has been decreased several times during the past.
> Update tooltip descriptions

- WalletWasabi.Daemon/Global.cs
- WalletWasabi.Fluent/ViewModels/Settings/ConnectionsSettingsTabViewModel.cs
- WalletWasabi.Fluent/Views/Settings/ConnectionsSettingsTabView.axaml
- WalletWasabi.Tests/IntegrationTests/ExternalApiTests.cs
- WalletWasabi/Wallets/Exchange/ExchangeRateProvider.cs
- WalletWasabi/Wallets/Exchange/ExchangeRateUpdater.cs
This PR makes the `ExchangeRateProvider` implement the exact same pattern than `FeeRateEstimationProvider` what makes easier to compose them to create a chain of providers.
> Redundant exchange rate providers fallback mechanism

- WalletWasabi/FeeRateEstimation/FeeRateProviders.cs
- WalletWasabi/Wallets/Exchange/ExchangeRateProvider.cs
Add log entries to know where the fee rate estimations and exchange rate come from.
```
2025-09-05 22:35:23.008 [11] INFO       FeeRateProviders.RpcAsync (52)  Fetched fee rate from RPC node: 20.048 Sat/B.
2025-09-05 22:35:27.116 [11] INFO       ExchangeRateProvider.GetExchangeRateAsync (83)  Fetched exchange rate from Blockstream: 110811.37.
```
> Add log entries about the fee and exchange rate providers
